### ISSUE TITLE
should be possible to use balance assertions/assignments when reading csv

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1000]
From apo on IRC: [balance assertions](https://hledger.org/journal.html#balance-assertions)/[balance assignments](https://hledger.org/journal.html#balance-assignments) are not [being applied](https://hledger.org/csv.html#csv-balance-assertionsassignments) when reading CSV. Also, it should let you omit the `amount` field assignment if there's a `balance` field assignment.
```
2018-10-15,100
2018-10-16,200
2018-10-17,300
```
```
fields date,bal
# Currently an amount field is required, but we can leave it blank.
# The following blank line is required to avoid a parsing bug.
amount 

balance EUR %bal
date-format %Y-%m-%d
description Assets Update
account1 assets
account2 income
```
```
$ hledger -f a.csv reg assets
2018/10/15 Assets Update           assets                             0             0
2018/10/16 Assets Update           assets                             0             0
2018/10/17 Assets Update           assets                             0             0
```
```
$ hledger -f a.csv print -x
2018/10/15 Assets Update
    assets     = EUR 100
    income

2018/10/16 Assets Update
    assets     = EUR 200
    income

2018/10/17 Assets Update
    assets     = EUR 300
    income

```
We should see:
```
$ hledger -f a.csv print -x
2018/10/15 Assets Update
    assets         EUR 100 = EUR 100
    income        EUR -100

2018/10/16 Assets Update
    assets         EUR 100 = EUR 200
    income        EUR -100

2018/10/17 Assets Update
    assets         EUR 100 = EUR 300
    income        EUR -100

```
You can work around by parsing a second time:
```
$ hledger -f a.csv print | hledger -f- print -x
```

**Comment by simonmichael** [comment]
Related (tested with 61e8ccb):

- `currency` should not add a currency symbol when the amount field is empty

- amount*/balance* rule validation should be more robust, eg these malformed rules:
       ```
       amount-in %3
       balance %4
       ```
       give the following error:
       ```
       hledger: found values for amount and for amount-in/amount-out
       please use either amount or amount-in/amount-out
       ```
       which should be more precise, and possibly should reuse the existing
       ```
       Please specify (as a top level CSV rule) either the amount field,
       both the amount-in and amount-out fields, or the balance field. Eg:
       amount %2
       ```

**Comment by simonmichael** [comment]
@adept: this is really #1095 followup, but I'll post here: this issue
(CSV rules that set balance assignments) provides an example of how
not fully processing the CSV-derived journal is problematic,
potentially generating false reports. See:

```csv
# a.csv
2018-10-15,100
2018-10-16,200
2018-10-17,300
```

```csv.rules
# a.csv.rules
fields date, balance
```

```shell
~/src/hledger$ hledger -f a.csv print -x
2018/10/15
    expenses:unknown     = 100
    expenses:unknown

2018/10/16
    expenses:unknown     = 200
    expenses:unknown

2018/10/17
    expenses:unknown     = 300
    expenses:unknown

$ hledger -f a.csv bal -E
  expenses:unknown
--------------------

```
The output is a valid journal, but -x would normally show the amounts;
we can see it infers no amounts at all, and guesses some wrong account names,
and the balance report shows no amounts. I guess we'd call this valid 
journal output, but malformed transactions internally.

To work around, after converting from CSV you have to pipe it through
hledger again:

```shell
~/src/hledger$ hledger -f a.csv print -x | hledger -f- print -x
2018/10/15
    expenses:unknown             100 = 100
    expenses:unknown            -100

2018/10/16
    expenses:unknown             200 = 200
    expenses:unknown            -200

2018/10/17
    expenses:unknown             300 = 300
    expenses:unknown            -300

```
but the balance report is still no good, because of the account names:
```shell
~/src/hledger$ hledger -f a.csv print -x | hledger -f- bal -E
                   0  expenses:unknown
--------------------
                   0
```
I think we should look into finalising the journal as part of reading csv, like the other readers. I'm not sure if we did that before, but now the new flexibility makes it more visible.

**Comment by simonmichael** [comment]
The csv reader now finalises the journal like the other readers, so it now should report any problems with the generated entries. 

It never checks balance assertions, assuming that CSV data is usually partial and while you may want to generate balance assertions you don't want to check them just yet.

Now the above example gives the expected:
```
~/src/hledger$ hledger -f a.csv print -x
2018/10/15
    expenses:unknown             100 = 100
    expenses:unknown            -100

2018/10/16
    expenses:unknown             200 = 200
    expenses:unknown            -200

2018/10/17
    expenses:unknown             300 = 300
    expenses:unknown            -300

~/src/hledger$ hledger -f a.csv bal -E
                   0  expenses:unknown
--------------------
                   0
```
The account name still needs fixing.

**Comment by Xitian9** [comment]
Given that there are now two types of balance assertions (excluding and including subaccounts), would it make sense to specify which kind is used here? Maybe with a new csv tag e.g. `balanceN-sub`?

The use case is that I occasionally manually break funds into a subaccount (for example, as provisions for future spending: assets:chequing -> assets:chequing:provisions). The csv I import from knows nothing of this, so asserting the balance in assets:chequing would miss the money moved into assets:chequing:provisions.

**Comment by simonmichael** [comment]
Argh.. maybe, @Xitian9. Please open as a new issue.

**Comment by simonmichael** [comment]
Well, I replied by reflex. Maybe this issue is fine, never mind.

**Comment by simonmichael** [comment]
As an alternative to complicating the rules further, maybe balance assertions generated from CSV should always be inclusive (`=*`) ? Pro: probably what you want for CSV data. Con: less compatible, such transactions couldn't be read by Ledger users.

**Comment by Xitian9** [comment]
I agree that inclusive seems like the more sensible default, and would avoid a lot of ugly complication. 

Another option is to include a switch, either in the executable call or in the rules file, which determines which type of assertion is used. It could be on by default, but could be unset for the old behaviour.

**Comment by simonmichael** [comment]
I kind of like that idea: `assertion-type: =|==|=*|==*`. Analogous to `date-format`. But only if needed, maybe I'd first try supporting `=*` only. Let's see what @adept thinks.

**Comment by adept** [comment]
If we stick to single global `assertion-type`, this should be easy to do. I'll see if i can whip up something ..

**Comment by simonmichael** [comment]
All issues mentioned here were resolved I think.
