### ISSUE TITLE
The order of -M and -p options can produce different reports

### ISSUE THREAD

**Issue by amybailey** [simonmichael/hledger#1008]
Entering this issue from the discussion list so it doesn't get lost:
https://groups.google.com/d/topic/hledger/ehFfd6nQ1y4/discussion

On the forum, Simon states that "-p 2019 -M, -M -p 2019,  -p 'monthly in 2019' should all be equivalent"

These 2 examples show the different outputs when the order of -M and -p are reversed.

**Example 1: -p followed by -M**
```
$ hleger b fuel -p 2019 -M -A
             $460.49  expenses:auto:fuel
--------------------
             $460.49
```

**Example 2: -M followed by -p**
```
$ hledger b fuel -M -p 2019 -A
Balance changes in 2019q1:

                    ||     Jan      Feb      Mar  Average
====================++====================================
 expenses:auto:fuel || $164.37  $178.24  $117.88  $153.50
--------------------++------------------------------------
                    || $164.37  $178.24  $117.88  $153.50
```

**Comment by schoettl** [comment]
The three forms should be equivalent from the user perspective.

But the source code doc says:
> Get the report interval, if any, specified by the last of -p/--period, -D/--daily, -W/--weekly, -M/--monthly etc. options.

in ReportOptions.hs -> intervalFromRawOpts

I'm trying to find out how to fix it...

**Comment by simonmichael** [comment]
Thanks for the report.
