### ISSUE TITLE
Feature request: API for appending entries

### ISSUE THREAD

**Issue by MisterY** [simonmichael/hledger#1026]
A simpler version of #1005. Related to #940.

Thanks for pointing me out to JSON API endpoints in hledger-web. This seems the perfect solution for the synchronization of Cashier (PWA application for quick transaction entry) and the main book.
While I would not go as far as to insert transaction Ids, and hledger is smart enough to figure out the date sorting for transactions, a simple appending would work for me.
The idea is to have Cashier connect (via ngrok?) to one's own instance of hledger-web and post the entered entries, get a positive response, and clear out the store. 
(The /accounts command is useful for getting back the balance sheet)

I assume that some sort of append functionality already exist due to existence of hledger-add and other related entry tools. Hence it would be a matter of exposing it, unless it's already there but I've missed it?

**Comment by simonmichael** [comment]
It's there in the API - https://github.com/simonmichael/hledger/issues/316#issuecomment-465857830 - but I see I forgot to add it to the manual. Will do.

**Comment by MisterY** [comment]
Simon, you are always two steps ahead! :D
Adding to my to-do list for Cashier.
