### ISSUE TITLE
Allow Cross-Origin in hledger-web

### ISSUE THREAD

**Issue by MisterY** [simonmichael/hledger#1031]
I am at the point where I'm connecting to hledger-web JSON API endpoints from [Cashier](https://cashier.alensiljak.ml/). At the Sync page, I'm using `http://localhost:5000` server URL.
As expected, the error pops up:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://127.0.0.1:5000/accounts. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Would it be possible to add the CORS header, so that a PWA can connect to a locally-run server (on the same machine)?
I would suggest to use the '*' spec, allowing all sources to access the API:
`Access-Control-Allow-Origin: *`
Open to discussion.

Some references 
- [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin)

**Comment by MisterY** [comment]
Perhaps using a parameter to allow this specifically would be a good idea? The server startup can be scripted, anyway.

**Comment by simonmichael** [comment]
I guess this will be useful for others as well ? A startup option sounds ok, and/or allowing it when base url is localhost. PR welcome.

**Comment by MisterY** [comment]
> I guess this will be useful for others as well ?

Depends on what exactly you mean by that. Cashier, as a PWA, is intended to be a replacement for native applications. There is no compilation, no packages, no markets, etc. It can run on mobile devices as well as desktops. The browser support for PWAs is still in the early stages. On mobile devices, the whole app is cached offline and can run just like a native app.
The original intention was to copy/paste plain text or exchange text files with content: accounts, payees go into the app, transactions go out of the app.
Hledger-web opens up an option to actually synchronize with one's own data server. This may be run locally, but not necessarily. If your main device is your phone, then it is not going to be `localhost` until Haskell is ported to Termux (at least on Android; iOS users - good luck). A nice scenario would be that one comes home, where a hledger-web server is run on a desktop/server and the phone synchronizes over local network. 

Perhaps this clarifies a little to whom this option would be useful. Anyone who uses "Add to home screen" option in their browser, will have an offline app on their device. On desktops, unfortunately, this does not work (yet) and the application has to be used online. However, I see the desktop usage useful only for imediate data entry and synchronization/export.

For the synchronization option to work, CORS headers must be present in the server component (hledger-web), otherwise none of these clients, which are running in a browser, will be able to connect to the API endpoint. Native apps do not have this limitation but that's a small price to pay for the portability, speed of development, etc.

I will try to see if I can understand how web server works in Haskell although I'd rather spend that time on getting the Cashier to a useful state. I'm looking to replace a native Android app with this and am already tempted to start using it. Just need to add a quick export option, hopefully tonight.

**Comment by simonmichael** [comment]
Good info. In summary, I'm reading it as: hledger-web/hledger-api must provide CORS headers to be usable by other web apps. 

It will be a small code change, I would guess in Main.hs or Application.hs. Resources:

https://stackoverflow.com/questions/15774833/allowing-cross-origin-requests-in-yesod <https://stackoverflow.com/questions/15774833/allowing-cross-origin-requests-in-yesod>
http://hackage.haskell.org/package/wai-cors <http://hackage.haskell.org/package/wai-cors>
https://stackoverflow.com/questions/41399055/haskell-yesod-cors-problems-with-browsers-options-requests-when-doing-post-req <https://stackoverflow.com/questions/41399055/haskell-yesod-cors-problems-with-browsers-options-requests-when-doing-post-req>
https://github.com/simonmichael/hledger/blob/master/hledger-web/Hledger/Web/Main.hs#L70 <https://github.com/simonmichael/hledger/blob/master/hledger-web/Hledger/Web/Main.hs#L70>
https://github.com/simonmichael/hledger/blob/master/hledger-web/Hledger/Web/Application.hs <https://github.com/simonmichael/hledger/blob/master/hledger-web/Hledger/Web/Application.hs>

**Comment by MisterY** [comment]
Correct. I provided some expanded info as an overview. This really has the potential to uproot many typical desktop applications. Especially the type of which we're talking about here.
And, running both on desktop and mobile with a single codebase is a huge advantage in terms of effort required to maintain it. 
Thanks for the pointers. I'll see if I can run -web with the interpreter.

**Comment by MisterY** [comment]
Ref:
- [wai-cors](https://github.com/larskuhtz/wai-cors)

**Comment by MisterY** [comment]
Application.hs, line 42
`(logWare . simpleCors) <$> toWaiApp foundation`

Thanks, @simonmichael !

**Comment by agarciamontoro** [comment]
I managed to allow CORS with @MisterY suggestion. Is any PR adding these changes on the way? I am willing to add this change if nobody else is working on it.

**Comment by simonmichael** [comment]
Hi @agarciamontoro, that would be great. Noone else is working on it.
