### ISSUE TITLE
--aux-date flag documentation inconsistency: unsupported forms?

### ISSUE THREAD

**Issue by GPPassos** [simonmichael/hledger#1034]
According to the [docs](https://hledger.org/doc/1.14/journal.html):
```
--date2 flag is specified (--aux-date or --effective also work).
```

But invoking the CLI, these alternative formats do not work, only --date2.

**Comment by simonmichael** [comment]
You're right, they seem to have been dropped over the years. They should be working in master now. Thanks for the report.

**Comment by GPPassos** [comment]
Thank you!
