### ISSUE TITLE
Can't import csv with date format 20190630

### ISSUE THREAD

**Issue by boydkelly** [simonmichael/hledger#1036]
Hi,
I'm trying to import a csv file with the following error:

bkelly@fedora-28 cbt]$ hledger import --dry test.csv
hledger: error: could not parse "20190524" as a date using date format "%Y%m%d "
the CSV record is:  "'5273'", "DEBIT", "20190524", "-17.61", "[CW]BMO MASTERCARD                                                             "
the date rule is:   %3
the date-format is: %Y%m%d 

Any ideas?  I tried fiddling with the rules to no avail...  Thanks!

**Comment by simonmichael** [comment]
Hi, https://hledger.org/csv.html#date-format explains this. I'm guessing you need `date-format %Y%m%d`.

**Comment by boydkelly** [comment]
Yes thats exactly what I have!

**Comment by simonmichael** [comment]
Let's discuss on the #hledger IRC channel or mail list: https://hledger.org/#help

**Comment by simonmichael** [comment]
Hi @boydkelly, what's your status ? I am hoping we can resolve this quickly on IRC, which is better than the issue tracker for support requests like this. http://webchat.freenode.net/?channels=hledger  takes you there.

**Comment by MichaelVessia** [comment]
@boydkelly I think I have seen this one myself. Your date appears to be surrounded by quotes.  By pre-processing my csv to remove quotes, I was able to move past a similar issue.

**Comment by adept** [comment]
I can't reproduce this on hledger 1.15, with or without quotes. Close?

**Comment by simonmichael** [comment]
I can't either, yes please do. @boydkelly if you see this please try again and show your hledger version, csv and rules if it's still failing.
