### ISSUE TITLE
assertion amount not reformatted according to commodity format by print -x

### ISSUE THREAD

**Issue by bkhl** [simonmichael/hledger#1042]
# Background

I'm trying to import some CSV:s in a couple of currencies. Since I can define currency in the CSV import rules file, but not the currency format, I then want to run `print -x` on the output, after including it in a journal that has some commodity formatting configuration.

# Issue

```
commodity kr
    format 1 000,00 kr

2019/01/01 * Opening balance
    assets:SE:Swedbank:savings        kr 1195,10 = kr1195,10
    equity:opening balances
```

Expected result of running `hledger -f $f print -x` on a file with the above content:

```
2019/01/01 * Opening balance
    assets:SE:Swedbank:savings     1 195,10 kr = 1 195,10 kr
    equity:opening balances       -1 195,10 kr
```

Actual result:

```
2019/01/01 * Opening balance
    assets:SE:Swedbank:savings     1 195,10 kr = kr1195,10
    equity:opening balances       -1 195,10 kr
```

It seems that the formatting according to the currency format is done for the transaction amount, but the balance is left in the original formatting.

**Comment by simonmichael** [comment]
Thanks for the report, this should fix it.
