### ISSUE TITLE
Number of spaces used before comment separator in print should be configurable

### ISSUE THREAD

**Issue by alerque** [simonmichael/hledger#1047]
By default `ledger` outputs comments with 2 spaces before the separator `;`

```ledger
2019/06/11 (TXNID) Office Building Complex
    Expenses:Building:Dues                 ₺1.020,00  ; date: 2019/04/01
    Expenses:Building:Dues                 ₺1.020,00  ; date: 2019/05/01
    Expenses:Building:Dues                 ₺1.020,00  ; date: 2019/06/01
    Expenses:Fees:Banking                      ₺6,75  ; payee: Bank Name
    Assets:Bankaccount                    ₺-3.066,75
```
On the other hand `hledger` uses four:
```ledger
2019/06/11 (TXNID) Office Building Complex
    Expenses:Building:Dues                 ₺1.020,00    ; date: 2019/04/01
    Expenses:Building:Dues                 ₺1.020,00    ; date: 2019/05/01
    Expenses:Building:Dues                 ₺1.020,00    ; date: 2019/06/01
    Expenses:Fees:Banking                      ₺6,75    ; payee: Bank Name
    Assets:Bankaccount                    ₺-3.066,75
```

I find the four spaces somewhat excessive (and in more verbose examples such as with tags the extra space can cause unnecessary wrapping or scrolling) and would like to configure it to output 2 instead. I don't see any option to configure this preference.

Note `ledger` requires at least one space to parse comments, `hledger` doesn't need any at all, so this isn't a parsing issue, it is just a preferred output format issue.

**Comment by simonmichael** [comment]
I'd be fine with this. Two spaces is how I write them in the journal. This must (surely) be quite an easy change in (probably) hledger-lib:Hledger.Data.Transaction.hs and could be done before #1045 wrecks everything. Would you be interested in having a go ?

**Comment by simonmichael** [comment]
Probably the four spaces was to try and separate them clearly from the amount/commodity/price area, which can get really noisy. In ledger-mode this is less of a problem because of colour highlighting. Probably adding some colour to print output would help likewise (separate issue).

**Comment by alerque** [comment]
I'm not sure how easy this one is, at least for my weak sauce Haskell skills. I had a look at the file you referred to, and it looks like the four space thing is a side effect of a shortcut taken while programming it originally. It seems like all comments are being treated equally whether appended to a posting or on their own line in the posting sections. As such the posting line indent is being applied to all comments before the comment marker, then either output as their own line or appended to the previous line.

This needs to be split up to handle a different prefix for the case of line indents vs. line->comment separating  spaces.
