### ISSUE TITLE
-A / --average could be using a different interval than the report interval (-p / --monthly / --quarterly / etc)

### ISSUE THREAD

**Issue by lestephane** [simonmichael/hledger#1049]
## Background

I'm playing with the budget capabilities of hledger, and as suggested in the [manual](https://hledger.org/manual.html#budget-report), I want to

_"
take average monthly expenses in the common expense categories
to construct a minimal monthly budget
"_

In order to determine the average monthly expenses, I want to use hledger as well, since there
is an `-A / --average` command-line argument to the `balance` command.

After fiddling for a while until I found the right incantation, I came up with something that worked for me:

```bash
$ hledger bal \
        --flat --drop 3 \
        --average \
        --period "quarterly from 2018-04-01" \
        'Personal:Expenses:Utilities:(Internet|Water|Telephone\(Prepaid\))'
Balance changes in 2018/04/01-2019/06/30:

                    ||      2018q2        2018q3        2018q4        2019q1       2019q2       Average 
====================++==================================================================================
 Internet           ||           0   90,8500 EUR   84,1500 EUR   56,6000 EUR  56,6000 EUR   57,6400 EUR 
 Telephone(Prepaid) || 30,0000 EUR   55,0000 EUR   30,0000 EUR   30,0000 EUR   8,0000 EUR   30,6000 EUR 
 Water              ||           0             0   55,8900 EUR   21,5600 EUR            0   15,4900 EUR 
--------------------++----------------------------------------------------------------------------------
                    || 30,0000 EUR  145,8500 EUR  170,0400 EUR  108,1600 EUR  64,6000 EUR  103,7300 EUR 
```

If I divide the Average by 3 in each case, I end up with what I wanted (the monthly average expense).

## Problem

As you can see in the output above, I use quarterly intervals.

The reason i did it this way is because I need the output to fit in my terminal. Using a monthly report interval yields garbled output as there are too many data points to fit on one line.

Similarly, as time goes on, and the range of dates over which I want to calculate average expenses no longer fits with `quarterly`, I may decide to move onto `yearly`. You get the idea.

But, for the Average, what I _really_ want is the average **per month** (at least in this use case).

And I need to be able to look at the data points and the average side-by-side. I'm a visual guy.

So:
- the report interval  is `quarterly`, then `yearly` when `quarterly` won't fit, etc... (for display)
- the average interval is `monthly` (for budgets)

## Suggested solution

- An optional specification of the 'average period' using in the -A/--average command-line argument
```text
-A --average(=AVGINTERVAL) show a row average column.
        By default the average interval is the same as the report interval.
        When AVGINTERVAL is specified, it overrides the default
        AVGINTERVAL is a [report interval](https://hledger.org/manual.html#report-intervals)
```
- In the report output, the `Average` column heading becomes `Average(_AVGPERIOD_)`, when _AVGPERIOD_ differs from report interval

## Caveats

At first glance, it may seem as if this wish is a duplicate of #1012. But I would argue that implementing the suggestion described here allows for experimentation and visual inspection using several different `-p PERIODEXPR` until the Average 'makes sense' for a monthly budget. What makes sense will be different from user to user. Just to give an example, My water bills arrive quite randomly, sometimes 6 months later. So my way of working around that is to keep increasing the -p to gain a more accurate budget over time, while the avg interval remains `monthly`.

If all you have is an average (with `--average-only`), without knowing what the data points look like (how the sausage was made, so to speak), then you have to generate the `bal` output without `--average-only`, then generate the `bal` output with `--average-only`. These outputs will show up one above the other in the terminal, making it difficult to compare these outputs _side-by-side_. This issue helps with that (sausage-making data points and average will be side-by-side).

**Comment by simonmichael** [comment]
Thanks for the clear proposal. As a practical matter, the flag would have to be more complicated, eg `--average-by=INTERVAL`, since *unfortunately* we don't currently have a way to parse flags with an optional argument.

So if I have it right you'd like to see:
```
$ hledger bal \
        --flat --drop 3 \
        --average-by=month \
        --period "quarterly from 2018-04-01" \
        'Personal:Expenses:Utilities:(Internet|Water|Telephone\(Prepaid\))'
Balance changes in 2018/04/01-2019/06/30:

                    ||      2018q2        2018q3        2018q4        2019q1       2019q2       Average (monthly)
====================++==================================================================================
 Internet           ||           0   90,8500 EUR   84,1500 EUR   56,6000 EUR  56,6000 EUR             19,2133 EUR 
 Telephone(Prepaid) || 30,0000 EUR   55,0000 EUR   30,0000 EUR   30,0000 EUR   8,0000 EUR             10,2000 EUR 
 Water              ||           0             0   55,8900 EUR   21,5600 EUR            0              5,1633 EUR 
--------------------++----------------------------------------------------------------------------------
                    || 30,0000 EUR  145,8500 EUR  170,0400 EUR  108,1600 EUR  64,6000 EUR            34,5766 EUR 
```

breaking the hitherto invariant that Average column always shows the average of the columns displayed.

**Comment by lestephane** [comment]
Correct!

**Comment by simonmichael** [comment]
How useful is this kind of mixed-interval report, really ? You can't really compare performance with the average, unless you mentally divide the column numbers.

**Comment by lestephane** [comment]
I'll use the existing hledger features and pipe the output to `less -S` for now
