### ISSUE TITLE
Aliases declared in ledger files processed bottom to top (which is counter-intuitive)

### ISSUE THREAD

**Issue by alerque** [simonmichael/hledger#1055]
Per the [manual](https://hledger.org/journal.html#multiple-aliases):

> Aliases are recursive - each alias sees the result of applying previous ones.

This appears to be true for normal alias, but not for regex ones. They don't match the output of previous ones, they match on the original string.

Note this is only true for alias directives, not alias options:

```sh
# This works
$ echo "2001/01/01 test\n  one 1" | hledger -f- --alias "/one/=two" --alias "/two/=three" print
2001/01/01 test
    three 1

# This fails
$ echo "alias /one/ = two\nalias /two/ = three\n2001/01/01 test\n  one 1" | hledger -f- print
2001/01/01 test
    two 1

# This should not match, but does
$ echo "alias /one/ = two\nalias /one/ = three\n2001/01/01 test\n  one 1" | hledger -f- print
2001/01/01 test
    three 1
```

**Comment by simonmichael** [comment]
"I'll just quickly fix this one..." 
What a rabbit hole. After much tweaking of tests and code and debugging, I think the original behaviour is by the doc. Cf: "alias directives, most recently seen first (recent directives take precedence over earlier ones".

**Comment by simonmichael** [comment]
I could still be confused. Let me know if you agree, or I'll look at it again with fresh eyes.

**Comment by alerque** [comment]
No offense, but I think you're still confused ;-)

The fix to this may be just to fix the documentation. While the feature would be nice to have (I noticed it didn't work specifically when I had a use case for it), but it's a relatively minor thing.

The bit of documentation you cited is different and potentially contradictory the bit I cited. I'll try to come up with a better example for why I think it's still wrong.

**Comment by alerque** [comment]
Okay I'm confused too! And results from trying to come up with a MWE explain why I was so confused trying to setup the multi stage import and categorize rules I was working on yesterday. Note this doesn't just apply to regex rules either.

The main issue I see is that the order is backwards from what is expected. The documentation you quoted that says "recently seen first" might be correct, but only if hledger is reading files upside down.

Consider this data entry:

```ledger
2001/01/01 Example
    FooOne               1
    Cash                -1
```

Lets try a two stage rewrite, fist Foo→Bar then Bar→Baz.

I would instinctively try this:
```ledger
alias FooOne = BarOne
alias BarOne = BazOne
```

Or with regex, something like this:
```ledger
alias /Foo/ = Bar
alias /Bar/ = Baz
```

Either way the transformation only works for the first stage:
```ledger
2001/01/01 Example
    BarOne               1
    Cash                -1
```

Instead I have to enter the results in the opposite order:
```ledger
alias BarOne = BazOne
alias FooOne = BarOne
```

Or the same goes for Regex style:
```ledger
alias /Bar/ = Baz
alias /Foo/ = Bar
```

Either way with the order of rules seemingly reversed, the result is now "correct" (meaning the desired final output):
```ledger
2001/01/01 Example
    BazOne               1
    Cash                -1
```

I guess I don't really care what order they are, but either the order should be reversed or the documentation should be a lot more explicit that aliases are applied in reverse order that they were declared in ledger files.

Note the order when applied as `--alias` from the command line is as expected, latter ones being applied after earlier ones.

**Comment by alerque** [comment]
As I squint and re-read I guess the documentation _is_ technically correct, it's just so counter-intuitive that it should be spelled out much  more directly to get the point through thick heads like mine. And the fact that the command line aliases are applied in a more intuitive order makes it extra confusing.

**Comment by simonmichael** [comment]
No argument that the documentation should spell this out in more detail, at minimum. 

I fell into the same trap as you: being used writing procedures from
top downward, when I wanted to create a (artificial) sequence of
aliases it was natural to first write the one I wanted applied first,
and so on.

hledger's alias directives are applied bottom up for a reason, which I think is a good one: to preserve their locality of effect. The directive closest to the transaction being parsed takes precedence. I think (a) this is normally more intuitive, and (b) it supports semantic stability - otherwise, aliases defined in one file could easily work differently based on position of file includes or order of -f options.

**Comment by simonmichael** [comment]
Oh, for the record: --debug=6 output shows which aliases are being applied in which order.

**Comment by simonmichael** [comment]
Latest doc: https://hledger.org/journal.html#combining-aliases 
So I think this can be closed ?

**Comment by simonmichael** [comment]
PS more doc edits for clarity and brevity welcome.
