### ISSUE TITLE
.hledger.journal file overwritten on -f path typo

### ISSUE THREAD

**Issue by klacansky** [simonmichael/hledger#1056]
On Windows, the following command will overwrite the file `Documents\.hledger.journal` with an empty file. I sometimes make the typo with extra period in the path and I have to restore from backup. Version tested 1.14.1.

```
C:\Users\klacansky>hledger -f Documents.\.hledger.journal add
Creating hledger journal file C:\Users\klacansky\Documents.\.hledger.journal.
The hledger journal file "C:\Users\klacansky\Documents.\.hledger.journal" was not found.
Please create it first, eg with "hledger add" or a text editor.
Or, specify an existing journal file with -f or LEDGER_FILE.
```

**Comment by simonmichael** [comment]
Wow, thanks for the report. Would you be interested in debugging further ? Help available in http://irc.hledger.org.

**Comment by klacansky** [comment]
On IRC, we determined the issue is the directory ending with a period '.', windows ignores it, but hledger does not, thus it will report the file does not exists, and proceed to create a new file '.hledger.journal'. However, when creating that file, windows removes the period at the end of the directory name, and thus overwrites the original file.

**Comment by alerque** [comment]
:clap::clap: _Windows! When will you learn?_

**Comment by simonmichael** [comment]
Ideas for resolution:

- mention this issue for windows users in docs
- on windows, check each part of the file path for a trailing period and warn or give an error
- report this issue to the appropriate upstream haskell lib (base ?) and do the warning/error there

**Comment by simonmichael** [comment]
More or less related:
- https://stackoverflow.com/questions/4075753/how-to-delete-a-folder-that-name-ended-with-a-dot
- https://stackoverflow.com/questions/11681207/how-to-create-a-filename-with-a-trailing-period-in-windows

**Comment by simonmichael** [comment]
> I recommend prioritizing it; I were not to keep backup, it would really be upsetting

**Comment by simonmichael** [comment]
...you're right. I have pushed a fix. It should also be highlighted in docs (somewhere) for users of older hledger versions. If someone wants to propagate this discussion to the upstream haskell lib, that might be a service to the community.

**Comment by simonmichael** [comment]
I've mentioned the issue in [add's documentation](https://hledger.org/hledger.html#add) (27c01e82). But I'm not sure this is enough. Is there somewhere else appropriate that users of older hledger might notice ?

**Comment by simonmichael** [comment]
I guess we could do this same path check for all commands (not just add and hledger-web add), which would make it more likely to be noticed before it actually causes trouble. But no.. this would require an up to date hledger version, which doesn't have the problem.

**Comment by simonmichael** [comment]
So mention in next release notes and release announcement I guess. Adding it to the FAQ (even though it isn't one) might not hurt.

**Comment by klacansky** [comment]
Thanks!
