### ISSUE TITLE
hledger-web.x86_64: E: missing-call-to-setgroups-before-setuid /usr/bin/hledger-web

### ISSUE THREAD

**Issue by juhp** [simonmichael/hledger#1057]
Recently we packaged hledger-web for Fedora.
Now I noticed an rpmlint error:
```
$ rpm -q hledger-web
hledger-web-1.10-1.fc30.x86_64
$ rpmlint -i hledger-web
hledger-web.x86_64: E: missing-call-to-setgroups-before-setuid /usr/bin/hledger-web

This executable is calling setuid and setgid without setgroups or initgroups.
There is a high probability this means it didn't relinquish all groups, and
this would be a potential security issue to be fixed. Seek POS36-C on the web
for details about the problem.
```

Do you have any ideas about this? (I could not find anything related to setuid/setgid in the source.)

**Comment by simonmichael** [comment]
That's a new one for me. #ghc points to process as a possible suspect, cf https://github.com/haskell/process/issues/83#issuecomment-507291908 ..

**Comment by simonmichael** [comment]
@juhp, bgamari has posted a possible fix for that issue, if you have time to try a build with this patched `process`.

**Comment by simonmichael** [comment]
Status: once https://github.com/haskell/process/pull/148 is released, make hledger-web depend on that.

**Comment by simonmichael** [comment]
I haven't added an explicit `process` bound to hledger-web, but I'm going to assume this is now fixed in practice.

**Comment by juhp** [comment]
Yes thank you - I just checked the last fedora build and the rpmlint error is indeed gone.
