### ISSUE TITLE
showing dev manuals by default on hledger.org can be confusing (Unknown flag: -X)

### ISSUE THREAD

**Issue by marcelino-m** [simonmichael/hledger#1064]
Run the command:
```shell
hledger bal -X \$
```
fail with error :

```shell
hledger: Unknown flag: -X (use -h to see usage)
```
Here the doc [-X flag](https://hledger.org/manual.html#x-market-value-in-specified-commodity)

Mi ledger version is **hledger 1.14.2**, and was instaled in this way:

```shell
stack install  hledger hledger-web hledger-ui
```
On **Debian GNU/Linux 10 (buster)**

**Comment by alerque** [comment]
You need to escape the dolor sign on the command line  because your shell is treating it as a the start of a variable name:

```sh
hledger bal -X \$
```

**Comment by simonmichael** [comment]
Quite right. More about this: https://hledger.org/manual.html#special-characters-in-arguments-and-queries

**Comment by simonmichael** [comment]
Oh.. and the -X flag is not yet released. It's in the current master branch.

**Comment by marcelino-m** [comment]
thanks for the quick response, Where I can find the documentation according to the version of hledger?.

**Comment by simonmichael** [comment]
@marcelino-m, at the top of the web manuals on hledger.org, click on the version you have, eg 1.14. By default it shows the latest manual for the unreleased master branch, currently.

**Comment by alerque** [comment]
@marcelino-m Check the top of the page, there are links to the documentation specific to each version. You're probably looking at the latest (dev) version docs now, try hitting the [`1.14` link](https://hledger.org/doc/1.14/manual.html) to get docs matching your version.

**Comment by alerque** [comment]
@simonmichael Jinx. But this is probably an issue worth fixing, the documentation site should probably default to the latest tagged stable version, not the dev version.

**Comment by marcelino-m** [comment]
I am soo stupid!!, thanks!.

I love hledger!, thanks

**Comment by simonmichael** [comment]
Good to hear @marcelino-m. Perhaps you're right about that @alerque. I was probably trying to encourage the power users to discover and use the latest features, otherwise it's very hard to get any testing.

**Comment by marcelino-m** [comment]
Or maybe highlight that you are watching the development version

**Comment by simonmichael** [comment]
I'll repurpose this issue for it.

**Comment by simonmichael** [comment]
Default links in hledger.org sidebar and "default version" manual urls like http://hledger.org/hledger.html were since made to show the latest released version.
