### ISSUE TITLE
Add JSON as an output format to all/most commands

### ISSUE THREAD

**Issue by alerque** [simonmichael/hledger#1069]
The `-O csv` output option for some commands is sometimes useful, but it actually leaves a lot to be desired as for as querying the data from any kind of GUI or other application. A companion `-O json` would be quite useful.

Setting up an instance of hledger-web to get access to an API is one option, but the same data would be a lot easier to get in many cases if it could just be requested on the command line.

**Comment by simonmichael** [comment]
JSON is easier only in some cases, but I agree, adding the `json` output format will be good. We have ToJSON instances in hledger-web/Hledger/Web/JSON.hs, which perhaps should move into hledger-lib; then it shouldn't be too hard to add this, handling any tricky cases like mutual references as hledger-web does. See also hledger-web/Hledger/Web/Handler/MiscR.hs.

**Comment by alerque** [comment]
This is a duplicate of #689.

**Comment by alerque** [comment]
I agree there are going to be some data sets or use cases where csv makes more sense. But for many others…
