### ISSUE TITLE
hledger-ui is not in current stackage

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1071]
hledger-ui (and hledger-iadd) has been [excluded](https://www.stackage.org/package/hledger-ui) from [stackage](https://www.stackage.org/) since nightly-2019-05-11 due to brick being excluded, due to data-clist being excluded since it does not build with QuickCheck-2.13.

https://github.com/commercialhaskell/stackage/issues/4444
https://github.com/commercialhaskell/stackage/issues/4542
https://github.com/sw17ch/data-clist/issues/16
https://github.com/sw17ch/data-clist/pull/19
https://github.com/sw17ch/data-clist/issues/20
https://github.com/commercialhaskell/stackage/pull/4732

[Waiting for: a stackage nightly containing 4732]

**Comment by Anachron** [comment]
Please push a new release and let us know so we can package it.

**Comment by simonmichael** [comment]
I'm curious how your packaging process works, ie what's blocking you right now.

I hope to release hledger 1.15 on 8/1.

**Comment by Anachron** [comment]
[Void Linux](https://voidlinux.org/) does only package releases, not a git-commit or similar.

**Comment by simonmichael** [comment]
Does Void Linux only package things in stackage ? 

The hledger-ui-1.14 release on Hackage builds fine with cabal, and builds with stack if you specify a couple of extra deps on the command line (data-clist etc., see the stack.yaml circa 1.14).

**Comment by Anachron** [comment]
I'm new to packaging haskell in Void Linux but I've not found any other build-style other than `haskell-stack`: https://github.com/void-linux/void-packages/tree/master/common/build-style

Not sure whether we want to add hackage since stackage was working well enough for now. Do you think it will take a longer time until stackage is fixed?

**Comment by simonmichael** [comment]
I think it will be just a couple of days until commercialhaskell/stackage#4732 is merged and a new stackage nightly snapshot is released. Then you could use that latest snapshot.

But if you can choose any snapshot, you could also use any of [these older ones](https://www.stackage.org/package/hledger-ui/snapshots) containing hledger-ui-1.14.2, eg nightly-2019-05-11.

Or if you want to avoid duplicated effort you could hold off a week or so and package 1.15 instead of 1.14. Thanks for working on this.

**Comment by Anachron** [comment]
I'll probably wait until `1.15` is released which should also be after the `stackage` fixes (hopefully), that way I only have to handle packing it once.

**Comment by simonmichael** [comment]
hledger-ui (and hledger-iadd) are back in stackage as of nightly-2019-07-30, closing this issue.
