### ISSUE TITLE
addons in bin/ need updating

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1072]
@agander writes on #809:
> @simonmichael, should bin/hledger-check.hs compile? As far as you know.
Or any others in bin/
I am looking a minimal executable with arguments so I can add in multiBalanceReportHtml* functions and gradually build up.
I have cobbled something together but I am stuck with the argument options.

Addons in [bin](https://github.com/simonmichael/hledger/tree/master/bin) (hledger-check, hledger-smooth, hledger-swap-dates) should run and compile, but currently do not.

**Comment by agander** [comment]
These 2 for bin/hledger-check.hs:

```
> stack stack exec ghc -- -Wall -Werror bin/hledger-check.hs
[1 of 1] Compiling Main             ( bin/hledger-check.hs, bin/hledger-check.o )

hledger-check.hs:240:14: error:
    Not in scope: ‘H.journalApplyAliases’
    Neither ‘Hledger.Data’, ‘Hledger.Query’,
            ‘Hledger.Read’ nor ‘Hledger.Utils.Parse’ exports ‘journalApplyAliases’.
    |
240 |            $ H.journalApplyAliases (aliases opts) j
    | 

bin/hledger-check.hs:357:53: error:
    Not in scope: ‘H.accountaliasp’
    Neither ‘Hledger.Data’, ‘Hledger.Query’,
            ‘Hledger.Read’ nor ‘Hledger.Utils.Parse’ exports ‘accountaliasp’.
    |
357 |                   <*> (many . fmap snd . popt (lift H.accountaliasp))
    |
```
1. Could this have had a name change? As I cant find mention of it.
Is there a way in git to search something that might now have a different name?
2. ```accountaliasp``` appears in ```hledger-lib/Hledger/Read/JournalReader.hs```, so I added it to the export statement having seen that this module is imported by ```hledger-lib/Read``` and recompiled hledger:lib (```stack build hledger-lib```).
But I still get the error.
Dont understand how ```JournalReader``` gets used in ```hledger-lib/Hledger/Read```

```readers = [
  JournalReader.reader
]```

**Comment by alerque** [comment]
You can use `git log -S <term>` (colloquially known as git pickax) to search for terms in patch sets so you can find what commits introduced (or removed) terms even if they are not in the _current_ code base.

**Comment by agander** [comment]
> You can use `git log -S <term>` (colloquially known as git pickax) to search for terms in patch sets so you can find what commits introduced (or removed) terms even if they are not in the _current_ code base.

Ooh, wow, thanks @alerque

**Comment by simonmichael** [comment]
Good tip! In magit it's `l = S journalApplyAliases <RET> l`. 

1. I see it was removed last year. I guess all alias processing is done during parsing now, so the call to journalApplyAliases is unnecessary.

2. Probably JournalReader's exports were tightened up since hledger-check was written. Depending on how you're running or building hledger-check, it may not see the hledger-lib package you just built. `stack install hledger-lib` might help.

**Comment by simonmichael** [comment]
Tip: for fast compilation feedback: `stack exec --  ghcid bin/hledger-check.hs`

**Comment by simonmichael** [comment]
@agander I hope I didn't step on your toes. There was some [weirdness](https://gitlab.haskell.org/ghc/ghc/issues/6132) here and I ended up fixing all to get to the bottom of it. All should run or compile cleanly now.

**Comment by agander** [comment]
> @agander I hope I didn't step on your toes.

No worries @simonmichael. I never would have got there anyway
