### ISSUE TITLE
Skip Footer Lines in CSV Import

### ISSUE THREAD

**Issue by rkelly** [simonmichael/hledger#1076]
TD Ameritrade adds an end-of-file message in their transaction download file. Here's an example:

```
DATE,TRANSACTION ID,DESCRIPTION,QUANTITY,SYMBOL,PRICE,COMMISSION,AMOUNT,NET CASH BALANCE,REG FEE,SHORT-TERM RDM FEE,FUND REDEMPTION FEE, DEFERRED SALES CHARGE
01/01/2019,99999999997,RECURRING ELECTRONIC FUNDING,,,,,999.00,999.00,,,,
..
01/03/2019,99999999999,CASH ALTERNATIVES PURCHASE,,,,,-999.00,0.00,,,,
***END OF FILE***
```

When processing this, hledger-csv errors out:
```
hledger: user error (CSV record ["***END OF FILE***"] has less than two fields)
```

The hledger-csv [Skip function](https://hledger.org/csv.html#skip) only handles headers.

Would be great if we could skip from the footer as well.

**Comment by simonmichael** [comment]
I think adding this to hledger sounds reasonable. What would you call it, `skipend` ?

I assume your footer is a fixed size. For cases where the number of lines can vary, perhaps we'd want something like an `end` directive (`if END OF FILE\n  end`).

**Comment by adept** [comment]
If one could write:
```
if REFEX
  skip 3
```
this would've solved it, right?

**Comment by simonmichael** [comment]
True, and that's something we want. I imagine some cases where there's no reliable REGEX though.

**Comment by simonmichael** [comment]
..but we could start with that, and see.. ?

**Comment by rkelly** [comment]
> I think adding this to hledger sounds reasonable. What would you call it, `skipend` ?
> 
> I assume your footer is a fixed size. For cases where the number of lines can vary, perhaps we'd want something like an `end` directive (`if END OF FILE\n end`).

This one does appear to be just one line, and the same text every time.

`skipend` seems OK. Or `skipfooter`. An `end` or `skip` conditional directive would be OK too.

This is the most problematic download file I've seen (having gotten several others to work fine with `hledger-csv`). Footers aren't even in the RFC 4180 spec. I will bring this up with the bank's tech support.

In the meantime, I'm preprocessing the file like this:
`$ head -n -1 transactions.csv | hledger --file=- --rules-file=transactions.csv.rules print`

**Comment by simonmichael** [comment]
Oops, no I believe this is now handled by #1095's conditional `skip` or `end` rules, so I think can be closed. Eg:
```
DATE,TRANSACTION ID,DESCRIPTION,QUANTITY,SYMBOL,PRICE,COMMISSION,AMOUNT,NET CASH BALANCE,REG FEE,SHORT-TERM RDM FEE,FUND REDEMPTION FEE, DEFERRED SALES CHARGE
01/01/2019,99999999997,RECURRING ELECTRONIC FUNDING,,,,,999.00,999.00,,,,
01/03/2019,99999999999,CASH ALTERNATIVES PURCHASE,,,,,-999.00,0.00,,,,
***END OF FILE***
```
```
skip 1
fields DATE,TRANSACTION_ID,DESCRIPTION,QUANTITY,SYMBOL,PRICE,COMMISSION,AMOUNT,NET_CASH_BALANCE,REG_FEE,SHORT-TERM_RDM_FEE,FUND_REDEMPTION_FEE,_DEFERRED_SALES_CHARGE
date-format  %m/%d/%Y
if END OF FILE
 end
```
```
~/src/hledger$ hledger -f a.csv print
2019/01/01 RECURRING ELECTRONIC FUNDING
    expenses:unknown          999.00
    income:unknown           -999.00

2019/01/03 CASH ALTERNATIVES PURCHASE
    expenses:unknown         -999.00
    expenses:unknown          999.00
```
