### ISSUE TITLE
hledger-lib-1.15 doctest suite failure

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#1082]
Citing from https://hydra.nixos.org/build/99669918:

~~~
Test suite doctests: RUNNING...
Hledger/Data/PeriodicTransaction.hs:77: failure in expression `_ptgen "monthly from 2017/1 to 2017/4"'
expected: 2017/01/01
              ; recur: monthly from 2017/1 to 2017/4
              a           $1.00
          
          2017/02/01
              ; recur: monthly from 2017/1 to 2017/4
              a           $1.00
          
          2017/03/01
              ; recur: monthly from 2017/1 to 2017/4
              a           $1.00
          
 but got: 2017/01/01
              ; generated-transaction:~ monthly from 2017/1 to 2017/4
              a           $1.00
          
          2017/02/01
              ; generated-transaction:~ monthly from 2017/1 to 2017/4
              a           $1.00
          
          2017/03/01
              ; generated-transaction:~ monthly from 2017/1 to 2017/4
              a           $1.00
          

Hledger/Data/TransactionModifier.hs:57: failure in expression `putStr $ showTransaction $ transactionModifierToFunction (TransactionModifier "" ["pong" `post` usd 2]) nulltransaction{tpostings=["ping" `post` usd 1]}'
expected: 0000/01/01
              ping           $1.00
              pong           $2.00
          
 but got: 0000/01/01
              ping           $1.00
              pong           $2.00  ; generated-posting:=
          

Examples: 189  Tried: 175  Errors: 0  Failures: 2
Loading and searching for doctests in 48 files, plus any files they import:
Test suite doctests: FAIL
~~~

**Comment by simonmichael** [comment]
Thanks for the report. Related: https://github.com/commercialhaskell/stackage/issues/4792. This one annoyed me, because yesterday I tested, found and fixed this in https://github.com/simonmichael/hledger/commit/095badd7f911453463c06b01213fb91eac0e5522. `make doctest` is still passing for me. I’m mystified, can anyone spot my error ?

**Comment by simonmichael** [comment]
I see the old source in the release tarball on hackage, http://hackage.haskell.org/package/hledger-lib-1.15/src/Hledger/Data/PeriodicTransaction.hs . I suppose I pushed those before merging a commit. Will fix soonish.

**Comment by simonmichael** [comment]
This should be resolved now by hledger[-lib]-1.15.

**Comment by simonmichael** [comment]
@peti, may I pick your brain - what’s a better way to find the new commit hash to use for the nix-env install command at https://hledger.org/download.html, when a new hledger lands in nixpkgs, than this: I searched for hledger on hydra, scrolled down and found the most recent builds, clicked into a few of them, guessed it’s fbf0d5 ?

**Comment by simonmichael** [comment]
With help from #nixos, I came up with some scripts that help a bit: https://gist.github.com/simonmichael/497a52ceb77bb52c4b47cf39f3a17109

**Comment by peti** [comment]
> I searched for hledger on hydra, scrolled down and found the most recent builds, clicked into a few of them, guessed it’s fbf0d5?

That is probably the best you can do. :-) I'd check https://hydra.nixos.org/jobset/nixpkgs/trunk to find a recent evaluation that is in reasonably good shape -- i.e. the number of broken builds is not higher than what appears to be the usual background noise, like https://hydra.nixos.org/eval/1540515. Then choose that evaluation and search for `hledger` to make sure that those packages in particular have compiled successfully: https://hydra.nixos.org/eval/1540515?filter=hledger&compare=1540478. This reveals that the `aarch64` builds are broken, unfortunately, but all other builds succeeded, so the underlying commit https://github.com/nixos/nixpkgs/commit/9dbda3eddf0be1e9c83877ae3929ab496a6688c6 is probably *okay* to use as a reference.

The problem with `aarch64` is that we cannot build `ghc` on that platform at the moment. The generated output is [too big](https://github.com/NixOS/nixpkgs/issues/66277). It's not clear yet when that will be resolved, but we're working on it.

**Comment by simonmichael** [comment]
Ok. Very helpful, thanks @peti.

**Comment by simonmichael** [comment]
PS I assume that was a typo and the underlying commit is 65000c, the “to” commit.
