### ISSUE TITLE
Non-deterministic failure to balance transaction

### ISSUE THREAD

**Issue by jblachly** [simonmichael/hledger#1098]
`hledger 1.15.2`
`Darwin jsbmbp13.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`

I had to write a CSV parser for transactions because reasons, and I picked this error up when importing transactions into my journal.

Take this transaction in isolation:

```
2019/07/01 * YOU BOUGHT
    assets:broker                 $-500.00
    assets:broker    22.056 XYZZY @ $22.67
```

22.056 * $22.67 = 500.00952 in actual fact, but qty is accounted for / reported by the broker only to 3 decimal places, while US dollars are reported only to two. The difference is < 1c. This balances and works fine.

HOWEVER, by adding another, UNRELATED transaction to the ledger, we can induce a failure to balance:
```
2019-09-01 *   YOU BOUGHT
    assets:broker    $-500.00
    assets:broker    22.056 XYZZY @ $22.67

2019-09-30 *   INTEREST EARNED CASH
    assets:florist    $1.13
    income:interest    $-1.13
```

This non-determinism is surprising and IMO dangerous.  What is going on behind the scenes? I could imagine how this happens if the triggering transaction were in the same account, but it needn't be: I changed the interest transaction to assets:florist to demonstrate it does not matter.

Clearly, if entering by hand I could just remove the `$-500.0` to make it auto-balance, but this is not feasible for large-scale CSV imports.

Thanks for hledger and thanks for insights into this problem.

**Comment by simonmichael** [comment]
Hi @jblachly. Sorry, emacs ate my first reply so here's a shorter one:

Actually that first transaction in isolation doesn't balance. (Are you sure you're showing everything ?) The reason is that hledger rounds 500.00952 to 500.01, not 500.00. 

If those are all numbers you got from your broker, they must be using a different rounding scheme - maybe banker's rounding ? https://en.wikipedia.org/wiki/Rounding#Round_half_to_even . If so you might need to do things a little differently as hledger doesn't currently support other rounding schemes.

One workaround would be to add a commodity directive reducing the number of decimal places in $'s display style. This also affects transaction balancing, allowing this one to succeed. Eg:

```
commodity $1000.

2019/07/01 * YOU BOUGHT
    assets:broker                 $-500.00
    assets:broker    22.056 XYZZY @ $22.67
```
```
$ hledger -f a.j print
2019/07/01 * YOU BOUGHT
    assets:broker                    $-500
    assets:broker    22.056 XYZZY @ $22.67
```

But that means not showing cents in reports.. and also you are converting from CSV, which might need a different workaround.

**Comment by simonmichael** [comment]
Eg, you could generate an entry using this syntax:
```
2019/07/01 * YOU BOUGHT
    assets:broker                   $-500.00
    assets:broker    22.056 XYZZY @@ $500.00
```
or just:
```
2019/07/01 * YOU BOUGHT
    assets:broker                 $-500.00
    assets:broker                    22.056 XYZZY
```

**Comment by jblachly** [comment]
Thanks, I will have my parser emit in a different format.

Still, I wanted to point out that the first transaction does balance, when in a journal all by itself. It is the addition of the second transaction that then triggers the issue.

Regarding the non-determinism, I made an error in my first post by adding an extra 0 to the amount when copying to github:

```
jsbmbp13:~/Documents/ledger/hledger/journals$ cat /tmp/wack.hledger
2019-09-01 *   YOU BOUGHT
    assets:broker    $-500.0
    assets:broker    22.056 XYZZY @ $22.67
jsbmbp13:~/Documents/ledger/hledger/journals$ hledger -f /tmp/wack.hledger bal
             $-500.0
        22.056 XYZZY  assets:broker
--------------------
             $-500.0
        22.056 XYZZY
```

So, it is the appearance of a subsequent $ denominated transaction (of any kind) bearing more significant digits that then triggers the unbalancing? A quick experiment seems to be that way.  Does this mean there is internal state representation of # digits in commodity quantity independent of `commodity` directive?

**Comment by simonmichael** [comment]
Ah, that explains it. Hledger infers decimal places from your data  by default, using the greatest number of places seen in the journal. (The journal manual has more details.) 

As I mentioned this also affects transaction balancing. Once you added an entry with two decimal places, the transaction balancing check became more precise, and hledger noticed your rounding discrepancy.

**Comment by jblachly** [comment]
Thanks and sorry for confusion.

As a side note, this is a major US financial firm.

I will use one of your suggested alternate notations; do you think either is advantageous in terms of hledger roadmap related to commodity lot tracking (i.e. of stock for FIFO purchases, cost basis accounting for taxes, etc.) ?

**Comment by simonmichael** [comment]
No problem. So, are they indeed using bankers rounding in their Csv I wonder ? That would suggest opening a wish issue to explore more rounding options. 

I think any of those other forms are fine for now - no clear implication for lot tracking yet. Generally the single @ form causes the most rounding/precision issues, so I tend to avoid it unless I really want to emphasize the unit price.
