### ISSUE TITLE
hledger-check fails to parse predicates

### ISSUE THREAD

**Issue by ShrykeWindgrace** [simonmichael/hledger#1108]
Hi!
`$ ./hledger-check.hs -D "0  ==  assets:subaccount"` fails with a parse error:
```
option -D: failed to parse input '0  ==  assets:subaccount': ParseErrorBundle {bundleErrors = TrivialError 24 (Just EndOfInput) (fromList [Tokens ('+' :| ""),Tokens ('-' :| ""),Label ('n' :| "umber")]) :| [], bundlePosState = PosState {pstateInput = "0  ==  assets:subaccount", pstateOffset = 0, pstateSourcePos = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 1}, pstateTabWidth = Pos 8, pstateLinePrefix = ""}}
```
Config: today's `git clone` of `hledger`, ubuntu-18.

Similar errors appear for predicates with inequalities, too. Replacing double quotes with single quotes does not help, either.

**Comment by bitwave** [comment]
The problem is, that it tries to parse the account as an amount, but does not backtrack and uses the account parser. I pretty printed the error using `P.errorBundlePretty` instead of `show` in the `readParsec'` function.

```
option -D: failed to parse input '0 == assets:subaccount': 1:23:
  |
1 | 0 == assets:subaccount
  |                       ^
unexpected end of input
expecting '+', '-', or number
```

**Comment by bitwave** [comment]
Probably the `wrap` function does not use `P.try` correctly.

**Comment by simonmichael** [comment]
@bitwave, thanks for looking at it. `make ghci` / `make ghcid` / `make watch` could be helpful if you'd like to try a fix..

**Comment by Xitian9** [comment]
I think #1686 resolves this too.
