### ISSUE TITLE
can't create a one-posting transaction from CSV

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1111]
A follow-on from #1095: we should be able to generate transactions with one posting from CSV, if they're valid. Eg:
```
2000/1/1
    (a)    1

2000/1/2
    a    0

2000/1/2
    a
```
But I haven't managed it. I think the special handling for amount gets in the way.

**Comment by adept** [comment]
Yeah, code for backwards compatibility with 1.15 will prevent this :(

Brainstorming:
- we either wait and drop backwards compatibility in the next version, and then this is supported
- we make backwards compatibility opt-in via top-level rules file statement
- we make backwards compatibility opt-out via top-level rules file statement
- we code special support to enable this for "(accounts)" only, and reconsider at a later time

**Comment by simonmichael** [comment]
I like your last idea actually - we could say "if you set the amount of only one posting, a second, balancing posting will be generated automatically. (Unless the amount is zero, or the account name is parenthesised indicating an [unbalanced posting].)"

**Comment by adept** [comment]
"Amount is zero" is a can of worms,, as we would have to explain why zeros are ignored in some cases, but not in all of them :(  (see #1112)

Parenthesised accounts would be easy to support though.

**Comment by simonmichael** [comment]
I was thinking we could rely on something like balanceTransaction to add the posting only if needed to balance. Maybe it's not so easy, but I hope we can do it eventually. This is documented as a limitation, so not super urgent.
