### ISSUE TITLE
csv rules: currencyN does not affect amount

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1113]
Post #1095: a rule like `currency1 $` should affect the amount generated by `amount`, as well as the amount generated by `amount1`.

**Comment by adept** [comment]
Yeah, i see. Current code tries to get a posting out of "non-numbered" fields, and then another one out of field set number1, and then tries to merge them.

I think a much better play would be to have a generalized notion of "field alias", where either field or its alias could be filled out. I will try to work on this soonish.

**Comment by simonmichael** [comment]
If it's not too much work.. "field aliases" is a complication we'd ideally not have, and it seemed like something we could drop in future. But I'm on the fence about that - for simple examples and intro docs and possible future auto-detection of fields based on headings, it's nice to be able just say "amount".

**Comment by simonmichael** [comment]
Oops, fixed already.
