### ISSUE TITLE
Add a command similar to ledger's `source` to check input syntax

### ISSUE THREAD

**Issue by alerque** [simonmichael/hledger#1115]
Ledger CLI has a `source` command that returns a successful exit code or a failing exit code plus an error message it cannot parse the input file properly. This is useful for automated checks. I bumped into this while [fixing the makeprg in the vim-ledger plugin](https://github.com/ledger/vim-ledger/issues/99) which helps _other plugins_ confirm whether the current file state is valid or not (buildable). This could also be used for something like a git pre-commit hook that warned when adding invalid syntax to a ledger.

A workaround is to use `print` and discard the output, but especially in the context of being used in somebody elses' pipeline that might be capturing error output this gets a  little bit complicated. A simple command that just validated input would be a useful utilitarian addition.

**Comment by DamienCassou** [comment]
I think `hledger check` is exactly what you want.
