### ISSUE TITLE
Accounting help

### ISSUE THREAD

**Issue by jbrodriguez** [simonmichael/hledger#1116]
Hi, I'm getting the following assertion in hledger

assertion details:
date:       2019/01/01
account:    liabilities:card
commodity:  $
calculated: -628.48
asserted:   -1259.75
difference: -631.27

I follow the structure from https://github.com/adept/full-fledged-hledger

The reason is:
- The 2018.journal closes with  1259.75 as the credit card balance, since that's the data on the Dec 2018 credit card statement
- The Jan 2019 credit card statement includes a payment in full (1259.75) and a mix of transactions occurring during Dec 2018 that add up to 628.48

This is probably not the right forum, but if anybody can lend a hand, I'd really appreciate it.

In general, any pointers for how to model credit cards payment from other banks via ACH would also help.

**Comment by simonmichael** [comment]
Hi there @jbrodriguez. When you have some end-of-year transactions that don't clear until the next year, you can move those amounts to a temporary account to avoid disturbing balance assertions. https://hledger.org/hledger.html#close -> "Transactions spanning the closing date can complicate matters" has an example of this. We can provide more help like this in #hledger or #plaintextaccounting channels or the hledger mail list. https://hledger.org/#help-feedback
