### ISSUE TITLE
csv rules file can't be parsed with a new line that has trailing spaces

### ISSUE THREAD

**Issue by FungusHumungus** [simonmichael/hledger#1120]
This rules file parses fine:

```
skip 3
fields date,_,description,amount
account1 assets:bank:current

if BRO EXET
  account2 income:hosting

if
TESCO
ASDA
BUTCHERS
  account2 expenses:food
```

But if you add an extra space to the blank line between the BRO EXET and TESCO rule it will no longer parse with the error:

```
hledger: user error (/Users/stephenwakely/Dropbox/work/moolah/natwest.csv.rules:12:1:
   |
12 | if BRO EXET
   | ^
unexpected 'i'
expecting end of input
)
```

The problem occurs on Master as well as 1.15.2.

**Comment by simonmichael** [comment]
This should be fixed now. Thanks for the report!

**Comment by FungusHumungus** [comment]
Fantastic, yes that works. Many thanks for the quick response!
