### ISSUE TITLE
"amount1" results in "unexpected 'a'"

### ISSUE THREAD

**Issue by harrisonthorne** [simonmichael/hledger#1129]
I'm trying to convert a csv file for cryptocurrency transactions. This includes conversions, buys, and sells.

hledger version and Arch Linux version:

```
~ $ hledger --version
hledger 1.15.2
~ $ uname -r
5.3.7-arch1-1-ARCH
```

Installed via:

```
yay -S hledger
```

**Minimal reproducible example**

crypto.csv.rules

```
skip 1

fields date, description, fromcurrency, fromamount, tocurrency, toamount, nativecurrency, nativeamount, nativeamountusd

account1        assets:cryptocom:unknown

amount1         %fromamount %fromcurrency
amount2         %toamount %tocurrency

date-format %F %X
```

When trying to `hledger -f crypto.csv print`, this error is returned:

```
hledger: user error (/home/harrisonthorne/Notebook/hledger/./csv/cryptocom.csv.rules:7:1:
  |
7 | amount1         %fromamount %fromcurrency
  | ^
unexpected 'a'
expecting end of input
)
```

I've read [this documentation](https://hledger.org/csv.html#posting-field-names) on the hledger website expecting the above rules to work without an error, but they don't. :(

**Comment by simonmichael** [comment]
Sorry @harrisonthorne .. I tricked you with the "This doc is for version: dev (latest)" at the top of the page. If you change to 1.15 docs it'll probably not mention amount1/amount2, those are brand new, in the master branch. It sounds like you might need that, build instructions can be found on the Download/Install page.

**Comment by simonmichael** [comment]
Also, the parse error messages for CSV rules are bad.

**Comment by harrisonthorne** [comment]
Ahh I see haha. Thanks for letting me know!
