### ISSUE TITLE
make use of P prices after the valuation date, as well as before ?

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1134]
Multiple people have not realised that you need a P directive dated on or before the earliest transaction's date if you want to see amounts fully converted with -V, -X or --value. 
(https://hledger.org/hledger.html#v-market-value). I believe this is the way it works in Ledger too.

I think folks getting started with -V are writing one P directive for today's date and expecting that to apply to older transactions too. Perhaps this is reasonable, and we could allow it, by using the closest P to the desired valuation date (before or after it). This would mean we sometimes give different results from Ledger.

**Comment by psb777** [comment]
I would prefer that the default remain as is, and that if this proposed feature (to use the closest future price should no prior price be available) is implemented that it must be enabled by a new command line option. My reasoning is as follows, a missing prior price may be not noticed should this feature become the default behaviour.

Another idea for implementing this is that sometimes a price is too old and shouldn't be used. Perhaps the new option I suggest might take date or duration args compatible with the -d option of the Unix date command. E.g.

--use-prices 'two weeks ago',now
--use-prices 2020/01/01,2020/01/07

**Comment by simonmichael** [comment]
Closing.
