### ISSUE TITLE
travis.hledger.org returns 404 error

### ISSUE THREAD

**Issue by chenrui333** [simonmichael/hledger#1141]
travis.hledger.org returns 404 error

![image](https://user-images.githubusercontent.com/1580956/69925894-370a1b00-1480-11ea-9dc7-185c993d35fc.png)

**Comment by chenrui333** [comment]
Same applies for `https://appveyor.hledger.org/`

**Comment by simonmichael** [comment]
I'd like to fix those shortcut URLs. Here's how I use them: I type "travis.hledger.org" or "appveyor.hledger.org" into the Firefox address bar and press enter. This works. I guess it uses http and not https. Is it a security risk ? Are you typing https or is your browser doing that/requiring that ? What browser version is it ?

**Comment by simonmichael** [comment]
It also worked for me in Safari 13 and Chrome 77.0.3865.90, on mac. 

I've now enabled SSL for those hledger.org urls, so http://travis.hledger.org redirects to https://travis.hledger.org which redirects to Travis build history, and likewise for appveyor.hledger.org. Let me know if you notice any difference.

**Comment by chenrui333** [comment]
Yeah, it works fo me now. 

But I am curious why do you prefer to host the subdomain rather the direct redirection? I would be still a handful of people like to click on the badge to check on the builds.

**Comment by simonmichael** [comment]
It's just an easy to remember shortcut, that you can type in at any time. Maybe you don't remember where the badge is, exactly..

**Comment by chenrui333** [comment]
I see, thanks for clarifying!
