### ISSUE TITLE
"could not balance this transaction" despite seemingly balanced transaction

### ISSUE THREAD

**Issue by lestephane** [simonmichael/hledger#1147]
```bash
$ hledger --version
hledger 1.15.2

$ cat <<EOF | hledger print -f -
2019/01/01 * Exchanged To BTC Savings
    Assets:EUR                 -10.00000000000000000000000000000 EUR
    Assets:XBT    0.00302198 XBT @ 3309.088743141913579838384106 EUR

EOF
hledger: "-" (lines 1-3)
could not balance this transaction (real postings are off by 0.00000000000000000000000000065 EUR)
2019/01/01 * Exchanged To BTC Savings
    Assets:EUR                 -10.00000000000000000000000000000 EUR
    Assets:XBT    0.00302198 XBT @ 3309.088743141913579838384106 EUR

$ echo "0.00302198 * 3309.088743141913579838384106" | bc
10.000000000000000000000000
```

Currently compiling 1.16 to see if the problem exists there.

**Comment by lestephane** [comment]
Same with 1.16

**Comment by simonmichael** [comment]
Interesting case, thanks for the report! GHCI agrees with bc when using floating point arithmetic, but hledger uses Decimal with gives a different answer, which I'm going to claim is more correct (though I'm not sure how to check it right this minute):
```
ghci> a = 0.00302198
ghci> b = 3309.088743141913579838384106
ghci> a * b
10.0
ghci> import Data.Decimal
ghci> Right a' = eitherFromRational a :: Either String Decimal
ghci> Right b' = eitherFromRational b :: Either String Decimal
ghci> a' * b'
10.00000000000000000000000000064988
```
Decimal says the unit price should be:
```
ghci> Right c = eitherFromRational 10 :: Either String Decimal
ghci> c / a'
3309.088743141913579838384105784948940760693320273463093733247738237844062502068180464463695987398990066115593087975433325170914433583279836398652539063792612790289809992124368791322245679984645828231821520989549897749157836914870382993931131245077730494576404
```
and hledger accepts this:
```
2019/01/01 * Exchanged To BTC Savings
    Assets:EUR                 -10.00000000000000000000000000000 EUR
    Assets:XBT    0.00302198 XBT @ 3309.088743141913579838384105784948940760693320273463093733247738237844062502068180464463695987398990066115593087975433325170914433583279836398652539063792612790289809992124368791322245679984645828231821520989549897749157836914870382993931131245077730494576404 EUR
```
It will accept fewer digits, for this example these seem to be the minimum required:
```
2019/01/01 * Exchanged To BTC Savings
    Assets:EUR                      -10.00000000000000000000000000000 EUR
    Assets:XBT    0.00302198 XBT @ 3309.088743141913579838384105784 EUR
```
Transaction balancing is done using the display precision, so if you specify a commodity style fewer digits will be required. Eg here this seems to be the minimum:
```
commodity 1.00000000 EUR

2019/01/01 * Exchanged To BTC Savings
    Assets:EUR                      -10.00000000000000000000000000000 EUR
    Assets:XBT    0.00302198 XBT @ 3309.088743 EUR
```
So I think we can say not a bug ?

**Comment by simonmichael** [comment]
PS in your example it checked to such high precision because you wrote the 10 EUR amount with so many zeroes. (The amount after the @ doesn't set the precision this way.) So something as coarse as this is also accepted:
```
2019/01/01 * Exchanged To BTC Savings
    Assets:EUR      -10 EUR
    Assets:XBT    0.003 XBT @ 3309 EUR
```

**Comment by simonmichael** [comment]
(3309 * 0.003 = 9.927, which rounded to the display precision of 0 = 10)

**Comment by lestephane** [comment]
Background: this is a transaction exported from `bean-report ... hledger`.

I need to be careful about modifying it or I'll simply kick the can down the road to the next problematic transaction. But I could add commodity directives once at the beginning of the export, or scrub the problematic cost.

My understanding:
There seems to be no way to represent the result of the division 10 / 0.00302198. It looks like an infinite decimal:

```bash
echo "scale=2000; 10/0.00302198" | bc
3309.088743141913579838384105784948940760693320273463093733247738237\
84406250206818046446369598739899006611559308797543332517091443358327\
98363986525390637926127902898099921243687913222456799846458282318215\
20989549897749157836914870382993931131245077730494576403549990403642\
64488845061846868609322364807179398937120695702817358155911025221874\
40022766530552816365429288082647800448712433570043481426084884744439\
07636715001422908159551022839330505165487528044527098127717589130305\
29652744227294687588931759971938927458156572842970502782943632982349\
32064408103296514205917974308234998246182966134785802685656423933977\
06139683254025506456032137869873394264687390386435383424112667853526\
49587356633730203376594153502008616867087141542961899152211464007041\
74084540599209789608137711037134593875538554192946346435118697013216\
50044010880283787450611850508606939820912117221159637059146652194918\
56332603127750680017736715663240656787933738807007326322477316196665\
76218241020787695484417501108544728952541049245858675437957895154832\
26229161013640063799230967776093819284045559533815577866167214872368\
44717701639322563352503987451935486005863705252847470863473616635450\
92952302794856352457660209531499215745967875366481578302966928967101\
03971568309518924678522028603763095718700984122992210405098643935433\
06044381498223019344932792407626787735193482418811507687013150318665\
24596456627773843638938709058299525476674233449592651175719230438321\
89491657787278539235865227433669316143720342292139590599540698482451\
90239511843228611704908702241576714604332258982521393258724412471293\
65515324389969490201788231556793890098544662770766186407587078670275\
77945585344707774373093137611764472299618131159041423172886650474192\
41689223621599084044235898318321100735279518726133197440088948305415\
65463702605576476349942752764743644895068795954969920383324840005559\
26908847841481412848529771871422047796477805941799747185620023957802\
50034745431802990092588303033110741963877987279862871362484199101251\
497362656271715894876868807867689
```

So beancount generated the @ cost using the rounded value `3309.088743141913579838384106 EUR`. It wasn't information I provided, it was computed.

The scale for XBT needs to remain at 8 digits after the comma, because one XBT (Bitcoin) can be divided into one hundred million satoshis, so following your advice to add a commodity directive, that would be:

```text
commodity 1.00000000 XBT
```

Having a larger scale than 2 digits for the amount makes no sense for EUR I think, so that would be:

```text
commodity 1000.00 EUR
```

If I add the commodity directives I get further:

```bash
$ cat <<EOF | hledger print -f -
> commodity 1000.00 EUR
> commodity 1.00000000 XBT
> 
> 2019/01/01 * Exchanged To BTC Savings
>     Assets:EUR                 -10.00000000000000000000000000000 EUR
>     Assets:XBT    0.00302198 XBT @ 3309.088743141913579838384106 EUR
> 
> EOF
2019/01/01 * Exchanged To BTC Savings
    Assets:EUR                                            -10.00 EUR
    Assets:XBT    0.00302198 XBT @ 3309.088743141913579838384106 EUR

```

If it was up to me I would keep all input numbers, avoid intermediate results (such as the @ cost computed by beancount) and push the cost computation to the very end.

Is this what is achieved by simply _removing_ the `@ ... EUR`?  There are only 2 legs in these currency exchange transactions of mine...

This seems to work:

```text
$ cat <<EOF | hledger print -f -         
2019/01/01 * Exchanged To BTC Savings
    Assets:EUR                 -10.00000000000000000000000000000 EUR
    Assets:XBT    0.00302198 XBT

EOF

2019/01/01 * Exchanged To BTC Savings
    Assets:EUR    -10.00000000000000000000000000000 EUR
    Assets:XBT                           0.00302198 XBT
```

The price info is still available both ways:

```bash
$ cat <<EOF | hledger prices --costs --inverted-costs -f -         
2019/01/01 * Exchanged To BTC Savings
    Assets:EUR                 -10.00000000000000000000000000000 EUR
    Assets:XBT    0.00302198 XBT

EOF

P 2019-01-01 EUR 0.0003021980000000000000000000000000000000000000000000000000000000 XBT
P 2019-01-01 XBT 3309.088743141913579838384105785 EUR
```

So there are two options:
- add commodity directives if either :
  - the transactions have 3 or more legs
  - the transactions have 2 legs, but removing the @ cost is not an option
- scrub the @ part if
  - the transactions have two legs, and @ can be thrown away

If prefer scrubbing the @ part because I'm not comfortable with the amount of magic happening as a side-effect of specifying commodity directives, and because the @ cost was computed by beancount, and therefore was already subject to rounding. I prefer the eventual rounding to be pushed to the very last command in the pipeline (hledger).

I still don't know whether what I reported is a defect though. Maybe I should mention it in the beancount issue tracker. I don't see why beancount uses scale 25 for the cost, but 30 for the EUR leg. The discrepancy happens between the 29th and 33th digits as you pointed out, so truncating the EUR leg precision to 25, or dropping extraneous zeroes on the EUR leg side would fix the problem.

**Comment by simonmichael** [comment]
Interesting. What magic ? It’s only a handy friendly commodity directive. Yes it would be fine to remove the transaction price (@) if you don’t need to see those. 

I think a cause of the trouble here is the beancount generated 10 euro amount. It has an unnatural number of zeroes, normally you would write just two there. That’s forcing  hledger to do a very precise comparison, necessitating the commodity directive workaround. Can you see what makes bean-report do that ?

**Comment by simonmichael** [comment]
PS is there online docs for bean-report hledger ?

**Comment by lestephane** [comment]
Not really, I discovered the export option through `--help` by chance

```text
$ bean-report --help
usage: bean-report [-h] [--version] [--help-reports [HELP_REPORTS]]
                   [--help-formats [HELP_FORMATS]]
                   [-f {text,csv,html,htmldiv,xls,ofx,beancount}] [-o OUTPUT]
                   [-t] [-q]
                   FILENAME.beancount
                   {balances,bal,trial,balsheet,income,journal,register,account,conversions,documents,holdings,cash,networth,equity,export_holdings,export_portfolio,pfexport,exportpf,commodities,lifetimes,prices,all_prices,pricedb,pricesdb,prices_db,tickers,symbols,check,validate,errors,print,accounts,current_events,latest_events,events,activity,updated,stats-types,stats-directives,stats-entries,stats-postings,ledger,hledger}
```

**Comment by simonmichael** [comment]
I'm inclined to close this.. or is it possible to describe briefly how hledger is not functioning according to spec or preferred UX ?

**Comment by lestephane** [comment]
Sure, let's close it, at least there's a record of the problem, someone later on might find add more info. I've already context switched to other things, and so the problem is no longer fresh in my mind.
