### ISSUE TITLE
`hledger-ui --forecast` should show future transactions by default

### ISSUE THREAD

**Issue by lestephane** [simonmichael/hledger#1149]
This is more of a usability issue than a bug, but when I do

```bash
hledger-ui -f ... --forecast
```

On a journal that only has recurring transactions, I'm faced with a blank screen,
until i press `F` (`future`), because hledger-ui shows `present` to start with.
`present` means that it shows transactions that occurred in, er, the past, up to the present.

I cannot think of a good reason to use `--forecast` and `present` together. 

To quote from the hledger doc 

> Periodic transaction rules describe transactions that recur. They allow hledger to generate temporary future transactions to help with forecasting

So when using `--forecast`, maybe `future` should be auto-selected in the ui.

**Comment by simonmichael** [comment]
In hledger-ui I'm trying to maximise the default usability, without creating confusion. So it

- enables --forecast by default
- has this additional F (future) toggle, off by default.

Your proposal means an explicit --forecast flag will turn F (future) mode on at startup. That sounds like a good idea, let's do it.

**Comment by simonmichael** [comment]
It seems this was done - closing.
