### ISSUE TITLE
With --require-balanced=true, Hledger should not allow multi-currency(or commodity) transactions, where the units don't zero out.

### ISSUE THREAD

**Issue by tphyahoo** [simonmichael/hledger#115]
Hledger allows transactions such as 

2009/1/1
    assets:cows  COW1   ; one cow at 100USD
    assets:usd     USD-100

where the units don't zero out, which violates the accounting equation.

Suggested fix:

The above transaction should be rejected by hledger, and instead users would be directed to enter multi-currency/commodity transactions as something like

2009/1/1
    assets:cow_account      COW1   ; one cow at 100USD
    equity:cow_account      -COW1
    assets:bank_account     USD-100
    equity:bank_account     USD+100

so that the units do zero out.

If it's important for backwards compatibility reasons that hledger allows transactions where the units don't zero out, perhaps there should be a flag that enables this mode.
  hledger --require-balanced-transactions would enable this mode, with the more permissive mode allowed by default
  or 
  hledger --allow-unbalanced-transactions would enable the current behavior, with the stricter behavior turned on by default.

My preference would be to do the second option, and have the stricter behavior be the default.

**Comment by lestephane** [comment]
> This is how I am currently using hledger for multi currency accounting

I know this is an old post, but can you share how you're doing today (hopefully with hledger, hopefully not manual)? I'm at a loss as to how to implement the 4.2 logic myself. I have some automation capability as I'm using hledger-flow, and a bunch of awk scripts, but i could use some pointers from someone who's already gone through this. cheers
