### ISSUE TITLE
Convert decimal separator for CSV imports

### ISSUE THREAD

**Issue by xnyhps** [simonmichael/hledger#1158]
I use a journal file which uses `.` for thousands and `,` for decimals:

```
commodity €1.000,00
```

One of the banks that I use uses `.` for the decimal separator for the CSV exports. This means that when I import these entries, the amounts are incorrect. Currently, I manually fix this by searching for the regex `\d\.\d\d^` and editing the `.`, but that is messy.

In the documentation for rules files, I did not see an option to convert the decimal separator (only the CSV field separator). It would be nice if that could also be supported.

This would probably mean defining how numbers are formatted (like `date-format` but for amounts) and how they should be formatted for the output (like a full `commodity` declaration, not the `currency` as it is in a rules file).

**Comment by simonmichael** [comment]
Thanks for the report. I would welcome reproducible examples, a specification or a PR for this.

**Comment by xnyhps** [comment]
I might be able to create a PR later, but for now a minimal example:

**hledger.journal**:
```
commodity €1.000,00
```

**import.rules**:
```
account1 assets:bank:checking

comment: %3, %14 %15 %16 %18

fields date,,,description,,,,,,,amount,,,,,,,,

date-format %d-%m-%Y

currency €
```

**import.csv**:
```
01-12-2019,NL12341234,,,,,,EUR,50.44,EUR,-42.79,01-12-2019,01-12-2019,1234,BEA,1234,'...','...',
```

Importing results in:
```
$ hledger import import.csv --rules-file import.rules -f hledger.journal
imported 1 new transactions
$ cat hledger.journal
commodity €1.000,00

2019/12/01    ; , 1234 BEA 1234 '...'
    assets:bank:checking         €-42.79
    expenses:unknown              €42.79
$ hledger -f hledger.journal bal
          €-4.279,00  assets:bank:checking
           €4.279,00  expenses:unknown
--------------------
                   0

**Comment by simonmichael** [comment]
Thanks! I see. When the import command is generating journal entries, it should format them according to any applicable commodity directives in the journal file it is importing to,

**Comment by simonmichael** [comment]
@xnyhps you can now use the https://hledger.org/csv.html#decimal-mark rule, in master.

**Comment by Flimm** [comment]
Here is the new link to the `decimal-mark` documentation: https://hledger.org/hledger.html#decimal-mark

Here is what it says now:

>     decimal-mark .
> 
> or:
> 
>     decimal-mark ,
> 
> hledger automatically accepts either period or comma as a decimal mark when parsing numbers (cf Amounts). However if any numbers in the CSV contain digit group marks, such as thousand-separating commas, you should declare the decimal mark explicitly with this rule, to avoid misparsed numbers.
