### ISSUE TITLE
vision/direction: hledger could accept a directory full of journal files, rather than a single journal file

### ISSUE THREAD

**Issue by tphyahoo** [simonmichael/hledger#116]
This is a wish/suggestion which emerged from conversation with Mike Klein / JavaSucksMan.

Note: this idea can be considered completely orthogonal to hledger as presently constituted. All it requires is translating the proposed new repo format to the file. Of course, if hledger community falls in love with the idea, the mainline code could use a directory rather than a file for state. 

Anyway, the idea: Rather than keep the state in a single file (~/.hledger.journal), hledger could keep state in a directory, which contains multiple files in the journal format. Possibly 1 file per transaction, but perhaps transaction batches could be allowed as well. To be determined.

The advantage of doing things this way is that it opens the door to using a version control system to add another layer of control / auditing functionality over who is doing what with the ledger. Down the line (waving hands here) you could even have journal entries linking binary files (also in repo) such as images of scanned receipts, or audio files with verbal notes like "Google Glass, Wake HLedger: Record found $20 on the sidewalk."

Integration of accounting assets as binary files is down the line and obviously a lot of work, but I think doing things repo style with multiple files could yield increased functionality with not that much work.

Mostly it just requires a function to translate a directory full of transactions into the ledger format at startup time. Repo integration would be orthogonal to hledger functionality. You would just put your directory in github and use the nice tools there.

Of course, you could also just keep a single file in a repo but
  a -- diffs will be messier
  b -- one file per transaction allows pessimistic rather than optimistic transactions if there are multiple people editing transactions. You would have an audit trail per file/transaction then.

**Comment by simonmichael** [comment]
Doing some bugtracker cleanup, closing  some old wishlist issues. These can be reopened if someone gets around to working on them.
