### ISSUE TITLE
command line option to override display precision in reports

### ISSUE THREAD

**Issue by Whil-** [simonmichael/hledger#1162]
Hi,

I've been searching the web and the documentation for some time now but cannot find any mention of rounding options in balance or register reports. At least in the balance report I think it can be valuable, but in register reports as well. The use case is to remove unnecessary clutter. For example a balance report for monthly expenses. I don't need all decimals in the report, even though all transactions in my ledger is written at that precision.

Have I missed something in the documentation? Or am I looking for something that still doesn't exist?

I've seen how commodity directives can modify the output precision but find modifying the global state of commodities in my ledger files is a bit hard to swallow when I'm simply wishing for some of my reports to be less cluttered and easier on the eye.

**Comment by simonmichael** [comment]
Commodity directives are the way - we assume there’s one standard precision you’d like to see always. 

But I agree it might be nice to override that with an easy command line flag once in a while..

**Comment by Whil-** [comment]
Ah ok, got it. A shame though ;-)

Your decision if you want to keep this wish as open or not. It's still open from my perspective. But I won't and can't "demand" it, as I'm not a paying customer. Thanks, and take care!

**Comment by Simaex** [comment]
I am experiencing connected issue. I have set precision to one decimal using journal-wide commodity directive but if I enter commodity value display precision in reports and hledger-web is changed according to number of decimals used in statment.
P 2020/1/31 EUR 1.1034
Also I have used the next format with the same result - values with unnecessary 4 decimals.
P  2020/1/31 EUR 1.1034$
P  2020/1/31 EUR $1.1034

P  2020/1/31 EUR 1.10337 results in 5 decimals in reports and hledger-web interface 

Please let me know: is it an intended behaviour or do I miss something obvious.

**Comment by simonmichael** [comment]
@Simaex this is not clear enough, would you mind opening as new issue with a reproducible example, or explain to me on #hledger. Thanks!

**Comment by simonmichael** [comment]
@Whil- I'm leaving this open as I think a command line flag to override the display precision (for all commodities, and maybe selected commodities) is a nice-to-have feature.

I don't quite understand "modifying the global state of commodities in my ledger files is a bit hard to swallow when I'm simply wishing for some of my reports to be less cluttered and easier on the eye.", could you explain more ? Why don't you set up your files to display the right number of decimal places always ?

**Comment by Whil-** [comment]
Hi again!

What I mean is that I might want the default one way, but for certain reports to  override the default. Having to modify the global config and then reset it after the report has been created isn't optimal.

**Comment by simonmichael** [comment]
Ah good, we're in agreement. I'll update this issue's title.

**Comment by simonmichael** [comment]
Related recent chat:

> or, allow overriding the each commodity's display style with a command line flag. Perhaps a flag that can do both of these
> `--output-number-format=AMT` # sets display format for AMT's commodity; if AMT has no commodity symbol, sets it for all commodities (slight clash with the no-symbol commodity)
> so then it'd be something like `hledger bal ... -O csv --output-number-format=1.0 | fooplot`

**Comment by simonmichael** [comment]
-c/--commodity now exists.

**Comment by MrPixelized** [comment]
`-c` does not override the precision in JSON reports where the total is calculated using the `-X` flag. Can this be considered a bug?

**Comment by simonmichael** [comment]
On Fri, Oct 11, 2024, at 03:02, Ischa Abraham wrote:
> `-c` does not override the precision in JSON reports where the total is calculated using the `-X` flag. Can this be considered a bug?Message ID: ***@***.***>
> 

This deserves some discussion, but I can't find your comment online - maybe deleted ? Consider posting it as a new issue, or we can discuss in chat.

**Comment by MrPixelized** [comment]
I deleted it because I realized that the JSON report format doesn't give you adjustable precision anyways. It's just the "raw data" - not taking into account your formatting and currency settings. I reckoned that might be expected behavior. I'll create a new issue.
