### ISSUE TITLE
close can generate unbalanced transactions

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1164]
I don't have a minimal repro yet, but when using multiple currencies `close` can generate journal entries that hledger can't parse because the transactions aren't exactly balanced. You can add an amountless "expenses:balancing error" posting as a quick workaround.

**Comment by simonmichael** [comment]
This has been fixed in master. It probably deserves a minor release, but only one other person has reported it so far, so I may hold it for the next major release on march 1.

**Comment by ggoodman** [comment]
@simonmichael I'm currently being hit with this. Would be lovely to have a blessed release that included this fix! ❤️
