### ISSUE TITLE
HTML Comment is rendered in docs

### ISSUE THREAD

**Issue by crispgm** [simonmichael/hledger#1168]
There are a few HTML comments rendered in docs, e.g.
- <https://hledger.org/journal.html#file-format> `
`
- <https://hledger.org/timedot.html> at the bottom paragraph

And the open issues section is totally messed up:
- <https://hledger.org/CONTRIBUTING.html#open-issues>

**Comment by simonmichael** [comment]
Thanks for the report. More issues with the new pandoc it seems. Working on it.

**Comment by simonmichael** [comment]
All fixed.
