### ISSUE TITLE
timeclock format can contain an error and is silently parsed wrong

### ISSUE THREAD

**Issue by schoettl** [simonmichael/hledger#1169]
I noticed a bug when using hledger with the timeclock format: If the input file has a slight error, the output is very surprising and in certain reports I get wrong results but it is not at all obvious that they are wrong.

Reproduce:

```
$ hledger --version
hledger 1.14.99

$ cat > test.timeclock
i 2020-01-05 11:00 a
i 2020-01-05 17:00 a
o 2020-01-05 22:00

$ hledger -f test.timeclock register
2020/01/05 11:00-17:00                       (a)                      6.00h         6.00h
2020/01/05 22:00-23:59                       ()                       2.00h         8.00h
2020/01/06 00:00-15:33                       ()                      15.56h        23.56h
```

**Comment by simonmichael** [comment]
Thanks for the report! Would you mind submitting it to the bug tracker (shortcut: http://bugs.hledger.org <http://bugs.hledger.org/>).

I think we currently assume a well-formed time log with alternating i and o. We'll need to decide what we should do in this situation, and get a pull request to fix it.

**Comment by alerque** [comment]
@simonmichael I'm going to go out on a limb and suggest that this report already _is_ in the issue tracker. :wink:

**Comment by simonmichael** [comment]
LOL, I misread mail headers. :)

**Comment by schoettl** [comment]
E.g. hledger already detects this kind of error in input:

```
hledger: clock-out time less than clock-in time in:
...
```

I would try me on this, it should not be too hard. But it can last a few weeks or even months until I'll get to this. If someone wants to fix it earlier, I'm thankful.
