### ISSUE TITLE
Precision display issue

### ISSUE THREAD

**Issue by Simaex** [simonmichael/hledger#1187]
I am experiencing issue. I have set precision to one decimal using journal-wide commodity directive 

; commodity-less amounts should be treated as dollars
; (and displayed with symbol on the left, thousands separators and one decimal place)
D $1,000.0
; commodity EXAMPLEAMOUNT
; display EUR amounts with the symbol on the right, space-separated,
; using period as decimal point, with oner decimal place, and
; separating thousands with comma.
commodity 1,000.0 EUR

This journal-wide directive is setting report and hledger-web display precision to one decimal as it was expected.
but if I enter commodity value in any of supported formats:
P 2020/1/31 EUR 1.1034
P 2020/1/31 EUR 1.1034$
P 2020/1/31 EUR $1.1034
 results in 4 decimals in reports and hledger-web interface that was not intended no convenient.
display precision in reports and hledger-web is changed according to number of decimals used in statement. For example if I change to 6 decimals
P 2020/1/31 EUR 1.103374
Reports and hledger-web interface get 6 decimals

Please let me know: is it an intended behaviour or do I miss something obvious.

Thank you for helping to make hledger better!

Things that can help us resolve your issue faster:

- A small reproducible example 

D $1,000.0
commodity 1,000.0 EUR

This is setting decimal precision to proper 1 digit
D $1,000.0
commodity 1,000.0 EUR
P 2020/1/31 EUR 1.1034

This will change display precision to 4 decimals resulting in unnecessary clatter in journal and reports.
- The output of hledger --version
1.14.2 
( I am using hledger version that is pre-compiled for UBUNTU and installed using app-get command)
- What platform you're on
UBUNTU 16.04LTS
- Any related docs that you found
[https://hledger.org/1.14/journal.html#declaring-commodities](url)

**Comment by Simaex** [comment]
Example journal with precision settings
D $1,000.0
commodity 1,000.0 EUR
2020/01/28 Correcting transactions From Cash to PE
    Assets:Cash     62
    Assets:PE             EUR -56
    Expenses:Trading      EUR 56
    Expenses:Trading

Example report with proper output precision:
alex@banach:/var/lib/hledger$ hledger bs -f test.journal
Balance Sheet 2020/01/28

             ||       2020/01/28
=============++==================
 Assets      ||
-------------++------------------
 Assets      || $62.0, -56.0 EUR
   Cash      ||            $62.0
   PE        ||        -56.0 EUR
-------------++------------------
             || $62.0, -56.0 EUR
=============++==================
 Liabilities ||
-------------++------------------
-------------++------------------
             ||
=============++==================
 Net:        || $62.0, -56.0 EUR

Example journal with commodity price
alex@banach:/var/lib/hledger$ cat test.journal
D $1,000.0
commodity 1,000.0 EUR
2020/01/28 Correcting transactions From Cash to PE 
    Assets:Cash     62
    Assets:PE             EUR -56
    Expenses:Trading      EUR 56
    Expenses:Trading

P 2020/1/31 EUR 1.1034


Example report with excessive precision due to commodity price
alex@banach:/var/lib/hledger$ hledger bs -f test.journal
Balance Sheet 2020/01/28

             ||          2020/01/28
=============++=====================
 Assets      ||
-------------++---------------------
 Assets      || $62.0000, -56.0 EUR
   Cash      ||            $62.0000
   PE        ||           -56.0 EUR
-------------++---------------------
             || $62.0000, -56.0 EUR
=============++=====================
 Liabilities ||
-------------++---------------------
-------------++---------------------
             ||
=============++=====================
 Net:        || $62.0000, -56.0 EUR

**Comment by simonmichael** [comment]
Thanks for the reproducible example. You can enclose things in triple-backtick lines for better formatting, eg:

    ```
    literal
    block
    ```

I think you have pointed out a bug here. The doc and example at https://hledger.org/journal.html#default-commodity implies that `D` sets the commodity's display format, including the number of decimal places. It does set most aspects of the display format, and it can increase the number of decimal places, but it can't limit them. (It has the same effect as an ordinary posting amount.) I'll fix the doc or the behaviour in some way. As a workaround, add a full `commodity` directive for the currency in question, eg:
```
D $1,000.0
commodity $1,000.0
commodity 1,000.0 EUR

2020/01/28 Correcting transactions From Cash to PE
    Assets:Cash                                   62
    Assets:PE                                EUR -56
    Expenses:Trading                          EUR 56
    Expenses:Trading

P 2020/1/31 EUR 1.1034
```
```
$ hledger print
2020-01-28 Correcting transactions From Cash to PE
    Assets:Cash                $62.0
    Assets:PE              -56.0 EUR
    Expenses:Trading        56.0 EUR
    Expenses:Trading

```

**Comment by Simaex** [comment]
Thanks a lot!
The workaround looks good to me.

**Comment by simonmichael** [comment]
Thanks for the report. https://hledger.org/journal.html#default-commodity is up to date.

**Comment by simonmichael** [comment]
(To be clear: I fixed `D` so that it can limit the number of decimal places, just like a `commodity` directive.)
