### ISSUE TITLE
Unintended change of default currency 

### ISSUE THREAD

**Issue by Simaex** [simonmichael/hledger#1197]
I am trying to set up multicurrency accounting using hledger. I have set automatic rate import for currencies of interest. For plain-text readability I have the next daily rates imported.
```
P 2019-12-31 EUR $1.1219906807454056
P 2019-12-31 UAH $0.04220368214465608
P 2019-12-31 $ UAH23.694615
P 2020-01-01 EUR $1.1218295694081564
P 2020-01-01 UAH $0.04197857975802119
P 2020-01-01 $ UAH23.821673

```
In main 2020.journal file i have set default currency to $ 
```
Y2020  ; set default year to 2020
D $1,000.0 ;commodity-less amounts should be treated as dollars
commodity 10,000. EUR
commodity 10,000. $
commodity 10,000. UAH
...
SOME TRANSACTIONS STUFF :-)
...
P 2020-01-01 EUR $1.1218295694081564
P 2020-01-01 UAH $0.04197857975802119
P 2020-01-01 $ UAH23.821673

```
But when I generated report it was converted to UAH currency, not to default $ that was intended.
I use the next call to generate report:
```
hledger -f /data/2020.journal bs --value=end -M --begin=thisyear --end=nextmonth --output-file=/data/report/balance.csv

```
This appears to be the result of the last market value that lists market value in reverse order (how much UAH for $, not how few $ to UAH). Is it an intended behavior?
PS I need the info for readability only so obvious workaround is to comment the market value directive that cause the unintended changes so please treat is as a low-priority.

**Comment by Simaex** [comment]
In the case the ```D``` directive is a bit confusing because it did not set default currency as I expected. At least I do not expect a commodity value directive to change default currency inferring it from what currency value is expressed. Thank you for pointing to the proper syntax of ```--value``` option. From now I will use explicit form ```--value=end,$```

**Comment by simonmichael** [comment]
I can't see your actual data, but `D` does set the default currency for currency-less amounts, and `commodity` does not, I believe.

**Comment by Simaex** [comment]
```
Y2020  ; set default year to 2020
D $1,000.0 ;commodity-less amounts should be treated as dollars
commodity 10,000. EUR
commodity 10,000. $
commodity 10,000. UAH
...
SOME TRANSACTIONS STUFF :-)
...
P 2020-01-01 EUR $1.1218295694081564
P 2020-01-01 UAH $0.04197857975802119
P 2020-01-01 $ UAH23.821673
```
This sample journal results in UAH default currency if a report is run using it. That's my point. The last ```P``` does the trick :-(. IMHO it make sense to choose default currency because usually it is the foundation accounting decision. I do not mean default for currency-less amounts but default in all use cases, for example for ```--value=OPTION[,COMMODITY]``` usage.

**Comment by simonmichael** [comment]
Could you show an actual reproducible example, then I can say what's what. :)
