### ISSUE TITLE
Inclusive balance assignments causing balance assertion failure

### ISSUE THREAD

**Issue by walling** [simonmichael/hledger#1207]
Hi, I'm trying to use the [assertions with subaccounts feature](https://hledger.org/journal.html#assertions-and-subaccounts), however it's not working for me. I'm pretty sure `hledger` is doing something wrong in this example.

**Example journal file:**

```hledger
; example.journal

2020-01-01 got paid
    assets:checking:available           2000.00 $
    revenues:job

2020-01-01 split available in budget
    assets:checking:budget:rent         1000.00 $
    assets:checking:budget:internet     100.00 $
    assets:checking:budget:food         400.00 $
    assets:checking:budget:shoes        500.00 $
    assets:checking:available

2020-01-02 buying new shoes
    expenses:shoes                      400.00 $
    assets:checking:budget:shoes

2020-01-03 rent
    expenses:rent                       1000.00 $
    assets:checking:budget:rent

2020-01-05 groceries
    expenses:food                       350.00 $
    assets:checking:budget:food

2020-01-25 internet
    expenses:internet                   100.00 $
    assets:checking:budget:internet

; NOTE: the following assertion breaks
2020-01-31 account balance check
    assets:checking                     ==* 150.00 $
```

**What happens:**

```
hledger: balance assertion: "example.journal" (line 32, column 41)
transaction:
2020/01/31 account balance check
    assets:checking     ==* 150.00 $

assertion details:
date:       2020/01/31
account:    assets:checking (and subs)
commodity:  $
calculated: 300.00
asserted:   150.00
difference: -150.00
```

**Expected result:** It accepts the file, because the assertion is correct.

If you comment out the assertion and run `hledger bs -f example.journal`, you see that the total of `assets:checking` is indeed 150.00 $:

```
Balance Sheet 2020/01/31

             || 2020/01/31
=============++============
 Assets      ||
-------------++------------
 assets      ||   150.00 $
   checking  ||   150.00 $
     budget  ||   150.00 $
       food  ||    50.00 $
       shoes ||   100.00 $
-------------++------------
             ||   150.00 $
=============++============
 Liabilities ||
-------------++------------
-------------++------------
             ||
=============++============
 Net:        ||   150.00 $
```

Also, you can run `hledger r assets:checking -f example.journal` and the output is:

```
2020/01/01 got paid                      assets:checking:available            2000.00 $     2000.00 $
2020/01/01 split available in budget     assets:checking:budget:rent          1000.00 $     3000.00 $
                                         assets:checking:budget:internet       100.00 $     3100.00 $
                                         assets:checking:budget:food           400.00 $     3500.00 $
                                         assets:checking:budget:shoes          500.00 $     4000.00 $
                                         assets:checking:available           -2000.00 $     2000.00 $
2020/01/02 buying new shoes              assets:checking:budget:shoes         -400.00 $     1600.00 $
2020/01/03 rent                          assets:checking:budget:rent         -1000.00 $      600.00 $
2020/01/05 groceries                     assets:checking:budget:food          -350.00 $      250.00 $
2020/01/25 internet                      assets:checking:budget:internet      -100.00 $      150.00 $
```

I find this behavior odd. The calculated amount is always exactly the double of what I expect.

**Hledger version:** 1.15.2
**OS:** Mac OS Catalina 10.15.3
**Related docs:** https://hledger.org/journal.html#assertions-and-subaccounts

Please let me know if you need any follow-up information for this bug report.

**Comment by walling** [comment]
[Duh](https://www.theseoproject.org/wp-content/uploads/2016/05/duh-meme.png), I literally sat with this for half an hour and after posting the bug report, I figured I just need to:

```
2020-01-31 account balance check
    assets:checking                     0 $ ==* 150.00 $
```

This issue can be closed. Sorry for disturbing.

**Comment by simonmichael** [comment]
Thanks for the report! Not to worry, I think you have indeed found a bug. Your original "assertion" is actually a balance assignment, and the error message should mention balance assertions. And it only does that with `==*` - `==` or `=` give the correct error:
```
could not balance this transaction (real postings are off by 150.00 $)
2020-01-31 account balance check
    assets:checking        150.00 $ = 150.00 $
```

**Comment by simonmichael** [comment]
I believe it goes wrong at https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Data/Journal.hs#L808, calculating a wrong running balance that's too large. Eg in this example it thinks a's actual balance should be $2:
```
2020-01-25
    (a:aa)   $1

2020-01-31
    a           ==* $1
```
@johannesgerer would you have time to take a look ?

**Comment by johannesgerer** [comment]
Unfortunately, I won't for the foreseeable future.

**Comment by simonmichael** [comment]
No problem. I got it fixed, inclusive balance assignments now work in master. 

(I think that's the right fix, even though the old behaviour was actually more useful to @walling, since it forced him to convert the balance assignment into the intended balance assertion.)
