### ISSUE TITLE
Values not shown on multi-commodity with depth=2 on hledger-ui

### ISSUE THREAD

**Issue by amitaibu** [simonmichael/hledger#1208]
1. clone https://github.com/amitaibu/hledger-example
1. `hledger-ui -f hledger.journal   --watch -2` - ![image](https://user-images.githubusercontent.com/125707/76164076-95682900-6154-11ea-8828-f2c4cbcc6a04.png)
1. Right click on `assets:banks`, and with 1.17 you will not see any value - 
![image](https://user-images.githubusercontent.com/125707/76164083-a3b64500-6154-11ea-81e2-eeb9437b4a8a.png)

**Comment by amitaibu** [comment]
With 1.16.2 it looks like this:

![image](https://user-images.githubusercontent.com/125707/76164189-99e11180-6155-11ea-927c-e823627dec93.png)

**Comment by simonmichael** [comment]
Good catch! Thanks for the report.
