### ISSUE TITLE
Formatting and representation for WeekPeriod

### ISSUE THREAD

**Issue by Xitian9** [simonmichael/hledger#1216]
### Representation

The current representation of `WeekPeriod` is a bit confused in its purpose and implementation. It is internally represented by by `WeekPeriod Day`, and `periodToDateSpan` will convert to the `DateSpan` with the given date as start, and a week later as end.

However, hledger itself will only create `WeekPeriod`s starting on a Monday and progressing to the next Monday. This means that many of the technically legal WeekPeriods are basically inaccessible, and suggests that maybe a different format is more appropriate. 

Overall, we have two different meanings of WeekPeriod, and I think it could be cleaned up a bit. As currently implemented, `WeekPeriod d` is basically just a synonym for `PeriodBetween d (addDays 7 d)`, with a different way of rendering it to a String. Here are some options for dealing with this:

- Leave it as is.
- Change to a representation `WeekPeriod year weeknumber`, where `1 <= weeknumber <= 53`.

The latter would bring it more in line with how MonthPeriod is represented. A disadvantage is that only some years have a week 53. However, there's not much harm in a WeekPeriod being representable but never created, beyond the cognitive overhead of having to write cases which will never end up being used (for an example, see the formatting options ahead).

### Formatting

In addition, the way a `WeekPeriod` is formatted is a bit nonstandard, and might be changed. Currently `WeekPeriod (fromGregorian 2000 01 01)` is formatted `2000-01-01w52` (as 2000-01-01 is actually part of the 52nd week of 1999). This has the advantage that the start date is explicitly written out, but is also a bit weird in that the week number doesn't necessarily match the year the date falls in.

The ISO standard for writing a week is e.g. `1999-W52` for the week (starting on Monday) containing `2000-01-01`. If you wanted to represent the day explicitly, you could add the weekday, resulting in `1999-W52-6`. This has the advantage that the week structure is much clearer, but the connection to the start date is a bit less clear, if we're not changing the representation of WeekPeriod. Here are the options I can think of:

1. Leave it as is (2000-01-01w52)
2. Display the start date in ISO week format with weekday (1999-W52-6)
3. Display the start date in ISO week format with weekday, but omit the weekday if it starts on a Monday (2000-01-01 = 1999-W52-6, but 2000-01-03 = 2000-W01). Note that if the representation is changed as above, then the weekday can always be omitted.

I'm curious on what people think of this, whether it's worth changing some or any of these things.

**Comment by simonmichael** [comment]
Thanks for looking at this stuff..

> On Mar 30, 2020, at 5:52 PM, Stephen Morgan <notifications@github.com> wrote:
> Representation
> 
> The current representation of WeekPeriod is a bit confused in its purpose and implementation. It is internally represented by by WeekPeriod Day, and periodToDateSpan will convert to the DateSpan with the given date as start, and a week later as end.
> 
> However, hledger itself will only create WeekPeriods starting on a Monday and progressing to the next Monday. This means that many of the technically legal WeekPeriods are basically inaccessible, and suggests that maybe a different format is more appropriate.
> 
> Overall, we have two different meanings of WeekPeriod, and I think it could be cleaned up a bit. As currently implemented, WeekPeriod d is basically just a synonym for PeriodBetween d (addDays 7 d), with a different way of rendering it to a String. Here are some options for dealing with this:
> 
> Leave it as is.
> Change to a representation WeekPeriod year weeknumber, where 1 <= weeknumber <= 53.
> The latter would bring it more in line with how MonthPeriod is represented. A disadvantage is that only some years have a week 53. However, there's not much harm in a WeekPeriod being representable but never created, beyond the cognitive overhead of having to write cases which will never end up being used (for an example, see the formatting options ahead).
> 

hledger doesn't yet support weeks not starting on monday; while that lasts, I don't care too much that they're not representable internally, it's not affecting anyone. But if you want to try a more elegant representation, that sounds fine. WeekPeriod could probably be documented a bit better, in any case.

> Formatting
> 
> In addition, the way a WeekPeriod is formatted is a bit nonstandard, and might be changed. Currently WeekPeriod (fromGregorian 2000 01 01) is formatted 2000-01-01w52 (as 2000-01-01 is actually part of the 52nd week of 1999). This has the advantage that the start date is explicitly written out, but is also a bit weird in that the week number doesn't necessarily match the year the date falls in.
> 
> The ISO standard for writing a week is e.g. 1999-W52 for the week (starting on Monday) containing 2000-01-01. If you wanted to represent the day explicitly, you could add the weekday, resulting in 1999-W52-6. This has the advantage that the week structure is much clearer, but the connection to the start date is a bit less clear, if we're not changing the representation of WeekPeriod. Here are the options I can think of:
> 
> Leave it as is (2000-01-01w52)
> Display the start date in ISO week format with weekday (1999-W52-6)
> Display the start date in ISO week format with weekday, but omit the weekday if it starts on a Monday (2000-01-01 = 1999-W52-6, but 2000-01-03 = 2000-W01). Note that if the representation is changed as above, then the weekday can always be omitted.

Thanks, it's this part I particularly wanted to raise on the mail list since UI and output changes affect us all.

I'm a bit unclear on this. Do you have any examples in mind of a real world problem caused by the current behaviour ?

We currently have a simplified model of weeks for "weekly" reports: they always begin on monday. And this means, as you say, that the first week of a year can begin in the previous year. Following some standard or other, it's the thursday's year that decides which year a week belongs to. Are you suggesting to change this model ? Or just the cosmetic rendering of these week periods ?

**Comment by Xitian9** [comment]
> hledger doesn't yet support weeks not starting on monday;

Is the intension to eventually support that? If so, I'd opt to leave this unchanged.

> Do you have any examples in mind of a real world problem caused by the current behaviour?

No, just a perhaps-overzealous push towards the standard.

> Are you suggesting to change this model ? Or just the cosmetic rendering of these week periods?

Definitely not suggesting to change the model, just the cosmetic rendering.

**Comment by Xitian9** [comment]
It's been about a week and nobody has chimed in on the mailing list. I have two interpretations of this:
- People are happy with whatever, make changes if you'd like.
- People are happy with the existing behaviour, so don't change it.

If it were just up to me I'd adopt proposal (3) here, but if you'd prefer to leave it alone then I'll drop this and close the issue.

**Comment by simonmichael** [comment]
Oh thanks. I'll reply there. My feeling is for the coming release we should just capitalise W.

**Comment by simonmichael** [comment]
I am inclined to wait for a problem to solve before changing this. I do find it useful to know the week's start date, otherwise they are quite hard to work with as a human. Our format is non-standard, agreed. That might be a problem worth solving, later; so I'm ok with leaving this open a bit longer. For 1.18 I think we should just capitalise the W for consistency with #1216.

**Comment by Xitian9** [comment]
I'm going to close this issue. The current behaviour is fine, if non-standard.
