### ISSUE TITLE
[hledger 1.17.1.1 on Linux] Garbled text in textfile output with -o option

### ISSUE THREAD

**Issue by ohmyohmyohmy** [simonmichael/hledger#1221]
Hello!

I use this command to output to a text file:
hledger -f ledgerfile balance -o balance.txt

The thing is, it outputs the colours for the console as well, so all negative values have a garbled look to them when read with any text editor. When I do "cat balance.txt", I can confirm the cause of the garbled sections was the console command to make the negative values red in colour.

I think that shouldn't be included when outputting to a file, thus, I think is a bug. What do you think?

Thanks!

P.S.
Currently there's a workaround for that. I use this command instead:
hledger -f ledgerfile balance > balance.txt

**Comment by simonmichael** [comment]
You're right! I'm surprised it doesn't disable the colours in that case. Thanks for the report.

**Comment by Xitian9** [comment]
I think this issue has been resolved already, and can be closed.

**Comment by Xitian9** [comment]
Closing. Feel free to reopen if you disagree.
