### ISSUE TITLE
[hledger-web 1.17.1 linux] Theme parsing error: gtk.css:6539:22

### ISSUE THREAD

**Issue by ohmyohmyohmy** [simonmichael/hledger#1222]
I don't think this is a biggie. When I load hledger-web -f ledgerfile, I see a message that says:
Gtk-WARNING **: 17:54:33.273: Theme parsing error: gtk.css:6539.22: 'dakren' is not a valid color name.

Also says:-
Theme parsing error: gtk.css:6536.26: 'dakren' is not a valid color name.

I think it's just a minor spelling issue. Perhaps it was meant to be 'darken'? XD

Stay safe all! Thanks!

**Comment by simonmichael** [comment]
I think that is caused my something else (your browser installation ?) We don't have a gtk.css in hledger.

**Comment by ohmyohmyohmy** [comment]
Dunno. It's just a standard installation of Firefox on Linux.

**Comment by adept** [comment]
Do you have ~/.config/gtk-3.0/gtk.css or in  ~/.themes?

I agree with Simon : it is something that had nothing to do with hledger
