### ISSUE TITLE
import uses different amount formatting

### ISSUE THREAD

**Issue by frivoal** [simonmichael/hledger#1224]
Version (running on macOS 10.14.6)
```
$ hledger --version
hledger 1.17.1.1
```

----

If I run `hledger -f test.journal print` to sort the transactions in my journal, it will reformat the amout / currency based on the way the last transaction is formatted, rather than preserving the way each transaction was written.

For example, I would expect the following file to stay unchanged

```
2020-01-01 test transaction with 123 USD
    cash           123 USD
    income

2020-01-02 test transaction with USD456
    cash           USD456
    income
```

but it becomes

```
2020-01-01 test transaction with 123 USD
    cash           USD123
    income

2020-01-02 test transaction with USD456
    cash           USD456
    income
```
(the change is on the second line).

Use case: I have a bunch of transactions in my journal formatted the way I want. I sometimes add transactions to it using `hledger import`, which end up being formatted differently. I then run `hledger` print to sort the newly imported transactions to the right place, but that causes amounts in the entire journal to be reformatted, which is not desirable.

---

Alternatively, if that is considered a feature rather than a bug in order to get consistent formatting, then the bug is in `hledger import`, since it will not follow the same rule, and instead of generating transactions that match the latest rule in the journal, it always puts the currency first, followed by the amount, with no space in between.

With the following files as input:
test.journal:
```
2020-01-01 test transaction with 123 USD
    cash           123 USD
    income
```

data.csv:
```

2020-01-02,456
```

test.rules:
```
fields date, amount
currency USD
account1 cash
account2 income
```

running `hledger -f test.journal import --rules-file test.rules data.csv`

will result in the following test.journal:
```
2020-01-01 test transaction with 123 USD
    cash           123 USD
    income

2020-01-02
    cash            USD456
    income         USD-456
```
This causes the original issue next time I sort my journal with `hledger print`. The problem would be avoided (and everything would have been made consistent) if hledger had instead generated:
```
2020-01-01 test transaction with 123 USD
    cash           123 USD
    income

2020-01-02
    cash           456 USD
    income        -456 USD
```

**Comment by simonmichael** [comment]
Thanks for the report. Can you read https://hledger.org/amounts.html and tell me if it helps ?

**Comment by simonmichael** [comment]
Correction: https://hledger.org/journal.html#amount-display-style

**Comment by frivoal** [comment]
Thanks for the pointer to the documentation. As far as I can tell, that documentation isn't fully accurate:

> Otherwise the format of the first posting amount in that commodity seen in the journal is used. But the number of decimal places (“precision”) will be the maximum from all posting amounts in that commmodity.

* Despite what the second bullet point claims, in the absence of directives, `hledger print` uses the last posting rather than the first posting as a basis for the display style.

  Fixing this would solve my particular problem.

* `hledger import` both ignores directives and the format of the last (and first) postings, and the default format is used in all cases.

  However, fixing that wouldn't solve my problem, as I then sort the journal with `hledger print`, which discards the directives in the journal. I would get the correct formatting the first time I import+print, but the wrong one the following time.

* Just in case, even though the documentation doesn't claim it would work, I tried using the commodity directive in the rules file, but it (predictably) is treated as a syntax error.

  If that worked, that would also solve my problem.

**Comment by simonmichael** [comment]
Hi @frivoal,

> "hledger print uses the last posting rather than the first posting as a basis for the display style."

I don't think that's what's happening... if you can create a minimal reproducible example, I'll be glad to see it.

> hledger import both ignores directives and the format of the last (and first) postings, and the default format is used in all cases.

You're right, this is related to #1158, where the proposed fix is "When the import command is generating journal entries, it should format them according to any applicable commodity directives in the journal file it is importing to". I think that would help you here also.

As a workaround for now, I believe you just need to change your CSV rules file. The `currency` rule always prepends the currency symbol. Instead, you can use rules like:
```
fields date, amount_
amount amount_ USD
account1 cash
account2 income
```

**Comment by frivoal** [comment]
> > hledger print uses the last posting rather than the first posting as a basis for the display style.

> I don't think that's what's happening... if you can create a minimal reproducible example, I'll be glad to see it.

There's one in the first comment above, but here's a more detailed one.

Input:
```
2020-01-01 initially formatted as 1234.00 USD
    cash           1234.00 USD
    income

2020-01-02 initially formatted as USD5678.00
    cash           USD5678.00
    income

2020-01-03 initially formatted as USD 2,468.00
    cash           USD 2,468.00
    income
```

command: `hledger -f test.journal print`

output:
```
2020-01-01 initially formatted as 1234.00 USD
    cash      USD 1,234.00
    income

2020-01-02 initially formatted as USD5678.00
    cash      USD 5,678.00
    income

2020-01-03 initially formatted as USD 2,468.00
    cash      USD 2,468.00
    income
```

----

> As a workaround for now […]

I can get this to work in the simple case where the csv file just has a single column for the amount. But in my actual files, the structure is more like `fields date, amount-in, amount-out`, with only one of  amount-in or amount-out being filled in. For that case, I cannot get it to work.

Here's a sample csv:
```
2020-01-02,123,
2020-01-03,,456
```
I tried these rules:
```
fields date, ai, ao
amount-in %ai USD
amount-out %ao USD
account1 cash
account2 income
```
and get this error:
```
hledger: error: could not parse "USD" as an amount
record values: "2020-01-02","123",""
the account1 rule is: cash
the account2 rule is: income
the amount-in rule is: %ai USD
the amount-out rule is: %ao USD
the date rule is: %1

the parse error is:      1:4:
  |
1 | USD
  |    ^
unexpected end of input
expecting '+', '-', or number

you may need to change your amount*, balance*, or currency* rules, or add or change your skip rule
```
I tried to deal with this with if clauses like this:
```
fields date, ai, ao
if %ai
	amount-in %ai USD
if %ao
	amount-out %ao USD
account1 cash
account2 income
```
but that didn't work, and I got that error instead:
```
hledger: "data.csv" (line 2, column 1)
could not balance this transaction - can't have more than one real posting with no amount (remember to put 2 or more spaces before amounts)
2020-01-02
    cash
    income
```

**Comment by simonmichael** [comment]
> here's a more detailed one.

Thanks. You're right in this case; here the last amount is the only one that unambiguously identifes the thousands separator and decimal separator, so those become the display style. In  the earlier ambiguous amounts, it's assumed to be a decimal separator in each case.

>  For that case, I cannot get it to work.

True. Your idea of using if is good, it's just not quite the right syntax. After `if %FIELD` there should be a regexp. It probably should have given you an error for this rules file. This one tests if there's any non-space character in the field:
```
fields date, ai, ao
if %ai 
	amount-in %ai USD
if %ao 
	amount-out %ao USD
account1 cash
account2 income
```

**Comment by simonmichael** [comment]
(corrected)

**Comment by frivoal** [comment]
Using a `.` in the regexp worked, so the immediate problem is solved.

However, for the formatting auto-detection, I am more confused than ever.

example 1:
```
2020-01-01 test transaction with 123 USD
    cash           123 USD
    income

2020-01-02 test transaction with USD456
    cash           USD456
    income
```
gives
```
2020-01-01 test transaction with 123 USD
    cash           USD123
    income

2020-01-02 test transaction with USD456
    cash           USD456
    income
```
example 2:
```
2020-01-01 initially formatted as 1234.00 USD
    cash           1234.00 USD
    income

2020-01-02 initially formatted as USD5678.00
    cash           USD5678.00
    income

2020-01-03 initially formatted as USD 2,468.00
    cash           USD 2,468.00
    income
```
gives
```
2020-01-01 initially formatted as 1234.00 USD
    cash      USD 1,234.00
    income

2020-01-02 initially formatted as USD5678.00
    cash      USD 5,678.00
    income

2020-01-03 initially formatted as USD 2,468.00
    cash      USD 2,468.00
    income
```
example 3:
```
2020-01-01 initially formatted as 1234,0 USD
    cash           1234,0 USD
    income

2020-01-02 initially formatted as USD2,468.00
    cash           USD2,468.00
    income

2020-01-03 initially formatted as USD 1 357,000
    cash           USD 1 357,000
    income

2020-01-04 initially formatted as 5678,00USD
    cash           5678,00USD
    income
```
gives
```
2020-01-01 initially formatted as 1234,0 USD
    cash      1 234.000USD
    income

2020-01-02 initially formatted as USD2,468.00
    cash      2 468.000USD
    income

2020-01-03 initially formatted as USD 1 357,000
    cash      1 357.000USD
    income

2020-01-04 initially formatted as 5678,00USD
    cash      5 678.000USD
    income
```
example 4:
```
2020-01-01 initially formatted as 1234 USD
    cash           1234 USD
    income

2020-01-02 initially formatted as USD 1 357,00
    cash           USD 1 357,00
    income

2020-01-03 initially formatted as 5678USD
    cash           5678USD
    income
```
gives
```
2020-01-01 initially formatted as 1234 USD
    cash       1 234.00USD
    income

2020-01-02 initially formatted as USD 1 357,00
    cash       1 357.00USD
    income

2020-01-03 initially formatted as 5678USD
    cash       5 678.00USD
    income
```
The only logic I can find which satisfies those files and the few other attempts I have made is
* it picks  the currency formatting (before or after, with a space or not) from the last transaction in the file
* it picks the thousands separator from the last number that has one (even if later numbers have enough digits to show that there shouldn't be a thousands separator)
* it picks the number of decimals from the number with the largest number of decimals
* if the number of decimals is not 0, it picks `.` as the decimal separator, no matter what you used in the journal

That may not be the actual logic, but either way, something non obvious is going on.

**Comment by frivoal** [comment]
> Using a `.` in the regexp worked, so the immediate problem is solved.

Forgot the important part: thank you!

**Comment by simonmichael** [comment]
I have tested only the first examples, but I believe this is all working as intended and documented nowadays. `hledger print` formats the amounts in each commodity consistently according to https://hledger.org/dev/hledger.html#commodity-display-style , and `hledger import` formats amounts likewise.
