### ISSUE TITLE
CSV import has a different behaviour with amount-out

### ISSUE THREAD

**Issue by LunaticMuch** [simonmichael/hledger#1226]
Hi there,

I've found a different behaviour after last release, which I am not sure it's a bug or it was one that is now corrected. I've been importing my credit card txn with the following rule file

```
fields  date, amount-out, description, account2, ,amount2, ,account3, amount3, ,account4, amount4, , account5, amount5 ,desc
skip 1
date-format  %d/%m/%Y
account1  liabilities:americanexpress
comment %desc
```

A sample of my file is

`16/03/2020,3.30 GBP,CAFFE NERO 212610 LONDON,expenses:food:coffee,100%,3.30 GBP,,,,,,,,,,
`
Before the last update, this was translated into 

```
2020/03/16 CAFFE NERO 212610 LONDON
    liabilities:americanexpress       -3.30 GBP
    expenses:food:coffee               3.30 GBP
```

But now the same file generates an error (with `hledger import --rules-file amex.csv.rules --dry`)

```
hledger: more than one non-zero amount for this record, please ensure just one
    amount2    : 3.30 GBP from rule: %6
    amount-out : -3.30 GBP from rule: %2
    record values: "16/03/2020","3.30 GBP","CAFFE NERO 212610 LONDON","expenses:food:coffee","100%","3.30 GBP","","","","","","","","","",""
```

Changing the `amount-out` in `amount-in`, which should reverse the sign, does not help.
Replacing the `amount-out` with `cardamount` and adding a rule like

`amount-out -%cardamount`

seems not effective as well 

```
hledger: more than one non-zero amount for this record, please ensure just one
    amount2    : 3.30 GBP from rule: %6
    amount-out : 3.30 GBP from rule: -%cardamount
    record values: "16/03/2020","3.30 GBP","CAFFE NERO 212610 LONDON","expenses:food:coffee","100%","3.30 GBP","","","","","","","","","",""
```

Same with `amount-in -%cardamount`

The only possible solution is `amount1 -%cardamount`. However, this makes useless `amount-out ` and `amount-in` useless.

**Comment by adept** [comment]
`amount-out` is retained for pre-1.16 compatibility, but as you can see it does not mix well with other numbered fields.

Change `amount-out` to `amount1-out`, and it all should work.

**Comment by LunaticMuch** [comment]
Interesting. Is it possible I did not find it in the doc? My rule file is coming from an example on the website, it should be updated maybe.

**Comment by simonmichael** [comment]
Thanks for the report. The doc is here: https://hledger.org/csv.html#amount , I think I'll add this url to the error message. Let me know if the doc could be improved. Eg should it end with "if any numbered amountN* fields are present ... amount/amount-in/amount-out are ignored" ? But maybe that would be too drastic and more confusing. If you find the doc with outdated example, please let us know.

**Comment by LunaticMuch** [comment]
I think manual is fine, not sure why I did not find it. However, the example _Bank of Ireland_ uses `amount-in` and `amount-out` and it should be change with the use of `amount1-in` and `amount1-out` so not one gets in trouble.

**Comment by simonmichael** [comment]
Well.. that example is using the "old" (not actually deprecated) syntax, true, but it works as intended - it sets the amount on both postings.

**Comment by LunaticMuch** [comment]
True, but I think the example should always use the currrent syntax .... not the old, regardless it's deprecated or not, nor the future new syntax.

**Comment by simonmichael** [comment]
It's old in the sense that it came first, but we kept it because I think it's still useful, being simpler for simple cases. I'm not sure there's any harm in showing it.

**Comment by simonmichael** [comment]
I've added https://hledger.org/csv.html#amount to the error message, and tweaked the doc to clarify the status. Does that help ?

The final sentence needs a bit more thought.

**Comment by simonmichael** [comment]
PS I will note that we did *want* to deprecate the old form, but couldn't; it was something to be considered for the future. So while I'm reluctant to open the can of worms that is CSV rules and compatibility right now, deprecating and removing the old form is not off the table.

**Comment by simonmichael** [comment]
Ideas for the final sentence (ie, how the old and new forms combine if both are present):

"If any numbered amountN/amountN-in/amountN-out fields are present, amount/amount-in/amount-out are ignored."

"Use either the numbered or the unnumbered forms, but not both at once."

**Comment by simonmichael** [comment]
PS I have some large old rules files using the unnumbered form, and I have found it useful to be able to use the numbered form in specific conditionals where I need it, without being forced to rewrite and test all rules.

**Comment by simonmichael** [comment]
So, another candidate:

"Normally you should pick either the numbered or the unnumbered form.
The numbered form gives most control.
However, if you have a large rules file using the unnumbered form,
you may want to use the numbered form in a few conditional blocks.
To support this, if any numbered
`amountN`/`amountN-in`/`amountN-out` assignments are seen (at top
level, or in an active conditional block), these will take precedence,
causing unnumbered`amount`/`amount-in`/`amount-out` assignments to be
ignored."

**Comment by simonmichael** [comment]
I've been cleaning this up. I understand now that your example worked in 1.17, but was broken by 1.17.1. In latest master, it works again:
```
$ hledger-1.17 -f a.csv print
2020-03-16 CAFFE NERO 212610 LONDON
    liabilities:americanexpress       -3.30 GBP
    expenses:food:coffee               3.30 GBP

$ hledger-1.17.1.1 -f a.csv print
hledger-1.17.1.1: more than one non-zero amount for this record, please ensure just one
    amount2    : 3.30 GBP from rule: %6
    amount-out : -3.30 GBP from rule: %2
    record values: "16/03/2020","3.30 GBP","CAFFE NERO 212610 LONDON","expenses:food:coffee","100%","3.30 GBP","","","","","","","","","",""

$ stack exec -- hledger -f a.csv print
2020-03-16 CAFFE NERO 212610 LONDON
    liabilities:americanexpress       -3.30 GBP
    expenses:food:coffee               3.30 GBP
```
And the disabling of unnumbered assignments when numbered ones are active is now more thorough - see the new doc at https://hledger.org/csv.html#amount . 

For anyone wondering, the example does look unusual, but here's why it happens to work: for posting 1, amount-out is used, and negates the value as -out usually does (-3.30 GBP); for posting 1, amount-out is ignored and amount2 is used (3.30 GBP).
