### ISSUE TITLE
support amount-in / amount-out with different signs

### ISSUE THREAD

**Issue by spang** [simonmichael/hledger#123]
In my bank's CSV export, the amount-in field is always positive, and the amount-out field is always negative. No matter how I set amount-in and amount-out and account2 and account2, either deposits or withdrawals will always have the wrong sign for me; hledger seems to assume (not crazily!) that these two fields will have the same sign.

It would be great if I could trigger a manual sign-flip on amount-in / amount-out. The documentation implies there is something of the sort for "amount values", but I couldn't figure out how it works.
##

**Comment by adept** [comment]
Close?

**Comment by simonmichael** [comment]
Yes please. I feel sure this can be handled with the right rules, @spang I'll help if it's still an issue.

**Comment by simonmichael** [comment]
PS @spang and if you're still interested have time to revisit the docs, please do point out what's unclear and I'll improve it.
