### ISSUE TITLE
hledger-ui/hledger-web can misleadingly hide a zero-balance parent account

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1237]
Reported by glguy, with additional testing from parsnip. When showing a tree of account balances, a parent account with non-zero subaccounts should always be shown, even if its balance is zero and zeroes are being hidden, to preserve the correct tree structure. This isn't working correctly when you toggle zeroes off in hledger-ui and hledger-web. 

Eg:
```journal
2020/1/1
    (A)        1
    (B:C)      1
    (B:D)     -1
    (Z)        0
```
The balance command hides zeroes by default (Z), but correctly does not hide B because it has non-zero subs:
```
$ hledger bal  -N
                   1  A
                   0  B
                   1    C
                  -1    D
```
hledger-ui shows zeroes by default:
```
 A    1
 B    0
  C   1
  D  -1
 Z    0
```
but when you press `Z` to hide them (or if you start it with -E) it incorrectly hides B:
```
 A    1
  C   1
  D  -1
```
The same thing happens in hledger-web's account sidebar when you press `e`.

**Comment by Xitian9** [comment]
I'm getting that this is no longer an issue for hledger-ui in master, but is still a problem form hledger-web.

**Comment by simonmichael** [comment]
How do you reproduce it with hledger-web ? I'm not quite seeing it with hledger master.

**Comment by simonmichael** [comment]
Now I do. Starting it with -E (to hide zeroes) correctly still shows B, but pressing e disrupted it.

**Comment by simonmichael** [comment]
Thank you!

**Comment by Xitian9** [comment]
Note that we still seem to have a slightly weird behaviour with hledger-web. If you call with `-E` then zero leaves will never be shown, even if you toggle with `e`. Toggling will only toggle zero branches. I'm not sure if this is worth fixing.

**Comment by simonmichael** [comment]
You're right, I rationalised that as a startup option that permanently restricts the data - hledger-web has some of those. But, it doesn't really make sense for zero display to work like that. I think it's worth fixing.
