### ISSUE TITLE
multiple date terms in a query are not ORed

### ISSUE THREAD

**Issue by amigalemming** [simonmichael/hledger#1246]
The online help of `hledger-web` claims that multiple terms of the same field are combined with OR,
but e.g. `date:2020 date:2018` yields empty responses where `date2020` yields non-empty results.
Is this intended behaviour? But then the online help is wrong or at least misleading.

**Comment by amigalemming** [comment]
~~~~
hledger> parseQuery nulldate $ Text.pack "date:2018 date:2020"
(Date (DateSpan 2020-01-01-2018-12-31),[])
~~~~

**Comment by thielema** [comment]
I have pushed a commit that ORs multiple date terms.
The automated tests however, verify that the terms are AND'd.
(:tests/cli/date-options.test:9, :tests/cli/date-options.test:10)
So ANDing of date terms is expected behaviour? Why?

**Comment by simonmichael** [comment]
Yes I see, it says "Multiple search terms on different fields are AND'ed, multiple search terms on the same field are OR'ed", while https://hledger.org/hledger.html#queries gives a more accurate description. Dates are AND'd indeed. I think I found it more useful for date restrictions to be additive, eg when you have a report defined as a command line alias and you want to add additional date limits. I propose we update the help text in hledger-web and don't mess with the date logic until somebody implements real boolean queries.
