### ISSUE TITLE
quarter period

### ISSUE THREAD

**Issue by amigalemming** [simonmichael/hledger#1247]
What do you think about a period specification for quarters, say
~~~~
date:2020q1
~~~~
for the first quarter of 2020?

**Comment by simonmichael** [comment]
I like the idea, and also date:q1 for the current year's first quarter.

**Comment by OneCricketeer** [comment]
When I first learned budgetting, I learned monthly (bills/rent/essentials), quarterly (auto maintenance/seasonal travel), and yearly (gifts, misc); really opened my eyes a bit, so +1 for this

**Comment by amigalemming** [comment]
I see that storing and showing of quarters is already implemented in `hledger-lib`. Only the parser is missing.
