### ISSUE TITLE
Rules not read when reading from STDIN

### ISSUE THREAD

**Issue by repomaa** [simonmichael/hledger#1251]
I noticed that allthough the following works:

```
hledger -f input.csv --rules-file my.rules print
```

This doesn't:

```
cat input.csv | hledger -f- --rules-file my.rules print
```

The latter fails to parse the csv from stdin because it doesn't skip lines defined in the rules file.

**Comment by repomaa** [comment]
Not so serious because i just discovered that it works if `-f csv:-` is used instead of `-f-`

**Comment by alerque** [comment]
I don't think the problem is that it doesn't read the rules file, the problem is it doesn't know the input stream is CSV unless you tell it since it doesn't have filename clues to work from.

**Comment by simonmichael** [comment]
Correct. Up till 1.16 or so we tried all readers so it worked, but that sometimes coukd give confusing results.

**Comment by simonmichael** [comment]
@repomaa, thanks for the report anyway. Maybe you see somewhere in the manual(s) where we should make this clearer ?

**Comment by simonmichael** [comment]
We could also assume csv: based on the presence of the --rules-file flag. Rules needn't necessarily be a CSV-only thing, but right now they are. It makes things for "clever" but probably it would be an improvement.

**Comment by Xitian9** [comment]
I think this issue can be closed, unless there's something to do here.

**Comment by simonmichael** [comment]
Agreed, I think the current behaviour is documented, reasonably intuitive in hindsight, and it's not worth trying to be more clever.
