### ISSUE TITLE
Proposal: CSV rules in a file

### ISSUE THREAD

**Issue by adept** [simonmichael/hledger#1252]
I am thinking about adding a new syntax for CSV rules to supplement (not replace) the existing one.

Rules will be kept in a delimited file where the header line defines which fields are assigned here:
```
regexp,account2,comment
FOO,expenses:foo,this is a foo
BAR,expenses:bar,
BAZ,,what a BAZ
```

This file will be semantically equivalent to this rules file:
```
if
FOO
  account2   expenses:foo
  comment   this is a foo

if
BAR
   account2  expenses:bar

if
BAZ
  comment   what a BAZ
```

Header `regexp` is mandatory, all other headers are optional and could be any of the assignable CSV fields.

Files in this format will have to be included in another (top-level) rules file, as they have no facility to define date format, `fields`, etc:
```
include delimiter "," rules.csv
```

They will not allow any further includes inside themselves

### Rationale

I'm actually using a simplified version of this format, where columns are set to be "regexp,accounts,comment" and file is being translated into hledger rules syntax by [awk script](https://github.com/adept/full-fledged-hledger/tree/master/06-maintaining-lots-of-csv-rules/import/psv-to-rules.awk).

I've had several reasons to create this system:
1)Speed. When I am making rules for unclassified entries, I have one window with something like "hledger print acct:expenses:unknown" and another window with rules file, and I want to write down rules for the transactions as quickly as possible. Default hledger syntax is not exactly made for speed: "if", Enter, <regexp>, Enter, space, space,"account2",space,space,type out account name - you get the idea. Counting newlines and white space, the amount of boilerplate is almost equal to the amount of actual information. 

Contrast this with "<regexp>|<account name>|<optional comment>" - format overhead is really low (just two separators). The difference becomes more pronounce the more rules you write out in a single sitting.

Arguably, this could be solved by copy-pasting or editor macro. But then we get to the second issue

2)The simplicity of keeping rules organized
In the current syntax, you could combine several rules that assign the same values to transaction fields via:
```
if
regex1
regex2
...
regex2
   field   assignment
   field    assignment
```

This is nice, neat, and compact. However, if you want to keep your rules file neatly organized as you are adding new rules, you will have to either: a)search in the rules file for the right "if" block to modify whenever you add new regex or b)add each new rule in its own "if" block and sort/combine later.

Both of these things are very time-consuming and not something that you really want to do if you plan to add 20+ new rules.

On the other hand, in the tabular format, you could just keep adding new rules (one line == one rule), and when you are done, you sort your file by the second column - and there you are, everything is nice, neat and organized. 

If you edit your delimited file in excel or OpenOffice, you also get poor man's autocomplete as you add new rules, since your accounts are in a single column, so as you type them, spreadsheet editor will suggest values to you.

What do you think?

**Comment by alerque** [comment]
Sure, this looks like a nicer format that would make it more pleasant to maintain lots of import rules. I would approve of this being added **provided** it doesn't make it any harder to maintain and extend the CSV import system. I'm much more interested in seeing features like capture groups (#1061) make it into `hledger` than on this syntactical sugar that –as nice as it is– doesn't actually extend what can be accomplished. If implementing this would hinder development on features like that that I wouldn't be so hot on it.

**Comment by simonmichael** [comment]
I know you have a preprocessor like this, and I raised the idea of building it in. Could you give more detail about the problem/pain this solves for you, to motivate it ?

**Comment by adept** [comment]
> Objections:
> 
> I see the benefits; I'm not sure they are strong enough to justify yet another file format (a sub-case of the csv rules format, and coincidentally another csv file, which may confuse the situation for some folks..
> 
> > include delimiter "," rules.csv
> You're proposing a new form of the (csv rules) include directive? Is it intended that the new rules file format (and it would need a short mnemonic name) would allow any character as delimiter ?

It could be something else than `include`. Ideas: `table`, `delimited`.
As for allowing variable delimiters: if it is easy, then -- why not?
Short mnemonic name: "rules table", "tabular rules", "compact rules"


> > Header regexp is mandatory
> The regexp would search the whole CSV record; I imagine folks would want support for per-field patterns too (and future enhancements like !negativepatterns).

Hmm. I think i am missing some context here. I assume that you are talking some future expansions to the rule syntax, as currently, regex do search the entire record, and there are no per-fields patterns/negative patters. If/when they materialize, it could simply be the case that tabular rules do not support them.

> > all other headers are optional and could be any of the assignable CSV fields.
> I think in practice account2 will be the only one that can usefully be assigned by this method ?

Why? I am using this approach now for account2, comment, and sometimes account1, but leaving my personal experience aside - why do you think this is mostly applicable to account2?

Or is this an observation that "if" rules, in general, are mostly used to assign account2?

> PS in my case, I normally would be adding 0-2 new patterns to my existing rules each time I do an import, so I don't feel the pain of making a lot of rules all at once. (Also, emacs user, so kind of oblivious to editing hassles...)

I import all of my Paypal and amazon transactions, and these intend to produce a lot of one-off things. Plus I am often importing months at a time, so for me the numbers are always 20+

> And I suppose replacing the existing rules format with some kind of one-rule-per-line format would wouldn't really be feasible. At least, not without much smarter auto-detection of some things.

Yes, this is not feasible at all IMO

**Comment by simonmichael** [comment]
> Hmm. I think i am missing some context here. I assume that you are talking some future expansions to the rule syntax, as currently, regex do search the entire record, and there are no per-fields patterns/negative patters. If/when they materialize, it could simply be the case that tabular rules do not support them.


Yes - we have https://hledger.org/csv.html#if -> single field matchers now. Negative patterns are a planned future expansion yes.

> Why? I am using this approach now for account2, comment, and sometimes account1, but leaving my personal experience aside - why do you think this is mostly applicable to account2?


Well, I assume account1 is going to be pretty constant, and you can't usefully assign account3+ (since you can't set the amount per posting, these rules are really only for simple two-posting transactions). Description already comes from the csv, unless you want to rewrite those. A fixed comment that you add every time sounds not that useful, I assume you'd have not too many of those. Perhaps I'm not seeing all the ways you can use these ?

> I import all of my Paypal and amazon transactions, and these intend to produce a lot of one-off things. Plus I am often importing months at a time, so for me the numbers are always 20+


Makes sense.

**Comment by simonmichael** [comment]
adept what would you think about integrating a “rules table” in the main rules format: if followed by one or more comma/semicolon/tab-separated field names begins a block of rules, until the next blank line ?

**Comment by adept** [comment]
> Well, I assume account1 is going to be pretty constant, and you can't usefully assign account3+ (since you can't set the amount per posting, these rules are really only for simple two-posting transactions). The description already comes from the csv, unless you want to rewrite those. A fixed comment that you add every time sounds not that useful, I assume you'd have not too many of those. Perhaps I'm not seeing all the ways you can use these?

All the rules behave kinda like a monoid, right? Later rules add to the effect of the earlier rules

Let's say that you engage the services of translation bureau. And you have regular "if" rule for them:
```
if TRANSLATORS INC
   account2     expenses:translations
```

And then your "delimited rules file" could assign comments to particular jobs they did for you:
```
regex,comment
2020-01-16.*TRANSLATORS INC,Contract with IBM
2019-12-31.*TRANSLATORS INC,Letter to Santa
```

Yes, you are right that this is a fixed comment, but as it is a comment for a single transaction, it is actually fine :)

Same reasoning could be applied to any other field: you could have other rules in place that supplement what you have in the file...

> adept what would you think about integrating a “rules table” in the main rules format: `if` followed by one or more comma/semicolon/tab-separated field names begins a block of rules, until the next blank line ?

I like it! Presumably current "include" rules apply and this tabular if could be moved into a separate file, right? Then it is the best of both worlds -- you can either have a separate file if you want or inline rules into your main one. Having "," as a separator might be problematic for people that want to include "," in the regexp, but I think it will not be awful to say that they should just use regular "if" then.

**Comment by simonmichael** [comment]
> Let's say that you engage the services of translation bureau. And you have regular "if" rule for them:
> ...
> And then your "delimited rules file" could assign comments to particular jobs they did for you:

Fair enough, it probably has more uses than I've imagined.

> I like it! Presumably current "include" rules apply and this tabular if could be moved into a separate file, right? Then it is the best of both worlds -- you can either have a separate file if you want or inline rules into your main one. 

Yes, exactly.

> Having "," as a separator might be problematic for people that want to include "," in the regexp, but I think it will not be awful to say that they should just use regular "if" then.

Well that's why I say let's allow alternate separators, I was thinking those of our supported CSV/SSV/TSV input formats (comma, semicolon, tab).

**Comment by adept** [comment]
Sold :)

I'll see if I can make this happen

**Comment by simonmichael** [comment]
(I'm imagining european users who want to match amounts with a comma decimal mark might use ; as field separator, or anyone who wants more readable rules might use tab.)

**Comment by simonmichael** [comment]
I'm remembering that we actually support any https://hledger.org/csv.html#separator in C(haracter)SV. (Comma, semicolon and tab are just the ones we recognise automatically by file extension (csv, ssv, tsv).) If you want to also allow pipes as a separator in this feature, go right ahead, maybe some folks have comma decimal points *and* semicolons in descriptions...
