### ISSUE TITLE
balance assignment in second top-level file not working as expected

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1265]
Reported by myridium:

This balance assignment works as expected:
```
2020-01-01
  (a)  1

2020-01-02
  (a)  = 0
```
```
$ hledger -f a.j print -x
2020-01-01
    (a)               1

2020-01-02
    (a)              -1 = 0

```
But if you move the balance assignment to a separate file, it doesn't:
```
2020-01-01
  (a)  1
```
```
2020-01-02
  (a)  = 0
```
```
$ hledger -f a.j -f b.j print -x
2020-01-01
    (a)               1

2020-01-02
    (a)               0 = 0

```

It's as if the second file doesn't see a's balance from the first file.

Related, hledger accepts the above, but hledger-ui rejects it with a balance assertion error - they should agree on this.

**Comment by simonmichael** [comment]
Oh dear. https://hledger.org/journal.html#assertions-and-multiple-f-options : "Balance assertions don’t work well across files specified with multiple -f options. Use include or concatenate the files instead."

**Comment by simonmichael** [comment]
Also mentioned at https://hledger.org/hledger.html#input-files .

I agree that balance assertions/assignments should work across sibling files, but I guess there's some difficulty that prevented it. I won't have time to fix it soon but would welcome a PR.

Separately, we should clarify whether hledger/hledger-web are right to succeed here, or hledger-ui is right to fail, and make them agree.

And, until this is implemented it would be nice if we could warn about this. Is there any way to detect it automatically ?

**Comment by adept** [comment]
Also #482 ?

**Comment by adept** [comment]
And maybe #480

**Comment by Myridium** [comment]
It also fails for `hledger bs`. Except it fails silently, and fails to perform the balance assignment. This is an even worse problem, as it is a silent failure which gives an incorrect financial report!

**Comment by simonmichael** [comment]
I think all bugs were resolved here: The two file example is working per docs, generating a zero posting in the second transaction. hledger, hledger-ui and hledger-web are consistent. hledger bs shows an empty report because there is no asset or liability account here. #482 is the enhancement request.
