### ISSUE TITLE
Int wraparound causing some problems

### ISSUE THREAD

**Issue by Xitian9** [simonmichael/hledger#1275]
This is to document some issues discovered by @simonmichael in #1271  regarding Int wraparound. I'll first discuss the actual issues seen, diagnose their cause, and propose some options for resolving them. These issues may arise elsewhere, either now or in the future, but be undiscovered, so I hope we can come to a principled conclusion about how to deal with these.

Here are three calls which display (1) normal behaviour, (2) incorrect behaviour type a (wrong, but innocuous), (3) incorrect behivour type b (incorrect behaviour causing crashes or other nasty things).

```
~/src/hledger$ hledger bal --tree --drop 999999999999999999
                   1  ...
                   1  ...
                   2  ...
                   1  ...
                   1  ...
--------------------
                   5
~/src/hledger$ hledger bal --tree --drop 9999999999999999999   # add one more 9, it wraps around [and strips all indentation]
                   1  a:k
                   3  b
                   1  i:p
                   2  j
                   1  q
                   1  c
--------------------
                   5
~/src/hledger$ hledger bal --tree --drop 99999999999999999999  # add one more 9, it swiftly consumes all memory
  C-c C-c
```

1. Note here that the first call has the argument to drop being less than the maximum bound of Int
2. The second call exceeds the maximum bound of Int, and wraps around to a negative number (-8446744073709551617)
3. The third call again exceeds the maximum bound of Int, but this time wraps to a positive number (7766279631452241919)

The places in the code where the issues arise are in this block, in particular lines 439 and 443.
https://github.com/simonmichael/hledger/blob/e2bccf8645b2e6caeb4f74b7b494c7a24bb8ce72/hledger-lib/Hledger/Reports/MultiBalanceReport.hs#L435-L444

Line 439 determines what the account leaf name is, and is responsible for the issue in example (2). It calls `drop` on a list under the hood, so when `drop_` is a large positive number, it will drop everything leaving only an ellipse `...`. If `drop_` is a negative number, it will gracefully drop nothing. Thus, in example (2), when `drop_` wraps around to a large negative number, the whole account name is displayed as if `drop_` were 0. In example (3), it wraps to a large positive number, and so everything is again ellided.

Line 443 is the account depth calculation, and determines the indentation of the displayed account name, which is done here
https://github.com/simonmichael/hledger/blob/e2bccf8645b2e6caeb4f74b7b494c7a24bb8ce72/hledger/Hledger/Cli/Commands/Balance.hs#L616-L617

So if `2 * level` is negative or zero, no indentation will take place. Otherwise, it will display the appropriate number of spaces. In particular, if `2 * level` is very large, it will try to display a very large number of spaces, and will eat up memory and crash. (Note that the actual number we care about is not `2 * level`, but rather `2 * level` minus some small number determined by boring parents, be we neglect that here and it doesn't have an effect).

In example (2), `drop_` is a large negative number, so `level` is a large positive number. However, `2 * level` wraps around again and becomes a large negative number, so all indentation is stripped. In example (3), `drop_` is a large positive number, so `level` is a large negative number, but `2 * level` again wraps around to a large positive number, and the program crashes trying to add lots of spaces.

This is the diagnosis of the current observed problem. What to do about it?

Since wraparound is the problem, changing `Int` to `Integer` would help. We would no longer get unexpected negative numbers. This would solve both problems (2) and (3). There would still be a problem if `drop_` were set to a negative integer, something which the command line interface forbids, but could be done in code.

We could also solve the problem by changing `Int` to `Word` of some sort. We would still have wraparound, but it would just wrap around to 0 instead of a negative number. This would eliminate problem (3), but not the ellision problem of problem (2).

We could be super fancy and change `Int` to `Natural`, which would be the correct type to use and would solve both (2) and (3), but we would then have to do some case handling whenever we do subtraction.

I think reasonable people can agree (correct me if I'm wrong) than anybody calling `drop_` with anything even remotely large is just being silly, and it might be acceptable to let them get silly results for their effort. So I wouldn't be too fussed about problem (2), and view solving problem (3) as the main thing to do. With that in mind, here are some proposed solutions.

1. Don't change the types, but do some ad-hoc checks at various points to make sure our numbers aren't negative or too large. This would solve any problem we can see now, but is ad-hoc and may miss cases we haven't seen.
2. Change type from `Int` to `Integer`. This makes everything predictable and no case checks are necessary, but if the value does wind up as negative we'd still have memory errors. We could either trust that that will never happen due to sufficient restrictions on the cli, or put some `max 0` in key places.
2. Change type from `Int` to some form of `Word` or `Natural`. This has the cost of needing to use some `takeGeneric` or `dropGeneric` where previously `take` and `drop` sufficed, but we can be pretty sure we won't have more problems. In any case, we will still need to do some case checking whenever we do subtraction.
  a. Changing to `Word` means we will occasionally still have problem (2) arise, and missing a case check on subtraction may result in large numbers (i.e. lots of spaces displayed)
  b. Changing to `Natural` means we don't get problem (2) or (3), and missing a case check on subtraction may result in runtime errors (i.e. program crashes, but doesn't hang and eat memory)

Thoughts?

**Comment by simonmichael** [comment]
Very good explanation, thank you!

Since you've debugged all this, and we're going to be making changes anyway, and since we have the best language in the world for doing things right, and hledger aims to always do the right thing, I say we certainly cannot let 2 stand either. :)

Based on your clear description, using Integer (here and generally for numeric inputs) seems like a good choice to me - it rules out the wraparound issue, we can disallow negative values when parsing options, and it shouldn't add too much busywork or boilerplate ?

**Comment by Xitian9** [comment]
Another issue to consider: should we do any sort of check at the rendering stage to make sure it's not going to display an enormous number of spaces, or should we just trust that it will never happen? (The only way to artificially inflate that number is to actually feed it an `AccountName` with a very large number of account separators)

**Comment by simonmichael** [comment]
As a general rule/first step, I think it's ok to let it try to carry on when given abnormally large data - perhaps running slowly or appearing to hang - but we want it to remain somewhat well behaved, never eating all memory and possibly hanging the machine. I'd like to understand why it blows up here just printing spaces, presumably something needs to be more strict. To help avoid that kind of coding elsewhere.

**Comment by Xitian9** [comment]
I've put together a couple of solutions, the first of which basically replaces all uses of Int with Integer, the second of which replaces the getintoptmaybe with something which reads an integer, makes sure it fits in an Int, and then emits that. The first involves much more change in the code base, the second is minimal.

https://github.com/simonmichael/hledger/compare/master...Xitian9:integers
https://github.com/simonmichael/hledger/compare/master...Xitian9:droprollover

**Comment by simonmichael** [comment]
The smaller change looks good! What do you think about these changes to make maybeintopt a little more transparent: 

- rename to maybeposintopt ? could keep the maybeintopt variant too, but we don't currently need it
- have it fail on negative or too-large value instead of silently clipping it
- add a haddock, "Reads the named option's natural-number argument, if it is present. An argument that is not a natural number, or too large to fit in an Int, will raise an error.", or whatever.

**Comment by simonmichael** [comment]
PS, with error message making the problem clear for users, eg "OPT's argument STR must be a positive integer less than 9223372036854775807". The number looks silly but at least it's clear.. better ideas welcome.

**Comment by Xitian9** [comment]
I've submitted PR #1277 . Interestingly, it looks like I was mistaken, and the cli doesn't actually prevent you from entering negative numbers. So you could arbitrarily increase your indentation (and make your computer hang), just by calling `hledger balance --drop="-999999999999999"`.

**Comment by simonmichael** [comment]
> before this change, you could arbitrarily increase your indentation (and make your computer hang), just by calling hledger balance --drop="-999999999999999".

Are you sure ? I couldn't reproduce this with current hledger master:
```
$ hledger -f examples/sample.csv bal --drop '-999999999999999'
hledger: could not parse drop number: --depth=999999999999999 (use -h to see usage)
```

I did some quick tests of 1.18 as well, and found that this memory blowup is reproducible only in master, not released hledgers, which is good news. And #1277 fixes it, thank you!

One more thing, the error wording above is a bit strange ("...--depth...").

**Comment by Xitian9** [comment]
Yes, I previously encountered that error, and so assumed that it was complaining about negative numbers and we weren't able to enter them. In fact, it's interpretting '-99999999' as the shorthand depth argument, and taking that as the argument to `--drop`. To get the error I was talking about, make sure you actually type the `=` sign and the quotation marks.

Yes, none of these errors should show up in any released version: they all appear with the new `multiBalanceReportWith` code, in particular coming from the use of subtraction to calculate the depth.

**Comment by simonmichael** [comment]
Oh, rats. I guess it's not a problem for now. Thanks!
