### ISSUE TITLE
print --auto can show unbalanced entries due to too many missing amounts

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1276]
For an auto postings question in #hledger - how to generate a tax liability from revenue - I came up with:
```
= Income:UK:MSG:Invoice
    Liabilities:UK:Tax                      *-0.453
    Assets:UK:TransferWise:MOAT:Checking

2019-08-29 Paid invoice
    Income:UK:MSG:Invoice                    -1000 GBP
    Assets:UK:TransferWise:MOAT:Checking
```

But notice how print --auto generates an unparseable journal entry, with two missing amounts:
```
$ hledger print --auto
2019-08-29 Paid invoice  ; modified:
    Income:UK:MSG:Invoice                      -1000 GBP
    Liabilities:UK:Tax                           453 GBP  ; generated-posting: = Income:UK:MSG:Invoice
    Assets:UK:TransferWise:MOAT:Checking      ; generated-posting: = Income:UK:MSG:Invoice
    Assets:UK:TransferWise:MOAT:Checking
```
You need to add -x to see a valid entry:
```
$ hledger print --auto -x
2019-08-29 Paid invoice  ; modified:
    Income:UK:MSG:Invoice                      -1000 GBP
    Liabilities:UK:Tax                           453 GBP  ; generated-posting: = Income:UK:MSG:Invoice
    Assets:UK:TransferWise:MOAT:Checking        -453 GBP  ; generated-posting: = Income:UK:MSG:Invoice
    Assets:UK:TransferWise:MOAT:Checking        1000 GBP

```
Is this documented ? Is there a better way to do this I'm not thinking of ?

**Comment by rhyanki** [comment]
I found another case where print --auto can generate an invalid entry, even without any implicit prices:

```
= A
	A1  *0.5
	A2  *0.5
	A3  *-1

2020-01-01 Test
	A   $ 0.03
	B  $ -0.03
```

It gives this output, which is unbalanced:
```
$ hledger print --auto
2020-01-01 Test  ; modified:
    A           $ 0.03
    A1          $ 0.02
    A2          $ 0.02
    A3         $ -0.03
    B          $ -0.03
```

Interestingly, running `hledger balance --auto` on the original journal shows the same amounts for each account, but shows the total as 0 and throws no error.

**Comment by simonmichael** [comment]
Thanks for the example @rhyanki. I think this is indeed another example of #931 (unbalanced output because of display rounding). Let's discuss it there.

**Comment by Xitian9** [comment]
@rhyanki's example is now corrected, but the first example in this issue is still a problem.

How should this be resolved? Should we always fill in explict amounts for auto postings? That seems like a reasonable approach here.

**Comment by simonmichael** [comment]
That sounds nice and easy. I imagine it would no longer be possible to generate amountless postings with auto postings. That might bother some people for cosmetic reasons. More importantly, it might prevent generating auto postings which do balance assignments ?

**Comment by simonmichael** [comment]
Oh, auto postings with balance assignments are disallowed, so no need to worry about that. Let's try it.
