### ISSUE TITLE
hledger-web is not mobile friendly

### ISSUE THREAD

**Issue by xiaoruoruo** [simonmichael/hledger#128]
![screenshot_2013-07-21-21-19-26](https://f.cloud.github.com/assets/452520/831716/9f3e4322-f209-11e2-9568-2d28a637fb19.png)

See the screenshot taken on a 4.3-inch mobile phone using Chrome. It takes lots of scrolling to make sense of the reports or to enter new transactions.

**Comment by simonmichael** [comment]
I'll need someone else to help with this...

**Comment by simonmichael** [comment]
Needs discussion/developers, closing.
