### ISSUE TITLE
accounts --tree should support --drop

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1282]
For consistency with the improved balance commands, `hledger accounts --tree --drop 1` should work too.

**Comment by Xitian9** [comment]
This was actually what I was planning to tackle next. The question is what to do with the following account tree:
```
a
b:c
```
If we call `hledger accounts --tree --drop 1`, should this display
```
...
c
```
or just
```
c
```
?

**Comment by simonmichael** [comment]
Hmm. I think we shouldn't remove them from balance reports, since we could be hiding important amounts and changing the meaning of the report based on an option that seems to be just cosmetic.

For the accounts command, maybe it doesn't make sense to show a bunch of ellipses, but again it's a cue that there are actually some accounts there which we've obscured with our cosmetic fiddling, and it'd be consistent.

**Comment by Xitian9** [comment]
Is there more to be done here? If not, this issue can be closed.
