### ISSUE TITLE
Colour support when piping

### ISSUE THREAD

**Issue by kumo** [simonmichael/hledger#1296]
Hello, according to the [documentation](https://github.com/simonmichael/hledger/blob/1425301a8ca2f09a1884e8e602ae3575b271cff9/hledger/Hledger/Cli/Commands/Balance.md) for the _balance_ command, colour support is disabled if the output is being piped or redirected, but in the same document, it also also suggests using _less_ with colour support, if the report is too wide. Is there anyway to force colour support when piping? Alternatively, perhaps the documentation should be updated to remove the colour support suggestion for _less_.

**Comment by simonmichael** [comment]
Good catch, thanks for the report. The relevant docs:

- https://github.com/simonmichael/hledger/blob/1425301a8ca2f09a1884e8e602ae3575b271cff9/hledger/Hledger/Cli/Commands/Balance.md#colour-support
- the line above https://github.com/simonmichael/hledger/blob/1425301a8ca2f09a1884e8e602ae3575b271cff9/hledger/Hledger/Cli/Commands/Balance.md#budget-report

Would someone like to fix this, and maybe fill out our colour support according to best practices ? Eg, provide flags to force colour on or off, and respect the NO_COLOR environment variable, https://no-color.org .

**Comment by simonmichael** [comment]
And what is the best/standard UI for this ? --color & --no-color ? --color=always|never|auto ? --color=yes|no|auto ?

**Comment by simonmichael** [comment]
Among haskell tools, I've found: in stack and ghcid, it's --color|colour = always|never|auto. In ghc it's -fdiagnostics-color=always|never|auto.

**Comment by simonmichael** [comment]
Actually I've been wanting this for a long time, and it's in line with the [ROADMAP](https://hledger.org/ROADMAP.html#priorities), so I've just added this, any testing welcome. Updated docs:

- https://hledger.org/hledger.html#colour-support
- https://hledger.org/hledger.html#budget-report (line above)
- https://hledger.org/hledger.html#environment
