### ISSUE TITLE
<tab> after commodity name parsed as part of the commodity (was: MixedAmount failed to normalize)

### ISSUE THREAD

**Issue by odavy37** [simonmichael/hledger#1301]
Hi team,

here is the bug.

command: 

hledger roi --inv "Stocks" --pnl "Income|Expenses|Unrealized-Gains" -f ledger.dat -Y

Output:
hledger: MixedAmount failed to normalize
CallStack (from HasCallStack):
  error, called at .\\Hledger\\Cli\\Commands\\Roi.hs:239:10 in hledger-1.18.1-GpiMbnmwgQi7APT1hGKyyM:Hledger.Cli.Commands.Roi

Root cause: 1 TAB at the end of the second split (after EUR) of the following transaction

2020-07-21 Versement de fond
	* Assets:0102-Actifs Productifs:07-Stocks:XXXXX:CT-Olivier:Liquidites    	-1600 EUR
	! Assets:0101-Actifs Improductifs:01-Comptes de depots:02-XXXXX-CCP joint		1600 EUR	

The error message should be more explicit to make it easy to fix the error.

Best regards,

**Comment by simonmichael** [comment]
@odavy37 thanks for the report. I haven't been able to reproduce it yet, eg with a TAB after the second EUR:
```
2020-07-21 Versement de fond
  * Assets:0102-Actifs Productifs:07-Stocks:XXXXX:CT-Olivier:Liquidites      -1600 EUR
  ! Assets:0101-Actifs Improductifs:01-Comptes de depots:02-XXXXX-CCP joint   1600 EUR	

comment
$ hledger -f a.j roi --inv "Stocks" --pnl "Income|Expenses|Unrealized-Gains" -Y
+---++------------+------------++---------------+----------+-------------+-----++-------+-------+
|   ||      Begin |        End || Value (begin) | Cashflow | Value (end) | PnL ||   IRR |   TWR |
+===++============+============++===============+==========+=============+=====++=======+=======+
| 1 || 2020-01-01 | 2020-12-31 ||             0 |    -1600 |       -1600 |   0 || 0.00% | 0.00% |
+---++------------+------------++---------------+----------+-------------+-----++-------+-------+
```
Could you give a short journal that reproduces it ?

I'm surprised that you see that "CallStack" text there, since the error call looks like:
```
error' =
#if __GLASGOW_HASKELL__ < 800
  error
#else
  errorWithoutStackTrace
#endif
```

Cc @adept.

**Comment by odavy37** [comment]
Dear Sir,

thank you for your answer.
 Here is a file that generates the error output. It seems to be linked with the next transaction: without it no error, stack error with it.

Regards,



Example with the TAB at the end of the 2nd split of the first transaction, and the second transaction (to generate the error). Uploaded in zip file

windows 10 command line
X:\account>hledger -f stack_error.dat roi --inv "Stocks" --pnl "Income|Expenses|Unrealized-Gains" -Y
hledger: MixedAmount failed to normalize
CallStack (from HasCallStack):
  error, called at .\\Hledger\\Cli\\Commands\\Roi.hs:239:10 in hledger-1.18.1-GpiMbnmwgQi7APT1hGKyyM:Hledger.Cli.Commands.Roi

file content:

2020-07-21 Versement de fond
	* Assets:0102-Actifs Productifs:07-Stocks:xxxx:CT-Olivier:Liquidites    	-1600 EUR
	! Assets:0101-Actifs Improductifs:01-Comptes de depots:02-yyyy-CCP joint		1600 EUR	
	
; import Stock value at 2020-07-22
2020-07-22 Valeur liquidative de la part au prix du marche, en fin d'annee pour la methode TWRR
	Assets:0102-Actifs Productifs:07-Stocks:Unrealized Liquidity:Cost value 	 	= EUR -10000
	Assets:0102-Actifs Productifs:07-Stocks:Unrealized Liquidity:Market value 	 	= EUR 11000
	Equity:Unrealized-Gains or Losses


[stack_error.zip](https://github.com/simonmichael/hledger/files/4986154/stack_error.zip)

**Comment by simonmichael** [comment]
Thank you odavy37. (Tip: you can use ```, a line containing three backticks before and after examples to preserve layout on github). I can see the error with 1.18, but it seems to have been fixed in master:
```
$ hledger-1.18 -f a.j roi --inv "Stocks" --pnl "Income|Expenses|Unrealized-Gains" -Y
hledger-1.18: MixedAmount failed to normalize
CallStack (from HasCallStack):
  error, called at ./Hledger/Cli/Commands/Roi.hs:239:10 in hledger-1.18-gpsVNPO3FQ2eHNyBC1pfv:Hledger.Cli.Commands.Roi
$ hledger -f a.j roi --inv "Stocks" --pnl "Income|Expenses|Unrealized-Gains" -Y
hledger: MixedAmount failed to normalize
```
So [installing hledger master](https://hledger.org/download.html#building-the-development-version), or the next release when it comes, should resolve this.

**Comment by adept** [comment]
@simonmichael I think the question here is why `<tab`> was parsed as part of the commodity, resulting in commodity `EUR<tab>`:

Look at `Assets` balance below, which has balances in both `EUR` and `EUR<tab>`:
```
$ h balance -f stack_error.dat
            -600 EUR        
           1600 EUR	  Assets
           1600 EUR	    0101-Actifs Improductifs:01-Comptes de depots:02-yyyy-CCP joint
            -600 EUR    0102-Actifs Productifs:07-Stocks
            1000 EUR      Unrealized Liquidity
          -10000 EUR        Cost value
           11000 EUR        Market value
           -1600 EUR      xxxx:CT-Olivier:Liquidites
           -1000 EUR  Equity:Unrealized-Gains or Losses
--------------------
           -1600 EUR
           1600 EUR
```

**Comment by adept** [comment]
Reproducible in master for 2020-07-28
