### ISSUE TITLE
Total sum is slightly off

### ISSUE THREAD

**Issue by Gioyik** [simonmichael/hledger#1303]
hello again!

I have been scratching my head on why the total sum here is `932.62` and not `932.60`. There's a way to know how it's making the calculation of if it's taking any other value to sum those `0.02`?

```
hledger bal -Y -V assets:etf
Balance changes in 2020, valued at period ends:

                ||       2020
================++============
 Assets:ETF:AAA || 138.63 USD
 Assets:ETF:BBB ||  34.94 USD
 Assets:ETF:CCC ||  80.32 USD
 Assets:ETF:DDD ||  43.28 USD
 Assets:ETF:EEE ||  34.78 USD
 Assets:ETF:FFF ||  27.15 USD
 Assets:ETF:GGG ||  34.43 USD
 Assets:ETF:HHH ||  29.25 USD
 Assets:ETF:III ||  56.16 USD
 Assets:ETF:JJJ ||  82.27 USD
 Assets:ETF:KKK ||  43.90 USD
 Assets:ETF:LLL ||  52.80 USD
 Assets:ETF:MMM ||  58.91 USD
 Assets:ETF:NNN ||  70.94 USD
 Assets:ETF:OOO ||  50.20 USD
 Assets:ETF:PPP ||  42.88 USD
 Assets:ETF:QQQ ||  51.76 USD
----------------++------------
                || 932.62 USD
```

I have another assets (stock) account where I run the same command and it makes the sum/total correctly

```
hledger bal -Y -V assets:stock
Balance changes in 2020, valued at period ends:

                  ||         2020
==================++==============
 Assets:Stock:RRR ||   555.36 USD
 Assets:Stock:SSS ||   265.13 USD
 Assets:Stock:TTT ||    85.28 USD
 Assets:Stock:UUU ||   142.88 USD
 Assets:Stock:VVV ||   347.25 USD
 Assets:Stock:WWW ||   623.56 USD
 Assets:Stock:XXX ||   773.48 USD
 Assets:Stock:YYY ||   371.35 USD
------------------++--------------
                  || 3,164.29 USD
```

Any help is appreciated

**Comment by simonmichael** [comment]
@Gioyik, it's only displaying two decimal places, but doing the sum at full precision. You're seeing an extra contribution from the hidden decimals. To see it more clearly you can increase the display precision temporarily, by adding eg:

commodity $1000.0000

**Comment by Gioyik** [comment]
hey @simonmichael thanks for the quick response. Actually what I found with making the commodity decimals longer is that my broker starts to ignore after a certain depth of decimals (this is probably part of their business model) especially with dividends reinvestments that are so fractional making the share price decimals extend a lot. hledger is more accurate and clear with the conversion, I thought it was something wrong in my entries.

thanks again
