### ISSUE TITLE
hledger-web add form error handling issues

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1311]
In current hledger-web, eg at https://demo.hledger.org, I notice some issues in the add form, maybe old, maybe new:

- you have to enter a date (there's no default)
- you have to enter a description (even though hledger doesn't require one)
- the above are checked client side, but other problems are reported after submitting the form. This is inconsistent, but I guess it's hard to avoid.
- the server side error is uninformative, eg if you post an unbalanced transaction it just says "Postings validation failed"
- the form is normally a modal dialog with the rest of the page dimmed. After a server-side error, the form is displayed inline like normal page content instead.

**Comment by Simaex** [comment]
https://demo.hledger.org/ is inaccessible

**Comment by simonmichael** [comment]
> https://demo.hledger.org/ is inaccessible

Thanks, fixed for no.

**Comment by Simaex** [comment]
Sorry I  was not precise enough. The HTTPS  version is still inaccessible (No such site at 443), HTTP is working.

**Comment by simonmichael** [comment]
Ah, me too. I'll open an issue to track that.

**Comment by simonmichael** [comment]
I believe this are essentially all fixed.
