### ISSUE TITLE
parseQuery is partial

### ISSUE THREAD

**Issue by amigalemming** [simonmichael/hledger#1312]
parseQuery is partial:
~~~~
hledger-lib> parseQuery nulldate $ T.pack "date::2020"
(*** Exception: "date::2020" gave a date parse error ()
~~~~

In hledger-web this means that entering an ill-formed query causes an Internal Server Error.
Generally, a parser should be total and return a human-readable error message in case of a parser error.
The type should be:
~~~~
parseQueryM :: Day -> Text -> Either Text (Query,[QueryOpt])
~~~~
We might maintain `parseQuery` as a partial wrapper around `parseQueryM` for compatibility,
but may add a warning.

See #1245, also #889.

**Comment by simonmichael** [comment]
WIP

**Comment by simonmichael** [comment]
So I started pulling on this piece of string, and I'm not yet sure where it will end!

There are a lot of calls to error in hledger. One big reason is to bail out when presented with a malformed regular expression, which can easily happen at runtime. For the command line tool, where we want to exit (with a decent message) at the first error, this has been fine, but it's not a good thing to have in library code and for long-running apps. Eg you only have to search for `?` or `(` to kill hledger-web's current request, showing an ugly internal server error (this issue), or to kill hledger-ui entirely. I wasn't totally aware of this since it doesn't happen to me in practice.

Solutions ? We could try to catch all those error exceptions, converting partial code into pure code. I think doing this everywhere would be asking for trouble, though it might be useful as a workaround for a partial library we depend on.

Or we can actually convert all the partial code to pure code. This is already under way, touching eg Hledger.Utils.Regex and Hledger.Query. This of course ripples outward, affecting Hledger.Reports and ultimately perhaps every part of hledger. It will mean more complicated code and numerous small api changes (lots of functions now dealing with Eithers instead of simple values). This sounds a bit unpleasant but I think that's basically unavoidable if we want to fix this. Let me know if you agree or if I'm missing some alternative.

**Comment by simonmichael** [comment]
PS so far I'm minimising api changes, instead just adding alternative total functions, generally with a `_` suffix. But to avoid doubling the code I expect at some point these should be renamed, replacing the old partial functions. If there are cases where the old partial functions are worth keeping, they'd be given a `'` suffix. Heads up for addon authors like @hpdeifel , @peti , @adept , @apauley and active hackers like @Xitian9 .

**Comment by simonmichael** [comment]
PPS here's an example of how hledger-web still calls error despite the fixes so far (getJournalR -> transactionsReport -> matchesPosting -> compileRegex):
```
127.0.0.1 - - [07/Aug/2020:09:48:57 -0700] "GET /journal HTTP/1.1" 200 - "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:79.0) Gecko/20100101 Firefox/79.0"
07/Aug/2020:09:49:03 -0700 [Error#yesod-core] this regular expression could not be compiled: "?"
CallStack (from HasCallStack):
  error, called at ././Hledger/Utils/Regex.hs:144:4 in hledger-lib-1.18.99-GUExF7Gj4vo9dcniGlJfcO:Hledger.Utils.Regex
CallStack (from -prof):
  Hledger.Utils.Regex.compileRegex (Hledger/Utils/Regex.hs:(142,1)-(145,34))
  Hledger.Utils.Regex.toRegexCI (Hledger/Utils/Regex.hs:139:1-82)
  Hledger.Utils.Regex.regexMatchesCI (Hledger/Utils/Regex.hs:104:1-38)
  Hledger.Query.matchesPosting.matches (Hledger/Query.hs:656:9-60)
  Hledger.Query.matchesPosting (Hledger/Query.hs:(648,1)-(672,46))
  Hledger.Query.matchesTransaction (Hledger/Query.hs:(701,1)-(720,50))
  Hledger.Reports.TransactionsReport.transactionsReport.ts (Hledger/Reports/TransactionsReport.hs:73:6-118)
  Hledger.Reports.TransactionsReport.transactionsReport (Hledger/Reports/TransactionsReport.hs:(69,1)-(74,35))
  Hledger.Web.Handler.JournalR.getJournalR.(...) (Hledger/Web/Handler/JournalR.hs:30:7-71)
  Hledger.Web.Handler.JournalR.getJournalR (Hledger/Web/Handler/JournalR.hs:(21,1)-(35,27))
  Yesod.Core.Types.>>=.\.\ (src/Yesod/Core/Types.hs:465:60-80)
  Yesod.Core.Types.>>=.\ (src/Yesod/Core/Types.hs:465:45-80)
  Yesod.Core.Types.>>= (src/Yesod/Core/Types.hs:465:5-80)
  Yesod.Core.Class.Yesod.defaultYesodMiddleware (src/Yesod/Core/Class/Yesod.hs:(369,1)-(373,11))
  Yesod.Core.Class.Yesod.yesodMiddleware (src/Yesod/Core/Class/Yesod.hs:296:5-44)
  Yesod.Core.Internal.Run.yesodRunner.handler (src/Yesod/Core/Internal/Run.hs:347:5-38)
  UnliftIO.Exception.catch.\ (src/UnliftIO/Exception.hs:(108,35)-(113,26))
  Control.Monad.IO.Unlift.withRunInIO (src/Control/Monad/IO/Unlift.hs:80:3-30)
  UnliftIO.Exception.catch (src/UnliftIO/Exception.hs:(108,1)-(113,26))
  UnliftIO.Exception.catchAny (src/UnliftIO/Exception.hs:125:1-16)
  Yesod.Core.Internal.Run.basicRunHandler (src/Yesod/Core/Internal/Run.hs:(67,1)-(102,9))
  Yesod.Core.Internal.Run.runHandler.\ (src/Yesod/Core/Internal/Run.hs:(189,83)-(204,17))
  Control.Monad.Trans.Resource.withInternalState (Control/Monad/Trans/Resource.hs:342:1-29)
  Yesod.Core.Internal.Run.runHandler (src/Yesod/Core/Internal/Run.hs:(189,1)-(204,17))
  Yesod.Core.Internal.Run.yesodRunner.\ (src/Yesod/Core/Internal/Run.hs:(341,53)-(344,65))
  Yesod.Core.Internal.Run.yesodRunner (src/Yesod/Core/Internal/Run.hs:(306,1)-(347,38))
  Hledger.Web.Application.yesodDispatch.helper4958 (Hledger/Web/Application.hs:31:1-34)
  Hledger.Web.Application.yesodDispatch (Hledger/Web/Application.hs:31:1-34)
  Yesod.Core.Dispatch.toWaiAppYre (src/Yesod/Core/Dispatch.hs:(104,1)-(130,54))
  Network.Wai.Middleware.Gzip.gzip (Network/Wai/Middleware/Gzip.hs:(96,1)-(135,23))
  Network.Wai.Middleware.Autohead.autohead (Network/Wai/Middleware/Autohead.hs:(12,1)-(16,38))
  Network.Wai.Middleware.AcceptOverride.acceptOverride (Network/Wai/Middleware/AcceptOverride.hs:(10,1)-(16,87))
  Yesod.Core.Dispatch.defaultMiddlewaresNoLogging (src/Yesod/Core/Dispatch.hs:222:1-83)
  Network.Wai.Middleware.RequestLogger.apacheMiddleware (Network/Wai/Middleware/RequestLogger.hs:(145,1)-(148,20))
  Network.Wai.Middleware.RequestLogger.mkRequestLogger (Network/Wai/Middleware/RequestLogger.hs:(121,1)-(142,93))
  Yesod.Core.Dispatch.mkDefaultMiddlewares (src/Yesod/Core/Dispatch.hs:(211,1)-(216,50))
  Yesod.Core.Dispatch.toWaiAppLogger (src/Yesod/Core/Dispatch.hs:(150,1)-(168,41))
  Yesod.Core.Dispatch.toWaiApp (src/Yesod/Core/Dispatch.hs:(145,1)-(147,30))
  Hledger.Web.Application.makeApplication (Hledger/Web/Application.hs:(38,1)-(45,31))
  Network.Wai.Handler.Launch.ping (Network/Wai/Handler/Launch.hs:(38,1)-(58,33))
  Network.Wai.Handler.Warp.Run.serveConnection.processRequest (Network/Wai/Handler/Warp/Run.hs:(461,5)-(527,24))
  Network.Wai.Handler.Warp.Run.serveConnection.http1 (Network/Wai/Handler/Warp/Run.hs:(443,5)-(459,53))
  Network.Wai.Handler.Warp.Run.serveConnection (Network/Wai/Handler/Warp/Run.hs:(344,1)-(532,75))
  Network.Wai.Handler.Warp.Run.fork.serve.\.\ (Network/Wai/Handler/Warp/Run.hs:328:12-75)
  Network.Wai.Handler.Warp.Run.fork.serve.\ (Network/Wai/Handler/Warp/Run.hs:(318,71)-(328,75))
  Network.Wai.Handler.Warp.Run.fork.serve (Network/Wai/Handler/Warp/Run.hs:(318,5)-(331,27))
  Network.Wai.Handler.Warp.Run.fork.\ (Network/Wai/Handler/Warp/Run.hs:(301,5)-(312,45))
  Network.Wai.Handler.Warp.setBeforeMainLoop (Network/Wai/Handler/Warp.hs:255:1-56)
  Network.Wai.Handler.Warp.setHost (Network/Wai/Handler/Warp.hs:158:1-36)
  Network.Wai.Handler.Warp.setOnException (Network/Wai/Handler/Warp.hs:165:1-50)
  Network.Wai.Handler.Launch.runHostPortFullUrl.settings (Network/Wai/Handler/Launch.hs:(208,9)-(213,30))
  Network.Wai.Handler.Warp.Settings.settingsFork (Network/Wai/Handler/Warp/Settings.hs:60:7-18)
  Network.Wai.Handler.Warp.Run.fork (Network/Wai/Handler/Warp/Run.hs:(298,1)-(334,63))
  Network.Wai.Handler.Warp.Run.acceptConnection.acceptLoop (Network/Wai/Handler/Warp/Run.hs:(258,5)-(274,26))
  Network.Wai.Handler.Warp.Run.acceptConnection (Network/Wai/Handler/Warp/Run.hs:(246,1)-(287,38))
  Network.Wai.Handler.Warp.Run.withII.\.\.\.\ (Network/Wai/Handler/Warp/Run.hs:(213,63)-(215,17))
  Network.Wai.Handler.Warp.FileInfoCache.withFileInfoCache (Network/Wai/Handler/Warp/FileInfoCache.hs:(87,1)-(91,43))
  Network.Wai.Handler.Warp.Run.withII.\.\.\ (Network/Wai/Handler/Warp/Run.hs:(213,5)-(215,17))
  Network.Wai.Handler.Warp.FdCache.withFdCache (Network/Wai/Handler/Warp/FdCache.hs:(41,1)-(44,54))
  Network.Wai.Handler.Warp.Run.withII.\.\ (Network/Wai/Handler/Warp/Run.hs:(212,5)-(215,17))
  Network.Wai.Handler.Warp.Date.withDateCache (Network/Wai/Handler/Warp/Date.hs:25:1-44)
  Network.Wai.Handler.Warp.Run.withII.\ (Network/Wai/Handler/Warp/Run.hs:(211,5)-(215,17))
  Network.Wai.Handler.Warp.Run.withII.withTimeoutManager (Network/Wai/Handler/Warp/Run.hs:(220,5)-(225,20))
  Network.Wai.Handler.Warp.Run.withII (Network/Wai/Handler/Warp/Run.hs:(209,1)-(225,20))
  Network.Wai.Handler.Warp.Run.runSettingsConnectionMakerSecure (Network/Wai/Handler/Warp/Run.hs:(200,1)-(203,62))
  Network.Wai.Handler.Warp.Run.runSettingsConnectionMaker (Network/Wai/Handler/Warp/Run.hs:(186,1)-(189,31))
  Network.Wai.Handler.Warp.Run.runSettingsConnection (Network/Wai/Handler/Warp/Run.hs:(177,1)-(181,30))
  Network.Wai.Handler.Warp.Run.runSettingsSocket (Network/Wai/Handler/Warp/Run.hs:(149,1)-(165,36))
  Network.Wai.Handler.Warp.Run.runSettings.\ (Network/Wai/Handler/Warp/Run.hs:(133,21)-(135,44))
  Network.Wai.Handler.Warp.Run.runSettings (Network/Wai/Handler/Warp/Run.hs:(129,1)-(135,45))
  Control.Concurrent.Async.catchAll (Control/Concurrent/Async.hs:873:1-16)
  Control.Concurrent.Async.concurrently'.\ (Control/Concurrent/Async.hs:(702,24)-(745,16))
  Control.Concurrent.Async.concurrently' (Control/Concurrent/Async.hs:(700,1)-(745,16))
  Control.Concurrent.Async.race (Control/Concurrent/Async.hs:(675,1)-(681,31))
  Network.Wai.Handler.Launch.runHostPortFullUrl (Network/Wai/Handler/Launch.hs:(205,1)-(220,51))
  Hledger.Web.Main.web (Hledger/Web/Main.hs:(60,1)-(109,61))
  Hledger.Cli.Utils.withJournalDo (Hledger/Cli/Utils.hs:(69,1)-(76,23))
  Hledger.Web.Main.runWith (Hledger/Web/Main.hs:(52,1)-(56,56))
  Hledger.Web.Main.hledgerWebMain (Hledger/Web/Main.hs:(38,1)-(41,14)) @(yesod-core-1.6.18-6o6FMotU5B8F8Edrh3K4o4:Yesod.Core.Class.Yesod src/Yesod/Core/Class/Yesod.hs:688:5)
```

**Comment by amigalemming** [comment]
On Fri, 7 Aug 2020, Simon Michael wrote:

> PS so far I'm minimising api changes, instead just adding alternative 
> total functions, generally with a _ suffix. But to avoid doubling the 
> code I expect at some point these should be renamed, replacing the old 
> partial functions.

You can avoid code duplication if the partial functions call their total 
counterparts and introduce the partiality by, say, 'either error id . 
totalFunc'.

Instead of the underscore suffix you could put total functions in new 
modules. Or put the total functions into the current modules and move the 
partial ones into new *.Partial modules.


Anyway, thumbs up for total functions!

**Comment by simonmichael** [comment]
@amigalemming great ideas, thanks! Necessary now because pretty much everything in MultiBalanceReport is affected..

**Comment by simonmichael** [comment]
It doesn't look right to add "Either RegexError ..." to so many functions. Now I think the better solution is to keep invalid regexps out of the core code as much as possible. So Query and Journal should always contain only valid regexps, ie the compiled Regex, instead of the "convenient" stringly Regexp type.

I think this will have less impact on the code, and be a nicer solution. It will probably be harder to introduce optionally though; all api client code will be forced to change.

**Comment by simonmichael** [comment]
The Regex type lacks many of the standard typeclass instances, which are required by most hledger data types so that we can test (Eq), sort (Ord), print debug output, serialise to json (Show, Read), force to normal form, etc. (Data, Generic, NFData..) So storing it in AccountAlias, Journal, Query, creates problems. 

Options:
- write custom instances for our types which carefully exclude the Regexes. May add a lot of boilerplate code where previously we could auto-derive. (On the upside, that might compile faster.) It could compile but still not work sensibly, eg we couldn't rely on Journal's Eq any more. Risk of failure: high.
- store the original text along with the compiled form (data SRegex { srtext :: String, srregex :: Regex }). Write instances for SRegex that work based on the String. I think there was some problem likely with this but I have forgotten it for the moment. Risk of failure: medium.
- continue the previous plan of adding the annoying Either RegexError to function types. This would permeate at least all the Hledger.Reports, but probably it wouldn't go further than that. Risk of failure: low.

This has been a big time sink so I may move forward on it slowly. Any other ideas, experiments welcome.

**Comment by Xitian9** [comment]
Option 2 is the one that seems most appealing to me. I'd like parser exception code to stay as isolated as possible.

That said, there are a few ‘should never happen’ errors that get thrown in the balance report code, mostly for empty journals and `today_` not being set. If we were wanting to handle those a bit more elegantly, we could package the RegexError with the other possible error types as part of option 3.

**Comment by simonmichael** [comment]
@Xitian9 would you want to have a go at it ? If not I'll keep chewing on it.

**Comment by simonmichael** [comment]
Or option 4:

- keep using strings, but via a newtype with only a smart constructor exported, then all code just assumes regex strings are valid as an invariant. (And would terminate if the invariant ever failed, but this shouldn't happen.) Risk of failure: low.

For me, any of 2-4 seem possible and acceptable..

**Comment by simonmichael** [comment]
I mean, none of them fill me with joy. In an ideal world, someone would all those missing instances to Regex. I'm not sure if that's possible to do in a principled way ? Probably it would require Regex itself to implement option 2.

I thought of trying another regexp library - [regex](http://hackage.haskell.org/package/regex) is the next candidate - but it has a similar problem.

**Comment by Xitian9** [comment]
Doing a little looking into it, I'm not sure it's possible to do (2) in a principled way. The value of `Regex` depends not only on the string used to construct it, but also the options used to compile it.

I have another option 5:
5. Remove the `AccountAlias` from `Journal`, keeping it somewhere separate. Journals are then assumed to have `AccountAlias`es already applied. Write custom `Show` instance for `ReportOpts` which excludes the `Regex`.

I believe `Journal` this is the only place where `Regex` appears in a data type we have sitting around. There should also be some sitting in the `Query` that can be extracted from `ReportOpts`, but the only place the derived instances are used is some debugging code for Show. I got things to compile and pass all tests after removing all instances from `ReportOpts`, `CliOpts`, and `EntryState`, just by removing two lines of code in `hledger` (which both display the options during debug).

**Comment by simonmichael** [comment]
I consider ubiquitous debug logging quite important, and don't like having to discard information from Journal that we'd need eg to implement a non-lossy journal tidying command. I'd be interested to see that code all the same.

**Comment by Xitian9** [comment]
This definitely falls into the long-term goals category, but I think it would be nice to have an AST for the Journal format. A non-lossy tidying command would then act on the AST, rather than the processed journal itself.

**Comment by simonmichael** [comment]
Isn't that what a ParsedJournal is, pretty much ? But incomplete, it needs to store all comment lines and directives.

**Comment by Xitian9** [comment]
In function, yes. Parsing the journal files is what takes the longest by far on my system, so I was hoping some speedups could be had by not requiring keeping track of state in the parser.

**Comment by amigalemming** [comment]
On Mon, 10 Aug 2020, Simon Michael wrote:

> The Regex type lacks many of the standard typeclass instances, which are 
> required by most hledger data types so that we can test (Eq), sort 
> (Ord), print debug output, serialise to json (Show, Read), force to 
> normal form, etc. (Data, Generic, NFData..) So storing it in 
> AccountAlias, Journal, Query, creates problems.

Missing instances certainly mean that the instances cannot be implemented 
in a way that is universally useful for all applications. Thus I'd say you 
implement a wrapper around Regex and implement instances as you need them. 
I.e. Option 2.

**Comment by simonmichael** [comment]
Resolved in master.
