### ISSUE TITLE
Boolean queries

### ISSUE THREAD

**Issue by amigalemming** [simonmichael/hledger#1315]
In #1246 Simon proposes "real boolean queries". This ticket may discuss the details.
Shall boolean queries try to be compatible with the current query syntax? Which features shall be maintained, which ones could be dropped?
Shall boolean queries replace current syntax? Shall it be the default e.g. in `hledger-web`?

Here an proposal:
Allow space-separated lists of query terms. Equal fields are OR'd and diferent groups of equal fields are AND'd.
This is done consistently for all fields, e.g. including `date`.
These default combinations can overridden by the operators `OR`, `AND`, `NOT` and parentheses.
In current syntax `OR`, `AND`, `NOT` would be interpreted as account names
and parentheses are interpreted as regular expressions for account names.
I propose to drop the feature that account names can specified without the `acct` prefix.
This should resolve all ambiguities.

**Comment by simonmichael** [comment]
Thanks, see also #203.

**Comment by amigalemming** [comment]
Hm, I missed that ticket.
However, from the old ticket I cannot recognize what syntax do you propose and how it should interact with regular expressions and plain lists of query terms.

**Comment by simonmichael** [comment]
To keep discussion together shall we repost your comment there and close this one ?
