### ISSUE TITLE
hledger-web sidebar displays accounts differently since 1.18

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1316]
As reported by @thielema on the mail list, master's hledger-web's sidebar was showing accounts in flat mode, making it less useful. I've now made it use tree mode. But also it's not eliding boring parents as it used to. I'm not quite sure why we see this difference in hledger-web but not in hledger. I think related code may be:

New multiBalanceReport code:
```haskell
    -- Accounts interesting for their own sake
    isInteresting name amts =
        d <= depth                                                       -- Throw out anything too deep
        && (empty_ ropts || depth == 0 || not (isZeroRow balance amts))  -- Boring because has only zero entries
      where
        d = accountNameLevel name
        balance | ALTree <- accountlistmode_ ropts, d == depth = aibalance
                | otherwise = aebalance
```

Old balanceReport code used by hledger-web 1.18:
```haskell
    -- | In an account tree with zero-balance leaves removed, mark the
    -- elidable parent accounts (those with one subaccount and no balance
    -- of their own).
    markBoringParentAccounts :: Account -> Account
    markBoringParentAccounts = tieAccountParents . mapAccounts mark
      where
        mark a | length (asubs a) == 1 && mixedAmountLooksZero (aebalance a) = a{aboring=True}
               | otherwise = a
```

The new code allows empty_ (-E) to disable boring parent eliding, like --no-elide. I'm not sure why. I guess hledger-web forces empty_ to true, which is the difference from hledger.

**Comment by simonmichael** [comment]
@Xitian9 any thoughts ?

**Comment by simonmichael** [comment]
Here's an easier way to see the change in behaviour, via CLI:
```
$ hledger-1.18 -f tests/balance/balance-multicol.journal bal -MH --no-total date:2013/1 --tree
Ending balances (historical) in 2013-01:

            || 2013-01-31 
============++============
 assets     ||         10 
   checking ||         10 
$ hledger -f tests/balance/balance-multicol.journal bal -MH --no-total date:2013/1 --tree
Ending balances (historical) in 2013-01:

                 || 2013-01-31 
=================++============
 assets:checking ||         10 
```

**Comment by Xitian9** [comment]
Is 1.18 correct? The posting in assets is on 2013-02-02, so would seem to be excluded by the date constraint.

**Comment by Xitian9** [comment]
It seems true that the behaviour in master differs from the behaviour in 1.18. That said, I think the behaviour in 1.18 is slightly counter-intuitive, and what we need is to think properly about what is displayed in each case.

The reason I think the old behaviour is a bit weird is that `--empty` will always display any account with any postings, even if those postings sum to zero. However, if it is a ‘boring parent account’, then it will suddenly not be displayed. This will not happen for a ‘boring leaf account’. From the journal file posted below, run `hledger balance --empty` will display `zero-leaf` but not `zero-branch`, which seems strange.

Here is a quick journal file which I believe has every combination of attributes, so you can test for yourself what happens in each case.
```
account full-fork
account full-fork:full-branch
account full-fork:full-branch:full-leaf
account full-fork:full-leaf2
account zero-fork
account zero-fork:zero-branch
account zero-fork:zero-branch:full-leaf
account zero-fork:full-leaf2
account empty-fork
account empty-fork:empty-branch
account empty-fork:empty-branch:empty-leaf
account empty-fork:full-leaf2
account zero-leaf
account empty-leaf

2020-01-01
    (full-fork)                          1
    (full-fork:full-branch)              1
    (full-fork:full-branch:full-leaf)    1
    (full-fork:full-leaf2)               1

2020-01-01
    (zero-fork)                          0
    (zero-fork:zero-branch)              0
    (zero-fork:zero-branch:full-leaf)    1
    (zero-fork:full-leaf2)               1

2020-01-01
    (empty-fork:empty-branch:full-leaf)  1
    (empty-fork:full-leaf2)              1

2020-01-01
    (zero-leaf)                          0
```

**Comment by Xitian9** [comment]
Perhaps something more systematic. All accounts are either forks, branches, or leaves. (Considering an account tree as a directed graph pointing from the root, leaves are those with out-degree 0, branches those with out-degree 1, and forks those with out-degree greater than 1.)
Every account can have no postings, postings but zero (exclusive) balance, or postings with non-zero (exclusive) balance. This makes 9 total possibilities.

# Display matrices

This shows whether an account is displayed or not in `hledger balance -f <the above journal file>` with the appropriate options. `Y` means it is displayed, `N` means it is not, `2` means it is displayed if and only if more than one of its immediate descendents is displayed (this only applies for forks), and `1` means it is displayed if and only if one or more if its descendents are displayed (this applies only for forks and branches).

## `--flat`, hledger-1.18 and master

|  | No postings | Zero balance | Nonzero balance
|----|-----|------|-----------
| fork      | N | N | Y
| branch | N | N | Y
| leaf      | N | N | Y

## `--flat --empty`, hledger-1.18 and master

|  | No postings | Zero balance | Nonzero balance
|----|-----|------|-----------
| fork      | N | Y | Y
| branch | N | Y | Y
| leaf      | N | Y | Y

## `--tree`, hledger-1.18 and master

|  | No postings | Zero balance | Nonzero balance
|----|-----|------|-----------
| fork      | 2 | 2 | Y
| branch | N | N | Y
| leaf      | N | N | Y

## `--tree --no-elide`, hledger-1.18 and master

|  | No postings | Zero balance | Nonzero balance
|----|-----|------|-----------
| fork      | 1 | 1 | Y
| branch | 1 | 1 | Y
| leaf      | N | N | Y

## `--tree --empty`, hledger-1.18

|  | No postings | Zero balance | Nonzero balance
|----|-----|------|-----------
| fork      | 2 | 2 | Y
| branch | N | N | Y
| leaf      | N | Y | Y

## `--tree --empty`, master, and `--tree --empty --no-elide`, hledger-1.18 and master

|  | No postings | Zero balance | Nonzero balance
|----|-----|------|-----------
| fork      | 1 | 1 | Y
| branch | 1 | Y | Y
| leaf      | N | Y | Y

# Differences

Looking at these, you can see that the only difference is in `--tree --empty`. Let me know what your thoughts are about what the desired behaviour is.

**Comment by Xitian9** [comment]
Relating all this back to the original issue, my general feeling is that the points above aside, the problem is probably in hledger-web using `--empty` in the first place. Do you know why this is necessary? The compound balance reports originally did the same thing, basically just so there were the same columns in each report. I ended up rewriting the code so that `--empty` was only used in the necessary part and not elsewhere, hence not breaking boring parent ellision. I was not 100% satisfied with the workaround. If hledger-web is doing the same thing, maybe there's a more principled solution which will resolve both.

**Comment by amigalemming** [comment]
I am happy with adjusting display details of `hledger-web` through command-line options. However, `hledger-web` currently has neither `--tree`, `--flat`, nor `--no-elide` option.

**Comment by Xitian9** [comment]
Looking briefly at the code for hledger-web, it looks like the only difference from the vanilla balance report is that the default value of `empty_` is reversed. If that's really the case, then the only issue to address is what the desired behaviour is.

**Comment by simonmichael** [comment]
Thanks - I'll look at this soon, waiting for a fresh mind to handle it efficiently.

**Comment by Xitian9** [comment]
Digesting this a bit more, I think a case can be made that, despite some minor conceptual ugliness, the old behaviour is reasonable. If you also come to that conclusion, let me know and I can submit a PR.

**Comment by simonmichael** [comment]
> hledger-web using --empty in the first place. Do you know why this is necessary? 

I'll answer the easy one! This is a UX choice. I intended hledger-web to be self-explanatory and configuration-free, suitable for non-technical users. I felt showing all accounts, including zero-balance ones, is the less confusing default for hledger-web users.

Great testing. These display cases get really intricate. It's a little hard to relate your tables to the on-screen behaviour I'm familiar with. When you write 1 or 2 in cells that means... the case does..? does not but should..? implement the corresponding organising principle ?

Today at least, the example given seems to me a definite and surprising display bug in 1.18, fixed by the new code in master. Here's a simpler case:
```
2012/12/31
  (assets:checking)  1

2013/1/1
  (assets:checking)  1
```
```
$ hledger-1.18 -f a.j bal -MH date:2013/1 --tree
Ending balances (historical) in 2013-01:

            || 2013-01-31 
============++============
 assets     ||          2 
   checking ||          2 
------------++------------
            ||          2 
$ hledger -f a.j bal -MH date:2013/1 --tree
Ending balances (historical) in 2013-01:

                 || 2013-01-31 
=================++============
 assets:checking ||          2 
-----------------++------------
                 ||          2 
```
I guess the historical starting balances weren't participating properly in the layout algorithm, or something. I'm going to assume the new hledger code is doing all the right things unless shown otherwise.

Now back to hledger-web: I haven't just now been able to produce a small repro of the boring parent non-eliding reported by @thielema. If someone can make one, we'll take another look at it. I found another bug, #1320.

**Comment by simonmichael** [comment]
Ha ha, I do get confused. That example is not showing wrong account balances as I was thinking. It's simply failing to elide the boring parent `assets`. It should be elided here because `assets` has zero exclusive balance in this report.

**Comment by Xitian9** [comment]
The 1 in a cell means it should be displayed only if it has an interesting child account. The 2 means it should be displayed only if it has two interesting child accounts.

I think the situation can be clarified by distinguishing two types of display: explicit display, where the account gets its own line and balance number shown, and implicit display, where the account is shown only as part of a child account, and does not get its own balance displayed. The above display charts talk about explicit display, not implicit display.

**Comment by simonmichael** [comment]
I think hledger-web master is displaying accounts like 1.18 now, or possibly better in some cases (cf #1319, #1321). How does it look to you @thielema ?

**Comment by amigalemming** [comment]
On Tue, 11 Aug 2020, Simon Michael wrote:

> I think hledger-web master is displaying accounts like 1.18 now, or 
> possibly better in some cases (cf #1319, #1321). How does it look to you 
> @thielema ?

display looks fine in hledger-web-1.19
