### ISSUE TITLE
"type: Cash" doesn't seem to work

### ISSUE THREAD

**Issue by frivoal** [simonmichael/hledger#1317]
https://hledger.org/journal.html#declaring-account-types says that `account assets:bank  ; type: Cash` is a thing that should work. Actually adding this directive to a journal gives me an error:

```
$ hledger cashflow
hledger: in file included from ***redacted***,
***redacted***:3:1:
  |
3 | account assets:bank  ; type: Cash
  | ^
invalid account type code Cash, should be one of A, L, E, R, X, ASSET, LIABILITY, EQUITY, REVENUE, EXPENSE
```

I'd like to use this to limit which accounts are considered cash for cashflow reports, but no luck so far.

```
$ hledger --version
hledger 1.18.1
```

**Comment by simonmichael** [comment]
The default web manuals are for hledger master; see the versions at the top.
