### ISSUE TITLE
Extract implied conversion rates from multi-currency ledger and dump to file

### ISSUE THREAD

**Issue by tphyahoo** [simonmichael/hledger#132]
Context: https://github.com/simonmichael/hledger/issues/131

I'm proposing a feature to extract currency conversion information from a ledger and dump it to a currency-conversions-txt file, which can then be utilized by the print --numeraire command.

hledger -f myledger.ledger dump-implied-conversions > currency-conversions.txt

The file can be hand-edited with additional, or changed information, if desired.

      prior to upgrade to --require-balanced=true ledgers, information can be extracted from entries such as
        2013/01/01  exchange dollars for euros at 1.4USD/EUR
          assets:cash  EUR100 ;
          assets:usd   -USD140
      post upgrade, information can still be extracted from entries such as
      2013/01/01  exchange dollars for euros at 1.4USD/EUR
	assets:cash   EUR100
	FIXME        -EUR100
	assets:cash   -USD140
	FIXME        140USD
      It could also be extrated from the food purcahse example

	2013/01/01  Canadian in the USA Buys food with US dollars (1 USD = 1.30 CAD)
           assets:cash          -USD40
           equity:forex         USD40
           equity:expense:food  CAD52
           equity:forex         -CAD52

**Comment by simonmichael** [comment]
Needs discussion/developers, closing.
