### ISSUE TITLE
lib: Parsing numbers breaks when there are more than 255 decimal places

### ISSUE THREAD

**Issue by Xitian9** [simonmichael/hledger#1329]
A pretty dumb example, but consider the following journal file.
```
2012/12/31
  (a)  1.555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555
  (b)  1.5555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555
```
Run `hledger bal` on this and you get the following result:
```
                   2  a
15555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555  b
--------------------
15555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555557
```
Note that it thinks the precision of the balance in account `b` is 256. `roundTo` takes a `Word8` as input, so it thinks the precision is 0 and this is a whole number.

**Comment by simonmichael** [comment]
Ha, perfect! Or even print:
```
$ hledger -f a.j print
2012-12-31
    (a)                                                                                                                                                                                                                                                                    2
    (b)    15555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555

```

**Comment by simonmichael** [comment]
So the current advice would be: don't ever write more than 255 decimals or reports will print nonsense. I guess I knew that in theory but it's nice to confirm it.

**Comment by Xitian9** [comment]
I guess fixing this problem also requires a bit more parser logic. The question is what is the right behaviour when you encounter a number with more than 255 decimal points?
- Truncate
- Round
- Fail

My inclination is to go with `fail`. I doubt there's an actual use case for such high precision, and if there is it's likely to encounter other bugs. We can fail with a clear message, and if somebody complains we can decide what the right behaviour is based on that use case.

**Comment by simonmichael** [comment]
Yes exactly, for now the parser should fail (abort parsing with an error, not just fail the current parse branch and try another). "Could not parse a number with 256 decimal digits: 1.55555... Sorry, we do not support more than 255 decimal digits at this time." or similar.

**Comment by Xitian9** [comment]
The parser now fails when more than 255 decimal digits are given, and there are no plans to support such a thing. I think this issue can be closed now.
