### ISSUE TITLE
offer SUSPENSE item to correct ledger add commands with non balancing transactions

### ISSUE THREAD

**Issue by tphyahoo** [simonmichael/hledger#133]
Current behavior:

  In the following transcript, hledger reports

  "could not balance this transaction (real postings are off by USD100)"

  and requires re-entry of transaction from the start.

Suggested behavior:

  hledger states: "could not balance this transaction (real postings are off by USD100)"
  but then asks: "re-enter transaction (R) or force balance using suspense account (FB)"
   if user chooses R, behavior is same as current
  if user chooses FB, hledger prompts
  account 4 [SUSPENSE]: <can be edited by user. other possible account maes: FIXME, WHATISTHIS, etc.>
  amount  4 [-USD100]:  <can be edited by user, although it seems odd to require more than one suspense account. but no reason to forbid this.>

more complete trancript (of current behavior, showing the problem) follows below:

```
$ hledger -f test.ledger add

Adding transactions to journal file "/Users/thomashartman/test.ledger".
To complete a transaction, enter . (period) at an account prompt.
To stop adding transactions, enter . at a date prompt, or control-d/control-c.
date, or . to end [2013/07/27]:
description []: win lotto
Similar transactions found, using the first for defaults:

[ 11%] 2013/07/27 found money again
    assets:cash:found_on_sreeet        USD200
    equity                            USD-200

account 1 [assets:cash:lotto]:
amount  1 [USD200.0]: USD1000
account 2 [equity]:
amount  2 [USD-1000.0]: -USD900
account 3, or . to record: .

could not balance this transaction (real postings are off by USD100)
2013/07/27 win lotto
    assets:cash:found_on_sreeet       USD1000
    equity                            USD-900

please re-enter.
account 1 [assets:cash:found_on_sreeet]:
```

**Comment by simonmichael** [comment]
Needs discussion/developers, closing.
