### ISSUE TITLE
hledger-ui crashes on malformed regular expression

### ISSUE THREAD

**Issue by Xitian9** [simonmichael/hledger#1338]
The problem comes from `queryFromOpts` and `queryOptsFromOpts`.

https://github.com/simonmichael/hledger/blob/5b647902c9f89b84ce814dec5bdc50778c82a153/hledger-lib/Hledger/Reports/ReportOptions.hs#L465-L469

Basically, we need to reckon with the fact that generating a `Query` from a `ReportOpts` might yield a `RegexError`. I can see three options:
1. Regex errors are handled as `None` (or some other Query). The disadvantage is that users won't get a warning on a malformed Regular expression.
2. Functions which call `query(Opts)?FromOpts` return `Either RegexError a` instead of `a`. The disadvantage is that this means functions like `multiBalanceReport` and `compoundBalanceReport` meet these criteria, and we went to a lot of effort to avoid this. (On the plus side, `(multi|compound)BalanceReportWith` are fine).
3. We store the parsed `Query` and `[QueryOpt]` inside `ReportOpts` itself, rather than the `String` that it will be parsed from. The disadvantage is that this is the biggest interface change. The advantage that we can stop passing around both `ReportOpts` and `Query` in lots of places (a quick grep reveals at least 15 functions with `ReportOpts -> Query ->`). This would also remove any ambiguity about whether you should use the `Query` or `ReportOpts`.

My inclination is to go with 3, and move the `queryFromOpts` logic into `rawOptsToReportOpts`. We should probably store all three of `queryFromOpts`, `queryFromOptsOnly`, and `queryOptsFromOpts`. Maybe we can use some friendlier names. Thoughts?

**Comment by Xitian9** [comment]
Interestingly, `queryFromOptsOnly` is used in only two places (Hledger.Cli.Commands.Add and Hledger.Cli.Commands.Registermatch), and in both places replacing it with `queryFromOpts` doesn't cause any tests to fail. Is it necessary to have this at all?

**Comment by simonmichael** [comment]
Argh, more deep-rooted partiality (sorry!). 

This will be something to explore for next release I think, unless we want to implement 1 in hledger-ui as an interim fix.

**Comment by Xitian9** [comment]
I don't use `hledger-ui`, so I have no strong opinions about whether to implement 1 in the interim. It's a simple change, the only disadvantage I can think of is the lack of error message for people using `hledger-cli`.

**Comment by simonmichael** [comment]
It seems we have implemented 1 (ignore malformed regular expressions) since hledger 1.20. Eg hledger-1.19 exits if you filter on `\` or `?`, while hledger-1.20+ ignores the attempted filter.

I think in other situations like this we continue but also show an error message, which seems optimal. Perhaps that was only in hledger-web ? But this bug is indeed fixed, in that it no longer crashes.

**Comment by simonmichael** [comment]
PS I tried `^` and `$` also, but apparently these are not considered malformed regular expressions.
