### ISSUE TITLE
hGetContents: invalid argument (invalid byte sequence)

### ISSUE THREAD

**Issue by yurivict** [simonmichael/hledger#1346]
Build fails on FreeBSD 11: http://beefy9.nyi.freebsd.org/data/113amd64-default/547401/logs/hs-hledger-ui-1.18.1_1.log

```
Hledger/Cli/DocFiles.hs:44:6: error:
    * Exception when trying to run compile-time code:
        /wrkdirs/usr/ports/finance/hs-hledger-ui/work/hledger-ui-1.18.1/hledger-1.18.1/embeddedfiles/hledger.info: hGetContents: invalid argument (invalid byte sequence)
      Code: embedFileRelative "embeddedfiles/hledger.info"
    * In the untyped splice:
        $(embedFileRelative "embeddedfiles/hledger.info")
   |
44 |     ,$(embedFileRelative "embeddedfiles/hledger.info")
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build hledger-1.18.1 (which is required by exe:hledger-ui
from hledger-ui-1.18.1).

*** Error code 1
```

Resolution of the same problem in another Haskell project: https://github.com/koalaman/shellcheck/issues/324

**Comment by simonmichael** [comment]
@yurivict isn't this the same as #1332 you reported two weeks ago ?

**Comment by yurivict** [comment]
>  isn't this the same as #1332 you reported two weeks ago ?

The error message is the same, but the previous one was fixed by setting ```USE_LOCALE=C.UTF-8``` and this one occurs with this setting on.

**Comment by simonmichael** [comment]
Is that locale installed ? Eg I believe `locale -a | grep $LANG` should show it.

**Comment by simonmichael** [comment]
Or since you're using USE_LOCALE which I don't know - try setting LANG instead.

**Comment by simonmichael** [comment]
Maybe https://unix.stackexchange.com/questions/485073/how-to-backport-freebsd-13-current-c-utf-8-locale-to-11-2-release is relevant.

**Comment by yurivict** [comment]
Thanks for this link. It seems that the C.UTF-8 locale isn't available in FreeBSD 11 (which is an older version still in support). I marked hs-hledger* ports broken on FreeBSD 11. Now they work on FreeBSD 12 and FreeBSD 13 (CURRENT).

**Comment by simonmichael** [comment]
Just by the way, if not C.UTF-8 isn't there some other UTF-8 locale available that would allow freebsd 11 folks to install hledger ?

**Comment by yurivict** [comment]
Yes, yesterday I updated the port to en_US-UTF-8 that is available on 11. C.UTF-8 was added later and isn't in 11. I didn't know this before.

**Comment by simonmichael** [comment]
Great work, thanks for packaging hledger on FreeBSD @yurivict.

**Comment by yurivict** [comment]
You are welcome, thanks for developing hledger.
