### ISSUE TITLE
truncated numbers in register command

### ISSUE THREAD

**Issue by RobertNielsen1** [simonmichael/hledger#1349]
After upgrading to 1.19, I am seeing truncated numbers with the register command. 

For example, using the file:

; begin file  *************************
2019/06/24 Acme Groceries
    Expenses:Groceries                        $36.90
    Liabilities:Credit Card B

2019/06/30 Paycheck
    Income:Job                               -$200.00
    Assets:Savings
; end file *****************************

A command such as

hledger reg

Gives the following output:

2019-06-24 Acme Groceries                                      Expenses:Groceries                                        $36.90        $36.90
                                                               Liabilities:Credit Card B                           ..6.90             0
2019-06-30 Paycheck                                            Income:Job                                          ..0.00  ..0.00
                                                               Assets:Savings                                           $200.00             0

I am running the command from bash on a Mac. 

I have tried changing the font size, but I still get the truncated numbers (for example "..6.90" instead of "36.90").

Thank you!

Rob

**Comment by simonmichael** [comment]
Good catch, thanks for the report. This is related to #1345 and is fixed in master, to be released shortly.

**Comment by simonmichael** [comment]
Fixed by 1.19.1.
