### ISSUE TITLE
balance --format in color mode can over-truncate or print corrupted ANSI codes

### ISSUE THREAD

**Issue by Xitian9** [simonmichael/hledger#1352]
Call `hledger balance --format "%.7(total)"` on the following journal file.
```
2020-09-01 Test
    a  -500 AAA
    b
```
The result is:
```
..[m
500 AAA
-------
0
```

The problem is that `takeWidth` is not aware of ansi escape sequences, and so will mangle any which are there.

I think perhaps maximum width should be ignored when formatting amounts. I can't think of an example where you'd want to clip an amount, and this is what the fancier mixedAmount ellision functions are for.

**Comment by simonmichael** [comment]
Ouch, another one. Good catch. 1.18 does this which was more correct I assume:
```
$ hledger-1.15 -f a.j bal -N --format "%.7(total)"
..AA
500 AAA
```

**Comment by simonmichael** [comment]
I suppose dropping the --format feature is out of the question...

**Comment by simonmichael** [comment]
1.18's output doesn't look very correct either. Here's what it's supposed to be when there are no ANSI codes messing things up (the amount is elided to a maximum of 7 characters):
```
$ hledger bal -N a --format "%.7(total)" --color=never
..0 AAA
```

**Comment by Xitian9** [comment]
Yes, I don't think this was ever handled correctly, as it would take some fancy logic to handle it correctly, and it would be strange for that to be removed.

Handling this correctling would involve:
1. Stripping ansi escape codes
2. Clipping the resulting ouptut
3. Re-inserting ansi escape codes in the appropriate places (which is tricky to even define)

Alternately, you could teach `takeWidth` to handle ansi escape codes, but it would have to know how to recognise them forwards and backwards.

Both of these options seem like a lot of work for something of questionable value in the first place. I propose that maximum widths on fields containing `MixedAmount` are not honoured.

**Comment by Xitian9** [comment]
Version 1.18.1 will also give you ansi escape garbage.

```
$ hledger balance -N a --format "%.4(total)"
..[m
```

**Comment by Xitian9** [comment]
Options I can think of:
1. Do not honour maximum width on `%(total)`
2. Calling maximum width on `%(total)` turns off colour
3. Document a warning that using a maximum width for `%(total)` may do bad things, and is not recommended unless you turn off colour

**Comment by simonmichael** [comment]
2 sounds good to me (--format always disables colour), with a note in the docs.

**Comment by Xitian9** [comment]
`--format` disabling colour is conceptually simpler, though there are no problems displaying colour when no maximum width is given for `%(total)`. The technical solution is simple in either case. Would you go for strictly more functional or conceptually simpler?

**Comment by simonmichael** [comment]
Yes simpler/easier to intuit if someone hits in in the wild. But this is not used often and we can document it (we'll probably need to mention it in both --format and --colour's manual sections). So yes just the minimal restriction would be fine too. 

Formatting coloured amounts seems to partly work, except for this one case where the maximum width is too narrow. I wonder if it's possibly a small fix.

**Comment by Xitian9** [comment]
This should be solved now.
