### ISSUE TITLE
Auto postings not reflected in hledger-web until cleared / account not appearing in accounts list

### ISSUE THREAD

**Issue by rkelly** [simonmichael/hledger#1355]
I started using an auto posting rule which helps completes transactions that pass through to my checking account.

```
= liability:card
    liability:card  *-1
    asset:checking  *1
```

This allows me to enter simpler transactions like this:

```
2020-09-14 ! buy milk
    expense:groceries  $4.00
    liability:card
```

This transaction should expand to this:

```
2020-09-14 ! buy milk
    expense:groceries  $4.00
    liability:card  $-4.00
    liability:card  $4.00
    asset:checking  $-4.00
```

If I start `hledger-web`, and look under asset:checking, I'd expect to see the above transaction. However it doesn't appear. Only when I clear the transaction with the asterisk, does it appear.

This makes it difficult to estimate future cash flow in accounts affected by auto postings. Took a while to realize why my pending balances were so high--these auto posting expenses weren't showing up.

Command-line `hledger` doesn't seem to be affected like this. Just `hledger-web`. Does it only process auto postings for cleared transactions?

**Comment by simonmichael** [comment]
Thanks for the report. This seemed to work more or less as expected for me with current hledger:

```
$ hledger-web -f a.j --auto
...
```
![Screen Shot 2020-09-14 at 4 36 41 PM](https://user-images.githubusercontent.com/10144/93148391-7e2c6a00-f6a8-11ea-9cac-0a5b122a975a.png)

The --auto flag is required, as with hledger CLI. 

But I'm not sure why the liability:card account is not displayed in the accounts list.

**Comment by rkelly** [comment]
Looks like I had failed to add the --auto flag to my hledger-web launch script. That seems to do it for me. Thank you, Simon.

I hadn't noticed the lack of the target account in the accounts list.

**Comment by simonmichael** [comment]
Great. Let's leave this open to follow up on that.

**Comment by simonmichael** [comment]
>  I'm not sure why the liability:card account is not displayed in the accounts list.

I can't reproduce this (tested back to hledger-web 1.9). No problem here, we can move along.
