### ISSUE TITLE
hledger-ui: VS Code line number support

### ISSUE THREAD

**Issue by levitanong** [simonmichael/hledger#1359]
VSCode supports opening a file at a specific line number and character position via this pattern:
```sh
code --goto FILE:LINE:COL
```
It would greatly improve UX between hledger and vscode if this were supported for hledger-ui's runEditor function. See: https://github.com/simonmichael/hledger/blob/master/hledger-ui/Hledger/UI/Editor.hs

I would fork and try it out, but I'm unfamiliar with haskell, and I'm pretty sure what would take an expert 15 minutes would take me a week to figure out. 😆

**Comment by simonmichael** [comment]
@levitanong, what would hledger-ui see in $EDITOR if you have configured VS Code as your editor there ?

**Comment by levitanong** [comment]
You mean what would be the result of `echo $EDITOR`? That would be `code`.

**Comment by simonmichael** [comment]
Thanks, and do the following also work ?

- `code --goto FILE:LINE`
- `code --goto FILE`
- a way to go to FILE's last line ?

**Comment by simonmichael** [comment]
Ah I found a way to test;  the first two do work. I have pushed VS Code positioning support to master, maybe you could test ?

**Comment by simonmichael** [comment]
PS not 15 minutes, but 105 minutes..

**Comment by levitanong** [comment]
I just tried it out. Hurrah! It works perfectly! Thanks so much!

PS oof, I need to work on my estimation skills 😅
