### ISSUE TITLE
bash, zsh, *sh auto-completion support

### ISSUE THREAD

**Issue by legrostdg** [simonmichael/hledger#136]
It would be great to provide a bash-completion file to  auto-complete on the command line...
##

**Comment by btittelbach** [comment]
There is already a great completion file for zsh.
Maybe some person still using bash could adapt it. :)
https://github.com/zsh-users/zsh-completions/blob/123a4007201c81eb9bc5785d5bac8d9b4d8709ec/src/_hledger

**Comment by ony** [comment]
@simonmichael you are right about support for `bash`. But it requires `processArgs` to be actively used to handle special calls for completion.

**Comment by fdw** [comment]
I can't seem to find a working completion for zsh. Is there any news regarding this topic?

**Comment by simonmichael** [comment]
@fdw, does the one @btittelbach mentioned not work ?

**Comment by fdw** [comment]
@simonmichael No :( For some reason, it isn't included in the current version of zsh-completions anymore.

**Comment by simonmichael** [comment]
I don't know anything about zsh, perhaps you could investigate.. ?

**Comment by simonmichael** [comment]
@fdw thanks for helping. Maybe it's a matter of contacting someone to get a license added to something ? If you have motivation for it you're the best person we have :)

**Comment by fdw** [comment]
As you can see in https://github.com/zsh-users/zsh-completions/pull/586 and https://github.com/zsh-users/zsh-completions/pull/587, I was successful :)

**Comment by simonmichael** [comment]
Good work! Close this when you think appropriate.

**Comment by legrostdg** [comment]
This bug is about bash completion, so I don't think this should be closed. Even for zsh completion, the best way to get completion would be to adapt the usage of cmdargs to generate it automatically. Without this, we will get outdated scripts as soon as the command line api changes.

**Comment by legrostdg** [comment]
@ony proposed a (beginning of a) solution

**Comment by fdw** [comment]
zsh now has a working, extensive completion :)

Do you think it would make sense to include it with hledger, so as too keep it up to date?

**Comment by simonmichael** [comment]
@legrostdg good point. The zsh stuff should probably have been a new issue. To save time and since they might be a bit related I'm just going to generalise this issue. Anyone interested in improving *sh completions for hledger, please send proposals/PRs.

**Comment by simonmichael** [comment]
Status ?
> I think... #136 was a request for bash auto completions of any kind, then I started a discussion of generating them from the command line options. And it looks like you worked on this ? But I didn't merge it ? And much later, @schoettl made bash completions manually, which are the ones we currently provide in /shell-completions/

**Comment by simonmichael** [comment]
Bash shell completions for `hledger` were added to the project repo in 2021 by @schoettl. Closing this issue, see #986 for more recent discussion.
