### ISSUE TITLE
Color output causes misalignment

### ISSUE THREAD

**Issue by visika** [simonmichael/hledger#1361]
I'm on Manjaro XFCE with hledger 1.19, using any terminal produces the issue.

Displaying values with negative sign in red makes them misaligned.
I tried using `--color=no` and the issue disappeared.

![hledger month color](https://user-images.githubusercontent.com/2254049/94620479-01f07400-02af-11eb-835f-8ab6edf17319.png)

![hledger month no color](https://user-images.githubusercontent.com/2254049/94620486-0583fb00-02af-11eb-9f61-bfe9087d79ca.png)

**Comment by simonmichael** [comment]
Thanks for the report. It's fixed in 1.19.1.
