### ISSUE TITLE
bad import breaking hledger-web

### ISSUE THREAD

**Issue by haskellGardener** [simonmichael/hledger#1362]
Please change 

import Hledger.Web.Options (version) 

to

import Hledger.Web.WebOptions (version)

**Comment by simonmichael** [comment]
Oops, thanks!

**Comment by haskellGardener** [comment]
Unfortunately the typo persists, but in a new form. It should be **Hledger.Web.WebOptions**. I understand why typos on this name are inevitable.

**Comment by simonmichael** [comment]
Ack! Thanks for your help.
