### ISSUE TITLE
OrdPlus, why no export?

### ISSUE THREAD

**Issue by haskellGardener** [simonmichael/hledger#1369]
Is there a reason why the Hledger.Query module does not export **OrdPlus** and its constructors?
I ask because I'm using hledger-lib to perform operations on journals and **OrdPlus** is essential for querying on amounts.

**Comment by Xitian9** [comment]
I had a need for this at some point too. I ended up working around it, but it should definitely be exported.

**Comment by simonmichael** [comment]
Thanks!
