### ISSUE TITLE
Formatting tool for journal files

### ISSUE THREAD

**Issue by ajeetdsouza** [simonmichael/hledger#1372]
I'd like to add new entries via my text editor (VS Code), but I don't know of any formatter that can prettify the entries after I'm done typing it in.

For comparison, Beancount has a format script that is used by the Beancount Formatter extension.

**Comment by simonmichael** [comment]
- VS Code has the `ledger` and `hledger-vscode` extensions, and neither seems to provide that feature at the moment, as you probably found out.
- Emacs' ledger-mode can do it; eg put the cursor in an entry or select some entries and press M-q
- hledger can do it to a certain extent; eg `hledger print` your journal, or a section of it, to get formatted entries, which you could save in place of the messy ones.
