### ISSUE TITLE
"Ratio has zero denominator" error when commodity price is zero

### ISSUE THREAD

**Issue by rhyanki** [simonmichael/hledger#1373]
My hledger version is 1.19.1 on Ubuntu.

When a commodity's price in relation to another commodity is zero, either as part of a P directive or as a transaction price, the cryptic error message "Ratio has zero denominator" is sometimes thrown when the `-V` or `-X` flags are used.

Example with P directive:
```
P 2020-01-01 USD EUR 0

2020-01-02 Test
    A   EUR 1
    B  EUR -1
```

```sh
> hledger balance -f test.ledger -X=USD
hledger: Ratio has zero denominator
```

Example with transaction price:

```
2020-01-01 Test
    B  USD 1 @ EUR 0
    A  EUR 0
```

```sh
> hledger balance -f test.ledger --infer-value -X=USD
hledger: Ratio has zero denominator
```

Note that any command which doesn't use flags like `-V` or `-X` works fine. Also, converting in the other direction works fine (e.g. if you had a USD balance and used the flag `-X=EUR`, it would report zero euros as expected).

Unfortunately, the fact that it only fails in specific situations, combined with its very cryptic error message, can make it very difficult to debug (in my case, the culprit was a single P directive in a file from 2017).

Perhaps it would be better to disallow zero prices entirely, and show a specific validation error message when one is found? At the very least, I think we should show a better error message when the user requests an impossible conversion.

**Comment by simonmichael** [comment]
Thanks for the report. We were getting an exception from Decimal's `/` when trying to calculate the inverse of a zero price.

I'm not sure whether zero prices have any use, but for now we still allow them, and the inverse of a zero price is a zero price.
