### ISSUE TITLE
clarify scope of commodity directive in regard to number notation

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1375]
*https://hledger.org/journal.html#directives -> commodity -> can affect* says it affects the number notation (eg, the input decimal mark, and number parsing) of following entries in all files.

*https://hledger.org/journal.html#directives -> D -> can affect* says it affects the number notation only up to the end of the current file.

It's not clear that the first is correct, and it seems likely that these two are or should be consistent. This unclarity is making it hard to explain some hassles when changing the decimal mark while converting CSV, reported in IRC.

Related: https://github.com/simonmichael/hledger/issues/1158. (And maybe https://github.com/simonmichael/hledger/issues/1224).

**Comment by simonmichael** [comment]
Example from #hledger: 
a.csv:
```
2020-02-01;foobar;19,99
```
a.csv.rules:
```
separator ;
fields date,description,amount_
currency €

account1 expenses
account2 income

amount1 %amount_
```
```
$ hledger -f a.csv print | hledger -f - -f <(echo commodity €1 000.00) print
2020-02-01 foobar
    expenses          €19,99
    income

$ hledger -f a.csv print | cat - <(echo commodity €1 000.00) | hledger -f- print
2020-02-01 foobar
    expenses          €19.99
    income
```

**Comment by apauley** [comment]
I ran into the same (or very similar) issue while investigating possible solutions for the Paypal amount formatting issue which @sbibauw reported here:
https://github.com/apauley/hledger-flow/issues/99#issuecomment-861662683

While playing around with both ` hledger import` and `hledger print` on csv files I found a small inconsistency.

Given the same `a.csv` and `a.csv.rules` files as above, but with the commodity directive in a separate file (as is done in hledger-flow) I get the following results:

```
$ hledger import --dry-run a.csv -f directives.journal
; would import 1 new transactions from a.csv:

2020-02-01 foobar
    expenses          €19.99
    income           €-19.99
```

```
$ hledger print -f a.csv -f directives.journal
2020-02-01 foobar
    expenses          €19,99
    income
```

The commodity directive is ignored in the case of `hledger print`, but honoured in the case of `hledger import`.

hledger-flow happens to use `hledger print` internally 😔 

I see that the ["can-effect" rules](https://hledger.org/hledger.html#directives) explain that hledger explicitly only honour directives until the end of the file it is declared in, but it would have solved this particular issue nicely if I could find a way to apply directives from the extra file to `hledger print` in this example.

Alternatively, a CSV rule similar to `decimal-mark` which would apply to amount formatting in transaction **outputs** could also be useful. Although we would then ask users to declare the same thing they've already declared in a directives.journal once more in a rules file. And I see in the description of #793 that you don't really want that level of flexibility.

**Comment by simonmichael** [comment]
Yes, I fixed `commodity`'s scope in  Directives table just in the last day or two; in fact its declaration of decimal mark lasts only to the end of the current file, like the other things it declares.

Normally, because of the usual https://hledger.org/hledger.html#directives-and-multiple-files reason, the only way to have a commodity directive in file A affect file B is if A includes B.

But `import` has a special behaviour of honouring the directives in the journal you're importing to (including in a dry run).

**Comment by simonmichael** [comment]
#1593, providing a command line option to override commodity styles, is in progress. Will that be the right solution for you ? CSV rules are about reading the CSV, I don't think they should say anything about output.

**Comment by simonmichael** [comment]
I believe this has been resolved.
