### ISSUE TITLE
hledger add bug with multiple account plus large amounts

### ISSUE THREAD

**Issue by RobertNielsen1** [simonmichael/hledger#1378]
version: hledger 1.19.1
command: add

If you use the file below, and use "add" to add a next paycheck, there is a problem. When you get to the amount for Amount 3 (Tax_2), the "add" command defaults to $2002.00 instead of $1.00. 
```
; begin file
2020-10-12 Paycheck
    Income:Job     -$2,003.00       
    Tax_1                    $1.00
    Tax_2                    $1.00
    Tax_3                    $1.00
    Assets:Savings         $2,000.00
; end file
```
The problem may be related to the size of the income. For example, the following file works fine. That is, you use add to enter the next paycheck, and the amounts that add defaults to for the next paycheck are fine.
```
; begin file
2020-10-13 Paycheck
    Income:Job     -$5.00     
    Tax_1                    $1.00
    Tax_2                    $1.00
    Tax_3                    $1.00
    Assets:Savings         $2.00
; end file
```
Thank you!

Rob

**Comment by simonmichael** [comment]
That's interesting, thanks for the bug report. It's not a regression, hledger 1.1 does the same. We need someone to debug the choice of amount (either based on postings in the similar transaction, or calculated as balancing amount) in https://github.com/simonmichael/hledger/blob/master/hledger/Hledger/Cli/Commands/Add.hs#L331 .

**Comment by simonmichael** [comment]
It was confused by the thousands separator (when checking if you accepted all the defaults so far). Now it ignores the number style there.

**Comment by RobertNielsen1** [comment]
Thank you! I have plans to do a video on the add command. I came across the problem when I was doing my research (i.e., using the add command for all my data entry). Nice to see this fixed!

**Comment by simonmichael** [comment]
Good catch!
