### ISSUE TITLE
Unable to import CSV on stdin

### ISSUE THREAD

**Issue by alerque** [simonmichael/hledger#1385]
Sometime in the last few releases (since 1.18 maybe?) input file handling has changed and some of my automated workflows have died. I used to be able to compose CSV data either on STDIN (`my_commands | hledger -f -`) or as an input redirect (`hledger -f <(my_commands)`) and, also passing a CSV rules file, have it processed. In 1.19.1 this is no longer being accepted. It only works for file names ending in `.csv`. In the case of input pipipe or redirects it doesn't seem to be possible to receive this data any more.

I suggest that even if auto-discovery of the input format as before is judged as bad, there should be a CLI flag for reading non filename inputs as CSV.

**Comment by simonmichael** [comment]
@alerque thanks for the report. Could you possibly give a small repro/example ?

**Comment by simonmichael** [comment]
Oh I think I get you.. it's https://hledger.org/release-notes.html#hledger-cli-1-17 -> Drop the file format auto-detection feature ? The workaround there should help (add the `csv:` file path prefix).

**Comment by alerque** [comment]
That sounds like the trick. I guess it's been longer than I thought since I updated this particular workflow!
