### ISSUE TITLE
Typed metadata (double-colon tags)

### ISSUE THREAD

**Issue by tbm** [simonmichael/hledger#1388]
Ledger has a syntax called [typed metadata](https://www.ledger-cli.org/3.0/doc/ledger3.html#Typed-metadata).  Normal metadata (`key: ...`) is interpreted as a string whereas typed metadata (`key:: ...`) has the type of whatever the value is (`[date]`, integer, `true`/`false`, an amount).

hledger doesn't interpret the `key::` syntax and thinks that the tag starts with `:`.

I guess hledger should either support typed metadata, or if not, add something about this incompatibility to the docs.

## Test case

```
2020-07-23 * Test metadata
  ; string: foo
  ; year:: 2020
  ; amount:: 10.00 EUR
  ; date:: [2020-07-19]
  ; bool:: true
  Assets:Test                                                     10.00 EUR
  Assets:Test                                                    -10.00 EUR
```

## hledger

```
hledger -f x tags --values
: 10.00 EUR
: 2020
: [2020-07-19]
: true
foo
```

## ledger

```
ledger -f x tags --values
amount: 10.00 EUR
bool: true
date: 2020/07/19
string: foo
year: 2020
```

**Comment by simonmichael** [comment]
Thanks for pointing that out @tbm. I think it would be nice for Ledger compatibility if we treated `::` as equivalent to `:`.

**Comment by simonmichael** [comment]
Slight downside of that: we'd have to say "if you ever have a tag value beginning with a colon, put a space before it or the colon will be consumed".

**Comment by tbm** [comment]
> I think it would be nice for Ledger compatibility if we treated :: as equivalent to :.

Note that the two are not equivalent in ledger.  Typed metadata has a type.  Ledger will store the value as a date, integer, boolean, or whatever it is; whereas `:` is always a string.  This matters in ledger because ledger has a complex value expressing syntax.  I'm not sure if hledger has the concept of types or if everything is a string.

(Also, for full compatibility: `foo:: [date]` should be parsed as `foo: date`; ledger requires dates to be in the format `[date]`. (Real dates, not dates as strings).

It's probably best to give an example:

```
2020-01-01 * Test
    ; foo:: 10
    ; bar:: [2020-11-11]
    Assets:Test1           10.00 EUR
    Assets:Test2          -10.00 EUR
```

Now you can do:

```
ledger -f d bal :test1 -l "tag('foo') > 9"
           10.00 EUR  Assets:Test1
$ ledger -f d bal :test1 -l "tag('bar') > [2020-11-11]"
$ ledger -f d bal :test1 -l "tag('bar') >= [2020-11-11]"
           10.00 EUR  Assets:Test1
```

**Comment by simonmichael** [comment]
Thanks - yes I got that. hledger does not have a typed query/programming language, and our tag values are just text.

As I mentioned on #ledger: "I did implement the `::` change but I'm on the fence, I'd like to remove one more roadbump for ledger users but on the other hand adding an unexpected quirk for hledger users needs some justification."

I'm wondering whether to add support for this, on by default (affects all users), or keep it to a separate tool or --extra-ledger-compatible mode. And, especially in the first case, how far it should go. Ignore the second colon ? Process the value differently when there is a second colon, ie stripping brackets from dates ? What if it's a non-date or malformed date in brackets ? What other types exist/should be supported ? There's danger of opening a rabbit hole that doesn't benefit many users. Is it causing trouble in your real-world workflow ? More details could be motivating.

**Comment by tbm** [comment]
> There's danger of opening a rabbit hole that doesn't benefit many users

**Comment by tbm** [comment]
> There's danger of opening a rabbit hole that doesn't benefit many users

That's true.  I think it boils down again to whether ledger and hledger files are supposed to be compatible or not.  I think there's some merit in keeping compatibility (and getting the hledger specific features into ledger), but maybe it's too late for that (the tag syntax is one example where it's now impossible to maintain full compatibility without breaking things).

Then again, I don't think supporting typed metadata in hledger would be that much work.

I noticed one other difference between hledger and ledger: ledger requires a space after the colon whereas hledger does not.

So you just need to look for tag colon colon space.  And yes, if there's `[date]` you have to strip the brackets.  Otherwise nothing else should be needed.

**Comment by simonmichael** [comment]
Thanks. Would that support for ledger typed date tags be useful to you in practice, or is it more of a nice-to-have ?

**Comment by tbm** [comment]
I don't use hledger.

I came across this issue while working on beancount2ledger.

**Comment by simonmichael** [comment]
Ok. Thanks for the feature idea - I will add it if/when it's needed by a person or two.
