### ISSUE TITLE
hledger-web: Data.HashMap.Base.(!): key not found when using --forecast

### ISSUE THREAD

**Issue by erictapen** [simonmichael/hledger#1390]
I'm seeing errors on current `hledger-web` with `--forecast` enabled.

```
$ hledger-web --version
hledger-web 1.19.1

$ cat test.journal 
~ monthly
    assets    20
    income

$ hledger-web --forecast --server --file test.journal
12/Nov/2020:23:56:33 +0100 [Info#yesod-core] Application launched @(yesod-core-1.6.18-JM1djr4oyKEAZ6NmFCfuhn:Yesod.Core.Dispatch src/Yesod/Core/Dispatch.hs:163:11)
Serving web UI and API on 127.0.0.1:5000 with base url http://127.0.0.1:5000
Press ctrl-c to quit
# Here I requested http://127.0.0.1:5000/journal
12/Nov/2020:23:56:34 +0100 [Error#yesod-core] Data.HashMap.Base.(!): key not found
CallStack (from HasCallStack):
  error, called at ./Data/HashMap/Base.hs:631:16 in unordered-containers-0.2.10.0-HKJeqMHlVyVLeqMEQJExLG:Data.HashMap.Base @(yesod-core-1.6.18-JM1djr4oyKEAZ6NmFCfuhn:Yesod.Core.Class.Yesod src/Yesod/Core/Class/Yesod.hs:688:5)
...
```

In the web UI appears the same error message:
```
Data.HashMap.Base.(!): key not found
CallStack (from HasCallStack):
  error, called at ./Data/HashMap/Base.hs:631:16 in unordered-containers-0.2.10.0-HKJeqMHlVyVLeqMEQJExLG:Data.HashMap.Base
```

I'm on NixOS 20.09, so the package I'm using is `hledger-web`.

What weirds me out is that I can't find any reference to `Data.HashMap.Base` anywhere. Not in hledger code, not on hoogle, not in the [`unordered-containers`](https://hackage.haskell.org/package/unordered-containers-0.2.13.0) package.

**Comment by erictapen** [comment]
Just confirmed that this issue persists with newest `unordered-containers-0.2.13.0`.

**Comment by simonmichael** [comment]
Thanks for the report @erictapen ! This broke in hledger-web 1.18 and went unnoticed. Now fixed in master.

.Base is probably an internal module, the symbol gets re-exported and used as Data.HashMap.(!).

Why didn't we notice ? hledger-web had a test suite, but it was useless and I disabled it in 2018. I'll enable it and make it a bit more effective.

**Comment by erictapen** [comment]
Thank you very much. I can confirm that this fixed the issue.
