### ISSUE TITLE
Error message with txn that fails to balance is too exact (shows more than needed precision)

### ISSUE THREAD

**Issue by tbm** [simonmichael/hledger#1391]
Given this test case:

```
2020-01-10 * "Test"
  Expenses:Test                           4.990 USD
  Assets:Bank                            -4.990 USD

2020-01-10 * "Test: will fail in ledger due to precision of USD"
  Expenses:Test            150.75 THB @ 0.03344 USD
  Assets:Bank                             -5.04 USD
```

Obviously it will fail since we need `-5.041 USD` because of the precision of USD from the first transaction (`4.990`).

And it fails:

```
hledger: "/xx" (lines 6-8)
could not balance this transaction:
real postings' sum should be 0 but is: 0.00108 USD
2020-01-10 * "Test: will fail in ledger due to precision of USD"
    Expenses:Test    150.75 THB @ 0.03344 USD
    Assets:Bank                    -5.040 USD
```

But the error talks about `0.00108 USD`, but because of the precision it really fails because of `0.001 USD`.

I wonder if it would make sense to change the error to `0.001 USD`, i.e. use the precision of the currency, because that's what matters.  Maybe putting the full number in brackets or something.

Feel free to close if you don't like; it's a minor issue.

**Comment by tbm** [comment]
Rationale: someone might add `0.00108 USD` to the transaction and than *other* transactions will fail to balance because you increased the precision of the currency.

**Comment by simonmichael** [comment]
Thanks for the report. I'm not seeing a problem here - 0.00108 is in fact the correct amount to add if someone wants to balance things perfectly.

**Comment by tbm** [comment]
Of course it's correct. I was just wondering if it could be made clearer but never mind.
