### ISSUE TITLE
[hledger-web 1.19.1 linux version (using docker from DAstapov)] unable to add more than 4 lines 

### ISSUE THREAD

**Issue by Simaex** [simonmichael/hledger#1403]
Hi!
I've upgraded to the new 1.19.1 version and got a problem. I am not able to add more lines to a single transaction using Add form anymore. I've got the cool additional field that delivers the ability to select the journal to store transactions but now the Add form lacks the possibility to add more rows. Hotkeys do not help too. I do my best to check the documentation for any new parameters but do not find any relevant. I check the issue in Chrome and Opera to be sure it is not browser-related. This is how the form look like in the new version:
![image](https://user-images.githubusercontent.com/33528038/100442574-e76d2800-30b0-11eb-8984-a1035553a5cb.png)
This is how it used to be before:
![image](https://user-images.githubusercontent.com/33528038/100442751-387d1c00-30b1-11eb-954f-095724b60332.png)
Please advise how to address the issue.

**Comment by simonmichael** [comment]
Thanks for the report. I don't find much about this in the release notes or manual, but it seems that I tried to streamline this and now there's only one way to add more rows: type something into the last amount field. This requires javascript I imagine. Are you using a non-js web browser ? Or, can you report your browser version, or check for js errors in the debug console ?

**Comment by Simaex** [comment]
Thank you for the fast responce. I try Chrome 86.0.4240.198 and Opera 72.0.3815.320 , both the latest versions at the moment of test. When I fill the last amount field it is either doing nothing or if I hit 'enter' throw imbalanced transaction error wich it is for sure since I can not enter the next row :-), something like this. 
![image](https://user-images.githubusercontent.com/33528038/100486583-26c96200-310d-11eb-85b5-852323077264.png)

**Comment by simonmichael** [comment]
Hmm, it's working here in Chrome 87.0.4280.67 on mac.

I suppose since it's bringing up the add form, javascript is working.

Could you try, while viewing hledger-web-1.19.1 in Chrome:

- open the inspector: ctrl-shift-i (cmd-shift-i)
- click the Console tab
- open the add form
- type any character into the last amount field
- look for any errors/warnings logged in the Console. (I see none, and the new amount row is created.)

**Comment by Simaex** [comment]
I try to follow the workflow. If I go directly to the last field and type an amount I've got a suggestion to fill the Date and Description fields first. After this nothing happens except the next diagnostics in the console window. 
![image](https://user-images.githubusercontent.com/33528038/100514272-e0f7b280-317b-11eb-87c3-17a0cf3dfde8.png)

**Comment by Simaex** [comment]
Just try to do the same in Firefox - to no avail :-(. So it seems not to be browser-related.

**Comment by simonmichael** [comment]
>  I've got a suggestion to fill the Date and Description fields first.

Did you press enter or click add ? Don't do that.. just click to focus the last amount field and type a single character, eg `1`. When you do that, you don't see a new row added below, and you don't see any new output in the web inspector console, right ? Note the console can be configured to filter out some events, I don't know how it works in chrome. Try with the inspector in firefox as well. We want it showing all warnings and errors.

Are you viewing a local hledger-web (http://localhost:5000), or a remote one where network issues could be a factor ?

**Comment by Simaex** [comment]
The hledger-web is running on a remote host. The same behaviour is experienced from several different locations and was not an issue before version upgrade. At first I try to just enter a value to the field - nothing happened. So I try enter and tab to force any action. According to you suggestion I try to run this once more and this time noted behaviour that I possibly missed before: when I invoke 'ADD' form the field is already populated with a value. My attempts to modify it did not change anything - no errors, no new line for further input. Do you have any ideas what I can be doing wrong way? 
![image](https://user-images.githubusercontent.com/33528038/100523155-ec1c0400-31b6-11eb-85b4-cb4a66c2e20a.png)

**Comment by simonmichael** [comment]
Sorry, at the moment I don't. :-/ Please try it with a hledger-web running on localhost just to rule out network traffic filtering issues.

**Comment by simonmichael** [comment]
Random other ideas: 

- repeat the test, changing only the hledger-web version, to find out in which version exactly it stops working for you
- try a hledger-web-1.19.1 that's not packaged or running in docker

**Comment by Simaex** [comment]
I try just the same operation using http://demo.hledger.org/ 
It is not working for me. Does it work for you? 
I'll try to downgrade and find the last version that is adding more lines and report back. At the moment I know that 1.17 is working but it features the old-style button to add more lines, not the new automatic method.

**Comment by Simaex** [comment]
docker pull dastapov/hledger:1.17.1.1 - working normally

**Comment by Simaex** [comment]
docker pull dastapov/hledger:1.18.1 - not adding new lines 
docker pull dastapov/hledger:1.18 - not adding new lines.
So it seems that the bug was introduced in 1.18 version.
I am going to downgrade to 1.17.1.1 for now. But still it will be great to be able to use new versions of hledger-web later.

**Comment by simonmichael** [comment]
Thanks for the testing @Simaex. Yes it works for me at http://demo.hledger.org in chrome, firefox, and safari.

`git log 1.17..1.18 -- hledger-web/{static,templates,Hledger}` shows the eight new code commits in hledger-web 1.18. The first three seem relevant:

23a79af1 * web: add form: always start with four rows when opened
ca4fc4a4 * web: add form: drop unneeded C-minus/C-plus keys & related help text
ef5db595 * web: fix a 2016 regression adding too many add form rows (#422, #1059)

Since I don't know how to reproduce this, if you feel motivated enough, you could try building with each of those  commits, and/or step through the javascript code,  to see what causes the problem...

**Comment by simonmichael** [comment]
@Simaex I wonder if you can reproduce this problem with [current hledger-web (1.22.2)](https://hledger.org/download.html) ?

**Comment by Simaex** [comment]
I'll try and report back.

**Comment by Simaex** [comment]
The problem vanished, thanks a lot for the update!
