### ISSUE TITLE
_HLEDGER_COMPLETION_TEMPDIR creates an additional directory on each shell invocation

### ISSUE THREAD

**Issue by zhelezov** [simonmichael/hledger#1404]
Hi,

As it stands currently bash completion leads to heavy pollution of my `/tmp` directory. The problem is this line which is evaluated by each started shell, and I do start a lot of them: https://github.com/simonmichael/hledger/blob/d40d53ae0257be0741c0f7556cbd2400edcff36b/shell-completion/hledger-completion.bash#L24

Can we use a more predictable temporary directory naming scheme in order to avoid creating hundreds of them? Something like this e. g.:
```sh
readonly _HLEDGER_COMPLETION_TEMPDIR="${TMPDIR:-/tmp}/hledger-${UID}"
mkdir -p "$_HLEDGER_COMPLETION_TEMPDIR"
```

This way we would have just one directory per user. What are your thoughts?

**Comment by zhelezov** [comment]
And while looking at the rest of the file...

Why can't we just store those lists of values in variables, why do we need to write them out?

**Comment by simonmichael** [comment]
Thanks for the report @zhelezov . @schoettl would you be able to take a look at it ?

**Comment by schoettl** [comment]
Good idea, to use the `$UID` for the directory name, @zhelezov ! Using `$TMPDIR` also seems to be a good idea.

I'd suggest we use `"[..]/hledger-completion-$UID"` to be more specific and to not interfere with potentially other uses of this directory, because the completion generates a lot of files...  or we use a subdirectory of `hledger-$UID`?

Do you want to provide a PR? Otherwise I can do it.

**Comment by simonmichael** [comment]
Is this a situation where $XDG_* dirs should be used ? Cf #1081.

**Comment by zhelezov** [comment]
No, please no writing to disk for temporary files! Unless it is done once upon installation but it still leads to unnecessary IO.

Please go ahead @schoettl. Unless you want to reconsider using arrays to store the  completion values. I see we are just grepping for them in the completion function so it's not that messy switching to variables and using constructs like:
```sh
completion-commands=(add import check-dates check-dupes ...)
completion-generic-opts=(...)
grep -h "^$wordToComplete" \
    <(printf -- '%s\n' "${completion-commands[@]}") \
    <(printf -- '%s\n' "${completion-generic-opts[@]}")
```
... which create the file descriptors we need to grep from as we go. If you want to reconsider it I can have a look at it one of these days and open a PR and move the discussion there.

**Comment by schoettl** [comment]
@zhelezov I'll not gonna put much effort into it, currently.

But I like your idea of omitting external files and using dynamically-filled variables instead. It seems like a better option than creating files on tmpfs every time a shell is started.

From your two suggestions, I think I prefer the second one (using here docs). It seems simpler and we don't use array functionality anyway, right?

A few questions:

- Do two times `<(...)`, i.e. two concatenated stdinputs work reliable? I've never seen this before.
- Does process substitution `<(...)` works reliably also on older bashs? I thought I had some problems with these sometimes...
- Is there a reason that you use `printf` and not `echo`?

Thanks for your suggestions. I'd appreciate a PR from you!

**Comment by zhelezov** [comment]
Alright then, I'll give it a thought soon and follow with a PR.

As to your questions:

- Process substitution is a concept from the 80's (ksh88) and bash has supported it since v1.4 released in 1994 so I suppose we are good.
- As to `printf` vs `echo` -- sorry, a slip of the hand. `echo` would be perfectly fine. I've just been in the habit of avoiding it altogether because of the wildly varying implementations/behavior on different systems.
