### ISSUE TITLE
Auto-Postings don't work on auto-deduced remaining amounts of periodic transactions

### ISSUE THREAD

**Issue by nobodyinperson** [simonmichael/hledger#1412]
Hi, thanks again for `hledger`, it's awesome!

I noticed that [auto postings](https://hledger.org/1.20/journal.html#auto-postings) don't work with auto-deduced remaining amounts of [periodic transactions](https://hledger.org/journal.html#periodic-transactions).

## Steps to Reproduce

Take this `log.hledger` file:

```hledger
~ 2021-01-02   Periodic
    Checking            -10
    Costs

2021-01-01   Fixed
    Checking            -20
    Costs

= acct:Costs
    (Auto)     *1
```

Execute the following:

```bash
hledger --version
# hledger 1.20
hledger -f log.hledger print --forecast --auto --explicit
```

## Observed Output

```hledger
2021-01-01 Fixed  ; modified:
    Checking             -20
    Costs                 20
    (Auto)                20  ; generated-posting: = acct:Costs

2021-01-02 Periodic
    ; generated-transaction: ~ 2021-01-02, modified: 
    Checking             -10
    Costs                 10
    (Auto)                    ; generated-posting: = acct:Costs
                          ^^
                      nothing here
```

## Expected Output

```hledger
2021-01-01 Fixed  ; modified:
    Checking             -20
    Costs                 20
    (Auto)                20  ; generated-posting: = acct:Costs

2021-01-02 Periodic
    ; generated-transaction: ~ 2021-01-02, modified: 
    Checking             -10
    Costs                 10
    (Auto)                10  ; generated-posting: = acct:Costs
                          ^^
                      amount is used
```

## Notes

The empty generated amount also ”breaks” the `register` output. Take for example this `log.hledger` file:

```hledger
~ monthly from 2021-04   Periodic
    Checking            -10
    Costs

2021-03-02   Fixed Nr. 1
    Checking            -20
    Costs

2021-03-31   Fixed Nr. 2
    Checking            -30
    Costs

= acct:Costs
    (Auto)     *1
```
And run the following:

```bash
faketime '2020-12-13' hledger -f log.hledger reg --forecast=today- --auto  Auto
```
Output:

```
2021-03-02 Fixed Nr. 1          (Auto)                          20            20
2021-03-31 Fixed Nr. 2          (Auto)                          30            50
2021-04-01 Periodic             (Auto)                                          
2021-05-01 Periodic             (Auto)                                          
2021-06-01 Periodic             (Auto)   
                                                                              ^^
                                                      cumulative amount vanishes
```

Maybe, the auto-postings are applied before expanding the periodic transactions and thus before filling in the remaining amounts?

**Comment by simonmichael** [comment]
Thanks for the report.

**Comment by nobodyinperson** [comment]
I posted a 10$ bounty on this issue [on bountysource](https://www.bountysource.com/issues/95188797-auto-postings-don-t-work-on-auto-deduced-remaining-amounts-of-periodic-transactions). Maybe it'll help solve this issue. It really affects me as I use auto postings a lot.

**Comment by Xitian9** [comment]
We've merged a fix into master, so I think this issue can be closed.

**Comment by simonmichael** [comment]
Time to claim @nobodyinperson 's bounty: https://github.com/simonmichael/hledger/issues/1412#issuecomment-886230543

**Comment by nobodyinperson** [comment]
Do I have to do anything for that? Or who decides whether the bounty should be given to who?

**Comment by Xitian9** [comment]
I'm not sure. I tried to sign up for an account, but haven't gotten anything. Preliminary research seems to suggest that bountysource may be defunct:
- https://en.wikipedia.org/wiki/Bountysource#History
- https://github.com/bountysource/core/issues/1539

**Comment by nobodyinperson** [comment]
😕 Well... Let's hope not.

**Comment by nobodyinperson** [comment]
At least now Boutysource sees the issue as **closed** so you can [claim the bounty](https://www.bountysource.com/issues/95188797-auto-postings-don-t-work-on-auto-deduced-remaining-amounts-of-periodic-transactions): 

![grafik](https://user-images.githubusercontent.com/19148271/128022957-81b0b5c8-d192-4a55-9c9d-91ffef42abfd.png)

**Comment by nobodyinperson** [comment]
While I can confirm that the added changes indeed fix this issue, they might have undesired side-effects: #1638

**Comment by simonmichael** [comment]
(Bounty Procedures:

- @nobodyinperson can decide if this bounty has been earned yet :)

- Even if Bountysource is kind of working, and is our only bounty mechanism where trust is outsourced to a known third party, maybe it's finally time to pull the plug and drop it.)

**Comment by nobodyinperson** [comment]
> @nobodyinperson can decide if this bounty has been earned yet :)

I think I can only grant the bounty if it was „claimed” by @Xitian9 (or whoever is responsible for the fix - by logging in to Boutysource and [claiming the bounty](https://www.bountysource.com/issues/95188797-auto-postings-don-t-work-on-auto-deduced-remaining-amounts-of-periodic-transactions)). I guess I'll then recieve a notification where I can grant it. Currently, I can't do anything on Boutysource AFAIK.

**Comment by Xitian9** [comment]
I tried creating an account on bountysource, but they are not sending me the required confirmation email. So there's not much I can do to claim it right now.

**Comment by nobodyinperson** [comment]
I think when logging in via GitHub, one doesn't need the email verification. Maybe try that?

**Comment by Xitian9** [comment]
It's also not letting me sign up with GitHub.

**Comment by nobodyinperson** [comment]
Okay, then screw Bountysource. As I can log in at least, I claimed the bounty myself 😝, lets see how that turns out. Let's do it the old-fashioned way, then. What would you prefer, direct 10$ PayPal payment or shall we go via OpenCollective?

**Comment by Xitian9** [comment]
I guess let's go OpenCollective, unless that's trickier for you.

**Comment by nobodyinperson** [comment]
Okay I [donated 10$ to the hledger collective](https://opencollective.com/hledger/transactions?amount=10-10&kind=CONTRIBUTION%2CEXPENSE%2CPLATFORM_TIP%2CADDED_FUNDS%2CHOST_FEE_SHARE%2CHOST_FEE&searchTerm=b%C3%BCchau). But at no point there was a possibility to specify what for. How to make an „earnmarked donation”, then? Not via the „individual one-time donation”? This should probably be clearer on https://hledger.org/#sponsorship

@Xitian9, I guess you now have to file an expense request and @simonmichael has to approve it.

**Comment by simonmichael** [comment]
Correct. Sorry, I just noticed this in a mail subfolder.
