### ISSUE TITLE
small business: `close` command and balance of next year, choose accounts?

### ISSUE THREAD

**Issue by 5472qaywsx** [simonmichael/hledger#1420]
Hi,
I've got a main (business) journal file which spans from 2018 until now (2020);
- I "closed the book"\* of year 2018 with the command `hledger close -p "2018"`, and saved the output (a transaction on the 2018-12-31-2018 for closing balances and a transaction on 2019-01-01 for opening balances) as a new journal file; this transactions include all balanced accounts <> 0;
- I included this file in the main journal;
- I then run a `hledger bal -p "2019"` command; the closed accounts are reported in 2019 with the assessed amount of the `close` command, which makes sense (from an accounting point of view) for *assets* and *liabilities*, not (for me) for *expenses* or *revenues*, which scope should reside only in the year of spending.

I would like to choose the accounts to close, i.e. only  of type *asset* and *liability* (without having to comment out manually in the created transactions): is this (already) possible / desirable?

\*: ...I'm struggling with this! I would have expected this can be done directly with a command/option, and not that I have to create extra transactions, see [this (quite old) post](https://groups.google.com/g/ledger-cli/c/M5T_H-bxGh0/m/Xck1C-pZCgAJ)) ; I second Blais' opinion on this!

**Comment by simonmichael** [comment]
Is there still an issue here, or can this be closed ?

**Comment by 5472qaywsx** [comment]
Yes, please, close this: the explanations of [https://hledger.org/hledger.html#close](https://hledger.org/hledger.html#close) are already explaining this in the correct way. Sorry for not having read that with attention before.
