### ISSUE TITLE
-T and -X. Any way to get "immediate" exchange rate?

### ISSUE THREAD

**Issue by aragaer** [simonmichael/hledger#1428]
```
P 2020-01-01 A 2.0

2020-01-02
 assets  2
 income

P 2020-01-03 A 1.0

2020-01-04
 assets  2
 income
```
I want some report that would show that I've got 3A. However either A is valued at 1 (end of journal) or income/assets get revaluated at P-record on 2020-01-03. Either way I'm getting 4A.

```
$ hledger bal -X A --transpose -N -T --invert income
                 A4  income
$ hledger bal -X A --transpose -N -T --invert income -D
Period-end value changes in 2020-01-02..2020-01-04:

            || income 
============++========
 2020-01-02 ||     A1 
 2020-01-03 ||     A1 
 2020-01-04 ||     A2 
   Total    ||     A4 
```

Is there a way to get number 3 using this journal?

**Comment by aragaer** [comment]
It seems that I found an actual problem with this -- when currency gets revaluated, it recalculates the total value of account even outside the requested period:
```
$ cat a.journal 
2019-01-02
 assets  50
 income

P 2020-01-01 A 2.0

2020-01-02
 assets  2
 income

P 2020-01-03 A 1.0

2020-01-04
 assets  2
 income
$ hledger bal  -f a.journal -X A --transpose -N -T --invert income -D -b 2020
Period-end value changes in 2020-01-02..2020-01-04:

            || income 
============++========
 2020-01-02 ||     A1 
 2020-01-03 ||    A26 
 2020-01-04 ||     A2 
   Total    ||    A29 
```
Which looks like I've magically earned 26 units of A just because the money I've earned last year suddenly got more valuable.

**Comment by simonmichael** [comment]
Thanks for the report. Re your first example, I can't figure out how you could have 3A, can you explain ?

Re the second, I don't get that output, please check it.

**Comment by aragaer** [comment]
Just tried it again. Also added the --version output.
```
$ cat a.journal 
2019-01-02
 assets  50
 income

P 2020-01-01 A 2.0

2020-01-02
 assets  2
 income

P 2020-01-03 A 1.0

2020-01-04
 assets  2
 income
$ hledger bal -f a.journal -X A --transpose -N -T --invert income -D -b 2020
Period-end value changes in 2020-01-02..2020-01-04:

            || income 
============++========
 2020-01-02 ||     A1 
 2020-01-03 ||    A26 
 2020-01-04 ||     A2 
   Total    ||    A29 
$ hledger --version
hledger 1.20
```
Regarding first example it's more or less the same -- I want my income entries to be "independent" from entries from other periods. Just like in second case my income is "affected" by records from 2019, when I am doing a multiperiod output I only want to see income limited to each period. In this case on period "2020-01-02" I have earned 1A and on period "2020-01-04" I have earned 2A. I might have already spent all that money so I'm not interested in it getting revalued on each subsequent exchange rate change.

**Comment by simonmichael** [comment]
Ah, thanks, both understood now. I was running hledger master.

--debug is useful with valued reports, showing the valuation date(s) and conversion rates found. Even with that, I don't see how it calculates A26, do you ? Debugging needed.

> I want my income entries to be "independent" from entries from other periods

I think this means mixed valuation types - eg showing income amounts at cost, and asset balances at market value, in a single report ? There's no built in way to do that currently, you would have to run a cost report and then a separate market value report.

I'll have another go at the first question later.

**Comment by simonmichael** [comment]
Cc @Xitian9 who might have ideas.

**Comment by aragaer** [comment]
I have built the current master and I am still getting the same result:
```
$ ./hledger/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0/build/hledger/hledger bal -f /tmp/a.journal -X A --transpose -N -T -D -b 2020 -e 2020-01-05 income --invert --debug
Period-end value changes in 2020-01-01..2020-01-04:

valuation date: 2020-01-01
shortest price path for  -> A: Nothing
shortest price path for  -> A:
 Just
   [ MarketPrice
     { mpdate = 2020 - 01 - 01, mpfrom = "", mpto = "A", mprate = 0.5 }
   ]
valuation date: 2019-12-31
shortest price path for  -> A: Nothing
shortest price path for  -> A: Nothing
valuation date: 2020-01-02
shortest price path for  -> A: Nothing
shortest price path for  -> A:
 Just
   [ MarketPrice
     { mpdate = 2020 - 01 - 01, mpfrom = "", mpto = "A", mprate = 0.5 }
   ]
valuation date: 2020-01-03
shortest price path for  -> A: Nothing
shortest price path for  -> A:
 Just
   [ MarketPrice
     { mpdate = 2020 - 01 - 03, mpfrom = "", mpto = "A", mprate = 1 }
   ]
valuation date: 2020-01-04
shortest price path for  -> A: Nothing
shortest price path for  -> A:
 Just
   [ MarketPrice
     { mpdate = 2020 - 01 - 03, mpfrom = "", mpto = "A", mprate = 1 }
   ]
            ||     income 
============++============
 2020-01-01 || -50.0, A25 
 2020-01-02 ||         A1 
 2020-01-03 ||        A26 
 2020-01-04 ||         A2 
   Total    || -50.0, A54 
```
As a side note I've discovered a `--value=then,A` which gives me A3 I wanted to see. Too bad it only works for `reg --cumulative`...

**Comment by aragaer** [comment]
Regarding the A26. It seems that only multiperiod reports add that transaction.
```
$ hledger bal -f /tmp/a.journal income --invert -b2020 -XA
                  A4  income
--------------------
                  A4
$ hledger bal -f /tmp/a.journal income --invert -b2020 -XA -D
Period-end value changes in 2020-01-02..2020-01-04:

        || 2020-01-02  2020-01-03  2020-01-04 
========++====================================
 income ||         A1         A26          A2 
--------++------------------------------------
        ||         A1         A26          A2 
$ hledger bal -f /tmp/a.journal income --invert -b2020 -XA -W 
Period-end value changes in 2019-12-30W01:

        || 2019-12-30W01 
========++===============
 income ||    -50.0, A54 
--------++---------------
        ||    -50.0, A54 
```
Output for `-M`, `-Q` and `-Y` is similar to `-W`.

**Comment by Xitian9** [comment]
Interesting: this is the new behaviour which was requested in #1353 and introduced in #1380. It seems that we do indeed have a use case for the old behaviour.

Here's an explanation for the A26.

```
2019-01-02
 assets  50
 income               # Balance -50

P 2020-01-01 A 2.0    # Balance -50 (= -A25)

2020-01-02
 assets  2
 income               # Balance -52 (= -A26), a change of -2 (= -A1)

P 2020-01-03 A 1.0    # Balance -52 (= -A52), a change of 0 (= -A26)

2020-01-04
 assets  2
 income               # Balance -54 (= -A54), a change of -2 (= -A2)
```

This comes down to a question of which is more relevant for valuation: tracking the change in the valuation, or tracking the valuation of the change. It seems that the former is more useful for assets, liabilities and equities, the latter more useful for expenses and income.

Which should be the default? I would guess the principle of least surprise would say the old behaviour (valuation of the change) is probably a better default, but we need a way to allow access to both behaviours in a reasonable way.

**Comment by Xitian9** [comment]
A possible solution is to extend `--value=then` to more report types. Here's a proposal:

For balance reports, we currently sum all the postings in a period, then perform a valuation at the relevant dates after this binning process. This leaves us without access to the information needed to figure out the posting date. Instead, we could value each posting before binning into the report periods, then sum all the valued postings in each period.

@aragaer: Would this give you the behaviour you want?

**Comment by aragaer** [comment]
Regarding valuation and changes -- I actually expected that adding `-R` flag would remove those revaluation events but that didn't work.

Regarding valuation before binning... while extending `--value=then` to more report types seems good, adding a way to have the old behavior would be enough since I can do a per-day report with `--value=end` and that would work.

I've got the behavior I want using `reg --value=then --cumulative` so ... no hurry.

**Comment by simonmichael** [comment]
It's good that we are thinking carefully about the options here. I'll respond over on #1353 and come back to this one later.

**Comment by simonmichael** [comment]
In 1.20.3 this will be possible using --value=end as in 1.19, and in 1.21 it will be possible with --value=then. I think this can be closed.
