### ISSUE TITLE
hledger print -X doesn't properly convert balance assertions/assignments

### ISSUE THREAD

**Issue by aragaer** [simonmichael/hledger#1429]
`hledger print` with `-X` option only converts changes but not asserions/assignments. Resulting output is not a correct entry. See an example below.
```
$ cat b
P 2020-12-28 A 2

2020-12-28
 assets  4 = 4
 income
$ hledger -f b print
2020-12-28
    assets               4 = 4
    income

$ hledger -f b print | hledger -f - bal
                   4  assets
                  -4  income
--------------------
                   0
$ hledger -f b print -X A
2020-12-28
    assets              A2 = 4
    income             A-2

$ hledger -f b print -X A | hledger -f - bal
hledger: balance assertion: "-" (line 2, column 28)
transaction:
2020-12-28
    assets              A2 = 4
    income             A-2

assertion details:
date:       2020-12-28
account:    assets
commodity:  
calculated: 0
asserted:   4
difference: 4
```

**Comment by simonmichael** [comment]
@aragaer thanks for the report! 

Normally we expect print's output to be valid and parseable. There are a few cases where it may not be, and you are right, this is one of them. I feel that this may be one where an exception to that rule is justified. A balance assertion is a definite statement made by the user and I'm not sure it's right to be manipulating it in any way.

**Comment by aragaer** [comment]
I was expecting that all amounts would be converted to the one specified, including the asserted one.

**Comment by simonmichael** [comment]
Got an example of the rounding problem ? Feel free to open a separate issue for that.

**Comment by simonmichael** [comment]
Re the balance assertion, perhaps we'll get some more opinions in coming days. Meanwhile..

We could automatically remove or comment balance assertions when using valuation with print. But balance assignments would remain problematic, I think.

We provide a flag allowing the user to remove or comment balance assertions when they are getting in the way.

We should justify any change by solving some real-world problem(s). Has this come up for you as a real problem in practice yet ?

**Comment by aragaer** [comment]
It was more like an attempt to work around the #1417 using `hledger print -X` piped into `hledger -f - roi`. Adding `-I` on the reading side fixes this problem but reveals the rounding problem. I will now create a separate issue for that one.

**Comment by simonmichael** [comment]
We should update docs, which currently [say](https://hledger.org/hledger.html#print) "print's output is always a valid hledger journal." I've done that: https://hledger.org/hledger.html#print
