### ISSUE TITLE
Space leak in Amount arithmetic

### ISSUE THREAD

**Issue by Xitian9** [simonmichael/hledger#1431]
There seems to be a space leak somewhere in `Amount` arithmetic. Running `hledger register +RTS -h` and viewing the resulting profiling report gives the characteristic spike. [hledger-register-master.pdf](https://github.com/simonmichael/hledger/files/5746750/hledger-register-master.pdf)

I've tried making `Amount` strict in its contents and adding some strictness annotations to `similarAmountsOp`, but this has only changed the precise function the spike is attributed to. I'm not very experienced in squashing space leaks, so any pointers on how to get rid of this would be helpful.

**Comment by Xitian9** [comment]
Okay, I think I've tracked this down to these lines. https://github.com/simonmichael/hledger/blob/7c9303a15c64859f11aec8fa75546793827e3086/hledger-lib/Hledger/Data/Amount.hs#L545-L549

I've gotten good results by replacing these lists with strict `Map` (total allocated memory drops in my example from ~250MB to ~35MB), but I'm having trouble getting the correct behaviour with respect to ensuring transactions with `AmountPrice` balance correctly (in particular `TotalPrice`). I've looked through the documentation, but I can't find where the correct behaviour is specified. Could you perhaps point to where this is specified?

Maybe related: #1177

**Comment by simonmichael** [comment]
Great! I'd love to read any notes about your tracking-down process. 
Does this help:
https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Data/Transaction.hs#L360

**Comment by simonmichael** [comment]
Incidentally, this will be interesting! http://www.well-typed.com/blog/2021/01/first-look-at-hi-profiling-mode

**Comment by Xitian9** [comment]
Thanks!

A quick question about `MixedAmount` normalisation. The tests specify that `TotalPrice`s should never be combined under any circumstances. Is there a reason for such a strict treatment? Why can we not safely combine the following
```
1A @@ 2B
2A @@ 3B
```
to `3A @@ 5B`?

**Comment by simonmichael** [comment]
Hmm.. it looks easy enough in this example, indeed. I don't remember the thinking exactly, unless it was to do with preserving per-lot information. I'm not against trying it.

**Comment by Xitian9** [comment]
Though I'm sure there are other space leaks around, this one has been fixed by #1445.
