### ISSUE TITLE
-f- no longer parses csv input

### ISSUE THREAD

**Issue by joeyh** [simonmichael/hledger#1437]
hledger print --rules-file=foo.rules  -f history-2019.csv  
cat history-2019.csv | hledger print --rules-file=foo.rules  -f-

The first command works. I have existing hledger files that were created using commands like the second command, which used to work identically to the first. But now that second command fails on the first character in the csv input:

    hledger: -:1:1:
    ...
    unexpected '"'
    expecting end of input or transaction or directive

Or, when the first field in the csv was not quoted, it failed parsing the date, despite the rules file having a date-format.

So I think it used to automatically detect csv on stdin and something broke that, and it's attempting to parse it as a ledger file.

Of course, I was not really uselessly using cat, but was doing some grepping etc of the input. I have worked around the problem by redirecting that to a temporary csv file, and then processing that with hledger.

hledger 1.18.1

**Comment by simonmichael** [comment]
Thanks for the report joeyh. You are right, it used to try all formats in that case, but this gave unpredictable errors so I changed it: https://hledger.org/release-notes.html#hledger-cli-1-17

Summary: add the `csv:` prefix: `-fcsv:-`.
