### ISSUE TITLE
balance reports are flat by default but documentation says otherwise

### ISSUE THREAD

**Issue by DamienCassou** [simonmichael/hledger#1441]
Given this ledger file:

```ledger
2021-01-01 misc
    asset:account                                -10
    expense:food                                   5
    expense:misc                                   5
```

The `balance` report shows a flat list of accounts by default:

```session
$ hledger -f foo.hledger balance
                 -10  asset:account
                   5  expense:food
                   5  expense:misc
--------------------
                   0
```

However, the documentation says:
- "By default, accounts are displayed hierarchically, with subaccounts indented below their parent"
- "To see a flat list instead of the default hierarchical display, use `--flat`"

To me, the documentation seems to contradict the default behavior. If the behavior is right, I would expect the documentation to be changed and to reference `--tree` in more places.

I'm using hledger 1.20.99 commit ac39d590165c5623777d7849b2e50ef6f8133fd1.

**Comment by Xitian9** [comment]
`--tree` used to be the default behaviour, but this was changed a few months ago. It looks like we missed updating some of the documentation.

**Comment by simonmichael** [comment]
Thanks for the report @DamienCassou, this has been fixed for 1.20.3.

**Comment by simonmichael** [comment]
(Unless I've missed some places. I updated the balance command's doc, visible at https://hledger.org/hledger.html#balance).

**Comment by simonmichael** [comment]
Ready for release.
