### ISSUE TITLE
nix builds of master failing due to manually modified hledger-lib.cabal

### ISSUE THREAD

**Issue by Xitian9** [simonmichael/hledger#1457]
Trying to build master using nix is now failing with the following message:
```
hledger-lib.cabal was modified manually, please use --force to overwrite.
```
It looks like there's not currently a way to do this within nix (cf. https://github.com/nshimaza/thread-supervisor/issues/1).

This may be due to 541c4fc18ca70afd00ee213627f279a5344ef793, which for some reason has some cabal stuff in there. That's my commit, and I don't remember doing that, so this may have been picked up in a rebase.

I think the solution should be as simple as regenerating the cabal file. If I can figure out how to do that I'll submit a PR.

**Comment by simonmichael** [comment]
Thanks! I was a bit confused, because my usual update method (`./Shake cabalfiles [-c]`) was not showing any changes. I had to actually `rm */*.cabal` first, to see it. I fixed with 70bcd0a24 instead, which includes the hash.
