### ISSUE TITLE
Check for `.hledger.journal` files in the working directory before `~/`

### ISSUE THREAD

**Issue by retainCount** [simonmichael/hledger#1466]
hledger is amazing!

I keep my personal and small business files in separate git repos (which I keep as sibling checkouts generally speaking):

```
~/finance/
~/ranch-finance/
```

Providing an input file for every invocation is tiresome so I use a `~/.hledger.journal` file but this poses a problem because I have two different sets of journals. As it stands, I let my primary accounting set "win" in the user dot file and I provide a `-f path` argument for operations in the secondary one.

One solution would be to place `.hledger.journal` files inside each of the repos but it looks like hledger only checks in `~` for a dot file. 

It would be great if `hledger` could check for & prefer a dot file in the working directory before looking in the user dir.

**Comment by simonmichael** [comment]
Thanks! I agree this would be useful for power users. I have resisted it because it creates more complexity/unpredictability for non-experts users. There is a trick though: export LEDGER_FILE=.hledger.journal. 

I know it would be more discoverable and convenient if built in. But maybe this is enough ?

**Comment by simonmichael** [comment]
If we did add this feature, would you expect it to also look in parent directories ? Stopping at $HOME ?

**Comment by retainCount** [comment]
> There is a trick though: export LEDGER_FILE=.hledger.journal

Excellent! That works for my needs.

> would you expect it to also look in parent directories ? Stopping at $HOME ?

Probably just the working directory. I can see the appeal of checking each segment up the path.

**Comment by simonmichael** [comment]
Closing, unless you want to make a PR adding this somewhere in the docs.
