### ISSUE TITLE
Display related accounts when generating cash flow report

### ISSUE THREAD

**Issue by jmaness** [simonmichael/hledger#1469]
GnuCash's Cash Flow Report lists related accounts for a given set of selected cash accounts for both "Money into" and "Money out of" sections. Adapted from an IRC conversation with @simonmichael, one way of emulating this is the command

```
hledger print CASHACCTSQUERY | hledger -f- -I bal --invert not:CASHACCTSQUERY
```

Could we add support for the `-r`/`--related` flag to the balance commands and cashflow report?

**Comment by Xitian9** [comment]
This is straightforward to implement for balance reports, but it's a bit trickier for the compound balance reports (balancesheet, cashflow, incomestatement). It would be good to have an example of what the output would look like.

Let's consider the sample journal
```
2008/01/01 income
    assets:bank:checking  $1
    income:salary

2008/06/01 gift
    assets:bank:checking  $1
    income:gifts

2008/06/02 save
    assets:bank:saving  $1
    assets:bank:checking

2008/06/03 * eat & shop
    expenses:food      $1
    expenses:supplies  $1
    assets:cash

2008/12/31 * pay off
    liabilities:debts  $1
    assets:bank:checking
```

A cashflow report gives:
```
$ hledger -f examples/sample.journal cashflow -N
Cashflow Statement 2008

                    || 2008 
====================++======
 Cash flows         ||      
--------------------++------
 assets:bank:saving ||   $1 
 assets:cash        ||  $-2 
```

Would the related report give this?
```
$ hledger -f examples/sample.journal cashflow --related -N
Cashflow Statement 2008

                      || 2008 
======================++======
 Cash flows           ||      
----------------------++------
 assets:bank:checking || $-1 
 expenses:food        ||  $1 
 expenses:supplies    ||  $1 
```

**Comment by Xitian9** [comment]
Here's another example to look at: an income statement.

```
$ hledger -f examples/sample.journal incomestatement -N
Income Statement 2008

                   || 2008 
===================++======
 Revenues          ||      
-------------------++------
 income:gifts      ||   $1 
 income:salary     ||   $1 
===================++======
 Expenses          ||      
-------------------++------
 expenses:food     ||   $1 
 expenses:supplies ||   $1 
```

With --related, would it look like this?
```
Income Statement 2008

                      || 2008 
======================++======
 Revenues             ||      
----------------------++------
 assets:bank:checking ||   $2 
======================++======
 Expenses             ||      
----------------------++------
 assets:cash          ||  $-2 
```

**Comment by simonmichael** [comment]
Thanks for the PR.

Do people think that --related really fits with balancesheet and incomestatement ? I can see the desire for it, but on the other hand, 

- it makes these reports no longer what they claim to be: simple, high-level reports that match the traditional financial statements people are used to
- `balance` is available for the more complex/more flexible needs
-

**Comment by Xitian9** [comment]
I agree that it seems a weird fit for the compound balance reports. I think not enabling it would be a reasonable course of action.

**Comment by Xitian9** [comment]
It would also allow us to sidestep knotty questions like: what if something is a related posting for two different subreports? Do we include it in both subreports or no subreports?

**Comment by jmaness** [comment]
If it helps prioritizing (or deprioritizing) this issue, for my particular use case that led to opening this issue, I've found that `hledger incomestatement -M` provides most of the information I needed (at least in terms of showing changes in expenses), and changes in liabilities are on the `hledger balancesheet -M`. For both of those, having a `--related` flag is probably not necessary.

A consolidated monthly cash flow report similar to the GnuCash Cash Flow Report would still be useful though.
