### ISSUE TITLE
Too many commodities (eg. stocks) make the tree view in hledger-ui unusable

### ISSUE THREAD

**Issue by mrkajetanp** [simonmichael/hledger#1474]
Hello!
I'm loving hledger so far but I've just stumbled onto a pretty annoying issue.
Namely, if I add too many different commodities (in my case it's >20 different stocks), whenever I switch to tree view hledger-ui becomes unusable because the long list of stocks accumulated in the parent Investment account fills out the whole screen and removes even all the account names from the view.
Would it be possible to somehow make the ui trim that list if it gets too long? I'm sure it'd be a great usability improvement for such cases. The functionality already seems to be implemented in hledger because "hledger bs" generates a balance sheet that trims this list and just says "20 more..".
I'd implement it myself but sadly I've never used Haskell so I'm hoping someone here could help with that.
Even more ideal would be if there was an option to be added when declaring a commodity that determines whether it can be trimmed or not (I'd like to trim stocks if it gets too long but keep traditional currencies in the front).
As an aside, is there some way to change the ordering of commodities/currencies when they're accumulated in tree view? I'd love to be able to make my currencies appear before my stocks and other assets. Currently the order seems to be pretty random.

**Comment by simonmichael** [comment]
Hello @mrkajetanp, thanks for the report and sorry for the late reply. We think #1531 mostly resolves this. Commodities should be displayed in alphabetic order (not random). There's currently no way to change this, but we could imagine controlling it by the order of commodity directives in the journal, similar to how display order of accounts is controlled. I'd be glad to test a PR for that.
