### ISSUE TITLE
Show account names when many currencies

### ISSUE THREAD

**Issue by artkpv** [simonmichael/hledger#1478]
Thanks for this great tool! I have many currencies / tickets under one account in subaccounts. When I decrease depth or move all to one account (at the start of the year) then hledger-ui truncates account names on the left to show amounts in different currencies. Expected: configure account name width or show one account on multiple lines. Pls see image:

![image](https://user-images.githubusercontent.com/3657998/106999543-72485e00-6797-11eb-89bd-f3d37e5b9a19.png)

Example:
```
2021-02-05 
    asset:a             1000.00 A
    disbalance

2021-02-05 
    asset:a             1000.00 B
    disbalance

2021-02-05 
    asset:c             1000.00 C
    disbalance

2021-02-05 
    asset:a             1000.00 DDDD
    disbalance

2021-02-05 
    asset:a             1000.00 EEEE
    disbalance

2021-02-05 
    asset:a             1000.00 FFFF
    disbalance

2021-02-05 
    asset:a             1000.00 GGG
    disbalance

2021-02-05 
    asset:a             1000.00 HHH
    disbalance

2021-02-05 
    asset:a             1000.00 III
    disbalance

2021-02-05 
    asset:a             1000.00 JJJ
    disbalance

2021-02-05 
    asset:a             1000.00 KKK
    disbalance

2021-02-05 
    asset:a             1000.00 LLL
    disbalance

2021-02-05 
    asset:a             1000.00 MMM
    disbalance

2021-02-05 
    asset:a             1000.00 NNN
    disbalance

2021-02-05 
    asset:a             1000.00 OOO
    disbalance

```

**Comment by simonmichael** [comment]
Thanks for the report. I agree something should be done. Multiple lines per item though is problematic, to implement with the brick library at least, I believe.

**Comment by simonmichael** [comment]
Actually I would expect it to elide some of those amounts. Can you try the latest version (1.20.x) if you haven't already.

**Comment by Xitian9** [comment]
I'm also getting this bug in master. It's easy enough to tell hledger-ui to elide to a given width, the question is how to we keep this adjustable so that you can see everything if you want.

Options:
- Elide to given width by default, but accept a `--no-elide` flag and/or toggle to disable this.
- Control elision width directly somehow

But even with this, there's still another problem to solve: the list of commodities may be so long that it's not possible to display everything. It may be worth considering whether anything should be done in these cases (multi-line, horizontal scrolling, option to open a dialogue which displays it in full?).

**Comment by artkpv** [comment]
> Actually I would expect it to elide some of those amounts. Can you try the latest version (1.20.x) if you haven't already.

That's on the newest:
❯ hledger --version
hledger 1.20.4

**Comment by Xitian9** [comment]
Coming back to this, we should decide on an elision policy form hledger-ui. Do we hard-code a value, hard-code a value with a command-line option to change it, give a maximum percentage of the screen width?

**Comment by simonmichael** [comment]
I just tried #1531, it's definitely better. The default view of my journal, with 13 commodities, now shows 15 letters of account names rather than just two, and the wide multicommodity amounts are elided properly instead of just being clipped.

Now I wonder if a percentage is the best, ie allow account names to use up to one half of the width ? And likewise for the amounts ? But either column could still use more than half if the other column doesn't need it.

**Comment by Xitian9** [comment]
I think there's no hard-and-fast rule about which would be better. You could always have a lot of small account names, plus one huge one throwing everything off, and the same for amount strings.

This problem has been addressed in the `register` command with a `--width W,D` flag. Could we apply a similar solution here. (And maybe put some more thought into a better default behaviour than a min width of 15 for accounts.)

**Comment by simonmichael** [comment]
Yes, one long value is always going to mess things up. We could allocate a percentage based on the weighted overall width, so one outlier doesn't have so much influence. But this might be more effort than needed for now.

I'm not sure manually controlling it with a flag could ever be usable for hledger-ui, which shows a series of different screens or different content on the same screen, unlike a register command which you might be willing to hand-tune once in a while.

**Comment by Xitian9** [comment]
Hmm. Good point.

So for a percentage-based solution, how would we decide between the two when there's conflict? Do we take the sum of the widest account name and the widest amount width, and allocate a percentage of the available space proportional to their fraction of that sum?

**Comment by Xitian9** [comment]
Perhaps we can just apply this solution:

https://github.com/simonmichael/hledger/blob/0f4e462ae72eacb88eecb494446e788414190ef2/hledger/Hledger/Cli/Commands/Register.hs#L159-L183

**Comment by simonmichael** [comment]
Or, allocate column widths proportional to the total weight (sum of item widths) of text in them ? With some minimum limits of course. Perhaps that would minimize wasted space ? It probably needs experimentation.

**Comment by Xitian9** [comment]
I've pushed a commit to the #1531 which is an attempt at weighted proportional allocation. It works reasonably well in my limited test, but let me know if it works for you.

**Comment by simonmichael** [comment]
@artkpv we think #1531 resolves this.
