### ISSUE TITLE
Command shortcut 'b' not recognized

### ISSUE THREAD

**Issue by markokocic** [simonmichael/hledger#1486]
After updating hledger after a while I noticed that command parser is working differently than before (regression?)

Typing `hledger b` gives the following message output:
```
hledger b
hledger: Ambiguous mode 'b', could be any of: balance balancesheetequity balancesheet (use -h to see usage)
```
I get the same error message for `hledger ba`.

However, typing `hledger bal` command works displays balance.

In previous releases I was able to type `hledger b` and get the balance information. I know that typing `b` is ambiguous, bat `bal` and that resolves to `balance`. I know it's not a big deal, but I'd like to have the old behaviour back, it's one of those small things that make the application a joy to use.

**Comment by simonmichael** [comment]
Sorry @markokocic !

It was removed  there was a discussion I think both here and on mail list and no one disagreed. Perhaps you want to reopen the topic. Let me know if you can't find it.

**Comment by simonmichael** [comment]
The discussion is at #1423, closing this one.
