### ISSUE TITLE
Add configuration option to add `--tree` as default display mode

### ISSUE THREAD

**Issue by markokocic** [simonmichael/hledger#1487]
This change of default output mode of all hledger commands from `--tree` to `--flat` happened some time ago, but I still can't get used to the new one, and end up typing `--tree` almost every time.

It would be nice to have a way to configure hledger to use `--tree` as default format without having to type it every time.

I'd also opt for a way to specify `--change` as default parameter when running income statement or balance sheet commands.

**Comment by simonmichael** [comment]
> This change of default output mode of all hledger commands from --tree to --flat happened some time ago, but I still can't get used to the new one, and end up typing --tree almost every time.
> 
Can you clarify, do you mean you type --tree when it's not necessary ? Also how much time have you given yourself to adapt ? 
> It would be nice to have a way to configure hledger to use --tree as default format without having to type it every time.
> 
The idea was to simplify, make things consistent and pick the most useful default, and I think that's done. We're probably not going to make list/tree configurability, specifically, a feature. 

A general config file is a recurring topic and has pros and cons; see open issue.

But as always, for power users there's solutions like:
```shell
alias bal="hledger balance --tree
```
> I'd also opt for a way to specify --change as default parameter when running income statement or balance sheet commands.
> 

--change is the default for incomestatement. I think it would be the wrong default for balancesheet ?

**Comment by markokocic** [comment]
For me, the default of displaying hierarchical account tree using flattened list is in 99% of the cases not what I want. I just developed habit of typing --tree everywhere to get around it since the change.

--change in the balancesheet is another topic. I think we already discussed that back in the time on the mailing list. I'm aware in the accounting it may have specific meaning, I use it just as a convenience for displaying nicely formatted `hledger bal assets liabilities`. If `--change` is to be dropped from `bs` I'll just end up using `balance` directly.

Having config file is probably not worth the effort if not many people would use it, but it can have some advantage over everyone having to define his own aliases and shell script wrappers like the one I posted in #1423

**Comment by simonmichael** [comment]
Thanks for your notes. --change isn't going to be dropped from balancesheet. It's just not the right default for it, since a real life balance sheet normally shows historical end balances, not changes in balance.

**Comment by Xitian9** [comment]
Note: `--change` is not going to be dropped, but the proposed interface for the new `--gain` functionality will change its meaning. The command which will give the same results as the previous `--change` flag would be `--periodic`. (see https://github.com/simonmichael/hledger/issues/1353#issuecomment-772594810)

**Comment by simonmichael** [comment]
Shell scripts/aliases like the above are our standard solution for this for now. Discussion of a config file is mostly at #1013, closing this one.
