### ISSUE TITLE
Regression: empty accounts in balance and balancesheet reports

### ISSUE THREAD

**Issue by markokocic** [simonmichael/hledger#1507]
I updated today to the latest git commit and observed that some accounts with 0 started to appear in balance and balancesheet report.

I tracked it down, and it seems that it happens only to the accounts that had transactions with more than one currency in the past.

Steps to reproduce:
``` bash
> cat test
2014-07-07 Desc 1
    liabilities:a       1200 inr
    liabilities:p

2014-07-13 Desc 2
    liabilities:t      900 inr
    liabilities:p

2014-07-13 Desc 3
    expenses:m          1,407.00 inr
    expenses:b           550.00 inr
    liabilities:p

2014-07-18 Desc 4
    liabilities:p    4,057.00 inr @@ 50.00 €
    expenses:cash

> hledger bal -f test
          550.00 inr  expenses:b
            -50.00 €  expenses:cash
        1,407.00 inr  expenses:m
        1,200.00 inr  liabilities:a
                   0  liabilities:p
          900.00 inr  liabilities:t
--------------------
        4,057.00 inr
            -50.00 €
```
Here `liablilities:p` account should not be displayed because its value is `0`

**Comment by Xitian9** [comment]
I think the problem here is not the presence of multiple commodities, but in the fact that its amount is balanced only in the primary amount, not the cost amount (with prices the balance is `0.00 inr @@ 50.00 €`). Since we're not displaying prices the fact that the cost is non-zero should obviously be irrelevant.

**Comment by markokocic** [comment]
I'm not sure about this. I just changed the test case as following:

```
> cat test
2014-07-07 Desc 1
    liabilities:a       1200 inr
    liabilities:p

2014-07-13 Desc 2
    liabilities:t      900 inr
    liabilities:p

2014-07-13 Desc 3
    expenses:m          1,407.00 inr
    expenses:b           550.00 inr
    liabilities:p

2014-07-18 Desc 4
    liabilities:p    4,057.00 inr
    expenses:cash  -50 €

> hledger bal -f test
          550.00 inr  expenses:b
               -50 €  expenses:cash
        1,407.00 inr  expenses:m
        1,200.00 inr  liabilities:a
                   0  liabilities:p
          900.00 inr  liabilities:t
--------------------
        4,057.00 inr
               -50 €
```
Now the only postings that appear on `liabilities:p` side are in `inr`, but it still gets displayed as 0.

The minimal test case that demonstrates the issue:
```
> cat test2
2014-07-07 Desc 1
    liabilities:a  1200 inr
    liabilities:p

2014-07-18 Desc 4
    liabilities:p  1200 inr
    expenses:cash  -50 €

> h bal -f test2
               -50 €  expenses:cash
            1200 inr  liabilities
            1200 inr    a
                   0    p
--------------------
            1200 inr
               -50 €
```

**Comment by markokocic** [comment]
I finally did bisecting, and it looks like the issue started since dabb3ef82e1bd95744cfe8b1830e5a1038598759 commit.
Before that it was working correctly.

**Comment by Xitian9** [comment]
Yes, I've tracked down the precise location of the problem, but this issue is actually a bit tricky. You've actually uncovered two different bugs here (one in the balance command, the other in the close command), and fixing one of them makes the other break.

In your second example there is still a cost of 50 €, as what you wrote is short-hand for

**Comment by Xitian9** [comment]
#1511 Should solve this. I've also added a test to check for this. Let me know if this works for you.

**Comment by markokocic** [comment]
Hi @Xitian9, I can confirm that your branch works for me for this use case.

**Comment by simonmichael** [comment]
I've started adding the `regression!` label to track those but I think it's best reserved for released regressions, and I see that this issue was not a release bug. Yay! Good catch @markokocic.
