### ISSUE TITLE
Incorrect escaping of quoted commodities in balance CSV output

### ISSUE THREAD

**Issue by edlanglois** [simonmichael/hledger#1508]
For a commodity AB.C (entered as "AB.C" in the journal), the following CSV balance output is produced:

`hledger -f test.journal balance --output-format=csv`:
```csv
"account","balance"
"Assets:ABC","\"\"AB.C\"\" 1"
"Assets:Cash","$-1"
"total","$-1, \"\"AB.C\"\" 1"
```
`\"\"AB.C\"\"` is too much escaping. Quotes are escaped in CSV by entering them twice: `""` so `""AB.C""` is the properly escaped string. The extra `\`s can actually cause the `"` to be un-escaped from the perspective of a CSV reader such that they are interpreted as ending a string.

I think this is a regression, but I might be mis-remembering.

More details:
hledger version: 1.21

test file:
```
2021-01-01 Test
    Assets:ABC   "AB.C" 1
    Assets:Cash       -$1
```

**Comment by simonmichael** [comment]
Thanks for the report. Indeed, this changed in 1.21. Both outputs look a bit strange to me:
```
$ hledger-1.20 bal -N ABC -O csv
"account","balance"
"Assets:ABC","""AB.C"" 1"
$ hledger-1.21 bal -N ABC -O csv
"account","balance"
"Assets:ABC","\"\"AB.C\"\" 1"
```

Related, the terminal output has always shown the quotes; should it ?
```
$ hledger bal -N ABC
            "AB.C" 1  Assets:ABC
```

**Comment by simonmichael** [comment]
`register` shows the same change in CSV output, and also shows the quotes in terminal output:
```
$ hledger-1.20 reg ABC -O csv
"txnidx","date","code","description","account","amount","total"
"1","2021-01-01","","Test","Assets:ABC","""AB.C"" 1","""AB.C"" 1"
$ hledger-1.21 reg ABC -O csv
"txnidx","date","code","description","account","amount","total"
"1","2021-01-01","","Test","Assets:ABC","\"\"AB.C\"\" 1","\"\"AB.C\"\" 1"
$ hledger reg ABC
2021-01-01 Test               Assets:ABC                "AB.C" 1        "AB.C" 1
```

`print` doesn't quote the commodity in CSV output:
```
$ hledger print ABC -O csv
"txnidx","date","date2","status","code","description","comment","account","amount","commodity","credit","debit","posting-status","posting-comment"
"1","2021-01-01","","","","Test","","Assets:ABC","1","AB.C","","1","",""
"1","2021-01-01","","","","Test","","Assets:Cash","-1","$","1","","",""
```
and also shows the quotes in terminal output:
```
$ hledger print ABC
2021-01-01 Test
    Assets:ABC         "AB.C" 1
    Assets:Cash             $-1

```

**Comment by edlanglois** [comment]
Ideally commodity would always be its own column in CSV outputs so that no extra quoting (or parsing by readers) is necessary but I guess balance and register can't do this because they might have multi-commodity accounts. I agree that all the quotes in the CSV output look strange but it does enable other tools to parse the amount correctly when there are multiple commodities.

I don't have a strong opinion about whether terminal output for balance should include quotes but if someone had a commodity with spaces and numbers in the name that could look confusing when printed without quotes.

**Comment by simonmichael** [comment]
@Xitian9 has fixed the excess quoting in balance CSV output. Thanks!
