### ISSUE TITLE
New periodic expression request: ~ every weekday [$50]

### ISSUE THREAD

**Issue by makdisse** [simonmichael/hledger#1517]
### Use case

For anyone that does contract work or any type of business relationship that has a daily rate.
At the moment we can do the days of the week, eg: `~ every monday`, so it is possible to achieve what `~every weekday` would do.  But when you have to do it for multiple accounts it gets messy and hard to maintain. 

Having `weekday` available as a period would allow us to properly capture daily rates for months with a variable number of days and weekends.

My particular use case is to forecast the pay for contractor workers.

### Behaviour

Pretty much like `~ every day` but only considering `mon|tue|wed|thu|fri`

**Example:**

```
~ every weekday
  Income:Client1          -10 GBP
  Assets:Contractors:Contractor1
```

Executed with `hledger.exe -f .\test.ledger reg -b "2021-04-01" -e "2021-04-15" --forecast -w 120` should result in:

```
2021-04-01                                          Assets:Contractors:Contractor1                  10 GBP        10 GBP
                                                    Income:Client1                                 -10 GBP             0
2021-04-02                                          Assets:Contractors:Contractor1                  10 GBP        10 GBP
                                                    Income:Client1                                 -10 GBP             0
2021-04-05                                          Assets:Contractors:Contractor1                  10 GBP        10 GBP
                                                    Income:Client1                                 -10 GBP             0
2021-04-06                                          Assets:Contractors:Contractor1                  10 GBP        10 GBP
                                                    Income:Client1                                 -10 GBP             0
2021-04-07                                          Assets:Contractors:Contractor1                  10 GBP        10 GBP
                                                    Income:Client1                                 -10 GBP             0
2021-04-08                                          Assets:Contractors:Contractor1                  10 GBP        10 GBP
                                                    Income:Client1                                 -10 GBP             0
2021-04-09                                          Assets:Contractors:Contractor1                  10 GBP        10 GBP
                                                    Income:Client1                                 -10 GBP             0
2021-04-12                                          Assets:Contractors:Contractor1                  10 GBP        10 GBP
                                                    Income:Client1                                 -10 GBP             0
2021-04-13                                          Assets:Contractors:Contractor1                  10 GBP        10 GBP
                                                    Income:Client1                                 -10 GBP             0

```

### Bonus

Maybe getting `~ every weekend` will be a nice bonus for feature completeness.
It could be used by people who provide contracting work only on weekends I guess.

**Comment by simonmichael** [comment]
Nice proposal!

Would anyone like to have a go at this ? hledger-lib:Hledger.Data.Dates.reportingintervalp is some relevant code.

**Comment by simonmichael** [comment]
`every weekend` might suggest one event per weekend.. perhaps `every weekendday` or `every nonweekday` would be better.

**Comment by simonmichael** [comment]
@makdisse has added a $50 bounty for this (support "~ every weekday").

**Comment by ShrykeWindgrace** [comment]
This change will require an explicit note in documentation on what we understand under "work day". While many countries understand it implicitly  as "Mon .. Fri", I've seen cases of "Mon .. Sat", "Sun .. Thu", "Sun .. Fri", and "Sat .. Thu" (I am sure that this list is not exhaustive).

**Comment by la-wu** [comment]
How about directly using the syntax of a combination of days? e.g

```
~ every mon|tue|wed|thu|fri
~ every sat|sun
```

We could make `weekday` and `weekendday` aliases for the 'standard' groups (above) if desired.

**Comment by simonmichael** [comment]
@makdisse , @la-wu has implemented this with #1632 ([doc](https://hledger.org/dev/hledger.html#events-on-multiple-weekdays)).

**Comment by makdisse** [comment]
@la-wu Thank you! I could not find your email on your github page. Could you please email me your bank acc details so I can transfer the bounty paulo@makdisse.com

**Comment by Xitian9** [comment]
I think this issue can be closed now.

**Comment by simonmichael** [comment]
@la-wu @makdisse is the bounty still pending, or was it paid ?

**Comment by la-wu** [comment]
@simonmichael Yes it was paid and everything is settled AFAIK. Thanks!

**Comment by simonmichael** [comment]
Awesome! Thanks.
