### ISSUE TITLE
hledger-ui 1.21's register is ignoring query arguments

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1523]
Since hledger-ui-1.21, the register screen is not affected by query arguments set by `/` or by command line arguments.

**Comment by Xitian9** [comment]
Could you describe what the expected behaviour is? I can confirm on my end that filtering on the register screen does not have any effect, but this behaviour seems to go back further, to at least 1.20.

**Comment by Xitian9** [comment]
Oops, my mistake. I managed to accidentally rebuild only hledger instead of hledger-ui when testing. I can confirm the behaviour is fine in hledger-1.20.

**Comment by Xitian9** [comment]
Git bisect says this first appears in 507648383d57b691644eb564f05b5b9ea688f686

**Comment by simonmichael** [comment]
Thanks! I'll fix.

**Comment by simonmichael** [comment]
It should be fixed now. I tripped up with updating ropts/rspec, which I'm pretty much guaranteed to do since #1340. I don't regret that change, but the current setup does indeed invite mistakes.
