### ISSUE TITLE
Hledger can't parse valid Ledger file

### ISSUE THREAD

**Issue by In-line** [simonmichael/hledger#1524]
```
hledger: /main.ledger:3501:51:
     |
3501 |     Equity:Opening Balances             (-0.0001 PRV + 0.002 PRV)
     |                                                   ^
unexpected 'P'
expecting ';', '=', end of input, ledger-style lot date, ledger-style lot price, newline, or transaction price
```

hledger 1.21
Ledger 3.2.1-20200518, the command-line accounting tool

**Comment by simonmichael** [comment]
Thanks for the report. It's not actually a bug; we don't support 100% of ledger syntax and features, such as parenthesised value expressions.

**Comment by In-line** [comment]
@simonmichael if it isn't supported currently, why don't plan to add it in the future?

**Comment by simonmichael** [comment]
@In-line we could discuss that. Basically: it's a difficult feature to implement well, we will never reach 100% compatibility with Ledger's implementation of it, no-one has done the work, and above all in the big picture I doubt this feature brings enough benefit to justify the cost. 

However someone did make a start on it which could be revived: #934.
