### ISSUE TITLE
XSS vulnerability: malicious javascript can be stored via hledger-web add/edit

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1525]
hledger-web's forms sanitise obvious javascript, but not obfuscated javascript (cf https://owasp.org/www-community/xss-filter-evasion-cheatsheet). This means hledger-web instances, especially anonymously-writable ones like demo.hledger.org, could be loaded with malicious javascript to be executed by subsequent visitors. Reported by Gaspard Baye and Hamidullah Muslih, who also provided a video and example of such js which I can share.

hledger-web processes forms with runFormPost, part of [yesod-form](https://hackage.haskell.org/package/yesod-form). I am guessing that makes use of [xss-sanitize](https://hackage.haskell.org/package/xss-sanitize) ? But note sanitising and escaping are different (https://github.com/yesodweb/haskell-xss-sanitize#readme). I get the impression it may be impossible to escape/sanitise with 100% reliability; if so, what should we do ? Tighten up sanitization as much as we can and document that anonymous-writable hledger-web's are unsafe and not recommended, and make demo.hledger.org read only ? 

I would appreciate any help diagnosing and resolving this. Questions to be answered: 

- which libraries are involved here - yesod-form, xss-sanitize, ... ?
- are we getting the most protection available from them ?
- should we open bugs against any of them ?
- is it ok for me to share an example of obfuscated js here ?
- are there any public hledger-web instances other than demo.hledger.org ?
- is reliable escaping/sanitisation possible ?
- if not, what should be done for hledger-web ?

**Comment by simonmichael** [comment]
Questions to be answered: 
- which libraries are involved here - yesod-form, xss-sanitize, ... ?
- are we getting the most protection available from them ?
- should we open bugs against any of them ?
- is it ok for me to share an example of obfuscated js here ?
- are there any public hledger-web instances other than demo.hledger.org ?
- is reliable escaping/sanitisation possible ?
- if not, what should be done for hledger-web ?

**Comment by simonmichael** [comment]
(For answers to the questions above, see discussion on #1663.)

**Comment by frasertweedale** [comment]
@simonmichael Sorry to bump an historical issue, but wondering if you could advise in which version of `hledger-web` this issue was introduced, and also whether it existed in `hledger` before the web bits were split out (and if so, which version introduced it).

**Comment by frasertweedale** [comment]
@simonmichael sorry for the noise, just noticed this info the corresponding PR discussion.  Thanks!
