### ISSUE TITLE
timeclock h commodity no longer rounded to two digits after decimal, and the commodity directive does not help

### ISSUE THREAD

**Issue by lestephane** [simonmichael/hledger#1527]
```
$ hledger print -f - <<EOF | head
> commodity 00.00 h
> $(<"$(pwd)/aliases.journal")
> !include timeclock:2-preprocessed/2020/2020-01-30.csv
> EOF
2020-01-30 * 08:38-09:03
    (wrk:learn:math)    0.416666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666667 h
```

It used to be

```
-    (wrk:learn:math)           0.42h
```

**Comment by lestephane** [comment]
The version is 1.21. The input looks like this (ignore the csv extension)

```
$ grep -A1 math  2-preprocessed/2020/2020-01-30.csv
i 2020-01-30 08:38:35 math
o 2020-01-30 09:03:35
```

The aliases look like this (not that aliases play any role here):

```
$ grep -E "alias (math|learn)" aliases.journal
alias learn=wrk:learn
alias math=learn:math
```

**Comment by simonmichael** [comment]
Thank you, I confirm.

a.timeclock
```
i 2020-01-30 08:38:35 math
o 2020-01-30 09:03:35
```

a.j
```
commodity 1.000h
include a.timeclock
```

Reading directly from a timeclock file, it is supposed to round hours to two digits:

```
$ hledger-1.20 -f a.timeclock print
2020-01-30 * 08:38-09:03
    (math)           0.42h

$ hledger-1.21 -f a.timeclock print
2020-01-30 * 08:38-09:03
    (math)    0.416666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666667h

```

Reading from a parent journal with a commodity directive, the commodity directive's style should be applied:

```
$ hledger-1.20 -f a.j print
2020-01-30 * 08:38-09:03
    (math)          0.417h

$ hledger-1.21 -f a.j print
2020-01-30 * 08:38-09:03
    (math)    0.416666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666666667h

```

**Comment by Xitian9** [comment]
A git bisect says this was a deliberate choice introduced with 61013689546433628f175883a7b34ec9a91b5f0c to solve another issue.

**Comment by simonmichael** [comment]
Ahh, right you are, thanks. Yes, I changed `print` to unconditionally show all decimal places, ignoring even commodity directives.

That's not ideal when reading timeclock files. 

We could add a special case: amounts from timeclock files are always rounded to two decimal places while being read ? This sounds not ideal either.

**Comment by simonmichael** [comment]
After discussion with glguy: the resolution of the timeclock format is whole seconds. Very early in hledger's history I chose to display timeclock amounts as decimal hours, to make my time reporting easier. It's this conversion that causes the large recurring decimals. I think always rounding these timeclock amounts to two decimal places is fine, it's a slight approximation but it doesn't really lose any significant precision.
