### ISSUE TITLE
unwanted ANSI color codes when redirecting output with `-o/--output-file`

### ISSUE THREAD

**Issue by RobertNielsen1** [simonmichael/hledger#1533]
This is a **small** bug, and I have only seen it with incomestatement reports that have negative numbers AND which output to a text file. In other words, the problem doesn't appear in reports that output to a screen.

Tested with hledger 1.21.

Test file:

=============
```
2020-02-17 Vita Drugstore
    Expenses:Drugstore                        -$5.00 ; refund
    Liabilities:AbraCard

2020-02-23 Cheap-O Gas
    Expenses:Automotive:Silver car            $33.68
    Liabilities:AbraCard

```

=============

Entering at the command line:

`hledger  is -o test.txt`

After opening the file test.txt:

```
Income Statement 2020-02-17W08

                                || 2020-02-17W08 
================================++===============
 Revenues                       ||               
--------------------------------++---------------
--------------------------------++---------------
                                ||               
================================++===============
 Expenses                       ||               
--------------------------------++---------------
 Expenses:Automotive:Silver car ||        $33.68 
 Expenses:Drugstore             ||        [31m$-5.00[m 
--------------------------------++---------------
                                ||        $28.68 
================================++===============
 Net:                           ||       [31m$-28.68[m 

```

Again, this is a small problem, one that I can easily work around, so no rush.

Thank you!

Rob

**Comment by simonmichael** [comment]
Thanks for the report!

`-o` is not disabling ANSI color as it should. 

```
2021-01-01
  (a)  -1
```
In an emacs shell configured to show ANSI codes (`M-x ansi-color-for-comint-mode-off`):
In terminal output, negative numbers are colored red:
```
$ hledger -f a.j bal -N 
                  [31m-1[m  a
```
When stdout is redirected to a file, color is properly disabled:
```
$ hledger -f a.j bal -N >a
$ cat a
                  -1  a
```
But when doing the same via `-o`, it is not:
```
$ hledger -f a.j bal -N -o a
$ cat a
                  [31m-1[m  a
```

**Comment by RobertNielsen1** [comment]
Very helpful and clear explanation!

Also, it appears that bash sometimes handles incomestatement output when Emacs doesn't. That is, if I create a report with:

`hledger  is -N -o a.txt`

if I execute the command:

`cat a.txt`

the output is:
```
Income Statement 2020-02-17W08

                                || 2020-02-17W08 
================================++===============
 Revenues                       ||               
--------------------------------++---------------
================================++===============
 Expenses                       ||               
--------------------------------++---------------
 Expenses:Automotive:Silver car ||        $33.68 
 Expenses:Drugstore             ||        $-5.00 

```
[On my command line output, the $-5.00 is shown in red. The color seems to have disappeared when pasting it here.]

However, if I open the file in Emacs, it shows:

```
Income Statement 2020-02-17W08

                                || 2020-02-17W08 
================================++===============
 Revenues                       ||               
--------------------------------++---------------
================================++===============
 Expenses                       ||               
--------------------------------++---------------
 Expenses:Automotive:Silver car ||        $33.68 
 Expenses:Drugstore             ||        [31m$-5.00[m 

```

Thank you.

**Comment by RobertNielsen1** [comment]
Oops. I think I hit the "close" button when I shouldn't have. I will reopen it.

**Comment by simonmichael** [comment]
Fixed in master. This never worked since the introduction of colour in hledger 1.3. Good catch!

**Comment by simonmichael** [comment]
PS your last example is explainable: with the buggy behaviour, the ANSI codes were saved into a.txt, and the terminal translates them to colour when you `cat a.txt`, but emacs does not when you edit a.txt.
