### ISSUE TITLE
web docs: headings differing in case (eg: tags and Tags) are not linked properly in TOC/search

### ISSUE THREAD

**Issue by jblachly** [simonmichael/hledger#1534]
The `#tags` anchor is used twice; once in the CLI section:

https://hledger.org/hledger.html#tags

And once for the Journal format section. Both are linked from the TOC. However, the hyperlink to journal format section does not work for obvious reasons.

I attempted to fix this myself for PR but am slightly embarrassed to say that the documentation file structure and mechanics are too convoluted for me.

**Comment by simonmichael** [comment]
Thanks! This is in progress at https://github.com/badboy/mdbook-toc/issues/15.

**Comment by simonmichael** [comment]
Closing this in favour of https://github.com/simonmichael/hledger_site/issues/33, reducing the current issue count from 6 to 5. :)
