### ISSUE TITLE
The parsing error displayed when two consecutive lines start with 'i' in a timeclock: include does not contain the location of the offending input file

### ISSUE THREAD

**Issue by lestephane** [simonmichael/hledger#1546]
I have one .timeclock file per day, and when I include each in a larger journal using `!include timeclock:...`.

Once in a while I make mistakes, and there is a parsing error (see below, two lines starting with 'i', without 'o' in between). The current error message is such that I have to figure out which of the many journals I include is to blame.

It would be easier if the offending file name would be displayed alongside the parsing error.

```
$ cat <<EOF > /tmp/input.txt
> i 2021-04-28 07:03:22 work
> i 2021-04-28 08:21:43 rest
> o 2021-04-28 08:36:43
> EOF

$ cat <<EOF > /tmp/parent.journal
!include timeclock:input.txt
EOF

$ hledger print -f /tmp/parent.journal 
hledger-39623934c38e12007434aeb4bf6fc0a280b62889: line 2: expected timeclock code o but got i
CallStack (from HasCallStack):
  error, called at ././Hledger/Data/Timeclock.hs:90:32 in hledger-lib-1.21.99-GglkDzcGeGQ4NXFwv9cPau:Hledger.Data.Timeclock
```

**Comment by simonmichael** [comment]
I agree that would be much better. We need a PR for this.

FYI, `!include` is old syntax, it has been `include` for many years.

**Comment by simonmichael** [comment]
This was fixed.
