### ISSUE TITLE
Quotes in csv are double escaped?

### ISSUE THREAD

**Issue by egh** [simonmichael/hledger#1552]
In the latest version of hledger (I am using the ubuntu binary from [here](https://github.com/simonmichael/hledger/releases/tag/1.21)), quotes seem to be overly escaped in CSV output.

```
$ hledger --version
hledger 1.21
```

Ledger file:
```
2021-01-01 Test"quote
    Assets:ABC   "AB.C" 1
    Assets:Cash       -$1
```

Test:
```
$ hledger -f test.lgr reg --output-format=csv 
"txnidx","date","code","description","account","amount","total"
"1","2021-01-01","","Test\"\"quote","Assets:ABC","\"\"AB.C\"\" 1","\"\"AB.C\"\" 1"
"1","2021-01-01","","Test\"\"quote","Assets:Cash","$-1","$-1, \"\"AB.C\"\" 1"
```

and:
```
hledger -f test.lgr balance -N --output-format=csv 
"account","balance"
"Assets:ABC","\"\"AB.C\"\" 1"
"Assets:Cash","$-1"
```

In an old hledger version (1.18.1) the quotes seem to work properly:
```
$ /usr/bin/hledger --version
hledger 1.18.1
$ /usr/bin/hledger -f test.lgr reg --output-format=csv 
"txnidx","date","code","description","account","amount","total"
"1","2021-01-01","","Test""quote","Assets:ABC","""AB.C"" 1","""AB.C"" 1"
"1","2021-01-01","","Test""quote","Assets:Cash","$-1","$-1, ""AB.C"" 1"
```

This was perhaps introduced here: https://github.com/simonmichael/hledger/commit/4cb9dfb5b8d130b1005fbd5a8fc73e068a7d527f but, strangely, that output is different from what I see.

**Comment by simonmichael** [comment]
Thanks, previously reported as #1508 but not yet released..

**Comment by egh** [comment]
Sorry, should have checked the *closed* tickets! I forgot I wasn't using the bleeding edge :smile: Thank you!

**Comment by simonmichael** [comment]
No problem, and hello @egh. This reminds me to get a bugfix release out. FYI I've set up http://bugs.hledger.org to (always, hopefully) show the recent bug reports whether open or closed.

**Comment by egh** [comment]
:wave: Thank you @simonmichael, that's good to know.
