### ISSUE TITLE
Don't write debug.log to $HOME when pressing `V` or `B` in hledger-ui.

### ISSUE THREAD

**Issue by crocket** [simonmichael/hledger#1556]
There is no option to disable writing debug.log to $HOME when I press `V` or `B` in hledger-ui.

**Comment by simonmichael** [comment]
hledger-1.21 was writing `./debug.log` when you press V, thanks for the report. This is fixed in master.

**Comment by Xitian9** [comment]
Sorry to resurect this, but there's another instance of this bug which arises when you press `g` in the transaction screen. I've put a PR for this in #1576.

**Comment by simonmichael** [comment]
(Not actually a regression, the V key has being doing this since the feature was introduced.)
