### ISSUE TITLE
hledger-web seems to break when --base-url includes path

### ISSUE THREAD

**Issue by levitanong** [simonmichael/hledger#1562]
Version: hledger-web 1.21
Platform: WSL2
Related Docs: https://hledger.org/hledger-web.html#options

- https://raw.githubusercontent.com/simonmichael/hledger/master/examples/sample.journal
- `hledger-web --server --port 5001 -f $PATH_TO_SAMPLE_JOURNAL`
- `hledger-web --server --port 5002 --base-url http://localhost:5002/foo -f $PATH_TO_SAMPLE_JOURNAL`

1. If I visit `localhost:5001`, everything works as expected.

2. If I visit `localhost:5002/foo`, all the resources are broken, but clearly it's hitting the server. Also, it's trying to look for a webserver endpoint `foo` as if it were rooted at `/`. `localhost:5002/foo/journal` has the same behavior.
With `curl -si http://localhost:5002/foo`, I'm getting `HTTP/1.1 404 Not Found`. The other header information has been elided since they don't seem useful. The HTML is consistent with the screenshot.
![image](https://user-images.githubusercontent.com/869638/118386601-29802b00-b64b-11eb-9c43-64dd54a0bbce.png)

3. If I visit `localhost:5002/journal`, all the resources are still broken, but it's loading the general journal.
With `curl -si http://localhost:5002/journal`, I'm getting `HTTP/1.1 200 OK`. The other header information has been elided since they don't seem useful. The HTML is consistent with the screenshot.
![image](https://user-images.githubusercontent.com/869638/118386636-749a3e00-b64b-11eb-8917-b0cb0368d71c.png)

A quick guess reveals that the assets remain in `curl -si http://localhost:5002/static/hledger.js`. Setting `--file-url` doesn't seem to have any effect.

**Comment by simonmichael** [comment]
Thanks for this report. Do we have any hledger-web-using devs who could investigate ?

**Comment by levitanong** [comment]
I was able to get around this by adding rewrite rules in NGINX:
```
location /hledger {
    if ($ssl_client_verify != SUCCESS) { return 403; }
    rewrite ^/hledger$ / break;
    rewrite ^/hledger/$ / break;
    rewrite ^/hledger/(.+) /$1 break;
    proxy_pass http://127.0.0.1:5000;
}
```
For those unfamiliar with nginx, this is configuration for a reverse proxy: all it does is rewrite the URL to remove the `/hledger` prefix, and pass the modified path to the hledger-web server.

**Comment by jfly** [comment]
I dug into this a bit, and I think this is actually working as intended by yesod itself: the approot parameter affects url *generation*, but not route *parsing*. See https://github.com/yesodweb/yesod/issues/1792 for details. In other words, it sounds like these knobs are really only useful if you're running your yesod application behind a reverse proxy that does path rewriting (as @livtanong demonstrated in their last comment).

Perhaps the hledger-web docs could be a bit clearer about this? From https://hledger.org/1.28/hledger-web.html#options:

> --base-url=URL : set the base url (default: http://IPADDR:PORT). You would change this when sharing over the network, or integrating within a larger website.

Perhaps we could replace "or integrating within a larger website" with something like "or running behind a reverse proxy that with path base rerouting"? That would at least make it clear that it's only for use when run behind a reverse proxy. I was convinced that this should be able to work without something *else* doing path based rewrites.

**Comment by simonmichael** [comment]
Thank you very much @jfly! How does this look to you both (in the manual; the CLI help is briefer):

`--base-url=URL` : set the base url (default: http://IPADDR:PORT). Note: affects url generation but not route parsing. Can be useful if running behind a reverse web proxy that does path rewriting.

**Comment by jfly** [comment]
Love it, @simonmichael! This issue can probably get closed =)

**Comment by simonmichael** [comment]
Excellent, doc change pushed to master.
