### ISSUE TITLE
Can't generate info manual: getDirectoryContents:openDirStream: does not exist

### ISSUE THREAD

**Issue by DamienCassou** [simonmichael/hledger#1565]
I've a git checkout of latest `master` branch (i.e., 3dc813add0ee1966782b951c91011ab534eea3a4). I can't generate info pages:

```
$ ./Shake infomanuals
Shake: site: getDirectoryContents:openDirStream: does not exist (No such file or directory)
```

**Comment by simonmichael** [comment]
@DamienCassou, thanks for the report. Shake.hs had an old dependency on having the website checked out as `./site`, I have pushed a fix.
