### ISSUE TITLE
CSV report output does not represent account tree structure

### ISSUE THREAD

**Issue by benwebber** [simonmichael/hledger#1566]
I'm passing hledger's CSV reports through pandoc/LaTeX to generate attractive PDF reports.

I like how the tree view works in the text reports:

```
hledger bs -f sample.journal --tree --no-elide
```
```
Balance Sheet 2008-12-31

             || 2008-12-31 
=============++============
 Assets      ||            
-------------++------------
 assets      ||        $-1 
   bank      ||         $1 
     saving  ||         $1 
   cash      ||        $-2 
-------------++------------
             ||        $-1 
=============++============
 Liabilities ||            
-------------++------------
 liabilities ||        $-1 
   debts     ||        $-1 
-------------++------------
             ||        $-1 
=============++============
 Net:        ||          0 
```

However, the CSV output does not encode the tree structure: 

```
hledger bs -f sample.journal --tree --no-elide -O csv
```
```
"Balance Sheet 2008-12-31",""
"Account","2008"
"Assets",""
"assets","$-1"
"bank","$1"
"saving","$1"
"cash","$-2"
"Total:","$-1"
"Liabilities",""
"liabilities","$-1"
"debts","$-1"
"Total:","$-1"
"Net:","0"
```

In the example above, one can't determine that `assets:cash` and `assets:bank:saving` belong to `assets` without prior knowledge of the account names and more complex parsing rules. It might be possible to work around the issue with aliases, but I haven't tested that yet.

I can think of two ways to encode the tree directly:

1. Indent each account name with a number of spaces, as we do in the text output. For example:

    ``` 
    "assets","$-1"
    "  bank","$1"
    "    saving","$1"
    "  cash","$-2"
    ```
2. Add another column representing the depth.

Technically, either would be a breaking change. However, given that there is no difference between the tree output and the normal output, there is no real reason to generate a CSV report with `--tree` right now. I can't imagine either change would impact many users.

**Comment by simonmichael** [comment]
That's odd, I thought we had a numeric "indent" column, perhaps in the past, but I don't see it.

The `balance` command at least provides the full account names. `balancesheet` seems to have changed (regressed?) in 1.20.3, showing only the leaf names:
```
$ hledger-1.20.2 -f examples/sample.journal bs --tree --no-elide -O csv
"Balance Sheet 2008-12-31",""
"Account","2008"
"Assets",""
"assets","$-1"
"assets:bank","$1"
"assets:bank:saving","$1"
"assets:cash","$-2"
"Total:","$-1"
"Liabilities",""
"liabilities","$-1"
"liabilities:debts","$-1"
"Total:","$-1"
"Net:","0"
$ hledger-1.20.3 -f examples/sample.journal bs --tree --no-elide -O csv
"Balance Sheet 2008-12-31",""
"Account","2008"
"Assets",""
"assets","$-1"
"bank","$1"
"saving","$1"
"cash","$-2"
"Total:","$-1"
"Liabilities",""
"liabilities","$-1"
"debts","$-1"
"Total:","$-1"
"Net:","0"
```

**Comment by benwebber** [comment]
Interesting. The regression seems to affect `bs`, `bse`, and `is`.

It would also be easy to detect how deep each leaf is if the account column contained the fully qualified account names. That is a better solution than indenting the account names with spaces.

**Comment by simonmichael** [comment]
It sounds like we just need to fix the 1.20.3 regression then.

**Comment by Xitian9** [comment]
Git bisect says this broke at this commit: 334c62732dc0c966a28cc181f9a845ddcda1b5b5.

**Comment by simonmichael** [comment]
@Xitian9: sorry but as I think about it more: Aren't we in effect making --tree have no effect on CSV output ? Is that fine, or should we adjust CSV output based on --tree, since we do this with some other report output options, and it would be easier to consume for someone trying to generate a tree-formatted report ? If we think that's worth doing, some more notes:

- we could add a "depth" column (1-based, same as --depth; also present in list mode, for a stable schema)
- we should decide whether to mimic the terminal output's boring parent eliding
- again for ease of consumption and report formatting, should we always include both full account name and leaf name ? 

I do believe the CSV included these things at one time, I just haven't found the commit. I simplified it since nobody was using the extra columns and it seemed more useful to have a simple CSV that you could just drag into a spreadsheet and have it make sense right away. So these goals are a bit in conflict (simple human-readable CSV, rich formattable CSV).

**Comment by Xitian9** [comment]
Indeed, the behaviour just prior to this breaking was to basically ignore `--tree` for csv output. I don't have a strong opinion on which option is better. To me a csv file screams ‘independent of row order’, which is definitely not the case for your proposed format, but also we already violate that for balancesheet output anyway (it matters where those report subheaders go).

My weak opinion is that csv output should force --flat mode. Maybe we can make this explicit by throwing an error if you try to call both together, or maybe we can just silently ignore it as we do now. But I'll leave the decision up to others.

**Comment by simonmichael** [comment]
"CSV forces list (flat) mode" is the quickest and easiest way to get things on a clear footing again, so I'd be fine with this. 

Ideally we'd document it somewhere. There is a related problem: I haven't found a great place to document CSV output or output formats generally. Currently I mention them briefly at the end of each command's intro text, before the first heading. This is ok for a short mention but if we have to go into detail they should get their own heading. I have avoided this because it seems like the same heading would recur for each command, which causes unstable non-mnemonic urls.

**Comment by simonmichael** [comment]
PS and now I wonder how `json`, `html` and other future formats do/should handle these things. But I don't want to get sidetracked.

**Comment by simonmichael** [comment]
For now I'll merge this and add a note to the five affected commands.

**Comment by simonmichael** [comment]
Well darn, I'm wrong; --tree does still alter CSV output, see the added parent account rows below.
```
$ hledger -f examples/sample.journal bal -O csv
"account","balance"
"assets:bank:saving","$1"
"assets:cash","$-2"
"expenses:food","$1"
"expenses:supplies","$1"
"income:gifts","$-1"
"income:salary","$-1"
"liabilities:debts","$1"
"total","0"
$ hledger -f examples/sample.journal bal -O csv -t
"account","balance"
"assets","$-1"
"assets:bank:saving","$1"
"assets:cash","$-2"
"expenses","$2"
"expenses:food","$1"
"expenses:supplies","$1"
"income","$-2"
"income:gifts","$-1"
"income:salary","$-1"
"liabilities:debts","$1"
"total","0"
```
I'm just going to revert my doc change and leave this for now.

**Comment by Xitian9** [comment]
Oh, good catch. Should we make it force list mode?

**Comment by simonmichael** [comment]
The current behaviour might have some use (similar behaviour was recently requested for the terminal output). Let's leave it alone until next time we have a clear need driving it. I clarified the tests a little.

**Comment by benwebber** [comment]
The 1.20.2 output is ideal (with proper `--drop` support). If the CSV output contains the balances for the parent accounts (e.g., `assets`, `assets:bank`), then the user does not have to calculate the balances themselves when they feed the data into another system. It's also easier to parse the accounts into a tree structure in one pass; one simply needs to keep track of the accounts they've already seen:

```
assets  # new parent account
assets:bank  # saw "assets", must belong to "assets"
assets:bank:saving   # saw "assets:bank", must belong to "assets:bank"
assets:cash  # saw "assets", must belong to "assets"
```

**Comment by simonmichael** [comment]
I think that's what we have in master, once again. 

Things get a little complicated when you --drop (rows may be dropped, or retained with `...` as account name, depending on the situation). But that's consistent with `txt` output and in any case a separate issue.

**Comment by simonmichael** [comment]
PS I used the wrong issue number in 0073c85c7 which can be really confusing. I have fixed the commit message and re-pushed the last two commits to master, rewriting history, sorry about that.

**Comment by benwebber** [comment]
Confirmed, I built the latest `master`. Thanks!

**Comment by simonmichael** [comment]
This can be closed I think ?

**Comment by Xitian9** [comment]
I think so.
