### ISSUE TITLE
Cannot toggle cost in hledger-ui transaction screen

### ISSUE THREAD

**Issue by Xitian9** [simonmichael/hledger#1577]
Well, you can, but it's difficult. Consider the following journal:

```
$ cat t.j
D 1. C

P 2021-06-01 A  1 C
P 2021-06-01 B  2 C

2021-06-01 Test
  (a)  1 A @ 1 B
```

There are four possible outputs I'd like to see based on cost and valuation:
1. No cost and no valuation: 1 A
2. No cost and valuation: 1 C
3. Cost and no valuation: 1 B
4. Cost and valuation: 2 C

- Open `hledger-ui -f t.j` and move to the transaction screen (press -> twice). It should display 1 A as expected.
- Pressing `V` toggles valuation, switching between 1 A and 1 C.
- Pressing `B` does not toggle cost, it remains at 1 A.

However, pressing `g` to reload the file can allow you to work around these, in unintuitive ways:
- Pressing `B` then `g` will switch to cost, showing 1 B. Pressing `V` at this point will toggle between 1 B and 2 C.
- Pressing `g` twice will get rid of valuation, but have no effect on cost.

To conclude:
- `V` works as expected.
-  `B` can be made to work if you press `g` afterwards.
-  Pressing `g` twice will unset valuation, but have no effect on toggle.

It's clear that pressing `B` will set the appropriate cost option, but the journal won't be updated until you reload it with `g`. `B` should work without updating the journal. I'm not sure what effect `g` is supposed to have on valuation/cost. Is it supposed to clear both valuation and cost? Have no effect on either? Clear only valuation but not cost? I can try to debug this when I know what the correct behaviour is.

**Comment by Xitian9** [comment]
git bisect says this one is my fault: 53611be6e

**Comment by Xitian9** [comment]
I think there are two issues here: B not working, and incorrect behaviour of `g`. I think this issue should be restricted to the former; the second can be dealt with elsewhere.

**Comment by simonmichael** [comment]
`g` is supposed to just reload the data, not change your viewing mode - it shouldn't affect the B or V state.

**Comment by simonmichael** [comment]
Great catch, thanks!

**Comment by Xitian9** [comment]
Okay, then the bug is in the documentation: the code which `g` calls says that it resets both the cost and valuation mode, and actually did reset the value_ mode.

**Comment by simonmichael** [comment]
Ack.. hmm. We'll discuss/investigate more elsewhere, as you rightly said.

**Comment by Xitian9** [comment]
I'll open a separate PR for that change, and we can decide on it as part of the next release cycle. I doubt anybody will encounter it much in practice.
