### ISSUE TITLE
Problem with info manual

### ISSUE THREAD

**Issue by DamienCassou** [simonmichael/hledger#1594]
The info manual of release 1.22 contains a broken DIR INFO section: trying to open the hledger manual from the top-level manual results in an error message. Here is the patch to make it work for me:

```patch
--- a/embeddedfiles/hledger.info	1970-01-01 01:00:01.000000000 +0100
+++ b/embeddedfiles/hledger.info	2021-07-04 12:57:09.220493292 +0200
@@ -2,7 +2,7 @@
 
 INFO-DIR-SECTION User Applications
 START-INFO-DIR-ENTRY
-* hledger: (hledger/hledger).  Command-line plain text accounting tool.
+* hledger: (hledger).  Command-line plain text accounting tool.
 END-INFO-DIR-ENTRY
```

**Comment by simonmichael** [comment]
Thanks for the report. I spent lots of time on these, and didn't see this - could you tell me how to reproduce ?

**Comment by DamienCassou** [comment]
If you are using Nix, you can just install hledger 1.22 and call `info` either from the command line or from Emacs. From there, if you try to open the info manual of hledger (or hledger-web) you will get:

> user-error: Info file hledger/hledger does not exist
> user-error: Info file hledger-web/hledger-web does not exist

If you apply the patch, it will work. Here is an extract of the system `dir` file:

```
User Applications
* Ledger3: (ledger3).           Command-Line Accounting
* hledger: (hledger/hledger).           Command-line plain text accounting tool.
* hledger-ui: (hledger-ui/hledger-ui).
                                Terminal UI for the hledger accounting tool.
* hledger-web: (hledger-web/hledger-web).
                                Web UI/API for the hledger accounting tool.
```

In my 378-line long `dir` file, only hledger entries have a slash in them.

Please note that all info files are symlinked in the same directory as the `dir` file:

```
$ ls -l ~/.nix-profile/share/info/{hledger*.info,dir}
-r--r--r-- 1 root root 22089 Jan  1  1970 /home/cassou/.nix-profile/share/info/dir
lrwxrwxrwx 1 root root    80 Jan  1  1970 /home/cassou/.nix-profile/share/info/hledger.info -> /nix/store/xkgfb6gwwkh4y1ylzc5i1b5vblaanwkc-hledger-1.22/share/info/hledger.info
lrwxrwxrwx 1 root root    86 Jan  1  1970 /home/cassou/.nix-profile/share/info/hledger-ui.info -> /nix/store/m5q6kdlxmrs54wq61aq9ipbdbiqa1jd5-hledger-ui-1.22/share/info/hledger-ui.info
lrwxrwxrwx 1 root root    88 Jan  1  1970 /home/cassou/.nix-profile/share/info/hledger-web.info -> /nix/store/i5v6gywf7wy6vcs4z8x23p5k69ix0h1m-hledger-web-1.22/share/info/hledger-web.info
```

**Comment by simonmichael** [comment]
I'm not using nix. Is this an issue with hledger's packaging in nix ? The `dir` file we provide is for hledger developers and probably not what nix should use (most packagers would run install-info I believe).

**Comment by DamienCassou** [comment]
I downloaded 3 release tarballs from 3 different packages including info manuals.

Here is a part of aspell.info:

```info
INFO-DIR-SECTION GNU Packages
START-INFO-DIR-ENTRY
* Aspell: (aspell).        GNU Aspell spelling checker
END-INFO-DIR-ENTRY
```

Here is a part of emacs.info:

```info
INFO-DIR-SECTION Emacs
START-INFO-DIR-ENTRY
* Emacs: (emacs).               The extensible self-documenting text editor.
END-INFO-DIR-ENTRY
```

Here is a part of of gnupg.info:

```info
INFO-DIR-SECTION GNU Utilities
START-INFO-DIR-ENTRY
* gpg2: (gnupg).           OpenPGP encryption and signing tool.
* gpgsm: (gnupg).          S/MIME encryption and signing tool.
* gpg-agent: (gnupg).      The secret key daemon.
* dirmngr: (gnupg).        X.509 CRL and OCSP server.
* dirmngr-client: (gnupg). X.509 CRL and OCSP client.
END-INFO-DIR-ENTRY
```
Compare that to hledger.info:

```info
INFO-DIR-SECTION User Applications
START-INFO-DIR-ENTRY
* hledger: (hledger/hledger).  Command-line plain text accounting tool.
END-INFO-DIR-ENTRY
```

As you can see, only hledger.info contains a slash `/` between the parenthesis. The info file is the only one which is important for packaging, the `dir` file is generated by each system automatically.

Conclusion:
- do whatever you want with the `dir` file;
- make sure that in hledger's release tarball no slash `/` is included in the `INFO-DIR-SECTION` between parenthesis.

I see 2 solutions: either
- keep the info file as it is in git and make sure your release script gets rid of the additional `hledger/`, or
- make sure the info file in git does not contain `hledger/`

**Comment by simonmichael** [comment]
I see, we're talking about the .info files themselves. I'll get rid of the slash there, at whatever cost to other workflows. Thanks for reporting.

**Comment by DamienCassou** [comment]
thank you very much
