### ISSUE TITLE
Unable to load non-default journal file in hledger-web

### ISSUE THREAD

**Issue by Xitian9** [simonmichael/hledger#1599]
I'm not sure if this is related to #1562, but when trying to run hledger-web with a journal specified on the command line, I get an error:
```
$ hledger-web -f chart.journal
The hledger journal file ""/home/username/src/hledger/chart.journal"" was not found.
Please create it first, eg with "hledger add" or a text editor.
Or, specify an existing journal file with -f or LEDGER_FILE.
```

**Comment by simonmichael** [comment]
I can't reproduce..

**Comment by simonmichael** [comment]
Strange shell environment ?

**Comment by simonmichael** [comment]
I said that because of the strange doubled double quotes in the error message. But actually I see those too if I give a non-existing file path. Seems like a bug in the error message.

**Comment by Xitian9** [comment]
Odd. I'll make sure it's just an issue with my shell and then close.

**Comment by simonmichael** [comment]
Invisible characters in that command line ? Non-standard period character ?

**Comment by Xitian9** [comment]
I'm not sure, but retyping the command it seems to work now. I must have hit some hidden character. I'll debug that error message, but otherwise close this.
