### ISSUE TITLE
Improve the documentation of close/the error message on closing transactions

### ISSUE THREAD

**Issue by Weyaaron** [simonmichael/hledger#1604]
Dear developers of hledger,

first of all, thank you for your effort with this software, its a joy to work with. 

This issue is about a problem that has bugged me for months: Closing my journal file resulted in an error message about missing balances. I attached a small example. 
None of my searches resulted in something substantive, so I asked [reddit.](https://www.reddit.com/r/plaintextaccounting/comments/oerbky/how_do_you_properly_close_your_financial_year_in/)

The answers included some pointers about the dates of the transactions, which helped me solve
my problem. 

However, this issue could be addressed by a more human-friendly error message or a small paragraph in the documentation of close. While I would prefer the former, this is more challenging, while the later is a no-brainer. If this issue is recognized, I might open a PR which adds a paragraph about this issue to the doc. 

Greetings,
Aaron 
[example_issue_close.txt](https://github.com/simonmichael/hledger/files/6796570/example_issue_close.txt)

**Comment by simonmichael** [comment]
Thanks for opening an issue, @Weyaaron.

Summarising: when starting out with the `close` command, it's easy to be tripped up by using it on a journal with future-dated transactions (eg a test journal as in this case). `close` chooses yesterday as the closing date by default, and in this case the closing balance assertions will be wrong.

If it picked the later of yesterday or journal's latest posting date, perhaps that would resolve this ? In this example, it would have picked 7/7 instead of 7/6 and the assertion would have worked.

**Comment by Weyaaron** [comment]
I appreciate the quick response time :)
I agree, this would resolve this as well. However, this solution might break systems currently in use which rely on this behavior. Not quite sure if this is a substantial problem though.

**Comment by simonmichael** [comment]
I don't think people use close often, and I think it might be worth simplifying close's date handling. Current doc:

> By default, the closing transaction is dated yesterday, the balances 
> are calculated as of end of yesterday, and the opening transaction is dated today.
> To close on some other date, use: `hledger close -e OPENINGDATE`.
> Eg, to close/open on the 2018/2019 boundary, use `-e 2019`.
> You can also use -p or `date:PERIOD` (any starting date is ignored).

The following might require more verbose `close` command lines, but it is easier to describe:

> By default, the closing date is the later of today and the journal's end date. 
> You can override this by specifying a report end date with `-e`, `-p` or `date:`. 
> The opening date will be the day after the closing date. 
> Eg, to close/open on the 2020/2021 boundary, use `-e 2020-12-31`.

**Comment by simonmichael** [comment]
The trouble is, we are used to end dates being exclusive. That's why currently to close on 2020-12-31 you would say `-e 2021-01-01` (or `-e 2021`). That is more consistent, and also requires less typing, but I think less intuitive. This is a case where inclusive end dates would be useful.

**Comment by simonmichael** [comment]
So for now perhaps:

> By default, the closing date is the later of today and the journal's end date.
> You can override this by specifying a report end date with `-e` (or `-p` or `date:`).
> Report end dates are exclusive as usual, and begin dates are ignored.
> The opening date is always the next day after the closing date.
> Eg to close on 2020-12-31 and open on 2021-01-01, any of these will work: 
> `-e 2021-01-01`, `-e 2021`, `-p 2020`, `date:2020`.

**Comment by simonmichael** [comment]
Actually "yesterday" works out better, as we had it. I "just" added the logic to use the journal end date (last day) if it's later, and rewrote the docs. #1605

**Comment by simonmichael** [comment]
This is merged in master. New docs: https://hledger.org/dev/hledger.html#close -> https://hledger.org/dev/hledger.html#close-date . I think this resolves it ?

**Comment by Weyaaron** [comment]
This solves my Issue, I really appreciate the thorough response, thank you all for this fantastic software!
