### ISSUE TITLE
Strange ROI reporting

### ISSUE THREAD

**Issue by ohmyohmyohmy** [simonmichael/hledger#1609]
I'm using hledger 1.22-0-g8d237869d, windows-x86_64

```
test.ledger:
2021/01/01 Opening Balance
 Assets:Test 101:Opening  $ 1000
 Assets:Test 102:Opening  $ 1000
 Equity:Opening Balance

2021/03/11 Dividends
 Assets:Test 101:Dividend  $ 101
 Equity:Test 101:Dividend

2021/03/11 Dividends
 Assets:Test 102:Dividend  $ 102
 Equity:Test 102:Dividend

2021/03/11 Deposit
 Assets:Test 101:Deposit  $ 1000
 Assets:Test 102:Deposit  $ 1000
 Assets:Cash

2021/04/22 Deposit
 Assets:Test 101:Deposit  $ 1000
 Assets:Test 102:Deposit  $ 1000
 Assets:Cash

```

When I run queries, I get some funny results:
```
hledger -f test.ledger roi -Y --inv "Assets:Test" --pnl "Equity:Test"
+---++------------+------------++---------------+----------+-------------+-------++-------+-------+
|   ||      Begin |        End || Value (begin) | Cashflow | Value (end) |   PnL ||   IRR |   TWR |
+===++============+============++===============+==========+=============+=======++=======+=======+
| 1 || 2021-01-01 | 2021-12-31 ||             0 |   $ 6000 |      $ 6203 | $ 203 || 4.06% | 6.84% |
+---++------------+------------++---------------+----------+-------------+-------++-------+-------+
Strange, but I guess it's acceptable.
```

```
hledger -f test.ledger roi -Y --inv "Assets:Test 101" --pnl "Equity:Test 101"
+---++------------+------------++---------------+----------+-------------+-------++-------+-------+
|   ||      Begin |        End || Value (begin) | Cashflow | Value (end) |   PnL ||   IRR |   TWR |
+===++============+============++===============+==========+=============+=======++=======+=======+
| 1 || 2021-01-01 | 2021-12-31 ||             0 |   $ 6000 |      $ 6102 | $ 102 || 2.04% | 5.10% |
+---++------------+------------++---------------+----------+-------------+-------++-------+-------+
Unexpected, getting totals of Test 101 AND Test 102, not just Test 101.
PnL of Test 101 has been switched with Test 102
```

```
hledger -f test.ledger roi -Y --inv "Assets:Test 102" --pnl "Equity:Test 102"
+---++------------+------------++---------------+----------+-------------+-------++-------+-------+
|   ||      Begin |        End || Value (begin) | Cashflow | Value (end) |   PnL ||   IRR |   TWR |
+===++============+============++===============+==========+=============+=======++=======+=======+
| 1 || 2021-01-01 | 2021-12-31 ||             0 |   $ 6000 |      $ 6101 | $ 101 || 2.02% | 5.05% |
+---++------------+------------++---------------+----------+-------------+-------++-------+-------+
Unexpected, getting totals of Test 101 AND Test 102, not just Test 102.
PnL of Test 102 has been switched with Test 101
```

```
hledger -f test.ledger roi -Y --inv "Assets:Test 103" --pnl "Equity:Test 103"
+---++------------+------------++---------------+----------+-------------+-------++-------+-------+
|   ||      Begin |        End || Value (begin) | Cashflow | Value (end) |   PnL ||   IRR |   TWR |
+===++============+============++===============+==========+=============+=======++=======+=======+
| 1 || 2021-01-01 | 2021-12-31 ||             0 |   $ 6000 |      $ 6203 | $ 203 || 4.06% | 6.84% |
+---++------------+------------++---------------+----------+-------------+-------++-------+-------+
Shouldn't have worked, but gave me the same result as the first query
```

Am I doing something wrong, or is this a bug?

**Comment by simonmichael** [comment]
Paging @adept, any thoughts ?

**Comment by adept** [comment]
So, keeping in mind that  both `--inv` and `--pnl` are queries, you can gain some insight into what is going on here:

Taking the second example and looking at the `--inv` query, we will see all the **transactions** that match it
```
> hledger -f /tmp/test.ledger print  "Assets:Test 101"                                                                                                         ~
2021-01-01 Opening Balance
    Assets:Test 101:Opening          $ 1000
    Assets:Test 102:Opening          $ 1000
    Equity:Opening Balance

2021-03-11 Dividends
    Assets:Test 101:Dividend           $ 100
    Equity:Test 101:Dividend

2021-03-11 Deposit
    Assets:Test 101:Deposit          $ 1000
    Assets:Test 102:Deposit          $ 1000
    Assets:Cash

2021-04-22 Deposit
    Assets:Test 101:Deposit          $ 1000
    Assets:Test 102:Deposit          $ 1000
    Assets:Cash
```

Quoting from [hledger manual](https://hledger.org/hledger.html#semantics-of---inv-and---pnl) for the `roi` command (with added emphasis):

"Query supplied to --inv has to match all **transactions** that are related to your investment. **Transactions** not matching --inv will be ignored.

In these **transactions**, ROI will consider **postings** that match --inv to be "investment postings" and other postings (not matching --inv) will be sorted into two categories: "cash flow" and "profit and loss", as ROI needs to know which part of the investment value is your contributions and which is due to the return on investment.
...

**All non-investment postings are assumed to be "cash flow"**, unless they match --pnl query. Changes in value of your investment due to "profit and loss" postings will be considered as part of your investment return.
"

Roi operates at transaction level, not posting level. If you rewrite your transactions in a way where separate investments would sit in separate transactions, like this:
```
2021/01/01 Opening Balance
 Assets:Test 101:Opening  $ 1000
 Equity:Opening Balance

2021/01/01 Opening Balance
 Assets:Test 102:Opening  $ 1000
 Equity:Opening Balance

2021/03/11 Dividends
 Assets:Test 101:Dividend  $ 101
 Equity:Test 101:Dividend

2021/03/11 Dividends
 Assets:Test 102:Dividend  $ 102
 Equity:Test 102:Dividend

2021/03/11 Deposit
 Assets:Test 101:Deposit  $ 1000
 Assets:Cash

2021/03/11 Deposit
 Assets:Test 102:Deposit  $ 1000
 Assets:Cash

2021/04/22 Deposit
 Assets:Test 101:Deposit  $ 1000
 Assets:Cash

2021/04/22 Deposit
 Assets:Test 102:Deposit  $ 1000
 Assets:Cash
```

You will get this (keeping in mind that spaces are ticky, so I've changed your queries to avoid dealing with space escaping):
```
hledger -f /tmp/test.ledger roi -Y --inv "Assets:Test.101" --pnl "Equity:Test.101" 
+---++------------+------------++---------------+----------+-------------+-------++-------+--------+
|   ||      Begin |        End || Value (begin) | Cashflow | Value (end) |   PnL ||   IRR |    TWR |
+===++============+============++===============+==========+=============+=======++=======+========+
| 1 || 2021-01-01 | 2021-12-31 ||             0 |   $ 3000 |      $ 3101 | $ 101 || 4.04% | 10.10% |
+---++------------+------------++---------------+----------+-------------+-------++-------+--------+

```

**Comment by ohmyohmyohmy** [comment]
Hi adept,

Thanks for that. A few questions and observations arose from your explanation:

- Wow, I actually didn't realize the distinction existed, and was important - transaction and posting. To me they are identical. Since this is important, perhaps a little explanation about this distinction should be highlighted in the roi section of the manual, and what could go wrong if not followed, because I've tried the same query [hledger -f /tmp/test.ledger roi -Y --inv "Assets:Test.101" --pnl "Equity:Test.101"] on test.ledger unchanged, and it works as expected, even without the suggested changes to the transactions.
- It appears my problem arose with the query and the unseen/unknown difference between"Assets:Test 101" and "Assets:Test.101", abd the effect of the dot. I thought "Assets:Test 101" would work as a valid, strict, regular expression. Where can I find this 'dot usage' in the manual? I also thought putting the account names in quotes to 'shell-escape' them eliminates the necessity to escape the spaces as stated in the manual:

```
Single escaping (shell metacharacters)

In shell command lines, characters significant to your shell - such as spaces, <, >, (, ), |, $ and \ - should
be "shell-escaped" if you want hledger to see them. This is done by enclosing them in single or double
quotes, or by writing a backslash before them. Eg to match an account name containing a space:

$ hledger register 'credit card'

or:

$ hledger register credit\ card
```

Thanks in advance.

**Comment by adept** [comment]
Firstly, I want to apologize - looks my recollection was not 100% correct, should've checked the sources first :) I agree with your observation that with `--inv "Assets:Test.101" --pnl "Equity:Test.101"` even your original file works as expected

We do indeed filter **both** transactions and postings using the supplied query (line 278 of roi.hs), so indeed even your original example works given the right query. I would still suggest separating investments into different transactions because it is quite easy to construct a multi-posting transaction that would have unexpected interpretation.

On 'dot usage': there is nothing special about the dot. A query that does not start with '<word>:' prefix should be interpreted as a regexp account match (https://hledger.org/hledger.html#queries), so I just replaced ' ' with '.' which should match any symbol, but, given your accounts, will match ' '. I did this simply because I don't like to deal with spaces and space escaping in general (not just in hledger accounts).

Looks like without this "Test 101" seem to be interpreted as two queries (Test) and (101). I can not immediately explain why this happens. Roi implementation does calls `parseQuery` on the supplied argument (line 74 of roi.hs), which I would've expected to do the right thing. @simonmichael , it is my turn to return the favour and page you :)

On "Test 103": based on the above, I think this gets interpreted as (Test) and (103), where (103) matches nothing and (Test) matches all your accounts that include Test in the name. If you try ` --inv "Assets:Test.103" --pnl "Equity:Test.103"` instead, you will get:
```
No relevant transactions found. Check your investments query
```

**Comment by ohmyohmyohmy** [comment]
Hi adept,

Ah! I get it now. So what's between the quotes " " after --inv and --pnl is considered a query. Although I can see how this makes sense, it's actually inconsistant with how hledger would work with other commands like 'bal', 'bs', and 'is' where I break up the account names with spaces:

```
hledger -f test.ledger bal "test 101" "cash"
hledger -f test.ledger bs "test 102" "cash"
```

By the way, I think I may have found another bug. Why doesn't this work?

```
(Using single quotes instead of double quotes)
hledger -f test.ledger bal 'test 101' 'cash'
hledger -f test.ledger bs 'test 102' 'cash'
```

Anyway, because of that, I thought what was in between between --inv and --pnl and what came after --pnl were the queries. So, if I wanted two accounts totalled and included in the report, I'd write:

`hledger -f test.ledger roi --inv "Assets:Test 101" "Assets:Test 102" --pnl "equity:test"`

And this should fail, as I have no account literally named "Assets:Test.101 Assets:Test.102"

`hledger -f test.ledger roi --inv "Assets:Test.101 Assets:Test.102" --pnl "equity:test"`

**Comment by simonmichael** [comment]
Thanks @adept.
I turned on all debug output with `--debug=9`. 
This confirmed that the basic command line parsing is working correctly,
but I couldn't see how the roi command was handling its option arguments
(possible addition for its debug output).

> So what's between the quotes " " after --inv and --pnl is considered a query. Although I can see how this makes sense, it's actually inconsistent with how hledger would work with other commands like 'bal', 'bs', and 'is' where I break up the account names and options with spaces:

I think it's ok.
roi's docs say these options' argument is a query. 
balance also takes a query, but in a different way, consuming all command line arguments.
For roi, an extra level of quoting is needed:

    --inv "'Assets:Test 103'"

Quoting with backslash required three of them, which I presume is another explainable case of
https://hledger.org/hledger.html#special-characters :

    --inv "Assets:Test\\\ 103"

Could/should roi handle these arguments in a more intuitive way ? I'm
not sure. Is it useful for them to be a full query, or only to match a
certain account ?

If it stays as is it could call out this issue in the docs: "Note
--investment and --profit-loss's argument is a query, if any query
terms contain spaces you will need an extra level of quoting, eg
--investment="'Assets:Test 1'"

> I think I may have found another bug. Why doesn't this work?

I think single quoted and double quoted command line arguments
containing a fixed string behave identically on all platforms,
please give more detail/a repro if it's still unclear.

Too much work to follow up the rest right now - I can help answer
questions in chat if you need.

**Comment by ohmyohmyohmy** [comment]
Hi @simonmichael,

Thanks for that. That does shed more light on the subject, especially the inception-movie-like quotes within quotes bit. 😆 Had that been in the manual, it would explain a lot, and reduce some head scratching!

With regards to single and double quotes:

```
; newtestprint.ledger

2021-01-01 Opening Balance
    Assets:Test 101:Opening          $ 1001
    Assets:Test 102:Opening          $ 1002
    Assets:Test 103:Opening          $ 1003
    Equity:Opening Balance

2021-01-01 Opening Balance
    Assets:Test.101:Opening          $ 1101
    Assets:Test.102:Opening          $ 1202
    Assets:Test.103:Opening          $ 1303
    Equity:Opening Balance

2021-03-11 Dividends
    Assets:Test 101:Dividend           $ 101
    Equity:Test 101:Dividend


2021-03-11 Dividends
    Assets:Test.101:Dividend           $ 111
    Equity:Test.101:Dividend


2021-03-11 Dividends
    Assets:Test 102:Dividend           $ 102
    Equity:Test 102:Dividend


2021-03-11 Dividends
    Assets:Test.102:Dividend           $ 122
    Equity:Test.102:Dividend


2021-03-11 Dividends
    Assets:Test 103:Dividend           $ 103
    Equity:Test 103:Dividend


2021-03-11 Dividends
    Assets:Test.103:Dividend           $ 133
    Equity:Test.103:Dividend


2021-04-04 Deposit
    Assets:Test 101:Deposit          $ 1000
    Assets:Test 102:Deposit          $ 1000
    Assets:Test 103:Deposit          $ 1000
    Assets:Cash

2021-04-04 Deposit
    Assets:Test.101:Deposit          $ 1000
    Assets:Test.102:Deposit          $ 1000
    Assets:Test.103:Deposit          $ 1000
    Assets:Cash

2021-05-05 Deposit
    Assets:Test 101:Deposit          $ 1000
    Assets:Test 102:Deposit          $ 1000
    Assets:Test 103:Deposit          $ 1000
    Assets:Cash

2021-05-05 Deposit
    Assets:Test.101:Deposit          $ 1000
    Assets:Test.102:Deposit          $ 1000
    Assets:Test.103:Deposit          $ 1000
    Assets:Cash
```
These are are the results with double quotes.
```
hledger -f newtestprint.ledger bal "test 101"
              $ 2000  Assets:Test 101:Deposit
               $ 101  Assets:Test 101:Dividend
              $ 1001  Assets:Test 101:Opening
              $ -101  Equity:Test 101:Dividend
--------------------
              $ 3001
```
```
hledger -f newtestprint.ledger bs "test 101"
Balance Sheet 2021-05-05

                          || 2021-05-05
==========================++============
 Assets                   ||
--------------------------++------------
 Assets:Test 101:Deposit  ||     $ 2000
 Assets:Test 101:Dividend ||      $ 101
 Assets:Test 101:Opening  ||     $ 1001
--------------------------++------------
                          ||     $ 3102
==========================++============
 Liabilities              ||
--------------------------++------------
--------------------------++------------
                          ||
==========================++============
 Net:                     ||     $ 3102
```
And these are the results with single quotes.
```
hledger -f newtestprint.ledger bal 'test 101'
--------------------
                   0
```
```
hledger -f newtestprint.ledger bs 'test 101'
Balance Sheet 2021-05-05

             || 2021-05-05
=============++============
 Assets      ||
-------------++------------
-------------++------------
             ||
=============++============
 Liabilities ||
-------------++------------
-------------++------------
             ||
=============++============
 Net:        ||
```
I'm using hledger 1.22-0-g8d237869d, windows-x86_64

**Comment by simonmichael** [comment]
Look at that! I stand corrected! Maybe you can narrow it down to whichever $SHELL or windows shell environment you're using. Here's the expected result, from a mac/iterm2/bash shell:
```
$ hledger bal "test 101"
              $ 2000  Assets:Test 101:Deposit
               $ 101  Assets:Test 101:Dividend
              $ 1001  Assets:Test 101:Opening
              $ -101  Equity:Test 101:Dividend
--------------------
              $ 3001  
$ hledger bal 'test 101'
              $ 2000  Assets:Test 101:Deposit
               $ 101  Assets:Test 101:Dividend
              $ 1001  Assets:Test 101:Opening
              $ -101  Equity:Test 101:Dividend
--------------------
              $ 3001  
```

**Comment by ohmyohmyohmy** [comment]
I just use the windows command line, 'cmd'

**Comment by simonmichael** [comment]
https://stackoverflow.com/a/51090074/84401 : *CMD doesn't treat single quotes as anything but a regular character. It's not a pair/group like double quotes.*  TIL!  We may need to tweak some examples in docs.

**Comment by ohmyohmyohmy** [comment]
Well that's a TIL moment for me too! 😆 That'll probably just require a small section that says:
```
The Windows command line 'cmd' doesn't treat single quotes as anything but a regular character. When using 'cmd', you should only use double quotes exclusively (Except for roi queries that use quotes within quotes).
```
But anyway, thanks, y'all for the help. I now have enough information to get the expected results I want from hledger. 😄

**Comment by simonmichael** [comment]
Still curious: Is it useful for these to be a full query, or they really just need to match one account, or multiple accounts ?

**Comment by adept** [comment]
Well, I my particular use case I would say "yes", cause I use `hledger open` and `hledger close` to handle the fiscal years AND use `hledger roi` to compute ROI over periods larger than year. This necessitates `not:acct:equity:open-close` for both `--inv` and `--pnl` , plus I have a script to compute ROI in which `--pnl` just lists all PnL accounts at once, so then you can specify investment you want in `--inv` and not think about getting `--pnl` just right.

I am pretty sure that both of these cases could be made to work with `--inv/--pnl` just being an account -- with some journal pre-filtering, account rewrites, some sed/awk etc, but it will be a major pain in the back. 

Re. multiple accounts -- if multiple accounts are separated by space, then I am not sure how this will be different from the current situation.

**Comment by simonmichael** [comment]
Fair enough, just wondering if this was a case where we were making it less intuitive by providing too much power. It's well documented now in any case.
