### ISSUE TITLE
hledger-web release contains files without source

### ISSUE THREAD

**Issue by nomeata** [simonmichael/hledger#161]
As reported at http://bugs.debian.org/736595 the hledger-web release contains these files without their corresponding source code

```
static/excanvas.min.js
static/jquery.flot.js
static/jquery.js
static/jquery.url.js
static/select2.min.js
````
This causes problems for downstream distributions.

Could you please make a release of hledger-web that includes the corresponding source (i.e. non-minified, non-packed) files?

Bonus points for ensuring that the minified files are really derived from the source files, for example by adding a small Makefile and building them yourself, which would also serve as documentation about the tool used to create these files.

Thanks,
Joachim

**Comment by nomeata** [comment]
I guess this needs to be re-opened: The jquery source got lost in or before 0.24.1:
http://hdiff.luite.com/cgit/hledger-web/diff/?id=0.24.1&id2=0.23.3

You can work around the issue by using the js-jquery and js-flot packages from Hackage.

**Comment by simonmichael** [comment]
Thanks.. I think I just need to re-add the unminified jquery.js.

**Comment by simonmichael** [comment]
I think this is resolved.
