### ISSUE TITLE
Add/document some sort of balancing mechanism for sub-accounts

### ISSUE THREAD

**Issue by Weyaaron** [simonmichael/hledger#1612]
Dear developers,

is there a way to balance sub-accounts with their parent? This would greatly decrease clutter in my data, since I use one account per month, but these accounts clutter future years when included by the closing transactions. 

My preferred solution would take two account-names as arguments and print a transaction such that one of them is zero, with a flag for recursion down into the children. An alternative might be to just provide one account as an argument and all its children will be balanced by the printed transactions. 

If there is an established way of archiving my goal, let me know, I did some searching and found nothing substantial.
Improving the docs might help to locate this solution more easily. 

Thank you for your time and dedication,
Aaron

**Comment by simonmichael** [comment]
This requires some conversation.. would you like to join the irc or matrix chat where we can clarify the problem and brainstorm some options ?

**Comment by Weyaaron** [comment]
This has been discussed via matrix, a solution is readily available with the use of balance assertions, as documented (here)[https://hledger.org/hledger.html#balance-assertions]
Thanks for the amazing work :)

**Comment by Weyaaron** [comment]
Dear community,
unfortunately the knowledge has been lost to me. And since I did not find adequate documentation, I would like to document the proper solution in this issue once and for all. 
My End-Goal is to add a transaction that balances all the sub-accounts with their parent:
```
2020-12-30 Close Expenses
    expenses:stuff                                                         = 0.00
    expenses:even_more_stuff                                      = 0.00
    expenses
```
As far as I can tell, there is no command that prints an entry such as this. As far as I can remember, I did this manually last time around. 
This seems like a common use-case, so a elegant solution "should exist".
I appreciate any tipps/effort.
Greetings,
Aaron

**Comment by simonmichael** [comment]
Your entry works for me:
```
2020-12-01
    expenses                       1
    expenses:stuff                 2
    expenses:even_more_stuff       3
    assets

2020-12-30 Close Expenses
    expenses:stuff                               = 0.00
    expenses:even_more_stuff                     = 0.00
    expenses
```
```
$ hledger print -x
2020-12-01
    expenses                               1
    expenses:stuff                         2
    expenses:even_more_stuff               3
    assets                                -6

2020-12-30 Close Expenses
    expenses:stuff                     -2.00 = 0.00
    expenses:even_more_stuff           -3.00 = 0.00
    expenses                               5

$ hledger bal
                  -6  assets
                   6  expenses
--------------------
                   0  
```

**Comment by Weyaaron** [comment]
Exactly, this entry solves my issue, but I am looking for a command that generates such an entry.
Assuming I start with the following file: 
```
2021-01-05 Groceries
    assets:2021           -10.00
    expenses:food        10.00
```
Is there a command such that 
```
$ hledger command
 ```
prints exactly
```
2021-01-06 Balance Assets 
    assets:2021            = 0
   assets 

2021-01-06 Balance Expensens
    expenses:food            = 0
    expenses
```

This would be usefull for executing 
```$ hledger command >> hledgerfile.journal```

**Comment by simonmichael** [comment]
No, but the `close` command can do essentially this:
```
$ hledger close --close
2021-12-22 closing balances
    assets:2021                               10.00 = 0.00
    expenses:food                            -10.00 = 0.00
    equity:opening/closing balances

```
Please see https://hledger.org/hledger.html#close for full details and examples.

**Comment by Weyaaron** [comment]
Oh wow, this was obvious, once again thank you for the quick help!

**Comment by simonmichael** [comment]
Great! Glad it helped.
