### ISSUE TITLE
Problems with hledger-ui and diacritics

### ISSUE THREAD

**Issue by edkedk99** [simonmichael/hledger#1652]
version: hledger-ui 1.19.1
platform: Ubuntu 21.04

A strange error happens when using hledger-ui filtering by pattern as the follow example:

## Example
**demo.jounal:**
``` 
2021-08-13 João Silva | Outros
    Asset:Bank                                   300
    Income
```

## Successful command

Filter by payee only with first name with diacritic:
`$ hledger-ui -f demo.journal payee:'João'`

## Failed command

Filter by payee with full name:
`$ hledger-ui -f demo.journal payee:'João Silva'`

## Result
On the header, hledger-ui shows :
*account balances matching "payee:Jo\227o Silva"*

It should show:
*account balances matching "payee:João Silva"*
 
## Conclusion
If hledger-ui receive a pattern parameter with diacritic, it works only if it is only one word. If the pattern has more than one word separated by space, the letter with diacritic is substituted by its ASCII code and the desired transactions doesn't show up. The question is why hledger-ui recognize the diacritic if the pattern contains only one word?

I have also tested with many letters and I get the same error
Hledger regular command works fine when I filter by one or two words, so the error is valid only for hledger-ui. 

I would appreciate if someone could try to reproduce this error and comment the result.

Thank you

**Comment by edkedk99** [comment]
Installed new version 488cf70 and the problem is solved.

Sorry for the bug report

**Comment by simonmichael** [comment]
Sweet! Thanks for reporting anyway. What version was showing this problem ?

**Comment by simonmichael** [comment]
Oops, you said, never mind.
