### ISSUE TITLE
reg: report intervals with custom start dates are hard to read

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1655]
When showing https://hledger.org/dev/hledger.html#intervals-with-custom-start-date , in general `register` must display both the start and end date for each period, but it doesn't allow enough width in the first column. `aregister` might have the same problem.

**Comment by Xitian9** [comment]
aregister doesn't seem to have the same problem, but does have another (possibly related) problem. I'll open a new issue for that.

**Comment by Xitian9** [comment]
This problem arose when we changed the display format from `2021/01/01-2021/02/02` to `2021-01-01..2021-02-02`. This is one character longer, and so our spacing became incorrect.

I have a fix coming which tightens up the date spacing in register reports in general.
