### ISSUE TITLE
ROI and external price files

### ISSUE THREAD

**Issue by melbv** [simonmichael/hledger#1660]
Hi Simon

I am just starting to work with hledger which works great for me thus far. 
I have a quick issue with the roi command. After the below declaration:

```
hledger roi -f personal.journal --investment assets:Investments -Q --cost --value=then,"$" --infer-market-price --pnl "unrealized"
```

I get an error message:

> hledger: Amounts could not be converted to a single cost basis

I am using a separate .prices file for ease of data management which works a charm with commands like 'bs' or 'is' but does not seem to work with 'roi'.
My declaration of the price file is:

> include personal.prices

Is this a known issue or is there a declaration I am not instructing 'roi' properly?
Many thanks in advance
M

My config below:
> hledger 1.22.2, mac-x86_64

PS: also added the issue on 'hledger-site', not realising there are 2 different directories - my apologies for that

**Comment by simonmichael** [comment]
Thanks for the report @melbv. A `roi` user may show up soon, but are you saying that having prices in a separate file triggers the error ?

**Comment by chvp** [comment]
I use `roi` with an included prices journal as well, so I doubt that would be the problem. Can you try removing the `--cost` from your invocation? It does not make much sense to combine it with `--value=then,$`.

**Comment by adept** [comment]
It might also help to run `hledger print` with exactly the same arguments (modulo arguments specific to `roi`) to see what kind of transactions/postings `roi` will receive. 

PS I also use `include`d price, and they work fine for me

**Comment by melbv** [comment]
Thanks for all your suggestions!
I have tried a few permutations of `roi` (including without `--cost`) which does not work. `print` with the same arguments does work however and prints all transactions. I am also using self-declared 'commodities' for all prices (using the 'cleaner declaration of transactions with the `equity:conversion` account. Not sure if this could be the source of the issue. 
Any further suggestion is welcome!

**Comment by melbv** [comment]
PS: the command seems to be working for a single investment but not for a full account with different investments. Not sure if this is an expected behaviour of the `roi` report

**Comment by adept** [comment]
A reproducible example will certainly help here. Account (or accounts) with different "investments" should not be a problem, provided that cash flows "in" and "out" could be identified.

**Comment by melbv** [comment]
In preparing my answer to you, @adept, i found out that i was missing an initial price declaration in my .prices folder that fixes the bug. I assumed that the implicit transaction price at purchase of each asset would be recorded by the `roi` function but is not as a matter of fact. I needed to input a price for each asset at time of purchase (or at a date just before for that matter).
Thanks for the help on this one

**Comment by Xitian9** [comment]
If you want it to automatically infer prices, you can pass it the `--infer-market-price` flag. I'm not sure if that works with `roi`, but you can try it.

**Comment by adept** [comment]
Based on a couple of quick experiments, it should work

**Comment by melbv** [comment]
It is now working fine with an explicit price declaration prior to investment date (and using `--infer-market-price`).
Thanks for following up on this.
On my side, i'll be on to my next topic, and implementing tax parameters across a few different currency areas...
