### ISSUE TITLE
Long command line options require an = to take arguments

### ISSUE THREAD

**Issue by Xitian9** [simonmichael/hledger#1666]
I was bitten by this trying to test the `--forecast=PERIODEXPR` functionality. I kept trying to type `--forecast PERIODEXPR` and was confused why it wasn't working.

This is different to how long options are usually handled, where the `=` is optional. We should at least document this better, but the usage is so ubiquitous I suspect it will keep causing confusion until it's changed to more standard behaviour. Is there a technical limitation to implementing this now?

**Comment by simonmichael** [comment]
Yes it's unfortunate. As far as I remember it's a technical difficulty, or I wouldn't have left it this way. It's mentioned in various places, like https://hledger.org/hledger.html#forecasting-with-periodic-transactions, but not in https://hledger.org/hledger.html#options. I'll add more details if they come back to me.

**Comment by simonmichael** [comment]
Here's the discussion: https://github.com/simonmichael/hledger/issues/149

**Comment by simonmichael** [comment]
Summary: it was a cmdargs limitation, I suspect it still is, Neil might be open to a PR changing the behaviour, the cmdargs code was "not that easy" when I looked at it.

**Comment by Xitian9** [comment]
I'll close this as a duplicate of #149.
