### ISSUE TITLE
disable number styling in SQL output ?

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1684]
It was reported in this Hacker News thread (https://news.ycombinator.com/item?id=28421267) that our SQL output can show styled numbers, eg with thousands separators, and suggested that this is never appropriate. This sounds right. We should investigate the effect of commodity styles on numbers in SQL and JSON output - perhaps it's true to say that these numbers should always be in "vanilla" ISO format, ie no digit group separators and period as decimal mark ?

I think CSV output is a special case, number styling is sometimes desired there.

**Comment by Xitian9** [comment]
Isn't this already done for JSON output? Amounts are currently stored like this, so the styling is beside the number, rather than within. The actual number is stored in `aquantity`.

```
        "pamount": [
          {
            "acommodity": "USD",
            "aprice": null,
            "aquantity": {
              "decimalMantissa": 2183,
              "decimalPlaces": 2,
              "floatingPoint": 21.83
            },
            "astyle": {
              "ascommodityside": "R",
              "ascommodityspaced": true,
              "asdecimalpoint": ".",
              "asdigitgroups": null,
              "asprecision": 2
            }
          }
```

**Comment by Xitian9** [comment]
For SQL output, do we just use `.` as a decimal point, and round to the precision in style?

**Comment by Xitian9** [comment]
Actually, I think the original comment is not correct. We seem to strip digit groupings and commodities from SQL output. Perhaps we need to change the decimal point to `.`, but aside from that I think we're good.

**Comment by Xitian9** [comment]
Digit groupings were removed from csv and sql output here: https://github.com/simonmichael/hledger/commit/802378999fe12d600c04fd7a7df511f918ceb1b0

**Comment by simonmichael** [comment]
Summary: 

- we made numbers in SQL output be completely unstyled, always using decimal period
- we left numbers in CSV output alone; currently they are mostly-unstyled for `print` (the decimal mark is styled), and fully styled for other commands. We proposed changing this on the mail list. https://groups.google.com/g/hledger/c/SBVVFZwzA_Q

**Comment by simonmichael** [comment]
Just for the record, mail list consensus seems to be in favour of consistently mostly-not-styling amounts in CSV output.
