### ISSUE TITLE
bal --no-elide (and -E, and hledger-ui zero display ?) not working as I expected

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1688]
I'm not sure if there's another explanation, but I'm puzzled enough to note it as a possible bug:

```
$ hledger-1.18 -f avodonosov.journal  bal revenues -N -E --no-elide
           200.0 BYN  revenues
           200.0 BYN    forex gain
           200.0 BYN      unrealised
$ hledger -f avodonosov.journal  bal revenues -N -E --no-elide
           200.0 BYN  revenues:forex gain:unrealised
```

With any hledger version >1.18, I'm unable to show the two zero-balance parent accounts here. I expected that -E, certainly when combined with --no-elide, would show them and their 0 balance as separate line items.

**Comment by simonmichael** [comment]
Repro:
```
1/1
    (a)        1
    (a:b)      1

1/2
    (a)       -1
    (a:b)     -1
```
```
$ hledger-1.18 -f b.j bal -E --no-elide
                   0  a
                   0    b
--------------------
                   0
$ hledger-1.19 -f b.j bal -E --no-elide
                   0  a:b
--------------------
                   0
```
It seems --no-elide's original function broke (a long time ago!). Perhaps with that fixed things will make more sense.

**Comment by Xitian9** [comment]
I think between 1.18 and 1.19 we switched from --tree as default to --flat as default. Can you check if `hledger-1.19 -f b.j bal -E --no-elide --tree` does what you want?

**Comment by simonmichael** [comment]
@Xitian9, ah good point. Yes that works; you remind me that `--no-elide` does that thing only in tree mode.

Maybe my problem is with `-E` ? Or I could still be confused. See:
```
$ hledger-1.18 -f b.j bal --flat
--------------------
                   0
$ hledger-1.18 -f b.j bal --flat -E
                   0  a
                   0  a:b
--------------------
                   0
$ hledger-1.19 -f b.j bal --flat
--------------------
                   0
$ hledger-1.19 -f b.j bal --flat -E
                   0  a:b
--------------------
                   0
```
All in list mode here. I expected the -E flag to reveal both the a and a:b accounts.

**Comment by Xitian9** [comment]
Indeed, it looks like `-E` will only show empty leaves, and not empty branches. This is probably reasonable behaviour for tree mode, but not for flat mode. Should I update this and add some new tests?

https://github.com/simonmichael/hledger/blob/4cb631c0f2de99a609bfa6c25b0c3de1bd07bc71/hledger-lib/Hledger/Reports/MultiBalanceReport.hs#L410-L414

**Comment by simonmichael** [comment]
That would be great, thanks.
