### ISSUE TITLE
hledger 1.23 release on Github missing some assets

### ISSUE THREAD

**Issue by Flimm** [simonmichael/hledger#1717]
The [1.23 release on Github](https://github.com/simonmichael/hledger/releases/tag/1.23) only includes these two assets:

- Source code (zip)
- Source code (tar.gz)

Usually, the Github releases include three more assets: the Linux, macOS and Windows assets.

Some of the download links in the Download page are broken because of it. For example, the Linux downloads. https://hledger.org/download.html

**Comment by simonmichael** [comment]
Thanks for reporting. I made the release before all CI binaries were in place; I probably will wait for them in future. The three main binaries are now uploaded. (The 32 bit linux takes many hours and I'll probably defer it till 1.23.1.)

**Comment by simonmichael** [comment]
(And I have given the 32 bit binary a separate badge on the download page, to show more accurate status.)

**Comment by adept** [comment]
I've downloaded hledger-linux-static-x64.zip from 1.23 release page and it seems corrupt.

```
% md5sum hledger-linux-static-x64.zip
fbd6c137416b9af080b1a87938de1160  hledger-linux-static-x64.zip

% file hledger-linux-static-x64.zip
hledger-linux-static-x64.zip: Zip archive data, at least v2.0 to extract

% unzip -t hledger-linux-static-x64.zip
Archive:  hledger-linux-static-x64.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of hledger-linux-static-x64.zip or
        hledger-linux-static-x64.zip.zip, and cannot find hledger-linux-static-x64.zip.ZIP, period.

```

**Comment by simonmichael** [comment]
Thanks for the report! I have re-uploaded over a better connection.

**Comment by adept** [comment]
Seems fixed!
