### ISSUE TITLE
Does not obey LEDGER_FILE environment variable

### ISSUE THREAD

**Issue by dbp** [simonmichael/hledger#172]
Building the most recent version from hackage, I see:

```
$ echo $LEDGER_FILE
/home/dbp/financial/ledger.journal
$ hledger add
Adding transactions to journal file /home/dbp/.hledger.journal
...
```

Which conflicts with what is in the MANUAL (https://github.com/simonmichael/hledger/blob/master/doc/MANUAL.md#basic-usage).

**Comment by kodonaut** [comment]
> For the record: LEDGER_FILE should be an environment variable, not a shell variable. More on this at http://hledger.org/manual.html#troubleshooting -> "I set a custom LEDGER_FILE, but hledger is still using the default file".

It doesn't work in the fish shell. I just don’t understand why hledger can’t behave like all the other Unix tools... This discouraged me right from the start. If I can’t use an environment variable for configuration, it feels more like a tool from another world. Sorry, is it really such a big problem to behave in a standard way?

**Comment by simonmichael** [comment]
Hi @kodonaut. I saw a comment from you about environment variable handling - now deleted, so maybe you resolved it ? But your downvote remains, so I'm following up.
