### ISSUE TITLE
aregister ignores secondary date

### ISSUE THREAD

**Issue by LaurenzWiskott2** [simonmichael/hledger#1731]
Given the file date2.ledger

```
2021-01-01 A
    all:account1                                                          100.00 EUR ; date2:2020-02-01
    all:account2
```

I get the results (with hledger 1.23 5895a46 linux-x86_64 on Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux):

```
linux> hledger -f date2.ledger reg --date2 account1
2020-02-01 A
all:account1                        100.00 EUR    100.00 EUR

linux> hledger -f date2.ledger areg --date2 account1
Transactions in all:account1 and subaccounts:
2021-01-01 A
al:account2                         100.00 EUR    100.00 EUR
```
Why does areg not use date2? Looks like an inconsistency to me.

Simon Michael wrote me:

---
> I'd guess it's because areg reports transactions, while reg reports postings. That sounds ok to me.
> 
> The situation is unclear though:
> 
> 1. https://hledger.org/hledger.html#aregister says "Each aregister line item shows: • the transaction's date (or the relevant posting's date if different, see below)"
> 
> 2. https://hledger.org/hledger.html#aregister-and-custom-posting-dates says "Transactions whose date is outside the report period can still be shown, if they have a posting to this account dated inside the
> report period. (And in this case it's the posting date that is shown.)"
> 
> 3. The aregister command contains this comment: "TODO: need to also pass the queries so we can choose which date to render - move them into the report ?"
> 
> I'm not seeing the behaviour described by 2. Even if I declare the secondary date on the transaction rather than the posting, --date2 doesn't display it or match on it.
> 
> So I'd welcome a bug report or PR, changing either the docs or the behaviour, for further testing. There may be some deeper implementation/design/usability reasons, but I don't remember them.

---

I would argue that areg should really respect the date2: tag.

Firstly, because that is what the user intuitively expects.  The normal user is not very
sensitive to the difference between transaction and posting.

Secondly, because it is really useful, in my view, to have this date2 option, in
particular since "As a quick rule of thumb, use aregister for reconciling real-world
asset/liability accounts and register for reviewing detailed revenues/expenses." as is
written in the hledger manual.  For reconciling with the real-world accounts the postings
should be dated with the date used in the account.  But these latter dates usually differ
between postings of the same transaction, so one should use the posting dates and not the
transaction dates.  Looks quite obvious to me.

**Comment by simonmichael** [comment]
Thanks for the report and issue.

I'm sympathetic with your first argument, even though the difference between transaction and posting is kind of important for some reports (eg it's what differentiates reg and areg). I don't understand the second argument; it feels like a number of things are being mixed. I think we need to figure out in detail what "that" more intuitive behaviour is, in detail. What changes should be explored for display, querying, docs, etc. in possible data scenarios: a secondary transaction date, a secondary posting date, multiple different secondary posting dates, etc.

**Comment by simonmichael** [comment]
Scenario 2 (yours):
```
2021-01-01  txn with a posting with a secondary date (specified in two equivalent ways)
  (a)   1      ; date2:2021-02-02,   [=2021-02-02]
```
$ hledger areg a --date2   # should show the transaction with the posting's february date ? But what about..

Scenario 2.5:
```
2021-01-01  txn with a posting with a different (primary) date
  (a)   1      ; date:2021-02-02
```
$ hledger areg a   # would you show the transaction with the posting's date ? 

And whether primary or secondary, what about when there are multiple posting dates ?

Scenario 3:
```
2021-01-01  txn with multiple posting secondary dates
  (a)   1      ; date2:2021-02-02
  (b)   1      ; date2:2021-03-03
```
$ hledger areg a --date2   # shows what ?

We have not considered queries and the behaviour/justification in https://hledger.org/hledger.html#aregister . 

This gets complex, as it *always* does with the secondary date feature. Before (a) spending lots of time on it and (b) risking regressions and disruption to existing reports, we should have a good understanding of any practical problems the current behaviour is causing, and any alternate solutions.

**Comment by LaurenzWiskott2** [comment]
OK, what is my second argument?

I see two different perspectives here. 
1) If I want to have a general overview over my finances, the exact dates of the postings don't matter so much, but it is important that the sum over all accounts is zero at all times, i.e. all postings of a transaction should have the same date, because otherwise one gets meaningless jumps in the assets or so that would be caused by money leaving one account on one day and arriving at another account two days later. If one had different days for the two postings, the money would disappear for two days, even though you own it. Thus, in this case I need one date per transaction.
2) If I want to check my hledger file against the real bank account, the exact dates of the postings matter, so that they are in the correct order given also on the bank statement, but it is not important that the sum over all accounts is zero at all times. Thus, in this case I need one date per posting, possibly inherited from the transaction date. And since 'areg' is meant exactly for this perspective, as far as I understand, it is a pity that it ignores per posting dates.

**Comment by Xitian9** [comment]
I don't have any deep insight into this issue, but whenever I'm tempted to have posting dates or secondary dates I almost always decide it's better to have two separate transactions with some sort of `accounts receivable` or `accounts payable` account holding the balance in the interim.

**Comment by LaurenzWiskott2** [comment]
> I don't have any deep insight into this issue, but whenever I'm tempted to have posting dates or secondary dates I almost always decide it's better to have two separate transactions with some sort of `accounts receivable` or `accounts payable` account holding the balance in the interim.

I think, then you can easily get strange jumps in an asset, because money disappears temporarily in an intermediate account.

**Comment by simonmichael** [comment]
Xitian9's method is the one that avoids strange jumps - posting dates are what cause them. (Money is temporarily in limbo, not tracked in any account.)

**Comment by LaurenzWiskott2** [comment]
> reg is for viewing postings. It shows one line per posting, so it can easily show posting dates.
> 
> areg is for viewing transactions. It shows one line per transaction, so it could only show at most one posting date. But there can be more than one, in which case choosing which one to show is problematic.

Oh, I got it the other way around. Initially I used 'reg' to check against an account statement, but I found it anoying that I would see several postings of a single transaction, while on the account statement I would only see the one line that matters for the account. Therefore I started using 'areg' because that combines the transaction into one line, which appeared to me more like what I wanted. I guess, I have not fully understood how to use 'reg'. I will look into this more.

Thanks for the clarification.

**Comment by LaurenzWiskott2** [comment]
> Xitian9's method is the one that avoids strange jumps - posting dates are what cause them. (Because money is temporarily travelling through time without being tracked in an account.)

Yes, with Xitian9's method the money is temporarily in some extra account rather than in limbo. But this method only works if one is careful about the naming conventions. Otherwise it might be overlooked in relevant queries. E.g. I have `account:work` and `account:private` and transfer money from one account to the other via an account named `transition` that takes a few days. If I then request 'areg account' the money will disappear for a few days, because `transition` is not included. This is the kind of jumps I mean. This is a simple case. What is a principled naming convention to avoid something like this?

Xitian9, maybe you could give an example of your naming convention that makes sure that the money still appears in your regular queries.

**Comment by simonmichael** [comment]
Exactly, that's the point of areg, to show a higher level transaction-oriented view. In general it can't show quite as much detail as reg (such as individual posting dates). 

I agree with the argument that if areg is advertised as being the best one for reconciling, ideally you'd like it to show accurate bank clearing dates. I have used it for this for years, why haven't I had a problem ? I think because (a) I usually use the bank clearing date as the transaction date (downloaded bank transactions) and (b) the cases where I record a transaction manually and the bank clearing date is different, are rare and don't matter, reconciling is still easy. 

Though, at times of confusion I do add a more accurate date to a bank posting, and then I do see the more accurate date in hledger-ui's register. Which should be equivalent to areg AFAIK. So I'm not quite clear areg's behaviour with posting dates, I'd have to test more when at computer.

**Comment by Xitian9** [comment]
```
2021-10-10  Transfer money to my super-secret account, carefully documented for transparency
  assets:mybank:chequing    -10 dollarbucks
  assets:transfer            10 dollarbucks

2021-10-12  Money arrived!
  assets:secretbank          10 dollarbucks
  assets:transfer           -10 dollarbucks
```

**Comment by simonmichael** [comment]
This seems fixed; matching with `areg date2:...` seems to work too.
