### ISSUE TITLE
cashflow, incomestatement: "more..." in new version of hledger

### ISSUE THREAD

**Issue by PSLLSP** [simonmichael/hledger#1739]
I attach simple journal for a game, where player uses several commodities, he pays membership in USD and he earns GOLD, GEMS and STONES in the game. It is just a game to demonstrate some issue in the new hledger.

hledger 1.2, I like that I can see all details in "is" and "cf" reports:

```
$ hledger --version
1.2

$ hledger is
...
Total:
--------------------
          -1000 GEMS
           -643 GOLD
         -100 STONES
              10 USD
```

```
$ hledger --version
hledger 47b5b6b, linux-x86_64

$ hledger is
...
==========================++=================================
 Net:                     ||   1000 GEMS, 643 GOLD, 2 more.. 
```

The report with "more.." trick could be useful but I would like to have a switch to expand the report to see all details in similar way like old hledger reported. The same problem with "is", "bs", "bse" and "cf" report.
[demo4.txt](https://github.com/simonmichael/hledger/files/7405071/demo4.txt)

**Comment by simonmichael** [comment]
I think we can close this ?

**Comment by PSLLSP** [comment]
I think this can be closed. I wish the option `--commodity-column` would be the default, like it was in the old hledger. hledger cannot guess correctly what to show (what is important) and what to hide (more..).

**Comment by simonmichael** [comment]
`--commodity-column` is brand new behaviour; I think you mean `--no-elide`. I tend to agree with you, and others might too. The default eliding behaviour was added for a good reason, but I think it probably causes more annoyance than it's worth.

**Comment by Xitian9** [comment]
Add me to the agreeing pile. I would actually go further and say that default behaviour should be multi-line display with one commodity on each line (like current `--commodity-column`, but without commodities necessarily aligned).

**Comment by simonmichael** [comment]
@adept, I think you were in favour of the default eliding at the time - any thoughts on the above ?

**Comment by Xitian9** [comment]
What do you think of this as a default for multicommodity reports?

```
                  ||       2012        2013       2014 
==================++===================================
 Assets:US:ETrade ||  12.00 GEA   70.00 GLD  14.00 GEA
 Assets:US:ETrade || 106.00 VHT  18.00 ITOT   1.00 USD
 ```

I'm not even sure whether it's worthwhile to have the single-line behaviour (with or without eliding), but if we wanted to maintain that as an option perhaps:
```
--commodity=singleline (current default)
--commodity=multiline (above proposed behaviour, and new default)
--commodity=column (current --commodity-column behaviour)
```

**Comment by simonmichael** [comment]
I would be interested to try that style for a while.

Bikeshedding:

I think we'd need to support the single-line behaviour at least for a while, for preserving/comparing with old reports. 
But the non-eliding or the eliding variant ? By the same argument we should keep both, though personally I'd be fine with dropping the eliding one.

--commodity sounds quite generic and valuable. It must be typed out in full since it overlaps --commodity-style. Possibly it would be a good replacement for --commodity-style. Is there something else we could use here ? --show-commodities ?

**Comment by Xitian9** [comment]
I have no strong opinion, but dropping the single line eliding variant would rid hledger of a pet peeve of mine: that `--no-elide` does two separate things unrelated to each other.

Maybe it could be `--multicommodity` instead? That would avoid the conflict with `--commodity-style`.

**Comment by simonmichael** [comment]
We now show all amounts unelided by default again, as in hledger 1.18. @PSLLSP, you were the last straw. :) New formatting options available in master: https://hledger.org/dev/hledger.html#commodity-layout
