### ISSUE TITLE
timedot: add payee/description and trailing comment/tags

### ISSUE THREAD

**Issue by linuxcaffe** [simonmichael/hledger#1754]
The most awesome timedot would be even awesomer with a description (payee field). 
Currently a timedot entry carries no description, but can handle a trailing comment. 

`<acct:sub:sub><spaces><qtty><spaces><;><comment>`

This enhancement would use the comment as description.

**Comment by linuxcaffe** [comment]
Closed in favour of #1220 https://github.com/simonmichael/hledger/issues/1220#issuecomment-968392952

**Comment by simonmichael** [comment]
Related to #1220 (comments in timeclock format). Let's keep this one open for timedot specifically.

**Comment by simonmichael** [comment]
Following up on djp's [timedot comment](https://github.com/simonmichael/hledger/issues/1220#issuecomment-968392952) there: 

- [timedot format](https://hledger.org/hledger.html#timedot-format) supports descriptions, written after the date
- You can add a `; comment` and tags there too, but it's treated as part of the description. Instead we should parse text after semicolon as a comment and tags, as in journal format
- We should do the same for `; comment` on a time dots line, where currently it is ignored.

**Comment by linuxcaffe** [comment]
I'm confused. "timedot supports descriptions".. how? I get an error putting anything after the date. I often put a comment like `;Friday` on the line following the date, but.. 
Does that description relate to the day?  Not to each timedot event, right? When I review my ledger combining the timedot and timeclock, using hledger-ui, for example, entries from the timeclock have descriptions, those from timedot do not.
I DO agree that the trailing `<spaces>;comment :tags:` would be dandy..

**Comment by simonmichael** [comment]
Eg:
```
* 2021-11-14 Sun
fos.hledger              .... .... .
```
```
$ hledger -f a.timedot print desc:sun
2021-11-14 * Sun
    (fos.hledger)            2.25
```

**Comment by simonmichael** [comment]
(It works for me at least back to hledger 1.17..)

**Comment by linuxcaffe** [comment]
Oh that's cool on the date (emacsism?) but I'm after a description on the entry
```
      (fos.hledger)        2.25       more dumb suggestions in irc
```

**Comment by simonmichael** [comment]
Yes, in that position I propose we should support comments  (`; comment maybe with a tag:`). There's no room for a posting description in our data model.

**Comment by simonmichael** [comment]
Well.. I'm getting confused, I thought the date creates a transaction and each dot line is a posting within it. Actually, each dot line is a separate transaction. (Is that for the best ? I'm not sure.)

**Comment by linuxcaffe** [comment]
yes, it's (nearly) perfect!

**Comment by linuxcaffe** [comment]
timedot entries being a one-liner, with an inherited date, is my favorite part of it, but it only has a date, an account and an amount, no description (or comment or tag). I suspect that some of the timedot behaviors you are seeing (Simon) is emacs magic, and not of the leading-* features described work in my editor (vi) and that's ok (for now) . Have another look at the mockup above, and I hope you'll agree that it might be the most concise, most hledgerish way to cram the full data set into a single line.

**Comment by simonmichael** [comment]
@linuxcaffe and I discussed this (cf today's #hledger chat log) and made some decisions. We'd like to get timedot format enhanced along these lines:
```
2021/11/12 blah
sleep                7
job:store            8.5   cleaned, set up xmas decorations
job:mary:reno        ...   * (21024) bathroom drain repair, sink didn't fit ; plumbing:, invoice:
   ; Mary suggests retrofitting the old one, scrapyard:
ent:reading          .... .   Kurt Vonnegut - Cat's Cradle, insane! loved it! ; fiction:, funny:
phys:workout         25m    ; reps: 305
```

- we'll keep generating a separate transaction from each data line, for now at least
- text following the date is currently used as a common description for all the day's transactions. In case anyone is using this, we will instead add such text as a common tag for the day's transactions, `day:` or some such. 
- after the time quantity (numeric or dotted), following 2+ spaces, we will read an optional transaction description, and/or semicolon comment, as in journal format
- addition comment lines below a data line will form additional transaction comment lines
- a (code) at the start of description could be parsed as the transaction's code
- a status mark (* or !) at the start could be parsed as the transaction's status. This is more impactful, it implies that timedot transactions would no longer have cleared status by default.

If all of these are implemented, the above would produce something like:
```
2021-11-12
    ; day: blah
    (sleep)               7.00

2021-11-12 cleaned, set up xmas decorations
    ; day: blah
    (job:store)           8.50

2021-11-12 * (21024) bathroom drain repair, sink didn't fit  ; plumbing:, invoice: 
    ; Mary suggests retrofitting the old one, scrapyard:
    ; day: blah
    (job:mary:reno)       0.75

2021-11-12 Kurt Vonnegut - Cat's Cradle, insane! loved it!  ; fiction:, funny: 
    ; day: blah
    (ent:reading)         1.25

2021-11-12  ; reps: 305
    ; day: blah
    (phys:workout)        0.41666666666666665
```

**Comment by alhirzel** [comment]
@simonmichael and/or @linuxcaffe - do either of you know of anyone working this issue at this time? I am a daily user of the timedot format and would like to implement this, as I have wished for the same thing!

**Comment by simonmichael** [comment]
Noone is working on it, be our guest @alhirzel .

**Comment by simonmichael** [comment]
Here's a RFC on changes to timedot format: https://groups.google.com/g/hledger/c/tRMvZnSF-lM/m/_CX-3-jsAQAJ

**Comment by simonmichael** [comment]
Ccing here (and reviewing the discussion above):

I'm fixing/improving timedot's description/comment/tag parsing. But before that.. 
which do you think is better: 

1. generating little transactions for each line, as we do now: 
```
2023-01-01 
a .... 
b .... 
c .... 
```
-> 
```
2023-01-01 
(a) 1 

2023-01-01 
(b) 1 

2023-01-01 
(c) 1 
```
Or 2. generating one big transaction per date line ? 
```
2023-01-01 
(a) 1 
(b) 1 
(c) 1 
```
I don't remember why it's implemented as 1. Right now, 2 looks a little tidier ? 
It would be a breaking change (print and register reports would change; 
balance reports would not). 

The above affects how timedot format can support descriptions and comments (and tags). 
Variant 2 would simplify that design space a bit: date lines can end with a transaction 
description and comment, time lines can end with a posting comment.

**Comment by simonmichael** [comment]
Now implemented in master: https://hledger.org/dev/hledger.html#timedot
