### ISSUE TITLE
Support different separators for CSV import [$10]

### ISSUE THREAD

**Issue by uu1101** [simonmichael/hledger#176]
CSV files served by some banks use a semicolon ";" as a separator instead of a comma. It would be useful being able to specify the separator in the rules file.
##

**Comment by simonmichael** [comment]
Our csv lib (or another) might support this now ? Personally I'd like the ability to read TSV (tab-separated values).

**Comment by larsen** [comment]
I had a look at the code of [Text.CSV](https://hackage.haskell.org/package/csv-0.1.2/docs/Text-CSV.html): it doesn't seem to the delimiter is replaceable with characters other than comma. The author is clear about it: the module is an implementation of RFC4180, that does not mention alternatives for the field separator. 

An option to implement this feature could be switching to something like [cassava](https://hackage.haskell.org/package/cassava), but I'm not sure about hledger dependency policies.
@simonmichael what would you recommend?

(I'd be happy to help with this task)

**Comment by simonmichael** [comment]
In general, we like light dependencies that just work, including on windows. cassava-megaparsec at http://hackage.haskell.org/packages/#cat:CSV is new and might be interesting ? After the 0.28 release https://github.com/simonmichael/hledger/pull/366 will be landing, and we'll be using megaparsec.

**Comment by pmatos** [comment]
I am interested in this since my bank serves semi-colon separated values.

**Comment by simonmichael** [comment]
Status update: 0.28 hasn't happened yet but #366 did land, so there's no reason to wait if someone wants to experiment with new CSV libs.

**Comment by peti** [comment]
Has anyone tackled this project yet? It's quite common for CSV files to use separators other than `,`, really, and it would be nice to have support for this (seemingly trivial) fact of life.

**Comment by simonmichael** [comment]
Anyone up for trying [cassava-megaparsec](http://hackage.haskell.org/package/cassava-megaparsec) ? It seems to handle any delimiter (but only one at a time, you might have to make several attempts I guess).

**Comment by ony** [comment]
Me ended up with [python script](https://gist.github.com/ony/5fa55f20dfc7f2da424e79dfda8e3269) . Default Python library `csv` is much more powerful than [`cassava-megaparsec`](http://hackage.haskell.org/package/cassava-megaparsec). [`csv-conduit`](http://hackage.haskell.org/package/csv-conduit) have more format settings than [`cassava-megaparsec`](http://hackage.haskell.org/package/cassava-megaparsec) but still lacks support for configuring format like `"Use ""Excel"" export\nMake your CSV parser fail"; 1138; "Have a fun"`.

**Comment by simonmichael** [comment]
https://groups.google.com/forum/#!topic/hledger/_aXEM1ssutc

**Comment by glumanda99** [comment]
I just converted a file with semicolons to a csv file with `cat bank.csv | sed 's/,/ /g' | sed 's/;/,/g' > bank.csv` in the meanwhile.

**Comment by sorsasampo** [comment]
[Osuuspankki](https://op.fi), one of the largest banks in Finland,  serves semicolon-separated fields as well. Probably because in Finland we use comma as a decimal separator - and it seems to be pretty popular in Europe:

https://en.wikipedia.org/wiki/Decimal_separator#Examples_of_use

So finnish and european users would probably be very happy about a configurable separator!

**Comment by simonmichael** [comment]
So would I. There's a lot of interest in this, who could take a crack at it ? Support available in #hledger if needed.

**Comment by simonmichael** [comment]
PS this issue has now been open for 4 years. :-)

**Comment by simonmichael** [comment]
Related helper by @sorsasampo: https://gitlab.com/sorsasampo/hledger-osuuspankki ([reddit](https://www.reddit.com/r/plaintextaccounting/comments/8j1xdk/hledger_support_for_finnish_osuuspankkis_csv/))

**Comment by lucamolteni** [comment]
I could work on this during Zurihac 2018.

**Comment by lucamolteni** [comment]
Can you please review this?

https://github.com/simonmichael/hledger/pull/829

Thank you

**Comment by simonmichael** [comment]
Done and merged. @lucamolteni I think you need to mark it resolved on bountysource.

**Comment by simonmichael** [comment]
Oh, perhaps I need to close this issue so you can do that. I was planning to discuss more here, but that makes sense. Done.

**Comment by simonmichael** [comment]
I was thinking the separator char is a property of the file and does not change between runs, so we should move it into the rules file. And actually, I see that's what this issue specified, but I don't want to delay this bounty any further. One of us will follow up before the end of month release. I also want to make this work for tab separators, and allow output in ssv and tsv formats.

**Comment by simonmichael** [comment]
Follow-on issues created, bounty claimed. Thanks @lucamolteni !
