### ISSUE TITLE
print -x and check -s are incompatible for zero-amounts

### ISSUE THREAD

**Issue by csamak** [simonmichael/hledger#1767]
test.journal:

```
<directives>

2021-12-02 Test
    assets:test               $0 = $0
```

hledger print -x -f test.journal:

```
2021-12-02 Test
    assets:test               0 = $0
```

which when ran through hledger check -s:

```
hledger: undeclared commodity ""
in transaction at: "/home/nixos/finance/test.journal" (lines 4-5)

  2021-12-02 Test
      assets:test               0 = $0
```

I am fine with the commodity being dropped for 0 in `print -x`, but in that case `check -s` should not check commodities for 0. It would also be fine to fix it the opposite way and not drop commodities for 0.

This seems closely related to (maybe a more general form of) https://github.com/simonmichael/hledger/issues/1356?

Setting a default commodity makes `check -s` work.

Tested with hledger 1.21

**Comment by simonmichael** [comment]
I would probably call this more of a wish than a bug, as we document "the print command is somewhat lossy", but this is another good example, one we don't call out in the doc and perhaps should.

**Comment by simonmichael** [comment]
Preserving commodity symbol for zero amounts is (I think) a rather huge task or even an impossible one, once you start to look into it, but I would be happy for someone to give it another look.

**Comment by Xitian9** [comment]
A potential solution is to always treat the empty commodity as having been declared.

**Comment by csamak** [comment]
I find it useful to have the empty commodity check (for when I forget to add a commodity.. I prefer not to have a default commodity).

Is it incorrect to ignore the check for 0 though? 0 means the same in any commodity right?

**Comment by simonmichael** [comment]
Generally yes @csamak. There are some special cases where a commodityful-zero is needed, eg for the per-commodity lines in hledger-web's register chart, but I think that's an internal matter. Cc'ing my latest comment from the PR:

> I imagine you're right that it probably won't cause problems in practice.
> I'm a little sad that we would give up the ability to check "all of my amounts have a declared commodity symbol", for the obsessive neat freaks among us. [Ok I mean me. It will now be "all of my non-zero amounts have a declared commodity symbol". And maybe that's fine.]
> But on the whole this change sounds like an improvement, I can merge soon.

**Comment by simonmichael** [comment]
This has been merged. Doc: https://hledger.org/dev/hledger.html#commodity-error-checking
