### ISSUE TITLE
CSV import

### ISSUE THREAD

**Issue by PSLLSP** [simonmichael/hledger#1778]
CSV import, amount is prefixed with currency. I would like to force postfix currency.

CSV import in hledger
```
income:unknown         EUR-10.23
```
desired format:
```
income:unknown         -10.23 EUR
```

CSV file (from hledger manual), **demo-ireland.csv**:
```
Date, Description, Id, Amount
12/11/2019, Foo, 123, 10.23
```

CSV rules, **demo-ireland.csv.rules**:
```
skip         1
fields       date, description, _, amount
date-format  %d/%m/%Y
currency     EUR
```

result:
```
$ hledger print -f demo-ireland.csv
2019-11-12 Foo
    expenses:unknown        EUR10.23
    income:unknown         EUR-10.23
```

**Comment by PSLLSP** [comment]
Maybe I found a solution, I define how amount filed looks: 


**demo-ireland.csv.rules**:
```
# basic.csv.rules
skip         1
fields       date, description, _, amount
date-format  %d/%m/%Y
#currency     EUR
amount %4 EUR
```
result:
```
2019/11/12  Foo
    income:unknown    -10.23 EUR
    unknown            10.23 EUR
```

Is this correct solution or is there a better way?

**Comment by simonmichael** [comment]
That's correct!

**Comment by the-solipsist** [comment]
I think this issue can be closed. Please re-open if there's anything else to be done.
