### ISSUE TITLE
hledger areg for multiple accounts

### ISSUE THREAD

**Issue by LaurenzWiskott2** [simonmichael/hledger#1780]
Following issue [1776](https://github.com/simonmichael/hledger/issues/1776).

I think it would be great if `hledger areg` would not only work for a single account but also for a group of accounts. Right now, if I use a template that would normally select a group of accounts, like `hledger areg account.*tax`, `areg` only works on one of them, presumably the first one. This is not what I expected intuitively, and it took me a while to actually notice. I like `areg`, because it aggregates all postings of a transaction into one line and gives a nice overview.  I would find it useful to have this also for a group of accounts.

**Comment by simonmichael** [comment]
Currently areg's reason for being is to give one account's register. I see that it seems confusing when you give it multiple arguments, perhaps we should be more informative when that happens. 

I'm not against exploring more flexibility for it, but someone would need to prototype it and work out all the test cases to validate the idea.

**Comment by LaurenzWiskott2** [comment]
Yes, on a second thought I think the easiest would be to add an option to reg to only show the last line of each transaction. And printing the last result in each transaction boldface would already bring 80% of the utility without complicating things at all.
