### ISSUE TITLE
Where is the chat?

### ISSUE THREAD

**Issue by iartarisi** [simonmichael/hledger#1807]
I can't really find a valid link for the chat room. In various places on the website and even github, I get this link: https://hledger.org/#help-feedback, then on that page there is a `Chat` link to https://hledger.org/#help link which doesn't go anywhere.

**Comment by simonmichael** [comment]
Thanks for the report, I'll fix those. The most up to date links are now at https://hledger.org/support.

**Comment by simonmichael** [comment]
Now fixed, I believe: 

- most help/contact links in the site and docs now point to Support/Discussion
- visits to index.html#help or index.html#help-feedback now land at the "Where should I go next ?" section
- that section now properly links to the chats, and Support/Discussion for more detail
