### ISSUE TITLE
`--strict` argument to `check` does not see forecasted transactions

### ISSUE THREAD

**Issue by gullcomb** [simonmichael/hledger#1810]
Given the following:

```ledger
account Account

~ 2022-01-31
    Account  $1
    Bccount
```

I expected `hledger check --strict --forecast=..2022-02-01` to detect the undeclared account like `hledger check accounts --forecast=..2022-02-01` does. My reading of [the documentation](https://hledger.org/1.24/hledger.html#strict-checks) is that any error reported by the latter should be reported by the former.

(`hledger --version` = `hledger 1.24.1, linux-x86_64`, version `1.24.1-18` from Arch Linux' repositories)

**Comment by simonmichael** [comment]
Thanks!
