### ISSUE TITLE
Comma seems to be converted to decimal with lot pricing

### ISSUE THREAD

**Issue by murtyjones** [simonmichael/hledger#1830]
```
2022-02-23 BUY INVESTMENTS
    assets:chase:checking                           $-2,000.00
    assets:invest                            12.612 FOO @@ $1,000
    assets:invest                             8.954 BAR @@  $1,000
```

then `hledger bal` yields:

```
could not balance this transaction:
real postings' sum should be 0 but is: $-1,998.000
```

**Comment by Xitian9** [comment]
Hmm, you seem to be correct. In the meantime you can work around this with a commodity declaration.

```
2022-02-23 BUY INVESTMENTS
    assets:chase:checking                           $-2,000.00
    assets:invest                            12.612 FOO @@ $1,000
    assets:invest                             8.954 BAR @@  $1,000
    ```

**Comment by Xitian9** [comment]
I think this is a duplicate of #698, as the same problem arises if you remove the decimal point from the first posting.

**Comment by murtyjones** [comment]
Thanks for the quick reply. Those workarounds make sense to me and since this appears to be a dupe, I'll go ahead and close it in favor of #698

**Comment by simonmichael** [comment]
Thanks for the report.

I'm not sure this is a bug in light of current docs: https://hledger.org/hledger.html#decimal-marks-digit-group-marks, which say "in numbers with an ambiguous mark, we assume it's a decimal mark; disambiguate with `commodity` or `decimal-mark`".
