### ISSUE TITLE
tree-mode balance reports do not show account hierarchy properly in HTML output

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1846]
$ hledger bal --tree  # subaccounts are properly indented
$ hledger bal --tree -o a.html  # subaccounts are not indented

**Comment by simonmichael** [comment]
FYI @thielema, in case it affects FODS output.

**Comment by thielema** [comment]
I have also encountered the missing indentation when experimenting with a LaTeX output.

**Comment by simonmichael** [comment]
The reports at https://github.com/simonmichael/hledger_finance have been updated, showing recent HTML improvements including a tree-mode report.
