### ISSUE TITLE
Crash: journalApplyValuationFromOpts: expected all spans to have an end date (since 1.22)

### ISSUE THREAD

**Issue by edlanglois** [simonmichael/hledger#1851]
The following income statement report crashes with `journalApplyValuationFromOpts: expected all spans to have an end date`

# Example
**command**
`hledger -f test.journal incomestatement --date2 --yearly --value=end`
Removing any of these options avoids the crash.  `--value=cost,'$'` crashes as well.

**test.journal**
```
2019-12-31 FOO
    Assets:A        $1.00
    Income:B

2020-01-01=2019-12-30 BAR
    Assets:A        $1.00
    Income:B
```

**output**
```
hledger: journalApplyValuationFromOpts: expected all spans to have an end date
CallStack (from HasCallStack):
  error, called at ./Hledger/Reports/ReportOptions.hs:604:11 in hledger-lib-1.25-8vNyE2cdZK46wrZOeWidOi:Hledger.Reports.ReportOptions
```

**version**
`hledger 1.25, linux-x86_64`

**Comment by simonmichael** [comment]
Good catch, thanks for the report! This broke in hledger 1.22, please claim your https://hledger.org/regressionbounty at your convenience.

**Comment by Xitian9** [comment]
Almost certainly this broke because of me. I'll look into it.

I've always thought it's a source of potential bugs that we use `DateSpan` for things which require both a start and an end date. Maybe we should replace it with `(Day, Day)` in `PeriodicReport`.

**Comment by simonmichael** [comment]
Fixed for next release, thanks @Xitian9.

**Comment by simonmichael** [comment]
I just noticed I somehow missed @edlanglois's opencollective expense on April 11. Very sorry Eric, I just approved it.

**Comment by edlanglois** [comment]
No worries, thanks! Can't possibly complain when you're already providing this great software for free :)

**Comment by simonmichael** [comment]
See if you can find some more and I'll approve promptly!
