### ISSUE TITLE
--infer-equity amounts are not styled by -c/--commodity-style

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#1856]
```journal
2022-01-01
  a         A5.00 @ B1.123456
  b

comment
Should show B amounts with no decimals, like A:

$ hledger -f a.j print -x --infer-equity -c A1. -c B1.
2022-01-01
    a                                    A5  ; cost: @ B1.123456
    equity:conversion:A-B:A             A-5  ; generated-posting:
    equity:conversion:A-B:B       B5.617280  ; generated-posting:
    b                             B-5.61728
```

**Comment by J12D** [comment]
Could someone comment on whether this is intended behavior?
Is there a way to have asset B formatted with the specified decimal precision?

**Comment by simonmichael** [comment]
It's not intended. I see slightly different behaviour with current hledger, and it doesn't seem necessarily related to --infer-equity. This needs someone to investigate it and produce a new more precise repro.

**Comment by J12D** [comment]
Indeed, this problem seems independent of `--infer-equity`.
In the below, I believe assets:cash should be reported in the specified commodity style.

File: `a.j`
```
commodity 1,000. USD

2022-01-01 Buy A
  assets:investment  10 A @ 1.23456 USD
  assets:cash

P 2023-04-01 A 2.34567 USD
```

`hledger -f a.j print -x`
```
2022-01-01 Buy A
    assets:investment    10 A @ 1.23456 USD
    assets:cash                -12.3456 USD
```

`hledger -f a.j print -xV`
```
2022-01-01 Buy A
    assets:investment          23 USD
    assets:cash          -12.3456 USD
```

**Comment by J12D** [comment]
This is even more concise:
File `a.j`
```
commodity 1,000. USD

2022-01-01 Transfer cash
  assets:cash  -1.23456 USD
  assets:bank
```

`hledger -f a.j print -x`
```
2022-01-01 Transfer cash
    assets:cash    -1.23456 USD
    assets:bank     1.23456 USD
```

**Comment by simonmichael** [comment]
Actually, this is normal with https://hledger.org/dev/hledger.html#print : "All of their decimal places are shown, as in the original journal entry" (otherwise it could show invalid/unparseable journal entries). Other reports will display with the specified precision.
