### ISSUE TITLE
tags command shows account tag only when there are transactions in account

### ISSUE THREAD

**Issue by RobertNielsen1** [simonmichael/hledger#1857]
If you have only the following in a file:

`account assets:bank  ; qq:`

Then when running the following command, no tags are listed.

`hledger tags`

However, if you have a transaction later on in the file that includes "assets:bank" (and without any explicit tag declared in the transaction) then the tags command correctly lists the tag (qq).

**Comment by simonmichael** [comment]
Good catch. Fixing this involves a question: 

Should `tags` show only tags actually on the matched thing, or also inherited/acquired tags ? 

Eg postings have their own tags, and will also acquire tags from their account and from their transaction. Transactions have their own tags, and will also acquire tags from their postings. 

Queries see both the local and acquired tags. Internally, I believe (most of ?) the acquired tags are applied to the entities at parse time

So if you are matching a specific transaction, should `tags` also show the tags of that transaction's postings' accounts ? Currently it does.

**Comment by simonmichael** [comment]
This confused me for a bit: `account assets:bank ; qq:` was a typo, it must be `account assets:bank    ; qq:` (at least [two spaces](https://hledger.org/hledger.html#account-comments) between account name and comment).

This also confused me: `tags` CLI is not the common `CMD [QUERY]`, but `tags [TAGREGEX [QUERY]]`.

Ok I think I get it. Currently we do show acquired tags, and that's easiest and probably the most useful.

Here are the latest proposed tests:
```
# tags command

account a   ; t1:v1, an account tag
account b   ; t2:v2, an unused account

2000/1/1    ; t3:v3, a transaction tag
  (a)    1  ; t4:v4, a posting tag

2000/1/2    ; t5:v4, a reused value
  (c)    1  ; t6:v6, an undeclared account

# 1. show all tags
$ hledger -f- tags
t1
t2
t3
t4
t5
t6

# 2. show all tag values
$ hledger -f- tags --values
v1
v2
v3
v4
v6

# 3. show tags matching a regex
$ hledger -f- tags '[1-4]'
t1
t2
t3
t4

# 4. show matched tags on a matched transaction
$ hledger -f- tags . date:2000/1/1
t1
t3
t4

# 5. show account tags even when there are no transactions (#1857)
<
account a   ; t1:

$ hledger -f- tags
t1
```

But there's an ambiguity around tests 4 and 5. In 4, note how I matched just the first transaction, then I expected to see only the tags active on that transaction (t1, t3, t4). How should it know I don't want to also see other account tags here, like t2 ?

**Comment by simonmichael** [comment]
I got it working this way:
```
# 4. show tags matching (a regex and) a hledger query.
$ hledger -f- tags . b c
t2
t5
t6

# 5. A transaction-related query limits the search to matched transactions;
# tags from accounts not used by those transactions will not be included.
$ hledger -f- tags . date:2000/1/1
t1
t3
t4
```
Ie, when there is a query for something not provided by account declarations (anything other than acct:, depth:, type:), account declarations not involved in the matched transactions are excluded. Hopefully that makes sense and will be the intuitive in practice.

**Comment by RobertNielsen1** [comment]
Thank you, Simon. Good to point out the necessity of the 2+ spaces, and I can confirm that the problem occurs with 2+ spaces.

There are a couple of things that I don't understand in the above section with the proposed tests.

First, what is the "-f-" that appears in the commands?

Second, in example 4, what is the function of the period between "tags" and "date:2000/1/1"?

I just saw your other post and will look at that later, but wanted to ask my questions to clear up my understanding!

Rob

**Comment by simonmichael** [comment]
`-f-` (or `-f -`) means read data from standard input instead of $LEDGER_FILE. We use this in the functional tests in hledger/test/ , which I copy/pasted above.

The period is the TAGREGEX argument, which I had to provide in order to add the QUERY argument. Since I'm not testing TAGREGEX there I made it `.` which is "match any character" in regexese.

**Comment by simonmichael** [comment]
I pushed this, and updated the doc at https://hledger.org/dev/hledger.html#tags .

**Comment by RobertNielsen1** [comment]
Thank you for your excellent work on this!
