### ISSUE TITLE
Version 1.26 of hledger/-web doesn't run on Windows

### ISSUE THREAD

**Issue by tech189** [simonmichael/hledger#1869]
Hi, when running either `hledger.exe` or `hledger-web.exe` from the command line, there is no output and no commands can be run. When double clicking on them from File Explorer the following error is shown:

```
---------------------------
hledger.exe - System Error
---------------------------
The code execution cannot proceed because libgcc_s_seh-1.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```

Running version 1.25 does not have the same issue and works with no problem. I tried copying `libgcc_s_seh-1.dll` from another program into the folder but now it says that it cannot find `libwinpthread-1.dll`!

I am on Windows 11 build 22000.708.

**Comment by simonmichael** [comment]
Would any Windows user be able to help identify the difference between https://github.com/simonmichael/hledger/releases/1.25 and (current) https://github.com/simonmichael/hledger/releases/1.26 windows binaries ? I expected them to be similar, and I am having trouble reviving a Windows VM to test.

**Comment by simonmichael** [comment]
Actually I used GHC 9.0, they should be fixed now.

**Comment by tech189** [comment]
Latest version works for me!
