### ISSUE TITLE
Flag for `print` to keep non-transactions.

### ISSUE THREAD

**Issue by the-solipsist** [simonmichael/hledger#1880]
Currently `hledger print` discards directives (price declarations, commodity declarations, include statements, etc.) and inter-transaction comments.

Proposal: add a flag (e.g., `--keep-directives-comments` or `--reformat-all` or something more appropriate) to retain directives and inter-transaction comments.

**Comment by simonmichael** [comment]
Duplicate of https://github.com/simonmichael/hledger/issues/1127 I think.
