### ISSUE TITLE
hledger-ui: support brick 1.0 (RFC: brick EventM API changes)

### ISSUE THREAD

**Issue by jtdaugherty** [simonmichael/hledger#1889]
I'm working on an overhaul of `brick`'s `EventM` API and I'd love to get your feedback on how it might impact this project. Please see the details and post comments on https://github.com/jtdaugherty/brick/issues/379. Thanks!

**Comment by simonmichael** [comment]
Discussion continues at https://github.com/jtdaugherty/brick/issues/379. 

Some general design discussion possibly useful for us begins [here](https://github.com/jtdaugherty/brick/issues/379#issuecomment-1191993357).

**Comment by simonmichael** [comment]
PS and thanks @jtdaugherty for your work and the heads-up.

**Comment by jtdaugherty** [comment]
Thanks, @simonmichael !

**Comment by simonmichael** [comment]
Reopening as a reminder to prepare for the future API change.

**Comment by jtdaugherty** [comment]
Hi, folks - Brick 1.0 is out. Here are the details: https://github.com/jtdaugherty/brick/blob/master/CHANGELOG.md#10

**Comment by simonmichael** [comment]
Related: https://github.com/commercialhaskell/stackage/issues/6682

**Comment by simonmichael** [comment]
Hi @jtdaugherty, I'm having trouble porting code involving handleEditorEvent, which uses a different state type than the main handler.  Would you have any clues handy ? Eg in code like:
```haskell
  case mode of
    Minibuffer _ ed ->
      case ev of
        VtyEvent (EvKey KEsc   []) -> put $ closeMinibuffer ui
        VtyEvent ev -> do
          ed' <- handleEditorEvent (VtyEvent ev) ed
          put ui{aMode=Minibuffer "filter" ed'}
```
should I be using runState to run an inner computation updating ed ?

**Comment by simonmichael** [comment]
Ha never mind, re-reading the excellent migration notes will help.

**Comment by jtdaugherty** [comment]
Great, I’m glad you got it sorted out. Let me know if anything else comes up!

**Comment by simonmichael** [comment]
We now use and require brick 1.0 (cf #1919). (This means that hledger 1.27 won't get into stackage nightly until brick 1.0 does.)

**Comment by simonmichael** [comment]
Crashes on entering an account register.

**Comment by simonmichael** [comment]
Fixed at last, UI tests passing.
