### ISSUE TITLE
Commas turns into Period (dot)

### ISSUE THREAD

**Issue by marshellwu** [simonmichael/hledger#1893]
version: 1.26
platform: windows

![Screenshot 2022-07-23 163105](https://user-images.githubusercontent.com/108053986/180599566-dc776ff5-f68a-484b-8ce1-ac578d126a26.png)

Even thought I used commas in the file, why hledger treat it as period?
Couldn't find what's wrong
This is messing up my balance as I consistently use commas.

I even gave a space in every `.journal` file ending line that I `include` in the `main.journal`

**Comment by marshellwu** [comment]
After tweaking with directives for a while, I found it fixed by formatting the commodity like:
```
commodity Rp
    format Rp1,000.
```
> note the `dot` at the end of the `format`

**Comment by simonmichael** [comment]
Exactly, or you can https://hledger.org/1.26/hledger.html#declaring-the-decimal-mark.
