### ISSUE TITLE
print with account specified and amt:</> with +/- contains postings for account with opposite sign

### ISSUE THREAD

**Issue by tuxlifan** [simonmichael/hledger#1896]
Hello,

Use case: find and `print` _details_ for particularly large or small amounts being deducted from (or added to) an account.

using hledger 1.26, linux-x86_64
with following test file "amt_query_minus" with arbitrary numbers:
```
1970-01-01 * Foo
    assets:Banking:Account    1,200.00 EUR
    income:unknown

1970-01-02 * Bar | with note
    assets:Banking:Account    -1,001.00 EUR
    expenses:unknown

1970-01-03 * Baz
    assets:Banking:Account    -2,000.00 EUR
    expenses:unknown          ; and a comment

1970-01-04 * Splitting 
    assets:Banking:Account    3,000.00 EUR
    income:unknown:split1   -500 EUR
    income:unknown:split2   -500 EUR
    income:unknown:split3   -500 EUR
    income:unknown          ; implicit -1500

1970-01-05 * small
    assets:Banking:Account    -0.02 EUR
    expenses:unknown
```

the command `hledger -f amt_query_minus print assets:Banking:Account 'amt:<-1100'` contains also "Foo" and "Splitting"
```
1970-01-01 * Foo
    assets:Banking:Account    1,200.00 EUR
    income:unknown

1970-01-03 * Baz
    assets:Banking:Account    -2,000.00 EUR
    expenses:unknown                         ; and a comment

1970-01-04 * Splitting
    assets:Banking:Account    3,000.00 EUR
    income:unknown:split1      -500.00 EUR
    income:unknown:split2      -500.00 EUR
    income:unknown:split3      -500.00 EUR
    income:unknown                          ; implicit -1500

```
apparently because of the posting amounts for other accounts matching the `amt:` term since "Foo" and "Splitting" disappear with
`hledger -f Test/amt_query_minus print assets:Banking:Account 'amt:<-1600'`
```
1970-01-03 * Baz
    assets:Banking:Account    -2,000.00 EUR
    expenses:unknown                         ; and a comment
```

In the QUERIES section of the manual under "Combining query terms" is written

```
[...] the print command shows transactions which:

    * match any of the description terms AND
    * have any postings matching any of the positive account terms AND
               ^^^^^^^^                     ^^^^^^^^^^^^^^^^^^^^^^ ^^^
    * have no postings matching any of the negative account terms AND
    * match all the other terms.
            ^^^^^^^^^^^^^^^^^^^
```
Shouldn't the AND imply that the `amt:<-` should apply to postings maching the account terms? Otherwise I would not specify an account or leave out the sign if I was only interested in magnitude.

The `register` command filters the transactions as expected but does not show any details about the transactions:
`hledger -f Test/amt_query_minus register assets:Banking:Account 'amt:<-1100'`
```
1970-01-03 Baz     assets:Banking:Account     -2,000.00 EUR  -2,000.00 EUR
```
f.e. in a different scenario to find large additions where I would like to study "Splitting" I cannot see all split accounts, even with --related --invert; much less tags or posting comments:
`hledger -f Test/amt_query_minus register assets:Banking:Account 'amt:>1100' --related --invert`
```
1970-01-01  Foo        income:unknown      1,200.00   EUR    1,200.00  EUR
1970-01-03  Baz        expenses:unknown    -2,000.00  EUR    -800.00   EUR
1970-01-04  Splitting  income:unknown      1,500.00   EUR    700.00    EUR
```

Thanks

**Comment by simonmichael** [comment]
Thanks for the report. Sorry, but no, currently AND does not imply that `amt:` should be limited to the postings matched by another query term. Each individual query term is applied in the normal way to the thing being matched (for print, transactions), and then those results are combined in the way described. While it doesn't do what you wanted here, my hunch is that it's more predictable and free of tricky corner cases. Perhaps https://github.com/simonmichael/hledger/issues/203 would be the way to get what you want.

**Comment by tuxlifan** [comment]
Thank you for rephrasing it.
Indeed, I misunderstood the postings conditions as narrowing down the scope and the list being applied sequentially while in reality, as you say, each of the 4 conditions independently leads to a set of transactions of which the intersection is the end result.

Using boolean expressions from #203 (or piping until then) there seems to be a possible solution for some cases with 
`hledger -f amt_query_minus print assets:Banking:Account 'amt:>1100' | hledger -f- print expenses`
```
1970-01-03 * Baz
    assets:Banking:Account    -2,000.00 EUR
    expenses:unknown                         ; and a comment
```
while relying on expenses vs. income to provide the sign distinction; however, one must be mindful of possible splits to the "wrong" side (e.g. income tax as an expense) so this method can become unwieldy and specialized very fast. A simple (for users) solution in hledger proper would require being able to specify against which level of detail of a thing to match (i.e. posting for transactions, etc.).

[The following assumes unix-like linebreaks (\n)]

Giving up on hledger-internal easy solutions and thinking along pipes, after pondering the implications of -O{csv,json,sql} and the nightmare of regaining a nice representation afterwards, there actually exists a quite simple solution using gawk (and probably also other awk implementations).
The secret sauce lies in `print` with the default output currently separating transactions by empty lines [^sed] and in letting awk handle all lines in-between as one record [^awkmultiline]:
[for leading currency symbols you would need to adapt the regular expressions]

1. Find large deductions (<-1100)
<pre>hledger -f amt_query_minus.commented print assets:Banking:Account 'amt:<b>>1100</b>' \
 | gawk -n 'BEGIN{RS=""} /\n +assets:Banking:Account<b>( +)-</b>/{print $0; print ""}'</pre>
[^nplus][^paren]
```
1970-01-03 * Baz
    assets:Banking:Account    -2,000.00 EUR
    expenses:unknown                         ; and a comment

```

2. Find small deductions (>-5)
<pre>hledger -f amt_query_minus.commented print assets:Banking:Account 'amt:<b><5</b>' \
| gawk -n 'BEGIN{RS=""} /\n +assets:Banking:Account<b>( +)-</b>/{print $0; print ""}'</pre>
```
1970-01-05 * small
    assets:Banking:Account       -0.02 EUR
    expenses:unknown

```

3. Find pennies (<+1)
For this example the test file has to be extended with
```
1970-01-06 * a penny a day
    assets:Banking:Account    0.01 EUR  ; probably rather ...:cash:pennies
    income:finding pennies
```
and then
<pre>hledger -f amt_query_minus.commented print assets:Banking:Account 'amt:<b><1</b>' \
| gawk -n 'BEGIN{RS=""} /\n +assets:Banking:Account<b>( +)[0-9]</b>/{print $0; print ""}'</pre>
```
1970-01-06 * a penny a day
    assets:Banking:Account        0.01 EUR  ; probably rather ...:cash:pennies
    income:finding pennies

```

4. Find large accruals (>+1500)
<pre>hledger -f amt_query_minus.commented print assets:Banking:Account 'amt:<b>>1500</b>' \
| gawk -n 'BEGIN{RS=""} /\n +assets:Banking:Account<b>( +)[0-9]</b>/{print $0; print ""}'</pre>
```
1970-01-04 * Splitting
    assets:Banking:Account    3,000.00 EUR
    income:unknown:split1      -500.00 EUR
    income:unknown:split2      -500.00 EUR
    income:unknown:split3      -500.00 EUR
    income:unknown                          ; implicit -1500

```

So please feel free to close this issue and also to use it as you see fit.


[^nplus]: The `\n +` at the beginning of the line regex is just a precaution against commented out postings. (`^` would be the beginning of the record so we have to anchor to `\n` here)
[^paren]: the parentheses in `( +)` are not necessary but make it easier to understand, especially in the first case where ` +-` might be a bit hard to grok at a quick glance
[^sed]: although these could also be reintroduced by GNU sed or similar with `... | sed 's#^\([^ ]\)#\n\1#' | ...` to put the non-indented smartdate on a new line in a pipe
[^awkmultiline]: [GNU Awk's User's Guide, 4.9 Multiple-Line Records](https://www.gnu.org/software/gawk/manual/html_node/Multiple-Line.html)

**Comment by simonmichael** [comment]
Nice! Plain text for the win!
