### ISSUE TITLE
Install instruction at release page for Linux are not correct

### ISSUE THREAD

**Issue by PSLLSP** [simonmichael/hledger#1922]
[Release page](https://github.com/simonmichael/hledger/releases/tag/1.26.1), has this receipt to install the latest `hledger` to Linux system:

```
cd /usr/local/bin
curl -LOC- https://github.com/simonmichael/hledger/releases/download/1.26.1/hledger-linux-x64.zip   # can rerun this if interrupted
unzip hledger-linux-x64.zip
chmod +x hledger hledger-ui hledger-web
cd -
hledger --version  # should show the new version
touch $HOME/.hledger.journal   # ensure a default journal file exists
```

This is not correct, because zip archive doesn't contain files `hledger`, `hledger-ui` and `hledger-web`:

```
$ unzip -l hledger-linux-x64.zip 
Archive:  hledger-linux-x64.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
 45512664  2022-07-31 22:15   hledger-linux-x64
 47684088  2022-07-31 22:15   hledger-ui-linux-x64
 96287352  2022-07-31 22:15   hledger-web-linux-x64
---------                     -------
189484104                     3 files
```

I do it for long time, I just want to highlight it here:
```
mv hledger-linux-x64 hledger
mv hledger-ui-linux-x64 hledger-ui
mv hledger-web-linux-x64 hledger-web
```

Without renaming files, commands `chmod` and `hledger --version` from receipt work on old hledger binaries those were in /usr/local/bin...

**Comment by simonmichael** [comment]
I believe the newer instructions at https://github.com/simonmichael/hledger/releases/tag/1.27 are accurate. Thanks for the report.
