### ISSUE TITLE
Removed command hledger check-dates is still displayed on shell completion

### ISSUE THREAD

**Issue by louislebrault** [simonmichael/hledger#1926]
Version : hledger 1.26, linux-x86_64

The problems concerns also `check-dupes` command.

```
$ hledger check-d
check-dates  -- check that transactions are sorted by increasing date
check-dupes  -- report account names having the same leaf but different prefixes
```

When trying to run those commands it leads to an error message :

```
hledger: Error: command check-dates is not recognized, run with no command to see a list
```

If this is within my competences and if somebody confirms this is an oversight i may update shell completion, replacing it by `hledger check <check>`.

**Comment by simonmichael** [comment]
+1, that does sound like an oversight. The completions are defined in their own directory, should be not too hard.

**Comment by simonmichael** [comment]
Agreed, we only provide bash completions currently. Closing this.
