### ISSUE TITLE
Backspace is broken after autocomplete (removes whole line including field title)

### ISSUE THREAD

**Issue by veikus** [simonmichael/hledger#1928]
Hi,
Sometimes backspace instead of removing only editable data removes line completely (sometimes even few previous lines).

Found a way to reproduce bug stable it with a small .hledger file:

`hledger add -f ~/Downloads/test.hledger`
Date: Press "Enter"
Description: Enter "Amazon|Gift" then press "Tab"
Account 1: Press "Tab", "Enter"
Amount 1: Press "Tab", "Enter"
Account 2: Press "Tab", "Enter"
Amount 2: Press "Tab", "Enter"
Account 3: Press "Enter"
Save this transaction: Press "Enter"

Date: Press "Enter"
Description: Enter "Amazon|Gift" then press "Tab". Hold "Backspace". Full line will be removed (with "Description" prefix).

Video:
https://user-images.githubusercontent.com/734550/188507907-c416d978-80bb-444b-91e2-3323a1f4d481.mov

hledger file:
[test.hledger.txt](https://github.com/simonmichael/hledger/files/9491851/test.hledger.txt)

Sometimes bug can be reproduced on Amount and Account fields.

OS: macOS 12.5.1 (M1)
hledger version: hledger 1.26.1, mac-aarch64 (from homebrew)

**Comment by simonmichael** [comment]
Thanks for the report. I could not reproduce with a few tries in Terminal or iTerm3. Are you able to reproduce every time with the above script ? Which terminal are you using ? Are you able to reproduce in other terminals / on other OSes ?

**Comment by simonmichael** [comment]
Whoops, I was not running homebrew's hledger. I can reproduce with that, in a simpler way: after tab-completing the first date and pressing backspace three times, the screen looks like:
```
$ /opt/homebrew/bin/hledger-1.26 -f/dev/null add
Adding transactions to journal file /dev/null
Any command line arguments will be used as defaults.
Use tab key to complete, readline keys to edit, enter to accept defaults.
An optional (CODE) may follow transaction dates.
An optional ; COMMENT may follow descriptions or amounts.
If you make a mistake, enter < at any prompt to go one step backward.
To end a transaction, enter . when prompted.
T
```

**Comment by veikus** [comment]
Wow. Thank you for checking.

Noticed one more difference between homebrew (1.26) and 1.27 from GitHub related to suggest. Maybe this may help somehow.
Suggest formatting for description is broken on homebrew version.

If tab was not pressed on a date field:
<img width="1487" alt="Screenshot 2022-09-08 at 11 11 23" src="https://user-images.githubusercontent.com/734550/189071378-ba3ae352-3a10-4fab-8217-77c6f44818df.png">

If tab was pressed on a date field and them suggests for Amazon are requested:
<img width="1487" alt="Screenshot 2022-09-08 at 11 11 07" src="https://user-images.githubusercontent.com/734550/189071319-a3011244-ba91-4d48-920c-7e38f0671ff9.png">

1.27 from GitHub:
<img width="1487" alt="Screenshot 2022-09-08 at 11 12 03" src="https://user-images.githubusercontent.com/734550/189071537-48be1f79-915c-4e1e-ab02-2deb7e09265e.png">

**Comment by simonmichael** [comment]
Homebrew has packaged hledger 1.27, and we believe the new binary is free of this problem. Any extra confirmation welcome for https://github.com/Homebrew/homebrew-core/issues/109922 .

**Comment by veikus** [comment]
Yes, both issues are fixed on homebrew version. Thank you.
