### ISSUE TITLE
hledger cashflow doesn't work anymore

### ISSUE THREAD

**Issue by schoettl** [simonmichael/hledger#1930]
I used to use `cashflow` in my reports. In a report for 2021 it looked like:
![grafik](https://user-images.githubusercontent.com/1301843/189765342-64ff7041-fb93-465a-95af-14671486252c.png)

Today, it only prints an empty table.

hledger version 1.27.99 (master) and 1.26.1 (Arch package)

It looks like it only regards `assets:cash`. Is this intended?

I prepared this shelltest. The first example prints an empty table, the second example works as expected.

```

<
2022-09-12 foo
    assets:a   5
    income:b  -5
$ hledger -f- cashflow
>
Cashflow Statement 2022-09-12

            || 2022-09-12 
============++============
 Cash flows ||            
------------++------------
 assets:a    ||          5 
-------------++------------
             ||          5 
>= 0

<
2022-09-12 foo
    assets:cash  5
    income:b    -5
$ hledger -f- cashflow
>
Cashflow Statement 2022-09-12

             || 2022-09-12 
=============++============
 Cash flows  ||            
-------------++------------
 assets:cash ||          5 
-------------++------------
             ||          5 
>= 0

```

**Comment by Xitian9** [comment]
Yes, this is intentional. Do you declare account types explicitly? If you do not, then cash accounts are those which match the following regular expression: `^assets?(:.+)?:(cash|bank|che(ck|que?)(ing)?|savings?|current)(:|$)`.
Otherwise, you can declare which accounts you want to be cash accounts explicitly: https://hledger.org/1.27/hledger.html#account-types

**Comment by simonmichael** [comment]
Yes we made a change in hledger 1.25 @schoettl :

> The rule for auto-detecting "cash" (liquid asset) accounts from account names for the cashflow report has been simplified. If you have been using the cashflow report, without explicitly declaring Cash accounts, you might notice a change, and might need to declare your Cash accounts explicitly (by adding type:C tags to top-level cash account directives).

The intention was to make the rules simpler and more well-behaved overall (not to break your setup, sorry about that :).  Here's the latest rule: https://hledger.org/1.27/hledger.html#cashflow

**Comment by schoettl** [comment]
Oh OK, I should have looked at the documentation more thoroughly!
Thank you for the links. It should be no problem to change my account names accordingly.
Thank you!
