### ISSUE TITLE
hledger-web cannot save transaction, returns "Value is required"

### ISSUE THREAD

**Issue by andrasf** [simonmichael/hledger#1932]
If I open hledger-web and add a new transaction, it does not save it, but returns error message. It works in hledger-ui.

Used version: hledger 1.27, mac-aarch64

Example pictures attached to reproduce.
![Screenshot 2022-09-14 at 16 18 27](https://user-images.githubusercontent.com/288001/190180199-f6805af5-dd4d-4365-bbab-35c310e7c692.png)
![Screenshot 2022-09-14 at 16 18 34](https://user-images.githubusercontent.com/288001/190180219-b269b950-2f86-40ec-b1ec-29e9c94cc58c.png)

**Comment by simonmichael** [comment]
Thanks for the report! Claim your regression bounty at http://hledger.org/regressionbounty .

The file field, which appears only when there are multiple files, should not have been made mandatory. As a temporary workaround, add an include to another file, forcing the field to appear:
```
$ echo > dummy.j
$ echo 'include dummy.j' >> $LEDGER_FILE
```

**Comment by simonmichael** [comment]
Fixed in master, will be released in 1.27.1 soon.

**Comment by simonmichael** [comment]
Hi @andrasf. I just approved your bounty payment - I'm very sorry for overlooking the approval notification. I have changed my mail rules to hopefully fix this in future.
