### ISSUE TITLE
hledger-ui on alacritty won't start

### ISSUE THREAD

**Issue by ocyj** [simonmichael/hledger#1939]
I've used hledger-ui successfully on alacritty before, but at some point it stopped starting, stating:

```
hledger-ui: no fore color support for terminal alacritty
CallStack (from HasCallStack):
  error, called at src/Graphics/Vty/Output/TerminfoBased.hs:119:39 in vty-5.37-8nUoNPcoKxc9l9PvrpykMo:Graphics.Vty.Output.TerminfoBased
```
hledger-ui version: `hledger-ui 1.27, linux-x86_64`
alacritty version: `alacritty 0.10.1 ()`

I can still use other terminal emulators however. Not sure if the problem is with alacritty/my config.

**Comment by simonmichael** [comment]
Thanks for the report @ocyj. This error looks like it's coming from the [vty package](https://hackage.haskell.org/package/vty), could you possibly test with the vty-demo/vty-mode-demo programs it provides. If they also fail, then perhaps a bug report at https://github.com/jtdaugherty/vty/issues is in order.

**Comment by ocyj** [comment]
Thank you for your reply (and work on hledger) @simonmichael! The vty-demo and vty-mode-demo programs seems to me to work fine, vty-demo:
![Screenshot_2022-10-07_13-06-05](https://user-images.githubusercontent.com/13800272/194540479-97f66e77-5026-42c1-9a74-6a1958318a1c.png)

and vty-mode-demo:
```
Mouse mode supported: False
Mouse mode status: False

Paste mode supported: False
Paste mode status: False

Last event: Just (EvKey (KChar 'm') [])

Press 'm' to toggle mouse mode, 'p' to toggle paste mode, and 'q' to quit.
```
I bypassed my alacritty config when starting alacritty, and hledger-ui works properly in that instance so it seems I have something weird in my config (I apologize, should have tried that before creating an issue...), I'll try to figure out what's wrong.

**Comment by ocyj** [comment]
OK, so for future reference, I had a theme (Iceberg Light) defined (in my `alacritty.yml` where the color values where specified using notation such as `foreground: '0x33374c'`, by changing these to the format `foreground: '#33374c'` hledger-ui worked again!
