### ISSUE TITLE
Track investments: Market price failure

### ISSUE THREAD

**Issue by aimuz** [simonmichael/hledger#1940]
https://hledger.org/investments.html#track-investments-2020

I consulted the documentation and found that the current version does not perform as expected in the documentation

```
2020-01-01 opening balances
    assets:bank:checking                       $1000
    equity:opening/closing balances

2020-02-01
    assets:cc:ada:20200201                      2000 ADA @@ $40
    assets:bank:checking                        $-40

P 2020-02-01 ADA $0.02
P 2020-03-01 ADA $0.04
```

https://hledger.org/investments.html#value-reports-some-gotchas

According to the documentation, the expected output from executing this command is this
```
$ hledger bs --flat -V |head -10
Balance Sheet 2020-02-01, current value

                        || 2020-02-01 
========================++============
 Assets                 ||            
------------------------++------------
 assets:bank:checking   ||    $960.00 
 assets:cc:ada:20200201 ||     $80.00 
------------------------++------------
                        ||   $1040.00 
```

This is the result of my local implementation

```
$ hledger bs --flat -V |head -10
Balance Sheet 2020-03-01, converted to cost, valued at period ends

                        || 2020-03-01
========================++============
 Assets                 ||
------------------------++------------
 assets:bank:checking   ||    $960.00
 assets:cc:ada:20200201 ||     $40.00
------------------------++------------
                        ||   $1000.00
```

 assets:cc:ada:20200201  Not consistent

version:
```
hledger 1.27.1, mac-x86_64
Usage: hledger COMMAND [OPTIONS] [-- ADDONCMDOPTIONS]
Commands (+ addons found in $PATH):

```

**Comment by Xitian9** [comment]
> Balance Sheet 2020-03-01, converted to cost, valued at period ends

This suggests that you are also doing cost conversion, not just valuation. Are you accidentally passing `--cost` or `-B` to hledger, possibly hidden within an alias? If you're using bash, try calling `alias hledger` to see if there are any extra options being passed.

**Comment by aimuz** [comment]
Yes I added the -B, they can't be mixed with each other?

**Comment by Xitian9** [comment]
They can, but they do two different things. The `-B` converts to cost, so your 2000 ADA is first converted to cost, which is $40. Once it's been converted to cost, there's no need to apply a valuation, so it remains at $40. What information do you want from this call?

**Comment by aimuz** [comment]
I will have multiple investments, such as
```
2020-01-01 opening balances
    assets:bank:checking                       $1000
    equity:opening/closing balances

2020-02-01
    assets:cc:ada:20200201                      2000 ADA @@ $40
    assets:cc:ddd:20200201                      2000 DDD @@ $40
    assets:bank:checking                        $-80

P 2020-02-01 ADA $0.02
P 2020-03-01 ADA $0.04
```
The price of DDD does not fluctuate

Do I need to add a price record at this point.

If not added, he will get the following output.

```
Balance Sheet 2020-03-01, valued at period ends

                        ||         2020-03-01
========================++====================
 Assets                 ||
------------------------++--------------------
 assets:bank:checking   ||            $920.00
 assets:cc:ada:20200201 ||             $80.00
 assets:cc:ddd:20200201 ||           2000 DDD
------------------------++--------------------
                        || $1000.00, 2000 DDD
========================++====================
 Liabilities            ||
------------------------++--------------------
------------------------++--------------------
                        ||
========================++====================
 Net:                   || $1000.00, 2000 DDD
```

**Comment by Xitian9** [comment]
You can get many different kinds of output, depending on what you're interested in. If you're interested in the current value of things which you purchased, you probably want `-V`, in which case yes, you must add a price directive. If you're interested in how much you paid for them at purchase, then use `-B`.

This might be helpful for figuring out what you want:
https://hledger.org/1.27/hledger.html#effect-of-valuation-on-reports

**Comment by aimuz** [comment]
Understood, I'll close the question

**Comment by aimuz** [comment]
Understood, I'll close the question

**Comment by chvp** [comment]
Note that you could also use [`--infer-market-prices`](https://hledger.org/1.27/hledger.html#--infer-market-prices-market-prices-from-transactions) instead of adding a price directive.
