### ISSUE TITLE
Accounts ordering in `balance`

### ISSUE THREAD

**Issue by alensiljak** [simonmichael/hledger#1948]
Related to #1752,

I'm comparing hledger`s vs ledger`s output of a simple balance command:

```
hledger bal > hledger-bal.txt
```
against
```
ledger bal --flat > ledger-bal.txt
```

Ledger seems to order the accounts in alphabetical order while hledger's output is a bit strange. It is mostly in alphabetical order, with some exceptions, making direct output file comparison impossible without manual interventions.

Some notable cases:
![image](https://user-images.githubusercontent.com/462445/200819693-e2239b6e-db32-4c61-8f05-7c8a034cdd21.png)

or
![image](https://user-images.githubusercontent.com/462445/200820179-19917829-a868-4c5e-a366-c007c48d73d7.png)

or
![image](https://user-images.githubusercontent.com/462445/200821845-2cfdc06a-45f6-4125-8110-9ecd3430c7db.png)
where all the sub-accounts are children of the same parent account.

Seems like the amount plays some role here?

Noting also that Ledger uses case-sensitive ordering in a way that, if account starts with a small-case letter, it will be ordered under a capital-case letter. This is a bit unintuitive to me.

I don't see any obvious instructions to specify an explicit ordering in either program (to simplify the comparison).

In the end, I'm not sure if this is intended or just "the way it is". While my concrete goal is to automate the comparison of the balances during book syntax adjustment (to make it work with both programs), I think it would still be useful to have the alphabetical ordering applying to all accounts.

**Comment by alensiljak** [comment]
In the [docs](https://hledger.org/1.27/hledger.html#simple-balance-report), it states

>Accounts are sorted by [declaration order](https://hledger.org/1.27/hledger.html#declaring-accounts) if any, and then alphabetically by account name.

**Comment by alensiljak** [comment]
This does not seem to apply to `Income:` accounts?

**Comment by alensiljak** [comment]
Assets, too, don't seem to follow this rule.

**Comment by alensiljak** [comment]
Liabilities:

![image](https://user-images.githubusercontent.com/462445/200840077-cd725568-9f0c-4bd6-9a7d-88c942011237.png)

although

![image](https://user-images.githubusercontent.com/462445/200840153-34cd630a-b4df-4106-a623-da374bacddfa.png)

**Comment by alensiljak** [comment]
Seems like the shorter account names (higher in the hierarchy) have advantage.

**Comment by alensiljak** [comment]
Adding a parent/grouping account fixes this last issue

![image](https://user-images.githubusercontent.com/462445/200844087-91852fac-f6ca-441b-9616-a3d168c18a91.png)

**Comment by simonmichael** [comment]
Correct, https://hledger.org/1.27/hledger.html#account-display-order is the relevant doc. Also for more complicated troubleshooting, `hledger accounts --positions` could help.
