### ISSUE TITLE
hledger on WinGet

### ISSUE THREAD

**Issue by zhzy0077** [simonmichael/hledger#1951]
It would be great if we can install hledger through WinGet https://github.com/microsoft/winget-cli

As of version WinGet 1.4(will be out soon), it supports zip-compressed portable exes, just like hledger: https://github.com/microsoft/winget-cli/issues/140

I sent a PR here to add it to WinGet: https://github.com/microsoft/winget-pkgs/pull/89472. Just send an issue here to check your opinion on this(this PR won't be checked in until 1.4 is out)

**Comment by simonmichael** [comment]
Thanks! 👍🏻

**Comment by zhzy0077** [comment]
PR completed. Thanks for making the amazing app!

**Comment by simonmichael** [comment]
Wonderful! Thanks for pushing that through. What new package page(s) and install command(s) might be useful to know about on the Install page ?

**Comment by zhzy0077** [comment]
![image](https://user-images.githubusercontent.com/8717471/217804542-e1ef4f37-66f6-4c18-b1ef-23439e4dad58.png)

this should be:
```pwsh
winget install hledger
```
or
```
winget install --id simonmichael.hledger
```

While I just discovered that unfortunately the version is out-dated on day one.  May I know how do we update other software sources? Are those all updated manually?

**Comment by simonmichael** [comment]
For the most part. Kind and hard-working packagers watch for my release announcements (or know the quarterly release schedule) and then there is a period of days or weeks while the various install methods up date and I gradually turn their badges green on the Install page.

**Comment by zhzy0077** [comment]
Sounds good. Let me do the same(testing a script that only happens once a few months looks hard to me). I will have a PR tomorrow to update winget package.
