### ISSUE TITLE
Wish: Handle importing csv when xact are inserted out of order

### ISSUE THREAD

**Issue by josephmturner** [simonmichael/hledger#1960]
CSVs from banks do not always append. Sometimes, new transactions are inserted before old ones, leading to problems with `hledger import`.

A simplified diff between an old and new CSV, where a transaction has been inserted before the prior latest entry:

```
+2022-12-06,vendor1,-10.00
+2022-12-05,vendor2,-20.00
+2022-12-05,vendor3,-42.00
+2022-12-03,vendor4,-50.58
 2022-12-01,vendor5,-25.24
+2022-12-01,vendor6,-36.00
 2022-11-30,vendor7,-12.07
 2022-11-30,vendor8,-17.76
```

`hledger import` inserts the `2022-12-01,vendor5,-25.24` xact twice in the journal file and does not insert the `2022-12-01,vendor6,-36.00` xact. Transactions inserted like this might even be from the prior day. 

In response to a similar issue, @adept mentioned [here](https://github.com/simonmichael/hledger/issues/1866#issuecomment-1249936502) that he wrote "a preprocessor that orders csv lines such that amounts + balances neatly tie together." My bank doesn't provide balance assertions.

[full-fledged-hledger](https://github.com/adept/full-fledged-hledger) solves this problem by fully re-generating journal files from CSVs which changed since the last time the `export.sh` script ran. As a consequence, the `full-fledged-hledger` solution means that you cannot directly edit `.journal` files, which I prefer over editing a `.rules` or [rules.psv](https://github.com/adept/full-fledged-hledger/wiki/Maintaining-CSV-rules) file.

Does anyone have ideas for a solution to this problem?

**Comment by josephmturner** [comment]
This is a duplicate of #1943. If I come up with a really good idea, I'll come back.

Thanks for making this project happen, Simon :)

**Comment by josephmturner** [comment]
Hack time!

```
#!/bin/bash
# This script is an alternative to the built-in hledger deduplication scheme for imported CSV files

# Keep in mind that this will only import lines which have been added, so you'll want to remove any skip rules from your rules file.

# For some reason, hledger import would not import entries from a CSV stored inside /tmp/ on my Debian 11 machine.
# Instead of using a tmp file, it might be preferable if hledger import accepted input from stdin.
mkdir -p ~/.tmp/

# The following git | perl snippets were copied from https://stackoverflow.com/a/25498422
# Checking if stdout is empty was copied from https://stackoverflow.com/a/54809333 (it requires bash)

# If any lines were removed, warn the user
if ! [[ -z $(git diff --color=always /path/to/import.csv | perl -wlne 'print $1 if /^\e\[31m-(.*)\e\[m$/') ]]; then
    echo "Warning: Lines were removed from the csv file!"
fi

# Write new lines to temp file
git diff --color=always /path/to/import.csv | perl -wlne 'print $1 if /^\e\[32m\+\e\[m\e\[32m(.*)\e\[m$/' > ~/.tmp/new-xacts.csv

# We don't want to use the .latest.FILE.csv. It might be good to prevent hledger from creating it.
rm -f ~/.tmp/.latest.new-xacts.csv

# Import!
hledger import --rules-file=/path/to/some.rules ~/.tmp/new-xacts.csv

# Clean up
rm -f ~/.tmp/.latest.new-xacts.csv ~/.tmp/new-xacts.csv
```

I'm curious to hear questions and comments.

**Comment by josephmturner** [comment]
In cases where this script is useful, it will produce a journal file with xacts which are out of chronological order. You can use `hledger print > your.journal` to fix it.

**Comment by josephmturner** [comment]
I updated the script to simplify the check for removed lines.

**Comment by josephmturner** [comment]
Updated again to accept positional args. The issue with this approach is that it's not idempotent.

**Comment by simonmichael** [comment]
Sounds like a nice hack ! And thanks for documenting it more at https://git.sr.ht/~breatheoutbreathein/hledger-import-new-xacts .

About "To prevent duplicate entries, it assumes that that your journal contains the same number of entries as the CSV you're importing from". I think this means you must keep a separate journal file for each CSV ? And does it assume that the CSV always covers the entire history ? Most bank CSVs go back only so far.

For people who need this, it would be cool to show some examples of the workflow in docs. Not idempotent, so when is it safe to run again ? That sort of thing.

**Comment by josephmturner** [comment]
Hello!

Simon Michael ***@***.***> writes:
> Sounds like a nice hack ! And thanks for documenting it more at
> https://git.sr.ht/~breatheoutbreathein/hledger-import-new-xacts .

Thanks!

> About "To prevent duplicate entries, it assumes that that your journal contains the same number of entries as the CSV you're
> importing from". I think this means you must keep a separate journal file for each CSV ? And does it assume that the CSV
> always covers the entire history ? Most bank CSVs go back only so far.

Unfortunately, the answer to both questions is yes. This works fine for
me since I already split my journals up by year and account.

> For people who need this, it would be cool to show some examples of the workflow in docs. Not idempotent, so when is it safe to
> run again ? That sort of thing.

I'd like to use this script for at least a few weeks to discover issues,
then write up some workflow examples.

Re: idempotency, it should be safe to run multiple times. I just added
some more commits: If the script thinks that running `hledger import`
would create duplicates, it lets the user edit the diff of between the
new CSV and old CSV. After that, the script performs the same check
again and either proceeds or exits.

**Comment by josephmturner** [comment]
The check to prevent duplicates works like this:
Count the lines in the CSV (assumed to contain the **total** number of transactions to date), the new transaction to be added, and the **current** journal length (with `hledger stat`), and an optional offset value (which contains the number of extra lines inside the CSV). If the first number doesn't equal the sum of the latter three, don't import.

**Comment by josephmturner** [comment]
I ironed out a couple more bugs, but I'm now coming back to the built-in deduplication method. My approach was already complicated and would have required passing a fifth argument to the script in order to handle importing files which weren't yet tracked by git.

This little project did let me dive a bit deeper into bash scripting. However if I were to do this over again, I'd prototype it with Emacs Lisp.

Perhaps someone else will find this interesting: https://git.sr.ht/~breatheoutbreathein/hledger-import-new-xacts
