### ISSUE TITLE
Hledger-web autocomplete hint for non-ascii account name 

### ISSUE THREAD

**Issue by ianzhuo** [simonmichael/hledger#1961]
When Add a transaction with non-ascii acount name, autocomplete hint shows some unidentify char.
![image](https://user-images.githubusercontent.com/1394735/208065888-e7cb7862-b5c7-46b6-80ac-887860cb9600.png)

**Comment by simonmichael** [comment]
Thanks for the report. Could you provide a minimal journal file that reproduces the problem ?

**Comment by simonmichael** [comment]
Actually, never mind, it's easy to reproduce:
```
account expenses:食物
```
and type "expenses" in an account field.

![Screen Shot 2022-12-16 at 06 55 43](https://user-images.githubusercontent.com/10144/208149393-70730cea-378b-4391-bddf-4b65499cfcbd.png)

**Comment by simonmichael** [comment]
toBloodhoundJson converts these account names from haskell Text to to javascript values for typeahead.js.

In #1663 for hledger-web 1.23, @ArsenArsen added [base 64 wrapping/unwrapping](https://github.com/simonmichael/hledger/blob/1.28/hledger-web/Hledger/Web/Widget/AddForm.hs#L182-L188) here to close an XSS vulnerability.

So currently the haskell is encoding account name `"expenses:食物"` as javascript code `atob("ZXhwZW5zZXM66aOf54mp")`, but javascript evaluates that as `"expenses:é£ç©"`.

I found that removing the b64wrap call fixes the bug (but of course re-opens the vulnerability, as can be seen with the example on #1663).

Is this a regression ? I haven't yet found a hledger-web version where this works correctly. Pre #1663, hledger-web-1.22 fails just slightly less badly:

![Screen Shot 2022-12-16 at 07 40 30](https://user-images.githubusercontent.com/10144/208164768-6ebf6588-0113-4814-926a-15573b546ec5.png)

Anyway - @ArsenArsen would you have any time to look at this, or thoughts ?

**Comment by ArsenArsen** [comment]
```js
const utf8textdecoder = new TextDecoder("utf-8");
function decode(b64) {
    const unb64 = window.atob(b64);
    const arr = new Uint8Array(unb64.length);
    for (let i = 0; i < arr.length; i++) {
        arr[i] = unb64.charCodeAt(i);
    }
    return utf8textdecoder.decode(arr);
}
```

Try this decoder instead of atob

**Comment by ArsenArsen** [comment]
Please do!  I'm a bit strapped for time lately, so it'd be a huge relief.

**Comment by simonmichael** [comment]
No problem @ArsenArsen. 

Conclusion from haskell chat:
> encodeBase64 uses Data.Text.Encoding.encodeUtf8 to go from Text -> byte sequence
...
> since encodeBase64 takes Text, I think it should kindly hint that decoding that text will also require utf8 decoding

Thank you both, for the bug report and the fix - this should make hledger-web more useful to a lot of people. The fix is in master, and a linux x64 binary at https://github.com/simonmichael/hledger/actions/runs/3717096718.

**Comment by ArsenArsen** [comment]
Indeed - Data.Text is always being encoded as UTF-8, and atob() apparently does not decode.  Odd, but it's solved now :)
