### ISSUE TITLE
Unexpected behaviour of balance assignments with transaction prices

### ISSUE THREAD

**Issue by SvyatoslavScherbina** [simonmichael/hledger#1965]
For the journal
```
2022-12-25
	assets:cash:eur  € 10
	equity

2022-12-26
	assets:cash:eur  = € 1 @ $1
	assets:cash:usd
```
`hledger print -x` shows
```
2022-12-25
    assets:cash:eur            € 10
    equity                    € -10

2022-12-26
    assets:cash:eur           € -10 = € 1 @ $1
    assets:cash:eur        € 1 @ $1 = € 1 @ $1
    assets:cash:usd             $-1
    assets:cash:usd            € 10

```
Which is unexpected and unparseable.

My `hledger --version`: `hledger 1.25, linux-x86_64`.

Originally reported here: https://matrix.to/#/!GYlETOAdUBSCcvnEMY:matrix.org/$j4e8tZDonFGhD-w6WaL35cOSj77Y3tFOWIUoFqZiIgw?via=libera.chat&via=matrix.org&via=defenestrate.it

Pretty useful investigation details are here: https://matrix.to/#/!GYlETOAdUBSCcvnEMY:matrix.org/$_VY4RAsOv4TwudKgRXequ1Y2yoLdoAWBAIuuN5b68Zo?via=libera.chat&via=matrix.org&via=defenestrate.it

**Comment by simonmichael** [comment]
The balance assertion should be shown on the second posting only, not the first. Now fixed in master. Good catch, thanks!
