### ISSUE TITLE
"make quickbench" does not work anymore

### ISSUE THREAD

**Issue by thdox** [simonmichael/hledger#197]
This is working fine:

    tools/simplebench -v -ftests/bench.tests hledger "ledger --no-pager"

But, trying to launch this from makefile is not working.

I have tried to put this in Makefile:

    BENCHEXES=hledger "ledger --no-pager"

And then: 

    $ make quickbench

    tools/simplebench -v -ftests/bench.tests hledger "ledger --no-pager"
    Using tests/bench.tests
    Running 2 tests 2 times with 2 executables at 2014-06-22 17:40:01.039481 UTC:
    1: hledger -f data/100x100x10.journal balance	[0.20s]
    2: hledger -f data/100x100x10.journal balance	[0.13s]
    1: ledger --no-pager -f data/100x100x10.journal balance (error 1)	[0.03s]
    2: ledger --no-pager -f data/100x100x10.journal balance (error 1)	[0.03s]

I got "(error 1)", and ledger is not run.

**Comment by thdox** [comment]
Hi Simon, I am unable, using new installation instructions using stack, to launch the bench for performance testing. "make bench" does not work.  What are the new instructions? Thanks

**Comment by simonmichael** [comment]
`stack bench`, or `stack bench hledger`, should work. I'll confirm and update the docs.

**Comment by thdox** [comment]
"stack bench hledger" did the work! :-) Definitely to be added to the documentation.

But how to compare with ledger ? "stack bench ledger" fails with "The following target packages were not found: ledger".

**Comment by simonmichael** [comment]
I've added http://hledger.org/developer-guide.html#run-benchmarks , with a note about tweaking bench --simplebench to compare multiple executables (add more arguments at the very end of bench.hs). 

There's also still the old tools/simplebench which you can compile and run directly, not yet redocumented.
Patches welcome!

**Comment by simonmichael** [comment]
And suggestions. Here's more background:

tools/simplebench.hs is a generic benchmarker of one or more executables (specified on the command line) against one or more sets of command-line arguments (specified in a file). It's convenient for interactive use and could be released as a standalone package.

hledger/bench/bench.hs is a benchmarking harness for the hledger package, integrated with cabal and stack and linking directly with the hledger code, which improves installability and automation. It also has a mode which links with the simplebench code and works like simplebench, but without the full command-line interface, so not as convenient. 

Maybe hledger/bench/bench.hs should expose more of tools/simplebench.hs' s CLI, and simplebench.hs can be retired ?

**Comment by thdox** [comment]
http://hledger.org/developer-guide.html#run-benchmarks is very good to detail how to use the tools. Thank you! It helped me.

One thing that I am still missing is how to compare with ledger? 
Maybe I have to understand (it is not clear for me) that this is only possible using the old tools/simplebench, but that one is not working anymore? As such this github issue #197 is probably still valid as this is about "make quickbench" and this was comparing hledger vs ledger performance.

And, I am missing too the way to generate file like "10000x1000x10.journal", that is for example something like "100000x1000x10.journal".

**Comment by simonmichael** [comment]
Added to the doc.

**Comment by simonmichael** [comment]
More updates, I think that should cover it.
