### ISSUE TITLE
How can I get the full account names in aregister?

### ISSUE THREAD

**Issue by Timonsc** [simonmichael/hledger#1980]
I've been trying to get the full accounts in de aregister command but it seems only possible to get the full accounts if I use the json output option.

I'd like to have the full accounts because I want to do some scripting with my data.

For example, with the command `hledger -f 2021.j areg Assets:Cash:ASN` I get the following output:
`2022-10-22 bs    Ex:Fo:Groceries    EUR-11.83    EUR1206.38`
Where I'd like to see:
`2022-10-22 bs    Expenses:Food:Groceries    EUR-11.83    EUR1206.38`

This also happens when I output it to txt and csv. Though I get the full accounts when I output it to JSON. Does anybody know why this works this way or how I can get the full accounts?

I'm on version 1.28 on Windows but the same happens on version 1.19.1 on Ubuntu WSL.

Thanks in advance,
Timon

**Comment by simonmichael** [comment]
This is [hard-coded in aregister](https://github.com/simonmichael/hledger/blob/18f264595bf472bb7a84acbaee374dd7d8122d15/hledger-lib/Hledger/Reports/AccountTransactionsReport.hs#L230) (except for JSON output as you said). Unlike register, aregister tries to show multiple account names on one line, and knowing that this will almost always get truncated, it tries to show more accounts more of the time by always showing abbreviated names.

The register command shows full names when there is space. You can ensure there is space by setting a large width with -w. But, it can also show multiple lines per transaction, which might be a problem for you.

aregister could be made similarly space-aware. I'd accept that change if someone wants to work on it. It may still not be ideal for consuming by script; eg multiple account names will be shown comma-separated, but account names can contain commas. JSON output may be the most reliably consumable here.

**Comment by simonmichael** [comment]
I'd also welcome a PR making it always show the full account names in csv output.

**Comment by Timonsc** [comment]
Thanks for your reply, you're right JSON is probably the way to go for scripting.
