### ISSUE TITLE
hledger web suggestion fails with unicode included

### ISSUE THREAD

**Issue by Hofer-Julian** [simonmichael/hledger#1981]
## Steps to reproduce

- Add a transaction with a Unicode character in your journal, e.g. "T-Shirt für Christian"
- Add a new transaction with `hledger web`
- The suggestion is broken, as can be seen in the screenshot. (No suggestion appears at all if the Unicode character is at the beginning)

```
$ hledger --version
hledger 1.27.1, linux-x86_64
```

![Bildschirmfoto vom 2023-01-10 16-55-14](https://user-images.githubusercontent.com/30049909/211601198-aab17dc0-cadf-4258-a5d6-07d2985b5de4.png)

**Comment by simonmichael** [comment]
Thank you! This is fixed in master and will be in next release (see also #1961 for a linux binary).

**Comment by Hofer-Julian** [comment]
Great to hear!

Thank you for your work :)
