### ISSUE TITLE
[💰10$ bounty] provide sourceName for `--forecast`ed periodic transactions

### ISSUE THREAD

**Issue by nobodyinperson** [simonmichael/hledger#1984]
Handy for [`hledger-edit`](https://pypi.org/project/hledger-utils) to also edit forecasted periodic transactions.

## Edit: Missing Context

```hledger
# journal.hledger

2023-01-01  Normal
    A      -1
    B       1

~ next quarter   Forecasted
    A      -1
    B       1
    
```

```bash
hledger -f journal.hledger print --forecast -O json | jq '.[].tsourcepos'
```

```json
[
  {
    "sourceColumn": 1,
    "sourceLine": 3,
    "sourceName": "/home/yann/code/hledger/journal.hledger"
  },
  {
    "sourceColumn": 1,
    "sourceLine": 6,
    "sourceName": "/home/yann/code/hledger/journal.hledger"
  }
]
[
  {
    "sourceColumn": 1,
    "sourceLine": 1,
    "sourceName": ""
  },
  {
    "sourceColumn": 1,
    "sourceLine": 2,
    "sourceName": ""
  }
]
```

☝️ In the above, the `sourceName`s of the forecasted transaction are empty and the positions are incorrect. It would be very helpful if they were set to the periodic transaction that created them. Expected output:

```json
[
  {
    "sourceColumn": 1,
    "sourceLine": 3,
    "sourceName": "/home/yann/code/hledger/journal.hledger"
  },
  {
    "sourceColumn": 1,
    "sourceLine": 6,
    "sourceName": "/home/yann/code/hledger/journal.hledger"
  }
]
[
  {
    "sourceColumn": 1,
    "sourceLine": 7,
    "sourceName": "/home/yann/code/hledger/journal.hledger"
  },
  {
    "sourceColumn": 1,
    "sourceLine": 10,
    "sourceName": "/home/yann/code/hledger/journal.hledger"
  }
]
```

**Comment by simonmichael** [comment]
It requires adding a source position field to PeriodicTransaction and saving it at parse time, as is done for Transaction, then using it when generating the transactions

**Comment by nobodyinperson** [comment]
@simonmichael Updated the OP with an example.

**Comment by chrislemaire** [comment]
I took a shot at fixing this issue.

**Comment by simonmichael** [comment]
Fixed by #1988, thank you @chrislemaire.

**Comment by nobodyinperson** [comment]
Perfect, I'll try it out and will then put the bounty into OpenCollective so that @chrislemaire can file an expense 👍

**Comment by simonmichael** [comment]
Or just send it directly ? 

Sending via OC would get it appearing in our project finances but would it take yet another hefty bite of fees ?

**Comment by nobodyinperson** [comment]
How much are the fees? Then I'll put them on top. I'd like to go via OpenCollective. What's it for otherwise 🙃

**Comment by simonmichael** [comment]
https://hledger.org/sponsor.html <https://hledger.org/sponsor.html> has some details of fees. I'm not certain, but the worst case I'm imagining is

You -> OC: 3% + 10%
OC -> bounty recipient: another 3%
or even a higher percentage for small transactions, because of minimum fees.

Certainly do it as you'd like - with small amounts involved, it's a good way to experiment and clarify things.

 <https://hledger.org/sponsor.html>General comment: people wanted to support our project when they donated. I'm a fan of Open Collective, but they (along with the others) sure take a lot of our money! Especially with small contributions. I think it's something we should be looking at.

**Comment by nobodyinperson** [comment]
Okay, then I'll bump my payment to OC by 20% to cover for the fees. I think it is important to keep things like this in the open and if the fees are the price we have to pay, then alright. LiberaPay is not suitable for this IIUC, they only do recurring payments. So OC with massive fees it is 😅

**Comment by nobodyinperson** [comment]
Okay I put 12USD into OC, @chrislemaire: time to [file a 10USD expense](https://opencollective.com/hledger/expenses/new) 💸

**Comment by chrislemaire** [comment]
> Okay I put 12USD into OC, @chrislemaire: time to [file a 10USD expense](https://opencollective.com/hledger/expenses/new) money_with_wings

Done! Thank you so much! :)

**Comment by nobodyinperson** [comment]
Thank **you** so much, now `hledger edit --forecast` also shows the matching transactions 🤩

**Comment by simonmichael** [comment]
OC payout approved, it happens twice weekly.
