### ISSUE TITLE
hledger-web: ctrl-c dosn't work

### ISSUE THREAD

**Issue by markokocic** [simonmichael/hledger#199]
When hledger-web is started without --server option, it is not possible to stop it using ctrl-c, although it says so when started.

**Comment by simonmichael** [comment]
Can anyone else find out more about this ?

**Comment by markokocic** [comment]
Now that I tried it again, it seems like Ctrl+C works again, both with and without --server flag.

**Comment by simonmichael** [comment]
Hurrah!
