### ISSUE TITLE
Option for including journals with a prefix account name

### ISSUE THREAD

**Issue by Pablo1107** [simonmichael/hledger#1994]
It would be great if you could include a journal file with an argument that prefix every account name with the string you choose, example:

### Example files
```
; business.journal
2023-01-01 opening
  assets:bank  1000 USD
  equity
```
```
; personal.journal
2023-01-01 opening
  assets:bank  2000 USD
  equity
```
```
; all.journal
include ./business.journal as business
include ./personal.journal as personal
```

### Example command output
```
$ hledger -f all.journal balance
    1,000.00 USD  business:assets:bank
   -1,000.00 USD  business:equity
    2,000.00 USD  personal:assets:bank
   -2,000.00 USD  personal:equity
----------------
               0
```

**Comment by simonmichael** [comment]
It's possible with https://hledger.org/dev/hledger.html#default-parent-account :
```
; all.journal
apply account business
include ./business.journal
end apply account
apply account personal
include ./personal.journal
end apply account
```

**Comment by Pablo1107** [comment]
> It's possible with https://hledger.org/dev/hledger.html#default-parent-account :
> 
> ```
> ; all.journal
> apply account business
> include ./business.journal
> end apply account
> apply account personal
> include ./personal.journal
> end apply account
> ```

Oh, didn't knew about that feature. Thanks Simon!
