### ISSUE TITLE
html output format for (at least) reg or areg

### ISSUE THREAD

**Issue by jmtd** [simonmichael/hledger#1996]
Quite simply I'd like to generate HTML 'reports' based on invocations of `reg` or `areg`. Perhaps others would like other commands, currently lacking html format output support, to have so.

**Comment by simonmichael** [comment]
You're right, reg and areg should support HTML output (all commands should support all output formats, more or less). Pull requests would be welcome.

**Comment by nobodyinperson** [comment]
You can script around it as a workaround, something along these lines:

```
hledger reg -O csv | turn_csv_into_markdown_table | pandoc -t html | weasyprint
```

**Comment by nobodyinperson** [comment]
Oh I smell a new cmd in `hledger-utils` here:

- read hledgers CSV with Python (easy)
- use `rich` to make nice colored table in the terminal (easy)
- export that to HTML ([easy](https://rich.readthedocs.io/en/stable/reference/console.html?highlight=Html#rich.console.Console.export_html))

**Comment by jmtd** [comment]
I’ve started hacking on this.
