### ISSUE TITLE
Expand --strict option to support tag validation

### ISSUE THREAD

**Issue by jman223** [simonmichael/hledger#1999]
**Issue**
The current implementation of the `--strict` option in hledger does not check to verify that tags have been declared before use.

Given the ease with which errors can be made when manually adding data, it would be nice to have hledger emulate ledger-cli and complain if it encounters a tag that has not been previously declared, just as we see with the current implementation of hledger's account and commodity checking.

**Current ledger-cli Output**

`Warning: "/home/xxxxx/register.ldg", line 24: Unknown metadata tag 'testtag'`

**Possible hledger Output**
```
hledger: Error: /home/xxxxx/register_2023.ldg:882:
882 | 2023-01-31 * TCCC - Interest  ; testtag:
    |                                 ^^^^^^^^
    |     Income:Interest:Bank Interest           $-0.12
    |     Assets:Banking:TCCC Savings              $0.12

Strict tag checking is enabled, and
tag "testtag" has not been declared.
Consider adding a tag directive. Example:

tag testtag
```

**Manual Workaround**
While I don't consider this to be a very good workaround (automatic notification would be much better), as long as one declares their [tags](https://www.ledger-cli.org/3.0/doc/ledger3.html#index-pre_002ddeclare-tag) (hledger won't complain), running the following command will at least provide insight into potential tag typos.

`hledger tags > /tmp/list1; grep ^tag accounts.txt | cut -c 5- | sort > /tmp/list2; comm -23 /tmp/list1 /tmp/list2`

**Comment by simonmichael** [comment]
Good news! I worked on it this morning. A bit more to do.

**Comment by simonmichael** [comment]
I was considering leaving it an optional check though (not part of --strict), as it's quite easy to accidentally create tags without meaning to. We'll see.

**Comment by simonmichael** [comment]
I have pushed a `tags` check to master:
- It is not enabled by -s; you must run `hledger check tags`
- The error messages don't show a very precise error region - if anyone has time to work more on that it's welcome (in JournalChecks, Errors modules).

Testers welcome!
