### ISSUE TITLE
Periodic Transactions from last day of the month

### ISSUE THREAD

**Issue by jeremy-j-ackso** [simonmichael/hledger#2005]
Would be great to have a Periodic Transaction syntax to specify from the end of the month that is agnostic to the number of days in the month.

I'm thinking either (or both) of something semi-textual (`last day`, `last-1 day`, `last -2 day`) or is ordinal with a `-` preceding it (`-1st day`, `-2nd day`, `-3rd day`).

This would allow me to specify a periodic transaction that always occurs on the last day of the month (or near the end of the month), without having to have individual periodic transaction blocks for the specific last day of each month in the year when creating my budget.

**Comment by simonmichael** [comment]
Agreed.

**Comment by avrahamappel** [comment]
+1

Incidentally, I have so far noticed that `every 31st day` will move the forecasted transaction back to the 30th if there is no 31st day of the month

Not sure if this is documented or not. (If not, I hope it doesn't break!)

**Comment by simonmichael** [comment]
Good tip for the FAQ maybe!

**Comment by avrahamappel** [comment]
@simonmichael Also, just wanted to take a moment to express my gratitude for this amazing tool, and the whole PTA ecosystem as well!
Just saving my poor programmer brain from having to muddle through spreadsheets is already a huge bonus!

**Comment by simonmichael** [comment]
Thanks @avrahamappel, glad it's helping.

**Comment by simonmichael** [comment]
I have added this to [docs](https://hledger.org/dev/hledger.html#more-complex-report-intervals) and FAQ now.
