### ISSUE TITLE
CSV import: support interpolating regex match groups into field templates

### ISSUE THREAD

**Issue by jmtd** [simonmichael/hledger#2009]
In CSV import rules, I want to incorporate portions of a CSV field into the hledger field that I am populating with the rules. Here are two supporting use-cases (interestingly these are both genuinely use-cases for me, and not contrived)

1. When importing credit card statement data, I have one repayment transaction each month. The real date of this transactions tends to be somewhere towards the middle of the date range of the statement, but on the human-readable statement, it is moved to the beginning of the period, cancelling out the carried-over balance, such that this month's transactions are against a zero-balance. I wish the same for my hledger data. This is achievable by hand with a comment tag, e.g. `some:account  £ X ; date:YYYY-MM-01`, but in order to do this automatically at import-time, I need to extract a sub-set of the CSV record's date field in a field match directive,  and reference that in the field assignment directive.

2. For some of my CSV imports, I wish to derive the hledger account for a posting from a field in the CSV. But I don't want the whole field, I only want a portion of it. ([This is actually for importing data from a separate ledger. The full worked use-case is described here](https://jmtd.net/log/hledger/separate/)).

In both cases, the solution is for *match groups* from the regular expression in a field matcher directive to be made available to be interpolated into the field assignment directive. For example (addressing use-case 1): 

```
if %date (....-..)-..
    comment2 date:\1-01
```

And (addressing use-case 2):

```
if %account1 liabilities:jon:(.*)
    account1 \1
```

Implementation note: interestingly part of the work required is already there: the field matcher regular expression already treats bracket-characters as denoting match groups (and not as literal brackets. I'm not sure how you would match a literal bracket, I haven't tested whether backspace-escapes work for example). I.e., `if (....)-(..)-(..)` matches `2022-12-31`.

**Comment by jmtd** [comment]
By coincidence, another problem I'm working on (providing different 'views' of a common set of transactions; handling when I owe or are owed from different pots e.g. personal family) would benefit from regex match tokens (method 2, above). I'm returning to my hacking

**Comment by alerque** [comment]
Yo thanks for this @jmtd, this is going to help cleanup some of my imports *a lot*!

**Comment by alerque** [comment]
Also it seems this covers at least of most of what I was requesting in #1061.
