### ISSUE TITLE
Ansi output is visible in shell when running `hledger`

### ISSUE THREAD

**Issue by olimorris** [simonmichael/hledger#2015]
When I run `hledger` in my terminal I'm seeing lots of ansi output:

<img width="824" alt="Screen Shot 2023-03-25 at 12 37 22@2x" src="https://user-images.githubusercontent.com/9512444/227717709-b10f8322-b1e0-4437-9f17-7a4805ee9624.png">

Additional information:

- Installed via Homebrew
- `hledger 1.29.1, mac-aarch64`
- I am using `Kitty 0.27.1` and  `tmux 3.3a`
- Running `hledger test` I see `All 220 tests passed (0.04s)`
- Running `echo $LANG` I see `en_GB.UTF-8`
- Trying this in the standard macOS Terminal.app also shows the same

**Comment by simonmichael** [comment]
Thanks for the report. If I understand rightly, you see this just running hledger in Apple's Terminal.app, with no tmux involved ?

As a temporary workaround you can `export NO_COLOR=1` or `alias hledger='hledger --color=no'`.

**Comment by olimorris** [comment]
> Thanks for the report. If I understand rightly, you see this just running hledger in Apple's Terminal.app, with no tmux involved ?
> 

That's correct. I'll try recreating in a GitHub Action too.

> 
> As a temporary workaround you can `export NO_COLOR=1` or `alias hledger='hledger --color=no'`.

👍🏼️

**Comment by simonmichael** [comment]
Hmm, I can't reproduce then. How about in iTerm if you have that ? I wonder if I configured Terminal in some way I've forgotten ? Can anyone else reproduce ?

**Comment by simonmichael** [comment]
Macos Monterey 12.6.2 here.

**Comment by simonmichael** [comment]
I see.. it works for me because I have `less` configured to render ANSI sequences (`LESS` environment variable contains `R`). Hmm. Seeing the bold headings is pleasant, but I'm not sure if we can safely detect when to show them.

**Comment by simonmichael** [comment]
Workaround for now: perhaps `export LESS=R$LESS` fixes it ? I use `export LESS=EFRSWX`.

**Comment by simonmichael** [comment]
We could:
- show no ANSI ever by default, and require an opt-in HLEDGER_COLOR=1 var to turn it on. People doing that would be responsible for also configuring their $PAGER to show ANSI.
- keep showing ANSI by default, and get https://github.com/pharpend/pager/pull/1 released or ship it ourselves, so when it is sent to $PAGER there's a better chance it will work (it would call `less -R` or `more`, both of which apparently show ANSI). People who have PAGER customised to something else might still see the problem.

**Comment by simonmichael** [comment]
I went with the third option - add R to $LESS (and $MORE) at startup. And added a https://hledger.org/dev/hledger.html#paging doc.

**Comment by olimorris** [comment]
Thanks so much for persevering with this. Can confirm that trying `export LESS=EFRSWX` fixed it for me!
