### ISSUE TITLE
SQL output has no primary key with SQLite

### ISSUE THREAD

**Issue by Allaman** [simonmichael/hledger#2017]
Hi, 

Recently, I played around with hledger's (comprehensive) export features and stumbled over a little issue with the sql output from `hledger print -O sql` 

```sh
hledger print -O sql | head -n 1
```
```sql
create table if not exists postings(id serial,txnidx int,date1 date,date2 date,status text,code text,description text,comment text,account text,amount numeric,commodity text,credit numeric,debit numeric,posting_status text,posting_comment text);
```

Though, this output will create a valid sqlite database with `hledger print -O sql | sqlite3 foo.db` the `id` column is `NULL` due to `id serial` [not known to SQLite](https://stackoverflow.com/a/19726143). For SQLite, one would use `id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL`. 

When I run `hledger print -O sql > test.sql, change the first line to 
```sql
create table if not exists postings(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,txnidx int,date1 date,date2 date,status text,code text,description text,comment text,account text,amount numeric,commodity text,credit numeric,debit numeric,posting_status text,posting_comment text);
```
and then run `cat test.sql | sqlite3 foo2.db` there is an `id` column with unique IDs.

The code is apparently [here](https://github.com/simonmichael/hledger/blob/master/hledger/Hledger/Cli/Commands/Print.hs#L153), but I have no clue how to implement this while remaining compatibility with MySQL and PostgreSQL. 

A possible workaround might be to clarify this limitation in the [docs](https://hledger.org/dev/hledger.html#sql-output)? 

> SQL output is expected to work with sqlite, MySQL and PostgreSQL

Version: hledger 1.29.1, mac-aarch64

**Comment by simonmichael** [comment]
It doesn't seem worth adding a special output format for SQLite - perhaps documentation is best ?

**Comment by Allaman** [comment]
Yeah, makes absolutely sense. 
`hledger print -O sql | sed 's/id serial/id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL/g' | sqlite3 foo.db` works for me
