### ISSUE TITLE
Release download issue with 1.29.1 tag

### ISSUE THREAD

**Issue by desaiuditd** [simonmichael/hledger#2021]
Commands to download new release binary for 1.29.1 is not working.

With `curl`
```
⇒ curl -LOC- https://github.com/simonmichael/hledger/releases/download/1.29.1/hledger-linux-x64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     23      0 --:--:-- --:--:-- --:--:--    24
docker-hledger|main⚡ ⇒ cat hledger-linux-x64.zip
Not Found%
```

With wget
```
⇒ wget https://github.com/simonmichael/hledger/releases/download/1.29.1/hledger-linux-x64.zip
--2023-04-02 12:46:16--  https://github.com/simonmichael/hledger/releases/download/1.29.1/hledger-linux-x64.zip
Resolving github.com (github.com)... 20.248.137.48
Connecting to github.com (github.com)|20.248.137.48|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-02 12:46:16 ERROR 404: Not Found.
```

I noticed that the download urls for these assets in 1.29.1 releases are bit off.

<img width="901" alt="image" src="https://user-images.githubusercontent.com/2236554/229328322-e1f7f9e9-1adb-47d0-8959-c4df945f8e44.png">

The url there is `https://github.com/simonmichael/hledger/releases/download/hledger-web-1.29.1/hledger-linux-x64.zip` instead of `https://github.com/simonmichael/hledger/releases/download/1.29.1/hledger-linux-x64.zip`.

Is that expected? Will all new releases now onwards will be under `hledger-web-` prefix, instead of just tag version number?

**Comment by simonmichael** [comment]
No, not expected, I will investigate. Thanks for letting me know!

**Comment by simonmichael** [comment]
This seems fixed now; the github release was just attached to the wrong tag.
