### ISSUE TITLE
report month period calculation

### ISSUE THREAD

**Issue by jbrodriguez** [simonmichael/hledger#2022]
i run this report

`hledger is -f all.journal -AVT -2 -M -c '$1,000.00' date:2022/3/31- date:-2023/3/31`

the issue is with the month periods, it's calculating these "months"

- 2022-03-31..2022-04-29
- 2022-04-30..2022-05-30
- 2022-05-31..2022-06-29

and so on

any suggestion on making the repot month correspond to a calendar month ?

**Comment by jbrodriguez** [comment]
looks like i should use `-p 'monthly from 2022/03` right ?

**Comment by simonmichael** [comment]
It's related to this change in 1.29: https://hledger.org/release-notes.html#hledger-129

`date:2022/3/31- date:-2023/3/31` looks like an odd date range.. that was specifying a report period of 2022-03-31 to 2023-03-30 inclusive.

`date:2022/3- date:-2023/4` specifies 2022-03-01 to 2023-03-31 inclusive (ie, 13 months). 

April 1 to march 31 inclusive would be `-p 2022/4 to 2023/4`, or `date:202204-202304` (lots of ways to write it).

**Comment by jbrodriguez** [comment]
thanks simon, yes, i'm re-reading the reporting section on time periods, quite a few ways to get a similar result :)

i do want 13 months sometimes, to have a year over year comparison (did i do better/worse, etc), but yes, i'll improve how i'm writing those date params
