### ISSUE TITLE
Autoposting rules in a journal change order of balance assertions

### ISSUE THREAD

**Issue by ShrykeWindgrace** [simonmichael/hledger#2025]
I have the following journal with an autoposting rule:
```ledger
= Expenses:Transport
    (Budget:Transport)  *-1


2023-01-01 Init
    Assets       367.45 EUR
    Init

2023-01-30 Amazon
    Assets       -257.59 EUR = 109.86 EUR  ; date: 2023-02-01
    Assets:Temp      257.59 EUR

2023-02-03 Ebay
    Assets               -30.25 EUR ; date: 2023-02-04
    Expenses:Gifts            29.95 EUR
    Expenses:Fees        0.30 EUR
    Assets               == 79.61 EUR
```
The `hledger bal` passes with flying colors, yet `hledger bal --auto` fails with
```
   | 2023-02-03 Ebay
   |     Assets              -30.25 EUR  ; date: 2023-02-04
   |     Expenses:Gifts       29.95 EUR
   |     Expenses:Fees         0.30 EUR
17 |     Assets                       0 == 79.61 EUR
   |                                    ^^^^^^^^^^^^

This balance assertion failed.
In account:    Assets
and commodity: EUR                             (no other commodities allowed)
this balance was asserted:     79.61
but the calculated balance is: 109.86
a difference of:               -30.25
```
even though there are no autopostings issued by the rewrite rule.

At the same time, if I delete the rule and keep only 
```ledger
2023-01-01 Init
    Assets       367.45 EUR
    Init

2023-01-30 Amazon
    Assets       -257.59 EUR = 109.86 EUR  ; date: 2023-02-01
    Assets:Temp      257.59 EUR

2023-02-03 Ebay
    Assets               -30.25 EUR ; date: 2023-02-04
    Expenses:Gifts            29.95 EUR
    Expenses:Fees        0.30 EUR
    Assets               == 79.61 EUR
```
both `hledger bal` and `hledger bal --auto` pass.

I am on
```
hledger 1.27.1, linux-x86_64
```

I'll try to test on a current master.

The output of
```
$ hledger reg 'Assets$' -I
2023-01-01 Init                              Assets                               367.45 EUR    367.45 EUR
2023-02-01 Amazon                            Assets                              -257.59 EUR    109.86 EUR
2023-02-03 Ebay                              Assets                                        0    109.86 EUR
2023-02-04                                   Assets                               -30.25 EUR     79.61 EUR
```
is identical to the output of `hledger reg 'Assets$' --auto -I`. I'd say that toggling `--auto` should not change the fail status of `hledger bal`.

**Comment by simonmichael** [comment]
Good catch! I agree, that seems to be going wrong somehow.

**Comment by simonmichael** [comment]
Notes:

This transaction is balanced but the assertion fails, correctly because of the posting date:
```
2023-02-03
    Expenses    1
    Assets     -1        ; date: 2023-02-04
    Assets      0 = -1
```

But if we make the last amount implicit, both transaction balancing and the assertion succeed, which is wrong - one or the other should fail depending on what amount is inferred (I would expect -1):
```
2023-02-03
    Expenses    1
    Assets     -1        ; date: 2023-02-04
    Assets        = -1
```

If we add any auto posting rule and run with --auto, it fails again:
```
2023-02-03
    Expenses    1
    Assets     -1        ; date: 2023-02-04
    Assets        = -1

= an auto posting rule
```

**Comment by simonmichael** [comment]
Fixed: postings with balance assignments were being processed in parse order; now they are processed in posting date order.So now all three cases above fail, for correct reasons, and --auto does not affect them. Thanks for the report!

**Comment by simonmichael** [comment]
Just for the record, I feel it's probably still possible to confuse it by having two transactions, each with multiple posting dates and assertions/assignments, which overlap each other's dates. I don't think that should be expected to work, as we process each transaction separately. But if someone wants to work up a test case, to see if the results are reasonable, that would be welcome.

**Comment by ShrykeWindgrace** [comment]
Thanks for the prompt fix!
