### ISSUE TITLE
CVS Import: different date for transaction and for keeping state

### ISSUE THREAD

**Issue by chrpinedo** [simonmichael/hledger#2026]
I download a CSV from my bank with two dates: transaction date and value date.
- transaction date (1st field of my CSV) is when the amount is charged in my account
- value date (2nd field of my CSV) is when the expense really happened

So, I have something like this:
```
18-04-2023;08-04-2023;something;-1,17;EUR;127,61;EUR;
19-04-2023;19-04-2023;another thing;100,00;EUR;227,61;EUR;
20-04-2023;10-04-2023;lala lalala;-2,72;EUR;224,89;EUR;
20-04-2023;20-04-2023;give me the money;100,00;EUR;324,89;EUR;
21-04-2023;16-04-2023;oh no more expenses;-2,30;EUR;322,59;EUR;
```

I would like to track transactions with the "value date" because it is when the transaction really happened. However, if i do that, the keep state functionality of "hledger import" fails, because the value date is quite random, it is not increased sequentially. I need to select the "transaction date" so that keep state functionality can work but then transactions lacks of right date.

I think it could be quite advisable to be able to choose one date for keeping state (the transaction date) and one date for the date of trasactions to create (the value date).

Regards,

**Comment by simonmichael** [comment]
@chrpinedo, it sounds like you could 

- use the secondary date feature, with https://hledger.org/dev/hledger.html#date2-field
- or (recommended) give the bank posting the other date,  setting its date: tag with a commentN assignment. https://hledger.org/dev/hledger.html#posting-dates

**Comment by chrpinedo** [comment]
I really like your second proposal, to use a posting date with commentN.

However, after testing, I discovered one issue. I use a different time format in my ledger file (yyyy-mm-dd) and in the downloaded CSV file (dd-mm-yyy). So if I use the `comment2 date:%valuedate`, it converts to `; date:dd-mm-yyyy`, which is not the date format of my ledger file. It should generate `; date:yyyy-mm-dd`.

**Comment by simonmichael** [comment]
Ah, that does sound like a problem, I remember it discussed in another issue/WIP branch somewhere. For now you might have to preprocess your CSV to normalise the dates.

**Comment by simonmichael** [comment]
Now the WIP branch should be visible at 18831261b.

**Comment by simonmichael** [comment]
And here's the issue: #1983. Perhaps we can close this one in favour of that.

**Comment by chrpinedo** [comment]
Thanks @simonmichael for your WIP.

In the meanwhile, as you suggested,  it is quite easy to preprocess the CSV with `sed`. The key is to have the same date format in the CSV file than in the ledger file before importing it:

`sed -i  -e 's/\([0-9]\{2\}\)-\([0-9]\{2\}\)-\([0-9]\{4\}\)/\3-\2-\1/g' $@`
