### ISSUE TITLE
hledger fails to resolve implicit posting in a three commodity trade where costs are specified with @@

### ISSUE THREAD

**Issue by rsnel** [simonmichael/hledger#2038]
Here is a minimal example, note that the last posting only has a balance assertion:

    2023/01/02 * Trade
        Assets                  AAA-1.1 @@ CCC 2
        Assets                  BBB-1.2 @@ CCC 3
        Expenses:Fees           CCC 0.1
        Assets                  = CCC 4.9

hledger says:

    hledger: Error: /home/user/journal:1-5:
    1 | 2023-01-02 * Trade
      |     Assets                AAA-1.1
      |     Assets                BBB-1.2
      |     Expenses:Fees         CCC 0.1
      |     Assets                CCC 4.9 = CCC 4.9
    
    This multi-commodity transaction is unbalanced.
    The real postings' sum should be 0 but is: AAA-1.1, BBB-1.2, CCC 5.0
    Consider adjusting this entry's amounts, adding missing postings,
    or recording conversion price(s) with @, @@ or equity postings.

Notice that it acts like the '@@'s are not there. However, it correctly infers the "CCC 4.9". When I add "CCC 4.9"
before the balance assertion explicitly, then hledger accepts the transaction.

    2023/01/02 * Trade
        Assets                  AAA-1.1 @@ CCC 2
        Assets                  BBB-1.2 @@ CCC 3
        Expenses:Fees           CCC 0.1
        Assets                  CCC 4.9 = CCC 4.9

I think it should also accept the first example.

**Comment by simonmichael** [comment]
> On May 27, 2023, at 08:19, rsnel ***@***.***> wrote:
> Here is a minimal example, note that the last posting only has a balance assertion:
> 

Thanks Rik - I got that one, but I meant an example of

> hledger didn't like ... balance assignments to '0' where hledger seems to require a commodity to be specified to work as expected

I kind of know what that is, but it would save time to see the different Ledger behaviour your journal was relying on.

**Comment by rsnel** [comment]
Thanks for your quick fix!

Here is an example of the other issue:

    2023/01/01 * Opening Balances
        Assets:ToZero           EUR 2
        Equity:Opening Balances
    
    2023/01/02 * Testcase
        Assets:Fromzero    EUR 2
        Assets:ToZero           = 0

hledger says:

    5 | 2023-01-02 * Testcase
      |     Assets:Fromzero           EUR 2
      |     Assets:ToZero                 0 = 0
    
    This transaction is unbalanced.
    The real postings' sum should be 0 but is: EUR 2
    Consider adjusting this entry's amounts, or adding missing postings.

When I change "= 0" to "= EUR 0" the file is accepted by hledger. ledger accepts both versions.

And another difference between Ledger 3.2.1-20200518 and hledger

    2023/01/01 * AssertFail
        Assets:To               EUR 5
        Assets:From             = EUR 0

hledger correctly gives an error but ledger accepts it, so I had a couple of wrong balance assertions in my ledger.dat without knowing it. This is clearly not a problem of hledger.

**Comment by simonmichael** [comment]
> On May 27, 2023, at 10:41, rsnel ***@***.***> wrote:
> 2023/01/02 * Testcase
> 
>     Assets:Fromzero    EUR 2
>     Assets:ToZero           = 0
> hledger says:
> 
> 5 | 2023-01-02 * Testcase
>   |     Assets:Fromzero           EUR 2
>   |     Assets:ToZero                 0 = 0
> 
> This transaction is unbalanced.
> The real postings' sum should be 0 but is: EUR 2
> Consider adjusting this entry's amounts, or adding missing postings.
> When I change "= 0" to "= EUR 0" the file is accepted by hledger. ledger accepts both versions.
> 

Ah, right. I can say what hledger is doing there:

- It treats the no-symbol commodity as a distinct commodity, like any other
- <no symbol> 0 is posted to Assets:ToZero to satisfy the balance assignment
- So the resulting transaction balance is EUR 2 + <no symbol> 0.

I'm not sure how ledger is interpreting that (how do you get ledger print to show all amounts ?)

> And another difference between Ledger 3.2.1-20200518 and hledger
> 
> 2023/01/01 * AssertFail
>     Assets:To               EUR 5
>     Assets:From             = EUR 0
> hledger correctly gives an error but ledger accepts it, so I had a couple of wrong balance assertions in my ledger.dat without knowing it. This is clearly not a problem of hledger.
>

**Comment by simonmichael** [comment]
> On May 27, 2023, at 11:58, Simon Michael ***@***.***> wrote:
> 
> 
> 
> > On May 27, 2023, at 10:41, rsnel ***@***.***> wrote:
> > 2023/01/02 * Testcase
> > 
> > Assets:Fromzero EUR 2
> > Assets:ToZero = 0
> > hledger says:
> > 
> > 5 | 2023-01-02 * Testcase
> > | Assets:Fromzero EUR 2
> > | Assets:ToZero 0 = 0
> > 
> > This transaction is unbalanced.
> > The real postings' sum should be 0 but is: EUR 2
> > Consider adjusting this entry's amounts, or adding missing postings.
> > When I change "= 0" to "= EUR 0" the file is accepted by hledger. ledger accepts both versions.
> > 
> 
> Ah, right. I can say what hledger is doing there:
> 
> - It treats the no-symbol commodity as a distinct commodity, like any other
> - <no symbol> 0 is posted to Assets:ToZero to satisfy the balance assignment
> - So the resulting transaction balance is EUR 2 + <no symbol> 0.
> 
> I'm not sure how ledger is interpreting that (how do you get ledger print to show all amounts ?)


I'd say ledger is wrong here also; balancing the transaction and saying that Assets:ToZero's balance is zero are in conflict. (The parent account, Assets, does have a zero balance.)

**Comment by rsnel** [comment]
Ledger interprets "= 0" as a special assertion: https://ledger-cli.org/doc/ledger3.html#Special-assertion-value-0

which is weird, because it also allows normal amounts without a symbol,  I agree that hledger is correct.

ledger bal should show everything, the '0' just doesn't 'count'

This file fails in ledger but works as expected in hledger

    2023/01/01 * Opening Balances
        Assets:ToZero           EUR 2
        Assets:ToZero           5
        Equity:Opening Balances

    2023/01/02 * Testcase
        Assets:Fromzero         EUR 2
        Assets:ToZero           = 2

**Comment by simonmichael** [comment]
See also #2039. Fixed in d19d8664.
