### ISSUE TITLE
balance --gain does not respect commodity display style

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#2048]
In my testing `hledger bal --gain` seems to show more decimal places than `hledger bal`.

**Comment by phobo3s** [comment]
![image](https://github.com/simonmichael/hledger/assets/47847184/36d5eea2-0e4f-44ce-b705-4e5482f4eb3e)
this works.
![image](https://github.com/simonmichael/hledger/assets/47847184/47a1e833-8703-4907-96db-63eb5700ef7c)
But this doesn't.
notice that the account with the name "TI3" at the and is working properly.
in the ledger file the commodity name is written like this 
![image](https://github.com/simonmichael/hledger/assets/47847184/6173663d-a708-4d55-a4d8-4da5c7237605)
issue can be something from this maybe?

**Comment by phobo3s** [comment]
YES! it is perfectly solved. 
thank you for your magic.
Now gain command is respects commodity display style.
![image](https://github.com/simonmichael/hledger/assets/47847184/dfdd1780-7e31-4701-9f17-b390ce37c594)
if i don't give commodity display style in command it still uses commodity style in ledger file 
![image](https://github.com/simonmichael/hledger/assets/47847184/a44a419f-4077-4542-9d08-5cf5e9f76b6f)

looks perfect to me.
