### ISSUE TITLE
Conversion postings must not have a cost for stocks data

### ISSUE THREAD

**Issue by vivekkalyan** [simonmichael/hledger#2055]
Using hledger version 1.29.

```
# example.journal
2022-08-16 XXXX
    assets:bank:xxx:usd                          USD 10000
    equity:trading:stocks:usd:xxx               USD -10000
    equity:trading:stocks:xxx:usd     100 xxx @@ USD 10000
    assets:stocks:xxx                -100 xxx @@ USD 10000

```

`hledger bal --file example.journal`

```
Conversion postings must not have a cost:
    equity:trading:stocks:xxx:usd    100 xxx @@ USD 10000
```

These transactions were working properly before so im not very sure why they don't work now. Tried doing `100 xx @ USD 100` but get the same error.

Should I change the way I deal with stocks data?

**Comment by vivekkalyan** [comment]
this might be a duplicate of https://github.com/simonmichael/hledger/issues/2045?

**Comment by simonmichael** [comment]
Thanks for the report. I see that this was accepted by hledger 1.28:
```
$ hledger-1.28 print
2022-08-16 XXXX
    assets:bank:xxx:usd                          USD 10000
    equity:trading:stocks:usd:xxx               USD -10000
    equity:trading:stocks:xxx:usd     100 xxx @@ USD 10000
    assets:stocks:xxx                -100 xxx @@ USD 10000
```
Cost conversion nowadays hides the equity postings, but in 1.28 it didn't:
```
$ hledger-1.28 print -B
2022-08-16 XXXX
    assets:bank:xxx:usd                 USD 10000
    equity:trading:stocks:usd:xxx      USD -10000
    equity:trading:stocks:xxx:usd       USD 10000
    assets:stocks:xxx                  USD -10000

```
Bottom line I think current hledger is doing the right thing - you shouldn't repeat the @@ cost on equity postings, which are supposed to be the general DEB alternative to our PTA @@ notation. So if you want to write both equity postings and @@ cost, just write the cost once:
```
2022-08-16 XXXX
    assets:bank:xxx:usd                    USD 10000
    equity:trading:stocks:usd:xxx         USD -10000
    equity:trading:stocks:xxx:usd                100 xxx
    assets:stocks:xxx                           -100 xxx @@ USD 10000
```

**Comment by simonmichael** [comment]
I rewrote https://hledger.org/dev/hledger.html#cost-reporting for clarity. Assuming this can be closed.
