### ISSUE TITLE
web: Emoji's not rendered correctly in the quick-search

### ISSUE THREAD

**Issue by silky** [simonmichael/hledger#2061]
Emoji's are actually rendered fine in the UI in most places; i.e.

![image](https://github.com/simonmichael/hledger/assets/129525/4b681dc9-1a9f-46c1-b9f1-fad44ace61cd)

but in the quick-search for some reason it fails to render well: 

![image](https://github.com/simonmichael/hledger/assets/129525/c00e6474-762f-4157-b6ca-a28b1e1ea3ef)

It seems like emojis work fine otherwise.

Just to be sure, the account is defined like so:

```
account assets:monzo:savings 💰
```

**Comment by silky** [comment]
I've looked into this, and it isn't happening in the latest version of hledger (1.30.1) and hledger-web (1.30), so i'll just consider it resolved :)

**Comment by simonmichael** [comment]
Great!
