### ISSUE TITLE
Periodic transaction does not print

### ISSUE THREAD

**Issue by gloriouslyawkward** [simonmichael/hledger#2064]
hledger is not showing period transactions prior to tomorrow. How do I fix this?

hledger version hledger 1.30-g94fe8b21c-20230601, windows-x86_64

I have a periodic transaction that looks like this (dollar amounts removed):

```
~ biweekly from 2023-01-04  Optum Services Inc.
  Assets:Checking  
  Income:Regular  
  Expenses:Taxes:Federal  
  Expenses:Taxes:Medicare  
  Expenses:Taxes:Social Security  
  Expenses:Insurance:Dental  
  Expenses:Insurance:Medical  
  Expenses:Insurance:Medical  
  Expenses:Insurance:Vision  
```
the tranasction _should_ triger on 2023/07/19, but it's not when using the `--forecast` option. Instead, this happens (note the start date for the period!):

```
hledger print --forecast -p "2023/07/18 to 2023/08/03" --debug=2
journalEndDate: Just 2023-07-20
forecastspan: DateSpan 2023-07-20..2023-08-02
.
.
.
2023-08-02 Optum Services Inc.
```
```

**Comment by gloriouslyawkward** [comment]
Not a bug; I have transactions dated today. This really needs to be changed.

**Comment by simonmichael** [comment]
You can always force the forecast period to avoid the default behaviour, eg:
hledger print --forecast=today.. -p thisquarter

**Comment by simonmichael** [comment]
How would you change it - always start forecasts from today by default ?

The rules are at https://hledger.org/dev/hledger.html#forecast-period-in-detail and they are, 
necessarily, a bit complicated. Here are the forecast start date rules, numbered for reference:

> The forecast period starts on:
> 
> 1. the later of
>   1.1. the start date in the periodic transaction rule
>   1.2. the start date in --forecast's argument
> 2. otherwise (if those are not available): the later of
>   2.1. the report start date specified with -b/-p/date:
>   2.2. the day after the latest ordinary transaction in the journal
> 3. otherwise (if none of these are available): today.

I'm guessing you would propose to drop 2.2, so in your example it would have chosen 3 (start forecasting from today) instead. If you had already recorded or imported that actual transaction from the bank today, the forecast would overlap and this transaction would be duplicated in reports. Isn't that suboptimal ? Without 2.2 there'd be no automatic way to start forecasting after latest actual transaction, you'd always have to be on guard for overlaps.

**Comment by gloriouslyawkward** [comment]
The `forecast=today` instruction is exactly what I'm looking for.
