### ISSUE TITLE
web: Plugins or some sort of customisation approach for hledger-web

### ISSUE THREAD

**Issue by silky** [simonmichael/hledger#2066]
I'd like to have a few graphs and links on the "web" version of hledger, so they are easily accessible to me.

There are at least a few potential ideas of how to do this:

- Maybe I could optionally provide a template that the main HTML is rendered in; this would work for simple links, HTML/CSS changes,
- Maybe I could provide both _client-side_ code _and_ "server-side" code; (not that dire, given both are running on my computer anyway), and that why I could do some interesting computations, if I wished it.

An example could be then I could have a link to a dashboard, something like [vegalite](https://github.com/xitian9/hledger-vega1), or otherwise.

As it stands, I'll have to build this as a stand-alone app myself, and run both; which seems mildly inconvenient.

**Comment by simonmichael** [comment]
Yes there a lot of possibilities and potentially a lot of work. I usually tell myself to at least separate the tasks of building a useful web app/web report, and figuring out how to integrate it nicely. 

https://hledger.org/scripting.html#plugins has some high level thoughts on plugins, no ideas for hledger-web yet. 

hledger-web is a rather dense and tight-knit haskell web app. Probably it's not the easiest to work with and (like all haskell apps) not obviously easy to extend in a dynamic runtime way.

**Comment by silky** [comment]
Yes, fair enough.

I suppose at a first-pass just merely the ability to configure the template it would use for rendering, and an ability to configure custom js, + an arbitrary binary callback would go a long way

But I imagine that's probably a bit too much work to be of interest.

So, fair enough.

**Comment by silky** [comment]
In my head I have in mind the pandoc-ish model for, how it does templating of, say, latex generation, or whatever the case may be.

**Comment by simonmichael** [comment]
/me thinks: embed lua (or, janet) and allow custom reports to be defined that way..
