### ISSUE TITLE
--rules-file doesn't do anything

### ISSUE THREAD

**Issue by aodhan-domhnaill** [simonmichael/hledger#2067]
The `--rules-file` option isn't being interpreted. `abnamro.rulesasdasdasd` does not exist, but there is only an error about tabs.

```
$ hledger import -f ~/Downloads/TXT2307126.TAB --rules-file abnamro.rulesasdasdasd
hledger: Error: /home/aidan/Downloads/TXT2307126.TAB:1:10:
...

unexpected tab
expecting date separator or digit
```

I added the `asd` garbage at the end because I couldn't figure out why my rules file wasn't being read.

**Comment by aodhan-domhnaill** [comment]
Looks like renaming the file to `.tsv` fixed this. Still seems like a weird setup. I would have expected that having `separator` specified in the rules file would fix this automatically.

**Comment by simonmichael** [comment]
Thanks for the report. hledger always shows just the "first" error. This might not be what you think because of Haskell's laziness. In this case because of the unfamiliar file extension it tries to parse the file as a journal . Add a csv: prefix to the file argument to force the csv reader and see a more useful error.

**Comment by simonmichael** [comment]
https://hledger.org/1.30/hledger.html#data-formats is the relevant doc. Basically, file extension is most important and the rules file was never consulted.

**Comment by simonmichael** [comment]
I think we can close this: it is working as documented, ie when encountering an unknown file extension like .TAB we try only `journal` format. We used to try all builtin formats in turn, but that can cause more confusion.
Better UX proposals are still welcome.
