### ISSUE TITLE
broken link to dev.md in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jmtd** [simonmichael/hledger#2078]
https://github.com/simonmichael/hledger/blob/ff730f775ba0cc6fc855a9767268c5094ddca1fd/doc/CONTRIBUTING.md?plain=1#L29

**Comment by simonmichael** [comment]
Thanks, but all of these docs are intended to be read on the website, eg at https://hledger.org/CONTRIBUTING.html . I couldn't make all links work on github as well - sorry.
