### ISSUE TITLE
Timedot: Decimal rounding issue

### ISSUE THREAD

**Issue by lstellway** [simonmichael/hledger#2096]
### Description

While playing with the `.timedot` format, I noticed a rounding error. Here's a simple example to reproduce.

Example file:

```txt
; test.timedot
2023-10-03
Test Account  15m
```

Command used to print the ledger:

```sh
$ hledger print -f test.timedot
# 2023-10-03 *
#     (Test Account)    0.24999999999999999
```

Version info:

```sh
$ hledger --version
# hledger 1.31, mac-aarch64
```

### Resources

- [Original Message](https://matrix.to/#/!GYlETOAdUBSCcvnEMY:matrix.org/$Lg7usJ3ut-bERnKp297yAcijDDTYxwtPICEvd_usrvc?via=libera.chat&via=matrix.org&via=vanpetegem.me) _(Matrix)_
- I imagine it is an [arbitrary precision](https://en.wikipedia.org/wiki/Arbitrary-precision_arithmetic) float issue

**Comment by simonmichael** [comment]
I have pushed a fix, which should land in master soon. Thanks for the report!

**Comment by simonmichael** [comment]
More details: this affected quantities with a number and a unit (like `15m`). Now after conversion to hours they are rounded to two digits.

**Comment by lstellway** [comment]
Beautiful, thank you!
