### ISSUE TITLE
hledger-web cannot serve on 0.0.0.0

### ISSUE THREAD

**Issue by klockeph** [simonmichael/hledger#2099]
If I run `hledger-web --serve --host 0.0.0.0` on my Raspberry Pi to expose web-hledger on all interfaces (in my case WiFi and VPN), some things break:

Most notably, opening `192.168.1.<Pi>:5000` redirects to `0.0.0.0:5000/journal`.
Navigating to the journal directly does not help, since it still tries to load additional resources from `0.0.0.0` - the browser console is flooded with `Failed to load resource: net::ERR_CONNECTION_REFUSED 0.0.0.0:5000/<resource>`.

**Comment by simonmichael** [comment]
Maybe also setting --base-url helps ?

**Comment by klockeph** [comment]
Well yes, but then it would still only work for the particular interface that has the matching IP to the base url.

**Comment by klockeph** [comment]
Coming to think of it, it probably just needs relative paths in the frontend. I'll try to see if I can create a PR.

**Comment by simonmichael** [comment]
"just" you say. :-)  Great, thanks for looking at it.
