### ISSUE TITLE
allow other date formats in journal via --input-date-format

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#210]
Journal entry dates currently have to be in ISO-style YYYY/MM/DD format (or YYYY-MM-DD or YYYY.MM.DD or MM/DD or MM-DD or MM.DD). If we provided a Ledger-style --input-date-format option, folks could use that to write DD/MM/YYYY (and DD/MM) dates instead, without ambiguity. We already have this kind of support when parsing CSV files.

Localisation is good. On the downside this makes sharing journal files and snippets harder, and creates one more hurdle for newcomers to get right. I've had to remember and adjust --input-date-format multiple times when running ledger on some pasted sample. So is this really worth it ?
##

**Comment by the-solipsist** [comment]
> Journal entry dates currently have to be in ISO-style YYYY/MM/DD format

I think YYYY-MM-DD is "[ISO style](https://en.wikipedia.org/wiki/ISO_8601)", rather than YYYY/MM/DD.

**Comment by Profpatsch** [comment]
I’m confused by the `YYYY/MM/DD` notation as well. I expected it to either

* use `YYYY-MM-DD` (ISO) dates everywhere
* use the user locale (`LC_TIME`, `LC_ALL` or `LANG`)

In all cases I think the plaintext files should only allow true ISO dates.

**Comment by the-solipsist** [comment]
This may be a separate issue, but as @hpdeifel notes in https://github.com/hpdeifel/hledger-iadd/issues/14#issuecomment-275505761, the `showTransaction` function from `hledger-lib` produces dates in the format YYYY/MM/DD rather than YYYY-MM-DD (which is the ISO8601 format).  This also affects how dates are displayed by `hledger print`, and in various reports.  Should this potentially be changed as well?

**Comment by simonmichael** [comment]
A new issue should be opened, proposing and exploring how to make hledger tools and docs use the ISO date format by default (rather than the Y/M/D one I chose for historical reasons).

**Comment by varac** [comment]
Specially for hledger add I'd like wither ISO8601 (YYYY-MM-DD) or it should honor the users LC_TIME locale var, which both don't apply.

**Comment by schoettl** [comment]
**I think the journal file itself should have an unambigious spec and no localized versions for dates** (except the few accepted formats @simonmichael mentioned in the first post).

`date-format` in CSV rules is perfect and neccessary for CSV import.

What I miss, is `--date-format` for hledger *output* (e.g. the `register` command's output). I think that would be useful to produce printed reports that are not awkward for "normal" clerks in Germany. Or did I miss something? Maybe I don't know hledger reporting tools yet...

**Comment by simonmichael** [comment]
It seems like there is some consensus that just ISO dates (or ISO plus a few punctuation variations, as we have now) is sufficient, and preferable, in journal files.

Then what about..

- the CLI ? Eg in the -b/-e/-p options, or the date:/date2: queries ? We allow more flexible [smart dates](http://hledger.org/hledger.html#smart-dates) there. I think allowing a different ordering of Y, M, D there could create a lot of hassle.

- dates entered in other UIs, eg in hledger-ui, hledger-web, hledger add ? Generally I think they should work follow the same syntax as in the CLI. Maybe hledger-iadd allows other formats.

- [timedot](http://hledger.org/timedot.html) files ? Should allow the same date formats as journal files.

- [timeclock](http://hledger.org/timeclock.html) files ? Consistency is good, but this is a pre-existing format. Does timeclock.el or Ledger allow ISO dates here ?

Output:

- from hledger (CLI) ? Should change to ISO format, #933 will handle this.

- from hledger-ui, hledger-web, and other tools ? Generally these should do what the hledger CLI does.

Docs:

- help and reference/tutorial/cookbook docs ? Also covered by #933.

**Comment by simonmichael** [comment]
> What I miss, is --output-date-format for hledger output (e.g. the register command's output). I think that would be useful to produce printed reports that are not awkward for "normal" clerks in Germany. 

@schoettl let's discuss that more on #933.

**Comment by simonmichael** [comment]
So I think we are rejecting the --input-date-format idea for now; our journal, timedot, and timeclock formats, and all UIs, already support ISO dates; so what's needed is to change docs, and the various tools' output; and this issue can be closed in favour of #933.

**Comment by mucholove** [comment]
My bank publishes this kind of format and I need to manually convert the data when preparing the file. This command would be amazing for "convert". This command does not work for me!

`ledger convert "sabadell transactions.csv" --input-date-format "%d/%m" --account Sabadell -f ~/Desktop/Ledger/LedgerBase`
