### ISSUE TITLE
Web/Sandstorm: File format help link is invalid

### ISSUE THREAD

**Issue by ocdtrekkie** [simonmichael/hledger#2103]
On the edit ledger form, there's a link to "File format help" which links to `http://hledger.orghledger.html/#file-format`. It appears to be a constructed URL from a couple variables, and I figured the / was being stripped out, though it is not a valid URL even with a / and I am unsure how to fix it.

**Comment by simonmichael** [comment]
Well spotted! The fix was a little bit involved - three commits at 9b8044f73 and one at https://github.com/simonmichael/hledger_site/commit/57257ab6d74887ad7e51e642cf47bc4b4ed2668d .
