### ISSUE TITLE
Scheduled actions auto-run in forks

### ISSUE THREAD

**Issue by ocdtrekkie** [simonmichael/hledger#2106]
Your website indicates that minimizing climate impact is a significant concern, so I felt this was worth highlighting: Some of your actions, such as https://github.com/simonmichael/hledger/blob/master/.github/workflows/binaries-mac-x64.yml run on a schedule. This will fire on every fork of your project new enough to include the Action. I noticed because I got an error message for a CI run, and disabled Actions on my fork, but for instance, here are automatic runs on another fork an hour ago: https://github.com/klockeph/hledger/actions/runs/6602384069

**Comment by simonmichael** [comment]
Thank you very much! I wondered why I've seen my binaries actions run in forked repos recently. 

I'd like these to run on the schedule - as a fallback to notify me of issues if I don't trigger them for a long time - but only in the master repo.

**Comment by simonmichael** [comment]
dae7b352 has disabled the weekly scheduled workflows in simonmichael/hledger .

Hopefully @klockeph and any other forkers will pull this soon so they are not running wasted workflows every week.

**Comment by klockeph** [comment]
Yeah actually I just deleted my fork, thanks for pointing this out :)

**Comment by simonmichael** [comment]
By search I found these other hledger forks currently running the weekly binaries workflows: @adept @silky @cardoe

And these forks which have the workflows but aren't running them (I wonder why): @chrislloyd @LudLaf @VOID404 @glguy @erictapen @gracig @chvp @cloudcompute

All, especially you first three, consider pulling the latest hledger master to disable these wasteful weekly builds. (And/or disable Actions in repo settings > Actions, as @DamienCassou did in his fork.)

And if you have any other tips on this topic (keeping workflows confined to the main repo), do share.

**Comment by simonmichael** [comment]
The most recent workflow run in those repos was 2 months ago (in @adept's), so I think wasteful runs are no longer happening and this can be closed.
