### ISSUE TITLE
if table; is matcher REGEX?

### ISSUE THREAD

**Issue by PSLLSP** [simonmichael/hledger#2107]
```
$ hledger --version
hledger 1.31, linux-x86_64
```

I try to process CSV data from [TradeOgre](https://tradeogre.com/markets) and it is not an easy task. I tried to use [if table](https://hledger.org/1.31/hledger.html#if-table) but it seems like "matcher" is not REGEX or REGEX doesn't work as expected. I need to combine several CSV fields to implement "AND" condition and when "," is in a matcher expression, then `hledger` doesn't like it... Character "," is used in "if table" statement so "," has to be escaped in some way.

It is possible that only documentation is not clear and this is not a real issue with `hledger`. I think I do not break any rule described in [hledger REGEX](https://hledger.org/1.31/hledger.html#regular-expressions) Or it is possible that "," character is a troublemaker and `hledger` code has to be fixed...

I assume that string `SELL,NEOX-LTC` can be matched with REGEX `SELL[,]NEOX-LTC` or `SELL\,NEOX-LTC` or `SELL.NEOX-LTC`; the last one is more general and could match other strings too... 

Example, with grep:
```
$ sed 's/;/,/g' demo-bug2.csv | grep "SELL,NEOX-LTC"
SELL,NEOX-LTC,"2023-09-22 12:46:55",3000.00000000,0.00004393,0.00041920
$ sed 's/;/,/g' demo-bug2.csv | grep "SELL[,;]NEOX-LTC"
SELL,NEOX-LTC,"2023-09-22 12:46:55",3000.00000000,0.00004393,0.00041920
$ sed 's/;/,/g' demo-bug2.csv | grep "SELL\,NEOX-LTC"
SELL,NEOX-LTC,"2023-09-22 12:46:55",3000.00000000,0.00004393,0.00041920
$ sed 's/;/,/g' demo-bug2.csv | grep "SELL.NEOX-LTC"
SELL,NEOX-LTC,"2023-09-22 12:46:55",3000.00000000,0.00004393,0.00041920
```

I have to use the last "workarround" (`SELL.NEOX-LTC`) because `hledger` doesn't like others in "if table" rule, character "," cannot be in REGEX...

DEMO data, CSV:
```
$ cat demo-bug2.csv
Type;Exchange;Date;Amount;Price;Fee
BUY;NEOX-LTC;"2023-09-17 13:45:33";5000.00000000;0.00004399;0.00043990
SELL;NEOX-LTC;"2023-09-22 12:46:55";3000.00000000;0.00004393;0.00041920
BUY;RTM-LTC;"2023-09-24 18:03:44";1600.00000000;0.00001149;0.00003676
SELL;RTM-LTC;"2023-10-06 07:23:11";600.00000000;0.00001499;0.00004796
```

DEMO, import rules:
```
$ cat demo-bug2.csv.rules
# Rules to import trade history from TradeOgre export

# debug
comment \n%1,%2,%3,%4,%5,%6

skip 1
separator ;
decimal-mark .

fields type, market, datetime, am1, price, fee

date-format %Y-%m-%d %H:%M:%s

date %datetime
description TOGRE|%market %type
account3  expenses:to:fee
status *

## NEOX-LTC

if NEOX-LTC
  account1  assets:to:account:ltc
  account2  assets:to:account:neox
  amount3   %fee LTC

if BUY,NEOX-LTC
  amount2   %am1 NEOX @ %price LTC

if SELL,NEOX-LTC
  amount2  -%am1 NEOX @ %price LTC

## RTM-LTC

if RTM-LTC
  account1  assets:to:account:ltc
  account2  assets:to:account:rtm
  amount3   %fee LTC

;if BUY,RTM-LTC
;  amount2   %am1 RTM @ %price LTC

;if SELL,RTM-LTC
;  amount2  -%am1 RTM @ %price LTC

; workarround, replace , with "wildcard" (.)
if,amount2
BUY.RTM-LTC,%am1 RTM @ %price LTC
SELL.RTM-LTC,-%am1 RTM @ %price LTC

; BUG, it doesn't work
;if,amount2
;BUY[,]RTM-LTC,%am1 RTM @ %price LTC
;SELL\,RTM-LTC,-%am1 RTM @ %price LTC
```
That rule file solves NEOX import with "if" rules and tries to import "RTM" with "if table" rule..

That rules file is accepted by `hledger`, it works:
```
$ hledger -f demo-bug2.csv bal
     -0.09849382 LTC  assets:to:account:ltc
  2000.00000000 NEOX  assets:to:account:neox
   1000.00000000 RTM  assets:to:account:rtm
      0.00094382 LTC  expenses:to:fee
--------------------
     -0.09755000 LTC
  2000.00000000 NEOX
   1000.00000000 RTM  
```

But when I change rule at the end of file then I receive the error:
 ```
$ hledger -f demo-bug2.csv print
hledger: Error: /home/user/hledger/demo-bug2.csv.rules:53:6:
   |
53 | BUY[,]RTM-LTC,%am1 RTM @ %price LTC
   |      ^
CSV parser: This regular expression is malformed, please correct it:
BUY[
```

Modified rule file to trigger the bug:
```
$ tail demo-bug2.csv.rules 

; workarround, replace , with "wildcard" (.)
;if,amount2
;BUY.RTM-LTC,%am1 RTM @ %price LTC
;SELL.RTM-LTC,-%am1 RTM @ %price LTC

; BUG, it doesn't work
if,amount2
BUY[,]RTM-LTC,%am1 RTM @ %price LTC
SELL\,RTM-LTC,-%am1 RTM @ %price LTC
```

**Comment by simonmichael** [comment]
Just in case: is https://hledger.org/1.31/hledger.html#matchers  > "the record matched is not the original CSV record" relevant ?

**Comment by PSLLSP** [comment]
> "the record matched is not the original CSV record" relevant ?

I missed that detail but it is not relevant. TradeOgre has "," as field separator but I modified my example and replaced "," with ";". to address `hledger` modification of the original CSV record. So, CSV file has ";" as field separator but I have to use "," in `hledger` CSV rules because it modifies original CSV record and replaces ";" with ",".

Anyway, this doesn't address the issue I tried to describe; 'hledger` cannot process REGEX that contains ","...

**Comment by simonmichael** [comment]
I had a look at this and I'm not seeing a bug yet. I think you wanted to include comma in your if table regexps, but at the same time you were using comma as the if table field separator; that's not supported apparently - there's no quoting mechanism, the if table field separator takes precedence and ends the regexp. Instead, you can simply use a different character as field separator, eg:
```
if|amount2
BUY,RTM-LTC|%am1 RTM @ %price LTC
SELL,RTM-LTC|-%am1 RTM @ %price LTC
```

**Comment by simonmichael** [comment]
If I'm not seeing the problem, can you try again to show it with a really minimal example ?

**Comment by PSLLSP** [comment]
OK, it is not a bug. I wanted highlight that separator cannot be escaped in REGEX. But I missed the detail that separator can use any other character, that it is not limited to comma...

Anyway, documentation uses comma in examples and comma is separator for CSV fields used by `hledger`. I think it will be better to use ";" or "|" as separator in documentation as it doesn't Coolidge with "," separator used in CSV. And it is even visually better, to see that the first field (regex) is different from other fields (values)...

if;field1,field2,field3
regrex1;value1,value2,value3
regex2;value1,value2,value3

or

if|field1,field2,field3
regex1|value1,value2,value3
regex2|value1,value2,value3

**Comment by simonmichael** [comment]
Those won't work, surely - the same separator must be used between all fields.

**Comment by simonmichael** [comment]
I don't see a problem with the functionality or docs here - can it be closed ?

**Comment by PSLLSP** [comment]
This issue can be closed. This is the rule modified with different separator and it works:

```
$ tail demo-bug2.csv.rules 

; workarround, replace , with "wildcard" (.)
;if,amount2
;BUY.RTM-LTC,%am1 RTM @ %price LTC
;SELL.RTM-LTC,-%am1 RTM @ %price LTC

; different separator, it works (comma was replaced with backslash)
if\amount2
BUY,RTM-LTC\%am1 RTM @ %price LTC
SELL,RTM-LTC\-%am1 RTM @ %price LTC
```

I use regular expressions in AWK and BASH (grep) and regular expressions work there in different way, I can escape most of characters, that was a source of my confusion...

**Comment by simonmichael** [comment]
I dug into this a little more to be sure.

https://hledger.org/hledger.html#regular-expressions says our regexps are POSIX ERE plus the extensions described there.

https://www.regular-expressions.info/posix.html#ere says that in POSIX ERE you can escape metacharacters with a backslash, but "escaping a character that is not a metacharacter is an error".

In `grep -E`, escaping a non-metacharacter works, with a warning; in `sed -E` it works with no warning.

In hledger regular expressions, backslash-escaping metacharacters or non-metacharacters works, as in sed.

https://hledger.org/1.31/hledger.html#if-table says "The first character after if is taken to be the separator for the rest of the table. It should be a non-alphanumeric character like , or | that does not appear anywhere else in the table." It seems more or less clear that this character will act as a delimiter, and so can't be part of regular expressions within the MATCHERs. So I think we're ok here. Thanks!

**Comment by simonmichael** [comment]
And finally, long story short: I have pushed an edit to make this clear in the doc. Thank for the feedback!

> The first character after if is taken to be this if table's field separator. It is unrelated to the separator used in the CSV file. It should be a non-alphanumeric character like , or | that does not appear anywhere else in the table (it should not be used in field names or matchers or values, and it cannot be escaped with a backslash).
