### ISSUE TITLE
hledger balance shows average column even if cumulative/historical

### ISSUE THREAD

**Issue by schoettl** [simonmichael/hledger#2118]
```
hledger bal -Y -AT --cumulative
```

shows a yearly cumulative balance. The total and average column make no sense for a cumulative balance.

The total column is therefore omitted – but not the average column.

I would provide a PR to fix this.

There might be similar bugs in register or other reports.

**Comment by simonmichael** [comment]
Should this kind of thing be an error, to reduce puzzlement ? Or left silent, for convenience when tacking options onto scripted commands ?

**Comment by schoettl** [comment]
I would omit the column silently, same behavior than the total column already has.

I've already implemented this. I open the PR for review this weekend...

**Comment by simonmichael** [comment]
Sounds good, we should probably check that it's mentioned in one or both docs (-T and --cumulative)

**Comment by Xitian9** [comment]
Just to add a counterpoint here: I'm not entirely convinced that average is not useful for a cumulative or historical report.

Imagine that I have an account meant to cover my monthly bills. I transfer a set amount of money into it each month. I may be interested in the average amount of money that is left in that account at the end of each month over the last two years, for example.

Granted, this is contrived and I've never actually done this myself. However, it is a conceivable and sensible report that someone may want to generate.

**Comment by schoettl** [comment]
Yeah, I think you're right @Xitian9... I first only considered cases like for `expenses:`, `income:` or `asset:savings`. They are normally monotonically increasing. In that case, the average wouldn't make sense. But for a cash account like you say, it makes sense.
