### ISSUE TITLE
Rounding not applied to first posting in multi-commodity transaction

### ISSUE THREAD

**Issue by wgslr** [simonmichael/hledger#2123]
As a preface, thank you for the new rounding options in hledger 1.32. I greatly appreciate having more control over rounding.  That said, there seems to be a bug: in the multi-currency transactions, rounding is never applied to the first posting:

Consider the following journal:
```
commodity 1.00$
commodity 1.00e

2023-12-01 | Single-currency transaction
    assets               -3e
    expenses              3e

2023-12-01 | Multi-currency transaction
    assets               -3e
    expenses              3$

2023-12-01 | Reversed order multi-currency transaction
    expenses              3$
    assets               -3e
```

Try printing with round=all and observe `-3e` and `3$` not being rounded 
```
$ hledger print -f journal --round=all
2023-12-01 | Single-currency transaction
    assets            -3.00e
    expenses           3.00e

2023-12-01 | Multi-currency transaction
    assets               -3e
    expenses           3.00$

2023-12-01 | Reversed order multi-currency transaction
    expenses              3$
    assets            -3.00e
```
With round=soft and round=hard it also doesn't work.

Adding the `-x` flag causes rounding to kick in:
```
$ hledger print -f journal --round=all -x
2023-12-01 | Single-currency transaction
    assets            -3.00e
    expenses           3.00e

2023-12-01 | Multi-currency transaction
    assets      -3.00e @@ 3.00$
    expenses              3.00$

2023-12-01 | Reversed order multi-currency transaction
    expenses    3.00$ @@ 3.00e
    assets              -3.00e
```

## Version

hledger 1.32, linux-x86_64

**Comment by simonmichael** [comment]
Good catch, thank you! I couldn't find it quickly so have opened https://github.com/simonmichael/hledger/issues/2124 . 

I avoid this style (implicit conversion costs) because it's error prone. But it should work as you expected.

**Comment by simonmichael** [comment]
Fixed in master.
