### ISSUE TITLE
require GHC 9.4+ ?

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#2129]
From #2128:
> I see vty-windows is requiring GHC 9.4.4+. I'm thinking about this for hledger. It would be pleasant, but a big jump from 8.10 which I think would hurt our packageability ? Debian stable has 9.0 but Debian unstable has 9.4. No Ubuntu version has a GHC newer than 9.0. But I guess it wouldn't be the end of the world. 8.10 is 3.5y old (2020) and 9.4 is 1y old (2022).

**Comment by simonmichael** [comment]
Actually it's [probably not necessary](https://github.com/simonmichael/hledger/pull/2128#issuecomment-1847475396) after all. But I'm still tempted.

**Comment by chreekat** [comment]
Yoiks, somebody should start packaging GHC for Ubuntu again!

**Comment by simonmichael** [comment]
If I'm reading things right we didn't do this yet, and for the moment still support GHC 8.10 and up (even for hledger-windows). If someone finds otherwise, eg someone installing hledger-ui on MS windows, please let me know.
