### ISSUE TITLE
Generate a report based on comments

### ISSUE THREAD

**Issue by llcc** [simonmichael/hledger#2131]
I'm interested in generating a report specifically for entries with identical comments in Hledger. After reviewing the Hledger manual, it appears that this feature is currently not available. I'm considering whether it would be valuable to propose the addition of such functionality to Hledger. What are your thoughts on this potential enhancement?

**Comment by simonmichael** [comment]
I think it'd be a great thing to prototype as an add-on script, using something like https://hledger.org/scripts.html#hledger-check-postable as a starting point. You could also try to do it or prototype it with a non-haskell script - these tend to be less robust but can be quicker to get going.

**Comment by simonmichael** [comment]
See also https://hledger.org/scripts.html#how-to
