### ISSUE TITLE
--anon needs clearer warnings in docs

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#2133]
--anon gives only a thin layer of obfuscation, and not all the docs make this clear. We should make this clearer (or remove it..).

>  `--anon` seems to use a deterministic hash with no seed, so if you want to look up whether someone is paying for Netflix or another streaming service you probably can. And you could probably calculate the hash of all dictionary words and deanonymize account names that way.

**Comment by edwintorok** [comment]
The `:` separators in the account (that are needed to preserve hierarchy) is also problematic, see https://www.ftc.gov/policy/advocacy-research/tech-at-ftc/2012/04/does-hashing-make-data-anonymous.
A better solution might be to use an HMAC with a secret key that you throw away (but that'd make the output of `--anon` change every time you run it).

**Comment by Anachron** [comment]
> A better solution might be to use an HMAC with a secret key that you throw away (but that'd make the output of --anon change every time you run it).

We could make --anon accept a salt parameter ENV var.

**Comment by simonmichael** [comment]
I'm inclined to drop this feature, because no matter how much we document it the name creates an expectation of anonymity, which it really can never provide, and having it in the product creates an ongoing risk of users getting burned.

**Comment by simonmichael** [comment]
I was the one who asked for determinism in 2016 (#265), because it was useful.

I assume even with a randomised hash, an interested person or tool could discover a lot from an obfuscated journal or report, because there's so much conventional structure in financial data.

I don't see much use case for this, if sharing obfuscated output online could unexpectedly leak information. Are there any counter proposals to removing this feature ? If not I'll move forward on that (perhaps keeping it available as --obfuscate for a period).

**Comment by simonmichael** [comment]
For the moment: --anon is now a hidden flag, gives an informative error when used, and can still be used as --obfuscate (also a hidden flag).

**Comment by edwintorok** [comment]
> counter proposals

Pardon the pun, but you could actually use a counter as a solution :) 

Assign each unique string a unique number the first time you see them (e.g. a hashtable with values assigned from a globally incrementing number).
Then the obfuscated value will not be a function of the input string at all, it'll be a function of the input string's *position*, which shouldn't reveal information about the string itself. And it'd be fully deterministic on a given journal file
(of course different journal files will produce completely different outputs, but I guess that is fine).

But I don't have an idea on what to do about obfuscating values.

The question is: was  this anon/obfuscate option ever useful to you as a way for users to report bugs in hledger?

**Comment by simonmichael** [comment]
I *believe* that yes it was (/seemed/can be)  useful to me and others for sharing repros of bugs and puzzles. Sometimes it's hard or too much work to recreate or reduce or sanitise these, which makes discussion and support more difficult. If we could add a flag and safely share, I think that would sometimes be helpful, saving time on both ends. (I also wished it could generate more readable human-style names, which would make comprehension and discussion easier.)

The above sounds like a good improvement, if we could find someone with time to do it. 

I think it's still not very private though. Think of sharing a whole journal obfuscated this way. It's still quite easy to guess what are the major accounts and big financial picture and some likely transactions by analysing amount flows and dates.

Obfuscating amounts and perhaps dates could help. But doing that without breaking journal invariants or correct bookkeeping or the behaviour being demonstrated sounds difficult.

**Comment by edwintorok** [comment]
Yes, all I could think of for obfuscating values was to multiply all values with a fixed number. But that is very easy to reverse as soon as you learn the true value of one real transaction, and it'd be quite difficult to change the multiplier with each transaction given how transactions can span many days or accounts (and in the end anything too clever here might hide the original bug the user was trying to report).

You raise a good point about "small examples". If someone has successfully minimized a bug (https://github.com/mpflanzer/delta used to be my go-to for minimizing compiler bugs, I assume it'd work for hledger too?), then the counter based obfuscation (perhaps prefixed with a letter to make it valid account name) may be useful, and perhaps a multiplier based obfuscation of values wouldn't be too bad either, considering that these values are just a sample of the journal and not the entire journal.
Although there are other pieces that might be sensitive (e.g. stock account names), so commodities might need a counter based strategy too.

**Comment by simonmichael** [comment]
We could definitely do with a more automated workflow for minimising examples, eg trying delta. If minimising were automated, it might reduce the need for obfuscation ?

**Comment by simonmichael** [comment]
Closing this pending further activity.

**Comment by the-solipsist** [comment]
I'd like obfuscation to hide certain personal details when I'm sharing examples with other people.

When I try to obfuscate, what I want changed are:

1. Amount, almost always.
2. Description, perhaps, since those often contains more "personal" information than the account names.
3. Possibly the last leaf of the account name.

What I definitely don't want changed are:
1. Most of the account hierarchy, since the account hierarchy is almost always what I'm seeking to share.

Given this, the current mode of obfuscation does pretty much the opposite of what I'd want.
