### ISSUE TITLE
ReportOpts depth is ignored in displayedAccounts

### ISSUE THREAD

**Issue by alt-romes** [simonmichael/hledger#2146]
Hello!

I am trying to programatically set the depth of a cummulative report in hledger by setting the `depth_` field of `ReportOpts` to `Just 2`, however, the report ignores this parameter.

I looked in the source, and it looks like the shown accounts are determined by `MultiBalanceReport.displayedAccounts`, which, in turn, determines the depth by looking for `Depth ...` in the query!

It makes sense to me that `displayedAccounts` also accounts for `depth_` of report options, but I might not be seeing the full picture.

Here's a suggested fix:
```diff
diff --git a/hledger-lib/Hledger/Reports/MultiBalanceReport.hs b/hledger-lib/Hledger/Reports/MultiBalanceReport.hs
index b0bc5e508..8180daba3 100644
--- a/hledger-lib/Hledger/Reports/MultiBalanceReport.hs
+++ b/hledger-lib/Hledger/Reports/MultiBalanceReport.hs
@@ -460,7 +460,7 @@ displayedAccounts ReportSpec{_rsQuery=query,_rsReportOpts=ropts} unelidableaccts
         minSubs = if no_elide_ ropts then 1 else 2
 
     isZeroRow balance = all (mixedAmountLooksZero . balance)
-    qdepth = fromMaybe maxBound $ queryDepth query
+    qdepth = fromMaybe (fromMaybe maxBound $ queryDepth query) (depth_ ropts)
     numSubs = subaccountTallies . HM.keys $ HM.filterWithKey isInteresting valuedaccts
 
 -- | Sort the rows by amount or by account declaration order.
```

**Comment by alt-romes** [comment]
Turns out the suggested fix is not good enough, since it affects the displayed accounts, but not the amounts like `Depth` does.

So I'm not sure what should happen, and perhaps I should stick to using the `Depth` query.

A possible solution could be to document more precisely what `depth_` in `ReportOpts` affects.

**Comment by Xitian9** [comment]
In general, you cannot update the `ReportOpts` within a `ReportSpec` without risking the two getting out of sync. This is documented here: https://github.com/simonmichael/hledger/blob/c82560572175652413f828393cae6a80721450a1/hledger-lib/Hledger/Reports/ReportOptions.hs#L276C50-L284.

Use `reportOptsToSpec` to update the `ReportSpec`. Or you can use the lens update infrastructure and it will update the `ReportSpec` automatically.

**Comment by simonmichael** [comment]
Thanks for that @Xitian9.

We knew when we set up this ReportSpec / ReportOpts redundancy that it would be error prone. Alas we found no better way to do it because of Reasons I forget, perhaps related to keeping partial code like regexp compilation out of the core.

**Comment by alt-romes** [comment]
Thank you @Xitian9 @simonmichael. That makes sense, and I had noticed that comment... though I forgot about it later on when actually calling the API.

Thanks!
