### ISSUE TITLE
1.32: import --catchup no longer writes .latest files

### ISSUE THREAD

**Issue by ishmaelavila** [simonmichael/hledger#2156]
When I attempt to import a `CSV` from my bank and I specify the `--catchup` option, the command runs successfully, however, the `.latest.sample.csv` state file is not written. The existence of the file and it's content do not seem to have an impact on whether the command updates/creates the file.

I've been able to reproduce this issue reliably on versions above `1.31`. The issue seems to have been introduced in `1.32` and I think it may be a regression as I couldn't find anything in the release notes suggesting it was an intentional change.

Please let me know if you need anything else to reproduce or if this is a problem on my end. Thanks!

```
$ hledger --version
hledger 1.32.2, linux-x86_64
```
## Steps To Reproduce
Note, the commands assume you have  the `LEDGER_FILE` [environmental variable](https://hledger.org/1.32/hledger.html#setting-ledger_file) specified.
1. Install hledger `>=1.32`
1. Create a `CSV` that contains valid transactions for importing
1. Run `hledger import --catchup sample.csv`
1. Observe that the command runs succesfully
1. Look for `.latest.sample.csv` to see if it was created or updated
1. Run the import again and observe it continues to say the CSV was marked as caught up rather than saying `no new transactions found in CSV`

## Expected Result

The command finishes successfully, prints the number of transactions skipped, and updated the `.latest.sample.csv` file with the latest dates.

## Notes

When I run the `import` command without `--catchup`, the journal file is updated and the `.latest.sample.csv` file is created/updated correctly. The `--catchup` option works for me in version`1.31` so I'll continue using that for now.

**Comment by simonmichael** [comment]
Confirmed, thanks for the report!

Claim your https://hledger.org/REGRESSIONS.html#regression-bounty when convenient. Per new policy, it's $50 to the finder and (if someone other than me wants to fix it) $50 to the fixer.

**Comment by simonmichael** [comment]
Fixed in master.

**Comment by simonmichael** [comment]
Hi @ishmaelavila, I encourage you to claim your $50 regression finder's bounty within the next 7 days! If not, it will be recorded as a project donation.
