### ISSUE TITLE
hledger-web tests fail on stackage

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#2157]
With `setupTerm: Couldn't look up terminfo entry "unknown"`. Something to do with terminal helpers in Hledger.Utils.IO  ?

https://github.com/commercialhaskell/lts-haskell/commit/1342c798114a09c49d87a59d25609fbe16098907

**Comment by juhp** [comment]
(thanks for filing, in the end I hesitated since I wondered if it's a problem on the stackage server env)

**Comment by simonmichael** [comment]
@juhp: when you have time could you clarify when you see this terminfo "unknown" error, with hledger-web tests ?

I failed to reproduce it with https://github.com/commercialhaskell/stackage/pull/7413.

**Comment by simonmichael** [comment]
Notes: hledger-lib's test suite seems currently disabled in stackage (because of issues running doctest). hledger-ui doesn't have a test suite. hledger-web's test suite is the only one using hspec. Most hledger packages import from transitively, even if they don't use, these three terminal-related packages: ansi-terminal, terminal-size, terminfo. Test runners also interact with the terminal.

**Comment by alaendle** [comment]
Unfortunately the situation remains unchanged:
```
Running tests for hledger-web 1.33.1, linux-x86_64
test: setupTerm: Couldn't look up terminfo entry "unknown"
```

**Comment by alaendle** [comment]
Okay - pretty sure we just depend on https://packages.ubuntu.com/jammy/ncurses-term to get the "unknown" terminfo ... will re-run with installed package ... and keep you up-to-date ...

**Comment by alaendle** [comment]
Hmm - doesn't seem to solve the problem - need to dive deeper ... maybe tomorrow  ... (temporarily?) re-disabled tests ... any idea/hint welcome ...

**Comment by alaendle** [comment]
I've tried to reproduce this inside the build container - without success - so my best guess is that this has to do with the user things happening here: https://github.com/commercialhaskell/stackage/blob/770b1939dc1784b0484b7f6aeb102c65a1f9cb25/automated/build.sh#L145
But I even tried to mimic this inside the container by creating another user and running `nice -n 15 /bin/bash -c "chown other $HOME && exec sudo -E -u other env \"HOME=$HOME\" \"PATH=\$PATH\" ./verify-package hledger-web 2>&1"` - but even this succeeds. So at least I have no idea what could be done with justifiable effort - so my suggestion would be to accept the test failure on stackage (as long it doesn't effect more packages) and close this issue without a solution.

**Comment by simonmichael** [comment]
Thank you @alaendle. Closing for now per this and the discussion on https://github.com/commercialhaskell/stackage/pull/7413.
