### ISSUE TITLE
Fails to build with base64 >= 1

### ISSUE THREAD

**Issue by dhruvin-dev** [simonmichael/hledger#2166]
Building with cabal, which resolves base64 to 1.0, fails.

We either need to pin `base64 <1` in hledger-web or need to update the code.

```shell
cabal build all
```

```text
Hledger/Web/Widget/AddForm.hs:189:7: error:
    • Couldn't match type ‘base64-1.0:Data.Base64.Types.Internal.Base64
                             'base64-1.0:Data.Base64.Types.Internal.StdPadded Text’
                     with ‘Text’
      Expected: Text -> Text
        Actual: Text
                -> base64-1.0:Data.Base64.Types.Internal.Base64
                     'base64-1.0:Data.Base64.Types.Internal.StdPadded Text
    • In the second argument of ‘(.)’, namely ‘b64wrap’
      In the second argument of ‘(.)’, namely ‘(<> "}") . b64wrap’
      In the first argument of ‘map’, namely
        ‘(("{\"value\":" <>) . (<> "}") . b64wrap)’
    |
189 |       b64wrap
    |       ^^^^^^^
```

For maintainers:
- severity3
- impact2

Update:

For now, we (alpine) have pinned [`base64 <1` here](https://gitlab.alpinelinux.org/alpine/aports/-/blob/b436ae28f3d4cf5725cf25b39178fe735982f14c/community/hledger/constrain-base64.patch). I believe other distributions building hledger with cabal would be facing the same.

**Comment by simonmichael** [comment]
Thanks for the report. I have revised hledger-web-1.32.3 on hackage and pushed a fix to master.
