### ISSUE TITLE
Strict mode should probably not require explicit commodity conversion

### ISSUE THREAD

**Issue by silky** [simonmichael/hledger#2170]
If you enable strict mode you get very convenient things like account-checking, but also the moderately inconvient requirement to "explicitly" declare commodity conversions.

I.e.

```
a  -10 USD
b  20 GBP
```

is _not_ accepted, but

```
a  -10 USD @@ 20 GBP
b
```

would be.

in my view, this particular rule is a bit odd. to me, the first one is actually more clear; because the amounts are directly allocated.

in any case, it becomes extremely inconvenient if _all_ you want is account checking (something you do _not_ get if you run the `check` operation, i think).

so, some ideas:

- allow an option for specifically running account-checking rule
- _don't_ run commodity checking when running strict mode
- ???

**Comment by NobbZ** [comment]
The 2 transactions are not equivalent.

The first one is unbalanced. When you add to one account, you have to deduct the other.

From my understanding the second os equivalent to this:

```ledger
a   10 USD
b  -20 GBP
```

**Comment by simonmichael** [comment]
I hear you. I don't have the past discussion handy, but it was felt that the first form, while pleasant, is too error-prone to be suitable for default strict mode.

The second form you've shown, with the balancing amount left implicit, is fairly similar but at least it's more explicit that a cost conversion is desired.

You can get strict mode without that one check by specifying the individual checks, I believe  `hledger check accounts commodities` will do it.
https://hledger.org/dev/hledger.html#checkMessage ID: ***@***.***>

**Comment by silky** [comment]
@NobbZ , sorry, I made a typo; I wanted a minus sign in there; but the idea is correct; consider the journal:

```
; a.journal
commodity 1,000.00 GBP
commodity 1,000.00 AUD

account a
account b

; Strict-checking fails
; 2021-01-01 Example
;   a  -10.00 AUD
;   b  20.00 GBP


; Strict-checking works
2021-01-01 Example
  a  -10.00 AUD @@ 20 GBP
  b
```

they both give the same balances (check with `hledger -f a.journal reg`) ; but the first one fails strict checking and the second does not.

**Comment by silky** [comment]
@simonmichael thanks; I see, `hledger check accounts` is what I want and I'm happy enough with that to close the issue.

To me it was just surprising to see the requirement for explicitness be part of strictness; but I get that it's probably best to just leave it as-is.

Thanks for the prompt response!
