### ISSUE TITLE
hledger-ui : Quickly change status of an entry

### ISSUE THREAD

**Issue by SanAntonio37** [simonmichael/hledger#2182]
Hi !

First of all, thank you for these worderful apps.

My wish is simple.
I'd like to change the status (marked/pending/cleared) of a journal entry directly from the hledger-ui interface.
I haven't found a key that can do this action.

Best regards.

**Comment by simonmichael** [comment]
You're welcome! This is a duplicate of #632 and #1413, I'll close all but the first.
