### ISSUE TITLE
Make the newest version apt binaries available for Ubuntu 22.04.x LTS 

### ISSUE THREAD

**Issue by edpichler** [simonmichael/hledger#2185]
Only `hledger 1.19.1` is currently available in `Ubuntu 22.04.4 LTS `

**Comment by simonmichael** [comment]
Thanks for the report @edpichler. That's right; you can see which hledger version is included in each ubuntu version here: 
https://hledger.org/install.html#gnulinux

You could bring this up with ubuntu's hledger packager - I guess things are sometimes backported to old ubuntus - but I think it's unlikely to happen here. Better to use a newer ubuntu or if you're willing, install hledger by other means, eg the linux binary at the above link.

**Comment by edpichler** [comment]
So this Ubuntu is the latest LTS (long term support). And it´s also used in the WSL2 in windows.
What do you mean by "bringing this up with ubuntu hledger packager"? I'm just asking to see if I can contribute with a PR.

**Comment by simonmichael** [comment]
Thanks for that. I don't have much control over what hledger version is in Ubuntu 22.04; there is a person responsible which you can find at https://packages.ubuntu.com/jammy/hledger. I see Ubuntu MOTU Developers, Debian Haskell Group and Clint Adams, and "Please consider filing a bug or asking a question via Launchpad before contacting the maintainer directly" - that might be the best next step.

**Comment by edpichler** [comment]
FYI: I created an issue there https://answers.launchpad.net/ubuntu/+source/haskell-hledger/+question/709536

**Comment by edpichler** [comment]
> There is no newer version of Hledger available in Ubuntu jammy, as long a nobody volunteers to build such version.
> 
> Maybe you can find somebody who creates a package of the newer version in a PPA, but due to the fact that Hledger is in the "universe" category (=community maintained), you cannot expect actions from Ubuntu side.
> 
> Ubuntu 24.04 (to be published in six weeks' time) will have Hledger 1.30.1 (or eventually higher). If you dare, you can already switch to the development version Ubuntu 24.04 now.

@simonmichael is there any plans to have hledger in PPA? https://launchpad.net/ubuntu/+ppas

**Comment by simonmichael** [comment]
@edpichler not that I know of. I sure would love it if installing latest hledger could finally(!) become easy for Ubuntu users. Is it something you could help push forward ?

**Comment by edpichler** [comment]
@simonmichael my agenda is very packed but I will give it a try.
