### ISSUE TITLE
roi valuation refuses to unify accounts, gives incorrect recommendation

### ISSUE THREAD

**Issue by aragaer** [simonmichael/hledger#2190]
Given the following journal file:
```
P 2023-01-01 B 20A
P 2023-01-01 C 1B

2023-01-01
 investment  1C @@ 20A
 investment  4B @@ 80A
 assets

P 2023-12-31 C 2B
```
If I want to get ROI "in units of B", I'm expecting to see something like this:
```
$ hledger -f /tmp/test.journal roi --inv investment --pnl income --value='end,B' -e2024
+---++------------+------------++---------------+----------+-------------+-----++--------++------------+----------+
|   ||      Begin |        End || Value (begin) | Cashflow | Value (end) | PnL ||    IRR || TWR/period | TWR/year |
+===++============+============++===============+==========+=============+=====++========++============+==========+
| 1 || 2023-01-01 | 2023-12-31 ||             0 |       5B |          6B |  1B || 20.00% ||     20.00% |   20.00% |
+---++------------+------------++---------------+----------+-------------+-----++--------++------------+----------+
```
But instead I get an error `Error: Amounts could not be converted to a single cost basis: ["2B","4B @@ 80A"]` with a recommendation to add `--cost`.

Adding `--cost` helps remove the error message, but gives an incorrect result:
```
$ hledger -f /tmp/test.journal roi --inv investment --pnl income --value='end,B' -e2024 --cost
+---++------------+------------++---------------+----------+-------------+-----++-------++------------+----------+
|   ||      Begin |        End || Value (begin) | Cashflow | Value (end) | PnL ||   IRR || TWR/period | TWR/year |
+===++============+============++===============+==========+=============+=====++=======++============+==========+
| 1 || 2023-01-01 | 2023-12-31 ||             0 |       5B |          5B |   0 || 0.00% ||      0.00% |    0.00% |
+---++------------+------------++---------------+----------+-------------+-----++-------++------------+----------+
```

How should I change my query (or perhaps my journal) to see that 20% IRR?

**Comment by aragaer** [comment]
It does work as expected if I rewrite the transaction like this:
```
2023-01-01
 investment  4B
 investment  1C
 assets  -80A @@ 4B
 assets  -20A @@ 1C
```
Which seems to be completely equivalent but is somehow different.

**Comment by simonmichael** [comment]
I don't know `roi` well, but it is true in general that the order of postings is significant when using @ cost notation. It is mentioned briefly at

- https://hledger.org/dev/hledger.html#costs > "Note the effect of posting order"
- https://hledger.org/dev/hledger.html#recording-costs > "Variant 3"

**Comment by simonmichael** [comment]
Perhaps a patch to roi's help is needed ?

**Comment by aragaer** [comment]
I think that in this specific case it's a bug in roi implementation, not documentation issue. It should not try and unMix `["B", "B @@ 20A"]` in general case (that is roi test 9), but with `--value=then,B` it should see those two as equal. I think the problem is that `--value` is not applied to `valueBefore` and `valueAfter` while it is applied to `cashFlow`.

**Comment by adept** [comment]
That's a bug allright (but not where you say it is - in fact, both `valueBefore` and `valueAfter` are properly valued at the moment). The fix is forthcoming.

**Comment by simonmichael** [comment]
Merged, thanks!
