### ISSUE TITLE
Install instruction under Linux with release 1.34

### ISSUE THREAD

**Issue by felixschurk** [simonmichael/hledger#2200]
https://github.com/simonmichael/hledger/releases/tag/1.34

Linux release notes show still on how to install the old ones. 

https://github.com/simonmichael/hledger/blob/245b082eb9389af4b65ec3f8af3644752d0c46f6/doc/ghrelnotes?plain=1#L39-L43

I think the new ones should be:
```sh
cd /usr/local/bin
curl -LOC- https://github.com/simonmichael/hledger/releases/download/1.34/hledger-linux-x64.tar.gz    # just rerun if interrupted
tar xvf hledger-linux-x64.tar.gz && rm -f hledger-linux-x64.tar.gz  # unpack and remove .tar.gz file
cd
hledger --version    # should show the new version
```

Thanks a lot for the update, its nice to have it straight forward. :)

**Comment by simonmichael** [comment]
Good catch, thank you! Fixed.

-Simon
