### ISSUE TITLE
Account type tag inconsistently recognized when declared in multiple files

### ISSUE THREAD

**Issue by pwseo** [simonmichael/hledger#2202]
Account `type:` tags seem to be inconsistently recognized.

I have set up a minimum working example:
```
$ hledger --version
hledger 1.34, linux-x86_64
$ ls
a.j  b.j
$ cat a.j
account Node:Leaf A  ; type: Cash
include b.j
$ cat b.j
account Node:Leaf B  ; type: Cash
```
Now we use hledger's accounts' listing and request the account types as well:
```
$ hledger -s -f a.j accounts --types
Node:Leaf A    ; type: 
Node:Leaf B    ; type: C
```
Shouldn't `Node:Leaf A` also be of `type: C`?

--
Note: this does not happen if all account directives with type tags are declared in the same file.

**Comment by pwseo** [comment]
Some follow-up to what I have mentioned above: if I remove the account `type: C` tag from `Node:Leaf B`, suddenly it starts working correctly:
```
$ cat a.j
account Node:Leaf A  ; type: Cash
$ cat b.j 
account Node:Leaf B
$ hledger -s -f a.j accounts --types
Node:Leaf A    ; type: C
Node:Leaf B    ; type: 
```
Is there a file-scoped limit for account type tags? If so, I was not aware (and did not expect it, since `account` directives are global).

**Comment by pwseo** [comment]
Okay, so things are a little bit weirder than I antecipated.
This bug manifests only for `type` tags with the same value.

Let's see another similar example:
```
$ cat a.j 
account Node:Leaf A  ; type: C
include b.j
include c.j
$ cat b.j 
account Node:Leaf B  ; type: C
$ cat c.j 
account Node:Leaf C  ; type: C
```
In this case, both `Node:Leaf A` and `Node:Leaf B` tags are ignored, only `Node:Leaf C` is kept:
```
$ hledger -s -f a.j accounts --types
Node:Leaf A    ; type: 
Node:Leaf B    ; type: 
Node:Leaf C    ; type: C
```

If we were to change `Node:Leaf B` to another type, both `Node:Leaf B` and `Node:Leaf C` would be kept. `Node:Leaf A`'s type will still be blank:
```
$ sed -i b.j -e 's/type: C/type: X/'
$ hledger -s -f a.j accounts --types
Node:Leaf A    ; type: 
Node:Leaf B    ; type: X
Node:Leaf C    ; type: C
```
And finally, if we change `Node:Leaf A`'s type tag to something else, everything works:
```$ hledger -s -f a.j accounts --types
Node:Leaf A    ; type: R
Node:Leaf B    ; type: X
Node:Leaf C    ; type: C
```

**Comment by simonmichael** [comment]
I agree, that is weird. Thanks for the report.

**Comment by pwseo** [comment]
@simonmichael, I believe the commits 531d34a and a18425c should reference issue #2201.

**Comment by pwseo** [comment]
> I agree, that is weird. Thanks for the report.

I tried running `hledger` with `--debug=9` but didn't find anything that might help.
Can I help with anything else? (my Haskell skills are not very good).

**Comment by simonmichael** [comment]
> @simonmichael, I believe the commits [531d34a](https://github.com/simonmichael/hledger/commit/531d34ae516b1959296fb88654f9992015fde37d) and [a18425c](https://github.com/simonmichael/hledger/commit/a18425ca50caa3f06c38b7643b6f17dbe6b09074) should reference issue #2201.

Right you are! I edited and force-pushed them.

> I tried running hledger with --debug=9 but didn't find anything that might help.
> Can I help with anything else? (my Haskell skills are not very good).

I appreciate that. I tried the same, then I started adding dbg0 calls and reloading in ghci (`just ghci`). I have seen that Hledger.Read.Common.addDeclaredAccountTags is adding each tag declaration, but on each call it sees that `jdeclaredaccounttags j` is empty, which is strange (it should be accumulating results from each call.

**Comment by simonmichael** [comment]
I believe this is now fixed in master. Good catch (a bug with the original implementation of type:, not a regression).

**Comment by pwseo** [comment]
It is fixed indeed! I thank you for your dedication to this project :)
