### ISSUE TITLE
Ledger file formatting tool

### ISSUE THREAD

**Issue by danihodovic** [simonmichael/hledger#2207]
I've tried to search the manual and Github for tools that automatically format ledger files (similar to Black for Python or gofmt for Go). I write my ledger file in vim and it ends up with inconsistent formatting, especially between the account and amount which vary for each transaction.

Does a command to format files already exist? If not, how difficult would it be to write?

**Comment by simonmichael** [comment]
I think the situation is this: 

1. In the PTA world, only the PTA tools themselves can fully parse their own formats, and they usually have a command for outputting the same format (like `print`). But none of them does this perfectly, eg `hledger print` is good at preserving everything within a transaction, but it doesn't preserve directives or inter-transaction comments, so you have to work around that. 
2. There are some editor/IDE addons which can parse and reformat PTA data files. These parse more superficially, but actually they are probably better at preserving data. ledger-mode in Emacs (M-q key), VS Code addons, and probably vim addons are some of these.

**Comment by danihodovic** [comment]
hledger print does seem to preserve comments which is great, but doesn't format the amounts for transactions consistently

```
2024-05-31 Manually added fees
    Expenses:Bank:Fees        EUR14.25
    Assets:Bank                  EUR-14.25

2024-06-01 Ice cream
    ; :-)
    Expenses:Ice Cream         EUR2.20
    Assets:Bank                    EUR-8.09
```

**Comment by simonmichael** [comment]
I can't reproduce your example, but the current general behaviour of hledger print is: it right-aligns the amounts, separately within each transaction. It doesn't align them across all transactions; ledger-mode is good for that.
