### ISSUE TITLE
Code for Postings

### ISSUE THREAD

**Issue by jtagcat** [simonmichael/hledger#2209]
Transactions can have code in the form of `2024-07-11 (CODE) TxName`.

I would find use in code for postings:
- EAN of product. Some receipts I digitize manually, some receipts are already available as CSV (even groceries).
- Multiple orders bundled up in to a single payment, for example, AliExpress. (Multiple / nested codes is another can of worms.)

For the format:
- Single-space brackets in account name are part of the name.
- Single and double-brackets after amount is already special syntax.

One semi-sensible format would be to do it before amount (or even double-space on both sides):
```
2024-07-11 (TxCode) TxName
  expense:hello   (PCode) 10.00 EUR
  expense:world  (PCode)  10.00 EUR ; double space on both sides
```

I find the double-space syntax error-prone, but it's the forever-v1 syntax we live with.

**Comment by simonmichael** [comment]
I feel it's probably not worth complicating that already complicated parsing region when we can use tags instead (`10.00 EUR  ; code:PCode`). In fact I switched from transaction codes to tags some time ago for consistency and better alignment in reports.

**Comment by jtagcat** [comment]
Meta discussion: will there be 'v2', an (besides migrating/converting) incompatible format, at some point?

**Comment by simonmichael** [comment]
That's certainly possible, at least as an additional supported file format. It would need to  be different/better enough to justify the effort and impact on UX. What would you change ?
