### ISSUE TITLE
ledger import not assigning default account2 as per manual

### ISSUE THREAD

**Issue by brucer42** [simonmichael/hledger#2210]
https://hledger.org/import-csv.html:
"# the other account will default to expenses:unknown or income:unknown;"

% hledger --version
hledger 1.34, mac-x86_64
% hledger import test.csv

test.csv:
header1
header2
header3
Transaction Number,Date,Description,Memo,Amount Debit,Amount Credit,Balance,Check Number,Fees  
"20180105000001[-8:PST]*-70.55*100**VZWRLSS*IVR VN 800-922-0204 FL",01/05/2018,"VZWRLSS*IVR VN 800-922-0204 FL","01-05-2018 DEBIT CARD DEBIT Eff. Date:",-70.55,,"256.06",,

test.csv.rules:
skip 4
fields Transaction,Date,Description,Memo,Debit,Credit,,Check_Number,Fees
date-format %-m/%-d/%Y
currency $
account1 Assets:RCU:Checking

.hledger.journal:

2018-01-05 VZWRLSS*IVR VN 800-922-0204 FL
    Assets:RCU:Checking               0

For me, this is a severity4, because I don't see how to get the default as I fill in known accounts. I'm trying to get off of ledger but this is a blocker for me. AND the documentation is wrong.

Who is likely to be impacted by this bug ? NEW PROSPECTIVE USERS

**Comment by brucer42** [comment]
***needs*** amount field. I'm up now.

**Comment by simonmichael** [comment]
Thanks for the report. I think you expected it to add a second "unknown" posting automatically. In fact it creates a posting N only when either amountN or accountN is set. This makes it possible to generate 0- or 1-posting entries. So I think all is well here ?

**Comment by brucer42** [comment]
All is well. I should have started with the exact example in the manual,
verified it, then introduced my csv.
Thanks for hledger!

λέγει αὐτῷ Ἰησοῦς Ἐγώ εἰμι ἡ ὁδὸς καὶ ἡ ἀλήθεια καὶ ἡ ζωή· οὐδεὶς ἔρχεται
πρὸς τὸν Πατέρα εἰ μὴ δι' ἐμοῦ. ΚΑΤΑ ΙΩΑΝΝΗΝ
