### ISSUE TITLE
hledger-web register does not show From/To accounts

### ISSUE THREAD

**Issue by thielema** [simonmichael/hledger#2227]
The Register page of current hledger-web-40 with an inacct query does not show To/From accounts for many transactions, even if there are only two accounts involved in the transaction, i.e. the To/From accounts column needs to display only one account.

Last time it worked correctly in hledger-web-1.32, but fails in hledger-web-1.33.

**Comment by thielema** [comment]
On Thu, 12 Sep 2024, thielema wrote:

> Last time it worked correctly in hledger-web-1.32, but fails in hledger-web-1.33.

With git-bisect I identified the commit 
2a99b3d45634f26cd62745ddce6136361001b3f8.

**Comment by thielema** [comment]
Problem is that the rewritten code with `tailDef` always removes the last account, whereas the original intention was to replace all accounts by a comma except the last one.
I have a patch here using NonEmpty. I'll submit it shortly.

**Comment by simonmichael** [comment]
Ouch, that's quite an obvious regression. It seems to suggest there aren't that many active hledger-web users..

Thanks for the report and fix! Please claim your $100 finder+fixer https://hledger.org/REGRESSIONS.html#regression-bounty when convenient.

**Comment by thielema** [comment]
On Tue, 24 Sep 2024, Simon Michael wrote:

> Ouch, that's quite an obvious regression. It seems to suggest there aren't that many active hledger-web users..

That would be sad. I use it frequently.

However, I missed the bug for several months because I do not always 
update to latest hledger when I am not looking for new features. It might 
be that other users just use hledger-web from their GNU/Linux distribution 
and the bug might not have been shipped with Debian&Co.

**Comment by simonmichael** [comment]
That's true, many users upgrade infrequently.

**Comment by simonmichael** [comment]
Hi @thielema, I encourage you to claim your $100 regression finder and fixer's bounty within the next 7 days. If not, it will be recorded as a project donation.
https://hledger.org/REGRESSIONS.html#regression-bounty

**Comment by wjdp** [comment]
![Image](https://github.com/user-attachments/assets/e2c80821-c5f4-42b8-8b41-6454468ea2cb)

Is this the reason the "To/From Account(s)" column is always empty?
