### ISSUE TITLE
Allow check recentassertions to respect --unmarked, --pending, --cleared

### ISSUE THREAD

**Issue by eddiegroves** [simonmichael/hledger#2229]
I have a situation where I've entered a future transaction (a car hire booking that is paid for at pickup) but I don't want the transaction included in the recentassertions check.

I've suggested a naive approach where it could support the --unmarked, --pending, --cleared though not sure how that would impact other check types...

**Comment by simonmichael** [comment]
I hear you. I'm not sure how you'd implement or present it exactly. We used to have some checks that took options, and some time ago I simplified those, removing the options, so they could be combined easily within one check command.

Sometimes I put a regular future-dated transaction in my future journal and it trips me up, perhaps in the same way. So instead I usually work around by making it a forecast transaction (requiring `--forecast` to enable it). This involves adding a ~ and a space. Eg, change
```
2025-01-01 description
  ...
```
to
```
~ 2025-01-01  description
  ...
```
Would this be enough ?

**Comment by eddiegroves** [comment]
Hi Simon thanks for the thoughts!

I am making extensive use of periodic transactions for budgeting and unfortunately in this case I am using the future dated  pending transactions in budget reports, so using periodic transaction would conflict.

Current report:
```
 Jun     || $134.83 [135% of $100.00] 
 Jul     ||       0 [  0% of $100.00] 
 Aug     ||       0 [  0% of $100.00] 
 Sep     || $490.14 [490% of $100.00] 
 Oct     ||       0 [  0% of $100.00] 

```

Changing to periodic:
```
 Jun     || $134.83 [135% of $100.00] 
 Jul     ||       0 [  0% of $100.00] 
 Aug     ||       0 [  0% of $100.00] 
 Sep     ||       0 [  0% of $590.14] 
 Oct     ||       0 [  0% of $100.00] 

```

This is not a show stopper by any means, and because `check` runs in chronological order I can ignore any errors it produces once it reaches the first future dated pending transaction.

Happy to close this as "won't fix" for now if you prefer  🙂

**Comment by simonmichael** [comment]
You could give the budget-related ptxns a distinct description and select only those with —budget=… or you could keep them in a separate file.. just some more workaround ideas.

**Comment by simonmichael** [comment]
Or just not use recentassertions. Are you finding it very helpful ?

**Comment by eddiegroves** [comment]
Moving the future pending transactions to another file is what I might do, that would work 👍

Using `recentassertions` is new in my check command and I don't run the check all the time (not in a pre-commit hook), just an occasional hygiene thing. I have found it handy has it points out some of the 'minor' accounts were missing assertions.

**Comment by simonmichael** [comment]
G’day all !

The --infer-equity flag generates postings to accounts named something like `equity:conversion:A-B:A` and `equity:conversion:A-B:B`, where A and B are the commodity symbols being converted between.

I feel these :A-B:* subaccounts 

- add noise

- complicate exporting to beancount, since currency symbols in account names generally aren't allowed there.

- complicate hledger check accounts and check -s, as seen in https://github.com/simonmichael/hledger/issues/2247

- are not much needed; you can always filter commodities with cur:

So I think I’d like to drop the subaccounts. —infer-equity would just use equity:conversion (or other conversion account you have designated). Do you see any problems with it ?

**Comment by simonmichael** [comment]
Deleted unrelated proposal mistakenly emailed here two days ago.
