### ISSUE TITLE
Custom time unit for timedot

### ISSUE THREAD

**Issue by aragaer** [simonmichael/hledger#2238]
Given that pomodoro is a popular method of tracking time spent on various activities it makes sense when people track time in units of "pomodoro" rather than hours or minutes.

Possible ways to use it:
- add an option to redefine `.` to be some other number of minutes instead of 0.25 hours
- add letter `p` meaning one pomodoro (and be able to set it to a custom value, not always 25 minutes)

**Comment by simonmichael** [comment]
To be precise: a timedot file records numbers, with no units attached. One dot is 0.25.

One thing you could do is this:

a.journal:
```
D 1.00 h            ; set a default commodity symbol
P 0000-01-01 h 60m  ; and a conversion rate of one h to 60 m
include a.timedot
```

a.timedot:
```
2024-01-01
a  .
```

```
$ hledger -f a.j print
2024-01-01 *
    (a)          0.25 h

$ hledger -f a.j print -V
2024-01-01 *
    (a)             15m

```

**Comment by simonmichael** [comment]
Or even just

a.journal:
```
P 0000-01-01 "" 60m
include a.timedot
```

**Comment by simonmichael** [comment]
It's probably not quite what you want. Another hack could be

a.journal:
```
D 1. pomodoro
P 0000-01-01 pomodoro 25m
include a.timedot
```

a.timedot:
```
2024-01-01
a  1
```

```
$ hledger -f a.j print
2024-01-01 *
    (a)    1.00 pomodoro

$ hledger -f a.j print -V
2024-01-01 *
    (a)             25m

```

**Comment by simonmichael** [comment]
No, that's why we need to add the journal file. This could be made clearer in the timedot doc.

**Comment by simonmichael** [comment]
I've added a doc update.

Can we close this, or is there still an unmet need ?

**Comment by aragaer** [comment]
If there is no plan to add extend timedot with additional (customizable?) unit I think this issue can be closed.

**Comment by simonmichael** [comment]
I'll close it; if someone comes up with a detailed plan we could reconsider.

**Comment by aragaer** [comment]
I've experimented with timedot and looks like changing the default unit changes all the units. Setting default unit to 25 minutes means that "30m" is now 12 minutes, "1d" is 600 minutes etc. Not the most intuitive behavior and definitely should be documented.

**Comment by simonmichael** [comment]
Please show a full repro of what you're doing. Maybe it's something non-experts will encounter in practice, maybe not ?

**Comment by aragaer** [comment]
a.journal:
```
D 1. pomodoro
P 0000-01-01 pomodoro 25m
include a.timedot
```

a.timedot:
```
2024-09-25
a  1
b  .
c  30m
d  1d
```

```
$ hledger -f a.journal bal -V
                 25m  a
                  6m  b
                 12m  c
                600m  d
--------------------
                644m
```

**Comment by aragaer** [comment]
I have checked the TimedotReader file and it seems that the simplest way is to add a new entry to `timeUnits` list. Unfortunately that means the value will be hardcoded.

Another approach is to use the tagged value, so that `a  pp` would count as two pomodoros rather than half a unit. That would require associating a value with some multiplier but at least it would be done outside timedot reader itself.

**Comment by simonmichael** [comment]
Thanks!

I had forgotten timedot supports those optional time units also. That does make your example appear a bit cursed - 30m becoming 12m, etc. Though it's functioning as documented, pretty much.

To contrast with this, could you mock up how you'd prefer things to work for this use case ?

**Comment by simonmichael** [comment]
One workaround could be to record pomodoros in your own preferred format and write a script that reads that as / converts that to journal entries.

**Comment by aragaer** [comment]
I'm seeing two different options here, depending on whether pomodoro should be a separate time unit (`a  1p`) or a way of tagging a logged time (`a  pp`). Either one would be fine.

The first one could be implemented by moving `timeUnits` list into the JournalParser object so that timedot reader could process additional types of units.

The second one means a list of tags and multipliers is provided in JournalParser as well and when creating tagged values we check that list.

However both cases require new directives/flags for the hledger itself as none of the existing directives seem to properly fit here.

**Comment by simonmichael** [comment]
At the UX level, I think we'll agree:

A person tracking pomodoros would like to conveniently record whole numbers of pomodoros. 

One of the desirable conveniences is to be able to record another one by just adding another character, as with time dots. Rather than having to delete and re-type a number.

And more generally, people may want to use the character-per-unit recording style for other things, like custom "pomodoros" of some other length; or anything else.

Timedot format can provide general character-per-unit recording if we add a character representing 1 (as . represents 0.25). It could be p, although that might seem too specific. Or something else: *, o, ', !, - etc..

Or, we could allow the meaning of `.` to be changed. These are what you suggested at the start.

And we know a journal file can add any unit to these bare numbers. And can define conversion rates from that unit to others.

And in this case we probably shouldn't use timedot's special time units syntax - or at least we shouldn't redefine those symbols in confusing ways.

**Comment by simonmichael** [comment]
And, we should try not to let things get too complicated. Timedot was originally very simple.

**Comment by simonmichael** [comment]
I wouldn't mind `'` (single quote) as the unit character, because it doesn't require the shift key, it's kind of like an "upper case `.`", and the upper case thing could be generalised to time letters ("upper case means 1, lower case means 0.25").

**Comment by simonmichael** [comment]
And a separate but connected topic: I have still some question about whether time letters should generate tag values (as they do now), or if they would be better as just commodity symbols. I don't remember just now why I chose the former.
