### ISSUE TITLE
it should be easier to find the exact regular expression syntax supported

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#224]
Notes: Regexps in hledger:

- come from the [regex-tdfa](http://hackage.haskell.org/package/regex-tdfa/docs/Text-Regex-TDFA.html) library. See that page for more details.
- are POSIX extended regular expressions-ish
- have some GNU word/text boundary extensions (\\<, \\>, \b, \B etc.)
- do not support (?i) etc.
- are case insensitive
- are infix matching (do not need to match the entire thing being matched)
- support (unnamed) parenthesised match groups, which can be referenced by \1 etc. in replacement patterns

Regexps are used eg in: 

feature | examples | limitations
--------------------------------|--------------------------------|--------------------------------
command line options                 | --alias '/REGEX/=...' | 
command line query arguments  | REGEX, desc:REGEX, tag:...=REGEX, cur:REGEX | 
hledger-web search                     | as above | 
CSV rules file conditional blocks | if REGEX ... |

**Comment by simonmichael** [comment]
hltp://hledger.org/manual#regular-expressions

**Comment by airtonix** [comment]
For complete peasant brains like myself, some concrete examples would be amazing.

**Comment by simonmichael** [comment]
@airtonix I have added some examples at https://hledger.org/dev/hledger.html#regular-expressions .
