### ISSUE TITLE
show total row in multi-period balance report

### ISSUE THREAD

**Issue by thielema** [simonmichael/hledger#2252]
`multiBalanceReportAsCsv` has a special case for not showing the total row for `LayoutTidy`. I do not see a reason for this special case and would like to remove it for consistency reasons. You can always suppress the total row with the `--no-total` option.

**Comment by simonmichael** [comment]
It's because "tidy" format is well defined outside of our project and it does not include a totals row. More details at https://hledger.org/dev/hledger.html#tidy-layout

**Comment by thielema** [comment]
On Mon, 14 Oct 2024, Simon Michael wrote:

> It's because "tidy" format is well defined outside of our project and it 
> does not include a totals row. More details at 
> https://hledger.org/dev/hledger.html#tidy-layout

If so, I'd suggest we omit those rows in HTML and FODS, too. I consider 
FODS to be a rich variant of CSV. If FODS is converted to CSV, e.g. by 
LibreOffice, it should be (almost) the same CSV as if exported by hledger 
directly.

Maybe I set no_total_ in ReportOpts in case of LayoutTidy in main 
'balance' function for consistent handling?

**Comment by simonmichael** [comment]
I thought --layout=tidy was only supported with CSV (*SV) output, and practically speaking only makes sense there ? I could be wrong.

**Comment by thielema** [comment]
On Mon, 14 Oct 2024, Simon Michael wrote:

> I thought --layout=tidy was only supported with CSV (*SV) output, and 
> practically speaking only makes sense there ? I could be wrong.

Before I started working on FODS output, there were already special cases 
for LayoutTidy in HTML exporting code, e.g. in 
multiBalanceReportAsCsvOrHtml:

https://github.com/simonmichael/hledger/blob/c3c95990fa42426e78e86f3045d6b547410a00fd/hledger/Hledger/Cli/Commands/Balance.hs

**Comment by simonmichael** [comment]
I don't remember giving any thought to viewing tidy data as HTML - I'd be ok with disabling it there if it saves time - but if it can be made to work consistently across CSV/FODS/HTML, even better.
