### ISSUE TITLE
hledger-web not compatible with new data-default-0.8.0.0

### ISSUE THREAD

**Issue by thielema** [simonmichael/hledger#2276]
When compiling `hledger-web` I get:
~~~~
[ 1 of 18] Compiling Hledger.Web.Settings ( Hledger/Web/Settings.hs, interpreted )

Hledger/Web/Settings.hs:87:5: error: [GHC-39999]
    • No instance for ‘Data.Default.Internal.Default
                         WidgetFileSettings’
        arising from a use of ‘def’
    • In the expression: def
      In a record update at field ‘wfsHamletSettings’,
      with type constructor ‘WidgetFileSettings’
      and data constructor ‘Yesod.Default.Util.WidgetFileSettings’.
      In the expression:
        def
          {wfsHamletSettings = defaultHamletSettings
                                 {hamletNewlines = AlwaysNewlines}}
   |
87 |     def -- Yesod.WidgetFileSettings
   |     ^^^
~~~~

Problem is `data-default-0.8.0.0` that was released yesterday. It does no longer re-export `Default` class from `data-default-class`. This is a breaking change, indeed the major version bump to 0.8 indicates that. `yesod` defines `Default` instance for `data-default-class`, not `data-default`. I asked the author of both packages, what package we shall prefer in the future:
https://github.com/mauke/data-default/issues/29

**Comment by simonmichael** [comment]
Thanks. (I've sent you a github repo collaborator invitation, which would allow more issue management powers if needed.)

**Comment by simonmichael** [comment]
@thielema do you know if there's anything we still need to do with bounds in hledger-web to avoid data-default-related build problems ?

My local build, and current stackage nightly, seem to be working without problems using


    data-default-0.8.0.0
    data-default-class-0.2.0.0

**Comment by thielema** [comment]
On Fri, 20 Dec 2024, Simon Michael wrote:

> @thielema do you know if there's anything we still need to do with bounds in hledger-web to avoid data-default-related
> build problems ?
> 
> My local build, and current stackage nightly, seem to be working without problems using
> 
> data-default-0.8.0.0
> data-default-class-0.2.0.0

I can build with Stack and Cabal (and GHC-9.10.1) now.
