### ISSUE TITLE
`hledger check commodities` doesn't check price directives

### ISSUE THREAD

**Issue by aragaer** [simonmichael/hledger#2280]
Accidentally found it this way:

```
commodity 1. "a0"

P 2024-10-31 a0 1

2024-10-31
 (assets)  1 "a0"
```

For a commodity with digits both commodity directive and a transaction require it to be surrounded by quotes. But price directive doesn't. And then it just happens to be a "different" commodity. For the journal above `hledger check commodities` will not report an error but `hledger bal --value=now,` will not convert the "a0" commodity to the default "" commodity.

**Comment by simonmichael** [comment]
Good catch! I have pushed several fixes:

- The above now gives a parse error. We were not requiring a space after P's first commodity symbol; now we do.
- `hledger check commodities` now also checks commodities in P directives.
- `hledger commodities` now also reports commodity symbols seen in P directives.
