### ISSUE TITLE
roi "Ratio has zero denominator" when --pnl account balances to 0

### ISSUE THREAD

**Issue by iartarisi** [simonmichael/hledger#2281]
I am trying to use hledger-roi and keep track of average cost using something similar to the method described in this [multicurrency accounting tutorial](https://www.mscs.dal.ca/~selinger/accounting/tutorial.html#4). That means that both the cash and stock amounts should always balance to zero.  In order to do that, all buy and sell commodity transactions go through an Income:Trading account (simplified below to just Income).

This crashes roi, I think, because it can't handle the Income account evaluating to 0

```
$ cat roi-example.journal 
P 2020/1/1 A GBP 100
2020/1/1 foo
    Assets                                  GBP -100
    Assets                                         1 A
    Income                                        -1 A
    Income                                   GBP 100

2020/2/1 doesn't matter what's in this transaction
    Equity                                  GBP -100
    Assets                                   GBP 100

$ hledger roi -f roi-example.journal --inv Assets --pnl Income -V
hledger: Ratio has zero denominator
$ hledger roi -f roi-example.journal --inv Assets --pnl Income -V --cashflow

IRR cash flow for 2020-01-01 - 2020-02-01
+------------++----------+
|            ||   Amount |
+============++==========+
| 2020-02-01 || GBP -100 |
| 2020-02-02 ||  GBP 100 |
+------------++----------+


TWR cash flow for 2020-01-01 - 2020-02-01
hledger: Ratio has zero denominator


$ hledger bal -f roi-example.journal -EV
             GBP 100  Assets
            GBP -100  Equity
                   0  Income
--------------------
                   0  
```

**Comment by adept** [comment]
Quoting from [roi manual](https://hledger.org/1.40/hledger.html#semantics-of---inv-and---pnl):
```
Query supplied to --inv has to match all transactions that are related to your investment. Transactions not matching --inv will be ignored.

In these transactions, ROI will conside postings that match --inv to be "investment postings" and other postings (not matching --inv) will be sorted into two categories: "cash flow" and "profit and loss", as ROI needs to know which part of the investment value is your contributions and which is due to the return on investment.
```

I think that the property "other postgres are either cash flows or PnL" does not hold for your initial transaction.

Try and separate your Income postings out:
```
P 2020/1/1 A GBP 100
2020/1/1 foo
    Assets                                  GBP -100
    Assets                                         1 A

2020/1/1 foo
    Income                                        -1 A
    Income                                   GBP 100

2020/2/1 doesn't matter what's in this transaction
    Equity                                  GBP -100
    Assets                                   GBP 100
```

**Comment by iartarisi** [comment]
Thanks for the reply @adept .

That does work for roi.  But those first two transactions don't balance to zero individually. 

```
hledger -f roi-example.journal check -s
hledger: Error: /.../roi-example.journal:2-4:
2 | 2020-01-01 foo
  |     Assets        GBP -100
  |     Assets             1 A

This multi-commodity transaction is unbalanced.
Automatic commodity conversion is not enabled.
The real postings' sum should be 0 but is: 1 A, GBP -100
Consider adjusting this entry's amounts, adding missing postings,
or recording conversion price(s) with @, @@ or equity postings.
```

**Comment by adept** [comment]
I can't reproduce your unbalanced transaction with hledger from tip. But lets backtrack. Do we at least agree that both TWR and IRR for your journal would be zero?

Regardless of what I think about the semantics of your journal, it is clear that division by zero should not be there, so lets at least fix that (via #2283 )

**Comment by iartarisi** [comment]
> Do we at least agree that both TWR and IRR for your journal would be zero?

> Regardless of what I think about the semantics of your journal, it is clear that division by zero should not be there, so lets at least fix that (via https://github.com/simonmichael/hledger/pull/2283 )

Yup, agreed. That's the issue I was raising here.

**Comment by simonmichael** [comment]
Thanks for the report @iartarisi and fix @adept. We've had many of these in the tricky roi calculations unfortunately, hopefully this is the last.
