### ISSUE TITLE
Amount calculation in csv rules?

### ISSUE THREAD

**Issue by yongli-abc** [simonmichael/hledger#2282]
Hi, my revolut statement looks something like below:

```
Date       | Description             | Amount    | Fee  | Currency    |
2024-10-05 | Exchanged to GBP        │  48.21    │ 0.48 │     GBP     │
```

This is a currency exchange transaction, the amount £48.21 is the total in-flow amount. The fee £0.48 is the exchange commission, so the net result is that £47.73 is added to my GBP balance.

I think in the journal i need to record like this:

```
2024-10-05 Exchnaged to GBP
    transfer:revolut-usd-gbp                   £-48.21    ; assuming i use a imaginary acct for transfer
    assets:bank:revolut:GBP                    £47.73
    expenses:fx-fees                           £0.48
```

How do I get the £47.73? It doesn't seem I can do amount calculations from the `csv.rules` file. Do I need to pre-process the csv file to generate a new field?

**Comment by adept** [comment]
You should be able to just leave it blank, and hledger will compute it from the other two amounts

**Comment by simonmichael** [comment]
> How do I get the £47.73? It doesn't seem I can do amount calculations from the `csv.rules` file. Do I need to pre-process the csv file to generate a new field?
> 

Hi,

That's correct, you can't do calculations in the CSV rules.

You could leave it blank, and hledger will infer it at runtime as Dmitry said.

But if you want it to be recorded explicitly in the journal,

- Yes you could preprocess the CSV data to add it there
- Or as part of conversion/import you can use hledger print -x to get explicit output, and save that in your journal.
- Or, hledger import -x might achieve the same - I'm not sure, it's worth a try.

Best

**Comment by yongli-abc** [comment]
I tried leaving it blank, but got transaction unbalanced error. Here's a minimal example.

test.csv
```
Type,Product,Started Date,Completed Date,Description,Amount,Fee,Currency,State,Balance
EXCHANGE,Current,2024-07-21 19:11:39,2024-07-21 19:11:39,Exchanged to EUR,236.69,2.37,EUR,COMPLETED,318.17
```

rules file
```
skip 1

fields ,,StartDate,date,description,Amount,Fee,Currency,,

date-format %Y-%m-%d %H:%M:%S

if %Fee [1-9]
    account1 transfer:revolut
    amount1 -%Amount
    account2 assets:bank:revolut:%Currency
    account3 expenses:fx-fees:revolut
    amount3 %Fee
```

Got the error:
```
hledger: Error: data/revolut/test.csv:1-0:
1 | 2024-07-21 Exchanged to EUR
  |     transfer:revolut              EUR-236.69
  |     assets:bank:revolut:EUR       EUR-236.69
  |     expenses:fx-fees:revolut         EUR2.37

This transaction is unbalanced.
The real postings' sum should be 0 but is: EUR-471.01
Consider adjusting this entry's amounts, or adding missing postings.
```

Am I not doing correctly by leaving out `amount2`?

**Comment by yongli-abc** [comment]
Oh I see, the no-amount account has to be the last account (account3).

**Comment by simonmichael** [comment]
Or did I misread your rules file ? If so, apologies. I’m having internet trouble.

**Comment by simonmichael** [comment]
@yongli-abc Hi, I tested with your example. The recent problem was that the "Amount" field name you used in the fields list has special meaning (it sets amount1 and amount2). I modified the example, this time using a defensive style where I just safely name all the csv fields and then use them below:
```
skip 1

fields type_, product_, started_date_, completed_date_, description_, amount_, fee_, currency_, state_, balance_

date %completed_date_
date-format %Y-%m-%d %H:%M:%S

if %fee_ [1-9]
    account1 transfer:revolut
    amount1 -%amount_
    account2 assets:bank:revolut:%currency_
    account3 expenses:fx-fees:revolut
    amount3 %fee_
```
```
$ hledger -f a.csv print
2024-07-21
    transfer:revolut                 -236.69
    assets:bank:revolut:EUR
    expenses:fx-fees:revolut            2.37
```
```
$ hledger -f a.csv print
2024-07-21
    transfer:revolut                 -236.69
    assets:bank:revolut:EUR           234.32
    expenses:fx-fees:revolut            2.37
```
Also I tried `hledger import a.csv` and confirmed that it applies -x automatically, so the missing amount is filled in during `import`.

Hope it helps!

**Comment by simonmichael** [comment]
Seems resolved.
