### ISSUE TITLE
hledger-ui: Cannot switch from "costs view" to "market values view"

### ISSUE THREAD

**Issue by lakshayg** [simonmichael/hledger#2284]
I was trying to switch between the "costs view (B)" and "market values view (V)" when I noticed inconsistency in how B and V behave. I have summarized my observations below.

| Current View | Keypress | Result       |
|--------------|----------|--------------|
| normal       | B        | costs        |
| normal       | V        | market value |
| market value | B        | costs        |
| market value | V        | normal view (regardless of the previous view) |
| costs        | B        | previous view (normal or market value) |
| costs        | V        | no change    |

The last two cases (the ones where current view is "costs") seem unexpected.
I would have expected pressing B in costs view would turn it off and go to normal view
and pressing V in costs view would take me to the "market value" view.

---

Platform: macOS 14.7

```
$ hledger --version
hledger 1.40-g0f31974c5-20240909, mac-aarch64
```

Here's a small ledger where I'm able to reproduce this issue.

```
commodity 1,000.00 USD
commodity 1,000.00 XYZ

P 2024-09-30 XYZ 200 USD

account assets:brokerage:cash
account assets:brokerage:XYZ
account equity:opening_balance

2024-01-01  opening balance
    assets:brokerage:cash         1,000.00 USD
    equity:opening_balance


2024-02-01  buy 2 XYZ
    assets:brokerage:XYZ      2 XYZ @@ 200.00 USD
    assets:brokerage:cash             -200.00 USD
```

**Comment by simonmichael** [comment]
I can reproduce. This seems to have regressed in hledger-ui-1.21 (or possibly 1.20.4). 

Thanks for the report! Please claim your $50 regression finder bounty :
https://hledger.org/REGRESSIONS.html#regression-bounty
