### ISSUE TITLE
Use exchange rates in reverse

### ISSUE THREAD

**Issue by mvhulten** [simonmichael/hledger#2287]
I have this exchange rate:

```
P 2024-11-18 19:00:00 EUR 11,664 NOK
```

but instead of using this to convert EUR from NOK, market values of transactions in the past are used when I run `hledger balance MyAccount --value=now,EUR`.  I want that the above works as this:

```
P 2024-11-18 19:00:00 NOK 0,08573388 EUR
```

**edit:** I was hoping that `--show-reverse` would do that, but after realising that this is only used from the `prices` command (not for e.g. `balance`), I reworked this issue… which – I now realise – may be more of a support issue than a bug report (*maybe* it is a feature request).

I am running hledger 1.33 on OpenBSD.

**Comment by simonmichael** [comment]
@mvhulten thanks - to save confusion, could you post a minimal repro when you have time ?

**Comment by simonmichael** [comment]
PS I think it's this: an declared forward price is always preferred over an inferred reverse price (https://hledger.org/dev/hledger.html#finding-market-price). I think the workaround is simply to add more forward price declarations.

**Comment by mvhulten** [comment]
In my MWE it works as I want and according to the documentation.

```ledger
P 2023-01-01 16:00:00 EUR 10,0 NOK
P 2024-11-18 16:00:00 EUR 11,0 NOK

2024-01-14 * conversion
    EuroAccount     100,00 EUR @12,0 NOK
    KronerAccount
```

As expected, today's value of 11,0 NOK/EUR takes precedence.
In my more complex multi-file ledger such a more recent declared price is ignored.

I will look into it better and find out where it fails.

**Comment by simonmichael** [comment]
--debug 2 may be helpful.

**Comment by mvhulten** [comment]
```ledger
commodity EUR
    format 100,00 EUR
commodity NOK
    format 100,00 NOK

2022-07-10 * Opening balances
    Activa:Sbanken:checking                           30,00 NOK
    Vermogen:Openingsbalansen

# FIXME: this overrules the subsequent declared price
2024-06-13 * Currency transaction
    Activa:Sbanken:saving                        -60.000,00 NOK @0,0872646 EUR
    Activa:Commerzbank:checking

# subsequent declared price
P 2024-11-18 19:00:00 EUR 11,664 NOK
```

When I convert my balance to EUR, I expect to get 2,57 EUR according to the final declared price.
However, I get instead:

```bash
$ hledger @.hledgerrc bal Sbanken:checking -X EUR --debug 2
seeking NOK to EUR price using forward prices
valuation date: 2024-11-18
trying: NOK>EUR
shortest path from NOK to EUR: NOK>EUR
price chain:
[ MarketPrice
  { mpdate = 2024-06-13
  , mpfrom = "NOK"
  , mpto = "EUR"
  , mprate = 0.0872646
  }
]
            2,62 EUR  Activa:Sbanken:checking
--------------------
            2,62 EUR
```

Removing the "FIXME" transaction results in the expected balance.
But that transaction is older than the declared price and I would not expect it to influence the final converted balance.

**Comment by mvhulten** [comment]
According to the [manual](https://hledger.org/1.33/hledger.html#finding-market-price), a *declared market price* or *inferred market price* is preferred, and only thereafter it looks at a *reverse market price*.

These lines contain "forward" market prices:

```
2024-06-13 * Currency transaction
Activa:Sbanken:saving                        -60.000,00 NOK @0,0872646 EUR
Activa:Commerzbank:checking

P 2024-11-18 19:00:00 NOK 0,0857338820301783 EUR
```

When doing `-X EUR`, it simply multiplies with one of those numbers (0.087…), in this case the latter because it has a more recent date.

Compared with the above, this line is more complex:

```
P 2024-11-18 19:00:00 EUR 11,664 NOK
```

It is a *reverse market price*, where the kroner need to be *divided* by the number (11.664).

One reason for this behaviour (treating *reverse market price* at a lower priority) could be that direct and reverse may be used for different "sell" and "buy" rates, respectively.

Is there a way to override and give the reverse market price precedent, or always use the newer date nomatter if it is direct or reverse?

(In my journals I use *,* as a decimal separator; in-text I used *.* as a decimal separator.)

**Comment by mvhulten** [comment]
There are at least two different work-arounds here, I think.

- I can type in the reciprocal number.  This is inconvenient as EUR/NOK markets are not usually presented as such.  Making more obvious if the last market price is used (direct or reverse), I could use `-V` instead of `-X EUR` as it will still show NOK if the *latest* market price is reverse.

- Or I can completely disable the convenient `--infer-market-prices`.

Both have downsides, but often such things you just need to get used to.

**Comment by simonmichael** [comment]
Thanks @mvhulten, I'm just getting to look at this now.

> When I convert my balance to EUR, I expect to get 2,57 EUR according to the final declared price.
> However, I get instead:

I believe you have --infer-market-prices in a config file, which is causing the `@12,0 NOK` cost to generate a market price. You could compare the behaviour with `-n`. The debug output could be more informative about this, reopening to remind myself. 

Does that help ?

**Comment by simonmichael** [comment]
I have improved the --debug=2 output, which now looks more like
```
seeking NOK to EUR price using forward prices
valuation date: 2024-11-18
use prices inferred from costs? yes
forward prices:
 2024-06-13 NOK>EUR 0.0872646
 2024-11-18 EUR>NOK 11.664
trying: NOK>EUR
shortest path from NOK to EUR: NOK>EUR
price chain:
 2024-06-13 NOK>EUR 0.0872646
```
