### ISSUE TITLE
Drill down into account doesn't respect period boundary, but instead aligns with calendar

### ISSUE THREAD

**Issue by jbrains** [simonmichael/hledger#2293]
I'm using `hledger-ui` to browse my ledger by year and when I drill down into an account's register, the transactions listed align with the calendar year instead of my fiscal year boundary, even though the balances match my fiscal year boundary.

- hledger-ui 1.40
- Ubuntu 22.04.5

Summary of example: launch `hledger-ui` with period `yearly 11/01`, using `Shift+Down` to shrink to the annual period, then `Shift+Left` to browse earlier fiscal years. The balances are correct, but when I drill down into the register of an account, `hledger-ui` lists transactions from the calendar year instead of the fiscal year (November 1 - October 31).

# Details

```
$ hledger-ui --file ledger/main.journal --tree --theme=greenterm --value="then,CAD" --period="every 11/01"
```

Today is November 23, 2024, so when I press `Shift+Down`, I see "main.journal  2024". I understand this means the period 2024-11-01 to but excluding 2025-11-01.

I press `Shift+Left`, I see "main.journal 2023". I understand this means the period 2023-11-01 to but excluding 2024-11-01.

I choose `Cash Accounts`. I see "main.journal cash balances at end of 2023". I verify that these balances match the real-life cash account balances as at the end of 2024-10-31. (This is "the fiscal year that contains 2023-12-31, I guess.)

I choose one of my bank accounts. I see "$ACCOUNT_NAME transactions in 2023". Unfortunately, I see transactions from 2023-01-01 to 2023-12-31 and not what I expect, which is transactions from 2023-11-01 to 2024-10-31.

**Comment by simonmichael** [comment]
@jbrains, thanks for the report. 

hledger-ui generally is not aware of report intervals.
And the [period navigating keys](https://hledger.org/1.40/hledger-ui.html#keys) are not aware of custom intervals; I believe they only operate on julian calendar years/months/weeks/days.

**Comment by simonmichael** [comment]
I consider it a doc bug, and I have added a mention of this to the hledger-ui manual. Though a PR to make this smarter would be welcome.

**Comment by jbrains** [comment]
Understood. Thank you for clarifying the documentation. As for a PR, that's not _impossible_, but it's a considerable _challenge_ given my relative inexperience with Haskell. Even so, I might feel up to trying once I have finished my bookkeeping for the year.
