### ISSUE TITLE
Renaming functions `first3` and `second3`

### ISSUE THREAD

**Issue by ivanperez-keera** [simonmichael/hledger#2294]
Hi,

Should the functions `first3` and `second3` be called `fst3` and `snd3` for uniformity with Haskell's Prelude's naming conventions?

`first` and `second` are used in arrows to apply a function to the first and second components of a pair, respectively.

**Comment by simonmichael** [comment]
Hi @ivanperez-keera, thanks for the comment. In fact these are part of a family of functions that currently goes up to sextuples; that's the reason for the more verbose english names (the abbreviations start to break down as you get to fth4 fth5 sth6). Hopefully the clash is not causing problems for anyone.

**Comment by ivanperez-keera** [comment]
Not really. I found it by coincidence and saw an opportunity to make things a bit more consistent with `Prelude`.

If you don't think this is worth doing, feel free to close the ticket.

**Comment by simonmichael** [comment]
At the moment I think it's not worth doing. Thanks for the suggestion, more welcome.
