### ISSUE TITLE
hledger-web-1.41 fails to compile: src/Yesod/Core/Dispatch.hs:247:32: error: [GHC-83865]  Couldn't match expected type ‘GzipSettings’ with actual type ‘RequestLoggerSettings’

### ISSUE THREAD

**Issue by yurivict** [simonmichael/hledger#2297]
See the log [here](https://freebsd.org/~yuri/hs-hledger-web-1.41.log).

ghc-9.6.6
FreeBSD 14.1

**Comment by simonmichael** [comment]
Thanks for the report @yurivict (and for packaging). I have pinged the upstream issue [here](https://github.com/yesodweb/yesod/issues/1854#issuecomment-2532550946). The workaround is to add `--constraint 'wai-extra <3.1.17'` to the cabal build command.

**Comment by simonmichael** [comment]
https://hackage.haskell.org/package/yesod-core's revision 1 has fixed this, so the above workaround is no longer needed, once you have done a `cabal update`.
