### ISSUE TITLE
balance shows wrong amount display style with this journal

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#230]
julm provided this test journal which provokes wrong output in a weirdly fragile way:
```
; simplified from julm's http://vpaste.net/qN238

D 1000,00€

1/1
      a:b         0

1/2
      a:1      4000,58  ; not starting this account name component with a digit fixes it
      a:D     -1000,58  ; lower-casing the D fixes it
      e       -3000

; hledger bal 
;             €3000.00  a     <------ not like the others
;             4000,58€    1
;            -1000,58€    D
;            -3000,00€  e
; --------------------
;                    0
```

**Comment by MarkusTeufelberger** [comment]
Had the same issue with "USD" (first time it appears in a balance output, it gets prepended to the amount) but didn't get around to minimizing my ledgers to a test case yet...

**Comment by simonmichael** [comment]
Since I see it wasn't mentioned here: it is a weakness in hledger's Amount arithmetic, there are some corner cases where the display style is not propagated correctly as amounts are combined. Julien Moutinho debugged and prepared a preliminary fix, which we need to rework.

**Comment by thdox** [comment]
On top of what is described above, I have also obtained amounts in balance output that looks like the first line that I have added to example above:

    hledger bal 
               3000.00 €  z     <------ I also get this
                €3000.00  a     <------ not like the others
                4000,58€    1
               -1000,58€    D
               -3000,00€  e
    --------------------
                       0

**Comment by simonmichael** [comment]
Another symptom of the [amount style](https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Data/Types.hs#L91) being lost during amount arithmetic.

**Comment by simonmichael** [comment]
A puzzling interaction of -V and the default commodity directive, from private email:
```
; when you uncomment this, hledger bal -V's final balance changes from 0 to 0.48 D
; (also D symbol is placed inconsistently, cf #230)
;D 1000.00 D

P 2015/08/14 AAAA   41.66
P 2015/08/14 BBBB   74.62
P 2015/08/14 CCCC  32.39

2015/08/15
    a  2.4120 AAAA @@ 100
    a  0.3350 BBBB @@ 25
    a  0.7718 CCCC @@ 25
    b
```

**Comment by simonmichael** [comment]
For the record, the above example is handled correctly by 0.23.3 but not by 0.24.

**Comment by simonmichael** [comment]
https://github.com/simonmichael/hledger/commit/40ab1e1 broke it.
