### ISSUE TITLE
--budget doesn't do anything with incomestatement

### ISSUE THREAD

**Issue by lowercasename** [simonmichael/hledger#2302]
From the docs it appears that `incomestatement` should take the `--budget` command, like `balance`. But I don't see that happening (`hledger 1.41, mac-aarch64`):

```
> hledger bal --budget -M

Budget performance in 2024-11-01..2024-12-31:

                           ||                         Nov                                Dec
===========================++================================================================
...
 expenses                  ||   £36.00 [1% of  £2,453.22]    £3,071.67 [ 125% of  £2,453.22]
 expenses:bills            ||   £36.00 [7% of    £532.22]      £384.67 [  72% of    £532.22]
...
---------------------------++----------------------------------------------------------------
                           ||        0 [               0]            0 [                  0]
                           
> hledger is --budget -M
Monthly Income Statement 2024-11-01..2024-12-31

                           ||     Nov         Dec
===========================++=====================
 Revenues                  ||
---------------------------++---------------------
...
---------------------------++---------------------
                           ||       0     £633.51
===========================++=====================
 Expenses                  ||
---------------------------++---------------------
 expenses:bills            ||  £36.00     £384.67
...
---------------------------++---------------------
                           ||  £36.00   £3,071.67
===========================++=====================
 Net:                      || £-36.00  £-2,438.16
```

(I've removed most of the lines, but the point is that `is` doesn't show the square bracketed numbers and percentages).

**Comment by simonmichael** [comment]
Thanks for the report. But `--budget` is only supported by the `balance` command at present. Which docs made you think otherwise ?

**Comment by lowercasename** [comment]
The section here: https://hledger.org/1.41/hledger.html#incomestatement

<img width="802" alt="Screenshot 2024-12-17 at 18 46 03" src="https://github.com/user-attachments/assets/c5b281d6-3aa1-4470-bdbb-3d210cb90d38" />

Have I misread the docs somehow?

**Comment by lowercasename** [comment]
I get the same with the `--help` flag on the command line:

```
> hledger is --help
incomestatement [OPTIONS] [QUERY]
  Show revenue inflows and expense outflows during the report period.
  Amounts are shown with normal positive sign, as in conventional
  financial statements.

Flags:
     --sum                  show sum of posting amounts (default)
     --valuechange          show total change of period-end historical
                            balance value (caused by deposits, withdrawals,
                            market price fluctuations)
     --gain                 show unrealised capital gain/loss (historical
                            balance value minus cost basis)
     --budget               show sum of posting amounts compared to budget
                            goals defined by periodic transactions
```

**Comment by simonmichael** [comment]
You've read them right, that does seem like a bug. 

Flags listed under "General * flags" headings are not expected to have an effect with all commands, which sometimes surprises people.

But here it's in the command-specific "Flags" section, which is definitely wrong. This changed in hledger-1.21. Thanks!

I'll either remove the flag, or (better ?) someone could add --budget support to incomestatement. I'm not sure how big or small a task that is.

Does this qualify for https://hledger.org/REGRESSIONS.html#regression-bounty ? One or two bounties have been granted for 0.21, so I think yes. Please claim your $50 regression finder's bounty!

**Comment by simonmichael** [comment]
Yes I see, perfectly valid finder's bounty. I'll clarify that page a bit.

**Comment by simonmichael** [comment]
Dropped the --budget option from bs/bse/cf/is commands.
