### ISSUE TITLE
Off-by-one error for year in week name of first week of the year

### ISSUE THREAD

**Issue by lowercasename** [simonmichael/hledger#2304]
It looks like the first week of 2025 is being printed as `2024-W01`, not `2025-W01` in balance and income statement output. This is with `--forecast` enabled.

<img width="1058" alt="Screenshot 2024-12-19 at 13 59 41" src="https://github.com/user-attachments/assets/f3bc4474-70d0-4d77-9360-4a6672bafc9d" />

The sort of bug you only get to catch once a year, like seeing Santa Claus!

**Comment by BardenB** [comment]
This may be because January 1 is on a Wednesday, so in many conventions, week 1 will "start" in 2024.

**Comment by simonmichael** [comment]
That was hard to see! There was even a test expecting the buggy output. Now fixed in master, thanks for the report.
