### ISSUE TITLE
'hledger add' seems to ignore the second account name

### ISSUE THREAD

**Issue by lowercasename** [simonmichael/hledger#2305]
When running 'hledger add' with prefilled information on the command line, the second account name seems to be ignored entirely:

```
> hledger -f test.journal add today Shopping assets '$-20' expenses:fruit '$10' expenses:soap '$10'
Adding transactions to journal file /Users/username/test.journal
Any command line arguments will be used as defaults.
Use tab key to complete, readline keys to edit, enter to accept defaults.
An optional (CODE) may follow transaction dates.
An optional ; COMMENT may follow descriptions or amounts.
If you make a mistake, enter < at any prompt to go one step backward.
To end a transaction, enter . when prompted.
To quit, enter . at a date prompt or press control-d or control-c.
Date [today]: 
Description [Shopping]: 
Account 1 [assets]: 
Amount  1 [$-20]: 
Account 2 [$10]: 
```

I would expect `Account 2` to be `expenses:fruit`, given the docs:

```
add [OPTIONS] [DATE [DESCRIPTION [ACCOUNT1 [AMOUNT1 [ACCOUNT2 [ETC...]]]]]]
```

This makes it impossible to add a transaction with more than one pre-specified account on the command line, which makes scripting needlessly hard.

**Comment by lowercasename** [comment]
I'm not strong with Haskell, but I wonder if this is the issue? Slicing off 2 rather than 1 on each pass? https://github.com/simonmichael/hledger/blob/02ffc5ab751afec9cb300e91136acb7d07ebe021/hledger/Hledger/Cli/Commands/Add.hs#L242

**Comment by simonmichael** [comment]
@lowercasename your fix seems to work! Thanks!
