### ISSUE TITLE
Balance assertions to skip virtual postings; so the --real/-R flag or real: query would have impact

### ISSUE THREAD

**Issue by iron-mors** [simonmichael/hledger#2307]
1st the **Background**:
I built my hledger around the following concepts:
- I have CSV files from my bank account which are unchange'able, and are the source of truth.
- I set up .rules files which assign each transaction to appropriate categories
- I used one of the approaches to budgeting - envelope budgeting. And for this I use virtual accounts to maintain a virtual envelopes for budget categories (e.g. [assets:budget:groceries]). 
- I have a separate CSV file where I set up for 1st of every month the value for each budget category (similar to YNAB)
- Using "real:1" shows me the "real" balance of accounts
- Using "real:0" shows me how much I have for each budget (and then the bank account balance should be shown as 0 - because every $ has a job)

2nd the **Problem**:
- My CSV files from the bank have the balance column. So I thought: Great! I'll be able to check every step of the way if what I have in the journals meets what my bank is stating. 
- But when I tried to apply the balance column as an assertion I found out after some digging that there is an obstacle for this approach. And it's in the manual:
"Balance assertions always consider both real and [virtual](https://hledger.org/1.41/hledger.html#virtual-postings) postings; they are not affected by the --real/-R flag or real: query."

3rd the **Wish**:
- Can the assertion please take into consideration the "real" flag? That way I can filter out the virtual postings and verify that the real balance is "true".

Thank you for reading, and thank you for creating this spectacular piece of software.

**Comment by simonmichael** [comment]
I'm glad you're enjoying it!

The problem with balance assertions respecting the real flag is that the real flag pretty quickly becomes useless, you'd have to either leave it always on or always off depending how you wrote your balance assertions. I experienced this with --auto in the past. I think it's better that balance assertions depend only on the data.

They could ignore virtual postings entirely, in principle. But hledger's assertions consider postings of any kind. That's simplest, most likely to make register balances correspond to balance assertions (helpful for troubleshooting), and it's how they work in Ledger (I'm guessing).

However, your real bank account should have only real postings in it, so you should be able to assert its balance regardless of virtual budget balances you've added elsewhere. Are you perhaps asserting `assets` instead of `assets:bank:checking` ?

The above should resolve it but there's another option which is to keep your budget envelopes under the real account, and don't bother with virtual postings.

**Comment by iron-mors** [comment]
Thank you for taking the time to respond.
"Are you perhaps asserting assets instead of assets:bank:checking ?" - I'm asserting assets:bank:account1 and assets:bank:account2

"(...) keep your budget envelopes under the real account, and don't bother with virtual postings."
That's one approach I considered. I didn't want to keep the budget accounts under a specific "physical" checking account - because I like the "assets:budget:*" structure of virtual envelopes which is separate from the physical ones.

I settled for a set of rules that do the magic and all in all I was able to match what I had in my bank statements. I've turned the assertions off.
When I use "real:1" in reports it shows me the true balances of the accounts (which I need e.g. to verify if hledger's state is the same as reality).

And when I don't set "real" then it shows the full structure of the budget envelopes, and the balance of checking accounts as "0" - so all the $ have a job :)

I just realized that I might try to write the assertion to "0" and see where it takes me. Something like this (previously I tried it on the non-virtual account with the balance value from the statement):
2024-12-13 Some transaction
    expenses:company:insurance             1 234.56
    assets:bank:account2              -1 234.56
    [assets:budget:company:insurance]     -1 234.56
    [assets:bank:account2]             1 234.56 = 0

I'm closing the issue and wishing all the best in the brand new upcoming 2025th year.

**Comment by nskobelevs** [comment]
I've a similar workflow to @iron-mors of using virtual postings for envelope budgeting and this assertion behaviour really does not play well with it.

There's two main options here, neither of which I'm a fan of:
* Do manual reconciliation to make sure things align while also not being able to use `recentassertions` to force myself to do so
* Use the balance that includes virtual postings which is _pretty_ meaningless and doesn't actually match what would be in the account


> However, your real bank account should have only real postings in it, so you should be able to assert its balance regardless of virtual budget balances you've added elsewhere. Are you perhaps asserting assets instead of assets:bank:checking ?

I believe a common approach here is to use `[]` posting so even the virtual budget transaction properly balance. For example:
```
2025-01-10 * Some Shop
    Expenses:Groceries                 $100.00
    Assets:Current                    $-100.00
    [Assets:Current]                   $100.00
    [Assets:Budget:Groceries]         $-100.00
```

> and it's how they work in Ledger (I'm guessing).

For what it's worth, ledger tracks the real balance separately for this. (See [this issue](https://github.com/ledger/ledger/issues/543))

In my opinion this is ideal as not only does the `--real` flag work as expected in this case but it also allows to assert the two balances individually.

> another option which is to keep your budget envelopes under the real account, and don't bother with virtual postings.

While an option I think using virtual postings for transactions that aren't "real" money movement makes genuine sense as it allows to use the `--real` flag to quickly separate actual accounts that have real world meaning to just other tracking accounts so having this be a real account isn't ideal imo.

**Comment by simonmichael** [comment]
I'm not much interested in virtual postings these days; I think they add complexity and don't carry their weight as a feature. I can use names or tags to classify accounts and postings. So I'm having a hard time following this in detail. But I'd be glad to test a PR with docs if someone wants to try.
