### ISSUE TITLE
A cash tracker that exports to CSV to work with hledger

### ISSUE THREAD

**Issue by jon49** [simonmichael/hledger#2308]
I made this little app that anyone can clone and put on their own server to track cash transactions.

https://github.com/jon49/cash

**Comment by simonmichael** [comment]
Nice! Add a screenshot and I'll add it to plaintextaccounting.org for you ?

**Comment by jon49** [comment]
Sure, thanks!

![Screenshot from 2024-12-31 12-12-34](https://github.com/user-attachments/assets/0e423f6f-fbbd-427e-89a4-8adfe925689e)

**Comment by simonmichael** [comment]
In your readme I meant. I have added the link.
