### ISSUE TITLE
Does hledger-web support different UI language?

### ISSUE THREAD

**Issue by weakish** [simonmichael/hledger#231]
I want to make hledger web to display in Chinese.
It seems that I need to edit the source file directly?
Or am I miss something?

**Comment by simonmichael** [comment]
Great! Unfortunately, yes that is true. The Yesod framework has some support for i18n, we should make use of that.

**Comment by simonmichael** [comment]
Needs discussion/developers, closing until they appear..

**Comment by mkaito** [comment]
Well, I would love to use hledger-web to make ledger accounting available to my wife, who only speaks Spanish. I'm happy to help with text translation, but don't know enough Haskell to help make it happen.

**Comment by simonmichael** [comment]
@mkaito, or anyone who would like to try, we'd be happy to help you work on it in the #hledger IRC channel. What needs to happen is some i18n. There is (deliberately) not a lot of text in the UI, so it's not *too* scary a task. But haskell i18n is not widely discussed yet. https://wiki.haskell.org/Internationalization_of_Haskell_programs is one place to start research.
