### ISSUE TITLE
Bug with includes files and hledger-web

### ISSUE THREAD

**Issue by julpec** [simonmichael/hledger#234]
I didn't have this problem with hledger-web 0.23.3 but with 0.24.1 it's not possible to add a transaction with multiple files.

I have this error message on my browser : 

> Handler/Post.hs:49:7-68: Irrefutable pattern failed for pattern (errs1, [date, desc, journalpath])

This is when I start hledger-web with a multiple file journal like this

> ;;
> !include plan.journal
> 
> !include 2013/ecritures-2013.journal
> !include 2014/ecritures-2014.journal

I can not write on this file or the include's one.

I made a test with a "normal" journal file (i.e. without includes) and it's working.

**Comment by simonmichael** [comment]
Thanks for the report. Submitting an empty add form also triggers this, even without an include.
```
curl -i http://localhost:5000/journal -d 'action=add'
```

**Comment by simonmichael** [comment]
Ignore those false starts, it's not fixed yet (ie currently you can't use hledger-web to add entries to a journal file which uses the include directive).

**Comment by simonmichael** [comment]
This is fixed in master; close when released. As a consequence, when there are includes the add form now reveals the full path of the journal files.

**Comment by simonmichael** [comment]
Fixed in 0.25.
