### ISSUE TITLE
hledger-web : base url change with several links

### ISSUE THREAD

**Issue by julpec** [simonmichael/hledger#235]
Hello

I have install a hledger-web instance and I start it with this command

> hledger-web --server --port=5001 --base-url=https://my.domain.org/hledger -f compta/compta.journal

The last parameter of my url (/hledger) is not maintained with several links in the web interface, for example when I click on the date of a transaction (so I get this type of link : https://my.domain.org/journal#2014-10-07 and a great 404 error)

There is no problems with the sidebar. All the bad links are in the main panel.

Thanks

**Comment by simonmichael** [comment]
Fixed I believe.. better late than never! julpec could you confirm ?

**Comment by julpec** [comment]
Hello

I tried to upgrade but I don't know how to do this (so, I can not see if it's working).

Here is my output : 

```
hledger@pacini:~/.cabal$ cabal update
Downloading the latest package list from hackage.haskell.org
hledger@pacini:~/.cabal$ cabal install hledger hledger-web
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: hledger-0.26 (user goal)
trying: hledger-0.26:-old-locale
next goal: time (dependency of hledger-0.26:-old-locale)
rejecting: time-1.4/installed-96b... (conflict: hledger-0.26:old-locale =>
time>=1.5)
trying: time-1.5.0.1
trying: shakespeare-text-1.1.0/installed-073... (dependency of hledger-0.26)
next goal: shakespeare (dependency of hledger-0.26)
rejecting: shakespeare-2.0.4/installed-d58... (conflict: time==1.5.0.1,
shakespeare => time==1.4/installed-96b...)
rejecting: shakespeare-2.0.6, 2.0.5, 2.0.4.1, 2.0.4, 2.0.3, 2.0.2.2, 2.0.2.1,
2.0.2, 2.0.1.2, 2.0.1.1, 2.0.1, 2.0.0.3, 2.0.0.1, 2.0.0, 1.2.1.1, 1.2.1,
1.2.0.4, 1.2.0.3, 1.2.0.2, 1.2.0.1, 1.2.0, 1.0.5.1, 1.0.5, 1.0.4, 1.0.3.1,
1.0.3, 1.0.2, 1.0.1.4, 1.0.1.3, 1.0.1.2, 1.0.1.1, 1.0.1, 1.0.0.2, 1.0.0.1,
1.0.0, 0.11, 0.10.3.1, 0.10.3, 0.10.2, 0.10.1.1, 0.10.1, 0.10.0 (conflict:
shakespeare-text => shakespeare==2.0.4/installed-d58...)
```

Can you help me ?

Thanks

**Comment by simonmichael** [comment]
Quite possibly your installed packages are making it hard for cabal to figure out the install plan. Try nuking them, or creating a new cabal sandbox, or using stack install (recommended) - see the download page for details.
