### ISSUE TITLE
Can not install on Linux Debian Jessie

### ISSUE THREAD

**Issue by thdox** [simonmichael/hledger#240]
Hi Simon,
I upgraded my Linux system from Debian Wheezy to Debian Jessie. Jessie is the to be "stable" debian to be published on 25-Apr-2015.

I installed using the commands

    sudo aptitude install ghc cabal-install happy
    sudo aptitude install libncurses-dev
    cabal update
    cabal install hledger

But it fails while compiling one of the dependencies.

--------------8<--------------8<--------------8<--------------8<--------------8<--------------8<--------------8<--------------
Preprocessing library control-monad-free-0.6.1...
[1 of 3] Compiling Control.Monad.Free ( Control/Monad/Free.hs, dist/build/Control/Monad/Free.o )

Control/Monad/Free.hs:45:67:
    Can't make a derived instance of `Typeable (Free f a)':
      `Free' must only have arguments of kind `*'
    In the data declaration for `Free'
--------------8<--------------8<--------------8<--------------8<--------------8<--------------8<--------------8<--------------

There is a github issue opened for that, see https://github.com/pepeiborra/control-monad-free/issues/4

I have no knowledge in Haskell, maybe you may find an easy fix/patch that I could install locally? Enabling me to use hledger?

Thanks

**Comment by simonmichael** [comment]
Yes, you can work around this by specifying an older version of control-monad-free:
```
$ cabal install hledger[-web] --constraint 'control-monad-free < 0.6'
```

**Comment by thdox** [comment]
Thanks Michael, meanwhile I found another workaround. 

Instead of this

    sudo aptitude install ghc cabal-install happy
    sudo aptitude install libncurses-dev
    cabal update
    cabal install hledger

I did 

    sudo aptitude install ghc cabal-install happy
    sudo aptitude install libncurses-dev
    sudo aptitude install libghc-control-monad-free-dev
    cabal update
    cabal install hledger

As you are more knowledgeable than me about Haskell, can you please tell me which one of the workaround is better?

**Comment by simonmichael** [comment]
Yours, probably. No big difference.

**Comment by thdox** [comment]
I confirm that your workaround does work. I prefer yours actually, it sounds more "haskelly", mine is more "debiany". ;-)
