### ISSUE TITLE
Developer-guide git clone url incorrect.

### ISSUE THREAD

**Issue by funmler** [simonmichael/hledger#241]
Hope this is the right place to post this. In the Developer-guied for hledger http://hledger.org/developer-guide.html the git clone command gives a permission denied error
```
git clone git@github.com:simonmichael/hledger.git
...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I think it should just be 
```
git clone https://github.com/simonmichael/hledger.git
```

**Comment by zeckalpha** [comment]
Hmm, I've ran into more problems with https remotes than git protocol remotes. This looks like you haven't given  GitHub your public key. https://help.github.com/articles/generating-ssh-keys/

**Comment by simonmichael** [comment]
Thanks!

@funmler needs to add a public key to user settings, to allow ssh access to github, right ?

Which address will be more convenient for most readers of the dev guide ? How should we change the wording to help people ?

**Comment by zeckalpha** [comment]
I'm not sure. The https one asks for username and password IIRC, so that gets annoying, too. Either way, a github account is needed, I think.

**Comment by simonmichael** [comment]
Surely it's possible to clone a public github repo without needing github credentials ?

**Comment by zeckalpha** [comment]
That would make sense. I could be spewing non-sense. I'll look into it
tomorrow.

**Comment by zeckalpha** [comment]
It doesn't ask for credentials, my mistake. This isn't documented very well.

https://help.github.com/articles/which-remote-url-should-i-use/ says that the https is preferred, however, "When you git fetch, git pull, or git push to the remote repository using HTTPS, you'll be asked for your GitHub username and password." This isn't the case. I'll see about getting the GitHub documentation updated. I think the HTTPS url would be fine in the hledger docs.

**Comment by simonmichael** [comment]
Automatic site updating on push is currently broken, the site is now current. Thanks!
