### ISSUE TITLE
layout of console output should adjust for double-width characters

### ISSUE THREAD

**Issue by charles-plessy** [simonmichael/hledger#242]
Hello,

With `hledger register`, the information is displayed in a tabular manner, but this does not work when the description contains double-space characters, which are typically found in Chinese, Japanese or Korean (CJK) texts. This seems to be a limitation of the `printf` command used in ` hledger/hledger/Hledger/Cli/Register.hs`, and I am not able to suggest a replacement, unfortunately.

Here is an example of a typically shifted output.

```
2015/04/10 Apples               expense:food                   1 $           1 $
                                asset:bank                    -1 $             0
2015/04/10 りんご                  expense:food                   1 $           1 $
                                asset:bank                    -1 $             0
```

Here is a joural file to reproduce the above.

```
; journal created 2015-04-10 by hledger

2015/04/10 Apples
    expense:food           1 $
    asset:bank

2015/04/10 りんご
    expense:food           1 $
    asset:bank
```

Many thanks for giving us hledger.  I love it.

**Comment by simonmichael** [comment]
Thanks Charles. 

This is most visible with register, but also with balance -M if you have wide characters in account names.

What OS/application/font(s) are you using ? For me with Menlo or Monaco fonts, on OSX, in iTerm2, the double-width characters are rendered exactly two regular characters wide, but in a graphical Emacs they appear slightly less than two characters wide, I'm not sure why.

Still it seems like we could compensate for this somewhat.

**Comment by charles-plessy** [comment]
I am running hledger on Linux (Debian Testing/Unstable), via the GNOME terminal, or via OSX's Terminal. The terminals display _Wide_ characters (in the sense of the [Unicode Standard Annex 11](http://www.unicode.org/reports/tr11/tr11-28.html)) with twice the space for _Narrow_ characters, which I think is the correct thing to do.

I also noticed that web browsers fail to display correctly aligned monospace text containing a mixture of narrow and wide characters.  For instance, the text below may be rendered unaligned in your browser, but if you paste it in your terminal it will be displayed correctly.

```
apple   10
りんご  9
ﾘﾝｺﾞ    7
苹果    6
猕猴桃  31
pear    16
```

The difference of rendering between web browsers and terminals is the amount of space (not characters, but just the distance) between east asian characters, that is shorter in the case of web browsers. This distance is the same as when rendering text in non-monospace context, therefore, my conclusion is that web browsers (and perhaps Emacs) do not provide a way to extend the concept of monospaced text to a mixture of east asian and latin characters.

So, altogether a working heuristic could be that for each wide character, hledger should remove a space.

**Comment by simonmichael** [comment]
Interesting! So we won't worry about hledger-web right now. But that heuristic should help with the console UI. I made a start on it.

**Comment by simonmichael** [comment]
With a decent terminal & font, all cli reports and hledger-ui now seem to align robustly with any mix of ascii and wide characters in codes/descriptions/account names/commodity symbols/comments. It feels pretty nice. Please reopen if you find more cases, hledger-web excluded.

**Comment by charles-plessy** [comment]
It took me some time before I could upgrade to test it, but I confirm that it works perfectly, thanks a lot !

**Comment by simonmichael** [comment]
Great, thanks for confirming.
