### ISSUE TITLE
Missing module Control.Applicative.Compat

### ISSUE THREAD

**Issue by snoyberg** [simonmichael/hledger#245]
Looks like this was removed from base-compat in 0.8

**Comment by simonmichael** [comment]
Ack... thanks!

**Comment by snoyberg** [comment]
No problem, I added an upper bound to Stackage for now so the build is continuing. Just give me a ping on the issue when it's ready to work with 0.8.

**Comment by peti** [comment]
Same problem here: http://hydra.cryp.to/build/781803/log/raw.

**Comment by simonmichael** [comment]
@snoyberg should be fixed now, thanks.

**Comment by snoyberg** [comment]
Thanks @simonmichael, I'll ping you if there are any problems with tomorrow's nightly build.

**Comment by snoyberg** [comment]
@simonmichael what are your plans for releasing this to Hackage?

**Comment by simonmichael** [comment]
Sorry, that would be a good idea wouldn't it. Released as 0.25.1.

**Comment by snoyberg** [comment]
Thanks

**Comment by snoyberg** [comment]
One more thing: could you release a new version of hledger-web too?

**Comment by simonmichael** [comment]
Done.

**Comment by snoyberg** [comment]
Thanks again
