### ISSUE TITLE
Overly zealous alias expansion

### ISSUE THREAD

**Issue by ellis** [simonmichael/hledger#249]
I'm getting unexpected and undesirable alias expansions using hledger 0.24.  Here's a small test case:

```
alias Some  = A:Any
alias Something  = B:Something

2001-01-01 Payee
	AccountOne  1.00
	Something
```

ledger expands the "Something" => "B:Something", as expected:
```
% ledger -f aliaserror.ledger print
2001/01/01 Payee
    AccountOne                                     1
    B:Something
```

In contrast, hledger expands "Something" => "B:A:Anything":
```
% hledger -f aliaserror.ledger print
2001/01/01 Payee
    AccountOne            1.00
    B:A:Anything         -1.00
```

**Comment by simonmichael** [comment]
Hi ellis.. this is according to http://hledger.org/manual.html#account-aliases . Does that doc explain it ?

**Comment by ellis** [comment]
Oh, I see.  Thanks for the link.
