### ISSUE TITLE
hledger in windows console does not print non-ascii characters

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#25]
_Original author: simon@joyful.com (November 03, 2010 16:35:58)_

Reported by André Albuquerque: with non-ascii characters in the journal file, eg:

2010/1/1 testing €
  a   1€
  b

using hledger, eg the 0.12.1 binary, in a windows DOS prompt:

C:&gt;hledger print
2010/01/01 testing Γé¼
    a          1Γé¼
    b         -1Γé¼

Output on unix is:

2010/01/01 testing €
    a            1€
    b           -1€

It's not clear how to fix this, other than waiting for GHC to get better.
Related discussion: 
http://thread.gmane.org/gmane.comp.lang.haskell.glasgow.user/19163
http://www.codeproject.com/KB/cpp/unicode_console_output.aspx

_Original issue: http://code.google.com/p/hledger/issues/detail?id=25_

**Comment by w1ld** [comment]
I had this with Powershell/cmd. It helped me to use mintty, thanks
