### ISSUE TITLE
Please allow for aliases without regular expression expansion (and re-establish compatibility with ledger)

### ISSUE THREAD

**Issue by ellis** [simonmichael/hledger#252]
In hledger 0.24, regular expressions in aliases allow for a lot of power.  For me, however, it's only presenting inconveniences so far.  I need to keep my journals compatible with ledger (especially because of the '-X' option), and the new alias expansions in 0.24 are causing some havoc since I can't just prefix my aliases with '^'.  In my opinion, regular expressions are an advanced feature (and potentially quite confusing) that might be better enabled explicitly rather than by force?  Maybe by a flag on the command line or keyword in the journal.  In the journal, it might look like this:

> rxalias short very:long

or

> alias /short/ very:long

That would allow for aliases in ledger journals to continue working in hledger.  What do you think?

**Comment by simonmichael** [comment]
It's good to hear from someone else using both hledger and ledger, and I agree something like this must be done. It's a little painful because in other parts of h/ledger regexps are the default and you don't need special syntax for them. And I try to minimise new syntax, which of course Ledger won't accept.

If Ledger adopted regexp aliases too (unlikely, but as a thought experiment) so that compatibility was restored, would you still find them a problem (because usability, too surprising/powerful) ?

Related to #244.

**Comment by simonmichael** [comment]
Other scenarios: would there still be a problem if
- our alias regexps always had an implicit ^ at the start ?
- and an implicit $ at the end ?
- --recursive-aliases was required to make them recursive, like Ledger ?

**Comment by ellis** [comment]
1) If Ledger adopted regexp aliases too, that'd be ok.

2) Having an implicit ``^$`` wrapper would solve the compatibility issues for me; and a ``--recursive-aliases`` flag would remove the wrapper, right?

**Comment by simonmichael** [comment]
--recursive-aliases might need to remove the wrapper eh ? I'd have to try it a bit. I've asked for more input from the mail lists.

**Comment by ellis** [comment]
Thanks, Simon

**Comment by simonmichael** [comment]
I've been thinking this over. It seems to me that adding even an implicit ^ will make regex-based aliases a bit tedious.  Instead I lean towards:

- restoring the old, more Ledger-compatible behaviour (match full account names) as default
- using the new regex behaviour when the pattern is wrapped in forward slashes
- and keeping aliases recursive always, at least for now

**Comment by ellis** [comment]
I see -- that sounds quite reasonable to me.

**Comment by simonmichael** [comment]
Here's the [new alias docs](https://github.com/simonmichael/hledger/blob/077e3c6a0217e7b60aa429c98094b87125f6a199/doc/manual.md#account-aliases).

Recursive aliases can indeed be confusing when you're not expecting them. My hope is they'll rarely trip up users of non-regex aliases. And users of the regex aliases are advanced and won't mind the occasional head-scratching. If I'm wrong we'll have to take on more complexity debt and make them an option.

**Comment by ellis** [comment]
Thanks, Simon!
