### ISSUE TITLE
anonymise data for easier sharing

### ISSUE THREAD

**Issue by rodlogic** [simonmichael/hledger#265]
This is mostly a thought that occurred with it's value quite debatable. 

It seems to me that one of the reasons we always talk about it but never show how we organize our ledger files in it's entirety because the data contained in it's contents are obviously quite private. It would be nice if at any moment I could create a complete copy of my files with account numbers and descriptions changed, and amounts normalized (e.g. from 0-1000 instead of the real ones). I.e. a fully functional ledger database but without any real data behind it.

Maybe that could trigger the generation of some pre-defined databases for different kinds of use cases (business, consultant, trading, etc).

**Comment by simonmichael** [comment]
Exactly right. Ledger has the --anon flag for this reason. We could implement a similar feature, and hopefully improve it, with potentially very good effects for docs, support, etc. Some details to consider:

- what to anonymise - dates, descriptions, account names, amounts, comments, tags, file paths, journal stats...
- can we generate human-friendly names rather than non-mnemonic codes
- CLI
- interactions with commands, like add

**Comment by simonmichael** [comment]
Bounty increased.

**Comment by simonmichael** [comment]
Leaving this closed so bounty can be claimed. Cc'ing the below here for context and next steps:

> For me the vision for this is making it easy to share non-trivial examples drawn from our real-world data and usage. Creating realistic synthetic examples is a lot of work. Generally we don't like to reveal our actual data for privacy and security reasons. If we could remove those concerns just by adding a flag, it would open up a lot more troubleshooting, support and sharing of tips and examples.

> The threat model is that we share some "anonymized" data thinking it gives away no private information, when actually it's quite easy for a motivated person or bot to "decrypt" it and learn a lot about your finances and life.

> After thinking about it slightly, it's a rather interesting challenge, since crypto is hard and also because of the goal of generating useful shareable examples. For that, we'd like to preserve constraints such as balanced transactions, balance assertions passing, balance zero points, prices etc. Also we'd like to generate easy human-readable names instead of random-looking data. I don't know how far we will go, and it may need a lot of experimentation. What we have so far is good, and when we are able to obfuscate amounts in some non-reversible way it should help a lot.
