### ISSUE TITLE
Allow more than two amounts when importing CSV

### ISSUE THREAD

**Issue by amigalemming** [simonmichael/hledger#267]
Please support more than two amounts in a CSV row. Currently I have an example with three amounts.
##

**Comment by amigalemming** [comment]
It seems I can import only one amount per CSV row. The two allowed accounts seem to always have the same value.

**Comment by simonmichael** [comment]
Can you show a real world-ish example ? And how could we change http://hledger.org/manual.html#csv to explain how to configure it ?

**Comment by amigalemming** [comment]
I want to convert
~~~~
Date,Description,Total,Netto,Tax
01.06.15,Ticket,119,100,19
~~~~
to
~~~~
2015-06-01 Ticket
    (Giro) -119.00 Euro
    Netto -100.00 Euro
    Tax -19.00 Euro
    Remainder
~~~~
For the imported data it holds `Total`=`Netto`+`Tax` but for other entries in the journal this does not apply. I export the CSV data from my web banking interface. I cannot freely choose its format.

I am uncertain about how to extend the current scheme to more than two accounts. I actually do not really understand what `amount-in` and `amount-out` etc. are intended for.
Maybe rules like these could work:
~~~~
fields date,description,amount1,amount2,amount3

account1 (Giro)
account2 Netto
account3 Tax
~~~~
where `account1` is filled with the value of `amount1`, etc.

**Comment by amigalemming** [comment]
Alternatively I can use a general CSV template processing program like `cvsreplace` from
http://hackage.haskell.org/package/spreadsheet .
It would allow me to use any number of amounts, but it cannot process cell contents like the date.

**Comment by simonmichael** [comment]
That's helpful, yes a separate tax field in the CSV record is not uncommon.

You could preprocess your CSV with a script that splits each record into two, which hledger could process into a main transaction and a tax transaction. But that's not very satisfying.

IIRC the plan was/is to add full journal entry templates to the CSV rules file, so you could just write out the kind of journal entry you want with interpolated expressions referencing the CSV fields.

**Comment by simonmichael** [comment]
PS, as it keeps growing, should this CSV->Journal conversion functionality remain in the main hledger executable, or should it move to an add-on ? Eg `hledger-csv file.csv ... | hledger -f - ...

Or, is there a separate tool that already can do all of this for us ? Though I suspect a hledger add-on has advantages over a tool that knows nothing about hledger data.

**Comment by amigalemming** [comment]
Yes this interpolation thing would be the most comfortable solution. It is what I can do partially with `csvreplace`. This tool does not know anything about hledger data and thus it cannot parse dates, for instance.

**Comment by simonmichael** [comment]
Discussion continues on #627, I'll close this one.
