### ISSUE TITLE
hledger-web-0.21.3-839-gb9b0417 doesn't compile

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#268]
Citing from http://hydra.cryp.to/build/916926/log/raw:

~~~~~~~~~~~
Application.hs:81:69:
    Couldn't match type ‘[Char]’ with ‘Char’
    Expected type: FilePath
      Actual type: [String]
    In the fourth argument of ‘readJournalFile’, namely ‘f’
    In the second argument of ‘fmap’, namely
      ‘readJournalFile Nothing Nothing True f’
~~~~~~~~~

**Comment by simonmichael** [comment]
I don't recognise that version string or hash, what would it correspond to in the hledger repo ?

**Comment by peti** [comment]
That is the output from "git describe", I think. It's the current HEAD of the master branch. You should have received e-mail from the Hydra server a while ago to inform you about the issue.

**Comment by simonmichael** [comment]
Right you are! I'll have to sort that out. And I see the build failure and will work on it asap. Thanks for escalating it.

Unfortunately I have got in the habit of reading and deleting hydra messages rather quickly. They often seem to be false positives from my perspective - build failures in some remote dependency I'm not currently interested in, or cabal installation issues on your server - and the emails don't quickly reveal what kind of failure they represent.
