### ISSUE TITLE
Timelog feature does not parse descriptions as described

### ISSUE THREAD

**Issue by MatthiasKauer** [simonmichael/hledger#270]
Hi,
I'm toying with the time log feature as described in the manual: 
http://hledger.org/manual.html#timelog

The example there (I slightly modified it for clarity)
```
i 2015/03/30 09:00:00 some:account name  optional description after two spaces
o 2015/03/30 09:20:00
i 2015/03/31 22:21:45 another account
o 2015/04/01 02:00:34
i 2015/04/01 09:00:00 some:account name  another description
o 2015/04/01 09:20:00
```
does not give the expected output. The description is treated as part of the account name on my system (Win7, hledger 0.25.0) if I am interpreting that correctly.

```
C:\Users\matthias.kauer>hledger -f time.log balance
               3.65h  another account
               0.67h  some
               0.33h    account name  another description
               0.33h    account name  optional description after two spaces
--------------------
               4.31h
```

Can you help me with this or is it a legitimate bug?

Best regards,
Matthias

**Comment by simonmichael** [comment]
Quite right! Thanks for the report.
