### ISSUE TITLE
[hledger-web] "J" shortcut doesn't work with --base-url option

### ISSUE THREAD

**Issue by julpec** [simonmichael/hledger#271]
Hello

I run hledger-web in server mode with --base-url option : 

  hledger-web -f /my/journal/file --server --port=5001 --base-url=https://my.domain.org/my-alias

The application is running well but when I use the shortcut `j` to display journal, it send me to this url : `https://my.domain.org/journal`

I running hledger-web 0.24.98 because I was not able to upgrade to last version (unmet dependencie wai-app-static because want time==1.4)

Thanks

**Comment by simonmichael** [comment]
Thanks for the report! I think it's fixed in master now.
