### ISSUE TITLE
--daily produces inconsistent column / date label (maybe only w/ time tracking)

### ISSUE THREAD

**Issue by MatthiasKauer** [simonmichael/hledger#272]
Hi,
I've gone ahead and began using hledger more for aggregation of time log data.
I observe the following inconsistent behavior.
Going from a minimal data set of the past week.

```
i 2015-06-29 10:43:04 pers:notes
o 2015-06-29 11:36:56
i 2015-07-03 01:05:00 sw:tim
o 2015-07-03 01:12:57
```

I execute

```
matthias@rp3deb:~/dvl/fastcellsimulator$ hledger -f /home/matthias/Seafile/mytodolist/tim/colwidth-minexample.hledger balance --daily --begin 'this week'
Balance changes in 2015/06/29-2015/07/03:

            ||  2015/06/29d  2015/06/30-2015/06/30  2015/07/01d  2015/07/02d  2015/07/03d 
============++============================================================================
 pers:notes ||         0.9h                      0            0            0            0 
 sw:tim     ||            0                      0            0            0         0.1h 
------------++----------------------------------------------------------------------------
            ||         0.9h                      0            0            0         0.1h 

```

I find it surprising and somewhat annoying that 2015/06/30-2015/06/30 shows up in this fashion. This may be OCD, but if it was 2015/06/30d like all the other days this aggregated report would fit my terminal width and this way it does not.
Do you have any idea where this is coming from? Can I do something about it?

Side notes:
* I'm in UTC+8 zone and logging in UTC but hledger doesn't care about this, does it?
* This is hledger 0.24 on debian testing, but I have observed similar behavior on my Windows 7 machine with hledger 0.25.

**Comment by simonmichael** [comment]
Wow, good catch! Fixed in master, thanks.

**Comment by MatthiasKauer** [comment]
looking at your change, that does indeed look like a very random find :)
let's hope that was indeed responsible and thanks for the prompt response!
