### ISSUE TITLE
Postfix currency symbol formatting becomes incorrect

### ISSUE THREAD

**Issue by greyson** [simonmichael/hledger#276]
This is weird, and I'm surprised not to find it already reported.

I typically use post-fix notation for even normal currencies (I have several that I track, so it's easier to be able to type them without remembering special key sequences) -- hence the problem.  See the journal file below (anonymized, stripped to the bare minimum -- problem does not manifest if any one of the three transactions below are removed.)

Note the summary balance of the "Asset" account.

        ; Example of a journal which produced odd output.
        
        D 1,000.00 USD
        ; ^^ Note the default format -- present or otherwise, this should
        ;    govern the formatting of the output. Present or otherwise, it does
        ;    not change the output.
        
        ;; EXPECTED OUTPUT:
        ;          553.04 USD  Asset
        ;          389.04 USD    Bank:Checking
        ;          164.00 USD    Cash
        ;         -553.04 USD  Equity:Opening Balance
        ;--------------------
        ;                   0
        
        ;; ACTUAL OUTPUT
        ;           USD553.04  Asset
        ;          389.04 USD    Bank:Checking
        ;          164.00 USD    Cash
        ;         -553.04 USD  Equity:Opening Balance
        ;--------------------
        ;                   0
        
        ; Note that this is the output with, or without, the default
        ; formatting setting.
        
        2015/01/01 Opening balance (USD)
          Equity:Opening Balance
          Asset:Cash            164.00 USD
          Asset:Bank:Savings    389.04 USD
        
        2015/07/20 Anonymous account closure
          Asset:Bank:Savings   -389.04 USD ; closing account
          Asset:Receivables     389.04 USD
        
        2015/07/30 ! Anonymous check receiver
          Asset:Receivables    -389.04 USD
          Asset:Bank:Checking   389.04 USD

For reference, I am using `hledger` version 0.26 on Arch Linux installed with cabal (rather than AUR or some such)

It seems that once such a combination of transactions is placed, the formatting is irrevocably changed to prefix notation (which is much less readable when using currency codes)  no matter what other transactions are added or removed.

**Comment by greyson** [comment]
Correction to the above;
If a transaction amount in `Asset:Receivable` causes it to be displayed, then the formatting is corrected.  This seems to manifest only when the receivables have been zero'd out -- and having receivables in an account not subordinate to `Asset` does not cause the problem to manifest.

**Comment by simonmichael** [comment]
Thanks for this detailed bug report. I think this is quite likely to be the same issue as #230 - a corner case in our amount arithmetic drops the custom display style information. This needs to be fixed.
