### ISSUE TITLE
hledger-lib does not compile with GHC versions prior to 7.10.x

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#280]
Full details are at http://hydra.cryp.to/eval/707913.

**Comment by simonmichael** [comment]
See also https://github.com/simonmichael/hledger/commit/e60eb71467fa3f693a94292532e439882da767a6 .

I'm confused, why is that recent hydra build building hledger 0.21.3 ?

**Comment by simonmichael** [comment]
I messed up the conditional deps in https://github.com/simonmichael/hledger/commit/a9b2e5409c0d510d4e1f2cae04e0d535405ccf1d on aug 12. The following commit should fix it, thank you!

**Comment by simonmichael** [comment]
[build status](http://hydra.cryp.to/jobset/hledger/master#tabs-jobs)

**Comment by peti** [comment]
I disabled the Hydra jobs a while ago because they kept failing with no fix in sight. I re-activated them today, though, so the CI environment is building the Git version of hledger again.

**Comment by simonmichael** [comment]
Thanks!

**Comment by simonmichael** [comment]
> I'm confused, why is that recent hydra build building hledger 0.21.3 ?

Answering myself: it only looks that way, probably because of #269.

**Comment by peti** [comment]
The Hydra job builds only released versions, now. We talked about this is another thread?
