### ISSUE TITLE
hledger-lib syntax error in Haddock comments

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#281]
Hledger/Data/StringFormat.hs:49:17: parse error on input ‘(’

Cited from http://hydra.cryp.to/build/1119272/nixlog/1/raw.

**Comment by simonmichael** [comment]
Thanks! I'll add haddock checking to Travis too.

**Comment by peti** [comment]
With Travis continuous integration in place for hledger, do you feel that the Hydra builds still add any value?

**Comment by simonmichael** [comment]
@peti: now that Travis is checking haddocks as well, probably not a lot.
Hydra tests against multiple GHC versions, but Travis could also handle that.
Travis also provides the status badge and IRC notifications.

Hydra has caught many failures and demonstrated the value of automated build testing, but perhaps we should lighten your workload now. Thank you very much for the service.
