### ISSUE TITLE
default Show instance for mixed-price amounts can be misleading

### ISSUE THREAD

**Issue by btittelbach** [simonmichael/hledger#284]
Hi,

I planned to do beverages inventory and cash-register calculation with hledger and playing around a bit with it it seems that summing up commodities with a price is badly broken in multiple instances in hledger 0.26.

actual issue: hledger only remembers the first price of any commodity:

example one: for any number of commodities with @@ totalprice, the totalprice of all postings should be summed up. It is not.
e.g. if the journal looks like this

```
2015/08/28 bought Mannerschnitten
    assets:current:cash:register
    assets:current:inventory-edibles    32 Mannerschnitten @@ 15.92 EUR

2015/09/07 bought Mannerschnitten
    assets:current:cash:register
    assets:current:inventory-edibles    48 Mannerschnitten @@ 23.88 EUR
```

then `show $ head $ ledgerTopAccounts $ ledgerFromJournal q j` while querying for `acct:assets:current:inventory-edibles` will actually show:

```
80 Mannerschnitten @@ 15.92 EUR
```

i.e. Even though the price per item is identical (@0.4975 EUR) hledger only remebers the total price and only the first one. It would even be somewhat fine if hledger added the total to display `80 Mannerschnitten @@ 39.80 EUR`, but it does not.

Furthermore, handling of commodities with differing prices is broken for the same reason:
e.g.: if the journal looks like this:

```
2015/08/28 bought Mannerschnitten
    assets:current:cash:register
    assets:current:inventory-edibles    32 Mannerschnitten @ 1 EUR

2015/08/29 bought Mannerschnitten
    assets:current:cash:register
    assets:current:inventory-edibles    10 Mannerschnitten @ 1 EUR

2015/09/07 bought Mannerschnitten
    assets:current:cash:register
    assets:current:inventory-edibles    48 Mannerschnitten @ 0.50 EUR
```

then `show $ head $ ledgerTopAccounts $ ledgerFromJournal q j` while querying for `acct:assets:current:inventory-edibles` will actually show:

```
90 Mannerschnitten @ 1 EUR
```

whereas these should actually be handled as different commodities, since their price differs and hledger should in my humble opinion actually show:

```
42 Mannerschnitten @ 1 EUR
48 Mannerschnitten @ 0.50 EUR
```

and should one attempt to transfer 50 Mannerschnitten, hledger-add should automatically transfer items starting with the earliest. i.e. preserve item prices and write the following transaction:

```
2015/09/07 sold Mannerschnitten
    assets:current:inventory-edibles    42 Mannerschnitten @ 1 EUR
    assets:current:inventory-edibles     8 Mannerschnitten @ 0.50 EUR
    revenue:sales:edibles
```
##

**Comment by simonmichael** [comment]
Thanks for the report. Re your first example: I believe generally the Show instance is used only for debugging, and some shortcuts may have been taken. I don't think this manifests as a user-visible bug anywhere in the UI ? But even if so, you're right, let's fix it.

**Comment by btittelbach** [comment]
Well, you may be right about the bug not appearing in the UI, since ```balance --cost``` apparently only looks a the total cost and ```balance``` without the cost flag, displays only the commodity count.

In my case however, it's a problem since I'd like to leverage hledger-lib and write a utility to add transactions that balance an inventory. For that I need to keep track of commodities and their different acquisition prices as well as the prices they are being sold at in our hackerspace.

My original idea was to buy commodities with money in the cash register, i.e. transfer it with their acquisition price from ```assets:current:cash-register``` to ```assets:inventory:edibles```.
Then after an inventory, transfer all commodities that do not remain (thus must have been sold) to ```revenue:sales:edibles``` with their acquisition price and then transfer them from ```revenue:sales:edibles``` to ```assets:current:cash-register``` with their sales-prices. Thus the revenue generated from the difference in the item prices, stays in the revenue account, while I differentiate between inventory and revenue and keep track of items in the inventory.

**Comment by simonmichael** [comment]
Cool. Just a quick reply for now: I would bet the differently-priced amounts are in fact being kept separate, it's only show that's giving a misleading rendering. It gives more detail if --debug level is 3 or higher, see:
```
*Hledger.Cli.Main Hledger> putStrLn $ showMixedAmountDebug $ aibalance $ head $ ledgerTopAccounts $ ledgerFromJournal (Acct "inventory") j
Mixed [Amount {acommodity="Mannerschnitten", aquantity=32.0, aprice= @@ Amount {acommodity="EUR", aquantity=15.92, aprice=, astyle=AmountStyle {ascommodityside = R, ascommodityspaced = True, asprecision = 2, asdecimalpoint = Just '.', asdigitgroups = Nothing}}, astyle=AmountStyle {ascommodityside = R, ascommodityspaced = True, asprecision = 0, asdecimalpoint = Just '.', asdigitgroups = Nothing}}
       Amount {acommodity="Mannerschnitten", aquantity=48.0, aprice= @@ Amount {acommodity="EUR", aquantity=23.88, aprice=, astyle=AmountStyle {ascommodityside = R, ascommodityspaced = True, asprecision = 2, asdecimalpoint = Just '.', asdigitgroups = Nothing}}, astyle=AmountStyle {ascommodityside = R, ascommodityspaced = True, asprecision = 0, asdecimalpoint = Just '.', asdigitgroups = Nothing}}]
```

**Comment by Xitian9** [comment]
I think this is no longer true of the current implementation of mixed amount, and this can be closed.
