### ISSUE TITLE
file-url opt does not work 

### ISSUE THREAD

**Issue by dvzubarev** [simonmichael/hledger#285]
hledger-web 0.26
specifying file-url does not take any effect.
It seems its name was [changed](https://github.com/simonmichael/hledger/blob/9e9aec957fe321c299d8e94cc71b88034b5c00d3/hledger-web/Hledger/Web/WebOptions.hs#L77) some time.

**Comment by simonmichael** [comment]
Oops! An incomplete rename. Thanks for the report.
