### ISSUE TITLE
Build problem with latest HEAD

### ISSUE THREAD

**Issue by markokocic** [simonmichael/hledger#286]
While trying to build the latest head I got the following message:

Installing library in                                                                         
/home/marko/src/cvstree/hledger/.cabal-sandbox/lib/x86_64-linux-ghc-7.10.2/hledger-lib-0.26.98
-KoWnj8sUrU41snwAu6iIBh                                                                       
Registering hledger-lib-0.26.98...                                                            
Installed hledger-lib-0.26.98                                                                 
Configuring hledger-0.26.98...                                                                
Building hledger-0.26.98...                                                                   
Preprocessing library hledger-0.26.98...                                                      
In-place registering hledger-0.26.98...                                                       
Preprocessing executable 'hledger' for hledger-0.26.98...                                     
Linking dist/dist-sandbox-297beb5b/build/hledger/hledger ...                                  
/home/marko/src/cvstree/hledger/hledger/dist/dist-sandbox-297beb5b/build/libHShledger-0.26.98-
JfIcHsbBK2M8KDYad1lVQt.a(Balance.o):(.text+0x5331): undefined reference to `hledgzuJfIcHsbBK2M
8KDYad1lVQt_TextziTabularziAsciiWide_zdwrender_info'                                          
/home/marko/src/cvstree/hledger/hledger/dist/dist-sandbox-297beb5b/build/libHShledger-0.26.98-
JfIcHsbBK2M8KDYad1lVQt.a(Balance.o):(.text+0x5503): undefined reference to `hledgzuJfIcHsbBK2M
8KDYad1lVQt_TextziTabularziAsciiWide_zdwrender_info'                                          
/home/marko/src/cvstree/hledger/hledger/dist/dist-sandbox-297beb5b/build/libHShledger-0.26.98-
JfIcHsbBK2M8KDYad1lVQt.a(Balance.o):(.text+0x6f21): undefined reference to `hledgzuJfIcHsbBK2M
8KDYad1lVQt_TextziTabularziAsciiWide_zdwrender_info'                                          
/home/marko/src/cvstree/hledger/hledger/dist/dist-sandbox-297beb5b/build/libHShledger-0.26.98-
JfIcHsbBK2M8KDYad1lVQt.a(Balance.o):(.text+0x70f3): undefined reference to `hledgzuJfIcHsbBK2M
8KDYad1lVQt_TextziTabularziAsciiWide_zdwrender_info'                                          
/home/marko/src/cvstree/hledger/hledger/dist/dist-sandbox-297beb5b/build/libHShledger-0.26.98-
JfIcHsbBK2M8KDYad1lVQt.a(Balance.o):(.text+0x8b79): undefined reference to `hledgzuJfIcHsbBK2M
8KDYad1lVQt_TextziTabularziAsciiWide_zdwrender_info'                                          
/home/marko/src/cvstree/hledger/hledger/dist/dist-sandbox-297beb5b/build/libHShledger-0.26.98-
JfIcHsbBK2M8KDYad1lVQt.a(Balance.o):(.text+0x8d4b): more undefined references to `hledgzuJfIcH
sbBK2M8KDYad1lVQt_TextziTabularziAsciiWide_zdwrender_info' follow                             
/home/marko/src/cvstree/hledger/hledger/dist/dist-sandbox-297beb5b/build/libHShledger-0.26.98-
JfIcHsbBK2M8KDYad1lVQt.a(Balance.o):(.data+0x1dd8): undefined reference to `hledgzuJfIcHsbBK2M
8KDYad1lVQt_TextziTabularziAsciiWide_zdwrender_closure'                                       
collect2: error: ld returned 1 exit status                                                    
Failed to install hledger-0.26.98                                                             
cabal: Error: some packages failed to install:                                                
hledger-0.26.98 failed during the building phase. The exception was:                          
ExitFailure 1

**Comment by simonmichael** [comment]
Thanks.. I was off net for a while, fixed now.
