### ISSUE TITLE
missing ']' at hledger/Hledger/Cli.hs (line 403)

### ISSUE THREAD

**Issue by erson** [simonmichael/hledger#291]
make build
....
....

Progress: 4/28
--  While building package hledger-0.26.98 using:
      /Users/erson/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ build lib:hledger exe:hledger --ghc-options  -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/erson/Development/haskell/hledger/.stack-work/logs/hledger-0.26.98.log

    Preprocessing library hledger-0.26.98...
    [15 of 17] Compiling Hledger.Cli      ( Hledger/Cli.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/Hledger/Cli.o )

    Hledger/Cli.hs:404:12: parse error on input ‘}’
make: *** [build] Error 1

-----------------------------------------
hledger/Hledger/Cli.hs (line 403)
```
tpostings= ["expenses:food:dining" `post` usd 4.821   // missing ']' get into code and put it over there.
```
problem solved.

**Comment by simonmichael** [comment]
I don't see that problem here (latest master). Were you making some changes ?

**Comment by erson** [comment]
I fetch this : git clone https://github.com/simonmichael/hledger.git hledger

missing bracket was here
![screen shot 2015-10-13 at 16 42 35](https://cloud.githubusercontent.com/assets/1500710/10456326/74a708fa-71c9-11e5-9669-b128d138ddb8.png)

**Comment by erson** [comment]
I have cloned the repo again with the same command i have used before.it is master branch and there isnt that error now.It seems that i have made an unconscious edit on that code segment(i dont know how)

anyway there seems no error now.thank you for your care.

**Comment by simonmichael** [comment]
Weird. :)
