### ISSUE TITLE
Feature request: reduce to one currency

### ISSUE THREAD

**Issue by feuerbach** [simonmichael/hledger#294]
I am looking at `hledger balance assets` which contains multiple currencies, and I want to get a quick idea of the total, in a single currency.

It would be nice if I could say something like `hledger balance assets --convert 'USD:UAH=22.7 EUR:UAH=25.1'` and have everything displayed in UAH.

**Comment by simonmichael** [comment]
If you have set up market prices (with P) for USD and EUR in terms of UAH, you can do this with balance -V (in current master branch, releasing soon).

We don't yet have Ledger's -X option which tries harder to convert between arbitrary currencies.

**Comment by feuerbach** [comment]
That's great, I'll give it a try. Thanks!

**Comment by simonmichael** [comment]
Can this be closed, or is more needed ?

**Comment by feuerbach** [comment]
I just compiled hledger for master (ff59e0c15c6a10b91dcb904a80ac526cdb02cd56), and yet I get

```
% hledger balance -V                  
hledger: Unknown flag: -V
```

**Comment by feuerbach** [comment]
It works nicely, closing this.
