### ISSUE TITLE
Ignore incompatible ledger journal syntax

### ISSUE THREAD

**Issue by loxs** [simonmichael/hledger#299]
Please allow (and ignore) incompatible ledger syntax.
Here are the keywords that I encountered (and don't work)
- commodity
- note
- account
- check commodity
##

**Comment by simonmichael** [comment]
http://ledger-cli.org/3.0/doc/ledger3.html#Command-Directives mentions more directives. We should at least ignore all directives mentioned here. Also we should rename our "account" to its new spelling "apply account".

**Comment by simonmichael** [comment]
This is a great starter task for someone wanting to get going with hledger hacking, by the way.

**Comment by simonmichael** [comment]
Covered by #258, closing.
