### ISSUE TITLE
stack install doesn't work from the git repository

### ISSUE THREAD

**Issue by loxs** [simonmichael/hledger#300]
I am following the instructions here: http://hledger.org/download.html

I was able to install hledger using "stack --resolver nightly install hledger" and it works.
But when I tried installing from git, I get this error:

$ stack install
Could not parse '/Users/loxs/code/hledger/stack.yaml':
AesonException "Error in $.flags: failed to parse field 'flags': failed to parse field flags: expected HashMap Text a, encountered Null"
See https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md.

**Comment by simonmichael** [comment]
What stack version is that ? It works here with stack 1.6.

**Comment by loxs** [comment]
Yes, now it works with the latest commit
