### ISSUE TITLE
hledger-ui: can't install

### ISSUE THREAD

**Issue by rstacruz** [simonmichael/hledger#305]
I'm getting an error about `lens`:

```
→  stack --resolver nightly install hledger-ui

Run from outside a project, using implicit global project config
Using resolver: nightly specified on command line
Selected resolver: nightly-2015-12-02
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:
      lens: needed (>=4.12.3 && <4.13), 4.13 found (latest version available)
    needed for package: hledger-ui-0.27
```

Using stack v0.1.8.0 on OS X 10.11.1.

**Comment by simonmichael** [comment]
Sorry about that, use the more specific `--resolver nightly-2015-11-04` which I've now added to the download page. Cf 5c0c883.

**Comment by simonmichael** [comment]
Actually..  as it says on the download page, hledger-ui can't be installed from stackage yet (which you're trying to do, because you're running stack outside the hledger source tree). Instead, you should probably follow hledger.org/download.html#i-want-to-build-the-unreleased-git-version .
