### ISSUE TITLE
register --invert

### ISSUE THREAD

**Issue by rstacruz** [simonmichael/hledger#307]
Feature request: ledger's `--inverse` option will invert (ie, multiply by -1) values. Here's a use case where it's useful.

Say I want to see what happens in my savings account. That's easily done with `hledger reg`.

```
$ hledger reg Assets:Savings

2015/11/02 ATM withdrawal      Assets:Savings    $-200.00    $1200.00
2015/11/04 ATM withdrawal      Assets:Savings    $-150.00    $1050.00
2015/11/05 Bills payment       Assets:Savings     $-50.00    $1000.00
2015/11/05 Fund transfer       Assets:Savings    $-500.00     $500.00
```

But this isn't that useful because it shows `Assets:Savings` as the account. I want to see where it transfers to. That's easily done using `reg --related`.

```
$ hledger reg Assets:Savings --related

2015/11/02 ATM withdrawal      Assets:Cash        $200.00    $-1200.00
2015/11/04 ATM withdrawal      Assets:Cash        $150.00    $-1050.00
2015/11/05 Bills payment       Expenses:Phone      $50.00    $-1000.00
2015/11/05 Fund transfer       Assets:Checking    $500.00     $-500.00
```

Great! Unfortunately, this makes the running balance negative. In this case, `--inverse` will display it like I expect it.

(This isn't a perfect solution to that problem. A transaction with multiple postings will look strange, but it's a start... what would really make sense is a `--related` that will simply show the accounts where the money was drawn from.)
##

**Comment by simonmichael** [comment]
Does the register view in hledger-web or hledger-ui give what you're looking for ?

**Comment by rstacruz** [comment]
yes, exactly!

**Comment by rstacruz** [comment]
any clues on how i can see it like hledger-web from `hledger`?

**Comment by simonmichael** [comment]
I'm not sure it's possible actually. I think we should add hledger-web/hledger-ui-like account-centric register command to the CLI. I suppose "register" should stay as it is, so maybe "aregister" ?

**Comment by schoettl** [comment]
I recently posted exactly the same question in the hledger IRC. Why don't you like the idea of `--inverse`, Simon?

`hledger-ui --register=.` gives good output for me, but I cannot use the UI output for the report because it's locked in the pager.

Personally, I think it's redundant to add a new subcommand `aregister`, just to invert the amount. It's not an "[orthogonal](https://fishshell.com/docs/current/design.html#ortho)" feature and the subcommand name does not tell much on its purpose or on how it's different to `register`.

Background: I use hledger's output directly for a report and I would need this option, too. Shame on me that I don't use `hledger-api`, but `hledger` is just too easy to use. And I don't want to write another tool to produce the report. I'm currently using a bash script to invert the amount: https://gist.github.com/schoettl/0d459347005661bbe7691116db7be4a6

**Comment by simonmichael** [comment]
> I recently posted exactly the same question in the hledger IRC.
> 
DId you ? I don't remember it.

> Why don't you like the idea of --inverse, Simon?
> 
Well, because it's spelled wrong. :) ledger has --invert. We have it for the balance command. No-one has contributed it for register yet.
> Personally, I think it's redundant to add a new subcommand aregister, just to invert the amount. It's not an "orthogonal <https://fishshell.com/docs/current/design.html#ortho>" feature and the subcommand name does not tell much on its purpose or on how it's different to register.
> 
This command I'm thinking of would do more than just flipping amount signs (--invert), or showing the other ends of the transaction (--related); it also collapses multiple postings into one "item" when necessary, so that each line truly represents a transaction (as in hledger-web/hledger-ui registers) and not a posting (as in hledger register command).

**Comment by simonmichael** [comment]
@schoettl I meant to say, would you like to try adding --invert to register ?

**Comment by schoettl** [comment]
I think I mixed something up, I asked a very similar question (how to show realated accounts). But I have this question in mind for a few weeks.

OK, `--invert` is better. So would you accept this option to be added for the `register` command?

I see. Would `transactions` be an alternative name? But anyway, how should it behave, when QUERY references multiple accounts (that are not part of the same tree)? Error?

**Comment by schoettl** [comment]
> @schoettl I meant to say, would you like to try adding --invert to register ?

Yes, I'd like to try!

**Comment by simonmichael** [comment]
> OK, --invert is better. So would you accept this option to be added for the register command?

Well, I think so. It seems reasonable to make it a common flag, supported by most commands, but that will take some work. Let's test it with register, and come up with one or two examples where it solves a problem. 
> I see. Would transactions be an alternative name?
> 
Yes possibly, except that's already an alternative for print (txns). 
> But anyway, how should it behave, when QUERY references multiple accounts (that are not part of the same tree)? Error?
> 
Not an error, no. In hledger-ui/hledger-web, it shows 1. the total amount by which the current account is changed and 2. all the other account names involved (abbreviated).

**Comment by schoettl** [comment]
Here is one example, where `--invert` solves a problem:

For a report, I want to show all income from a specific account. `hledger register income:x` shows only negative amounts. Normally, in a report one would expect positive amounts for income. `--invert` solves that problem.

**Comment by simonmichael** [comment]
Well, it depends. *ledger users are of course used to income amounts appearing as negative numbers. 

balancesheet, cashflow and incomestatement are "financial" reports which do automatic sign flipping, to be more readable to non *ledger users. register is considered a "low level" report, which just shows the arithmetical numbers. 

A concrete example, if you have one, would still be useful (fake accounts/amounts is ok).

**Comment by simonmichael** [comment]
Well I see your PR so I guess I'll be able to demo it for myself soon enough.

I meant to say, there is also a related wish to support Ledger's --dc feature, which would be another way to see positive income numbers.

     --dc     Display register or balance in debit/credit format If you use --dc with
              either the register or balance commands, you will now get separate col-
              umns for debits and credits.

**Comment by schoettl** [comment]
> Well, it depends. *ledger users are of course used to income amounts appearing as negative numbers.

Sure, ledger users are used to it. But I think, objectively, it's still not intuitive to see negative numbers for income. Customers, that just want to see a report of income will be confused. I can tell them the reason for the negative numbers but they will still not be satisfied with the report.

> A concrete example, if you have one, would still be useful (fake accounts/amounts is ok).

I'm doing the books for a yearly festival. This festival is funded from many public and govermental organisations. And they all want to see reports on how their money is used.

The report must contain the accounts code, the income statement and cash flow, all transactions on the bank account, the saving account, and the cash. And it must contain lists of all transactions for each income and expenses accounts separately. For example

```
hledger reg income:ticket-sale
hledger reg income:public-fundings
hledger reg income:ads

hledger reg expenses:salary-singers
hledger reg expenses:salary-musicians
hledger reg expenses:advertising
hledger reg expenses:room-rent
```

I have a script that copies the output of this commands into a document to print it. But as I said, non-accountants are confused when there are negative incomes. Therefore, I need to invert the numbers.

**Comment by schoettl** [comment]
> I meant to say, there is also a related wish to support Ledger's --dc feature, which would be another way to see positive income numbers.

That sounds like a good feature, though I personally like the ledger-way with signed numbers more. It also sounds like it's much more work to implement this, than the `--invert` flag.

**Comment by simonmichael** [comment]
> I'm doing the books for a yearly festival.
> 
Thanks! That sounds quite interesting. I've heard a little about nonprofit accounting, where you have to track the use of each donor's specific funds. That would make a nice how-to.
> I meant to say, there is also a related wish to support Ledger's --dc feature, which would be another way to see positive income numbers.
> 
> That sounds like a good feature, though I personally like the ledger-way with signed numbers more. It also sounds like it's much more work to implement this, than the --invert flag.
> 

Hopefully not too much more. It's supposed to be a final-stage output transform, too. #71.

**Comment by simonmichael** [comment]
Thanks @schoettl.
