### ISSUE TITLE
hledger web --server not working

### ISSUE THREAD

**Issue by TomK32** [simonmichael/hledger#312]
Those two should do the same thing, no?
```
$ hledger web  --server
hledger: Unknown flag: --server
$ hledger-web  --server
Starting web app on port 5000 with base url http://localhost:5000
Press ctrl-c to quit
```

**Comment by TomK32** [comment]
ah, i see `hledger web -- --server` it is. non-issue then.

**Comment by simonmichael** [comment]
http://hledger.org/manual.html#add-on-commands talks about this, a rough patch in our CLI which I'd really like to smooth out. I thought there was an issue but I'm not finding it right now.
