### ISSUE TITLE
web: Filters are dropped when ledger file is reloaded

### ISSUE THREAD

**Issue by TomK32** [simonmichael/hledger#314]
Starting `hledger-web -e today` does limit the transaction to the current day as expected but after changing a file all future transactions are also shown.

The question is wether to write that `-e today` into the web opts input field (so the user carries it along and can change it) or (my personal perference) apply them when reloading the journal.

**Comment by simonmichael** [comment]
Isn't it a little misleading/confusing to show a filtered view without having anything in the search field ? Should command-line query arguments be shown there from the start ?

**Comment by simonmichael** [comment]
On the other hand, that would mean you can change/remove the initial filter, and can't enforce a limited view from the command line. Maybe it's better after all to treat a command-line query as a permanent invisible extra filter.
