### ISSUE TITLE
Support for budgets

### ISSUE THREAD

**Issue by achernyak** [simonmichael/hledger#315]
Are there any plans to add support for budgeting with periodic transaction, similar to what ledger currently has?

**Comment by simonmichael** [comment]
Hi.. no. I have some notes somewhere towards a different approach. Currently I do budgetting manually, using virtual subaccounts to divide funds into spending "envelopes".

Closing this, feel free to bring it up again on #hledger or the mail list.

**Comment by rstacruz** [comment]
IMHO, ledger-cli's budgeting was pretty weak anyway and compares poorly to other budgeting-focused solutions like ynab.

**Comment by simonmichael** [comment]
Right. Here's some recent chat about emulating YNAB:
```
<sm> I try to replicate YNAB's method with subaccounts
<sm> virtual subaccounts, of checking
<sm> I have checking:available, checking:month:food,home,..., checking:year:vacation,... etc.
<sm> income lands in available. At the start of each month I transfer funds from available to the various "envelope" accounts and try to keep them above 0 during the month. At month-end I refill any that wen\
t negative, bringing them to 0 before the next budget.
<sm> it's getting more effective over time.. working out a process and getting efficient with it is a slow process, I imagine it would be a bit quicker with YNAB which has it all laid out
```

**Comment by rstacruz** [comment]
interesting, @simonmichael. can you give us an example ledger file of that?

I've been thinking about this myself and I'm thinking it's probably better done on a separate ledger than your main one.

**Comment by simonmichael** [comment]
Here's one: https://gist.github.com/simonmichael/a1addcb652da4e78b183

**Comment by ony** [comment]
[Virtual postings approach](http://www.ledger-cli.org/3.0/doc/ledger3.html#Working-with-multiple-funds-and-accounts) is nice. But only when you write a few transactions. Otherwise without having #99 implemented this is very painful. It doubles the size of a journal which is pretty hard to keep already for lazy people.

**Comment by simonmichael** [comment]
Related thoughts:
http://ircbrowse.net/day/hledger/2016/12/30?id=43241&timestamp=1483132104#t1483132104
http://ircbrowse.net/day/hledger/2016/12/31?id=43358&timestamp=1483153839#t1483153839
