### ISSUE TITLE
Support for ledger's -%/--percent flag

### ISSUE THREAD

**Issue by matze** [simonmichael/hledger#319]
To determine the relative allocation of certain accounts I often use ledger-cli's `-%`/`--percent` flag which is used to

> Calculate the percentage value of each account in balance reports. Only works for accounts that have a single commodity.

It would be a really nice if this could find its way into hledger.
##

**Comment by simonmichael** [comment]
Agreed!

**Comment by narendraj9** [comment]
Are there any plans to implement this? This is very important because looking at the numbers doesn't really tell much if we don't know the relative allocation. And it seems that there is no support for sorting the balances as well. Currently, I sort them once I have the output.

**Comment by simonmichael** [comment]
These are not on my short list, pull requests welcome. For sorting balances, hledger bal | sort -n +1 perhaps ?

**Comment by narendraj9** [comment]
I have written a major mode for it, I do the sorting inside Emacs sort-numeric-fields function.

https://github.com/narendraj9/dotfiles/blob/master/.emacs.d/packages/rest/hledger-mode/hledger-reports.el#L191

**Comment by narendraj9** [comment]
What is the short list? I might be missing things that are important and your answer might help me understand managing things better.

**Comment by simonmichael** [comment]
Oh, nice.

My priority in hledger right now is to deliver the next release, so my list is pretty much this: https://github.com/simonmichael/hledger/milestone/4

**Comment by narendraj9** [comment]
Okay. Thanks. I might want to try to implement this. Which files should I start looking into?

**Comment by simonmichael** [comment]
Let's assume for now this flag would be for the balance command only, then [hledger/Hledger/Cli/Balance.hs](https://github.com/simonmichael/hledger/blob/master/hledger/Hledger/Cli/Balance.hs) is the place to start. It calls singleBalanceReport or multiBalanceReport depending on mode. I don't know if the percentage-reporting mode should be done inside those or outside them as is done for -V (see line 317).

**Comment by simonmichael** [comment]
This was added in 1.16.
