### ISSUE TITLE
multiple -f arguments fails if the files are of different format

### ISSUE THREAD

**Issue by anarcat** [simonmichael/hledger#320]
while investigating timelog support in hledger and ledgercli, i stumbled upon this weird bug where some of the multiple `-f` arguments are ignored if they are in a different format.

in other words, this prints time entries:

```
hledger -f timelog p
```

while this doesn't:

```
hledger -f timelog -f hledger.lgr p
```

The sample files are in the https://github.com/anarcat/ledger-timetracking repo, which also demonstrates a compatibility problem when applying accounts before includes, which i believe was fixed in https://github.com/simonmichael/hledger/commit/a2b989d898dec79a8ec1217dc238b75178cf6f39.

**Comment by anarcat** [comment]
oh, and of course `include` fails similarly (or worse, actually):

```
$ hledger -f hledger.lgr bal
using conversion rules file /home/anarcat/src/ledger-timetracking/hledger.lgr.rules
hledger: "/home/anarcat/src/ledger-timetracking/hledger.lgr" (line 2, column 1) in included file "timelog":
"/home/anarcat/src/ledger-timetracking/timelog" (line 1, column 1):
unexpected 'i'
expecting journal transaction or directive or end of input
```

should that be filed as a separate bug?

**Comment by simonmichael** [comment]
No, this is explicitly disallowed by the docs. But, with luck one fix will resolve both.

**Comment by simonmichael** [comment]
Partly fixed.. "The include directive can only be used in journal files. It can include journal, timeclock or timedot files, but not CSV files."

Eventually, we should be able to include any supported format. I'll leave this open as a reminder.

**Comment by simonmichael** [comment]
Ah shoot! I forgot the original `-f` case. That's still open.

**Comment by simonmichael** [comment]
Multiple FILES specified on the command line are now parsed individually, so they can have different formats. Directives in one file no longer affect subsequent files. I think this is ok.

**Comment by z3cko** [comment]
As this has been closed 4 years ago i guess you could also update your https://github.com/anarcat/ledger-timetracking @anarcat

**Comment by anarcat** [comment]
> As this has been closed 4 years ago i guess you could also update your https://github.com/anarcat/ledger-timetracking @anarcat

Patches welcome, I do not use (h)ledger anymore...

**Comment by z3cko** [comment]
>  I do not use (h)ledger anymore

whaaaat?

**Comment by anarcat** [comment]
> whaaaat?

Not sure how to respond to that, which part do you not understand? :)
