### ISSUE TITLE
website layout problems on mobile

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#324]
Reported recently on https://news.ycombinator.com/item?id=11034539: "Site layout is broken on mobile (at least Android Chrome)".

**Comment by simonmichael** [comment]
Could someone test the current http://hledger.org pages in Android Chrome and report the current status ?

**Comment by simonmichael** [comment]
@TomK32: Thanks! Much better, eg at http://www.mobilephoneemulator.com.

**Comment by simonmichael** [comment]
The original poster could also have been talking about http://demo.hledger.org (hledger-web), which also has problems on small screens, eg:

- no way to open/close sidebar
- if sidebar is showing, it insists on side-by-side layout

**Comment by simonmichael** [comment]
The main "hledger" heading on the home page doesn't fit on a small screen in portrait mode, it would be nice to shrink or fit it in that case.

**Comment by TomK32** [comment]
Do you use Firefox? `Ctrl-Shift-M` is a useful view where you can make the viewport smaller.

**Comment by simonmichael** [comment]
I believe hledger.org is readable now on small screens. Usability of hledger-web (demo.hledger.org) is tracked by #340.
