### ISSUE TITLE
empty space as digit group?

### ISSUE THREAD

**Issue by pablox-cl** [simonmichael/hledger#330]
I find it easier to read: `100 000`, than `100.000`, also because space is easier to type. The currency here in Chile is very 'low' compared to USD, so we normally have to use a lot of `.` (miminal wage per month is around `CLP 150 000`).

I tried to write (since we don't use decimals):

```
D $ 1 000,
```

But of course didn't work, so I was wondering if it was possible to be implemented :)
##

**Comment by simonmichael** [comment]
It seems to complicate parsing a bit more, but I would like to have this feature if anyone wants to work on it.

**Comment by PaBLoX-CL** [comment]
Obviously it's not that terrible, so it can wait. Where is the corresponding code?

**Comment by simonmichael** [comment]
https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Read/JournalReader.hs#L921 most likely.
