### ISSUE TITLE
Another character as account separator

### ISSUE THREAD

**Issue by PaBLoX-CL** [simonmichael/hledger#331]
A while ago when using GNUCASH, I was using dot `.`, instead the colon `:` to separate accounts (easier to type). Reading the documentation it says only "full colon". In the example journal file only have `equity.balances` and `assets.cash` and while `hledger` doesn't seem to complain, and `stats` shows:

```
$ hledger stats
Main journal file        : /home/pablo/.local/share/ledger/hledger.journal
Included journal files   : 
Transactions span        : 2016-03-09 to 2016-03-10 (1 days)
Last transaction         : 2016-03-09 (0 days ago)
Transactions             : 1 (1.0 per day)
Transactions last 30 days: 1 (0.0 per day)
Transactions last 7 days : 1 (0.1 per day)
Payees/descriptions      : 1
Accounts                 : 2 (depth 1)
Commodities              : 1 ($)
```

That means it's working?

**Comment by simonmichael** [comment]
I'd like to use `.` more myself. Normally if you use `.` hledger won't recognize the subaccounts. But at the end of http://hledger.org/manual.html#timedot you can see an example of how to make it work with an alias.

**Comment by simonmichael** [comment]
Now I see, sample.timedot uses `.`. I'll fix that.

**Comment by PaBLoX-CL** [comment]
Oh, I thought the `(depth 1)` meant that it recognized "1 level deep after base level", I guess then it refers to:

```
assets.cash
equity.open_balances
```

Are two accounts, and therefore `assets.checking` would be the third one.

I didn't understand the last part, could this be implemented?

**Comment by simonmichael** [comment]
Fixed sample.timedot and added http://hledger.org/how-to-use-another-account-separator-character.html . "(depth 1)" from the stats command means there is only one level of accounts. Hopefully all clear now.

**Comment by PaBLoX-CL** [comment]
wow, that was fast! thanks a lot :). I'm closing this since it's solved.
