### ISSUE TITLE
Inconsistent multi-currency formatting in csv balance

### ISSUE THREAD

**Issue by feuerbach** [simonmichael/hledger#336]
```
% cat test.journal 
; journal created 2016-04-19 by hledger

2016/04/19 1
    a        10 USD
    b     -10.0 USD

2016/04/19 2
    a        20 EUR
    b     -20.0 EUR

% hledger -f test.journal balance a -O csv
"account","balance"
"a","20.0 EUR
10.0 USD"
"total","20.0 EUR, 10.0 USD"
```

In one case multiple currencies are separated with newline, in another with a comma and space.

I'd prefer comma and space, this is also what `register` is using.

**Comment by simonmichael** [comment]
Good catch, thanks. Comma-separated is probably not optimal for CSV consumers but it beats malformed CSV.

**Comment by feuerbach** [comment]
It's not necessarily malformed (since the newline occurs inside the quotes), just inconsistent. Anyway, thanks for the quick fix!
