### ISSUE TITLE
Hledger/UI/UITypes.hs:55:13: No instance for (Show (Day -> AppState -> AppState))

### ISSUE THREAD

**Issue by juhp** [simonmichael/hledger#344]
When trying to rebuild hledger-ui-0.27.3 for Stackage Nightly today:

```
Hledger/UI/UITypes.hs:55:13:
    No instance for (Show (Day -> AppState -> AppState))
      (maybe you haven't applied enough arguments to a function?)
      arising from the second field of ‘AccountsScreen’
        (type ‘Day -> AppState -> AppState’)
    Possible fix:
      use a standalone 'deriving instance' declaration,
        so you can specify the instance context yourself
    When deriving the instance for (Show Screen)
```

**Comment by simonmichael** [comment]
Thanks. This was caused by https://github.com/ChrisKuklewicz/regex-tdfa/issues/2. I've revised hledger-lib-0.27 on hackage setting an upper bound on regex-tdfa which I think will take care of this.

**Comment by simonmichael** [comment]
And hledger-0.27, just to be safe.

**Comment by juhp** [comment]
Okay I thought so, but any chance you could support newer regex-tdfa?

**Comment by simonmichael** [comment]
Newer regex-tdfa is supported in hledger master branch, which will hopefully land in a new release fairly soon.

**Comment by juhp** [comment]
Thanks!  New point releases would really help now since now none of hledger*-0.27 builds any longer in Stackage Nightly.

**Comment by simonmichael** [comment]
Aiee, I see. I'll make point releases tomorrow. Rolling hledger back a major release seems potentially confusing, if necessary I think I'd rather have it excluded from the nightly.

**Comment by juhp** [comment]
Okay can do that for next nightly - thanks very much!

**Comment by simonmichael** [comment]
I have relaxed the regex-tdfa bound for hledger-lib and hledger 0.27 again, and I've released hledger-ui-0.27.4 to fix that package with newer regex-tdfa. Hopefully this takes care of it.

**Comment by juhp** [comment]
Thank you that is great!

**Comment by simonmichael** [comment]
I've revised hledger-ui-0.27.4's upper bounds for vty and brick.

**Comment by juhp** [comment]
Thanks!

**Comment by juhp** [comment]
They are all in yesterday's Stackage Nightly now.
