### ISSUE TITLE
transformers upper bound needs bumping for ghc 8

### ISSUE THREAD

**Issue by ilovezfs** [simonmichael/hledger#351]
To get hledger building under GHC 8.0.1 for Homebrew (we only typically support the latest GHC), I've needed to add a "cabal.config" file at the root of the package containing "allow-newer: transformers", at which point everything builds as expected. Without this, I get

```
==> cabal install --jobs=64 --max-backjumps=100000 --only-dependencies
clang: warning: -Wl,-headerpad_max_install_names: 'linker' input unused
clang: warning: argument unused during compilation: '-L/usr/local/lib'
clang: warning: argument unused during compilation: '-L/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries'
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: hledger-0.27 (user goal)
trying: transformers-0.5.2.0/installed-0.5... (dependency of
shakespeare-2.0.8.2)
next goal: wizards (dependency of hledger-0.27)
rejecting: wizards-1.0.2 (conflict: transformers==0.5.2.0/installed-0.5...,
wizards => transformers>=0.1 && <0.5)
rejecting: wizards-1.0.1 (conflict: transformers==0.5.2.0/installed-0.5...,
wizards => transformers>=0.1 && <0.4)
rejecting: wizards-1.0 (conflict: transformers==0.5.2.0/installed-0.5...,
wizards => transformers==0.2.*)
rejecting: wizards-0.1 (conflict: hledger => wizards==1.0.*)
Dependency tree exhaustively searched.
```

**Comment by ilovezfs** [comment]
Hmm, I seem to be getting this error when running `hledger test`
```
could not parse date "0000/00/00"
CallStack (from HasCallStack):
  error, called at ./Hledger/Utils/UTF8IOCompat.hs:122:10 in hledger-lib-0.27-HXd1Ym2WvHIBuxpEkzyu2a:Hledger.Utils.UTF8IOCompat
Cases: 68  Tried: 68  Errors: 1  Failures: 0
```

**Comment by simonmichael** [comment]
Thanks! This is due to https://github.com/liamoc/wizards/issues/8 which I've bumped. 

I'm not sure if you're updating the hledger homebrew formula, or just trying to build hledger from source ? See also https://github.com/simonmichael/hledger/issues/351.

**Comment by ilovezfs** [comment]
@simonmichael Yeah, I'm one of the homebrew maintainers, and doing upgrades for everything that didn't build with GHC 8 out of the box, of which this was one. Everything looked fine until CI ran hledger test. This is with `allow-newer: transformers`.

**Comment by ilovezfs** [comment]
@simonmichael https://github.com/Homebrew/homebrew-core/pull/1445

**Comment by simonmichael** [comment]
I guess hledger-lib's transformers bound will also cause the problem, as you say. I'll fix that with a release asap. Thanks for working on this.

**Comment by ilovezfs** [comment]
That would be awesome! :)

**Comment by simonmichael** [comment]
Related, though perhaps not a blocker: http://hub.darcs.net/ross/transformers/issue/29

**Comment by ilovezfs** [comment]
We use only cabal sandboxes not stack. transformers, base, and time have been the most common ones needing a bump. Looks like they're quite busy over at stack https://github.com/commercialhaskell/stack/issues/2192#issuecomment-221722028

**Comment by simonmichael** [comment]
hledger-lib and wizards have had a revision on Hackage to allow newer transformers. Is this sufficient ?

**Comment by ilovezfs** [comment]
@simonmichael It seems to build without patching now as you indicated, but I still am seeing the same test failure.
