### ISSUE TITLE
could not parse date "0000/00/00"

### ISSUE THREAD

**Issue by ilovezfs** [simonmichael/hledger#352]
Built with GHC 8.0.1 as described in #351, `hledger test` is throwing

```
could not parse date "0000/00/00"
CallStack (from HasCallStack):
  error, called at ./Hledger/Utils/UTF8IOCompat.hs:122:10 in hledger-lib-0.27-HXd1Ym2WvHIBuxpEkzyu2a:Hledger.Utils.UTF8IOCompat
Cases: 68  Tried: 68  Errors: 1  Failures: 0
```

**Comment by ilovezfs** [comment]
@simonmichael This is still happening despite the resolution of #351

**Comment by simonmichael** [comment]
Thanks, fixed in master now.

**Comment by ilovezfs** [comment]
@simonmichael Awesome. I'll give it a try right now.

**Comment by ilovezfs** [comment]
@simonmichael Do you mind creating a new tag? I'm attempting to build from the GitHub hledger-0.27 tag, but the patch doesn't want to apply cleanly.

**Comment by ilovezfs** [comment]
Yup, HEAD passes the test now :)


```
==> Summary
🍺  /usr/local/Cellar/hledger/HEAD: 29 files, 26.3M, built in 3 minutes 56 seconds
iMac-TMP:local joe$ brew test hledger
Testing hledger
==> Using the sandbox
==> /usr/local/Cellar/hledger/HEAD/bin/hledger test
iMac-TMP:local joe$
```

**Comment by simonmichael** [comment]
Would you prefer to have hledger-0.27.1 released now, followed soon after by hledger-0.28, or wait a little longer for 0.28 ?

**Comment by ilovezfs** [comment]
definitely 0.27.1. only needs to be on GitHub as a tag designated as stable, not necessarily released to hackage + $everywhere_else.

**Comment by simonmichael** [comment]
I have pushed (and released) hledger-lib-0.27.1, hledger-0.27.1, and hledger-ui-0.27.5, please let me know of any problems.

**Comment by ilovezfs** [comment]
You're awesome. Thank you.

**Comment by ilovezfs** [comment]
```
==> Summary
🍺  /usr/local/Cellar/hledger/0.27.1: 6 files, 24.9M, built in 3 minutes 46 seconds
iMac-TMP:local joe$ brew test -v hledger
Testing hledger
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160527-21265-17r3bvi.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-core/Formula/hledger.rb -v
==> /usr/local/Cellar/hledger/0.27.1/bin/hledger test
Cases: 75  Tried: 75  Errors: 0  Failures: 0
iMac-TMP:local joe$ 
```

@simonmichael Looks great. Waiting on CI to build the bottles and then it'll :ship:

**Comment by ilovezfs** [comment]
@simonmichael Shipped: https://github.com/Homebrew/homebrew-core/commit/abf0366689aaa9bb6baa5652d2c2458507225a2c
