### ISSUE TITLE
get hledger into stackage GHC 8 snapshots [8|6.5]

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#353]
Status:

| package | in stackage GHC8 nightlies | blockers ? |
| --- | --- | --- |
| [hledger-lib](https://www.stackage.org/package/hledger-lib) | yes |  |
| [hledger](https://www.stackage.org/package/hledger) | yes |  |
| [hledger-ui](https://www.stackage.org/package/hledger-ui) | yes |  |
| [hledger-web](https://www.stackage.org/package/hledger-web) | yes |  |
| [hledger-api](https://www.stackage.org/package/hledger-api) | yes |  |
| [hledger-interest](https://www.stackage.org/package/hledger-interest) | yes |  |

https://github.com/fpco/stackage/blob/master/build-constraints.yaml
https://www.fpcomplete.com/blog/2016/05/moving-stackage-nightly-ghc-8
https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0
##

**Comment by cocreature** [comment]
brick was intentionally [removed from stackage](https://github.com/jtdaugherty/brick/issues/60#issuecomment-223714942), so you won’t be able to get hledger-ui back into stackage.

**Comment by simonmichael** [comment]
That discussion makes me sad, but we can still get hledger-ui into stackage, as stackage automatically includes brick as long if it can build it. And it's already doing so (both pre and post GHC 8 snapshots). The current blocker for hledger-ui in the GHC 8 snapshots that it needs to allow newer vty and brick:
```
brick-0.8 is out of bounds for:
- [ ] hledger-ui-0.27.5 (>=0.2 && < 0.7). Simon Michael <simon@joyful.com> @simonmichael. @simonmichael
vty-5.7.1 is out of bounds for:
- [ ] hledger-ui-0.27.5 (>=5.2 && < 5.6). Simon Michael <simon@joyful.com> @simonmichael. @simonmichael
```

**Comment by simonmichael** [comment]
And for hledger-web, I think its tight hledger/hledger-lib==0.27 bound is the only blocker.
```
hledger-0.27.1 (Simon Michael <simon@joyful.com> @simonmichael) is out of bounds for:
- [ ] hledger-web-0.27 (==0.27). Simon Michael <simon@joyful.com> @simonmichael. @simonmichael
hledger-lib-0.27.1 (Simon Michael <simon@joyful.com> @simonmichael) is out of bounds for:
- [ ] hledger-web-0.27 (==0.27). Simon Michael <simon@joyful.com> @simonmichael. @simonmichael
```

**Comment by simonmichael** [comment]
All the main hledger packages are in stackage nightly as of 2016-10-28. The latest hledger & hledger-lib are in stackage LTS as of 7.6, and the other packages [may be added in LTS 7.7](https://github.com/fpco/lts-haskell/issues/30).
