### ISSUE TITLE
release 0.28 is overdue, issue management

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#371]
It has been too long since a major release. 0.28 keeps getting pushed back. Contributing factors include:
1. feature creep, unclear priorities, unclear release goals
2. a tedious release notes process that I avoid
3. joint release of the hledger-\* packages means waiting for sufficient visible changes in all of them

1 has been enabled by my extensive private task list which has grown into a second (third, fourth ? see also notes.org, [trello.hledger.org](http://trello.hledger.org)) issue tracker.

Corrective actions:
- [x] issue tracker gardening: issues, labels, milestones, urls, clarify & document usage for bugs/features/tasks
- [x] clean up private backlog, begin moving to issue tracker as appropriate
- [x] minimise work on things not in the issue tracker
- [x] mark issues and PRs for 0.28 milestone
- [x] review, prioritise, estimate, adjust, set dates, limit WIP
- [x] list remaining release tasks
- [ ] review/merge/drop notes.org
- [ ] clarify/streamline processes where possible
- [x] switch to package.yaml files
- [ ]  simplify version string updates

[milestones](https://github.com/simonmichael/hledger/milestones?direction=desc&sort=due_date&state=open)
[currently scheduled for 0.28](https://github.com/simonmichael/hledger/issues?utf8=✓&q=is%3Aopen%20is%3Aissue%20milestone%3A0.28%20)
[currently not scheduled for 0.28](https://github.com/simonmichael/hledger/issues?q=is%3Aopen+is%3Aissue+-milestone%3A0.28+sort%3Acreated-desc)

0.28 release plan:
- [x] focus issue tracking
- [x] issue/PR triage
- [ ] close open [0.28 issues](https://github.com/simonmichael/hledger/milestone/4)
- [x] merge PRs
- [x] rename to 1.0
- [x] release notes
- [x] release announcement
- [x] tag, release, announce
##

**Comment by simonmichael** [comment]
How to help: close issues in the [0.28 milestone](https://github.com/simonmichael/hledger/milestone/4)!

**Comment by crocket** [comment]
Is the latest master stable most of the time?

**Comment by simonmichael** [comment]
Yes.

**Comment by simonmichael** [comment]
Done, ignoring unimportant open issues and calling it 1.0.
