### ISSUE TITLE
hledger-ui not building on windows is confusing / set up appveyor

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#376]
In https://github.com/ndmitchell/ghcid/issues/71#issuecomment-234513139 @ndmitchell reports problems building on windows due to unix dependency, investigate.

> I can no longer build hledger since it now ends up requiring unix on my system, and configuring that fails.

..

> Windows building: hledger-ui is known not to build on windows, since it depends on vty, so the whole project won't, but the other packages should (eg stack build hledger). I think the unix package is supposed to pull in unix-compat or something. I've opened simonmichael/hledger#376 for investigation, any more details welcome.

**Comment by ndmitchell** [comment]
Can I recommend an Appveyor continuous integration instance. The template at https://github.com/ndmitchell/extra/blob/master/appveyor.yml is probably enough to get going with.

**Comment by simonmichael** [comment]
Yes! I have been meaning to look into that, will do.

**Comment by ndmitchell** [comment]
It's pretty easy, but if you get stuck just give me a yell. (Working out that script, and fixing the bugs in stack, took months - but now we're there, it's not too hard.)

**Comment by simonmichael** [comment]
Marking this as a bug, it should be made clear how to avoid build problems on windows - eg by disabling the hledger-ui package automatically on that platform ?

**Comment by simonmichael** [comment]
Getting started with Appveyor was really quick - thanks for that!

It's now building all but hledger-ui, and saving the executables as build artifacts.

I updated the hledger-ui to package to not build at all on windows (buildable:false), but it didn't seem to work as expected on appveyor. If you have the chance to pull the latest and try stack build [hledger-ui] again, I'd like to know what happens.

**Comment by simonmichael** [comment]
Attempts to build hledger-ui on windows now fail early with a slightly more informative "Package hledger-ui-0.28 can't be built on this system". On windows, you'll see this error when doing "stack install hledger-ui". You will also see it when doing "stack install" (of all packages) in the hledger source dir. 

The information that hledger-ui isn't supported on windows has fallen off the download page and needs be added there (at least).

Here's the status of getting vty (and hledger-ui) on windows: https://github.com/coreyoconnor/vty/pull/1
