### ISSUE TITLE
check for valid commodity symbols

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#380]
We'd like to have the ability to define the valid commodity symbols, and warn/fail if an amount is found with some other symbol. This would eg reduce errors like:

> I made a typo in a Ledger file ...
> 
> ``` journal
> 2016/07/21 Store
>     Expenses:Groceries                         $9.27
>     Expenses:Drugstore                         10.50  ; <- missing dollar sign
>     Liabilities:CCard                        -$19.77
> ```
> 
> ... Should Hledger also ideally have given me an error message given the mistake in my file?

We have a `commodity` directive (cf #295). Perhaps a reasonable design is to say if any commodity directives are found, allow only those commodities. This should be pretty easy to implement.
##

**Comment by Xitian9** [comment]
I think this is implemented by `hledger --strict` or `hledger check commodities`, and so this can be closed.
