### ISSUE TITLE
Mixing .csv and .ledger files

### ISSUE THREAD

**Issue by rstacruz** [simonmichael/hledger#385]
Hey there, the docs say you can mix files of different formats (emphasis mine):

> __Multiple files__  
> You can specify multiple -f/--file FILE options. This is like combining all the files into one, **except they can have different formats.** Also directives and aliases in one file do not affect subsequent files (if you need that, use the include directive instead).

But this doesn't seem to work:

```sh
# setup.ledger
2015/01/01 Hello
  A  P 1.00
  B
```

```sh
# cash.csv
2016/08/06, 957, Food
```

```sh
# cash.csv.rules
fields date, amount, description
amount P %2
account1 Expenses:Variable:Misc
account2 Assets:Cash
status *
```

**Comment by simonmichael** [comment]
It works for me, but only using the development version of hledger, from git. I'm guessing you read http://hledger.org/manual.html but didn't notice that it's for this version. The "version: dev | 0.27" links at the top try to hint this. Does that explain it ? How could things be improved ?

```shell
$ hledger -f setup.ledger -f cash.csv print
using conversion rules file /Users/simon/src/hledger/385/cash.csv.rules
2015/01/01 Hello
    A        P 1.00
    B       P -1.00

2016/08/06 *  Food
    Assets:Cash                   P -957
    Expenses:Variable:Misc         P 957

~/src/hledger$ hledger-0.27.1 -f setup.ledger -f cash.csv print
using conversion rules file /Users/simon/src/hledger/385/cash.csv.rules
hledger-0.27.1: user error (CSV record ["2015/01/01 Hello"] has less than two fields)
```

**Comment by rstacruz** [comment]
The docs said it was for 0.27, and I was running 0.27.1 from homebrew :)

**Comment by simonmichael** [comment]
Where do you see the docs saying they are for 0.27 ?

**Comment by rstacruz** [comment]
It says it's for version dev or 0.27 in the hledger website :)

**Comment by simonmichael** [comment]
Hmm. So, to be specific, you're looking at eg the top of http://hledger.org/manual.html ?

There, you see "version: dev | 0.27" which is my ultra-cheap docs version indicator/selector. "dev" is not a link, "0.27" is. In my mind, this means "you are looking at the docs for the unreleased development version. Click the link to see docs for that version instead". 

Clicking 0.27 takes you to http://hledger.org/doc/0.27/manual.html, which is the doc you want. (This one does not have the version links at top because I didn't want to fiddle with the old docs.)

Making sense ? Suggestions/patches to make it clearer ?

**Comment by rstacruz** [comment]
Oh! Oops, yeah, that part was rather confusing indeed. I see now. I have no
suggestions on how to improve it though.

Thank you for hledger!

**Comment by simonmichael** [comment]
Working on a better doc version selector. Thanks for the reports!

**Comment by rstacruz** [comment]
My impression was it was an indicator like "Available on versions: dev,
0.27, 0.26 and 0.25".

**Comment by simonmichael** [comment]
Closed this accidentally. But hopefully it's now clear enough which version of web manual you are looking at and how to get to the right one. If not let me know.

**Comment by simonmichael** [comment]
PS you'll have to reload the hledger.org pages once in your browser to see the latest.
