### ISSUE TITLE
Documentation for the ~ regex format

### ISSUE THREAD

**Issue by rstacruz** [simonmichael/hledger#386]
The document in http://hledger.org/how-to-read-csv-files.html reads:

```sh
# if the CSV record contains ‘SAVINGS’, set the second account to assets:bank:savings
# (if not set, it will be expenses:unknown or income:unknown)
if ~ SAVINGS
  account2 assets:bank:savings
```

But there seems to be to explanation for what `if ~ SAVINGS` means. http://hledger.org/manual.html#csv-format has nothing on it. Any hints? :)

**Comment by simonmichael** [comment]
Yup. This how-to assumes that the reader wanting more detail will follow the "CSV rules syntax" link to see the full docs, where http://hledger.org/manual.html#conditional-block is explained. Improvements welcome ?

**Comment by simonmichael** [comment]
Oh! You did follow the link, and probably saw conditional block, but `~` (tilde) is not mentioned there. Good catch! I think that was an older syntax to enable regular expression matching. I'll investigate.

**Comment by simonmichael** [comment]
It's an optional operator, currently ignored:
https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Read/CsvReader.hs#L543
It was intended to select regex/non-regex and positive/negative matching (and later, field-specific matching). I've removed it from the how-to for now.
