### ISSUE TITLE
easier import command for deduplicating CSV etc.

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#388]
From mail list:

Using a checksum for deduplication won't handle identical CSV records 
well, right ? Those are unlikely with our usual banks but I think quite 
possible if you consider CSV data generally.

Here's my recent plan for hledger. Let reading CSV files work as it 
currently does, but add a separate import command which does some 
additional things: append the converted entries to the main journal 
file, and save a position marker in CSVFILE.lastimport. Also when 
reading, if the marker file is found, skip any CSV records before the 
marked position.

This much is generic and could be used with any data format, but I think 
it makes sense mainly for "import" data which you want to move into a 
main journal, and which is somewhat sequential, eg CSV, OFX QIF. It's 
would be harder and is probably not needed for eg journal or timeclock 
files.

For CSV specifically, I'm thinking the position marker will be the last 
CSV record processed. It could be elaborated later to consider 
timestamps, checksums etc. if needed.
##

**Comment by tshirtman** [comment]
i used the last import idea for my scripts, fetching csv data from bank, cleaning up, adding to journal, then updating last import.

**Comment by simonmichael** [comment]
hledger 1.4 has the [import command](http://hledger.org/manual.html#import).
