### ISSUE TITLE
inacct: is undocumented

### ISSUE THREAD

**Issue by rstacruz** [simonmichael/hledger#390]
hledger-web uses `inacct:Assets`, while the docs say the proper syntax is `acct:Assets` ([here](http://hledger.org/doc/0.27/manual.html#queries)). Is there a difference between `acct:` and `inacct:`?

**Comment by simonmichael** [comment]
Yes they are different. `inacct` is a special, I guess undocumented, term used in hledger-web to set the current account we are "in" in a register view, which affects which transactions are shown and also how they are presented. You can have `acct` terms as well, providing extra filtering.

**Comment by rstacruz** [comment]
Are they functionally the same when used in the CLI?

**Comment by simonmichael** [comment]
No (try it). I've added a note to http://hledger.org/manual.html#queries .

**Comment by rstacruz** [comment]
Oh, neat! BTW, I'm working on an hledger-web clone (with more focus on
reports and visualization), your comments are really helpful.

**Comment by simonmichael** [comment]
Great! Don't forget about hledger-api, in case it's useful.
