### ISSUE TITLE
Question: grouping transactions in `reg -O csv`

### ISSUE THREAD

**Issue by rstacruz** [simonmichael/hledger#391]
Doing `hledger reg -O csv` gets you a list of postings:

```
"2016/08/06","7-Eleven","Assets:Cash","P -500.00","P -500.00"
"2016/08/06","7-Eleven","Expenses:Variable:Misc","P 500.00","0"
"2016/08/07","McDonalds","Assets:Cash","P -350.00","P -350.00"
"2016/08/07","McDonalds","Expenses:Variable:Dine","P 350.00","0"
```

Doing it without `-O` csv shows them grouped properly by transaction:

```
2016/08/06  7-Eleven   Assets:Cash
                       Expenses:Variable:Misc
2016/08/07  McDonalds  Assets:Cash
                       Expenses:Variable:Dine
```

Is there any way I can get this grouping information via -O csv? I'm trying to make a UI here and that info would be very useful!

**Comment by simonmichael** [comment]
`print -O csv` adds the transaction index field, providing this information. This should be added to register's CSV output too, good idea.
