### ISSUE TITLE
In a specific case, the share count is incorrect for the balance command

### ISSUE THREAD

**Issue by cerk** [simonmichael/hledger#395]
I am running hledger 0.27 on Windows. I am experiencing incorrect output on the "balance" command for the following example journal:

test.txt
```
2016/01/27 Fund
    Asset:Broker                  $70,000.00
    Asset:Checking

2016/01/28 Buy
    Asset:Broker                    1,388 MSFT
    Asset:Broker                 $-69,400.00

2016/01/29 Sell
    Asset:Broker                   -1,388 MSFT
    Asset:Broker                  $69,500.00

2016/01/30 Buy
    Asset:Broker                      115 MSFT
    Asset:Broker                  $-5,750.00
```

Output of:
hledger -f test.txt bal --flat
```
          $64,350.00
        115,000 MSFT  Asset:Broker
         $-70,000.00  Asset:Checking
--------------------
          $-5,650.00
        115,000 MSFT
```

What should be 115 MSFT, turns out to be 115,000 MSFT.

If I had to guess, this issue is probably related this hledger feature in the FAQ:

> hledger's output follows the decimal point character, digit grouping, and digit group separator character used in the journal.

I am guessing that the 1,388 MSFT (with a comma) does not play well with the 115 MSFT (with no comma) on the final output. I do not know Haskell so I cannot pinpoint anything wrong with the code.

Note that the following journals work without error:

test2.txt
```
2016/01/27 Fund
    Asset:Broker                  $70,000.00
    Asset:Checking

2016/01/28 Buy
    Asset:Broker                    1,388.00 MSFT
    Asset:Broker                 $-69,400.00

2016/01/29 Sell
    Asset:Broker                   -1,388.00 MSFT
    Asset:Broker                  $69,500.00

2016/01/30 Buy
    Asset:Broker                      115.00 MSFT
    Asset:Broker                  $-5,750.00
```

test3.txt
```
2016/01/27 Fund
    Asset:Broker                  $70,000.00
    Asset:Checking

2016/01/28 Buy
    Asset:Broker                    1,388.00 MSFT
    Asset:Broker                 $-69,400.00

2016/01/29 Sell
    Asset:Broker                   -1,388.00 MSFT
    Asset:Broker                  $69,500.00

2016/01/30 Buy
    Asset:Broker                      115 MSFT
    Asset:Broker                  $-5,750.00
```

Output of either:
hledger -f test2.txt bal --flat
or:
hledger -f test3.txt bal --flat
```
          $64,350.00
         115.00 MSFT  Asset:Broker
         $-70,000.00  Asset:Checking
--------------------
          $-5,650.00
         115.00 MSFT
```

test4.txt
```
2016/01/27 Fund
    Asset:Broker                  $70,000.00
    Asset:Checking

2016/01/28 Buy
    Asset:Broker                     1388 MSFT
    Asset:Broker                 $-69,400.00

2016/01/29 Sell
    Asset:Broker                    -1388 MSFT
    Asset:Broker                  $69,500.00

2016/01/30 Buy
    Asset:Broker                      115 MSFT
    Asset:Broker                  $-5,750.00
```

Output of:
hledger -f test4.txt bal --flat
```
          $64,350.00
            115 MSFT  Asset:Broker
         $-70,000.00  Asset:Checking
--------------------
          $-5,650.00
            115 MSFT
```

So my current workaround is to always have some decimal places after share counts, even though they are not normally fractional. Can anyone reproduce this?

**Comment by cerk** [comment]
After thinking about it, hledger must be interpreting the first 1,388 MSFT as 1.388 MSFT (so it interprets the comma as a decimal place). Then on the output it infers the output as using the comma as a decimal place and so 115,000 MSFT is actually correct. Sorry for my confusion.

After reading about commodity directives, I'm not sure that is the answer to "my problem" either. Is there anyway to specify a commodity directive such that I want commas to be thousands separators and I don't want a decimal place because I know the values will always be integers?

**Comment by cerk** [comment]
From the manual:

Decimal points and digit groups

hledger supports flexible decimal point and digit group separator styles, to support international variations. Numbers can use either a period (.) or a comma (,) as decimal point. They can also have digit group separators at any position (eg thousands separators) which can be comma or period - whichever one you did not use as a decimal point. If you use digit group separators, you must also include a decimal point in at least one number in the same commodity, so that hledger knows which character is which. Eg, write $1,000.00 or $1.000,00.

So it appears that I can either choose 1388 MSFT (no commas) or 1,388.0 MSFT, but not 1,388 MSFT. And this is by design.

Closing this issue.

**Comment by simonmichael** [comment]
Hi, thanks for the report. You are right, it is functioning as designed. There may be things we could change to make it more intuitive/discoverable, however. Eg, perhaps the decimal point and digit group style should be the same across all commodities ?

Note you don't have to write every MSFT amount with both commas and decimal point, just one will do. In hledger dev (not yet released), http://hledger.org/manual.html#commodity-directive is another way to specify the style.

**Comment by cerk** [comment]
Thanks for your response.

A slight problem with the commodity directive is that it only specifies one symbol. I.e., if I were tracking hundreds of stock positions, I would have to have a commodity directive per stock symbol.

For my very specific situation, a "culture info" flag would probably be the most ideal (or a "culture info" directive). Some flag or directive that would specify that I always wanted hledger to infer American amounts. So a comma would always be viewed as a thousands separator.

That being said, this suggestion is just nitpicking and now that I know what I was doing wrong, I can adjust accordingly.
