### ISSUE TITLE
Can't Use Thousand Separators Without Using A Decimal Separator

### ISSUE THREAD

**Issue by ORYLY** [simonmichael/hledger#399]
Thousand separators in an amount number can't be used unless the number also has a decimal separator. If there is only one punctuation mark, it's always considered to be a decimal separator even if one or more of the following are present:
- A "D directive" with:
  - A sample amount using only a thousand separator.
  - A sample amount using both thousand and decimal separators.
- A commodity directive that defines a format similar to the sample amounts listed above.
- A preceding transaction with an amount that uses a format similar to the sample amounts listed above.

For example:

```
D JPY 111,111,111
# also doesn't work:
# D JPY 111,111,111.0
# D JPY 1,111
# D JPY 1,111.0

2016/01/01 default_commodity
  (asset:no_comma)  100
  (asset:comma)  100,500
```

The balance sheet for this journal adds up to ""200,500" or "200.500" for either commodity, rather than "100,600".

Using a commodity directive also has incorrect totals. An unexpected value rounding also occurs with the format "JPY 111,111,111".

```
commodity JPY
  format JPY 111,111,111 # also causes unexpected rounding

#  format JPY 111,111,111.0
#  format JPY 1,111
#  format JPY 1,111.0

2016/01/01 yen
  (asset:commodity:no_comma)  JPY 100
  (asset:commodity:comma)  JPY 100,500
```

Using a preceding dummy transaction with a sample amount has the same output as the cases above:

```
2016/01/01 init
  (asset:commodity:init)  JPY 111,111,111
  (asset:commodity:init)  JPY -111,111,111
  # same output with the formats tried in other examples

2016/01/01 yen
  (asset:commodity:no_comma)  JPY 100
  (asset:commodity:comma)  JPY 100,500
```
##

**Comment by ony** [comment]
Oh. How did I missed this. I've created a duplicate  #487 and even pull request #635 to fix this slightly.

**Comment by simonmichael** [comment]
Heh heh the hledger issue tracker is getting a bit... mazelike.
