### ISSUE TITLE
Problem : Parser errors are not informative.

### ISSUE THREAD

**Issue by crocket** [simonmichael/hledger#402]
```
commodity BTC
  note Bitcoin
```

When I parse the above journal with hledger, it should report that `note` is not a supported subdirective of commodity directive.

Instead, the parser reports the following error.

```
hledger: ledger.journal:1:1:
unexpected 'c'
expecting end of input or transaction or directive
```

The same happens when `account` directive contains unsupported subdirectives and when the end of a journal file is not a new line. When the end of a journal file is not a newline, the parser reports an error at the beginning of the last transaction or any last directive.
##

**Comment by simonmichael** [comment]
Agreed, thanks.

**Comment by karan-ta** [comment]
I started using timedot format and created a new file with contents :  
2016/2/2
client1   .... ....
research  .

but i got error - 
using conversion rules file /karanahuja.timedot.rules
hledger: "/karanahuja.timedot" (line 2, column 1):
unexpected 'i'
expecting journal transaction or directive or end of input

**Comment by simonmichael** [comment]
That looks strange. I can't reproduce here with hledger 1.2..

**Comment by ony** [comment]
@crocket I agree that errors sometimes quiet hard to understand because of excessive backtracking in journal parser.

Note that it is hard to identify "not supported" because it means that we should already partially support that sub-directive in parser. On the other hand most of the parser able to generate meaningful error message with their expectations. Example:

```
hledger: -:2:3:
unexpected 'n'
expecting "format"
```

**Comment by ony** [comment]
With newer `MegaParsec` you can get even better error report:

```
hledger: -:2:3:
unexpected "note B"
expecting "format"
```

**Comment by simonmichael** [comment]
The specific error reported by this issue has been improved: https://github.com/simonmichael/hledger/pull/640#issuecomment-347354365
