### ISSUE TITLE
Problem : Documentations for hledger and journal don't explain --value clearly.

### ISSUE THREAD

**Issue by crocket** [simonmichael/hledger#403]
http://hledger.org/journal.html#market-prices says `When market prices are known, the -V/--value option will use them to convert reported amounts to their market value as of the report end date.`.

There are two problems with this.
1. The report end date is not defined. The definition should be given on http://hledger.org/journal.html#market-prices.
2. `as of` could mean two things. `On the report date` and `From the report date on`.

It's better to say something like `convert reported amounts to their latest market values before or on the report end date. For example, if the report end date was 2010/1/25, a market value on 2015/1/25 can be used, but a market value on 2015/1/26 cannot be used.`

http://hledger.org/hledger.html#market-value says `The -V/--value flag converts all the reported amounts to their "current market value" using their default market price. That is the latest market price (P directive) found in the journal (or an included file), for the amount's commodity, dated on or before the report end date.`

This is confusing. I'd write something like `The -V/--value flag converts all the reported amounts to their "current market value". The current market value is the latest market price (P directive) found in the journal (or an included file), for the amount's commodity, dated on or before the report end date. For example, if the report end date was 2015/1/26, a market value on 2015/1/26 can be used, but a market value on 2015/1/26 cannot be used.`

I haven't defined report end date in the above examples. But, a pull request that addresses this issue will include the definition of report end date.
##

**Comment by simonmichael** [comment]
Wow. This sounded like a quick docs fix, but looks were deceiving. [Two](https://github.com/simonmichael/hledger/issues/453) [fixes](https://github.com/simonmichael/hledger/commit/1866d2375d21c1ad0ac190f7c58346401f87c0ca) and many docs clarifications later, I think this is resolved. I have rewritten
http://hledger.org/journal.html#market-prices and http://hledger.org/hledger.html#market-value, added a section http://hledger.org/hledger.html#report-start-end-date and added a bunch of links between these places (with some text hints for when hyperlinks are not available, eg in man pages). 

Thanks for this helpful feedback.
