### ISSUE TITLE
csv rules following conditional blocks don't work

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#414]
http://hledger.org/manual.html#csv-rules says rules can appear in any order, but rules placed after a conditional block don't take effect.
##

**Comment by traytonwhite** [comment]
I'm interested in taking a look at this, but I'm not sure how to recreate the issue. If I run a modified version of Test 4 from `tests/csv/read.test`, it seems to work as expected. I have a conditional block at the top of the rules file, but the other rules after the block are executed.

```
rm -rf t.rules$$; printf 'if Brainard\n  account2 acct\nfields date, description, amount\ndate-format %%d/%%Y/%%m\nif Flubber\n  account2 acct\n  comment cmt\ncurrency $\naccount1 assets:myacct' >t.rules$$; printf '10/2009/09,Flubber Co,50\n12/2009/01,Brainard,100' | hledger -f- print --rules-file t.rules$$; rm -rf t.rules$$
using conversion rules file hledger/t.rules45506
2009/01/12 Brainard
    acct                  $-100
    assets:myacct          $100

2009/09/10 Flubber Co    ; cmt
    acct                   $-50
    assets:myacct           $50

```

**Comment by simonmichael** [comment]
Thanks for looking @traytonwhite. What about the unmodified test 4 ? Does make functest pass for you ?

**Comment by traytonwhite** [comment]
Unmodified test 4 works for me as well. But it's reported as test 3 since the "real" test 3 is commented out right now (`3. report rules parse error`). I do get the expected error for test 5 (`5. this should infer display styles correctly`) from #415 , but it's reported as test 4. There seems to be an unrelated issue with one of the cli tests:

```
> make functest
:tests/cli/multiple-files.test:3: [Failed]

Expected stdout:
2014/01/02
    expenses:food            $1
    assets:cash             $-1

2016/01/01 * 12:00-16:00
    (a:aa)         4.00h

2016/01/01 *
    (b.bb)          1.00


Got stdout:

Expected exit code:
0
Got exit code:
1
:tests/csv/read.test:4: [Failed]

Expected stdout:
          $-1,001.00  income:unknown
           $1,001.00  unknown

Got stdout:

Expected exit code:
0
Got exit code:
1
```

**Comment by adept** [comment]
@simonmichael do you still have an example for this? I can't reproduce, I think this got fixed at some point

**Comment by simonmichael** [comment]
No, it sounds very likely that it’s fixed.
