### ISSUE TITLE
csv conversion can produce multiple styles for a commodity

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#415]
This test fails:

```
hledger --rules-file minimal.csv.rules -f- balance --no-total
<<<
"2016/1/1","$1"
"2016/2/2","$1,000.00"
>>>
          $-1,001.00  income:unknown
           $1,001.00  unknown
>>>=0
# Got stdout:      
#            $-1001.00  income:unknown
#            $1,001.00  unknown
```

There should be a comma in both dollar amounts, not just the second.
##

**Comment by adept** [comment]
I think that processing the generated file with hledger will actually display the correct formatting. Close?

**Comment by simonmichael** [comment]
I expect piping through another hledger print can fix it, yes, but I think ideally it should be right the first time, since we treat CSV as a “first class” format to some degree.

**Comment by adept** [comment]
Well, but it is not really first-class, is it? I can't write a file with `commodity` directive, `include` csv file in there and expect things to work. I likewise can't include journal with `commodity` directive in CSV file.

I can't even specify both files on the command line and expect CSV file to honor `commodity` directive ...

The only way to start approaching this would be to re-parse records produced by CSV printer, but this creates a whole host of other problems (most of which could be tied back to the fact that each CSV file in reality is being processed in isolation)

**Comment by simonmichael** [comment]
It doesn’t have all the features of the journal format, sure, but it’s first class in the sense of having equal billing with the other file formats, and I consider it a normal use case to run reports directly from csv files, without having to convert and save to journal format.

**Comment by simonmichael** [comment]
Resolved in master.
