### ISSUE TITLE
csv converstion - line feed in description field causes additional crlf in output

### ISSUE THREAD

**Issue by pragmat1c** [simonmichael/hledger#416]
Citibank has a problem with inserting a line feed at the end of their description fields. (I've reported the issue to them.)

This causes a problem in the csv conversion.

Example input:
![image](https://cloud.githubusercontent.com/assets/1749623/19224663/0fb7e10e-8e50-11e6-8ce0-f58ffdd4c653.png)

Example output:

![image](https://cloud.githubusercontent.com/assets/1749623/19224671/4c650348-8e50-11e6-805c-0fa350680f9d.png)

And of hledger doesn't like the the resulting journal file:

```
hledger: c:\Tools\hledger\test.tmp:7:5:
unexpected 'e'
expecting newline
```
##

**Comment by simonmichael** [comment]
Nice example. But, I think we can say that kind of data cleanup should be handled outside hledger, would you agree ?

**Comment by pragmat1c** [comment]
I think it's something that _can_ be handled outside of hledger. (In fact I have a script that cleans up the file and that works fine for me :-) ).

However, from a "right thing to do" standpoint:

1. Line feeds are valid in csv fields.
2. Hledger is generating journal output that is clearly invalid, meaning it can't be read by hledger itself.

So I think we have 3 options:

1. Leave as is,  line feeds/carriage returns in description fields will need to be removed manually or via a script.
2. Detect cr/lf's in description fields and fail with an error message.
3. Remove cr/lf's from the description field when parsing csv's.

Would a patch to do #3 above be acceptable, or do we not want to touch this at all?

I'm trying to set this up on my Windows 10 system. That is not working so well. Maybe I'll dig out my mint laptop and see if I get everything running/buiding on that.

**Comment by simonmichael** [comment]
You persuade me, sure a patch would be welcome. 

hledger dev should be easy on Windows too, any bug reports for that are also welcome.

**Comment by simonmichael** [comment]
Since #1095, we now convert line feeds/carriage returns within quoted values to a single space.
