### ISSUE TITLE
run all tests in CI

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#419]
Our continuous integration test setup (Travis & Appveyor) should run more tests. Eg it should run functional tests (make functest), which are quite important. Cf https://github.com/simonmichael/hledger/pull/410#issuecomment-251752411.
##

**Comment by simonmichael** [comment]
Related: #424, #520.

**Comment by Xitian9** [comment]
I think this is done now? If more is desired, perhaps a new issue instead of keeping this old one around.
