### ISSUE TITLE
appveyor CI builds are failing intermittently

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#424]
See https://github.com/haskell/cabal/issues/4005

**Comment by simonmichael** [comment]
Also https://github.com/commercialhaskell/stack/issues/2617 and this [unpleasant workaround](https://github.com/input-output-hk/cardano-sl/commit/61470aa41b70428467543f5ac23118fa1fa5a2f6).

**Comment by simonmichael** [comment]
Update: it looks like this has been fixed in GHC 8.1, so we can wait (a long time) for that to arrive on appveyor, or use the (ugly) retries hack.

**Comment by MatthiasKauer** [comment]
Is AppVeyor building hledger at the moment or have you paused that?
The last build with an artifact I can find is: https://ci.appveyor.com/project/simonmichael/hledger/build/master-258
I have tried to find the GHC version on AppVeyor but without success. I presume the fix you mention hasn't arrived yet, has it?

Do we have to compile Windows builds locally for now? I suppose the download page kinda answers that already but I'm trying to avoid it, hehe.

**Comment by simonmichael** [comment]
It's still paused, yes. I doubt if appveyor has a new-enough GHC yet, but I don't know for sure. Yes building yourself is probably required on Windows. Is that hard though ?

**Comment by MatthiasKauer** [comment]
Thank you for the explanation.
Actually, it wasn't that hard. I had expected worse after my adventures with the gitit compilation.
Anyway, it still was a 1h process and I now have more than 1GB of artifacts around.
I'd say it's worth uploading the exe I just created for others. What do you think? Is github the best place for that?

**Comment by simonmichael** [comment]
Binaries need periodic updating, extra support when it doesn't work on somebody's system, and (should) carry an extra burden of attention to security - checksums, signing, transparent build process etc. Is this something you'd be willing to take on ? I feel that some existing CI system is a cost-effective way to do it.

**Comment by simonmichael** [comment]
PS I will re-enable and play around with appveyor again.  It sounds like stack build -j1 might be a workaround.

**Comment by MatthiasKauer** [comment]
You are correct. I was oversimplifying it. My local "build environment" for a lack of a better word certainly has its issues. I have ideas about how to do it without AppVeyor but my energy level might not suffice at the moment.

**Comment by simonmichael** [comment]
Nightly [appveyor builds](https://ci.appveyor.com/project/simonmichael/hledger/history) re-enabled (& http://appveyor.hledger.org url shortcut added).

**Comment by MatthiasKauer** [comment]
That's awesome. Thank you so much.

**Comment by simonmichael** [comment]
You're welcome. I'll close this, assuming the appveyor builds keep working.
