### ISSUE TITLE
brew recipe still points to old version hledger-0.27.1

### ISSUE THREAD

**Issue by grepinsight** [simonmichael/hledger#426]
Hi. Thank you for making this amazing program. Ever since it was featured on Hacker news, I have been using hledger almost everyday.

I wanted to try out the new version of hledger 1.01 via using brew, but it seems like brew recipe points to the old version, and I currently do not know how those series of hashes are generated on the recipe to request for PR :(
[hledger.rb at Hombrew](https://github.com/Homebrew/homebrew-core/blob/23eecb8b96da1f67d66e4b084eeb2aaae13dff6a/Formula/hledger.rb)

**Comment by simonmichael** [comment]
Hi @grepinsight, thanks for the feedback!

I'm no homebrew expert either, but IIRC you commit the recipe without the hashes and then in a little while a homebrew bot adds them for you.

Would you be willing to take a shot at it ? We do need help maintaining this.

**Comment by grepinsight** [comment]
@simonmichael Turns out the updating the existing formula was relatively simple.
I just made a PR to the homebrew-core! [Homebrew/homebrew-core#6483](https://github.com/Homebrew/homebrew-core/pull/6483)
Hopefully it gets merged soon.

Thank you and I hope to make more contributions.

**Comment by simonmichael** [comment]
Wonderful! Welcome aboard!

Next goal for homebrew is to add hledger-ui/web/api.
