### ISSUE TITLE
balance calculation error / rounding error

### ISSUE THREAD

**Issue by btittelbach** [simonmichael/hledger#435]
I have discovered a weird bug where hledger-lib **calculates** an accounts balance **wrongly**.
It appears to be a rounding error.
Sorry I've not tracked this down in the code in any way yet.

### Tested Softwareversions:
Tested with versions 1.0.1 from cabal and newest version compiled from git (2016-11-22 as of commit 64a877bff09edb755b9c0d0a1cf1c98d14fbdd01) using `./cabal-install.sh`

### Test Data:
```
2016/10/21 Out
    assets:current:cash:onthemove   210.4700 EUR
    assets:current:cash:register        -210.4700 EUR

2016/10/21 Out
    assets:current:cash:onthemove   180.0000 EUR
    assets:current:cash:register        -180.0000 EUR

2016/10/21 In
    assets:current:checking-r3           210.7400 EUR
    assets:current:cash:onthemove  -210.7400 EUR

```

### Reproducing the bug:
```shell
#% hledger -f test3.ledger register assets:current:cash:onthemove
2016/10/21 Out        assets:current:cash:onthemove     210.4700 EUR  210.4700 EUR
2016/10/21 Out        assets:current:cash:onthemove     180.0000 EUR  390.4700 EUR
2016/10/21 In         assets:current:cash:onthemove    -210.7400 EUR  179.7300 EUR

#% hledger -f test3.ledger balance assets:current:cash:onthemove 
        179.7300 EUR  assets:current:cash:onthemove
--------------------
        179.7300 EUR
```

### Expected Output:
Would be a correct account balance of` 180.0000 EUR`

**Comment by simonmichael** [comment]
It looks right to me, is your eye is missing the transposed digits (.74 versus .47) ?

**Comment by btittelbach** [comment]
exactly!

Thank you for debugging our accounting data!!
Now please delete this bug or move it to the psychology example section ;->
I really really did not see the difference between 0.47 and .74 because those values were suppossed.. no KNOWN.. to be the same, so of course my brain read them as being the same. Whoa... what an eye opener.

**Comment by simonmichael** [comment]
Trippy isn't it! Mind over reality! :-)

**Comment by btittelbach** [comment]
indeed indeed :)
