### ISSUE TITLE
Does `instance Monoid Journal` drop too much information?

### ISSUE THREAD

**Issue by johannesgerer** [simonmichael/hledger#436]
Whenever a journal is read with `readJournalFiles` the `mconcat` in `Read.hs:141` will call `mappend _ mempty`, which means that things like `jparsedefaultcommodity` are set to `Nothing`.

One unfortunate consequence is: calling `readJournalFile f` will give a different result from `readJournalFiles [f]`.

Is this intended or would you accept a pull request to change this?

**Comment by simonmichael** [comment]
Thanks for the report. That sounds not ideal, I would gladly receive a pull request.

**Comment by simonmichael** [comment]
I remember the docs say that parse state is reset for each file when reading multiple files, so I'm not absolutely sure it's a bug. Your PR might clarify things.

**Comment by simonmichael** [comment]
Great - thanks!
