### ISSUE TITLE
do not report future postings by default / add --current ?

### ISSUE THREAD

**Issue by schmeisers** [simonmichael/hledger#440]
hledger's date tag and ability to record postings out of chronological order make it convenient to record future transactions for things like amortization and prepaid expenses.  For example, I pay for garbage pickup every six months and record the following on the day that I pay the bill:

~~~
2016-12-07 alternative recycling systems
    assets:prepaid:garbage                              195.00
    liabilities:cc                                     -195.00
    expenses:utilities:garbage                           32.50
    assets:prepaid:garbage                              -32.50
    expenses:utilities:garbage                           32.50 ; date: 2017-01-07
    assets:prepaid:garbage                              -32.50 ; date: 2017-01-07
    expenses:utilities:garbage                           32.50 ; date: 2017-02-07
    assets:prepaid:garbage                              -32.50 ; date: 2017-02-07
    expenses:utilities:garbage                           32.50 ; date: 2017-03-07
    assets:prepaid:garbage                              -32.50 ; date: 2017-03-07
    expenses:utilities:garbage                           32.50 ; date: 2017-04-07
    assets:prepaid:garbage                              -32.50 ; date: 2017-04-07
    expenses:utilities:garbage                           32.50 ; date: 2017-05-07
    assets:prepaid:garbage                              -32.50 ; date: 2017-05-07
~~~

The problem with this system is that the future postings are included in reports unless I include a date filter such as "-e tomorrow" in every report.  I am wondering if it makes sense for hledger to not report future postings unless a future end date is specifically included in a query or a specific option such as "--future" is provided.

Unfortunately this would be a breaking change in the sense that reports would generate different output depending on which version of hledger is used.  But I'd be interested to know if it is common for people to record future postings and want those postings reported by default.

**Comment by simonmichael** [comment]
It's an interesting question. I hear the usability argument. What do Ledger and Beancount do ?

What I have done myself is not include future entries by default. So when I was recording extensive future entries, I kept them in future.journal which includes the default journal, and I have an `alias future="hledger -f future.journal"` for when I want to see those in reports. I haven't done much of that recently, I am just occasionally recording future entries in the default journal and commenting them out until ready for them.

**Comment by schmeisers** [comment]
Ledger shows future entries by default and has a `--current` option to limit to entries `date <= today`.  I've never used beancount and am not sure what the behavior is.

I hadn't realized before looking just now that Ledger's `--current` option is a general option that can appear anywhere on the command line.  If hledger had the same option, it would be easy to `alias l = hledger --current`.  This doesn't work with `-e tomorrow` because date filters cannot appear before commands.  This seems like a better option than changing default behavior.

**Comment by simonmichael** [comment]
So basically we'd like a more convenient way to make the report end date default to tomorrow (end of today). A command line flag that works anywhere in the command line (making it easier to use in an alias) would be one solution. 

It could be a Ledger-style --current flag. Slightly increases our Ledger compatibility, also slightly increases our UI complexity, we would have to figure out how --current interacts with -p/-e/date:/date2:. Or, we could look again at making -e (and perhaps others) work anywhere in the command line. That is really the most desirable situation, but I think it's more work than it seems. Any other ideas ?

**Comment by schmeisers** [comment]
I guess another option would be a tag based way of hiding future entries.  It could be a standalone tag such as `; future:` or an additional date tag like `; fdate: 2020-01-01`.  Tags have the advantage of working in non-CLI UIs.

I'm not familiar with the codebase (still only a few days into "Learn you a Haskell"), but I imagine that tags would be more difficult to implement.  I also like it less from a user's perspective.  An alias friendly CLI option seems like the best for my particular use-case.

**Comment by simonmichael** [comment]
Adding `future:` tags and using `not:tag:future` already works, but it's more effort than just using `-etomorrow` or `not:date:tomorrow-`. (And all of these should work with all the UIs.)

How do you feel about the separate files approach I mentioned ? Also, if you want to explore how --current interacts with -p and -e in Ledger and how it should work in hledger, that would be helpful.

**Comment by schmeisers** [comment]
For the tag solution I was thinking something that would filter a query without an explicit `tag:` option on the command line.  But I think the tag idea is not as nice as a CLI option.

In Ledger, `--current` is a shortcut for `--limit 'date <= today'` and date filters that occur after it take precedence.  For example `ledger --current -f test.ledger print -e 2018` will show entries from 2017.  However, additional `--limit` filters are ANDed together so `ledger --current -f test.ledger print --limit "date > today"` returns nothing.

I'll try the separate file idea.  I'm not a huge fan of needing to move transactions from the future file to the current file as they become current, but I suppose it could be scripted and run with cron.  It would be nice to have a solution that doesn't rely on fragile external logic though.  I'm not familiar with the codebase (or Haskell yet), but I'll start looking and see if a natural solution presents itself.

**Comment by simonmichael** [comment]
More thoughts: in hledger, all queries are like Ledger's `--limit`. Different query flags, and all query arguments, are ANDed. If the same query flag is repeated, all but the last one are ignored. 

Let's assume `-c` is provided as a [general option](http://hledger.org/hledger.html#general-options), and you define `alias l="hledger -c"`. Would you want `-c` to always take precedence (your `l` alias would never be able to show future transactions) ? Or to be overrideable by `-e`, `-p` or `date:` (so you could set a different end date by adding options ?)

**Comment by simonmichael** [comment]
Another option is to use a different alias:
```bash
function hledgercurrent ()
{
    hledger $@ -e tomorrow
}
```
This one is a bit fragile, but effective.

**Comment by schmeisers** [comment]
I think the function will work great for my use-case.  Thanks!

If the general command line option is pursued, I would think that it should be overridable by any of the other date options.

**Comment by simonmichael** [comment]
Closing for now.
