### ISSUE TITLE
print should preserve implicits amounts the way the user wrote them

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#442]
When I `print` a journal file with hledger, then the output gives the amount for both sides of the (trivial) transaction like this:

~~~
2016/12/19 Jasmin
    Ausgaben:Restaurant        EUR 13.00
    Vermögen:Bargeld:Peter    EUR -13.00
~~~

If I `print` that same journal with the C++ `ledger`, however, then it omits the amount from the second part of the transaction and prints just:

~~~
2016/12/19 Jasmin
    Ausgaben:Restaurant                    EUR 13.00
    Vermögen:Bargeld:Peter
~~~

Personally, I feel that the second for is neater because it omits redundant information, so now I wonder whether there's a way to make hledger `print` output in the same way?

**Comment by simonmichael** [comment]
I seem to remember some reason for changing it to the current behaviour - making conversion prices explicit or something ? There's no option to change it at the moment.

**Comment by ony** [comment]
I don't think this is a good behavior. I like ledger because it preserves what user write and allows to get report on it.
This feature results in making transaction written by user with explicit amounts more implicit.
I don't mind if `ledger print` will preserve original content. I.e. if user omits number it also omits it in output.

**Comment by simonmichael** [comment]
This I agree with: we shouldn't remove explicitness that the user may have put there intentionally, eg for error checking and readability.

**Comment by peti** [comment]
There is no one true way for `hledger` to behave in this case, IMHO. As far as I am concerned, the behavior should be configurable. My personal preference is for `hledger` to keep the journal the way I wrote it -- i.e. don't insert or remove any amounts. Others may have other preference (i.e. make all posting amounts explicit).

**Comment by simonmichael** [comment]
Following helpful discussion here and on #465 and #hledger, I think the priorities for print are now:

1. don't remove explicitness the user has added
2. print valid journal format by default, adding whatever explicitness needed to do that easily
3. preserve the user's original implicit/explicit style when it does not conflict with 2

**Comment by simonmichael** [comment]
With #466, 1 and 2 should now be covered, and 3 remains open for PRs and design decisions, like when/whether to activate various modes such as:

- add sufficient explicitness for correct output (current default)
- preserve original implicit/explicit entries as far as possible
- make all entries as implicit as possible
- make all entries as explicit as possible

**Comment by peti** [comment]
`hledger` cannot insert amounts into places where one is required. The posting amount is required because the posting would be ambiguous otherwise (i.e. in the presence of a balance assertion), so by definition `hledger` cannot figure out the proper amount to insert. Am I missing something?

**Comment by simonmichael** [comment]
I haven't thought about balance assertions & assignments  relating to this issue, assuming all that should work normally. Can you give an example of the problem you're seeing ?

**Comment by peti** [comment]
I have a hand-edit ledger file, `foo.ledger`, from which I generate various other ledger files with automatic processes (like `hledger-interest`). Now `main.ledger` includes all of them in the correct order (the generated ones before the manually edited one). Now, `foo.ledger` contains balance assertions for accounts that contain automatically generated transactions (like interest). Thus, whether those assertions hold or fail depends on whether the other generated files are up-to-date or not. If `hledger` were to infer posting amounts such that the assertion holds, then that amount can be false.

I actually ran into this problem before and realized that postings with a  balance assertion must always give the amount, too, to be stable, so for my particular ledger this problem would not occur, but still ... if that issue can arise in principle, then I'm sure someone has thought up an even weirder process that will trigger it, too.

Another open question about balance assertions would be how to deal with them when running as `hledger print -I`? That flag means that trying to infer amounts for balance assertions is off the table, right?

Anyway, IMHO `hledger` should never mess with postings that specify a balance assertion -- `-I` flag or not.

**Comment by ony** [comment]
@peti I can see now what you mean. When I tried to use multiple files with assignment/assertion I've hit a problem with intra-day ordering. But looks like all your assertions/assignments are the last postings of the day.

While `print` doesn't preserve user implicitness you still can solve this problem.
Just keep all of your +assignments+ in a separate hand-edited file.
It should be ok if your get pipeline like ((`foo.ledger` -> post-process) + `foo-assignments.ledger`) -> `ledger-interest` -> `ledge-rewrite` for budgeting.

I agree that `print` should preserve original implicitness by default. If you don't mind I'd like to treat this issue ticket exactly for that. And not like forcing every transaction to have one posting with omitted amount.
Can we change subject to reflect that?

P.S. Note that C++ `ledger` preserves original user input.

**Comment by peti** [comment]
> Just keep all of your assignments in a separate hand-edited file and avoid post-processing it.

I'm not sure whether I follow. What do you mean by "assignments"? 

>  I agree that print should preserve original implicitness by default. Can we change subject to reflect that?

I edited the title to reflect that goal.

**Comment by ony** [comment]
@peti I use next terminology
```
2017/1/1
    Assets:Cash:Wallet  = $20  ; balance assignment: implicit delta with explicit balance
    Equity:Unbalanced  ; implicit amount: implicit delta with implicit/absent balance
    Assets:Bank  0 = $1,000.00  ; balance assertion: explicit delta with explicit balance
    Liabilities  $-5  ; general posting: explicit delta with implicit/absent balance
```
- `Assets:Cash:Wallet` - gets implicit amount calculated from balance difference
- `Equity:Unbalanced` - gets implicit amount calculated from whole transaction balance (to make it balance to zero)
- `Equity:Unbalanced` -- `Assets:Bank` - gets assertion check that can be turned off by `-I`

Thank you for updating subject.

**Comment by simonmichael** [comment]
@peti thanks for the example. I don't see it yet, can you show a reproducible one ?

-I/--ignore-assertions simply means "don't raise an error if you find a false balance assertion", I don't think it changes any other behaviour.

**Comment by ony** [comment]
@peti, you can try [branch feature/442 on my fork](https://github.com/ony/hledger/tree/feature/442). Change in behavior mostly exposed in tests [`tests/print/explicit.test`](https://github.com/ony/hledger/blob/ffd21f9df21f032c5a41ff544e22e2dc1c38b0fe/tests/print/explicit.test)
@simonmichael, I'll try to rebase this off from `--pivot desc` feature (#460).
