### ISSUE TITLE
Why does hledger write "*.rules" files all over the place and how can I disable that?

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#444]
I've recently switched my book-keeping from GnuCash to hledger, which has been an awesome improvement, btw. Kudos for all the great work you've done for plain-text accounting!

One thing that bothers me though is that my project directory is littered with files called, like, `main.ledger.rules` which I did not create -- hledger did. I don't want those files created automatically, and now I wonder what I could do to prevent that from happening?

**Comment by simonmichael** [comment]
Thanks @peti! You're right, that is an annoying thing that happens when the journal parser fails and hledger tries the CSV parser. I believe it's fixed in HEAD.

**Comment by simonmichael** [comment]
At least, it will now happen only for actual CSV files.

**Comment by peti** [comment]
OK, cool. I'll just ignore those files for the time being. Or maybe I'll switch to HEAD even.

**Comment by simonmichael** [comment]
This was fixed by 1.1 I believe.
