### ISSUE TITLE
"hledger balancesheet -h" lists the "--yearly" flag as supported, but it doesn't seem to be

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#445]
`--yearly` has no observable effect on `hledger balancesheet`, apparently because that module cannot generate a multi-column report. Is it wise to list that flag in the help page then?

**Comment by simonmichael** [comment]
At some point I found it easier to reuse this group of options across all commands, accepting that in some cases they might have no effect. About this http://hledger.org/hledger.html#options says "Common reporting options are available with most commands.", which could be clarified. Also this could be made clearer in the CLI help.

In this particular case, I think the right fix is updating balancesheet/incomestatement/cashflow to use the newer multi-column balance report.

**Comment by simonmichael** [comment]
This works now.
