### ISSUE TITLE
Open a project on Gratipay

### ISSUE THREAD

**Issue by mattbk** [simonmichael/hledger#446]
I saw that you have a Gratipay link at http://hledger.org/. Gratipay has changed quite a bit over the last few years and now requires you to create a "project" in order to receive money. It's a simple process at https://gratipay.com/apply.

hledger came up during a [discussion](https://github.com/gratipay/finances/issues/28) about how to organize the books at Gratipay, which led to the website. (I'm part of the Gratipay team.)

**Comment by simonmichael** [comment]
Thanks for the heads-up mattbk. I've opened https://github.com/gratipay/project-review/issues/310.

**Comment by simonmichael** [comment]
hledger added to Gratipay, home page widget updated, announcement sent.
