### ISSUE TITLE
"hledger print" loses all balance assertions

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#447]
I wanted "hledger print"' my journal so that everything is in some sort of canon format, but then I noticed that this process drops all balance assertions! Is that a known issue?

**Comment by simonmichael** [comment]
Yes, it's a missing feature in the print command. I think perhaps it should be optional, because print gets used both for canonicalising a hledger journal, and for exporting to Ledger (where balance assertions work differently).

**Comment by rodlogic** [comment]
I have a very limited experience with hledger, but the main use case I am interested at this point archiving. By this I mean making sure I can archive a range of transactions in a loss-less manner so that this archive transactions becomes a standalone hledger database.

**Comment by simonmichael** [comment]
Related issue: print doesn't always produce a valid journal.

I've seen these use cases for print: 

1. human-readable output for quick cli reporting 
2. non-lossy hledger-readable output for archiving/transforming data
3. sanitised ledger-readable output for data interchange

Perhaps the next step is to make it do 2 by default.
And later, extend the `-O/--output-format` option if needed, 
eg instea of `-O csv|txt` provide `-O csv|hledger|ledger|beancount`.

**Comment by peti** [comment]
IMHO, (2) is by far the most important use-case. If hledger has special support for creating journals that C++ ledger can parse, then I am all for it but I don't need that capability, personally. I *do* need (2), however. As a user of `hledger-lib`, I am rather surprised to find out that all those `pbalanceassertion` attributes I've carefully calculated don't show up anywhere when I print the `Transaction`.

**Comment by peti** [comment]
Duh, I just compiled the current git HEAD of `hledger-lib` so that I can patch printing of balance assertions into it. Now guess what? The code is already there. HEAD *does* print balance assertions.

I suppose this means that I'm hugely in favor of (a) keeping that behavior and (b) releasing a new version of `hledger-lib` that contains this feature.

**Comment by simonmichael** [comment]
Ack! But good! I guess this landed two weeks ago, thanks @johannesgerer.

**Comment by simonmichael** [comment]
PS I will release 1.1 before year end.

**Comment by peti** [comment]
> I will release 1.1 before year end.

OK, very cool. Meanwhile, I've configured my Nix installation to fetch hledger from git rather than Hackage so that I can use the bleeding-edge whenever I feel like it. Maybe I'll get around to contributing a patch or two.
