### ISSUE TITLE
hledger-ui theme(s)

### ISSUE THREAD

**Issue by linuxcaffe** [simonmichael/hledger#448]
Personally, I prefer darker themes. I learned about --theme=terminal, and that's ok, but might be even better (for me) with some colors in the terminal theme. I was thinking something informational defaults like;

assets=green
expenses=red
liabilities=blue
income=yellow
equity=magenta

I guess color defaults/ assignments for bg, header and status lines would be desirable too.

and maybe those could be overridden by user preferences..? in a config? in a theme file?

**Comment by simonmichael** [comment]
Yup, experimentation/screenshots/PRs needed - just tweak https://github.com/simonmichael/hledger/blob/master/hledger-ui/Hledger/UI/Theme.hs#L65 .

**Comment by simonmichael** [comment]
Cf #443.

**Comment by linuxcaffe** [comment]
Very cool, that DOES look themeable! I\m willing to poke at that, but I have a "few" questions;

1. What would the workflow be like, in tweaking a theme? modify Theme.hs and then rebuild with stack?

2. what does "<>" mean, in the context of the theme definition?

3. what themeing "handles are available? I see;
- themeName
- default style for this theme
- error
- border
- border-bold
- border-query
- border depth
- border-keys
- border-mini-buffer
- normal
- list  -- regular list items
- list-selected -- selected list items
- list-selected
- list-accounts
- list-amount-increase
- list amount-decrease
- list-balance-positive
- list-balance-negative
- list-amount-increase-selected
- list-amount-decrease-selected
- list-balance-positive-selected-
- list-balance-negative-selected
- others? 
- any way to reference "account-name-assets" or "account-name-expenses" sort of thing?

**Comment by linuxcaffe** [comment]
4. what "color-spaces" are available? the colors currently referenced could be from a limited palette, 8? 16? 256?

**Comment by simonmichael** [comment]
> What would the workflow be like, in tweaking a theme? modify Theme.hs and then rebuild with stack?
> 
Set up with stack: http://hledger.org/download.html#c <http://hledger.org/download.html#c>

Auto-rebuild on file change: stack install ghcid;  ghcid -c stack ghci hledger-ui

Tweak Theme.hs (in very small steps to avoid errors; study errors carefully until they become easy to avoid)

> what does "<>" mean, in the context of the theme definition?
> 
Generally it means "join two things together" and here it's used to construct increasingly-specific style selectors similar to the ones in CSS, eg list.amount.increase.selected.
> what themeing "handles are available? any way to reference "account-name-assets" or "account-name-expenses" sort of thing?
> 
I think only the ones already used in this file, so we'll probably need to add some, which is a little harder. It means eg inserting `withAttr` calls in the drawing code, like https://github.com/simonmichael/hledger/blob/master/hledger-ui/Hledger/UI/AccountsScreen.hs#L246 <https://github.com/simonmichael/hledger/blob/master/hledger-ui/Hledger/UI/AccountsScreen.hs#L246> .
> what "color-spaces" are available? the colors currently referenced could be from a limited palette, 8? 16? 256?

I think 256, automatically down-sampled to 16 or monochrome if user doesn't have TERM=xterm-256color or some equivalent. See 

https://hackage.haskell.org/package/vty-5.14/docs/Graphics-Vty-Attributes.html <https://hackage.haskell.org/package/vty-5.14/docs/Graphics-Vty-Attributes.html> and 

https://hackage.haskell.org/package/vty-5.14/docs/Graphics-Vty-Attributes.html#t:Color


Good questions for a "how to style hledger-ui" doc!

**Comment by simonmichael** [comment]
Answer updated.

**Comment by simonmichael** [comment]
> What would the workflow be like, in tweaking a theme? modify Theme.hs and then rebuild with stack?

Set up with stack: http://hledger.org/download.html#c

Test compilation on file change: `stack install ghcid;  ghcid -c stack ghci hledger-ui`

Tweak Theme.hs, in very small steps to avoid errors; study error messages carefully until avoiding them becomes easy.

In another window, preview it: `stack build hledger-ui && stack exec hledger-ui`

> what does "<>" mean, in the context of the theme definition?

Generally it means "join two things together" and here it's used to construct increasingly-specific style selectors similar to the ones in CSS, eg like "list.amount.increase.selected".

> what themeing "handles are available? any way to reference "account-name-assets" or "account-name-expenses" sort of thing?

I think only the ones already used in this file, so we'll probably need to add some, which is a little harder. It means eg inserting `withAttr` calls in the drawing code, like https://github.com/simonmichael/hledger/blob/master/hledger-ui/Hledger/UI/AccountsScreen.hs#L246 .

> what "color-spaces" are available? the colors currently referenced could be from a limited palette, 8? 16? 256?

I think 256, automatically down-sampled to 16 or monochrome if user doesn't have TERM=xterm-256color or some equivalent. See 

https://hackage.haskell.org/package/vty-5.14/docs/Graphics-Vty-Attributes.html and 

https://hackage.haskell.org/package/vty-5.14/docs/Graphics-Vty-Attributes.html#t:Color

And I guess you reference them by any of:

- [these 16 names](https://hackage.haskell.org/package/vty-5.14/docs/src/Graphics.Vty.Attributes.html#black)

- `(rgbColor r g b)` where r, g, b are 0-255

- `(Color240 c)` where c is 0-239

Good questions for a "how to style hledger-ui" doc!

**Comment by linuxcaffe** [comment]
> Good questions for a "how to style hledger-ui" doc!

well good answers for a "how to style hledger-ui" question! thanks!

I've got some poking to do!

hey, while you're thinking aboot it, what are the chances, down the road, of linking external theme files? eg.  dark256.theme, that might be used without the rebuilding process?

**Comment by simonmichael** [comment]
Chances are good. A reason to add config file support.

**Comment by jmtd** [comment]
I've just spotted this issue. Is think it is resolved by #2167. Please re-open if you disagree.
