### ISSUE TITLE
hledger ui 'amt:>200' fails unexpectedly

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#457]
~~~
$ hledger ui "amt:>200"
hledger-ui: could not parse as '=', '<', or '>' (optional) followed by a (optionally signed) numeric quantity: 
~~~

I suppose there is some kind of quoting error when `hledger` forwards the command-line to `hledger-ui`?

**Comment by simonmichael** [comment]
Thanks.. yes, it seems so, `hledger-ui  "amt:>200"` works better. Add --debug=2 to see how its parsing. The > is somehow not being escaped.

**Comment by simonmichael** [comment]
See also #458.

**Comment by agander** [comment]
I cant reproduce this. Tried the other operatos as well:

`hledger-ui "amt:>200" --debug=2
trying reader: "journal"
reader result: "Journal /home/gander/.hledger.journal with 5 transactions, 8 `accounts"``


![hledger_repro_457](https://user-images.githubusercontent.com/1449985/35556431-7cffcca2-05a2-11e8-8118-6a7bf3378ef3.png)


where the transactions are:
cat ~/.hledger.journal 
; journal created 2017-10-09 by hledger

2015/5/25 trip to the supermarket
    expenses           $10
    assets          $-10.0

2015/05/26 forgot the bread
    expenses            $5
    assets             $-5


2017/10/23 giffgaff
    assets:bank:checking          €10.00
    expenses:telco               €-10.00

2017/10/23 mina
    assets:bank:checking          €50.00
    expenses:tools               €-50.00

2017/10/23 baavet
    assets:bank:checking         €224.00
    expenses:casa:soft          €-224.00

**Comment by simonmichael** [comment]
The error is when calling hledger-ui via the hledger command, ie `hledger ui ...` not `hledger-ui ...`

**Comment by agander** [comment]
That was for version 1.5 on Linux x86_64

**Comment by agander** [comment]
If I repeat the command with these args:
`hledger ui "'amt:>200'" --debug 4`
it works as expected.
The debug messages now are:
=====
external command selected: "ui"
external command arguments: [ "\"'amt:>200'\"" , "--debug" , "4" ]
running shell command: "hledger-ui \"'amt:>200'\" --debug 4"
=====

whereas on the original run, they are:
`hledger ui "amt:>200" --debug 22`
and
=====
external command selected: "ui"
external command arguments: [ "amt:>200" , "--debug" , "22" ]
running shell command: "hledger-ui amt:>200 --debug 22"
=====
i.e. the shell says "oh no you dont" when it sees unquoted ':>'

Does that suggest that that particular type of arg needs to be double-quoted?
Is that going to be possible to achieve bearing in mind that we dont know where that type of arg will appear.

Or I am barking up my neighbours tree ...
 
(Its strange that the shell drops the  quotes in the original but not the second.)

**Comment by simonmichael** [comment]
Here's a test for the reported issue:
```
#!/usr/bin/env shelltest
# test for https://github.com/simonmichael/hledger/issues/457
# note a shelltest already provides one level of quoting, so amt:>0 not 'amt:>0'
#
$ hledger -f - ui amt:>0
>2 !/could not parse/
>=1
```
