### ISSUE TITLE
journal reader optimization opportunities: followingcommentandtagsp/postingdatesp

### ISSUE THREAD

**Issue by cocreature** [simonmichael/hledger#461]
I did some profiling and found that an unreasonably large amount of time is spent in `followingcommentandtagsp`. In particular the culprit sems to be the parsing of dates, i.e., `postingdatesp`. Removing this brought the total runtime of a balance report on my 6155 line journal from 448ms down to 392ms (more than 10%). I don’t have time to look deeper into this right now but from a quick look it seems like the call to `notFollowedBy` could be really expensive here.

I doubt I’ll have time to rewrite this anytime soon so I’m opening it for someone else to look into.

**Comment by awjchen** [comment]
I've attempted to address this issue in PR #765. I think the issue is resolved for now. Thanks for the report!
