### ISSUE TITLE
Wrong multi-currency printing

### ISSUE THREAD

**Issue by rmoehn** [simonmichael/hledger#465]
I'm not sure if I'm doing the right thing, but I think I've found a problem. I'm trying to use a currency trading account like this:

```
2017-01-07 buy food
    expenses:food   20 usd @ 1.30 cad
    assets:usd     -20 usd
    income:currency
```

`hledger print` yields:

```
2017/01/07 buy food
    expenses:food    20 usd @ 1.30 cad
    assets:usd                 -20 usd
                            -26.00 cad
    income:currency             20 usd
```

Using `hledger print -O csv`, I can understand how this is meant:

```
"txnidx","date","date2","status","code","description","comment","account","amount","commodity","credit","debit","status","posting-comment"
"1","2017/01/07","","","","buy food","","expenses:food","20 @ 1.30 cad","usd","","20 @ 1.30 cad","",""
"1","2017/01/07","","","","buy food","","assets:usd","-20","usd","20","","",""
"1","2017/01/07","","","","buy food","","income:currency","20","usd","","20","",""
"1","2017/01/07","","","","buy food","","income:currency","-26.00","cad","26.00","","",""
```

However, in this case `print` is not idempotent. – `hledger print |
hledger -f- print` yields:

```
2017/01/07 buy food
    expenses:food    20 usd @ 1.30 cad
    assets:usd                 -20 usd
    -26.00 cad              -26.00 cad
    income:currency             20 usd
```

This looks wrong.

**Comment by simonmichael** [comment]
Thanks for the report. Yes, print's output is not always valid journal format, which is a pity. Postings where the amount is implicit can have a multi-commodity amount. To show this in valid journal format would mean showing one posting per commodity, like this:
```journal
2017-01-07 buy food
    expenses:food     20 usd @ 1.30 cad
    assets:usd       -20 usd
    income:currency   20 usd
    income:currency  -20 usd @ 1.30 cad
```

Should the print command do this ? Ie, show a journal entry which is not what you wrote, to get valid journal output ?

Or, it could just leave the amount implicit as it was in the first place ? 
```journal
2017-01-07 buy food
    expenses:food     20 usd @ 1.30 cad
    assets:usd       -20 usd
    income:currency
```
It originally did this, but I had some reason to change it - clarity when troubleshooting ? See also https://github.com/simonmichael/hledger/issues/442 .

**Comment by simonmichael** [comment]
Let's revert to the old behaviour and see what happens. I think this means print will show all entries with no explicit amount on the last posting - whether you wrote one in the journal entry or not. So eg if you did write all amounts explicitly:
```
2017-01-07 buy food
    expenses:food     20 usd @ 1.30 cad
    assets:usd       -20 usd
    income:currency   20 usd
    income:currency  -20 usd @ 1.30 cad
```
print will show
```
2017/01/07 buy food
    expenses:food     20 usd @ 1.30 cad
    assets:usd                  -20 usd
    income:currency              20 usd
    income:currency
```
Maybe this is ok. Maybe we'll need a `--explicit` option later.

**Comment by simonmichael** [comment]
And I shouldn't have pushed that before updating tests. Oh well.

**Comment by simonmichael** [comment]
Also, as @ony pointed out this doesn't fix the problem. Eg we still have:
```
2017-01-07 buy food
    expenses:food   20 usd @ 1.30 cad
    assets:usd     -20 usd
    income:currency
    expenses:fee     3 usd
```
```
$ hledger -f 465.journal print
2017/01/07 buy food
    expenses:food    20 usd @ 1.30 cad
    assets:usd                 -20 usd
                            -26.00 cad
    income:currency             17 usd
    expenses:fee
```
Discussing a bit on IRC.

**Comment by rmoehn** [comment]
Thanks for the quick action!

For my purposes it would be enough if there was a canonical format that I can thread through multiple calls. Like `hledger-rewrite -f … | hledger-rewrite -f- … | hledger-rewrite -f- … | hledger -f- print`. I thought the CSV format would work, but apparently I misunderstood the purpose of CSV reading and writing. It's thought for communicating with outside programs, not for communicating with hledger itself, right?

**Comment by simonmichael** [comment]
Yeah. The CSV output of print has one record per posting, while we expect CSV input to have one record per transaction, so doing that with CSV sounds hard.

**Comment by simonmichael** [comment]
Thanks for the PR! I believe this issue is now resolved in master.

**Comment by rmoehn** [comment]
Thanks! I will try it out soon.

**Comment by ony** [comment]
Though journal now is valid I've got strange output for journal
```
2016/1/1
    saving-card  $-105
    snacks  95 EUR @@ $100
    Equity:Unbalanced  ; absence of $5 here triggers strange behavior
```

```
2016/01/01
    saving-card                 $-105
    snacks             95 EUR @@ $100
    Equity:Unbalanced            $105    ; absence of $5 here triggers strange behavior
    Equity:Unbalanced           $-100    ; absence of $5 here triggers strange behavior
```
I would understand if the output would look like:
```
2016/01/01
    saving-card                           $-105
    snacks                       95 EUR @@ $100
    Equity:Unbalanced                      $105    ; absence of $5 here triggers strange behavior
    Equity:Unbalanced           -95 EUR @@ $100    ; absence of $5 here triggers strange behavior
```

**Comment by simonmichael** [comment]
I see, it looks like the balancing amount inferring function is missing an opportunity to combine same-commodity amounts. It's normal for the inferred balancing amount to be converted to the price's commodity ($) by the way, hledger always does that for similarity with Ledger/convenience reasons I don't fully recall.

**Comment by rmoehn** [comment]
Looks like it works for me now! Thanks!
