### ISSUE TITLE
Upgrade to brick-0.16

### ISSUE THREAD

**Issue by jchia** [simonmichael/hledger#473]
brick-0.16 switches from using `Control.Concurrent.Chan` (unbounded size) to `Brick.BChan` (bounded size). Can we make the necessary changes and switch to brick-0.16? Should compatibility with brick-0.15 be maintained using conditional compilation?

**Comment by simonmichael** [comment]
Hmm, good question. I suppose yes we should add some more CPP for this for now. A few people need this, if you have time a PR is welcome.

**Comment by cocreature** [comment]
> Hmm, good question. I suppose yes we should add some more CPP for this for now.

I’m not sure if that’s worth the effort. Maintaining compatibility with old versions is useful for libraries but much less so for executables (e.g. hlegder-ui) since there is nothing stopping you from building against a newer version in that case.

**Comment by simonmichael** [comment]
Assuming it's easy, we tend to do this in hledger at least temporarily, to maximise the chance of installation just working for all kinds of users, which is a high priority.
