### ISSUE TITLE
balance assertion errors should show a more accurate line number

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#481]
Currently they show the line number where the transaction starts. Better to show the line number of the posting with the failing assertion.

**Comment by jeevcat** [comment]
I was thinking about having a look at this issue as something easy to get me started contributing. However, as far as I can tell, there are currently no line numbers being printed for balance assertion errors?
I'm looking [here](https://github.com/simonmichael/hledger/blob/08acad3f42a78cc84b870d66d23f15473be40e07/hledger-lib/Hledger/Data/Transaction.hs#L393) and at the following strings at 417 and 419.

**Comment by simonmichael** [comment]
Great. That's actually a different error (unbalanced transaction). [Here's](https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Data/Journal.hs#L538) the balance assertion error.

**Comment by simonmichael** [comment]
I notice it says column 0 which looks a little odd, I wonder how hard it would be to show just the line number, or (gold plated version) the actual column of the = sign.

**Comment by jeevcat** [comment]
I have this working now, but it only finds the column using the output of `postingAsLines` or `show transaction`. However, this isn't always the same as what is written in a journal file. 

I can see that I can get the transaction's 1-based position in the input stream from a Transaction. How can I access the current input stream from the `checkBalanceAssertion` function?

**Comment by simonmichael** [comment]
To do it robustly I guess we'd have to save the position of the balance assertion during parsing, similar to Transaction.tsourcepos. Perhaps:

type BalanceAssertion = Maybe (Amount, GenericSourcePos)
data Posting = Posting {... pbalanceassertion :: BalanceAssertion ...}

**Comment by simonmichael** [comment]
PS if you think it's worth the trouble. Or we could just not show a column number.

**Comment by jeevcat** [comment]
Can we go with `type BalanceAssertion = (Maybe Amount, Maybe GenericSourcePos)` instead?

In some places I'm unable to populate the source position easily (like in [Equity.hs](https://github.com/simonmichael/hledger/blob/b7f8ca2cdaa0fb23e419a689788e8ce8a3f11471/hledger/Hledger/Cli/Commands/Equity.hs#L69) and also [CSV parsing](https://github.com/simonmichael/hledger/blob/b7f8ca2cdaa0fb23e419a689788e8ce8a3f11471/hledger-lib/Hledger/Read/CsvReader.hs#L700).

**Comment by simonmichael** [comment]
I was wondering how tsourcepos handles that.. it uses nullsourcepos.
