### ISSUE TITLE
Price precision shouldn't affect rendering of final amounts

### ISSUE THREAD

**Issue by ony** [simonmichael/hledger#489]
I guess prices still somehow affect the output:
```sh
% hledger bal -f -
commodity 1,000.00 UAH

2017/1/1
	Expenses  20 UAH
	Assets

2017/1/2
	Income  $-100 @ 26.0988 UAH
	Assets
	
2017/1/3
	Expenses  1000 UAH
	Assets
```
Produce
```
	Expenses  1000 UAH
	Assets
       1589.8800 UAH  Assets
        1,020.00 UAH  Expenses
               $-100  Income
--------------------
               $-100
      2,609.8800 UAH
```
Seeing numbers for same currency in a different format makes it even worse.
According to comments in #23 `hledger` should ignore prices. But looks like calculated amount doesn't use proper styling and results in a different formatting.

**Comment by simonmichael** [comment]
I haven't investigated the above, but I wonder if it's related to #295. I added commodity (-> format) directive as the solution for situations like this. The docs should be more accurate than #23.

**Comment by ony** [comment]
@simonmichael, I don't think it is related with #295. It looks like when implicit amount being calculated it inherits the most precise style for decimals. Yet another example:

```ledger
% hledger -f - reg
2017/1/1 payout
  a  1.00 USD @ 29.2331 UAH
  b

2017/1/2 balance report
  b  = 29.23 UAH
```
Results in
```
hledger: could not balance this transaction (real postings are off by 58.4631 UAH)
2017/01/02 balance report
    b   58.4631 UAH = 29.23 UAH
```

**Comment by Xitian9** [comment]
I'm not seeing this issue in master. Has it been resolved?

**Comment by simonmichael** [comment]
Yes, it seems so, thanks.
