### ISSUE TITLE
failed to discover how to specify location of journal file

### ISSUE THREAD

**Issue by silvernode** [simonmichael/hledger#497]
It would be nice if I could do something such as:  

```  
hledger -j ~/gitserver/journals/journal-1.journal  
```  

If this is already possible, I haven't been able to figure it out using all the help resources presented. 
Thanks for your consideration :)

**Comment by simonmichael** [comment]
I believe you're looking for -f/--file, right ?

I appreciate this kind of report. What did you try / what path have you taken through the help resources so far ? From my point of view, the canonical doc on this would be http://hledger.org/hledger.html#input-files . It also appears in the SYNOPSIS, DESCRIPTION, and General Options on that page. It's in the short (`-h`) and long (`--help`) help for most hledger commands, but it's not in the short help for hledger itself (`hledger -h`).

**Comment by silvernode** [comment]
Running: hledger 1.1.98 from git  

I didn't extensively read the man pages I'll admit as the "Step by step tutorial" on the main website was mostly enough for what I needed. I was able to find other things via google from the man pages and docs as needed such as how to create a starting balance.  

With all that in mind I couldn't seem to find the -f option. I'll be honest though, I didn't look in the man pages for -f but I did attempt to google for the wrong things like "hledger config file " and "specify journal file hledger". 

Then I typed -h again because these days if a program can take a file input from a custom location I'm used to that option ALWAYS being the -h and --help (which usually do the same thing). In the end I decided to create a soft link from my git folder (original file) to ~/.hledger.journal. This seems to be working out pretty well actually.  

I probably should have looked a bit harder for the option however It would be very pleasant to see "-f" show up in the "-h" output. 

P.S Why is --help different than -h? Also, why aren't man pages installed to the system via stack? Are man pages installed to system directories if using a proper package?  

Please keep up the fantastic work! I tried out ledger a few years ago and decided I wanted something a little more automated and hledger lets me add interactively just the way I want. Maybe one day I can create my budget with it. :)

Cheers!

**Comment by ony** [comment]
@silvernode, man pages should be installed into folders that `man` tool looks for as I know. I don't think that cross-platform tool `stack` supports that specific of Unix systems.

I agree that option `--help` is almost useless on Unix. It would be better to return the same thing that `-h` returns. People who want to read that output may use `--man`. But I guess that's because I didn't try `hledger` on other platforms where `man` and `info` tools are absent.

P.S. I also use a symlink to the main file with a lot of includes that reside in git workspace.

**Comment by silvernode** [comment]
@ony I still can't believe I couldn't find -f. It was in --help all along and not that deep into it. Although I suppose this comes back to the -h vs --help conversation. I didn't bother trying --help because I assumed I was already looking at it with -h.

**Comment by ony** [comment]
@silvernode, `hledger reg -h` mentions that option in `General flags:` section also. Maybe you expected to see it in output of `hledger -h`?

**Comment by silvernode** [comment]
Yes I think it's something that makes sense in hledger -h unless of course
"hledger -f FILE doesn't work.

**Comment by simonmichael** [comment]
@silvernode great feedback, thanks.

It's literally in every -h and --help output, except for `hledger -h`, I believe.

Having -h and --help is a little unusual in unix land but git does it that way and I decided it was useful enough to copy their approach.

**Comment by simonmichael** [comment]
Concrete alternate designs welcome. 
We can show or advertise more flags in `hledger -h` (how ? it's already over-long). 
We could make --help the same as -h (short help, should fit on a screen), requiring --man or --info to see long help (these may not always work; what flag would you use to show long help as plain text ?).
Short help itself is still somewhat in flux. The common hledger flags including -f don't fit on a screen, so the bundled addons no longer show them with -h, only with --help. They do have a line suggesting --help to see more flags though.

Glad you're enjoying hledger @silvernode.

**Comment by silvernode** [comment]
@simonmichael Ah yes git does do this and I think it was a logical decision to structure hledger this way. I think I would be useful to mention something about it in the "step by step tutorial" in the future as I think that's where most people probably go when viewing the Docs page. I would also include there that input files exist as functionality as well as the ability to create a starting balance. I had a hell of a time trying to figure out how to make a starting balance but eventually found it somewhere in the docs via Google.  

We should probably re-think the step-by-step tutorial and include these things and more.

**Comment by simonmichael** [comment]
An update to the tutorial (or an alternate tutorial) would be very welcome, I haven't tested/updated it for quite a while.

We have always needed more practical how-to docs, beyond "how do I install/run/format". The new user cookbook at http://hledger.org/docs.html is another place for those.

**Comment by silvernode** [comment]
@simonmichael hledger -h doesn't have to be terribly long, it just needs to include a few more vital flags like "-f" and maybe another few. For long help, the existing "man" command works fine. As long as essential core flags for operating hledger are in -h, people will feel at home just like any usual CLI application. When -f wasn't in there for example, I just assumed the program couldn't let me specify a journal file because that would have been there if it could (or so I thought). Thus I promptly went for the soft link. Glad I knew how to make soft links in Linux :)

**Comment by simonmichael** [comment]
It is long. 53 lines here (35 if I had no addons installed).

We'll improve it, mockups welcome..

**Comment by simonmichael** [comment]
Could list just command names, several per line, as git does, I guess.

**Comment by silvernode** [comment]
@simonmichael I have seen much longer, MUCH longer but I share your goal of short and simple design. I'll see what I can come up with when I have some time (which is hard to come by) and get back to you.

**Comment by simonmichael** [comment]
As `git help -a` does, I mean. `git` output is actually like `hledger`, but they do a better job of showing basic flags up at the top.

**Comment by simonmichael** [comment]
Related: https://github.com/simonmichael/hledger/issues/297

**Comment by silvernode** [comment]
@simonmichael I have now posted in #297

**Comment by simonmichael** [comment]
Probably resolved, closing.
