### ISSUE TITLE
Accounts with '?' confound web/ui registers

### ISSUE THREAD

**Issue by chreekat** [simonmichael/hledger#498]
Accounts with question marks show up in balances, but their transactions are not listed in `hledger ui -- --register` nor `hledger web`.

    1/1
        First?  $1
        Second

    1/2
        Second  $1
        Third

    1/3
        Third  $2
        First?

![anim](https://cloud.githubusercontent.com/assets/538538/22399159/f43b6452-e54b-11e6-8288-e63d15c97d52.gif)

I suspect the problem is the question mark is not escaped in `accountNameToAccountRegex`, but I'm still compiling the universe and haven't tried it out yet. Also not sure what your preferred solution would be in this case.

(I just noticed this while working on cleaning up some imported data... I don't intend to keep the question marks for long.)

**Comment by chreekat** [comment]
Yeah, this "fixed" it:

    diff --git a/hledger-lib/Hledger/Data/AccountName.hs b/hledger-lib/Hledger/Data/AccountName.hs
    index d70fb50..42a4975 100644
    --- a/hledger-lib/Hledger/Data/AccountName.hs
    +++ b/hledger-lib/Hledger/Data/AccountName.hs
    @@ -152,7 +152,10 @@ clipOrEllipsifyAccountName n = accountNameFromComponents . take n . accountNameC
     -- | Convert an account name to a regular expression matching it and its subaccounts.
     accountNameToAccountRegex :: AccountName -> Regexp
     accountNameToAccountRegex "" = ""
    -accountNameToAccountRegex a = printf "^%s(:|$)" (T.unpack a)
    +accountNameToAccountRegex a =
    +    printf "^%s(:|$)"
    +    $ regexReplaceBy "\\?" ("\\" <>)
    +    $ (T.unpack a)
     
     -- | Convert an account name to a regular expression matching it but not its subaccounts.
     accountNameToAccountOnlyRegex :: AccountName -> Regexp

**Comment by simonmichael** [comment]
Nice catch! I would welcome a PR.

**Comment by simonmichael** [comment]
PS I wonder if there's a more robust function in regex-tdfa, which powers our regexps.

**Comment by chreekat** [comment]
My thought exactly. :) I can wing a fix, but I'd be worried about missing corner cases. I looked briefly and didn't see anything good. PR incoming.

**Comment by ony** [comment]
@simonmichael, wouldn't it be easier to use alternative ways for match? I.e.
```haskell
data MatchTarget = TargetRegex Regex
                 | TargetCaseInsensitive String
                 | TargetExact String
```

Ideally regexp library should allow building `Regex`. There is [`Pattern`](https://hackage.haskell.org/package/regex-tdfa-1.2.2/docs/Text-Regex-TDFA-Pattern.html#t:Pattern) and corresponding [`patternToRegex`](https://hackage.haskell.org/package/regex-tdfa-1.2.2/docs/Text-Regex-TDFA-TDFA.html#v:patternToRegex)  but it isn't much different from building string for parser.

**Comment by simonmichael** [comment]
I don't know, probably more principled but is it worth the added complexity ? We are using regexps everywhere so I don't mind leaning on them. Alternate PR welcome.
