### ISSUE TITLE
Chart of Accounts support

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#50]
_Original author: davamu...@gmail.com (June 09, 2011 17:01:32)_

hledger can list all of the accounts you use, but is that a Chart of Accounts ?
not necessarily
An actual CoA would include every account that is relevant to you, whether or not you have any entries corresponding to each account. It should also be able to contain all desired details for each account; account number, bank branch addresses, terms, rates, paper-file cross reference, tax GIFI numbers, what have you. These details should not live in specific transactions, but they should be available wherever you need them; as reference to your chosen account structure and to enhance account-specific reports. 

A Chart of Accounts should take the form of a valid (h)ledger transaction, with zero values. This could also be a logical place to put account starting values. 

Hledger could be induced to generate an initial chart of accounts, with a new command --coa, using all active accounts. This could be sent to a file, could be edited, extended and enhanced with details, and then could be included in an active ledger file, and would then be available to enable tab-completion, and to define allowable accounts when no new ones can be created. 

_Original issue: http://code.google.com/p/hledger/issues/detail?id=50_
##

**Comment by simonmichael** [comment]
See also https://github.com/simonmichael/hledger/issues/523#issuecomment-288658996

**Comment by simonmichael** [comment]
From #523:
```
# accounts directive, optional multi-line form.
# Defines account tree, or at least the roots.
# First five root accounts are ALQRE.
# Aside from that, order of names influences default account ordering in reports.
# Comments and tags allowed. Tags propagate to subaccounts.
accounts  ; undeclared-subs:no, special tag disallowing subaccounts not declared here
 assets      ; this and subaccounts are assets. They get an implicit type:A tag.
  bank       ; phone:111-111-1111, url:http://blahblah
   checking
     ; acctno:12345
     ; routingno:123127745
   saving
  cash
 liabilities
  debts
 equity
 revenues
  salary
 expenses  ; undeclared-subs:yes, allow non-pre-declared accounts under expenses
  food
  home
 special assets
  book tokens
  prepaid classes
```

**Comment by linuxcaffe** [comment]
Looks brilliant Simon, thanks

**Comment by simonmichael** [comment]
Closing this to continue on #217.

**Comment by tonyxiao** [comment]
This would be amazing!!

**Comment by simonmichael** [comment]
Latest: #877
