### ISSUE TITLE
megaparsec-5.2.0

### ISSUE THREAD

**Issue by sjakobi** [simonmichael/hledger#503]
I noticed https://github.com/fpco/stackage/issues/2259 and did a successfull `stack test --fast` with relaxed bounds and an additional `extra-dep` of `megaparsec-5.2.0`.

I don't know whether you'd like to release the new bounds as Hackage revisions, tiny maintenance releases or in combination with other changes, so I haven't filed a PR. I thought I'd let you know anyway.

**Comment by simonmichael** [comment]
Nice! Thanks for the testing. I use hackage revisions for this when possible - it sounds like that will work for this, so I'll do that shortly.

**Comment by simonmichael** [comment]
Done.

**Comment by sjakobi** [comment]
Cheers!
