### ISSUE TITLE
Remove and .gitignore the .cabal files

### ISSUE THREAD

**Issue by sjakobi** [simonmichael/hledger#504]
When I did https://github.com/simonmichael/hledger/issues/503 I of course first edited the .cabal files directly and wondered why stack didn't seem to pick up my changes!

I think the .cabal files should be regarded as a build product and therefore not included in version control.

**Comment by simonmichael** [comment]
They are redundant for stack users, but I think we need to keep them around as not everyone uses stack.

**Comment by sjakobi** [comment]
And asking cabal users to install hpack is too much?! You might be right though…

**Comment by simonmichael** [comment]
For the moment, yes I think it is. Haskellers can get a bit grumpy about tools and we want to just work for as many as possible.

**Comment by sjakobi** [comment]
> Haskellers can get a bit grumpy about tools and we want to just work for as many as possible.

Good point!
