### ISSUE TITLE
"Invalid package ID: .." when trying `stack install`

### ISSUE THREAD

**Issue by misev** [simonmichael/hledger#513]
On Ubuntu 16.04 I have this problem:
```
$ stack install --resolver=nightly hledger hledger-ui hledger-web
Run from outside a project, using implicit global project config
Using resolver: nightly specified on command line
Selected resolver: nightly-2017-03-08
Invalid package ID: "array-0.5.1.1 base-4.9.1.0 binary-0.8.3.0 bytestring-0.10.8.1"
```
Cloning the git repo and trying `stack install` in it gives the same result.

**Comment by simonmichael** [comment]
Hi there.. I searched for your error message and found [this](http://stackoverflow.com/questions/42269549/weird-error-with-haskell-stack-it-doesnt-install-anything-anymore) and [this](http://stackoverflow.com/questions/42269549/weird-error-with-haskell-stack-it-doesnt-install-anything-anymore). What's your `stack --version` ?

**Comment by misev** [comment]
Didn't think to search the error beforehand.. :) I guess it's some issue with this stack version indeed
```
$ stack --version
Version 0.1.10.0 x86_64
```

**Comment by simonmichael** [comment]
Assumed resolved, closing.

**Comment by gdennie** [comment]
Isn't the purpose of Haskell's Stack suppose to prevent invalid package errors?

**Comment by simonmichael** [comment]
It does its best, but it's a pretty hard job. For best results you want the latest stack, and definitely not a two year old version.
