### ISSUE TITLE
incomestatement and cashflow reports incorrectly include historical amounts

### ISSUE THREAD

**Issue by joshkehn** [simonmichael/hledger#514]
Pull #506 appears to have caused a regression when rendering `is` and `cf` reports as they now include historical amounts outside of the reporting period.

***

From [mailing list thread](https://groups.google.com/forum/#!topic/hledger/34ZRe4j5xUM). 

Given a ledger [is.txt](https://github.com/simonmichael/hledger/files/845754/is.txt) and version `1.1.98` of hledger (built from 7b4e11ba), the `is` and `cf` reports incorrectly include historical data outside of the reporting period. This bug is not present on version `1.1` of hledger (from homebrew).

Balance correctly calculates for each year:

```
: hledger -f is.l bal -e 2017 -Y -T -N
Balance changes in 2015/01/01-2016/12/31:


                   ||        2015    2016       Total
===================++=================================
 assets:checking   ||  $10,000.00 $-40.00   $9,960.00
 expense:hosting   ||           0  $50.00      $50.00
 revenue:clients:A || $-10,000.00       0 $-10,000.00
 revenue:clients:B ||           0 $-10.00     $-10.00
```

`incomestatement` is incorrect:

```
: hledger -f is.l is -b 2016 -e 2017
Income Statement


Revenues:
         $-10,010.00  revenue:clients
         $-10,000.00    A
             $-10.00    B
--------------------
         $-10,010.00


Expenses:
              $50.00  expense:hosting
--------------------
              $50.00


Total:
--------------------
          $-9,960.00
```

**Comment by simonmichael** [comment]
That's not good! Great catch! @mstksg would you be able to take a look ?

**Comment by mstksg** [comment]
I'll take a look!  I wonder if the bug exists in balancesheet too, and if it was a problem in my initial generalization process or a problem in applying the abstraction to each individual command.

**Comment by joshkehn** [comment]
@mstksg That's a good question. Since `balancesheet` is a historical point-in-time report I don't think this affects it.

**Comment by mstksg** [comment]
Ah I see.  Should the behavior for bs, is, and cf be different then in regards to usage with -b, -e ?

**Comment by simonmichael** [comment]
> Ah I see. Should the behavior for bs, is, and cf be different then in regards to usage with -b, -e ?

I think so. incomestatement and cashflow are period reports, but balancesheet is a snapshot report and should probably ignore a start date (like balance --historical).

**Comment by joshkehn** [comment]
> Ah I see. Should the behavior for bs, is, and cf be different then in regards to usage with -b, -e?

Any period report should respect `-b` and `-e` (as well as multi-period output, total, cumulative). Point-in-time report should ignore `-b` or preferably raise an `Unknown flag`.

**Comment by simonmichael** [comment]
Would someone like to update `tests/*/{balancesheet,cashflow,incomestatement}.test` to test this issue ?

**Comment by joshkehn** [comment]
I have a test for incomestatement and would be happy to add a test for the other reports.

**Comment by simonmichael** [comment]
Great!

**Comment by joshkehn** [comment]
@simonmichael Opened a PR. It passes the old version of heldger.

**Comment by joshkehn** [comment]
Noticed #514 was merged, rebased and updated that PR.
