### ISSUE TITLE
Does hledger-lib contain functions to print/format monetary values in accordance with the rules of the locale?

### ISSUE THREAD

**Issue by sras** [simonmichael/hledger#517]

**Comment by simonmichael** [comment]
It does not.

**Comment by simonmichael** [comment]
@sras, should it ? If so, feel free to come up with a use case/specification/proposal.

**Comment by sras** [comment]
@simonmichael 

I guess it is up to you. But being an accounting package with command line and web interfaces, I expected this functionality to be part of Hledger, and in turn exported by hledger-lib.
