### ISSUE TITLE
Add an option to use unicode in tables

### ISSUE THREAD

**Issue by cocreature** [simonmichael/hledger#522]
Unicode has a bunch of [box drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) which enable relatively pretty tables even in terminals. It would be nice if `hledger` provided an option to make use of those instead of the pure ASCII tables since I personally find them easier to read.

I’ll probably give this a shot myself but I’m not sure when I’ll get to that so if someone else wants to pick this up be my guest.

**Comment by simonmichael** [comment]
Good idea. Here are some relevant table-drawing libs:

- [tabular](http://hackage.haskell.org/package/tabular) - renders ascii/html/latex/csv. What we currently use.
- [table-layout](http://hackage.haskell.org/package/table-layout) - renders unicode/borderless. Supports multiline cell content and alternating styles.
- [colonnade](http://hackage.haskell.org/package/colonnade) - renders ascii/html/ui widgets.

Ideally, we will generate many of the above formats and also various markdown/org/emacs table formats. I suppose we could use more than one of these libs.
