### ISSUE TITLE
allow flexible naming of main account types

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#523]
High-level commands like balancesheet/incomestatement/cashflow, and more parts of hledger in future, need to know which accounts are assets, liabilities, equity, revenues, and expenses. Until now this has been done with hard-coded anglo-centric account name patterns. We need to support names in other languages.

The current plan is to write [account directives](http://hledger.org/manual.html#account-directive) for the top-level accounts and define the account type there. Eg:
```
account aktivum
  type: A

account forpliktelse 
  type: L

account aksje
  type: Q

account omsetning 
  type: R

account utgift
  type: E
```

Ie an account tag named `type`, which would also apply to subaccounts.

Can we foresee any usability issues ? Any other ideas ?

Related: 
[support the account directive & account metadata #217](https://github.com/simonmichael/hledger/issues/217)

**Comment by simonmichael** [comment]
Related: #217.

**Comment by simonmichael** [comment]
Alternatives & older mockups:
```
# using a keyword/subdirective rather than a specially-named tag:
account aktivum
  asset          # assets and its subaccounts are asset accounts (by default ? need to override for "contra" accounts ?)

account forpliktelse
  liability      # this and subs are liability accounts

account aksje
  equity

account omsetning
  revenue

account utgift
  expense

account annen   # a special account, not one of the standard types

# a single directive listing the five top-level account names in ALQRE order. Account names may not contain comma.
account-types aktivum, forpliktelse, aksje, omsetning, utgift

# six top-level account names, separated by double space. The first five are the A/L/Q/R/E accounts.
account-roots  assets  liabilities  equity  revenues  expenses  special assets
```

**Comment by simonmichael** [comment]
```
# accounts directive, one-line form. Defines top-level accounts & types.
accounts assets, liabilities, equity, revenues, expenses, special assets
accounts  assets  liabilities  equity  revenues  expenses  special assets

# accounts directive, optional multi-line form.
# Defines account tree, or at least the roots.
# First five root accounts are ALQRE.
# Otherwise, order of names might influence default account ordering in reports.
# Comments and tags allowed.
accounts
 assets      ; this and subaccounts are assets
  bank       ; phone:111-111-1111, url:http://blahblah
   checking
     ; acctno:12345
     ; routingno:123127745
   saving
  cash
 liabilities
  debts
 equity
 revenues
  salary
 expenses
  food
  home
 special assets
  book tokens
  prepaid classes

```

**Comment by simonmichael** [comment]
<b>A funding goal of $1,000 has been set for this issue.</b>
Donate via CodeFund.io to support this developer and solve this issue.
<a href='https://www.codefund.io/view.php?id=5'><img src='http://www.codefund.io/img/percent/0-percent-funded.png'></a>
<a href='https://www.codefund.io/view.php?id=5'><b>Make a Donation!</b></a>
<i>Why donate? Learn more at <a href='https://www.codefund.io/support-open-source.php'>www.codefund.io/support-open-source.php</a></i>

**Comment by simonmichael** [comment]
Moving the multi-line accounts directive to #50. For the current issue, a simpler solution will be implemented.

**Comment by nniro** [comment]
Technically, the main account types are only used/mandatory when generating reports and currently, it is possible to use aliases to rename an account to be part of one of these main account types.

How about using the same technique but aliases that are strictly to be used for reports. There are 5 main account types and we could have the same amount to set each alias.

[In a journal file, current alias format is]
alias oldAcctName/Query = newAcctName/Query

[this is what I propose]
alias-asset oldAcctName/Query       ; We wouldn't need to set the second part as in alias.
alias-liabilities oldAcctName/Query  ; The query will need to support multiple entries and convert each.
etc.

We could even use a similar technique to set the output name of the main account types.

**Comment by cwarden** [comment]
#584 raises the issue of needing to exclude some asset accounts from the cashflow report.

Perhaps we should tackle this from the report side rather than from the account side by making the default queries for each report to be configurable, e.g
```
cashflow ^assets not:receivable
balancesheet-assets ^assets
balancesheet-liabilities ^liabilities
balancesheet-equity ^equity
incomestatement-revenue ^income
incomestatement-expenses ^expenses
```

**Comment by simonmichael** [comment]
Yes, I wrongly conflated separate issues. This one (#523) is about identifying the top level account types. Choosing accounts and subaccounts to include/exclude for cashflow and other reports is a separate issue, but related.

**Comment by cwarden** [comment]
What do you have in mind with respect to "more parts of hledger in future need[ing] to know which accounts are assets, liabilities, equity, revenues, and expenses"?

[Quasar Accounting](http://www.linuxcanada.com/) has the concept of Account Categories, which are a bit different from the ALQRE types you've defined.  The Categories are `Asset`, `Liability`, `Equity`, and `Income Statement`.  Here's a sample list of Accounts with Categories:
```
Name                            Parent Name                     Category
------------------------------  ------------------------------  ------------------------------
ASSETS                                                          Asset
Current Assets                  ASSETS                          Asset
Fixed Asset                     ASSETS                          Asset
Accounts Receivable             Current Assets                  Asset
Bank                            Current Assets                  Asset
Inventory                       Current Assets                  Asset
Other Current Asset             Current Assets                  Asset
EQUITY                                                          Equity
Cost of Goods Sold                                              Income Stmt
Expense                                                         Income Stmt
Income                                                          Income Stmt
Other Expense                                                   Income Stmt
Other Income                                                    Income Stmt
Professional Fees               Expense                         Income Stmt
Repairs and Maintenance         Expense                         Income Stmt
Staff Expenses                  Expense                         Income Stmt
Utilities                       Expense                         Income Stmt
Vehicle Expense                 Expense                         Income Stmt
Sales                           Income                          Income Stmt
LIABILITIES                                                     Liability
Accounts Payable                Current Liabilities             Liability
Credit Card                     Current Liabilities             Liability
Other Current Liability         Current Liabilities             Liability
Current Liabilities             LIABILITIES                     Liability
Long Term Liability             LIABILITIES                     Liability
GST Payable                     Other Current Liability         Liability
PST Payable                     Other Current Liability         Liability
```

Quickbooks Online has [Account Types and Detail Types](http://km-ext.ebs-dam.intuit.com/content/dam/km/external/qbolegacy/external2/CoA_Types__Detail_Types.xlsx), where Detail Type is also used as the default Account Name for new Accounts of the Detail Type.  The Types are:
```
Type
------------------------------
Accounts payable (A/P)
Accounts receivable (A/R)
Bank
Cost of Goods Sold
Credit Card
Equity
Expenses
Fixed Assets
Income
Long Term Liabilities
Other Assets
Other Current Assets
Other Current Liabilities
Other Expense
Other Income
```

**Comment by mstksg** [comment]
how married are we to having this be configured in the .journal file?  since it's basically a configuration of the command line interface (and not an actual journal property), would it be too bad to have it be loaded from a dotfile in the home directory?

**Comment by simonmichael** [comment]
I don't think it belongs on the command line. You're very unlikely to want to change it, for a given journal. And it's not necessarily going to be the same for all journals you work with. I think the journal is just the right scope for it.

**Comment by simonmichael** [comment]
@cwarden useful to see how others do it and what conventional account names are. They seem like variations of the same basic structure. You could mimic them using account aliases.

**Comment by cwarden** [comment]
Keeping the configuration in the journal seems ok to me since you can include it from a dotfile if that makes more sense in your environment.

**Comment by simonmichael** [comment]
Yes, actually the default journal path is $HOME/.hledger.journal which is kind of a dotfile already (except it's ignored if you specify the path with LEDGER_FILE or -f).

**Comment by varac** [comment]
would love to have this!

**Comment by snowcastle** [comment]
This is the only feature I really miss in hledger at the moment.

**Comment by simonmichael** [comment]
My current ideas:
```
account NAME  [TYPE] [CODE]
```
1. CODE is a numeric account code, currently just used for sorting. Additionally, when present on top level accounts, the first digit could determine their type - 1 for assets, 2 for liabilities, etc., following some popular real world coding system. 

We already have the syntax for 1, but making it significant for account types brings some complexity to do with inconsistent numbering IIRC. Maybe having it affect only top level accounts resolves that. Oh the issue is what if the numbers don’t reflect the same hierarchy as the account names - keeping that in sync will be busywork/error prone. A problem in practice ?

2. TYPE would be one of the letters ALEIX (assets, liabilities etc). Valid or effective only on top level accounts, probably. Could be instead of 1, or an override for it if you need to use a different numbering scheme for some reason. Maybe unnecessary ?

**Comment by simonmichael** [comment]
#877 is the latest design for this, and will be merged soon if there are no further comments. Still to be decided: whether to allow only single-letter ALERX codes or also allow full english ASSET,LIABILITY,EQUITY,REVENUE,EXPENSE words.
