### ISSUE TITLE
Negating amount breaks parser for negative amounts

### ISSUE THREAD

**Issue by joshkehn** [simonmichael/hledger#524]
### Reproducing

Specific trace:

```
hledger: error: could not parse "$--5000.00" as an amount
the CSV record is:       "2017/01/04", "Merchant Credit", "-5000.00"
the amount rule is:      -%payment
the currency rule is:    $
the default-currency is: unspecified
the parse error is:      ParseError {errorPos = SourcePos {sourceName = "", sourceLine = Pos 1, sourceColumn = Pos 3} :| [], errorUnexpected = fromList [Tokens ('-' :| "")], errorExpected = fromList [Tokens (',' :| ""),Tokens ('.' :| ""),Label ('d' :| "igit")], errorCustom = fromList []}
you may need to change your amount or currency rules, or change your skip rule
```

Attached the rules [bank.csv.rules.txt](https://github.com/simonmichael/hledger/files/867967/bank.csv.rules.txt) and the CSV [bank.csv.txt](https://github.com/simonmichael/hledger/files/867968/bank.csv.txt) which cause this.

### Why this matters

First, it's in an example [rules](https://github.com/simonmichael/hledger/blob/master/examples/csv-rules/amazon.csv.rules#L22). 

Second, currently American Express outputs amounts as “inflow” (positive) amounts in—some—CSV exports. It's a liability account, it has a credit balance, these are credits to the liability and a debit to the expense account. 

A possible user solution is to flip `account1` and `account2` and let some other logic in hledger figure out the balance to credit the liability. This means a common set of rules can't be used since another CSV might have “outflow” (negative) amounts. In that case, `account1` and `account2` for common rules would be reversed.

**Comment by simonmichael** [comment]
You're right, we don't parse a double minus sign. The CSV reader also recognises parentheses as negative, so it's better to use those for sign-flipping: `amount (%payment)`. I see several instances of `-%` in  examples/csv-rules/*.

I suppose it's a good idea to change the amount parser in JournalReader.hs to allow a double minus sign. Would you be willing to give that a try ? Support available in #hledger if you need.

**Comment by simonmichael** [comment]
So these would be equivalent to `$1`: `--$1`, `$--1`, and `-$-1` too ? On second thought, this is strange syntax that might be better confined to the CSV reader only.

**Comment by simonmichael** [comment]
https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Read/CsvReader.hs#L642

**Comment by joshkehn** [comment]
@simonmichael Yes, idea would be `--$1 == $1 == -$-1`. However, I find `--$1` to be a bit confusing. I much prefer the `amount (%payment)` idea as explicit negation. 

That said, I did take a look at the CSV parsing code in the area you indicated. It seems like the possible solution would be to expand `negateIfParenthesised` and negate the amount if it starts with a `-`. This would mean `negateStr` needs to understand `-<currency?>-<amount>` is `<currency?><amount>`.
