### ISSUE TITLE
"hledger --help" doesn't help :)

### ISSUE THREAD

**Issue by chreekat** [simonmichael/hledger#526]
I believe having it be a synonym for "-h", or even *replacing* -h, would bring hledger more in line with UNIXy tools.

It is surprising to me that -h and --help have different behavior, and dumping a man page as text can hardly serve anyone very well, can it? :)

This is a minor suggestion on what is really a fun and useful tool. I'll leave it to your discretion to decide if this issue really matters. Thanks!

**Comment by simonmichael** [comment]
The present situation was a response to #297.

**Comment by chreekat** [comment]
Indeed, I'll close this as a dupe of #297.
