### ISSUE TITLE
hledger-budget help cleanups needed

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#530]
bin/hledger-budget.hs's reuse of mainmode means that `hledger-budget -h` gives almost the same usage text as hledger, which is confusing. Instead, it should show its own help (currently just a comment).  Cc-ing @ony.

**Comment by ony** [comment]
I suspect 7cb7554 "re-factor to use `hledgerCommandMode`" already drops reference to `mainmode`.
It still reports its subcommands that matches with subset of main commands. But that's the whole idea. You still can use multiple approaches while getting same reports with slight effects:
- Automatically injected transactions to set-up per-period budgets refills or write them manually.
- Automatically added budget postings (`rewrite` effect) to real transaction for mirroring them in budget (separate space of accounts) or have them already there while you type in your transactions.
- Fold sub-accounts based on accounts specified in periodic transactions.
