### ISSUE TITLE
"unable to decommit memory: Invalid argument"

### ISSUE THREAD

**Issue by cwarden** [simonmichael/hledger#541]
I'm getting an error, unable to decommit memory: Invalid argument, working with [this journal](https://gist.github.com/cwarden/0e5db6ab210003637147b561e153343a#file-anon-journal).

```
/tmp $ hledger -f /tmp/anon.journal print -p today
hledger: unable to decommit memory: Invalid argument
/tmp $ hledger -f anon.journal print -p today
/tmp $ hledger -f anon.journal reg -p today
hledger: unable to decommit memory: Invalid argument
/tmp $ hledger -f /tmp/anon.journal reg -p today
hledger: unable to decommit memory: Invalid argument
/tmp $ hledger -f anon.journal print
...
2017/03/07 faba7f2f
    325566ed:cfc24db6:3c0d04e0        $47.23
    fac2dc17:f6f84467:b95464f5       $-47.23

hledger: unable to decommit memory: Invalid argument
```

I'm using hledger 1.0.1 (debian amd64 package 1.0.1-1+b1)

```
/tmp $ hledger +RTS --info
 [("GHC RTS", "YES")
 ,("GHC version", "8.0.1")
 ,("RTS way", "rts_v")
 ,("Build platform", "x86_64-unknown-linux")
 ,("Build architecture", "x86_64")
 ,("Build OS", "linux")
 ,("Build vendor", "unknown")
 ,("Host platform", "x86_64-unknown-linux")
 ,("Host architecture", "x86_64")
 ,("Host OS", "linux")
 ,("Host vendor", "unknown")
 ,("Target platform", "x86_64-unknown-linux")
 ,("Target architecture", "x86_64")
 ,("Target OS", "linux")
 ,("Target vendor", "unknown")
 ,("Word size", "64")
 ,("Compiler unregisterised", "NO")
 ,("Tables next to code", "YES")
 ]
```

Let me know if any additional info would be helpful in troubleshooting.

**Comment by simonmichael** [comment]
Thanks! That is unfortunate. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847677. It appears to be fixed in ghc 8.0.1-15, but perhaps the hledger packages also need rebuilding. Would you mind reporting a bug against the hledger package, https://www.debian.org/Bugs/Reporting .

I expect you could work around this by building hledger yourself, http://hledger.org/download b or c.

**Comment by cwarden** [comment]
I've opened https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=860829 in the debian bug tracker.

**Comment by cwarden** [comment]
I've confirmed that I no longer get the error when building hledger 1.2 with GHC 8.0.2.

**Comment by cwarden** [comment]
This is fixed in Debian sid now, and doesn't affect the version in Jessie.
