### ISSUE TITLE
What are hledger's dependencies?

### ISSUE THREAD

**Issue by crocket** [simonmichael/hledger#544]
I want to package hledger for gentoo, and I can't figure out its dependencies.

Although https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hledger says 'gmp' 'libffi' 'ncurses' 'zlib' are dependencies, I can't confirm.

**Comment by simonmichael** [comment]
Thanks for working on it. Is this something different from the gentoo instruction already on the download page ?

**Comment by simonmichael** [comment]
hledger itself has no C dependencies, just haskell dependencies. The haskell packages that depend on those C libs you mentioned might be: GHC itself, zlib, terminfo, ansi-terminal, vty. (If there's a terminfo C library, that might be required as well).

**Comment by crocket** [comment]
Oh, it is weird.

The last time I visited http://gpo.zugaina.org/Search?search=hledger, there was no result.
Now, I can see packages.

Thanks. I thought there was no hledger package in gentoo overlays.

**Comment by simonmichael** [comment]
Anything you can do to test that install command or improve the packages will be appreciated I'm sure. (Maybe hledger-api is missing ?)
