### ISSUE TITLE
General advice for more complicated CSV formats

### ISSUE THREAD

**Issue by flip111** [simonmichael/hledger#547]
I read in [the manual](http://hledger.org/csv.html) that it's not possible to match on specific fields. What is the general advice for important more complex csv formats? For my bank i found [a script](http://caspar.verhey.net/ing-homebank/) online that converts to the homebank format. Is it possible to recreate the logic in here with the hledger rules file? Or do i need to preformat it using a script or macro?

**Comment by simonmichael** [comment]
If you'd like to paste a CSV sample, I can try. I have been able to convert everything I needed to, so far.

**Comment by flip111** [comment]
```
"Datum","Naam / Omschrijving","Rekening","Tegenrekening","Code","Af Bij","Bedrag (EUR)","MutatieSoort","Mededelingen"
"20170426","bedrijf","nummer1","nummer2","IC","Af","25,00","Incasso","blabla"
```

This is a header with 1 transaction. The heading is as follows:
* Date
* Name / description
* account (my account)
* account (other party account)
* code (this indicates the type of transaction), in this transaction IC stands for the company draw funds from my account automatically (i have signed an agreement for this)
* Af Bij indicates + or -. Af = withdraw, Bij = add to account (through a deposit or something like that)
* The amount (this is always positive because of the previous field)
* Mutation type - this seems to be the same thing as the code before but now in full (without abbreviation to a code)
* Message - a message that can be given by the sender

**Comment by simonmichael** [comment]
The only tricky part is the field specifying the direction sign. Here's how you can handle that with the current feature set:
```
skip 1
date-format %Y%m%d
fields date, description, account1, account2, code, af_bij, amount, _, comment

# if we see a field containing just "Af", flip the amount's sign
if ,Af,
 amount (%amount)
```

**Comment by simonmichael** [comment]
PS a useful command for testing rules:
```shell
$ ls 547.* | entr hledger -f 547.csv print
```

**Comment by flip111** [comment]
Thank you :)
