### ISSUE TITLE
Possibility to account something in the past?

### ISSUE THREAD

**Issue by matze** [simonmichael/hledger#549]
Here's a simple real-world example: I got a tax refund which goes directly to my checking account. The source of that is an income tax account that keeps track of monthly income tax payments. But reducing that account *now* does not make sense because that would not reflect correctly how much tax I paid *this* year. So ideally, I would have a transaction that happens now but changes one of the accounts at a date other than the transaction date.

Is this somehow possible? Or am I thinking this wrongly?

**Comment by simonmichael** [comment]
You can set a date on individual postings, different from the main transaction date. Would you like to know more ? Repost this on the mail list which is better for general questions.

**Comment by matze** [comment]
Thanks for the term I had to look for! Now everything's clear :-)
