### ISSUE TITLE
hledger-1.2 balancesheet --flat regression

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#552]
As of 1.2, balancesheet ignores the --flat flag.

**Comment by simonmichael** [comment]
Hi @mstksg - would you mind reviewing this fix ? (I meant to send a PR). I can't remember why you added this, and it breaks bs --flat.

**Comment by simonmichael** [comment]
This fix was no good, alas. Reopening.

**Comment by mstksg** [comment]
will look at this :)
