### ISSUE TITLE
Balance assertion error when the difference is 0

### ISSUE THREAD

**Issue by rmoehn** [simonmichael/hledger#561]
I'm getting a balance assertion error with the following explanation, but I can't figure out what is wrong. It even says that the difference is 0.

```
in transaction:
2017/06/04 Budget
    a:m:next-non-fun     -923.55 €
    a:m:non-fun           923.55 € = 923.55 €
after posting:
    a:m:non-fun    923.55 €
balance assertion details:
date:       2017/06/04
account:    a:m:non-fun
commodity:  €
calculated: 923.55 €
asserted:   923.55 € (difference: 0)
```

**Comment by simonmichael** [comment]
Hi, thanks for the report - can you include more data (minimising/anonymising as needed) to make this reproducible ?

**Comment by rmoehn** [comment]
Hmm, I tried `print --anon`, but then it doesn't give me the balance assertion error. I don't know what else I can do since I'm not familiar with Haskell or hledger development. I have a hunch that this problem is caused by a goof-up of my own, but still it's weird for hledger to complain about a difference of 0.

**Comment by simonmichael** [comment]
Yes, that is weird and interesting. Just make a copy of your journal and minimise it - chop things out and simplify it until it's small as possible while still reproducing the bug.

**Comment by simonmichael** [comment]
PS if you have the [entr](http://entrproject.org) tool available, here's a nice way to do that:

`ls test.j | entr hledger -f test.j bal`

**Comment by rmoehn** [comment]
I'm finally getting back to this. Your hint with entr was indeed very helpful. Thanks! The following is what fails. I could have made it smaller, but I was lazy.

```
commodity 10,000.00 €
commodity 10,000.00 $
commodity 1,0000. 円

2017/04/25 * f90470b7
    452a9f37:ca2a39               1001.43 €
    452a9f37:392a8c53:e1299fc1     806.07 €
    382a8ac0:6cfd7d2a            -1807.50 €

2017/05/10 * 80268660
    382a8ac0:6cfd7d2a           27216 円 @ 0.0080749 €
    452a9f37:4f00fc99:c26914d0          -173.0000000 €
    452a9f37:392a8c53:e1299fc1           -46.7664784 €

2017/05/23 * f90470b7
    452a9f37:ca2a39               1131.45 €
    452a9f37:392a8c53:2a367c9b     923.55 €
    382a8ac0:6cfd7d2a            -2055.00 €

2017/06/02 6c9085f6
    382a8ac0:6cfd7d2a                27.18 €
    452a9f37:392a8c53:1fc0f78b      -15.59 €
    452a9f37:392a8c53:e1299fc1      -11.59 €

2017/06/04 1809dc3
    382a8ac0:6cfd7d2a               742.33 €
    452a9f37:392a8c53:e1299fc1     -700.58 €
    452a9f37:392a8c53:1fc0f78b      -41.75 €

2017/06/04 1809dc3
    452a9f37:392a8c53:1fc0f78b       47.13 €
    452a9f37:392a8c53:e1299fc1      -47.13 €

2017/06/04 1809dc3
    452a9f37:392a8c53:2a367c9b     -923.55 €
    452a9f37:392a8c53:e1299fc1      923.55 € = 923.55 €
```

The problem is that the second transaction puts an amount with lots of decimal places on 452a9f37:392a8c53:e1299fc1. That's why the asserted 923.55 € is wrong, by -0.0035216 € actually. However, the commodity directive causes hledger to render it rounded to two decimal places and thus 0.

**Comment by simonmichael** [comment]
Thanks for the example.

**Comment by awjchen** [comment]
I have reduced the example to the following, which gives a similar balance assertion error:
```
> cat 561_mod.journal             
commodity 10,000.00 €
commodity 1,0000. 円

2017/05/10
    acct1      1 円 @ 0.999 €
    acct2

2017/06/04
    acct2      0 € = -1.00 €
```
```
> hledger -f 561_mod.journal print
hledger: balance assertion error in "561_mod.journal" (line 9, column 20):
in transaction:
2017/06/04
    acct2               0 = -1.00 €
after posting:
    acct2    0
balance assertion details:
date:       2017/06/04
account:    acct2
commodity:  €
calculated: -1.00 €
asserted:   -1.00 € (difference: 0)
```
The problem is precision, as noted above, which can be confirmed by tracing `showamountquantity` in `hledger-lib/Hledger/Data/Amount.hs` to show the quantities and precision of the amounts it displays (where the precisions are part of the `AmountStyle`):
```
quantity: 0.000, precision: 2
quantity: 0, precision: 0
quantity: 0, precision: 2
quantity: 0, precision: 0
quantity: 0, precision: 2
quantity: 0, precision: 2
quantity: -1.00, precision: 2
quantity: 0, precision: 2
quantity: -0.999, precision: 2
quantity: -1.00, precision: 2
quantity: -0.001, precision: 2
```
The value `-0.999` is produced by the multiplication of quantities in the `costOfAmount` function, also in `Data/Amount.hs`, displayed below:
```haskell
costOfAmount :: Amount -> Amount
costOfAmount a@Amount{aquantity=q, aprice=price} =
    case price of
      NoPrice -> a
      UnitPrice  p@Amount{aquantity=pq} -> p{aquantity=pq * q}  -- `-0.999` produced here
      TotalPrice p@Amount{aquantity=pq} -> p{aquantity=pq * signum q}
```
It seems like this issue would be prevented if we just rounded the result of the multiplication.

I'm not too familiar with financial stuff, but must real-world transactions always use a whole number of cents? If so, would it be reasonable to stipulate that all amounts of a certain commodity have the same precision, perhaps specified by the commodity directive?

**Comment by awjchen** [comment]
Ah, my example is the same as the one @ony gave in #489! Are these issues the same?

**Comment by simonmichael** [comment]
Could well be. I'll send a mail which might be a little bit related.

**Comment by Xitian9** [comment]
I think this can be closed, as hledger now provides a much more detailed error message:
```
hledger: balance assertion: "my journal file" (line 36, column 46)
transaction:
2017-06-04 1809dc3
    452a9f37:392a8c53:2a367c9b       -923.55 €
    452a9f37:392a8c53:e1299fc1        923.55 € = 923.55 €

assertion details:
date:       2017-06-04
account:    452a9f37:392a8c53:e1299fc1
commodity:  €
calculated: 923.5535216
asserted:   923.55
difference: -0.0035216
```
