### ISSUE TITLE
`hledger add` should remember previous inputs

### ISSUE THREAD

**Issue by SzymonPajzert** [simonmichael/hledger#577]
When we enter '<' in prompt to restart transaction it is often tiresome to enter the same details again, because we've made mistake in the last line. There's currently implemented a default answer, which is taken from previous similar transaction. What I would like to see (and probably implement) is additional '<e' option in prompt to set this default value to answers we typed in the amended transactions without looking for similar transactions.

If this feature is welcome, I would be happy to implement it, but I need some guidance to start working on hledger.

**Comment by simonmichael** [comment]
Instead of adding a new <e command, I think it would make sense to just do this with <. The code is in hledger/Hledger/Cli/Add.hs,questions welcome.

**Comment by ghallak** [comment]
@simonmichael I was trying to make the '<' command go one step backward instead of restarting the transaction, as suggested in the issue description, with default values being set as they were set by the user.

Do you think that would be a more appropriate solution to this issue?

**Comment by simonmichael** [comment]
That sounds even better.
