### ISSUE TITLE
Allow separate help output for each command / make --help the same as -h

### ISSUE THREAD

**Issue by varac** [simonmichael/hledger#579]
I.e. `hledger add --help` should print a help for only this command, like most other cli tools do.
Currently, it shows the whole monolithic help for hledger.

**Comment by simonmichael** [comment]
Which other cli tools ?

Currently, `hledger CMD --help` prints the full hledger manual, at least for the builtin commands, and `hledger CMD -h` shows the short command-specific usage.

**Comment by simonmichael** [comment]
(See `hledger -h` for some examples.)

**Comment by simonmichael** [comment]
Ohh I get it. CLI tools other than hledger.

Using -h and --help for short and long help respectively is a little "modern", but we are following in the footsteps of git which is a big precedent..

**Comment by varac** [comment]
> Currently, hledger CMD --help prints the full hledger manual, at least for the builtin commands, and hledger CMD -h shows the short command-specific usage.

Oh, I was not aware of this distinction. For my point of view, this is confusing for the user, because `-h` is considered as the short version of `--help` and I don't see why both should behave differently.
Maybe I'm just used that they behave the same and somewhat "unmodern" in this sense :D

**Comment by simonmichael** [comment]
I find the short and long help distinction useful. I wouldn't be against making --help a synonym for -h again. But, what name would you use for the current `--help` and `help` functionality ? There is a certain symmetry and consistency with the current --help/--man/--info & help/man/info.

**Comment by simonmichael** [comment]
PS maybe start a discussion on the mail list to get more input on this.

**Comment by cfellinger** [comment]
Lately I use -h/-help for the short and -H/--HELP for the long help text.  Seems to work.  When you're unfamiliar with the program the standard -h/--help tells you there is an option to get more help, and the
uppercase variant is close enough to be easy to remember.

**Comment by simonmichael** [comment]
Interesting, but -H is used for --historical.

**Comment by cwarden** [comment]
I always use `git help <command>` rather than `git <command> --help`.  I also expect `--help` and `-h` to be synonyms.

**Comment by simonmichael** [comment]
I use git-CMD --help and didn't notice git help. I'm also used to the long ledger --help.

**Comment by cfellinger** [comment]
On Thu, Jul 06, 2017 at 05:56:27AM -0700, Simon Michael wrote:
> Interesting, but -H is used for --historical.

I could live with --HELP only, more help requires extra effort.

But as long as -h gives the short version and the long help version
contains a hint how to get the short help text w're good I presume.

-- 
groetjes, carel

**Comment by simonmichael** [comment]
Some thoughts:

** principles
*** docs (usage, manuals, tutorials..) should be available reliably and instantly from the software you are running (without net or filesystem access and on windows too)
*** docs should by default be provided in the native UI of the tool you request them from
*** each tool should provide the full set of docs
*** within a tool, there should be one clear way to call up any particular doc

** mockup
 ```
 hledger -h/--help                         general usage
 hledger CMD -h/--help                     command usage
 hledger help                              list manuals/topics
 hledger help [--man|--info] MANUAL/TOPIC  show MANUAL/TOPIC as plain text[/man page/info manual]
 hledger-ui, hledger-web              (manuals provided in-app)
 ```

**Comment by simonmichael** [comment]
Let's try it this way. --help and -h are synonyms again, and all more detailed help is provided by a single powerful help command (and an equivalent feature in hledger-ui/hledger-web, some day).

Git's scheme was more scalable, in that you could always get the manual for any new executable by running it with --help. Our help command is monolithic, it has to have the docs built in. There might be a way around that some day.

**Comment by simonmichael** [comment]
Fixed.

**Comment by varac** [comment]
Thx !
