### ISSUE TITLE
hledger 1.3 is not in stackage or lts-9

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#591]
See https://github.com/fpco/stackage/issues/2628 . Secondly, we need some better process for ensuring the hledger packages in stackage are as fresh as possible.

**Comment by simonmichael** [comment]
hledger-1.3 has landed in stackage nightly. ui, web and api are currently blocked due to GHC 8.2 issues, though not ours AFAICT.

**Comment by cdornan** [comment]
@simonmichael we are taking `hledger` out of nightly again because it has been blocking megaparsec-6 for 4 weeks and we are getting complaints: https://github.com/fpco/stackage/issues/2666#issuecomment-324234497

Can you get it to work with megaparsec-6? It would be great to get all of the hledger packages back into nightly RSN!

**Comment by simonmichael** [comment]
Amending what I said on the other issue: it was too much work for today, I will finish and release asap.

**Comment by simonmichael** [comment]
@cdornan: hledger-* 1.3.1 supporting megaparsec 6 has been released, I will follow any suggested next steps.

**Comment by simonmichael** [comment]
https://github.com/fpco/stackage/pull/2835, https://github.com/fpco/stackage/pull/2836, https://github.com/fpco/stackage/pull/2838

**Comment by simonmichael** [comment]
All resolved, except for the third-party hledger-* packages which probably be resolved soon. Much better.

Process changes to help keeping our stackage presence fresh: 

- use the same GHC version in our default stack.yaml as stackage nightly as soon as it becomes practical
- periodically run the new thorough `make stackagetest` rule, which builds/tests/benchmarks all main packages with stackage resolvers for the last three GHC versions
