### ISSUE TITLE
Filter by payee

### ISSUE THREAD

**Issue by avillafiorita** [simonmichael/hledger#598]
Hello,
I am trying to filter my ledger by payee. 

The "tags" section of the documentation suggests to use the `payee:` implicit tag. I tried:

    hledger register payee:"A Payee"

with no luck.

However,

    hledger register desc:"A Payee"

seems to correctly return the entries having "A Payee" as the payee.

I am wondering whether I am doing something wrong, the documentation has a glitch, or I bumped into a bug.

**Comment by simonmichael** [comment]
I see the same thing. Thanks for reporting.

http://hledger.org/manual.html#implicit-tags

**Comment by simonmichael** [comment]
@avillafiorita, it has been updated to work like you expect. Docs:
http://hledger.org/manual.html#payee-and-note,
http://hledger.org/manual.html#pivoting,
http://hledger.org/manual.html#queries .
If you happen to test hledger master, please let us know if it fixed the issue for you. Thanks.

**Comment by avillafiorita** [comment]
I recently updated to 1.4 and it works, thank you!
