### ISSUE TITLE
1.4 requires .hledger.journal to exist to run hledger test

### ISSUE THREAD

**Issue by ilovezfs** [simonmichael/hledger#614]
This did not used to be the case as of 1.3.1.

But in hledger 1.4

```
==> /usr/local/Cellar/hledger/1.4/bin/hledger test
The hledger journal file "/tmp/hledger-test-20170930-86811-5j5ute/.hledger.journal" was not found.
Please create it first, eg with "hledger add" or a text editor.
Or, specify an existing journal file with -f or LEDGER_FILE.
```

Of course, I can work around this by

```
touch .hledger.journal
```

but I wanted to make sure this is an intentional change to `hledger test` as it doesn't seem like one.

**Comment by simonmichael** [comment]
That was not intended. Thanks for the report!

**Comment by Xitian9** [comment]
This does not seem to be the case anymore in master. I think this can be closed.
