### ISSUE TITLE
hledger-budget does not compile

### ISSUE THREAD

**Issue by saesh** [simonmichael/hledger#615]
Using Haskell 8.2.1 on `master` branch (`d257351`) running `bin/compile.sh` results in this error:

```
building dependencies
building add-on commands
[1 of 1] Compiling Main             ( hledger-budget.hs, hledger-budget.o )

hledger-budget.hs:193:42: error:
    • Couldn't match expected type ‘InputOpts’
                  with actual type ‘CliOpts’
    • In the first argument of ‘ignore_assertions_’, namely ‘opts’
      In the second argument of ‘($)’, namely ‘ignore_assertions_ opts’
      In the expression: not $ ignore_assertions_ opts
    |
193 |     let assrt = not $ ignore_assertions_ opts
    |                                          ^^^^
```

Any help with this is appreciated.

**Comment by simonmichael** [comment]
Thanks for the report. https://groups.google.com/d/msg/hledger/77pKzzv8GXY/PBrBm_yIAAAJ explains why hledger-budget hasn't been integrated yet. Could somebody update it ?

**Comment by simonmichael** [comment]
Pinging @ony, in case you missed this.

**Comment by simonmichael** [comment]
Thanks! That does fix the immediate issue. What do you think about making hledger-budget just offer that one command, so it can be integrated like the others ?

**Comment by simonmichael** [comment]
Continued on #617.
