### ISSUE TITLE
Allow brick <0.27

### ISSUE THREAD

**Issue by rhofour** [simonmichael/hledger#618]
Brick [0.25 and 0.26 added new functions](https://github.com/jtdaugherty/brick/blob/master/CHANGELOG.md) without breaking backwards compatibility. You should be able to safely extend your version bounds.

This is currently blocking the availability of brick-0.26 on Stackage: https://github.com/fpco/stackage/issues/2933

**Comment by rhofour** [comment]
Also, shouldn't you really want brick <1.0? Minor versions should always be backwards-compatible.

**Comment by simonmichael** [comment]
@rhofour, thanks for the report. I have revised hledger-ui to allow latest brick (again).
