### ISSUE TITLE
add sub-items on description

### ISSUE THREAD

**Issue by azzamsa** [simonmichael/hledger#636]
I want to have detailed log on every transaction, so instead of writing

- trip to the supermarket : $10

I want to add more sub-items

- trip to the supermarket : $10
  - tomatos : $3
  - ketchup : $2
  - meat    : $5

Can I achive this in hledger ?

Thank you so much for this awesome application.

**Comment by simonmichael** [comment]
You're welcome azzamsa. You can use subaccounts, eg:
```
2017/10/29 supermarket
  expenses:food:groceries:tomatoes  $3
  expenses:food:groceries:ketchup  $2
  expenses:food:groceries:meat  $5
  assets:checking
```
or comments (which you can't search on or display in a report):
```
2017/10/29 supermarket
  expenses:food:groceries  $3  ; tomatoes
  expenses:food:groceries  $2  ; ketchup
  expenses:food:groceries  $5  ; meat
  assets:checking
```
or tags (which you can):
```
2017/10/29 supermarket
  expenses:food:groceries  $3  ; detail:tomatoes
  expenses:food:groceries  $2  ; detail:ketchup
  expenses:food:groceries  $5  ; detail:meat
  assets:checking
```

**Comment by azzamsa** [comment]
wow, thank you so much for fast response.  Actually, I want to use hledger months ago but I stuck with this problem. I asked in IRC but no response so I try to ask here, maybe if this feature has not been implemented yet, my issue will give you and idea.

But, fortunately I can achieve this with three ways you described above. I will read the docs on how to use subaccounts and try it soon. 

Thank you so much for your great contribution to community.

**Comment by simonmichael** [comment]
Great. In IRC (the #hledger channel), don't forget to stick around/leave window open for a while, or check back at a different time of day - sometimes it takes a while to get noticed.
