### ISSUE TITLE
hledger-web 1.4 showing zero amount accounts by default

### ISSUE THREAD

**Issue by ohmyohmyohmy** [simonmichael/hledger#641]
hledger-web 1.4 is showing zero amount accounts by default. So, there's no option to turn it off.

Running on Windows 7.

Thanks!

**Comment by simonmichael** [comment]
Hi, you're right. It was [hard-coded](https://github.com/simonmichael/hledger/blob/master/hledger-web/Handler/Common.hs#L76), as part of hledger-web's goal of being a simple UI that just works without surprises for non-power-users. Is it causing you a lot of trouble ?

**Comment by ohmyohmyohmy** [comment]
It's just not pretty having a whole bunch of Accounts Receivables (about 50) showing zero, on my balance sheet is all.

Plus, I was expecting zero amount accounts to be hidden by default as stated in the doc:

>  -E --empty
>     show items with zero amount, normally hidden

**Comment by simonmichael** [comment]
That does sound annoying. And you're right that it's at least a docs bug. 

On the other hand: I imagine non-expert users starting up hledger-web, and not seeing a full picture of their assets (eg) just because some of them happen to be currently empty, and this seems like a usability/discoverability problem to me.

I'm not using hledger-web a lot at the moment, but maybe what's needed is a discoverable toggle within the UI ? Maybe somebody can work on this ?

**Comment by ohmyohmyohmy** [comment]
Yeah, I see what you mean. Though, I imagine anyone using hledger-web would have started with hledger or ledger-cli first, and then try hledger-web out of curiousity, so the concern with non-experts (which is who I am by the way) may be a non-issue.

Like me, I started with hledger and then tried hledger-web, so I sorta expected both to act the same way, and have zero amount accounts hidden by default and the option to turn it on with -E when I want it to. I actually thought I did something wrong, and was checking my ledger file to see if I entered something, a special comment maybe, that would turn zero-amount accounts on (told you I was a non-expert).

A simple checkbox at the top-left corner with the words "Show accounts with zero amounts" then "refresh", would help, I guess?

**Comment by simonmichael** [comment]
Some possible resolutions:

A. change hledger-web --help/docs to match the current behaviour (always show zero-balance accounts)

B. change hledger-web to behave like hledger (show zero-balance accounts only if you start it with a -E command line flag. Won't be available to GUI users double-clicking the hledger-web icon.)

C. enhance hledger-web so zero-balance accounts can be toggled in the UI (as in hledger-ui), making them discoverable

My preference would be C. If nobody wants to work on that, I'd accept a PR removing the special case and enabling B, but it should be cleared with the mail list too, to see if existing users have any objection.

**Comment by dotlambda** [comment]
I think hledger-ui is doing the same: It shows zero-balance accounts that `hledger balance` doesn't show unless you pass the `-E` flag.

**Comment by simonmichael** [comment]
(There was no objection, PRs welcome.)

**Comment by simonmichael** [comment]
@dotlambda you're right, hledger-ui shows zero-balance accounts by default, with no way to change that initial setting, and incorrect command-line help for hledger-ui -E. We should change -E's help, to "hidden by some commands" or something. 

hledger-ui does provide discoverable UI (the Z key) for toggling them, at least. (Note the change of letter - Z toggles zeroes. I found it more mnemonic, and E was valuable for something else. Would there be any sense in also allowing -Z on the command line ?)

**Comment by Xitian9** [comment]
I think this issue can be closed, as both hledger-ui and hledger-web now take the `--empty` flag to toggle this behaviour (though their defaults are still the opposite of hledger).

**Comment by simonmichael** [comment]
Agreed. At least "there's no option to turn it off" is no longer true (-E hides zero accounts in hledger-web and hledger-ui).
