### ISSUE TITLE
hledger-web only processes first file -f argument

### ISSUE THREAD

**Issue by dbp** [simonmichael/hledger#657]
If I run: `hledger-web --server -f file1.ledger -f file2.ledger`, the web UI only shows data from the first file, and the title at the top of the page is `file1.ledger`. This isn't great, especially because I can't run hledger-web from standard in (which granted would probably complicate things, as it would necessitate a read-only mode), and seems to contradict the documentation, which writes:

> Like hledger, it reads data from one or more files in hledger journal, timeclock, timedot, or CSV format specified with -f, or $LEDGER_FILE, or $HOME/.hledger.journal (on windows, perhaps C:/User/USER/.hledger.journal).

Perhaps this limitation has something to do with needing to know where to store added entries, but it would be great if it were fixed. 

There are at least two use cases:

- I having archival .ledger files and then current ones, and ideally want to be able to show them all in the web ui sometimes. 
- I usually process bank transaction when statements are issued (to make it easier to not duplicate things), but I wanted to look at the most current data available, so I downloaded all transactions since last statement. I don't want to add this to my ledger file, but I would like to be able to, temporarily, look through them in the web ui.

**Comment by zarybnicky** [comment]
@simonmichael While solving the Sandstorm permission problem and resurrecting the edit/import forms, I might as well solve this one. What's the standard way of handling multiple files now? Append to the last one specified?

**Comment by simonmichael** [comment]
I suspect we add to the primary (first) file. I would check what the add command does. We should have pretty solid support in hledger-lib for multi-file journals now.

**Comment by simonmichael** [comment]
This got fixed by 6a966836 and released in hledger-web 1.10.

It still only shows the first file's name as the title, pull requests welcome for that.
