### ISSUE TITLE
Tags are not shown.

### ISSUE THREAD

**Issue by NorfairKing** [simonmichael/hledger#664]
https://hackage.haskell.org/package/hledger-lib-1.4/docs/Hledger-Data-Transaction.html#v:showTransaction

Does not render tags.
The test even talks about a transaction _with_ tags, but explicitly does not expect them in the output.

**Comment by ony** [comment]
@NorfairKing , I agree that it might be confusing. But reason for that is that all tags comes from comments. By the end of parsing you have tags included in both `ptags`/`ttags` and `pcomment`/`tcomment`.
`showTransaction` assumes that these two are consistent and takes the easiest way and render all comments together preserving their original representation.
If you want to manipulate with tags you should render them to comments of `Posting` or `Transaction`.

Though `showTransaction` may do better by checking if there is a new tags and add them. But it will be still inconsistent and there is no clear understanding how removal of tags show change comments.

P.S. Same issue with dates that can be overridden in comments :)

**Comment by NorfairKing** [comment]
@ony Now I understand! Thanks for the clarification! The improvement to showTransaction that you describe would fix my use-case. I am trying to generate some transactions from scratch with hledger as a library and the resulting hledger journal is missing data because the tags dissappear.

**Comment by NorfairKing** [comment]
On a related note, this duplication of information is a significant code smell and should be taken care of seperately as well, in my opinion.

**Comment by simonmichael** [comment]
Quick comment without looking at code: in journal syntax, tags are kept in comments. showTransaction generates journal syntax. Ie ony is right, it's best to think of ttags/ptags fields as an internal optimization.

If you still think it should behave differently, show us exactly how it would look.

**Comment by NorfairKing** [comment]
@simonmichael I'd like to way to generate a transaction with tags, such that those tags don't dissappear.
I guess a function as follows should be enough:

```
commentWithTags
    :: Text -- Old comment
    -> [Tag]
    -> Text -- New comment
```

**Comment by simonmichael** [comment]
If you're generating a transaction, it's easy to just generate a comment containing the tags, but if you're adding tags to an existing transaction yes I can see that will be useful. You're the first person to need this so you get to define its behaviour. :)

**Comment by NorfairKing** [comment]
> it's easy to just generate a comment containing the tags

Maybe, but I don't want to be the one to maintain that code :p
Thanks for the label and triage. I will get back to this if it turns out to be mission-critical.

**Comment by simonmichael** [comment]
Ok, if it helps:
```
renderTag (n,v) = n ++ ":" ++ v
renderTags tags = intercalate ", " . map renderTag
transactionSetTags tags t = t{tcomment=renderTags tags}
```

**Comment by NorfairKing** [comment]
@simonmichael Thanks!
I had to fix that a bit:

```
renderTag :: Tag -> Text
renderTag (n, v) = n <> ":" <> v

renderTags :: [Tag] -> Text
renderTags = T.intercalate ", " . map renderTag

transactionSetTags :: [Tag] -> Transaction -> Transaction
transactionSetTags tags t = t {tcomment = renderTags tags}
```

**Comment by NorfairKing** [comment]
These are not unambiguously parseable, are they? What happens if there are commas or colons in tags?

**Comment by simonmichael** [comment]
Tag values continue until the first comma or end of line. More details at http://hledger.org/manual.html#tags-1

**Comment by simonmichael** [comment]
(And tag names may not contain commas or colons. Not sure which you meant.)

**Comment by simonmichael** [comment]
Hi @NorfairKing. I found this again via #1101, and it's a bit hard to understand the discussion two years later.. do you remember what this was for ? What was the use case ?

**Comment by NorfairKing** [comment]
I don't remember at all :s

**Comment by simonmichael** [comment]
Ok. :) showTransaction and print do render comments/tags today, closing.
