### ISSUE TITLE
Query any of matching amounts

### ISSUE THREAD

**Issue by varac** [simonmichael/hledger#665]
Hi, 

maybe I don't fully understand the query syntax (more example in the manpage would be highly appreciated), but how can I query for any of two specified amounts ?

    hledger reg amt:20.00 amt:10.00

shows nothing at all, while single searches for each amount do show some transactions.

**Comment by simonmichael** [comment]
That's a good question. It's not so easy, because we haven't got around to implementing full boolean query expressions. As the "queries" doc says, like query terms are AND'd together.

Some possible workarounds, meanwhile:
```
(hledger print amt:20; hledger print amt:10) | hledger -f- reg    # (bash syntax)
```
```
hledger reg amt:'>=10' amt:'<=20'
```

**Comment by simonmichael** [comment]
(Actually it doesn't say that. [Here's](http://hledger.org/manual.html#queries) what it says.)

**Comment by varac** [comment]
Is there an issue for implementing full boolean query expressions that I could subcribe to ? Is this on the roadmap ?

**Comment by simonmichael** [comment]
https://github.com/simonmichael/hledger/issues/203 is the one I found just now. This is a feature we'd like to have, and shouldn't be too hard.

**Comment by ony** [comment]
@simonmichael currently accounts being OR-ed together and `not:...` being AND-ed. It might make sense have something similar for `amt:...` as well where precise values are added to query with `OR` semantic while half-ranges with AND.
I would definitely like to have complete query language that allows me to find any transaction (maybe SQL-like with grouping). But I suspect that this feature will be underused by most people.
Even `hledger reg amt:20.00 amt:10.00`

**Comment by phobo3s** [comment]
i am trying this command
hledger reg "alınan sipariş" amt:>0
expecting a return of records that amount is more than zero but get this instead

hledger: could not parse as a comparison operator followed by an optionally-signed number:
CallStack (from HasCallStack):
  error, called at ./Hledger\Query.hs:296:102 in hledger-lib-1.27-5xCcUkcpkQ6LSGTMZgtDyf:Hledger.Query

**Comment by simonmichael** [comment]
< and > are special to the shell, so you need to quote the third
 argument, like you did with the second.

**Comment by phobo3s** [comment]
thank you for quick reply and answering this simple question.

**Comment by DanielG** [comment]
@simonmichael Since #203 has landed (yey!) this issue can likely be closed now.
