### ISSUE TITLE
rewrite tools/pandoc-*.hs as lua scripts

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#670]
Shake.hs will soon depend on pandoc 2, which has built in support for [filters written in lua](http://pandoc.org/lua-filters.html). If we rewrite our [haskell pandoc filters](http://pandoc.org/filters.html) in lua ([tools/pandoc-*hs](https://github.com/simonmichael/hledger/tree/master/tools), just [the ones being used by Shake.hs](https://github.com/simonmichael/hledger/blob/master/Shake.hs#L82)), we'll remove another source of complexity and fragility from the doc toolchain. Need someone to help with this.

**Comment by simonmichael** [comment]
Getting-started ideas:

Pick one filter, eg https://github.com/simonmichael/hledger/blob/master/tools/pandoc-drop-html-blocks.hs
Get that filter working on command line, cf linked docs
Get a similar lua filter working on command line
Modify Shake.hs to use the lua filter instead of the haskell one
Watch compilation errors: `stack exec --package base-prelude -- ghcid Shake.hs`
Repeat

**Comment by ehildenb** [comment]
Anyone working on this? I can give a try.

**Comment by simonmichael** [comment]
Please do!

**Comment by ehildenb** [comment]
@simonmichael I think you can close due to #741.

**Comment by simonmichael** [comment]
True, and PS it's working great! No more waiting for pandoc filters to compile, and one less reason to need to wait for pandoc to compile.

@ehildenb, if you have any time to look at replacing hakyll-std with just pandoc, that would be quite useful too. If not, I'll try it one of these days.
