### ISSUE TITLE
hledger-api broken on Windows

### ISSUE THREAD

**Issue by jeevcat** [simonmichael/hledger#682]
I'm trying to run hledger-api on Windows, but it will only ever print out the usage text.

I tried digging into the issue but it looks like it is caused by docopt which is exiting due to the `parseArgsOrExit` no matter which arguments are supplied.

I tried adding the following code to find the issue (at the start of main in hledger-api.hs):
``` haskell
args <- getArgs
print parseArgs doc args
```

and it always prints:
`Left "argv" (line 1, column 1):unknown parse error`

That's as far as I managed to get. Has anyone else managed to get this to run on Windows? I'm using Windows 10, build 17046.

**Comment by simonmichael** [comment]
Yikes.. thanks for the troubleshooting. Is there another windows user who can help investigate ?

**Comment by simonmichael** [comment]
I have opened https://github.com/docopt/docopt.hs/issues/31 .

**Comment by MisterY** [comment]
What would be the reason that this happens with hledger-api but now hledger or hledger-web?

**Comment by simonmichael** [comment]
Yes it is, I recommend ignoring hledger-api, hledger-web gets more testing and is probably the focus going forward.

**Comment by mhansen** [comment]
I think we could close this issue, now that hledger-api is mothballed.

**Comment by simonmichael** [comment]
Agreed, thanks!
