### ISSUE TITLE
Query and aggregate transactions by description

### ISSUE THREAD

**Issue by ohbadiah** [simonmichael/hledger#686]
I might want to examine all the purchases at a given store, for instance. Querying and aggregating transactions by description could make that easier. Something like if `print -m` returned a list.

Maybe this should simply be handled through accounts, i.e. maybe I should add a sub-account to transactions with the description I care about, and then query that. But I thought I'd raise the issue.

**Comment by simonmichael** [comment]
Yes, a few ways to do it: use accounts, or match descriptions with desc:, or (slightly more structured) record [payees](http://hledger.org/manual.html#payee-and-note) and match with payee: or pivot on payee.

**Comment by ohbadiah** [comment]
Ah, `desc:` sounds like just the trick! What improvement to the documentation might you envision? I was looking at `hledger -h` and `hledger print -h`. I'm not sure the simplest way to reach documentation on querying.

**Comment by simonmichael** [comment]
Those are good questions. `print -h` does hint at something called `[QUERY]` but to learn about that you'd probably have to explore your way to hledger.org > docs > reference (or hledger) > QUERIES. Or at the command line, `hledger help hledger` > QUERIES. Suggestions/pull requests welcome.

**Comment by ohbadiah** [comment]
Great. If I come up with something I think is an improvement I'll open a separate issue. Thanks!
