### ISSUE TITLE
commodity directive with no decimal point causes wrong parsing

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#688]
```
#!/usr/bin/env shelltest

# this commodity directive causes the decimal points below to be ignored,
# whether comma or period is used
commodity $0

2018/1/1
    a    $1.5
    b    $1.5
    c   $-3

$ hledger -f- print
>2
hledger: could not balance this transaction (real postings are off by $27)
2018/01/01
    a             $15
    b             $15
    c             $-3


>=1
```

**Comment by ony** [comment]
That's actually a matter of interpretation. I.e. should we treat absence of decimals as an indicator of the commodity that always represented in integers.

This was designed and [here is the line responsible for that](https://github.com/simonmichael/hledger/blob/e58272f28f4612568123c998c5d2608cca861379/hledger-lib/Hledger/Read/Common.hs#L591).

```haskell
    asdecimalcheck :: AmountStyle -> Char -> Bool
    asdecimalcheck = \case
        AmountStyle{asdecimalpoint = Just d} -> (d ==)
        AmountStyle{asdigitgroups = Just (DigitGroups g _)} -> (g /=)
        AmountStyle{asprecision = 0} -> const False   -- here we conclude: no decimal points
        _ -> const True
```

**Comment by simonmichael** [comment]
Interesting. This is too surprising at present. Until now we've never limited how many decimals you can write (and that sounds like quite a deep rabbit hole). And maybe you want to write decimal amounts, but have them displayed as integers. I think in the above case it would be better to make no inference about decimal point or digit group separator from the commodity directive.

**Comment by ony** [comment]
> And maybe you want to write decimal amounts, but have them displayed as integers.

It might be confusing. I doubt someone expect to see in their report something like `0 + 1 = 3`. So I 'm not sure about this case yet. As a counter-example:

```
commodity 0 coins

2018/1/1
    (a)    = 1,000 coins
```

Though we can ignore directives that have no decimal and no group separators by removing that line of code. And require to at least one separator to be present in `commodity` directive. I guess absence of any makes that directive useless anyway.

**Comment by awjchen** [comment]
Perhaps commodity directives could be made more explicit? If it wouldn't cause too much breakage, I would prefer to enforce that a commodity directive specify both the digits separator and the decimal point (and thereby a digit grouping scheme).

**Comment by simonmichael** [comment]
I agree, and using my time machine I have [proposed](https://groups.google.com/forum/#!topic/hledger/7VxF05_KowU), [merged](https://github.com/simonmichael/hledger/commit/0b380971f7ae742ba72ee9f8e8ae6de486b46ae7) and [documented](http://hledger.org/journal.html#declaring-commodities) it. :)

I must have screwed something up though, because it's still not enforcing it.

**Comment by simonmichael** [comment]
Separate issue: until now, commodity directives could avoid limiting the decimal places displayed by omitting the decimal point, allowing the default behaviour (use the largest number of decimal places seen in the posting amounts). Now we have lost this ability.

**Comment by simonmichael** [comment]
So, using a commodity directive's single amount to control both parsing and output, produces a slight clash. Needs more thought as to how we can best maximise all of: i18n, flexibility, correctness, predictability, convenience.

**Comment by simonmichael** [comment]
#793 aims to help with this and similar issues.

**Comment by simonmichael** [comment]
I think this was clarified; commodity directives are now required to include a decimal mark and give an error otherwise.
