### ISSUE TITLE
Support different charsets for CSV import

### ISSUE THREAD

**Issue by glumanda99** [simonmichael/hledger#691]
After dealing with https://github.com/simonmichael/hledger/issues/176 and converting semicolons to commas, I got into a new issue with german umlauts. It always throws the same error, without telling me the exact line where it happened (even the debug level didn't help). 

```
hledger: bank.csv: hGetContents: invalid argument (invalid byte sequence)
```

So I removed line by line to get to know where the error comes from. It seems to be an issue with german umlauts such as `ä`, `ö` or `ü`.

```
XXX,Kdnr. XXX für 201801                   OG/000000348 HYPXX ATXXX ...,05.01.2018,05.01.2018,-49.00,EUR
```

**Comment by simonmichael** [comment]
@glumanda99 that sounds like the problem affecting all GHC programs when they don't have a locale set. http://hledger.org/manual.html#troubleshooting any help ?

**Comment by glumanda99** [comment]
@simonmichael I don't think so, my locale is set.

```
manu@X220:~$ echo $LANG
en_US.UTF-8
manu@X220:~$ locale -a
C
de_DE
de_DE@euro
de_DE.iso88591
de_DE.iso885915@euro
deutsch
en_US
en_US.iso88591
en_US.utf8
german
POSIX
```

**Comment by simonmichael** [comment]
Huh, and is the file utf8 encoded ? (`file thefile.csv`).

And just curious, does it have a utf8 BOM ? Support for those was added recently, fedf36e

**Comment by glumanda99** [comment]
I thought ISO 8859 is a subset of UTF8?

```
manu@X220:~$ file tmp/test/easybank.csv
tmp/test/easybank.csv: ISO-8859 text, with CRLF line terminators
```

**Comment by simonmichael** [comment]
I think not, those are different encodings.

**Comment by glumanda99** [comment]
Thanks, you're right, I got it working with 2 ways:

1. `LANG=de_DE.iso88591 hledger -f bank.csv print` or

2. `iconv -f ISO8859-1 -t UTF8 bank.csv` as you said

**Comment by simonmichael** [comment]
I wish we could provide more useful error messages in such cases. Possibly relevant:
https://stackoverflow.com/questions/27616611/run-time-exception-when-attempting-to-print-a-unicode-character/27652154#27652154
https://hackage.haskell.org/package/base-4.10.1.0/docs/GHC-IO-Encoding.html
https://hackage.haskell.org/package/text-1.2.3.0/docs/Data-Text-Encoding-Error.html
