### ISSUE TITLE
seeing markup on website

### ISSUE THREAD

**Issue by efx** [simonmichael/hledger#692]
On http://hledger.org/hledger-web.html, some of the styling markup shows through:
![hledger-web-markup](https://user-images.githubusercontent.com/472721/35334350-124ccaf2-00e0-11e8-95e7-edbf69236fc0.png)

I have seen this in Firefox and Brave.

**Comment by simonmichael** [comment]
Thanks! I see it too, something changed. I see your commit removes a commented style and some trailing spaces on the home page, but I don't see it fixing this issue ?

**Comment by efx** [comment]
sure thing @simonmichael ; hmmm, I'll test this locally later today to resolve that.
