### ISSUE TITLE
AppVeyor Windows builds stuck at f5a39f7b (2017-11-06)?

### ISSUE THREAD

**Issue by ddumitriu** [simonmichael/hledger#694]
Hi,

Any ideas why there are no recent Windows builds on AppVeyor? They used to come out pretty much daily, now the latest one is from 2017-11-06 (commit f5a39f7b).

https://ci.appveyor.com/project/simonmichael/hledger/build/artifacts

**Comment by simonmichael** [comment]
Thanks for letting me know. It seems the last build was on 2017/11/8. I used to have a nightly cron schedule, but today that field is blank and appveyor tells me to contact support to enable it, which I'm doing.

**Comment by simonmichael** [comment]
I think the cause was my cached stack dir exceeding 1G. I cleaned it, and have been able to configure nightly builds again. I'm still having trouble with disk usage though:
```
hledger-web-1.5.99: configure (lib + exe + test)
hledger-web-1.5.99: build (lib + exe + test)
hledger-web-1.5.99: copy/register
hledger-web-1.5.99: test (suite: test)
hledger-web-1.5.99: Test suite test passed
Completed 241 action(s).
Log files have been written to: C:\project\.stack-work\logs\
Test suite failure for package hledger-1.5.99
    test:  exited with: ExitFailure 1
Full log available at C:\project\.stack-work\logs\hledger-1.5.99-test.log
    
             Test Casestest.exe: ConsoleException 6
Command exited with code 1
APPVEYOR_SAVE_CACHE_ON_ERROR is set to 'true' - cache will be updated
Updating build cache...
Cache 'C:\Users\appveyor\AppData\Local\Programs\stack' - Updated
Cache 'c:\project\.stack-work' - Updated
Cache 'c:\sr' - Uploading (363,391,090 bytes)...100%Error uploading cache entry to the cache storage: Remote server returned 500: There is not enough space on the disk.
```

https://ci.appveyor.com/project/simonmichael/hledger/history

**Comment by simonmichael** [comment]
Related: #695

**Comment by simonmichael** [comment]
And: https://www.appveyor.com/blog/2017/11/08/sheduled-builds-for-free-accounts/

**Comment by ddumitriu** [comment]
Any news about this? I tried to build hledger locally, but I am a complete beginner with stack/Haskell and failed.

**Comment by simonmichael** [comment]
Alas, no news. Paying for more space would cost $50/month which makes me want to find another solution. Circle CI perhaps ?

Building on windows should be easy enough with a few pointers, do ask in #hledger IRC channel if you'd like to try again.

**Comment by simonmichael** [comment]
No, Circle CI does not do windows. I see one other option, interesting but with a learning curve: Microsoft's Team Services.
https://www.quora.com/What-are-hosted-continuous-integration-services-for-Windows/answer/Esther-Fan-4
https://docs.microsoft.com/en-us/vsts/build-release/actions/ci-build-github
https://docs.microsoft.com/en-us/vsts/build-release/actions/build-yaml

**Comment by simonmichael** [comment]
Trying this again, building just hledger. The deps take 800M (of 1G allowed) already.
https://github.com/yav/pretty-show/issues/27
https://github.com/corsis/clock/issues/50

**Comment by simonmichael** [comment]
https://ghc.haskell.org/trac/ghc/ticket/15094

**Comment by simonmichael** [comment]
https://github.com/haskell/network/issues/313

**Comment by simonmichael** [comment]
Happy to report we now have nightly windows binaries again. Notes:
- hledger and hledger-web executables are built from master nightly at 2300 UTC (if there are new commits)
- they are also built when a new tag is pushed, or when manually requested by me
- they are packaged together as a 15M zip file for quicker download
- the download page links to the zip file from the last successful build
