### ISSUE TITLE
`--value` uses way too many decimals

### ISSUE THREAD

**Issue by NorfairKing** [simonmichael/hledger#701]
Hi,

I have a transaction file that ends like this:

```
P 2018/01/11 EUR 1.173598723124589238153703263378702104091644287109375 CHF
P 2018/01/11 GBP 1.31754041555224699067139226826839148998260498046875 CHF
P 2018/01/11 USD 0.97665787674577597687886054700356908142566680908203125 CHF
```

When I try to show the balance, I get this:

```
3639.96648345527031066626300059851928381249308586120605469 CHF  assets
3594.68134294616630079910457595815387321636080741882324219 CHF    bank
          84.05 CHF        card
         420.00 CHF        savings
```

I get that this could 'accurate', but the alignment is messed up as a result.

Is there a way to ensure that the style used in the transactions could be used after the multiplication with the rate?

On a related note, `hledger-web` doesn't seem ot handle `--value` very well.

**Comment by simonmichael** [comment]
This is a complicated topic, but hopefully the short answer is use a http://hledger.org/manual.html#commodity-directive . It would be useful to see a minimal example.

**Comment by NorfairKing** [comment]
I can confirm that this is a nice workaround ^

**Comment by NorfairKing** [comment]
Closing this as "fixed well enough"

**Comment by ony** [comment]
Problem might exist for both `-V` and `-B`. We may want to ensure that `jinferredcommodities` are not offended by `-V` and `-B`. Note that after #509 resolved we already apply style unification.

I would suggest to re-open this issue. As a solution we might have either dropping price styles completely or having them to be unified separately from amounts.
