### ISSUE TITLE
need to read scientific notation numbers in CSV

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#704]
Coinbase uses scientific notation for very small amounts, which breaks our CSV reader. I think it makes sense for use to add support for this when reading CSV. Would anyone like to take a crack at it ?
```
2018-01-01 20:28:12 -0800,3.0e-08,...
```

**Comment by flip111** [comment]
Is there a recommendation of library to use ?

**Comment by simonmichael** [comment]
Haskell can read it natively I believe. We'll have to handle read errors gracefully, still allow the use of e or E as commodity symbol (I do that), etc. numberp in Hledger.Read.Common seems the right neighbourhood.

**Comment by simonmichael** [comment]
Oops no, that’s for journal format, which is a separate question.

**Comment by simonmichael** [comment]
All good points. I need it only for CSV right now. Limiting scope that way could possibly keep this a small task. I have not seen anybody needing this in journal format yet, though I do like the idea of allowing there just for generality, assuming we find solutions to all the horrible issues you raise. :)

**Comment by simonmichael** [comment]
Now I see the commit comments were showing up on PR #706. Never mind, I continue the main discussion here on the original issue #704. 

I guess next steps are to merge #706, add our scientific notation to the journal > Amounts doc, and make sure we do warn if it looks a digit group separator is used in scientific notation.

**Comment by simonmichael** [comment]
Merged. For the record (and noted in scientific.test): E-notation with only a digit group separator is indeed wrongly parsed as a decimal point. Eg, assuming you use comma as thousands separator and period as decimal point:
```
2018/1/1
  (a)   $1,000e1   ; looks like $10000, but parsed as $10.
```
If you declare the thousands separator with a commodity directive, you get a useful (though unclear) parse error instead:
```
commodity $1,000.00
2018/1/1
  (a)   $1,000e1   ; gives a parse error
```
But setting the thousands separator implicitly by the first amount does not give the useful error:
```
2018/1/1
  (a)   $1,000.00  ; implicitly declare comma as thousands separator
2018/1/1
  (a)   $1,000e3  ; should be parsed as $1000000, is parsed as $1000
```
I've mentioned it in [docs](http://hledger.org/manual.html#amounts).
