### ISSUE TITLE
 Missing packages on Debian 9

### ISSUE THREAD

**Issue by hoclun-rigsep** [simonmichael/hledger#705]
Date: Thu, 8 Feb 2018 10:21:39 -0500
Subject: [PATCH] Add libtinfo-dev to Debian prerequisites

the install script didn't work for me until I installed libtinfo-dev, so:

```
 hledger-install/hledger-install.sh | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/hledger-install/hledger-install.sh b/hledger-install/hledger-install.sh
index ff18a30b..d1c345bc 100755
--- a/hledger-install/hledger-install.sh
+++ b/hledger-install/hledger-install.sh
@@ -226,7 +226,7 @@ do_ubuntu_install() {
 do_debian_install() {
 
   install_dependencies() {
-    apt_install_dependencies g++ gcc libc6-dev libffi-dev libgmp-dev make xz-utils zlib1g-dev
+    apt_install_dependencies g++ gcc libc6-dev libffi-dev libgmp-dev make xz-utils zlib1g-dev libtinfo-dev
   }
```

**Comment by simonmichael** [comment]
Thanks! It would be useful to know a little more about the error you see without this, and what it is providing that we need. Eg certain files needed to build vty & hledger-ui ?

**Comment by simonmichael** [comment]
```
[21 of 36] Compiling Graphics.Vty.Input.Loop ( src/Graphics/Vty/Input/Loop.hs, .stack-work/dist/i386-linux/Cabal-2.0.1.0/build/Graphics/Vty/Input/Loop.o )               
<command line>: can't load .so/.DLL for: libtinfo.so (libtinfo.so: cannot open shared object file: No such file or directory)                                            
```
hledger-ui requires vty which requires (eg) the /usr/lib/i386-linux-gnu/libtinfo.so symbolic link installed by libtinfo-dev, it seems. We should add this to both the debian and ubuntu install routines probably. This will increase our divergence from the original stack install script.

**Comment by simonmichael** [comment]
This should be fixed on debian/ubuntu now. We need help identifying similar changes needed for alpine, arch, centos, fedora, freebsd, osx.
