### ISSUE TITLE
hledger-install.sh fails on FreeBSD 12.0-current

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#709]
The stack and/or ghc downloaded by the installer don't yet work with 12-current, see https://github.com/commercialhaskell/stack/issues/3515 . And [freebsd's stack](https://www.freshports.org/devel/stack) is too old to work. 

```
--  While building custom Setup.hs for package base-compat-0.9.3 using:
      /usr/home/jungle/.stack/setup-exe-cache/x86_64-freebsd/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-freebsd/Cabal-2.0.1.0 configure --with-ghc=/usr/home/jungle/.stack/programs/x86_64-freebsd/ghc-8.2.2/bin/ghc --with-ghc-pkg=/usr/home/jungle/.stack/programs/x86_64-freebsd/ghc-8.2.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/usr/home/jungle/.stack/snapshots/x86_64-freebsd/lts-10.5/8.2.2/pkgdb --libdir=/usr/home/jungle/.stack/snapshots/x86_64-freebsd/lts-10.5/8.2.2/lib --bindir=/usr/home/jungle/.stack/snapshots/x86_64-freebsd/lts-10.5/8.2.2/bin --datadir=/usr/home/jungle/.stack/snapshots/x86_64-freebsd/lts-10.5/8.2.2/share --libexecdir=/usr/home/jungle/.stack/snapshots/x86_64-freebsd/lts-10.5/8.2.2/libexec --sysconfdir=/usr/home/jungle/.stack/snapshots/x86_64-freebsd/lts-10.5/8.2.2/etc --docdir=/usr/home/jungle/.stack/snapshots/x86_64-freebsd/lts-10.5/8.2.2/doc/base-compat-0.9.3 --htmldir=/usr/home/jungle/.stack/snapshots/x86_64-freebsd/lts-10.5/8.2.2/doc/base-compat-0.9.3 --haddockdir=/usr/home/jungle/.stack/snapshots/x86_64-freebsd/lts-10.5/8.2.2/doc/base-compat-0.9.3 --dependency=base=base-4.10.1.0 --dependency=unix=unix-2.7.2.2
    Process exited with code: ExitFailure 1
    Logs have been written to: /usr/home/jungle/.stack/global-project/.stack-work/logs/base-compat-0.9.3.log

    Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2: No cabal file found.
    Please create a package description file <pkgname>.cabal
...
```

One possible workaround for freebsd 12 users:
- install freebsd's ghc (8.0)
- git clone https://github.com/simonmichael/hledger.git
- cd hledger
- stack --system-ghc --no-install-ghc --stack-yaml stack8.0.yaml install

Another:
- install [freebsd's cabal-install](https://www.freshports.org/devel/hs-cabal-install)
- git clone https://github.com/simonmichael/hledger.git
- cd hledger
- ./cabal-install.sh

**Comment by myfreeweb** [comment]
I have a patch that updates ports to ghc 8.2.1 (and probably breaks some `hs-` ports) https://github.com/myfreeweb/freebsd-ports-dank/commit/475ac1b3411dc9927cdc1d87fe88a8c1808326c9 should upgrade that to 8.2.2 but didn't have time to do so

**Comment by jungle-boogie** [comment]
I've also gotten hledger to build with this on 11.1:
`stack --system-ghc --install-ghc --stack-yaml stack8.0.yaml install`

when haskell files change, will I need to run the same build line above?

**Comment by simonmichael** [comment]
Update: although I don't see a response to [this](https://github.com/commercialhaskell/stack/issues/3515#issuecomment-366514846), [FreeBSD's stack](https://www.freshports.org/devel/stack) was updated in June. Could someone on FreeBSD 12 retest hledger-install.sh (with and without stack already installed) and report the latest status ?

**Comment by zieone** [comment]
$ bash hledger-install.sh
hledger-install.sh 20190309 Sun  4 Aug 2019 08:21:19 PDT
WARNING: this script installs hledger (and perhaps stack) in '/home/zie/.local/bin'
  but this directory is not in your PATH. Adding it temporarily. To run
  these things easily, please add it to PATH in your shell profile.
  Eg, bash users:
    echo "export PATH=$PATH:~/.local/bin" >> ~/.bashrc && source ~/.bashrc

System info:
FreeBSD 12.0-STABLE-HBSD FreeBSD 12.0-STABLE-HBSD  HARDENEDBSD-12-STABLE

Install status before:
hledger is not found
hledger-ui is not found
hledger-web is not found
hledger-api is not found
hledger-iadd is not found
hledger-interest is not found
hledger-install.sh is not found

Install method:
no stack or cabal installed; stack will be installed and used to install hledger in /home/zie/.local/bin
Installing stack
Updating HardenedBSD repository catalogue...
HardenedBSD repository is up to date.
All repositories are up to date.
The following 9 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	gmake: 4.2.1_3
	gcc: 8_3
	compat8x-amd64: 8.4.804000.20151116
	compat9x-amd64: 9.3.903000.20170608
	compat10x-amd64: 10.4.1004000.20181014
	gcc8: 8.3.0_2
	mpfr: 4.0.2
	mpc: 1.1.0_2
	binutils: 2.32_1,1

Number of packages to be installed: 9

The process will require 386 MiB more space.
67 MiB to be downloaded.
[1/9] Fetching gmake-4.2.1_3.txz: 100%  419 KiB 429.3kB/s    00:01
[2/9] Fetching gcc-8_3.txz: 100%    836 B   0.8kB/s    00:01
[3/9] Fetching compat8x-amd64-8.4.804000.20151116.txz: 100%  419 KiB 429.1kB/s    00:01
[4/9] Fetching compat9x-amd64-9.3.903000.20170608.txz: 100%    3 MiB   1.5MB/s    00:02
[5/9] Fetching compat10x-amd64-10.4.1004000.20181014.txz: 100%    2 MiB   1.2MB/s    00:02
[6/9] Fetching gcc8-8.3.0_2.txz: 100%   37 MiB   1.4MB/s    00:28
[7/9] Fetching mpfr-4.0.2.txz: 100%  441 KiB 451.2kB/s    00:01
[8/9] Fetching mpc-1.1.0_2.txz: 100%   78 KiB  79.8kB/s    00:01
[9/9] Fetching binutils-2.32_1,1.txz: 100%   24 MiB   1.8MB/s    00:14
Checking integrity... done (0 conflicting)
[1/9] Installing mpfr-4.0.2...
[1/9] Extracting mpfr-4.0.2: 100%
[2/9] Installing compat10x-amd64-10.4.1004000.20181014...
[2/9] Extracting compat10x-amd64-10.4.1004000.20181014: 100%
[3/9] Installing mpc-1.1.0_2...
[3/9] Extracting mpc-1.1.0_2: 100%
[4/9] Installing binutils-2.32_1,1...
[4/9] Extracting binutils-2.32_1,1: 100%
[5/9] Installing compat9x-amd64-9.3.903000.20170608...
[5/9] Extracting compat9x-amd64-9.3.903000.20170608: 100%
[6/9] Installing gcc8-8.3.0_2...
[6/9] Extracting gcc8-8.3.0_2: 100%
[7/9] Installing gmake-4.2.1_3...
[7/9] Extracting gmake-4.2.1_3: 100%
[8/9] Installing gcc-8_3...
[8/9] Extracting gcc-8_3: 100%
[9/9] Installing compat8x-amd64-8.4.804000.20151116...
[9/9] Extracting compat8x-amd64-8.4.804000.20151116: 100%
Message from gcc8-8.3.0_2:

To ensure binaries built with this toolchain find appropriate versions
of the necessary run-time libraries, you may want to link using

  -Wl,-rpath=/usr/local/lib/gcc8

For ports leveraging USE_GCC, USES=compiler, or USES=fortran this happens
transparently.
Stack has been installed to: /home/zie/.local/bin/stack
Using stack Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64
Compiled with:
- Cabal-2.4.0.1
- Glob-0.9.2
- StateVar-1.1.1.1
- aeson-1.2.4.0
- aeson-compat-0.3.8
- annotated-wl-pprint-0.7.0
- ansi-terminal-0.9
- ansi-wl-pprint-0.6.8.2
- array-0.5.2.0
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.1.1
- attoparsec-0.13.2.2
- attoparsec-iso8601-1.0.0.0
- auto-update-0.1.4
- base-4.10.1.0
- base-compat-0.9.3
- base-orphans-0.7
- base-prelude-1.2.1
- base16-bytestring-0.1.1.6
- base64-bytestring-1.0.0.1
- basement-0.0.8
- bifunctors-5.5.3
- binary-0.8.5.1
- bitarray-0.0.1.1
- blaze-builder-0.4.1.0
- blaze-html-0.9.1.1
- blaze-markup-0.8.2.1
- byteable-0.1.1
- bytestring-0.10.8.2
- case-insensitive-1.2.0.11
- cereal-0.5.7.0
- clock-0.7.2
- colour-2.3.4
- comonad-5.0.4
- conduit-1.3.0.3
- conduit-combinators-1.3.0
- conduit-extra-1.3.0
- connection-0.2.8
- containers-0.5.10.2
- contravariant-1.4.1
- cookie-0.4.4
- cryptohash-sha256-0.11.101.0
- cryptonite-0.25
- cryptonite-conduit-0.2.2
- data-default-class-0.1.2.0
- deepseq-1.4.3.0
- digest-0.0.1.2
- directory-1.3.0.2
- distributive-0.5.3
- dlist-0.8.0.4
- easy-file-0.2.2
- echo-0.1.3
- ed25519-0.0.5.0
- either-5.0.1
- exceptions-0.8.3
- extra-1.6.9
- fast-logger-2.4.11
- file-embed-0.0.10.1
- filelock-0.1.1.2
- filepath-1.4.1.2
- foundation-0.0.21
- fsnotify-0.3.0.1
- generic-deriving-1.12.2
- ghc-boot-th-8.2.2
- ghc-prim-0.5.1.1
- githash-0.1.3.0
- gitrev-1.3.1
- hackage-security-0.5.3.0
- hashable-1.2.7.0
- hi-file-parser-0.1.0.0
- hourglass-0.2.11
- hpack-0.31.2
- hpc-0.6.0.3
- http-api-data-0.3.8.1
- http-client-0.5.13.1
- http-client-tls-0.3.5.3
- http-conduit-2.3.2
- http-download-0.1.0.0
- http-types-0.12.1
- infer-license-0.2.0
- integer-gmp-1.0.1.0
- integer-logarithms-1.0.2.1
- lifted-base-0.2.3.12
- memory-0.14.16
- microlens-0.4.8.3
- microlens-th-0.4.1.3
- mime-types-0.1.0.8
- mintty-0.1.2
- monad-control-1.0.2.3
- monad-logger-0.3.29
- monad-loops-0.4.3
- mono-traversable-1.0.9.0
- mtl-2.2.2
- mustache-2.3.0
- neat-interpolation-0.3.2.1
- network-2.6.3.6
- network-uri-2.6.1.0
- old-locale-1.0.0.7
- old-time-1.1.0.3
- open-browser-0.2.1.0
- optparse-applicative-0.14.2.0
- optparse-simple-0.1.0
- pantry-0.1.1.0
- parsec-3.1.13.0
- path-0.6.1
- path-io-1.3.3
- path-pieces-0.2.1
- pem-0.2.4
- persistent-2.9.2
- persistent-sqlite-2.9.3
- persistent-template-2.5.4
- pretty-1.1.3.3
- primitive-0.6.4.0
- process-1.6.3.0
- profunctors-5.2.2
- project-template-0.2.0.1
- random-1.1
- regex-applicative-0.3.3
- regex-applicative-text-0.1.0.1
- resource-pool-0.2.3.2
- resourcet-1.2.1
- retry-0.7.6.3
- rio-0.1.10.0
- rio-orphans-0.1.1.0
- rio-prettyprint-0.1.0.0
- rts-1.0
- safe-0.3.17
- safe-exceptions-0.1.7.0
- scientific-0.3.6.2
- semigroupoids-5.2.2
- semigroups-0.18.5
- silently-1.2.5
- socks-0.5.6
- split-0.2.3.3
- stm-2.4.5.0
- stm-chans-3.0.0.4
- streaming-commons-0.1.19
- syb-0.7
- tagged-0.8.6
- tar-0.5.1.0
- tar-conduit-0.3.0
- template-haskell-2.12.0.0
- temporary-1.2.1.1
- terminal-size-0.3.2.1
- text-1.2.3.0
- text-metrics-0.3.0
- th-abstraction-0.2.8.0
- th-expand-syns-0.4.4.0
- th-lift-0.7.10
- th-lift-instances-0.1.11
- th-orphans-0.13.6
- th-reify-many-0.1.8
- th-utilities-0.2.0.1
- time-1.8.0.2
- time-locale-compat-0.1.1.4
- tls-1.4.1
- transformers-0.5.2.0
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- typed-process-0.2.6.0
- unicode-transforms-0.3.4
- unix-2.7.2.2
- unix-compat-0.5.0.1
- unix-time-0.3.8
- unliftio-0.2.8.0
- unliftio-core-0.1.1.0
- unordered-containers-0.2.9.0
- uri-bytestring-0.3.2.0
- uuid-types-1.0.3
- vector-0.12.0.1
- vector-algorithms-0.7.0.1
- void-0.7.2
- x509-1.7.3
- x509-store-1.6.6
- x509-system-1.6.6
- x509-validation-1.6.10
- yaml-0.10.4.0
- zip-archive-0.3.3
- zlib-0.6.2

Warning: this is an unsupported build that may use different versions of
dependencies and GHC than the officially released binaries, and therefore may
not behave identically.  If you encounter problems, please try the latest
official build by running 'stack upgrade --force-download'.

Installing hledger packages:
Installing hledger
Trying stack install --install-ghc --resolver=nightly-2019-03-09 hledger-1.14.2 hledger-lib-1.14.1 brick-0.46 text-zipper-0.10.1 config-ini-0.2.4.0 data-clist-0.1.2.2 word-wrap-0.4.1 --verbosity=info
Writing implicit global project config file to: /usr/home/zie/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using resolver: nightly-2019-03-09 specified on command line
Preparing to install GHC (ino64) to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-ino64-8.6.4.
rts-1.0: Warning: .:458:1: The field "hugs-options" is deprecated. hugs isn't supported anymore
Installed GHC.
Found an invalid compiler at "/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/ghc-8.6.4": Control.Exception.Safe.throwString called with:

Could not find any of: ["/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc"]
Called from:
  throwString (src/Stack/Setup.hs:721:25 in stack-2.1.3-GXj9L9IkaWo2XtPwJQo3Zk:Stack.Setup)


Installing hledger-ui
Trying stack install --install-ghc --resolver=nightly-2019-03-09 hledger-ui-1.14.1 hledger-1.14.2 hledger-lib-1.14.1 brick-0.46 text-zipper-0.10.1 config-ini-0.2.4.0 data-clist-0.1.2.2 word-wrap-0.4.1 --verbosity=info
Found an invalid compiler at "/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/ghc-8.6.4": Control.Exception.Safe.throwString called with:

Could not find any of: ["/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc"]
Called from:
  throwString (src/Stack/Setup.hs:721:25 in stack-2.1.3-GXj9L9IkaWo2XtPwJQo3Zk:Stack.Setup)


Installing hledger-web
Trying stack install --install-ghc --resolver=nightly-2019-03-09 hledger-web-1.14.1 hledger-1.14.2 hledger-lib-1.14.1 brick-0.46 text-zipper-0.10.1 config-ini-0.2.4.0 data-clist-0.1.2.2 word-wrap-0.4.1 --verbosity=info
Found an invalid compiler at "/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/ghc-8.6.4": Control.Exception.Safe.throwString called with:

Could not find any of: ["/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc"]
Called from:
  throwString (src/Stack/Setup.hs:721:25 in stack-2.1.3-GXj9L9IkaWo2XtPwJQo3Zk:Stack.Setup)


Installing hledger-api
Trying stack install --install-ghc --resolver=nightly-2019-03-09 hledger-api-1.14 hledger-1.14.2 hledger-lib-1.14.1 brick-0.46 text-zipper-0.10.1 config-ini-0.2.4.0 data-clist-0.1.2.2 word-wrap-0.4.1 --verbosity=info
Found an invalid compiler at "/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/ghc-8.6.4": Control.Exception.Safe.throwString called with:

Could not find any of: ["/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc"]
Called from:
  throwString (src/Stack/Setup.hs:721:25 in stack-2.1.3-GXj9L9IkaWo2XtPwJQo3Zk:Stack.Setup)


Installing hledger-iadd
Trying stack install --install-ghc --resolver=nightly-2019-03-09 hledger-iadd-1.3.9 hledger-lib-1.14.1 brick-0.46 text-zipper-0.10.1 config-ini-0.2.4.0 data-clist-0.1.2.2 word-wrap-0.4.1 --verbosity=info
Found an invalid compiler at "/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/ghc-8.6.4": Control.Exception.Safe.throwString called with:

Could not find any of: ["/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc"]
Called from:
  throwString (src/Stack/Setup.hs:721:25 in stack-2.1.3-GXj9L9IkaWo2XtPwJQo3Zk:Stack.Setup)


Installing hledger-interest
Trying stack install --install-ghc --resolver=nightly-2019-03-09 hledger-interest-1.5.3 hledger-lib-1.14.1 brick-0.46 text-zipper-0.10.1 config-ini-0.2.4.0 data-clist-0.1.2.2 word-wrap-0.4.1 --verbosity=info
Found an invalid compiler at "/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/ghc-8.6.4": Control.Exception.Safe.throwString called with:

Could not find any of: ["/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc-8.6.4","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock","/usr/home/zie/.stack/programs/x86_64-freebsd/ghc-ino64-8.6.4/bin/haddock-ghc"]
Called from:
  throwString (src/Stack/Setup.hs:721:25 in stack-2.1.3-GXj9L9IkaWo2XtPwJQo3Zk:Stack.Setup)



Install status after:
hledger is not found
hledger-ui is not found
hledger-web is not found
hledger-api is not found
hledger-iadd is not found
hledger-interest is not found
hledger-install.sh is not found

**Comment by zieone** [comment]
on freeBSD proper, same issue. I think the installer script needs to use 8.6.5: https://builds.sr.ht/~zie/job/79662

Tried with 8.6.5 on fbsd proper:
```
Trying stack install --install-ghc --resolver=lts-13.27 hledger-1.14.2 hledger-lib-1.14.1 brick-0.46 text-zipper-0.10.1 config-ini-0.2.4.0 data-cl$
st-0.1.2.2 word-wrap-0.4.1 --verbosity=info
hledger> configure
hledger> Configuring hledger-1.14.2...
hledger> build
hledger> Preprocessing library for hledger-1.14.2..
hledger> Building library for hledger-1.14.2..
hledger> [ 1 of 33] Compiling Hledger.Cli.DocFiles
hledger>
hledger> /tmp/stack79237/hledger-1.14.2/Hledger/Cli/DocFiles.hs:42:6: error:
hledger>     * Exception when trying to run compile-time code:
hledger>         /tmp/stack79237/hledger-1.14.2/embeddedfiles/hledger.1: hGetContents: invalid argument (invalid byte sequence)
hledger>       Code: embedFileRelative "embeddedfiles/hledger.1"
hledger>     * In the untyped splice:
hledger>         $(embedFileRelative "embeddedfiles/hledger.1")
hledger>    |
hledger> 42 |     ($(embedFileRelative "embeddedfiles/hledger.1")
hledger>    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
hledger>

--  While building package hledger-1.14.2 using:
      /usr/home/zie/.stack/setup-exe-cache/x86_64-freebsd-ino64/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-freeb$
d-ino64/Cabal-2.4.0.1 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

**Comment by simonmichael** [comment]
Thanks for working on this. Looks like progress. That kind of error sometimes is due to an unconfigured locale, see discussion somewhere in the manual (in “troubleshooting” IIRC).

**Comment by zieone** [comment]
Woohoo! :) So it's working now, but you have to change the resolver to 8.6.5(i.e. `--resolver=lts-13.27`)

@simonmichael Do you want a PR for the resolver change?  It's in my copy obviously, since that's where I'm pulling from for this to run.  I haven't tested the resolver change against any other platforms however.

```
$ uname -a
FreeBSD userfbsd 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  amd64
$ export LANG=en_US.UTF-8
$ curl -sSL https://github.com/zieone/hledger/raw/master/hledger-install/hledger-install.sh | bash
<CUT>
Install status after:
hledger 1.14.2 is installed at /home/craig/.local/bin/hledger
hledger-ui 1.14.1 is installed at /home/craig/.local/bin/hledger-ui
hledger-web 1.14.1 is installed at /home/craig/.local/bin/hledger-web
hledger-api 1.14 is installed at /home/craig/.local/bin/hledger-api
hledger-iadd 1.3.9 is installed at /home/craig/.local/bin/hledger-iadd
hledger-interest 1.5.3 is installed at /home/craig/.local/bin/hledger-interest
$ hledger test
<cut>
  198 tests passead, no failures! 👍 🎉
```

**Comment by simonmichael** [comment]
Sounds good! The stack.yaml file in current master should be an up to date reference if needed.

**Comment by zieone** [comment]
OK if I run with `--resolver=nightly-2019-07-26`, then I get QuickCheck problems.
and hledger-api wants QuickCheck-2.13.2, but the rest of hledger wants QuickCheck-2.12.6.1
So there is an incompatibility there.  These errors are above my haskell knowledge.

to replicate my issue a diff from hledger-install.sh @ head (commit: 8aac6f80bb42437548f7146bee05a72fa7c9ea94)

```
$ diff hledger-install.sh hledger-install-zie.sh
59c59
< RESOLVER="--resolver=nightly-2019-03-09"
---
> RESOLVER="--resolver=nightly-2019-07-26"
91a92
> QuickCheck-2.12.6.1 \
```

Applying this diff will get you everything but hledger-api.

**Comment by simonmichael** [comment]
The hledger-install.sh in master now should work on FreeBSD. If not, please let me know.
