### ISSUE TITLE
hledger sets `nix enabled` to false by default

### ISSUE THREAD

**Issue by cdepillabout** [simonmichael/hledger#712]
The `stack.yaml` file in the root of the repo sets `nix.enabled` to [`false`](https://github.com/simonmichael/hledger/blob/master/stack.yaml#L6).

This makes builds on NixOS fail by default.

Normally, to use stack on NixOS, you add [`nix.enabled`](https://docs.haskellstack.org/en/stable/nix_integration/#additions-to-your-stackyaml) to `~/.stack/config.yaml`.  However, with `nix.enabled` set to `false` in hledger's `stack.yaml`, the settings in `~/.stack/config.yaml` are ignored.

Ideally, `nix.enabled` would not be set in hledger's `stack.yaml` file so that `stack` would fall back to the `nix.enabled` setting specified in `~/.stack/config.yaml`.

**Comment by simonmichael** [comment]
Thanks for the report. @efx, any thoughts ? I'm not finding discussion of 6bd86f9.

**Comment by simonmichael** [comment]
I assume this affects http://hledger.org/download.html -> B, C but not A.

**Comment by cdepillabout** [comment]
I think it was added [here](https://github.com/simonmichael/hledger/pull/671), but there doesn't seem to be any discussion as to why `nix.enabled` is set to `false` (instead of just not specified).

**Comment by efx** [comment]
IIRC, we set this to false so that the stack installer wouldn't default to using nix, but you could opt in. based on what @cdepillabout points out, I think it is safe to remove and just document that preferred approach:
> Ideally, nix.enabled would not be set in hledger's stack.yaml file so that stack would fall back to the nix.enabled setting specified in ~/.stack/config.yaml.

**Comment by simonmichael** [comment]
What docs are needed ? What were the circumstances under which stack installer would default to using nix ?

**Comment by efx** [comment]
Maybe they are not needed. I think you need to have the nix enabled set to true in your per user stack config. Otherwise, you have to pass `--nix` to `stack install` for it to be enabled.

**Comment by simonmichael** [comment]
Ok, the current PR sounds good to me. Thanks!
