### ISSUE TITLE
default-commodity directive does not limit display precision

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#716]
A bug noticed by @ony in #706 PR. The [default commodity directive](http://hledger.org/manual.html#default-commodity), as well as adding a commodity to commodity-less amounts, is supposed to set that commodity's display style, like a [commodity directive](http://hledger.org/manual.html#commodity-directive) would. This works, except it does not limit the display precision:

```hledger
#!/usr/bin/env hledger bal -N -f

# commodity directive, does limit to two decimal places
#commodity 1,000.00

# default commodity directive (re-applying the no-symbol commodity for simplicity; same thing happens with a symbol)
# does apply the thousands separator, does increase to four decimal places
#D 1,000.0000

# does not limit to two decimal places
D 1,000.00

2018/1/1
  (a)  1000.123
```

**Comment by simonmichael** [comment]
Related: the overlap in these two directives can be confusing. When we enable strict checking for declared commodities, will `D` also be allowed to declare a commodity ? Another overlap.
We could change `D` so that all it can do is specify a commodity symbol to add, and use only `commodity` for setting display style. Eg:
```hledger
D $
commodity $1,000.00
```
This is simpler and easier to learn. But also less compatible with Ledger's file format. To preserve maximum compatibility, we could also accept the old form, `D $1,000.00`, but ignore everything but the symbol in such a case.

**Comment by Xitian9** [comment]
I think it does this now, and this can be closed.
