### ISSUE TITLE
hledger timer

### ISSUE THREAD

**Issue by dawei-dev** [simonmichael/hledger#720]
I use hledger for time management. Is there already a hledger timer tool to track time? By this I mean:

The workflow I imagine:

1: I type hledger start

2: I do my stuff

3: I Ctrl+C to stop the task

4: hledger prompts me for task description with elapsed time already registered.

**Comment by simonmichael** [comment]
I was going to say no, but I looked at http://plaintextaccounting.org/#time-logging and saw eg tim. Let us know what you find.

I keep a drop-down window for editing a timedot file, which I find a little less distracting than clocking in and out.

**Comment by dawei-dev** [comment]
Thanks for the quick feedback.
https://github.com/MatthiasKauer/tim is sufficient for me.
