### ISSUE TITLE
Sorting by account codes isn't working with single-column balance report

### ISSUE THREAD

**Issue by danielverdugo** [simonmichael/hledger#727]
For example, let's write the following directives:
```
account Equity  3000
account Assets  4000
```

Then enter some transactions. Enter in the Terminal window: `hledger -f covfefe.journal b`

Output:
```
          7,081.65 ₽  Assets
         -7,081.65 ₽  Equity
--------------------
                   0
```

So, sorting by code haven't worked.

In the `--monthly` mode, however:
```
        ||         Mar 
========++=============
 Equity || -7,081.65 ₽ 
 Assets ||  7,081.65 ₽ 
--------++-------------
        ||           0 
```

**Comment by simonmichael** [comment]
Thanks! Test added, patches welcome.

**Comment by legrostdg** [comment]
I've investigated a little further. The order seems right for the top accounts, but it goes wrong for subaccounts. Subaccounts with subaccounts are always sorted after subaccounts without subaccounts...

So, given this `test.journal`:

```
account 2.a
account 2.a:1.c:0.d
account 2.a:2.e
account 2.a:3.f
account 1.b

2020/01/01 bla
    1.b          -3
    2.a:2.e      +1
    2.a:1.c:0.d  +1
    2.a:3.f      +1
```

`hledger b --file test.journal` returns:

```
$ hledger b --file ~/test.journal 
                   3  2.a
                   1    2.e
                   1    3.f
                   1    1.c:0.d
                  -3  1.b
--------------------
                   0
```

I guess there's something wrong in the recursion of `sortAccountTreeByDeclaration` in `hledger-lib/Hledger/Data/Account.hs`...

**Comment by simonmichael** [comment]
Since account codes are no longer supported, can we just close this ?

**Comment by legrostdg** [comment]
I guess I did not read the bug report well, so maybe we can close this, but there still is a bug. Do you want me to open a new one with my previous message?

**Comment by legrostdg** [comment]
I opened https://github.com/simonmichael/hledger/issues/1218, feel free to close this one.
