### ISSUE TITLE
`hledger-chart` should not use pie charts

### ISSUE THREAD

**Issue by taktoa** [simonmichael/hledger#733]
Pie charts are extremely misleading because the [psychophysical power constant](https://en.wikipedia.org/wiki/Stevens%27s_power_law) for visual area is 0.7; so if you show someone a pie chart, they will systematically estimate the ratio between two pie slices as `R^0.7` if the actual ratio is `R`. A much better way to display percentages of a whole is to use a bunch of stacked lines (e.g.: a stacked bar chart), since the psychophysical power constant for visual length is 1.

**Comment by simonmichael** [comment]
The hledger-chart package is deprecated. But better charts (somewhere) would be very welcome. hledger-web has a chart, and more could be added. Also, it would be nice to add charts support to hledger CLI (separate from, or part of, HTML output format).

**Comment by varac** [comment]
I'd love to have bar charts in hledger-web, maybe it's already possible but I haven't found how to do it.
Right now when I'm filtering for i.e. an income account, I see a chart which displays the cummulative value over time, I'd love to have a bar chart which displays my monthly income over time.

**Comment by simonmichael** [comment]
Agreed. It's not a feature of current hledger-web. As always, it would be great if someone has time to work on it. My personal prioritisation involves making simple bar charts for the CLI first. But for today, the way to make bar charts is to export a balance report as CSV, drag that into a spreadsheet and use the graphing tools there.

**Comment by simonmichael** [comment]
PS closing this specific issue, as [hledger-chart](http://hackage.haskell.org/package/hledger-chart) is long retired.
