### ISSUE TITLE
retire hakyll-std/reduce hakyll & pandoc dependency

### ISSUE THREAD

**Issue by ehildenb** [simonmichael/hledger#744]
In PR https://github.com/simonmichael/hledger/pull/740 there are references to phasing out Hakyll std, or at least parts of it. In the file `site/hakyll-std/hakyll-std.hs` it also mentions that it should go away.

@simonmichael How are we interested in doing that? Do we want to completely remove Hakyll as a dependency, or just remove a site-specific build file `hakyll-std` (I'm not super familiar with Hakyll, so am not sure if this is possible)? If we remove Hakyll as a dependency, will the site be built with manual calls to `pandoc` instead?

**Comment by simonmichael** [comment]
Looks like our comments crossed! Quite interested! Yes it seems like we could do everything needed with Shake and pandoc and so I would love to get rid of hakyll and especially hakyll-std entirely.

**Comment by ehildenb** [comment]
Alright, my plan is to migrate things over to the Shake file in a series of commits. First the file-copying stuff that Hakyll is doing. The hard part will be the `relativizeUrls` function that Hakyll provides. We can either:

1.   Keep importing the `relativizeUrls :: String -> String -> String` function that Hakyll provides. Still have dependence on Hakyll in the Shake file then.
2.   Write our own relativizeUrls either as a standalone Haskell function, or as a Pandoc Lua filter.
3.   Just make sure all the URLS on the website are already relativized in the original markdown.

Which would you prefer?

**Comment by simonmichael** [comment]
I'd prefer to not depend on hakyll or pandoc (in source form) at all, as they take forever to build and tend to have upgrade issues. Re urls, I'm in favour of the simplest thing that could possibly work, not sure how much of a problem this will be, let's test with one page maybe.

**Comment by simonmichael** [comment]
Though it does depend on pandoc source, http://hackage.haskell.org/package/pansite looks like it might be worth a look..

**Comment by simonmichael** [comment]
Actually that's a web app, and probably too new. Never mind.

**Comment by ehildenb** [comment]
Not sure depending on Pandoc source is the problem, as much as invoking `stack exec ghc -- --package pandoc`, which causes rebuilds every time. I think it it's installed with the stack file directly it shouldn't cause rebuilts of Pandoc when we change things that involve Pandoc. Not sure though, not super familiar with stack.

Either way, I'm not opposed to depending on Pandoc sources, I think some interesting things in terms of generating/building reports can be done that way. Actually that was the original reason I searched "Pandoc HLedger", leading me to these issues I've been working on (as a way to get familiar with the code).

Anyway, progress on this:

1.   All uses of `Blaze` were removed from `TableOfContents.hs`, in favor of staying in pure Pandoc data-structures; `relativizeUrls` is called directly as part of `TableOfContents` instead of `hakyll-std`.
2.   The file copying that `hakyll-std` was doing was replaced with calls in the `./Shake.hs` file.
3.   The new `TableOfContents.hs` is copied (with small modifications) to `tools/pandoc-site.hs` as a Pandoc filter.
4.   The `./Shake.hs` script invokes pandoc directly on the generated HTML targets, using the `tools/pandoc-site.hs` filter.

I'm running tests to make sure the documentation is built entirely the same after the changes, will probably have a PR ready by early/mid next week.

Rebuild times are much better now. The reason I removed uses of `Blaze` in the Pandoc filter is because I want to make it easier to eventually turn `tools/pandoc-site.hs` into a Lua filter (where Blaze won't be available).

**Comment by ehildenb** [comment]
#755 has addressed this partly. Continuing the discussion from there here to keep in one place.

> Can you add a module doc to pandoc-site.hs summarising what it does.
> Is the "from https://github.com/blaenk/blaenk.github.io" comment still accurate ?
> Perhaps we can avoid adding site-building deps to stack-ghc8.2.yaml, which forces a slow pandoc build on folks trying to build hledger with it.

I still plan on replacing this Haskell pandoc filter with a Lua filter, just wanted to get this in so that we have confirmation that the Hakyll-less build is doing things correctly before going all the way to Lua.

I'll add a module doc to `pandoc-site.hs` explaining what it does, then migrate that over to the Lua code as well when the transition occurs. Not sure if that URL is still accurate, but it certainly won't be after migrating to Lua.

Also after migrating to Lua, we won't be needing `stack-ghc8.2.yaml` for compiling the site anymore at all, so that issue should go away as well.

**Comment by simonmichael** [comment]
Cool, no big deal then. And we can drop the blaenk link.

**Comment by Xitian9** [comment]
Since Hakyll has gone, and the website has been through significant changes in the last 3 years, perhaps this issue can be closed?
