### ISSUE TITLE
Feature request: Register command csv output should have "code" field

### ISSUE THREAD

**Issue by imprest** [simonmichael/hledger#746]
Hi Simon, 
Feature request: 
is it possible to output the "code" field in the register cmd csv output?

> hledger register Cash -Ocsv
> "txnidx","date","code"...

Keep up the good work and thank you.

**Comment by simonmichael** [comment]
Thanks @imprest. code is really a transaction field, it appears in print's CSV output. In register's, it will be the same for all postings in a transaction. Is this useful ?

**Comment by imprest** [comment]
I was using code for cheque and voucher # references so was hoping I could get register output like this
Assets:Bank
2017-01-01, "                ", Opening Balances, Assets:Bank,  10, 10
2017-01-02, chq 123456, Payment               , Assets:Bank, -10,   0 
2017-01-02, chq 623451, Income                  , Assets:Bank,  20, 20

Current work around is to use print command and edit statement accordingly;
Else do you advise I should just put that info. in the description field.

Thanks for the quick reply.

**Comment by simonmichael** [comment]
I've added it.

**Comment by imprest** [comment]
🧡 🙏
