### ISSUE TITLE
Add screenshots for hledger-ui

### ISSUE THREAD

**Issue by ChShersh** [simonmichael/hledger#763]
I really would like to see `hledger` UI before starting to use it. But I don't see screenshots of UI neither in README nor on hledger.org website. Could you please add some screenshots or guide me to them if they are already exist somewhere (and ideally make them easier to use)?

Somewhat relevant to #448

**Comment by simonmichael** [comment]
Thanks for the report, but I see 6 screenshots down the right side of the hledger-ui manual (web version), and one on the What is hledger? page. If you don't, what browser version are you using ?
http://hledger.org/hledger.html
http://hledger.org/intro.html

**Comment by simonmichael** [comment]
http://hledger.org/hledger-ui.html, I mean

**Comment by ChShersh** [comment]
@simonmichael Thanks a lot! I just wasn't able to find screenshots. But now I see all them. Btw, looks cool :+1: Maybe it's a good idea to put couple screenshots to the main page (either from web-version or from terminal UI). But this totally resolves my issue, so feel free to close it!

**Comment by simonmichael** [comment]
The /intro content was on the home page until recently, but now that space is given to the docs. Feel free to propose a new home page layout with screenshots that's still effective.

**Comment by simonmichael** [comment]
(Closing for now.)
