### ISSUE TITLE
GHC 7.10 compatibility has broken

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#775]
`stack build --stack-yaml=stack-ghc7.10.3.yaml` fails, currently due to use of megaparsec 6's notChar. To get it working means backporting that to megaparsec 5.3.1, or finding an install plan for megaparsec 6+ with lts-6.35 if any. Or we can drop support for GHC 7.10. Would this limit our availability anywhere significant ?

**Comment by awjchen** [comment]
Sorry, introducing `notChar` without checking for backwards compatibility is my bad. I think we should just define `notChar c = satisfy (/= c)` for ourselves where we use it.

**Comment by simonmichael** [comment]
Aha. I tried that but failed, if it’s easy perhaps we should. Debian stable is up to Ghc 8.0 though.

**Comment by awjchen** [comment]
Yes, I've been terrible with backwards compatibility, and being able to use a single version of megaparsec would be great!

**Comment by simonmichael** [comment]
Resolved.
