### ISSUE TITLE
Restricting the syntax for posting dates

### ISSUE THREAD

**Issue by awjchen** [simonmichael/hledger#778]
I am wondering whether we should restrict the allowed syntax for tags, date tags, and bracketed dates of posting comments.

I don't see any problem with the intended usage of date tags and bracketed dates. But, when the syntax for bracketed dates are mixed with tags and date tags, there are currently some obscure possibilities that parse in strange ways. I'm not really sure how the following examples would arise in practice, but it might be nice to tighten up the syntax anyway.

On the current master branch:
```
> stack ghci hledger-lib
ghci> :set -XOverloadedStrings
ghci> import qualified Data.Text as T
ghci> day <- getCurrentDay
ghci> day
2018-05-17
ghci> let parseComment txt = rejp (followingcommentandtagsp (Just day)) txt >>= putStrLn . either id (\(_, tags, date1, date2) -> "Tags:\n" ++ unlines (fmap (\(name, value) -> "  " ++ T.unpack name ++ " -- " ++ T.unpack value) tags) ++ "date1: " ++ show date1 ++ "\ndate2: " ++ show date2)

ghci> parseComment "; tagName: [checklist] [1 / 3]" -- 1a
Tags:
  tagName -- [checklist] [1 / 3]
date1: Nothing
date2: Nothing

ghci> parseComment "; tagName: [checklist] [1/3]" -- 1b
Tags:
  tagName -- [checklist] [1/3]
date1: Just 2018-01-03
date2: Nothing


ghci> parseComment "; date:2018/05/17, [2000/01/01=01/02]" -- 2
Tags:
  date -- 2018/05/17
date1: Just 2018-05-17
date2: Just 2000-01-02


ghci> parseComment "; [ date:2000/01/01 ]" -- 3a
Tags:
  date -- 2000/01/01 ]
date1: Just 2000-01-01
date2: Nothing

ghci> parseComment "; [date:2000/01/01]" -- 3b
Tags:
  [date -- 2000/01/01]
date1: Nothing
date2: Nothing
```

(1) Perhaps the user is accustomed to using brackets in their comments, and eventually come to believe that tag values cannot hold date values by successfully using (1a). In some future journal, the same comment, but this time without spaces, suddenly adds a random date to the transaction. 

(2) Both syntaxes are used to give date pairs, but the result is neither of the given pairs; the pair of (bracketed) dates has been only partially overwritten by the date tag.

(3) In (3a), The date parses correctly, but the date tag has a trailing trailing ']'. Without spaces (3b), the date no longer works.

**Comment by awjchen** [comment]
I was hoping that we could make a change to the syntax, but I suppose that any restriction of the syntax could potentially break someone's journal. Furthermore, if a journal did break it could be very tedious to fix. So perhaps there's not much we can do.

If we indeed can't do anything to the syntax, it's no big deal. The examples I came up with are pretty contrived. I feel that it should be enough to put in the docs a recommendation to avoid the use of square brackets except for posting dates. Perhaps even that is unnecessary?

Alternatively, it might be reasonable to change our bracketed date parser to match ledger's, since it's _supposed_ to be a clone of theirs. How does their parser work?

**Comment by simonmichael** [comment]
@awjchen that is always hard to answer. I started to search docs and test it but got busy elsewhere. "supposed" is the right word. I was going to say, one easy way to simplify is drop the bracketed syntax. We can make whatever changes we want, as long as we assess their impact (eg by discussing on the mail list) and feel that it's acceptable.

**Comment by simonmichael** [comment]
Though, if it ain't obviously broke don't "fix" it..

It might be worth asking the hledger and ledger lists to see if we can find anyone using bracketed dates.

**Comment by tbm** [comment]
@simonmichael (raised this on the ledger list](https://groups.google.com/forum/#!topic/ledger-cli/ZLMUdhFsJuA).

**Comment by awjchen** [comment]
From the responses so far, it seems like removing bracketed date syntax completely is off the table.

Suspending for the moment any concerns about breaking journals or my inexpertise, I would personally like to restrict the syntax for date tags and bracketed dates as much as possible. For example,
1. I would stipulate that the date (and the secondary date) could only be specified once in a posting.
1. I would have it so that any pair of square brackets (`[...]`) is parsed as a bracketed date, eschewing the heuristic we currently use to prevent the parsing of non-dates within square brackets and instead opting to throw a parse error.
1. Perhaps too restrictively, I would try to reserve the `[` and `]` characters specifically for bracketed dates, for example, throwing an error on encountering unmatched brackets.

Unfortunately, I'm not sure how feasible it is to add such rules without breaking journals. An alternative might be to raise warnings about violations of these rules, and maybe only on the user's request.

**Comment by simonmichael** [comment]
1. agreed. 
2. and 3. since we are existing within a freeform comment field and brackets are pretty commonly used for other things, I think we really have to be lenient with them. After all, usually a comment delimiter means "anything goes" and we are cheating a bit by keeping structured data in there. It could be annoying to upgrade and find journals valid for years suddenly breaking, for a feature you might not use or care about.

**Comment by simonmichael** [comment]
However, we do need to add a strict mode, and this could be one of the things checked in that mode. Though is there an actual real-world need driving this ?

**Comment by simonmichael** [comment]
Even 1 is debatable - you could argue that nothing in a comment should be allowed to break parsing, though that's not our current situation (eg date: not followed by a date breaks). It's not actually a comment field, it's sort of half comment half structured data right now.

**Comment by awjchen** [comment]
> However, we do need to add a strict mode, and this could be one of the things checked in that mode. Though is there an actual real-world need driving this ?

I have also been wondering about whether these changes are really needed. While the current syntax allows for some strange things, those things are far enough removed from the regular use of the syntax to be of little concern. I see that the benefit of these changes are dwarfed by the cost of introducing a breaking change to the existing syntax.

I was motivated by the desire to be able to know with certainty that a journal was free of (certain kinds of) errors without having to think, just to catch silly mistakes. An optional strict mode sounds like a good way to achieve this without breaking anything.

I still do feel that my 1st wish for a rule is quite natural, even if it may not be a frequent concern, since it is unlikely that someone would intentionally provide two dates so that one shadows the other; this lowers the chance of breaking existing journals. While I have a hard time imagining how rules 2 and 3 would help, I can see myself accidently edit a `date2` into a `date`, or accidently inserting a date (e.g. unknowingly pressing '.' or 'p' in vim), causing a silent error.

**Comment by awjchen** [comment]
Do you think that restricting the parser to accept at most one date (and secondary date) per posting is a sufficiently benign and worthwhile change to bother the mailing list with a question?

**Comment by simonmichael** [comment]
You never have to worry about bothering the mailing list. It's the best place to discuss anything or interest to the community, small or large - go for it.

**Comment by simonmichael** [comment]
I don't care about this issue, but I'll gladly merge any PRs to tighten up parsing of posting dates. Closing for now.
