### ISSUE TITLE
Use megaparsec 6 for all supported versions of GHC

### ISSUE THREAD

**Issue by awjchen** [simonmichael/hledger#783]
I would like to use `megaparsec >=6.4.1` on all versions of GHC we support (7.10, 8.0, 8.2, 8.4).

I have verified that it is possible to do so just by adding `megaparsec-6.4.1` and `parser-combinators-0.4.0` to `stack-ghc7.10.yaml` and `stack-ghc8.0.yaml`. I have chosen version `6.4.1` in particular because it matches the version of megaparsec in the stackage resolver for `stack-ghc8.2.yaml`.

Using the same version of megaparsec on all supported versions of GHC would allow us to remove the megaparsec compatability module `/hledger-lib/Text/Megaparsec/Compat.hs`, and relieve us of thinking about backwards compatibility when working on the parser. Furthermore, megaparsec 6 is supposed to have performance improvements through the use of new parsing primitives like `takeWhileP`, so we might also get some easy performance gains.

**Comment by simonmichael** [comment]
That sounds fine (I thought it was harder than that to support newer megaparsec with older stackage snapshots.) We might need the Compat module again in future, but it's ok to get rid of it for now. One possible downside is that requiring a very new megaparsec could somehow make life harder for distro packagers, delaying the packaging of new hledger versions on some distros. We should ask Clint (IRC) about this and maybe research the megaparsec packaging situation a bit on https://repology.org/.

**Comment by simonmichael** [comment]
I guess it's not on repology, and megaparsec 6.4.1 is in debian unstable, and stackage lts. It sounds good, go for it.

**Comment by awjchen** [comment]
Alright, I'll see what I can do!
