### ISSUE TITLE
journal ending with "end" keyword

### ISSUE THREAD

**Issue by oupala** [simonmichael/hledger#785]
I don't know why exactly, but all my journals are ending with the `end` keyword. It probably an old copy/paste from a tutorial or a documentation.

I updated Ubuntu, and hledger has been updated from version 0.26 to version 1.2.

I now have an error while parsing my journals:

> $ hledger balance -f my.journal 
> hledger: /home/user/Documents/my.journal:98:1:
> unexpected 'e'
> expecting end of input or transaction or directive

It seems that the reason is my journal is ending with the `end` keyword:

```
; journal created 2010-01-01 by hledger

; setting commodity to euro
D 1.000,00 €
; setting year to 2009
Y2009
; setting global account to something
account something

[...]

02/08 bill
  seller                                             65,00
  bank

end
```

Has anything changed in the journal syntax between version 0.26 and version 1.2?

**Comment by simonmichael** [comment]
Hi.. yes (see release notes). Your `account...end` pair is now spelled `apply account...end apply account`. I recommend running the current release, 1.9.1.

**Comment by oupala** [comment]
Thanks a lots @simonmichael for your answer. With your help, I have successfully fixed my journals.

It was however hard for me to find the release notes (for those who might be looking for them, they are on [hledger website](http://hledger.org/release-notes.html)). I was expecting to find release notes, in a `CHANGELOG.md` at the root of the git repository, or something like this.

And I know I should be running the last version (and I see that the version number is increasing very fast since version 1.0!), but I'm using the hledger version available on my distro (Ubuntu Bionic, or Debien Stretch). I don't know how easy it is to install a version not packaged by the distro (something not a .deb package).

**Comment by simonmichael** [comment]
> It was however hard for me to find the release notes (for those who might be looking for them, they are on hledger website <http://hledger.org/release-notes.html>). I was expecting to find release notes, in a CHANGELOG.md at the root of the git repository, or something like this.
> 

Thanks for the feedback @oupala. The master changelogs are one level down in hledger*/CHANGES, because each of those packages can be released independently. And these are summarised in the web-ready site/release-notes.md, kept with the other website content. At http://hledger.org <http://hledger.org/>, this is the first link under Reference. Ideas to improve discoverability are welcome.

> And I know I should be running the last version (and I see that the version number is increasing very fast since version 1.0!), but I'm using the hledger version available on my distro (Ubuntu Bionic, or Debien Stretch). I don't know how easy it is to install a version not packaged by the distro (something not a .deb package).
> 
It's supposed to be easy (by running a hledger-install script). You can find out more on the download page.

**Comment by oupala** [comment]
Ok, everything seem very clear now. I've seen that `doc/CHANGES` tells about other changelogs.

I close the issue, if you don't mind.

**Comment by simonmichael** [comment]
Great, thank you. More reports welcome.
