### ISSUE TITLE
hledger-lib is too new for hledger-irr when running the install script 

### ISSUE THREAD

**Issue by Walms** [simonmichael/hledger#787]
When running curl https://raw.githubusercontent.com/simonmichael/hledger/master/hledger-install/hledger-install.sh | bash

The following error is shown 

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for hledger-irr-0.1.1.13:
    hledger-lib-1.9.1 from stack configuration does not match >=1 && <1.6  (latest matching version is 1.5.1)
needed since hledger-irr is a build target.

Happens on Ubuntu 16.04 on two separate machines. 

https://pastebin.com/1QydvcdL

**Comment by simonmichael** [comment]
Thanks for the report. This broke recently as hledger-install.sh was changed to build all tools with the latest hledger-lib, which hledger-irr does not yet support. @nomeata, could hledger-irr upper bound be updated ?

**Comment by nomeata** [comment]
New version uploaded.

**Comment by simonmichael** [comment]
Thanks! Presumed fixed.
