### ISSUE TITLE
base-compat 0.10.x breaks hledger-lib build

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#794]
~~~
    Hledger/Read/Common.hs:725:62: error:
        Ambiguous occurrence ‘<>’
        It could refer to either ‘Sem.<>’,
                                 imported from ‘Prelude.Compat’ at Hledger/Read/Common.hs:97:1-39
                                 (and originally defined in ‘Data.Semigroup’)
                              or ‘Data.Monoid.<>’,
                                 imported from ‘Data.Monoid’ at Hledger/Read/Common.hs:110:1-18
~~~

**Comment by simonmichael** [comment]
Thanks! It looks like we missed this in https://github.com/simonmichael/hledger/pull/788. I thought I ran `make buildtest-all`, but it seems not. I guess we need to run this or similar as part of CI somehow, though that is already slow and disk-space-limited.

**Comment by peti** [comment]
It's possible that the base-compat 0.10.x version simply hadn't been released yet at the time you ran those tests.

**Comment by simonmichael** [comment]
Oh I see.. right. Or I just didn't have it installed, I don't think these tests force the latest version of deps. (Maybe they should, if they could..)

Separately, I guess this is a breakage caused by removal of upper bounds, and base-compat is a package where I should keep specifying upper bounds.

**Comment by simonmichael** [comment]
I'll merge this when I've verified make buildtest-all passes with base-compat-0.10.1 installed (or if you observe that before I do let me know).

**Comment by simonmichael** [comment]
Merged your and my changes, which should make us somewhat robustly build and doctest warning-free across the last four GHC versions again. Thanks!

**Comment by peti** [comment]
What shall we do about Hackage? I see two options:

1. Edit the version constraint of `base-compat` to `> 0.8.1 && < 10`.
2. Release the updated code as a new version.

**Comment by simonmichael** [comment]
Yes, perhaps I'll do a revision on 1.9.1 at least, adding the upper bound on base-compat. I have been resisting spending brain cycles on a minor release.

**Comment by simonmichael** [comment]
And also on [fsnotify](https://github.com/simonmichael/hledger/issues/797#issuecomment-394587766).

**Comment by simonmichael** [comment]
Done.

**Comment by simonmichael** [comment]
But this causes problems in stackage nightly (https://github.com/commercialhaskell/stackage/issues/3706). So I'll probably do a minor release of all packages soon.
