### ISSUE TITLE
Add *.info files to the Stack package

### ISSUE THREAD

**Issue by DamienCassou** [simonmichael/hledger#805]
It would be nice if installing through Stack would generate .info files. Currently, info files are generated automatically on-demand in a temporary directory which is inconvenient to use from Emacs (where all manuals are gathered).

**Comment by simonmichael** [comment]
It seems we stopped stack from doing this in [5cea120a](https://github.com/simonmichael/hledger/commit/5cea120a). Should we rethink this ? Although, they can be retrieved quickly this way:
```
~$ stack unpack hledger
Unpacked hledger-1.9.1 to /Users/simon/hledger-1.9.1/
~$ ls hledger-1.9.1/embeddedfiles/
hledger-api.1           hledger-web.1           hledger_csv.5           hledger_timeclock.5
hledger-api.info        hledger-web.info        hledger_csv.info        hledger_timeclock.info
hledger-api.txt         hledger-web.txt         hledger_csv.txt         hledger_timeclock.txt
hledger-ui.1            hledger.1               hledger_journal.5       hledger_timedot.5
hledger-ui.info         hledger.info            hledger_journal.info    hledger_timedot.info
hledger-ui.txt          hledger.txt             hledger_journal.txt     hledger_timedot.txt
```

**Comment by simonmichael** [comment]
Cc'ing @peti.

**Comment by DamienCassou** [comment]
I don't care about this issue anymore. If no one else cares, I suggest closing it.
