### ISSUE TITLE
Info files can't be added to the Info root

### ISSUE THREAD

**Issue by DamienCassou** [simonmichael/hledger#806]
For hledger.info to be added to the Info root node, something like this must be done on all info files:

```diff
diff -u /home/cassou/Documents/projects/ledger/hledger/hledger-1.9.1/hledger.info.bak /home/cassou/Documents/projects/ledger/hledger/hledger-1.9.1/hledger.info
--- a/hledger.info.bak	2018-06-08 16:35:36.244331263 +0200
+++ b/hledger.info	2018-06-08 16:29:09.730763422 +0200
@@ -1,5 +1,10 @@
 This is hledger.info, produced by makeinfo version 6.5 from stdin.
 
+INFO-DIR-SECTION User Applications
+START-INFO-DIR-ENTRY
+* HLedger: (hledger).           Command-Line Accounting
+END-INFO-DIR-ENTRY
+
 
 File: hledger.info,  Node: Top,  Next: EXAMPLES,  Up: (dir)

```

**Comment by DamienCassou** [comment]
I've been bitten by this again yesterday and wanted to report an issue. GitHub found out I already did 3 years ago :-). Can you please tell me what I should modify where? I will be happy to do a PR.

**Comment by simonmichael** [comment]
Thanks! 

The `infomanuals` recipe in Shake.hs is where info manuals are generated. You could add the extra text there.

But perhaps it's easier to add it in the manual source files - *.m4.md - wrapped in the `_info_` macro, similar to the `_web_` and `_man_` calls you'll see there.

**Comment by DamienCassou** [comment]
I'm currently blocked by #1565.

**Comment by DamienCassou** [comment]
I tried adding the following to hledger.m4.md:

```m4
_info_({{
INFO-DIR-SECTION User Applications
START-INFO-DIR-ENTRY
* HLedger: (hledger).           Command-Line Accounting
END-INFO-DIR-ENTRY
}})
```

The end result is not satisfying though:

```
-DIR-SECTION User Applications START-DIR-ENTRY * HLedger: (hledger).
Command-Line Accounting END-DIR-ENTRY
```

As you can see:
1. all lines got merged
2. the `INFO` word got eaten on every lines where it appears

I don't have plans to learn m4 anytime soon :-).

**Comment by simonmichael** [comment]
For the record, we renamed the INFO/MAN/WEB m4 flags to avoid clashes, and we found that to preserve newlines in multiline m4 macro arguments, it's necessary to call the macro once for each line of text (we have pandoc refilling paragraphs, which is good for visible text but also affects macro arguments). Eg:
```
_info_({{INFO-DIR-SECTION User Applications}})
_info_({{START-INFO-DIR-ENTRY}})
_info_({{* HLedger: (hledger).           Command-Line Accounting}})
_info_({{END-INFO-DIR-ENTRY}})
```

**Comment by DamienCassou** [comment]
PR #1585 got merged.
