### ISSUE TITLE
compilation fails on embedded manuals with locale set to C

### ISSUE THREAD

**Issue by zarybnicky** [simonmichael/hledger#813]
Since the last few commits, I've started having this error while trying to compile hledger:
```
    /home/inuits/hledger/hledger/Hledger/Cli/DocFiles.hs:58:6: error:
        * Exception when trying to run compile-time code:
            /home/inuits/hledger/hledger/embeddedfiles/hledger_journal.5: hGetContents: invalid argument (invalid byte sequence)
          Code: makeRelativeToProject "embeddedfiles/hledger_journal.5"
                  >>= embedStringFile
        * In the untyped splice:
            $(makeRelativeToProject "embeddedfiles/hledger_journal.5"
                >>= embedStringFile)
       |
    58 |     ($(makeRelativeToProject "embeddedfiles/hledger_journal.5" >>= embedStringFile)
       |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Digging into it further, I've found several non-ASCII characters in *.m4.md files. AFAIK, having non-ASCII in man or info pages means that they are non-portable (even though most modern Linux boxes come with *.UTF-8 locales). I'm guessing I've run into it due to my Czech locale and running `make` with `LC_ALL=C`.

**Comment by simonmichael** [comment]
We are an international project and we embrace the non-ascii. If it doesn't work, it's a bug. 

What made you set your locale to C ?

**Comment by zarybnicky** [comment]
It wasn't an intentional change, but I started building in a pure nix shell - I was moving my other projects to pure Nix shells to avoid mixing up local binaries, and this happened. I guess the better solution is to fix the `make genmanuals` pipeline to that the *.txt files build better, and to switch to a custom `shell.nix` file like in https://github.com/commercialhaskell/stack/issues/2358#issuecomment-258719548 so that hledger can build in a pure nix-shell, with a LANG and LC_* that is *.UTF-8 - and not POSIX nor C.

**Comment by zarybnicky** [comment]
I have no idea what's the situation with LANG=*.UTF-8 vs LANG=C/POSIX in the rest of the Unix world though.

**Comment by simonmichael** [comment]
Ok, let's close this issue or if you want to keep using it for something else, clarify the name.

**Comment by zarybnicky** [comment]
Ok, renamed. I'll have a look at a custom shell.nix that works with `--pure` sometime soon, but I've been a bit short on time lately, and I still want to finish the `hledger-web` permissions fix soon (still WIP...).
