### ISSUE TITLE
hledger-ui shows an empty transaction list as a screenful of  `..  ..`

### ISSUE THREAD

**Issue by bertiebaggio** [simonmichael/hledger#822]
With `hledger-ui` 1.9 (built a week ago using `stack install --resolver=lts hledger-lib-1.9 hledger-1.9 hledger-ui-1.9`) on OSX; attempting to show **Cleared** or **Pending** transactions when there are none to show causes `hledger-ui` to display `100/0` empty transactions `.. ..`.

To reproduce:

    $ less mwe.journal
    
    2018/06/18 Widget Co
        assets:checking              -20
        expenses:widgets              20

    $ hledger-ui --register checking -C -f mwe.journal

Output is (*long screenshot*):

![mwe output](https://i.imgur.com/jc5ebjU.png)

(In addition, navigating upwards through the 'transactions' decrements the number of transactions and also prevents navigating back down)

Checking the whole journal (as opposed to an account) has different behaviour, showing `1/0` and two spaces:

    $ hledger-ui -C -f mwe.journal

![overall journal](https://i.imgur.com/tI0YuOf.png)

**Comment by simonmichael** [comment]
An old display bug that we really should get fixed.
