### ISSUE TITLE
sorting by account code is not supported consistently

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#827]
[Account codes](http://hledger.org/manual.html#declaring-accounts) do not yet affect the sort order of:

1. the accounts command
2. the balance command's single-column mode
3. code-less subaccounts of code-ful parent accounts in flat mode balance reports.
4. hledger-web's sidebar

For 3, presumably we'd want those subaccounts without an explicit account code to sort similarly to their parents, even in flat mode and if the parent account is not being displayed, perhaps inheriting some account code similar to their parent's. Unless it creates too many complications.

**Comment by legrostdg** [comment]
Are account codes still supported?

`accounts.journal`:
```
account revenues                4000
account expenses                6000
```

```
$ hledger accounts -f accounts.journal 
hledger: /home/gueux/accounts.journal:1:33:
  |
1 | account revenues                4000
  |                                 ^
unexpected '4'
expecting ';', end of input, or newline

```

**Comment by simonmichael** [comment]
No, they were [dropped in 1.13](https://hledger.org/release-notes.html#hledger-cli-1-13). So we can close this, thanks.
