### ISSUE TITLE
Why can't hledger query for comments?

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#828]
I have a journal with 10 years worth of financial data that contains lots of useful information in posting comments, i.e.: 

~~~
2018/06/25 EDEKA     ; Kartenzahlung
    Vermögen:Girokonto         EUR -53.68 = EUR 8574.21    ; Debitkarte 123456789
    Ausgaben:Lebensmittel
~~~

Now, I wanted to make a report that show all transactions paid with my debit card, but not my wife's. That seemed easy enough, because I assumed that I could run something along the lines of

    hledger reg comment:123456789

but it turned out that hledger cannot query by posting comments. That was quite a surprise to me. Why is there no `comment:` and/or `pcomment:` selector that can be used for this purpose?

**Comment by adept** [comment]
As a person with double-digits years of ledger/hledger journal, I do feel an occasional need to "grep" for something. On the other hand, I agree with @simonmichael that "from the position of hledger's current design, that was a wrong use of comments" and "if comment becomes just another data field, results will start to depend on its contents and there's no longer a way to add some guaranteed-harmless annotations".

Interestingly, the example provided even have the comment that looks like a tag, if only it was written "Debitkarte:123456789"

I do see a middle ground, though (warning: i did not think long and hard about this). An ability to regexp-match whole transaction body could be added to print (and potentially other commands as well) and will both give a grep-like prefilter ability (in "user beware" style - it would be anyone's guess what happens to balance assertions for example) and avoid giving comments a first-class place among other data fields.

**Comment by simonmichael** [comment]
Yes, if I was writing that comment I would usually think "this looks like something I might like to query, make it a tag" and write `; Debitkarte:123456789`.

The print --grep (I don't know what else you'd call it) idea is interesting. Somewhat equivalently, I have long wanted a query syntax for searching all fields, which could be made to also match comments. It would be a kind of ambivalent half support for comment searching. It would be hard to match on the comment field only. The "non-affecting comment" principle would be weakened.

**Comment by simonmichael** [comment]
Or (does not require blank lines between entries, cleans up the entries, loses the things print loses, eg inter-transaction comments):

    hledger print | awk -vRS='' -vORS='\n\n' /PATTERN/

**Comment by simonmichael** [comment]
I'm still off on this tangent, making notes. How could print --grep look as a query ?

    `entry:REGEX` - matches transactions whose journal entry contains REGEX

requires saving journal text with each transaction

    `txn:REGEX` - matches transactions whose print output contains REGEX

requires rendering each transaction to query it

    `any:REGEX` - matches transactions where any transaction or posting field contains REGEX

requires rendering non-text fields to text to query them.

**Comment by bertiebaggio** [comment]
Another small thought off the back of one of sm's comments above: if comments are searchable, would that include inter-transaction comments? On the one hand, I can't think of a reason that someone would want to do so with a tool that works with transactions (as opposed to a a plain `grep`); on the other hand, it seems inconsistent/surprising to search some comments and not others.

**Comment by simonmichael** [comment]
No it wouldn't, without special effort. We do (documented or not) have a concept of three different kinds of comment: file, transaction, posting comments.

**Comment by simonmichael** [comment]
Well actually, we also have a some special handling for comment lines immediately preceding a transaction (tpreceding_comment_lines).

**Comment by simonmichael** [comment]
Update: we had another short IRC chat yesterday. @peti got annoyed and abandoned ship. So far, two people are somewhat in favour of my position (@adept, f-a), noone has supported peti's, and the list doesn't care about this. I have been thinking about it. 

Some notes. First, here are the types of comment in hledger, for reference:

-   transaction-preceding comment
    Lines beginning with ; immediately before a transaction.
-   transaction comment
    Text following ; after the description field, or indented on following lines. Displayed by print. Can define searchable tags.
-   posting comment
    Text following ; after the amount/price/balance assertion fields, or indented on following lines. Displayed by print. Can define searchable tags.
-   directive comment (not implemented)
    Lines beginning with ; immediately before a directive, and text following ; after it, or indented on following lines.
-   file comment
    All other lines beginning with ; or # or \*, not attached to transactions or directives.
    Also lines between a \`comment\` directive and \`end comment\` or end of file.
    
Several ideas aimed at improving the situation for someone with peti's wish:

-   make tags more convenient
    -   a TAG:[PAT] query could be a shortcut for tag:TAG[=PAT]
    -   a desc: tag could set the transaction/posting description
    -   a desc:VALUE tag could be written more briefly as ; :VALUE

-   posting descriptions
    -   postings could have a new optional description field, separated from the amount/price by 2+ spaces, replacing or augmenting the transaction description

-   searchable comments
    -   all transaction/posting comments could be searchable with cmt: (peti's proposal, in essence)
    -   there could be two kinds of transaction/posting comments, light/soft vs deep/hard
        -   transaction/posting comments beginning with ; can define tags and are searchable with cmt:
        -   transaction/posting comments beginning with ;; (and all file comments) can't define tags and aren't searchable

Tangential thoughts on comment visibility:

-   print currently shows transaction and posting comments
-   it should also show transaction-preceding comments
-   should it also show file (inter-transaction) comments ?
-   should it have options to show/hide some/all kinds of comments ?
    
Summary: 

-   I can understand the urge to search comments, I sometimes feel it too.
-   It's important to avoid feature creep and keep complexity under control.
-   It's important to present clear and intuitive concepts, data models and best practices to users.
-   I find the ; vs ;; idea attractive.
-   But no matter how we slice it, searchable comments means adding another data field, another concept, and another decision for users to make when recording journal entries.
-   If someone wants to push this forward, please do the work of writing the docs and let's see how it reads. My best guess is we will judge it more complicated and not quite worth it, but I keep an open mind.

**Comment by peti** [comment]
Well, to be accurate, I did not "abandon ship". I simply realized that there was nothing I could say or do to make you agree to that particular feature so I stopped pursuing it. You have strong convictions on what hledger should look like, and this is great because those beliefs drive you to go the extra mile to make the source code neat and to clean up the API and to write good user documentation, etc. `hledger` is a great tool, and it got into that shape because you feel strongly about it and put all this effort into developing it.

The downside is, unfortunately, that it is very difficult for anyone else to join into the effort because anyone who'd like to contribute something that's not quite exactly like you'd have done it yourself is going to meet significant resistance. I've attempted to contribute to hledger a couple of times before, and it has always been, um, a surprisingly large effort to get changes in that looked really trivial to me, personally. It appears that the design ideas I have are somewhat different from those that you have and therefore it feels like a bad idea to try and fight over those ideas all the time. I'd rather leave you to do your thing without disturbing and meanwhile I'll do my thing. It's a hobby, right? It's supposed to be fun, not arguments and heated discussion that lead nowhere.

**Comment by simonmichael** [comment]
@peti, ok. I tried to be brief rather than just pasting our IRC chat. When someone drops out mid-conversation, closes everything, revokes collaborator status and (it seemed to me) unsubscribes from the mail list, it seemed a reasonably accurate and non-offensive phrase. I apologise for poor wording.

Re your feedback, I appreciate it. While I'm doing my best to adapt as the project grows, yes, doubtless sometimes I'm too controlling or overthinking. 

In my defense, I believe many contributions have been quickly and easily accepted, including from you.

Others require more justification, and don't get in unless I, or the community, have been convinced. Because it's a hledger principle to care a lot about long-term design/UX/complexity/maintainability, and if we merged every idea we would long ago have ended up like [the bad parts of] Ledger. 

Some things that don't get in at first, do get in eventually (periodic transactions, auto postings..). Sometimes the delay means we find a better solution and avoid locking in some unnecessary complication for all time. 

When it happens, hopefully not *too* often, such foot-dragging can require a frustrating amount of patience and work from a contributor. I think this happens in many projects. I fully support you dropping this issue since it's no longer fun for you. If you feel like coming back to it or something else in future, please do. Thanks for your valuable contributions.

**Comment by simonmichael** [comment]
PS. I'm being longwinded, but such discussions can be quite useful for the project. 

A contrasting school of thought says that the best strategy in the long run is a free-for-all. I am always trying to move hledger a bit more in that direction, but perhaps never all the way. If someone ever tries that, it would be a very interesting experiment.

**Comment by rickswe** [comment]
It is surprising that such a useful program does not support querying comments. Tags and ordinary comments share the same comment field, which may complicate how a comment query should treat tag text. For now, Perl provides a workable solution:

```sh
make |
  perl -00 -ne 'print unless /;[^\n]*\bSkip Me\b/i' |
  hledger -f- -I print 'tag:fixme'
```

Thanks for all the great work.
