### ISSUE TITLE
start forecast transactions before today ? clarify forecast start/end rules

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#835]
We currently have some functional tests failing due to --forecast being current-date-dependent. I think the [manual](http://hledger.org/manual.html#forecasting-with-periodic-transactions) is not quite right about forecast transactions' start date. It seems not possible to generate forecast transactions before today's date. Perhaps it should be.

**Comment by simonmichael** [comment]
Actually it is, but only if the journal contains normal transactions ending on a sufficiently old date.

I think the manual now shows the precise forecast date rules are pretty confusing, and we should drop the "later of" clause.

**Comment by simonmichael** [comment]
(I'm pretty sure I haven't documented it completely even now..)

**Comment by simonmichael** [comment]
(And those failing functional tests are not in master actually, just some local WIP.)

**Comment by barrucadu** [comment]
I don't tend to use `-b` or `-p`, so dropping the "later of" would work for me, but I wonder if using `-b`/`-p` here is conflating two things: the desired start date for the report, and the desired start date for the periodic transactions.  Are those really the same thing?

What if you want a report beginning three months ago and ending in three months time, with forecasted transactions for the future months, but only actual transactions for the previous months?

**Comment by simonmichael** [comment]
Good point. For full control you'd need to set forecast start date separately. So maybe it's best to stick with the current policy of never generating forecast transactions before last normal transaction.

**Comment by simonmichael** [comment]
Thanks for the examples. By my reading of the docs [here](http://hledger.org/manual.html#forecasting-with-periodic-transactions), they are working exactly as specified. But, I agree that 1. this spec is too complicated and surprising and 2. it does not allow generating transactions earlier than your latest recorded transaction, and that might sometimes be useful.

I think this idea (adding a flag with different behaviour) would solve 2, and we'd need to keep --forecast as well to serve barrucadu's use case above..

**Comment by simonmichael** [comment]
If two flags, ideally their names would be related somehow. "--periodic" may be a bit too similar to `--period`.

We should think about complications that might arise from wanting to combine multiple periodic transaction rules in different ways. Currently all periodic rules are activated together and work the same way. Will people want to generate some periodic txns during the journal period and others only in the future ?

**Comment by simonmichael** [comment]
I will just note that right now the way to get the report you want, is to generate the periodic transactions once and save them into your journal (or a separate journal file which you include at will), before running reports. I do this with forecasted transactions. I understand that it might be nice not to have to do that.

**Comment by julian-klode** [comment]
I guess this is the problem I have?

I want to have a transaction that runs in April every year (so every 12 months from 2019/04). However, if the specified from date is past the current date, the current month is used:

```
$ cat t
~ every 12 months from 2019/04
        a  -5 EUR
        b  5 EUR
$ hledger -f t  p --forecast -p 2020 
2020/09/01
    ; generated-transaction:~ every 12 months from 2019/04
    a          -5 EUR
    b           5 EUR
$ hledger --version   # from nix
hledger 1.15.2
```

**Comment by simonmichael** [comment]
@julian-klode, thanks for reporting. From a quick investigation I think this is simply a bug in runPeriodicTransaction, would you mind opening a separate issue for this.

**Comment by julian-klode** [comment]
#1085 - title might need work.

**Comment by adept** [comment]
Let me add some color on the original rationale for `--forecast` (as it came out of my PR):

The rationale was that `--forecast` is just this: a forecast of activity that will happen in the future, but did not happen yet, however you want to have it for budgeting/planning purposes. Eventually (as time goes) these transactions will happen "for real" and at this point there would be no need for forecast stand-ins, as you would have real transactions in hand. This is why --forecast always starts after the last real transaction in the journal, as I saw this as a simple reasonable compromise **that does not add yet another date/period-related switch as there are so many of them already.** 

Obviously there could be alternatives:

1. generate them all the time -- for starters, this should probably not be called "--forecast". Then, what if -b/-e/-p were passed - do we ignore them? Do we not? Either way there is a chance to mess up historical/cumulative reports.

As an aide If there is a need for a way to generate automated transactions (as opposed to automated postings), maybe --auto could be conscripted to always generate periodic transactions.

2. Start after the date of last transaction in affected accounts, not in journal as a whole. This could get really confusing really quickly if transaction mentions more than 2 accounts. Do you take min of all dates? Or max? Why? 

3. Start after some explicitly specified date and end at explicitly specified date. Making this non-optional looks like overkill. If they are optional, they need to have some default values. 

Maybe this is the way to go? Introduce something like --forecast-from and --forecast-until, have them default to current default start-end dates, and leave the rest of the code intact? Would this be enough for all the use-cases we've seen so far?

**Comment by simonmichael** [comment]
Quick response: good points @adept, thanks. So, two use cases:

1. generating transactions in the future, temporarily, just for forecasting
2. generating transactions during the same span as the recorded transactions, perhaps as the norm, because eg someone finds it easier than data entry

2 is not something I usually advocate, but it might be a common wish with real value. Is it ? We should probably figure that out before investing much effort in it.

I agree that "forecast" implies "future" (so I wouldn't call it --forecast-from).

**Comment by adept** [comment]
`--forecast-from` would make sense if the future is unevenly distributed, to steal the quote. Perhaps some of your accounts are more up-to-date than the rest of them and you want to pretend that future starts not now or at the most recent transaction, but rather a bit further in the past

**Comment by julian-klode** [comment]
Maybe it makes sense to have tags so you can match forecasts to existing transaction, so if an existing transaction exists, you don't forecast it.

Like you have a monthly rent payment, you tag it rent for the real transaction and the automated one, and then if there already is such a transaction in the current month, you'd skip the forecast.

I'm not sure it's useful though, it sounds more like a --budget task.
