### ISSUE TITLE
Correction to download instructions for stack

### ISSUE THREAD

**Issue by thanateros** [simonmichael/hledger#837]
http://hledger.org/download.html, in section **b2**, the stack command, as given, will not install hledger and friends: `stack install --resolver=nightly-2018-06-02 hledger-lib-1.10 hledger-1.10 hledger-ui-1.10 fsnotify-0.3.0.1 hledger-web-1.10.1 hledger-api-1.10` ; it has a problem finding hledger-web.

I know nothing of Haskell (Coming from a Go perspective, I'm guessing `stack` is the Haskell version of a `go get`); I checked the version of hledger-web in the stack repo (I'm guessing as to terminology here) and it is **10.0**, not **10.0.1**, so the version of the command that is chugging away installing everything right now is:

```haskell
stack install --resolver=nightly-2018-06-02 hledger-lib-1.10 hledger-1.10 hledger-ui-1.10 fsnotify-0.3.0.1 hledger-web-1.10 hledger-api-1.10
```

Again, all I did was change `hledger-web-1.10.1` to `hledger-web-1.10`.  Now it is installing a bunch of stuff, we will see how it goes.

**Comment by simonmichael** [comment]
Thanks for the report! I have limited access for a day or two. Yes this needs updating, we can use —resolver lts-12 now.

**Comment by simonmichael** [comment]
Download page updated.
