### ISSUE TITLE
Visual artefacts in hledger-ui after update to 1.10.1

### ISSUE THREAD

**Issue by dstrelnikov** [simonmichael/hledger#838]
Hey there!

I have just updated hledger-ui to 1.10.1 after 1.9 with the command
```
stack install --resolver=nightly-2018-06-02 hledger-ui-1.10.1
```
and got some visual artefacts in ui:

<img width="518" alt="screenshot_20180715_133840" src="https://user-images.githubusercontent.com/14166481/42733165-577e4e2a-8835-11e8-8219-b88a1f7a112a.png">

**Comment by simonmichael** [comment]
Uh, that's.. weird. The body text is blurred, and the title/footer text isn't ? What happens with `--theme greenterm` and `--theme terminal` ?

**Comment by simonmichael** [comment]
Oh, no, surely you've just blurred the data for privacy. What is the visual artefact you mean ?

**Comment by dstrelnikov** [comment]
>Oh, no, surely you've just blurred the data for privacy. What is the visual artefact you mean ?

Yes, sorrry, I have to complain this :)

I mean the top and the bottom lines. There are white spaces. They was fully black before the update. Compare with this:

<img width="518" alt="screenshot_20180715_153827" src="https://user-images.githubusercontent.com/14166481/42734030-623a8788-8845-11e8-88a1-fdf1ac0fdd66.png">

**Comment by simonmichael** [comment]
I see it. Thanks for the report! Here are my 1.9 and 1.10.1 builds on macos in iterm2:

![screen shot 2018-07-15 at 2 04 09 pm](https://user-images.githubusercontent.com/10144/42734192-c79fe39c-8837-11e8-8fbb-33ef558659be.png)

I don't see anything obviously related in the brick, vty or ansi-terminal changelogs; any debugging help is welcome.

**Comment by dstrelnikov** [comment]
I confirm the bag also on version 1.10.

**Comment by simonmichael** [comment]
Fixed in master. Thanks for the report!

**Comment by dstrelnikov** [comment]
> Fixed in master. Thanks for the report!

Thank you!
