### ISSUE TITLE
Allow globs in 'include' statements

### ISSUE THREAD

**Issue by jbweston** [simonmichael/hledger#843]
I see from the [documentation](http://hledger.org/journal.html#including-other-files) that globs cannot be used in 'include' statements. I have also confirmed that this does not work with v1.10.

Would this be difficult to add to hledger? I would be willing to have a go at implementing this, if it's an uncontroversial feature.

**Comment by simonmichael** [comment]
Hi @jbweston, that would be great. I'm not aware of any problems with it (yet).

**Comment by simonmichael** [comment]
Related: #846

**Comment by jbweston** [comment]
This is actually a duplicate of #303.
