### ISSUE TITLE
force use of custom tags in every posting

### ISSUE THREAD

**Issue by legrostdg** [simonmichael/hledger#845]
I would need to associate some custom fields to every posting. Tags seem to be a nice solution for this, but it does not seem like there is a solution to force the user to fill these.

**Comment by simonmichael** [comment]
Yes, no builtin solution for this. Writing a script to check it is a good start, then you could arrange to run it before other hledger commands (eg with a shell alias).

**Comment by varac** [comment]
I'm looking for the same functionality. I.e. I need all postings under one account to contain a VAT tag with at least a value>0. How would i check for this ? I mean, how can I find posting *without* a tag ?

**Comment by simonmichael** [comment]
hledger reg expenses:business not:tag:.  # or not:tag:vat=.*[1-9].*
