### ISSUE TITLE
Error using periodic transactions

### ISSUE THREAD

**Issue by cnicolai** [simonmichael/hledger#847]
Hi there,

let me start by thanking you for all the work you put in hledger! It is an amazing tool that I really enjoy using! :-)

Consider the following journal file `test.journal`:

```
2018/07/01 Cake
	expenses:Food			1€
	assets:Cash		       -1€

~ monthly
	expenses:Food                    19€
	assets:Cash                     -19€ 
```

Running `hledger -f test.journal reg --forecast -e oct` results in the expected output

```
2018/07/01 Cake                           expenses:Food                             1€            1€
                                          assets:Cash                              -1€             0
2018/08/01                                expenses:Food                            19€           19€
                                          assets:Cash                             -19€             0
2018/09/01                                expenses:Food                            19€           19€
                                          assets:Cash                             -19€             0
```

The following journal file used to work for me:

```
2018/07/01 Cake
	expenses:Food			1€
	assets:Cash			   -1€

~ every 2nd Thursday
	expenses:Food                    19€
	assets:Cash                     -19€ 
```

Here, `~ monthly` in the periodic transaction is replaced with `~ every 2nd Thursday`.
Running `hledger -f test.journal reg --forecast -e oct` now results in 
`hledger: Prelude.head: empty list`.

Is this a regression or am I missing something? Any help is appreciated.

**Comment by simonmichael** [comment]
You are welcome! And thanks for the report. It looks like the capital T breaks it!

**Comment by cnicolai** [comment]
Thanks a lot for the quick help. The capital T indeed seems to be the problem, lower-casing the weekdays in my way more complex journal fixes the problem as well.

I have very rudimentary knowledge of Haskell and basically no knowledge about hledger, so I'm afraid I can't help fix the bug.
I'm in the process of learning Haskell, so maybe in a few months when I find bugs I can try to fix them myself.

Thanks again!

**Comment by simonmichael** [comment]
That would be great. If you get the urge, you are welcome to come on #hledger and ask for help working through a fix.
