### ISSUE TITLE
Forecasting bug in hledger 0.10

### ISSUE THREAD

**Issue by peti** [simonmichael/hledger#852]
When I attempt to process the following file

~~~
~ every 31st March
    Bank             EUR 1
    Mortgage
~~~

with `hledger print --forecast`, the tool crashes, saying:

~~~
hledger: Prelude.!!: negative index
~~~

The same command worked fine with previous versions.

**Comment by peti** [comment]
Other period transactions still work fine, so I reckon that the issue is with that particular period expression.

**Comment by cnicolai** [comment]
This could be related to #847 since lowercasing "March" seems to solve it.

**Comment by simonmichael** [comment]
Thanks for the report! This was a regression in hledger 1.10.

**Comment by peti** [comment]
Thank you for the quick fix!
