### ISSUE TITLE
hledger-web API doc improvements needed

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#856]
The api provided by ~hledger-api~hledger-web should be easier to discover, eg in manual, perhaps via new swagger docs. See list discussion: https://groups.google.com/d/topic/hledger/a1iK_pxYgUU/discussion

**Comment by mhansen** [comment]
I think this can be closed now since https://github.com/simonmichael/hledger/commit/4db14ef70fad0cd1efa4f0bddfefca834d07e749 and https://github.com/simonmichael/hledger/commit/2d1b53c59773dc619602efc6348bc2a67edc3bc0, hledger-api seems mothballed.

**Comment by simonmichael** [comment]
I’ve retargeted this at hledger-web.

**Comment by simonmichael** [comment]
Downgrading to a wish as no-one complains.
