### ISSUE TITLE
Auto-balancing between multiple currencies can hide errors, should be warned/preventable

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#86]
_Original author: rocon...@r6.ca (May 08, 2012 16:09:46)_

<b>What steps will reproduce the problem?</b>
1. create a file called /tmp/hledger.test with the following data:

2012/01/01 Initial
    accounts:bank           100 EUR
    equity:initial

2012/04/21 Test
    expenses:test1        1.78 EUR
    expenses:test2      $44.00
    accounts:bank       -45.78 EUR
1. execute hledger bal -f /tmp/hledger.test

<b>What is the expected output? What do you see instead?</b>

I expect there to be an error because the Test transaction does not balance to 0.  Instead I made an error where I entered $44 dollars instead of 44 EUR.

Instead the command succeeds and I'm oblivious to error in the entry. 

What version of the product are you using? 

hledger-0.16.1

On what operating system?

linux

<b>Please provide any additional information below.</b>

Some people on IRC were arguing that there is nothing that can be done to catch this error.  However I disagree.  Any time that sum of all the currencies of a transaction do not sum to 0 the entry is in error.  The fact that all the ledger entries sum to 0 is the fundamental property of double entry bookkeeping that makes it so effective at catching errors.  Removing this property in any situation makes the ledger program useless for catching mistakes.  For currency conversions a &quot;trading&quot; account should be used as described in: http://www.mscs.dal.ca/~selinger/accounting/tutorial.html

_Original issue: http://code.google.com/p/hledger/issues/detail?id=86_
## 

----
Related: #115, #758, #1177

**Comment by simonmichael** [comment]
Also related: https://www.mathstat.dal.ca/~selinger/accounting/tutorial.html#4.2

**Comment by dstrelnikov** [comment]
I do agree that the transactions of this form
```
2020/01/01 Purchase in USD
    Expenses:Food          50 USD
    Assers:Bank:Checking  -42 EUR
```
should raise at least a warning.

A more neat way to record this transaction could be
```
2020/01/01 Purchase in USD
    Expenses:Food          50 USD @@ 42 EUR
    Assers:Bank:Checking
```

However, I realize that the solution isn't easy. For example someone might want to record it in the following way
```
2020/01/01 Purchase in USD
    Expenses:Food          50 USD
    Assers:Bank:Checking  -42 EUR
    Equity:Trading
```

A more neat way would be
```
2020/01/01 Purchase in USD
    Expenses:Food          50 USD
    Assers:Bank:Checking  -42 EUR
    Equity:Trading        -50 USD
    Equity:Trading         42 EUR
```

But the `@@` and automatic balancing are so sweet, I have a great temptation to use it :)

**Comment by simonmichael** [comment]
The current plan is to add a fullybalanced check to the new check command, which would not allow balancing via prices. And possibly include it in --strict mode. And then, possibly, always convert to the fully balanced form internally, and give print the ability to show either form.

**Comment by simonmichael** [comment]
This was done, see #1177.
