### ISSUE TITLE
Support declaring payees

### ISSUE THREAD

**Issue by DamienCassou** [simonmichael/hledger#864]
My ledger file is full of lines such as:

```ledger
payee Carousel
payee Cinema
```

This forces me to be coherent across the journal and let me query it with greater confidence. Could you please consider a feature like this?

**Comment by simonmichael** [comment]
DId you see the http://hledger.org/manual.html#payee-and-note feature, which you can query with `payee:`. 

However we don't support predeclaring and enforcing a limited set of payees, and perhaps we should.

**Comment by DamienCassou** [comment]
> DId you see the http://hledger.org/manual.html#payee-and-note feature, which you can query with payee:.

I did yes. My opinion is that such feature can only be useful if the user is careful enough to always write payees in the same way. This is the purpose of this ticket.

> However we don't support predeclaring and enforcing a limited set of payees, and perhaps we should.

That is indeed my opinion.

**Comment by DamienCassou** [comment]
This was implemented in 652deb04ee769d0e996bfc5c9b5dfb37128f4229.
