### ISSUE TITLE
haddocktest doesn't seem to run parser's tests

### ISSUE THREAD

**Issue by DamienCassou** [simonmichael/hledger#866]
If you arbitrarily replace some haddock test in hledger-lib/Hledger/Read/JournalReader.hs (and maybe other files), you won't get any error while running the tests. To reproduce, change the file like this:

```patch
@@ -273,7 +273,7 @@ indentedlinep = lift (skipSome spacenonewline) >> (rstrip <$> lift restofline)
 
 -- | Parse a one-line or multi-line commodity directive.
 --
--- >>> Right _ <- rjp commoditydirectivep "commodity $1.00"
+-- >>> Right _ <- rjp commoditydirectivep "commoXXXXXdity $1.00"
```

and run

```session
$ make haddocktest
```

**Expected**: haddocktest should fail because `commoditydirectivep` can't recognize `"commoXXXXXdity $1.00"`.

**Actual**: haddocktest succeeds with

    Log files have been written to: /home/cassou/Documents/projects/ledger/hledger/.stack-work/logs/
    haddocktest PASSED

**Comment by simonmichael** [comment]
Correct, haddocktest only tests that haddock can process (render to html) those docs without error. `make doctest` tests the actual doctests.
