### ISSUE TITLE
--anon seems to break balancesheet

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#878]
Adding to --anon to balance does not change the numbers, as expected. Adding it to balancesheet changes them dramatically, at least with my personal ledger. Could someone confirm ?

**Comment by cocreature** [comment]
I can confirm this. The reason why this happens is that when `assets` is anonymized the query done by the balancesheet hits the wrong accounts. I’m not entirely sure what it is hitting in this case (I would have expected it to match nothing at all). An easy fix would be to not anonymize account prefixes that are used in fixed queries such as `assets`, `liabilities` and probably a few others. Ofc that does end up leaking a bit of information but I’m not sure that’s actually a problem.
