### ISSUE TITLE
Plan for megaparsec 7 support? blocking Arch Linux packagers

### ISSUE THREAD

**Issue by felixonmars** [simonmichael/hledger#879]
Looks like megaparsec changed the related part again... Do we have a plan to support the new version soon?

**Comment by simonmichael** [comment]
Yes: https://github.com/simonmichael/hledger/issues/853#issuecomment-420054999. Have you had a chance to start on this @awjchen ?

Is it causing problems @felixonmars ?

**Comment by felixonmars** [comment]
Ah thanks, didn't find that comment.

It is currently blocking the megaparsec update on Arch. I have recalled the batch already so it is not in a hurry :)

**Comment by awjchen** [comment]
I've been working on re-implementing the `ExceptT` layer, but I had decided to delay moving to megaparsec 7 since some of our dependencies (cassava-megaparsec, config-ini) still required megaparsec <7. It now looks like they have all been updated to use megaparsec 7, so I'll prioritize this work.

**Comment by simonmichael** [comment]
This was merged, next hledger release will require megaparsec 7.
