### ISSUE TITLE
Make the website accessible over HTTPS

### ISSUE THREAD

**Issue by nikhiljha** [simonmichael/hledger#881]
The [site](https://hledger.org/) does load over HTTPS currently, but with a bad certificate. Getting an SSL certificate is [free with Let's Encrypt](https://letsencrypt.org/) - so there's no real reason not to do it.

The website should work over HTTPS and have a redirect from the HTTP > HTTPS version.

[Why your static site needs HTTPS](https://www.troyhunt.com/heres-why-your-static-website-needs-https/)

**Comment by simonmichael** [comment]
I dragged my heels on this for a long time, but now it's done. Thanks for the push, and the useful links.
