### ISSUE TITLE
support GHC 8.6 / get into stackage nightly

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#883]
hledger 1.10 was in stackage nightly-2018-09-28, since then we and a thousand others have been removed pending GHC 8.6 buildability.

**Comment by simonmichael** [comment]
https://github.com/joelburget/easytest/issues/12

**Comment by simonmichael** [comment]
https://github.com/liamoc/wizards/issues/11

**Comment by simonmichael** [comment]
https://github.com/aisamanra/config-ini/issues/18

**Comment by peti** [comment]
Is there still anything blocking this issue from making progress?

**Comment by simonmichael** [comment]
It looks like at least hledger can get into stackage. Working on it now.

**Comment by simonmichael** [comment]
https://github.com/commercialhaskell/stackage/pull/4132

**Comment by simonmichael** [comment]
Ah.. yes, of course the released hledger 1.11 doesn't support GHC 8.6. The required code and dep changes are involved enough that (a) I'd prefer not to spend that time if I don't have to and (b) they may require more than a minor version bump. 

On the other hand, it's still quite a long time until next scheduled release (12/31). Hmm.

**Comment by peti** [comment]
Will there be a new version of hledger that support ghc 8.6.x? It's been quite a while since 8.6.x came out, but the current release hledger still doesn't support it even though the incompatibilities seem rather small'ish in nature.

**Comment by simonmichael** [comment]
Yes, and thanks for the ping. I have been grinding on release prep and aim to release 1.12 on or close to 12/1.

**Comment by simonmichael** [comment]
hledger 1.12 released, https://github.com/commercialhaskell/stackage/pull/4132 in progress.

**Comment by simonmichael** [comment]
https://github.com/commercialhaskell/stackage/issues/4202

**Comment by simonmichael** [comment]
Stackage-related followup issues noted above, but we are back in stackage at last \o/ so closing this.
