### ISSUE TITLE
Strange raw/debug display of transactions

### ISSUE THREAD

**Issue by swalladge** [simonmichael/hledger#884]
In hledger version 1.11 in some cases transactions display in what looks like raw/debug output of the internal data structure. Example:

```
Adding transactions to journal file main.ledger
[clipped]
Account 3 (or . or enter to finish this transaction): 
Transaction {tindex = 0, tsourcepos = JournalSourcePos "" (1,1), tdate = 2018-10-05, tdate2 = Nothing, tstatus = , tcode = "", tdescription = "test tx", tcomment = "", ttags = [], tpostings = [PostingPP {pdate="Nothing", pdate2="Nothing", pstatus="", paccount="assets", pamount=Mixed [Amount {acommodity = "AUD", aquantity = 1, aprice = NoPrice, astyle = AmountStylePP "R True 0 Nothing Nothing..", amultiplier = False}], pcomment="", ptype=RegularPosting, ptags=[], pbalanceassertion=Nothing, ptransaction=Just "<txn>", porigin=Nothing},PostingPP {pdate="Nothing", pdate2="Nothing", pstatus="", paccount="income", pamount=Mixed [Amount {acommodity = "AUD", aquantity = -1, aprice = NoPrice, astyle = AmountStylePP "R True 0 Nothing Nothing..", amultiplier = False}], pcomment="", ptype=RegularPosting, ptags=[], pbalanceassertion=Nothing, ptransaction=Just "<txn>", porigin=Nothing}], tpreceding_comment_lines = ""}
Save this transaction to the journal ? [y]: 
```

I have observed this type of output when it prints a tx to confirm in hledger add (as above), when hledger add shows a similar tx for defaults, and when hovering over a tx in hledger-web.

**Comment by simonmichael** [comment]
Thanks for the report. I have seen this in transaction balancing/balance assertion errors too. It's a recent regression due to messing with Show instances.

**Comment by simonmichael** [comment]
I think https://github.com/simonmichael/hledger/commit/d14d6e2b683b808157f48d398353bdef866d2aa6 might be the kind of fix needed, ie find all places we `show` a transaction and `showTransaction` instead.

**Comment by simonmichael** [comment]
1.11.1 fixes this and hopefully all similar cases.
