### ISSUE TITLE
ugly error messages for bad/unsupported regular expressions

### ISSUE THREAD

**Issue by tonyxiao** [simonmichael/hledger#889]
I can't seem to find any docs on this. How do I find transactions not matching a particular query pattern?

**Comment by tonyxiao** [comment]
I tried using negative lookahead however it does not appear to be supported

```
$ hledger print '(?!tax)'
hledger: Explict error in module Text.Regex.TDFA.String : Text.Regex.TDFA.String died: parseRegex for Text.Regex.TDFA.String failed:"(?!tax)" (line 1, column 2):
unexpected "?"
expecting empty () or anchor ^ or $ or an atom
CallStack (from HasCallStack):
  error, called at ./Text/Regex/TDFA/Common.hs:29:3 in regex-tdfa-1.2.3.1-Els0MxxgIzJ4ypVBjgoTSQ:Text.Regex.TDFA.Common
```

**Comment by ony** [comment]
Have you tried `hledger print not:tax` or something similar?

**Comment by tonyxiao** [comment]
Oh yea I have no idea how I missed this. Working thanks so much!
![image](https://user-images.githubusercontent.com/696842/46578078-2bb97d80-c9aa-11e8-9aba-8a306cf5ea1d.png)

**Comment by simonmichael** [comment]
http://hledger.org/manual.html#regular-expressions describes our regexps - POSIX Extended Regular  Expressions with some extras, sadly no lookahead/lookbehind. It was a reasonable thing to try and we didn't handle it well, so I'm going to keep this open. We should ensure some better kind of error message in this situation.

**Comment by simonmichael** [comment]
PS we should identify who is calling error here. From the call stack it looks like regex-tdfa, which seems like an upstream bug as [parseRegex](https://hackage.haskell.org/package/regex-tdfa-1.2.3.1/docs/Text-Regex-TDFA-ReadRegex.html#v:parseRegex) is supposed to return an error message.

**Comment by simonmichael** [comment]
Our toRegex/toRegexCI functions should be changed to call makeRegexOptsM and handle an Either.

**Comment by simonmichael** [comment]
PS I guess the easiest fix would be to still call error, but show something more informative like "The regular expression "(?!tax)" is invalid or not supported. See http://hledger.org/manual.html#regular-expressions for more about regexps in hledger."

**Comment by simonmichael** [comment]
Update: not sure if it's possible to get the error message out if you use makeRegexOptsM. Ideas: catch the error call higher up, in IO code; or rewrite Hledger.Utils.Regex to use regex rather than regex-tdfa.

**Comment by Xitian9** [comment]
hledger now displays an error in this case: `hledger: user error (this regular expression could not be compiled: (?!tax))`. Does this resolve the issue sufficiently to close it?
