### ISSUE TITLE
Multiple tags per transaction

### ISSUE THREAD

**Issue by tonyxiao** [simonmichael/hledger#890]
This is my simple transaction
```
2018/10/07 store #10396 ; split: split2:
  L:Credit Cards  USD -30.43
  Expenses:Food & Drinks:Groceries  
```

I can successfully query by `hledger print tag:split`, however `hledger print tag:split2` will display no results. 

Is it possible to add multiple tags per transaction?

**Comment by simonmichael** [comment]
Separate them by commas. http://hledger.org/manual.html#tags-1

**Comment by tonyxiao** [comment]
Thanks - no idea how I missed this.
