### ISSUE TITLE
strict checking for valid accounts

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#891]
This is a proposal for the "optional strict checking" part of #217, allowing us to check account names in transactions against account declarations, and report misspelled or non-permitted account names, similar to --strict/--pedantic mode in Ledger. Here's what I'm thinking:

### Proposal 1

There are different kinds of accounts in the chart of accounts:
- structural parent accounts, like `assets` and `liabilities`, needed for the tree, not normally posted to
- accounts corresponding to real-world accounts, like `assets:bankA:checking` and `liabilities:visa card`
- imaginary subaccounts of real-world accounts, like `assets:bankA:checking:rent` or `assets:bankA:savings:travel`, used eg for budget envelopes/savings goals
- accounts used to balance the books and track accounting concepts, like `equity:opening balances`
- accounts used to categorise inflows and outflows, like `revenues:salary` and `expenses:food:groceries:bulk:rice`

The first kind (structural parents) usually should not receive postings (but they can have account directives, eg to declare their display order or type). All the others typically can receive postings. I'm calling this an account's "usability", ie whether it may be used in postings (I haven't found a better word, ideas welcome.)

You may want to limit the creation of subaccounts deeper than what has been declared. You may want to lock down the basic chart of accounts but still allow freeform subaccounts in certain places.

Syntax should be lightweight and language neutral. Declaring account usability should be orthogonal to the other functions of account directives (display order, type etc.)

We could declare an account's usability by adding characters in the metadata area (in the account directive after two or more spaces, similar to #877):
- `.` (a period) means "this account is usable"
- `*` (a star) means "any subaccount of this account is usable (both children and deeper descendants)"

If any such declarations are found in the journal, account usability checking is enabled and hledger will raise an error if it finds postings to accounts which have not been declared usable.

Eg:
```
; postings to assets or assets:bank are not allowed
account assets
account assets:bank
; postings to assets:bank:checking or any subaccount are allowed
account assets:bank:checking  .*
; postings to assets:bank:savings are allowed, but not to subaccounts
account assets:bank:savings  .
; postings to anything under liabilities, revenues or expenses are allowed (but not to the top-level accounts)
liabilities  *
revenues  *
expenses  *
```

### Proposal 2:

Alternately it could be 

- `.` "this account is usable"
- `*` "direct children of this account are usable"
- `**` "any subaccount of this account is usable (both children and deeper)" 

This gives more control. And if we want this in future, it would be better to start with it now (switching would be disruptive.) However I think it is unnecessary precision, and it's better to keep things simple.

**Comment by simonmichael** [comment]
### Proposal 4

Maybe we don't want such detailed control, and the maintenance busywork that comes with it ? Maybe we can support diverse declaration styles a little more conveniently ? Maybe we want to offload some functionality from account directives ?

We could activate strict account checking with a new `postable-accounts` (or similar) directive. This specifies in a more global and perhaps more future-extensible way which area of the accounts tree can receive postings. Accounts tree here is the full tree (forest) implied by the account directives in effect, including both declared and undeclared accounts. 

Here are some possible values, least restrictive first:

`postable-accounts: any` - unrestricted accounts, equivalent to no directive.

`postable-accounts: tree-and-subs` - can post to any account on the tree, plus anywhere under (above?) the tree, ie deeper subaccounts.

`postable-accounts: tree` - can post to any account on the tree, but no deeper.

`postable-accounts: leaves-and-subs` - can post to any leaf account of the tree or any deeper subaccount.

`postable-accounts: leaves` - can post to leaf accounts only.

`postable-accounts: declared-and-subs` - can post only to accounts declared with account directives, or deeper subaccounts. Possibly excluding the ones ending with `:` as in proposal 3.

`postable-accounts: declared` - as above, without the subs.

`postable-accounts: declared-wildcards` - could even have this, implementing proposal 3.

**Comment by simonmichael** [comment]
### Proposal 5

A simpler plan, similar to what Ledger does:

- by default, there's no restriction on account names
- with the `--strict` flag, any reference to an undeclared account is an error. Eg: if you have declared `account assets:bank:checking`, a journal entry posting to `assets:bonk:checking` will give a parse error. (AFAIK Ledger has --strict and --pedantic giving warnings and an error respectively, but I'd rather not have a --pedantic flag.)

**Comment by danihodovic** [comment]
Any plans for this in 2021?

**Comment by simonmichael** [comment]
Why yes, proposal 5 is in recent releases. Perhaps this can be closed.

**Comment by danihodovic** [comment]
Is there any way to use this command line option by default? Similar to how I set LEDGER_FILE in my zsh file I'd like to set LEDGER_STRICT=true for it to always be enabled.

**Comment by simonmichael** [comment]
For now, the way would be something like:

alias hledger='/path/to/hledger -s'

If you use ledger-mode and flycheck-hledger, you can enable it there by customizing the flycheck-hledger-strict variable.

**Comment by danihodovic** [comment]
```
$ alias hledger='/path/to/hledger -s'
```
I'll give this a try. Thanks. You've built a beautiful tool.

ledger-mode won't work since I use vim :smiling_imp:

**Comment by simonmichael** [comment]
You're most welcome!
