### ISSUE TITLE
Forecast credit card payments

### ISSUE THREAD

**Issue by tonyxiao** [simonmichael/hledger#894]
I want to accurately model spending $ on credit card and then paying it off via autopay via bank account. However the way credit card works is that you spend $ during your statement cycle and then you get at least 21 days after your cycle closes before you pay the balance in a particular cycle while you are still making new transactions (https://www.thebalance.com/credit-card-account-statement-closing-date-959982 more details)

Here's an example where the naive approach doesn't work

```
Y2018

# Credit Card Closing date on 12th, due day on 9th following month
# How do we account for that?

~ 1/1 Buy food
  creditcard  -20
  expense

~ 1/15 Buys drink after closing date
  creditcard  -12
  expense

~ 2/9 Expected autopay
  creditcard  = 0
  bank
```

```
$hledger -f journals/test.journal print -x
2018/01/01 Buy food
    creditcard             -20
    expense                 20

2018/01/15 Buys drink after closing date
    creditcard             -12
    expense                 12

2018/02/09 Pays credit card
    creditcard              32 = 0
    bank                   -32
```

The autopay on 2018/02/09 should be only 20, not 32. Is there a way to account for that in hledger?

**Comment by tonyxiao** [comment]
Primarily for cashflow reasons and knowing the timing helps knowing whether bank accounts would go into negative.

**Comment by adept** [comment]
If you intend to budget with averages, then (rather obviously) you can just create periodic transaction that goes from "bank" to "creditcard" on the same day of the month, moving your average credit card spending.

If you want to model with precise one-off transactions, then, I think, you would have to write you "creditcard" forecast, do "hledger balance -p" on it with the required period, and convert numbers from balance report to forecase transactions from bank to creditcard, which would require a bit of coding.

Alternatively, your creditcard forecast can look like this:
```
~ 1/1 Buy food
  creditcard:jan  -20
  expense

~ 1/15 Buys drink after closing date
  creditcard:jan  -12
  expense

~ 2/1 Buy food
  creditcard:feb  -20
  expense

~ 2/15 Buys drink after closing date
  creditcard:feb  -12
  expense

~ 2/9 Expected autopay
  creditcard:jan  = 0
  bank

~ 3/9 Expected autopay
  creditcard:jfeb  = 0
  bank
```

**Comment by simonmichael** [comment]
Separate from adept's comment, here's a way you could make that work. Your original example, fixed for reproducibility:
```
2017/12/31  make forecast window start on 2018/1/1

Y2018

# Credit Card Closing date on 12th, due day on 9th following month
# How do we account for that?

~ 1/1 Buy food
  creditcard  -20
  expense

~ 1/15 Buys drink after closing date
  creditcard  -12
  expense

~ 2/9 Expected autopay
  creditcard     = 0
  bank
```
```
$ hledger -f a.j print -x --forecast not:desc:window
2018/01/01 Buy food
    ; recur: 1/1
    creditcard             -20
    expense                 20

2018/01/15 Buys drink after closing date
    ; recur: 1/15
    creditcard             -12
    expense                 12

2018/02/09 Expected autopay
    ; recur: 2/9
    creditcard              32 = 0
    bank                   -32
```
Balance assertions are date sensitive, so you could make it pass by changing the date of the last creditcard posting:
```
~ 2/9 Expected autopay
  creditcard    = 0  ; date:1/12  (or [1/12])
  bank
```
but the above runs into a limitation:
```
hledger: Not supported: Transactions with balance assignments 
AND dated postings without amount:
```
so you have to write the amount explicitly:
```
~ 2/9 Expected autopay
  creditcard  20 = 0  ; [1/12]
  bank
```
and now you get the intended
```
$ hledger -f a.j print -x --forecast not:desc:window
2018/01/01 Buy food
    ; recur: 1/1
    creditcard             -20
    expense                 20

2018/01/15 Buys drink after closing date
    ; recur: 1/15
    creditcard             -12
    expense                 12

2018/02/09 Expected autopay
    ; recur: 2/9
    creditcard              20 = 0    ; [1/12]
    bank                   -20
```

Personally, I would tend to write amounts explicitly anyway, it makes the journal clearer.

**Comment by simonmichael** [comment]
Resolved ? Let's discuss it on list if not.
