### ISSUE TITLE
unicode emoji breaks hledger register formatting

### ISSUE THREAD

**Issue by tonyxiao** [simonmichael/hledger#895]
Test case
```
$ cat ./journals/test.journal
Y2018

1/1 Buy Drinks
  creditcard  -20
  expense


1/1 Buy food 🧀
  creditcard  -20
  expense

1/1 Buy toiletry
  creditcard  -20
  expense

$ hledger -f journals/test.journal register
2018/01/01 Buy Drinks                 creditcard                          -20           -20
                                      expense                              20             0
2018/01/01 Buy food 🧀                 creditcard                          -20           -20
                                      expense                              20             0
2018/01/01 Buy toiletry               creditcard                          -20           -20
                                      expense                              20             0
```

Notice the buy food entry off by 1 character. In an actual console this results in a pretty ugly line break

![image](https://user-images.githubusercontent.com/696842/46691746-7578b280-cbba-11e8-873b-0b52b12a3671.png)

**Comment by simonmichael** [comment]
Thanks for the report. It works here, I think you need to adjust your terminal (or font ?) so that wide characters are displayed as double width. I couldn't find any mention of this in docs, so I've added http://hledger.org/manual.html#unicode-characters .

**Comment by ony** [comment]
@simonmichael if issue would be in wide character being displayed in less than two cells then I would expect to see offset to the left side. But on a screenshot it looks like cheese takes two cells but we still put same amount of spaces as for "Buy Drinks".  
So I assume issue is in formatting that doesn't calculate correctly emoji. I tried [wide characters](https://www.unicode.org/charts/nameslist/n_FF00.html) and they were properly aligned.

![screenshot](http://i.imgur.com/OOqrFU1.png)
Github markdown mis-align wide characters on the other hand:
```plain
zsh% hledger -f x.journal reg
2018/01/01 Green Yellow                     creditcard                                 -20           -20
                                            expense                                     20             0
2018/01/01 Ｗｉｄｅ                         creditcard                                 -20           -20
                                            expense                                     20             0
2018/01/01 Wink! 😉                          creditcard                                 -20           -20
                                            expense                                     20             0
```

Note that even [ANSI escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code) works fine.

**Comment by ony** [comment]
And [here is culprit](https://github.com/simonmichael/hledger/blob/b245ec7b3d402aeb701fb4dda10a4a0b4de7effd/hledger-lib/Hledger/Utils/String.hs#L321-L381). We may want to look for some standard function to calculate character width.

**Comment by simonmichael** [comment]
<sm> wow you dug up a secret ancient package there.. looks great except for https://github.com/solidsnack/wcwidth/issues/2 , seems not windows-aware yet
<sm> virkony: and sorry, I don't understand the problem yet. hledger 1.11 renders the examples correctly for me in Terminal.app using Essential PragmataPro font. (But not in emacs. This stuff is very font & app-specific)...

![screen shot 2018-10-15 at 4 55 07 pm](https://user-images.githubusercontent.com/10144/46984669-28ee1500-d09b-11e8-966b-f6efab54c7d0.png)

**Comment by simonmichael** [comment]
I think I see what you mean.. as latest screenshot shows, on my setup they are consuming one character cell, but spilling over the adjacent cells.
![screen shot 2018-10-15 at 4 59 53 pm](https://user-images.githubusercontent.com/10144/46984796-e7aa3500-d09b-11e8-9ae2-6478e8a5a0b6.png)

**Comment by simonmichael** [comment]
Making sense now I think.. as you said, hledger is measuring the emojis as 1 wide (cf strWidth), but my iTerm uses only 1 character cell for them, letting the graphic overflow the following cells, and in the examples there was only whitespace following, so it looked correct. I was able to see the problem by testing in Terminal.app which uses 2 cells.

To use wcwidth we need it to work on windows - perhaps https://github.com/solidsnack/wcwidth/issues/2 will be released soon, otherwise we could temporarily fork/inline it, or add emoji codes to our hardcoded list of widths.

**Comment by tonyxiao** [comment]
Btw in iterm I had to uncheck the following settling to make it work. I hope there's no side effects. 
<img width="925" alt="a" src="https://user-images.githubusercontent.com/696842/46993756-e130b300-d0c5-11e8-87f3-418e5cd9973b.png">

**Comment by tonyxiao** [comment]
Before
![image](https://user-images.githubusercontent.com/696842/46993778-07565300-d0c6-11e8-97d2-d68ef42908d9.png)

After
![image](https://user-images.githubusercontent.com/696842/46993783-0fae8e00-d0c6-11e8-8398-36f5c698eb49.png)

Alignment works fine however the emojis are squished together.

**Comment by simonmichael** [comment]
That tip, and the help: is useful:
![screen shot 2018-10-16 at 5 54 07 am](https://user-images.githubusercontent.com/10144/47017877-42797600-d108-11e8-9647-7f94bc36052e.png)

Strangely it's having no effect on my iTerm 3.1.5 though:
![screen shot 2018-10-16 at 5 59 34 am](https://user-images.githubusercontent.com/10144/47018067-be73be00-d108-11e8-9d19-e360002ddcdb.png)

**Comment by simonmichael** [comment]
Ok, I do see the effect:
![screen shot 2018-10-16 at 6 09 35 am](https://user-images.githubusercontent.com/10144/47018707-35f61d00-d10a-11e8-9d5b-da3d8920d59a.png)
And I see it has also to do with the relative sizes of iTerm's ascii and non-ascii fonts. Both were at 14pt above, when I increased the ascii font to 18pt the emojis' rendering fits nicely in 2 cells:
![screen shot 2018-10-16 at 6 13 58 am](https://user-images.githubusercontent.com/10144/47019054-04ca1c80-d10b-11e8-9826-4a49d81b266f.png)

**Comment by simonmichael** [comment]
Awesome, thanks @Xitian9 !
