### ISSUE TITLE
accounts --anon doesn't anonymise account names declared with account directives

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#901]
```
account a
```
```
$ hledger accounts
a
$ hledger accounts --anon
a
```

**Comment by ony** [comment]
Sounds like we anonymize journal entries only.

**Comment by ony** [comment]
To fix cashflow/balancesheet/etc we need to re-factor our current reporting in favor building default account type mappings from regexps instead of building queries directly.

**Comment by simonmichael** [comment]
That looks nice. Do you think there's any advantage to putting it in hledger-lib ?

**Comment by ony** [comment]
As an advantage, I see that we can define instances close to data types and thus less chances that they will go out of sync.

My initial idea was to use default constructors and if new field appears we just ignore it instead of copying it without anonymization. But this require more effort.
