### ISSUE TITLE
How to keep track of "invoices" via hledger

### ISSUE THREAD

**Issue by tonyxiao** [simonmichael/hledger#906]
I share a house with a bunch of people. I common need I have is to charge other people for shared expenses. So I keep an `Account Receivables:Person X` account for each person.  When charging them however, they want to know the exact list of items they are being charged for. However hledger register would show the history of all of my interactions with that person, including all the money they have owed me before which has been paid off and I currently have to manually do a whole bunch of work to find matching, opposite amounts and filter them out such that I can display only a list of "Unpaid items". I think this is probably the idea of invoice (though I'm not sure). What's the recommended way to do this in hledger?

**Comment by tonyxiao** [comment]
In the case of invoices with hledger, how do you keep track of which specific ones have been paid and which one has not? The register command only gives you the net balance. 

PS. OK, will ping the mailing list.

**Comment by simonmichael** [comment]
Discussion moved to https://groups.google.com/d/topic/hledger/mwazGQ5stOo/discussion
