### ISSUE TITLE
What are the hardware requirements to build hledger?

### ISSUE THREAD

**Issue by dstrelnikov** [simonmichael/hledger#924]
I'm trying to build the latest release with `hledger-install` script on my VPS (1 core, 512 MB RAM).

It fails and it looks like the process of "Populating index cache" has been killed cause of the lack of memory. 

Will 1 GB RAM be enough?

**Comment by simonmichael** [comment]
Sorry, but possibly not. Building some haskell libraries can take more. There are ways to make it work, you can get more help with this on #haskell. Some quick ideas:
- use stack or cabal-install directly, for more control
- install one hledger package at a time
- pass options like -j1 to stack/cabal/ghc to limit concurrent jobs
- pass options like +RTS -M 500m -RTS to GHC to limit its memory usage
- when a stack/cabal build fails, try it again; it may get further next time
- enabling swap can allow larger builds too succeed, but this is usually impractically slow
- temporarily enlarge your VPS's ram if that's an option
- build on a larger machine of similar architecture and copy the executable, if that's an option

**Comment by simonmichael** [comment]
Re your question, http://hledger.org/download.html says "Building all hledger tools and dependencies for the first time could take as much as an hour, 1-2G of free memory, and 1-2G of disk space.". Improvements to this doc are welcome.

**Comment by dstrelnikov** [comment]
@simonmichael, thank you for the answer! I'll try to reduce memory usage with the above options. If it doesn't work, then I'll try to make a swap file. If it will be successful, I'll let you know!
