### ISSUE TITLE
Dangerously greedy reporting on tags

### ISSUE THREAD

**Issue by GSI** [simonmichael/hledger#930]
Given these two bookings:

    2011/11/11  booking (semantically) without a tag
        expenses:cash  USD 1
        assets:foo     USD -1          ; see also accounts_payable:bar

    2011/11/12  booking containing tag
        expenses:cash  USD 1
        assets:foo     USD -1          ; pay:

When we report `hledger r tag:pay` in hledger 1.11.1, both match, since the string "pay" is part of the comment in the first booking. => Unexpected behavior.

**Comment by simonmichael** [comment]
Thanks for the report. The `tags` command shows that the first tag is parsed correctly as  `accounts_payable`. But the `tag:pay` query does an infix match, and succeeds. For robust matching in this case, you need to use a more precise regular expression, like `tag:^pay` or `tag:'\bpay\b'`. It looks like this could be made clearer in the manual.

**Comment by GSI** [comment]
Thanks for your clear explanation!

Personally, I'd have expected the variant with word boundaries to be the default, but, re-evaluating, it does make sense to have consistent behavior across all types of filters.
