### ISSUE TITLE
periodic transaction with date, comment line and amountless posting fails to parse

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#942]
This entry is not parsed correctly:
```
~ 2019/04/01
    ;
    a  1
    b
```
```
$ hledger print --forecast
...
could not balance this transaction - can't have more than one real posting with no amount (remember to put 2 or more spaces before amounts)
2019/04/01
    ; recur: 2019/04/01
    ;
    a               1
    b

```
To reproduce: the date should be within the six months from today, there should be no space after the date, the second line should be a comment line, there should be an amountless posting.

**Comment by adept** [comment]
comment line looks suspicious: if you remove it, everything works

**Comment by simonmichael** [comment]
I know, but it's a perfectly valid comment line

**Comment by adept** [comment]
I think I have a fix via the PR above. Can you please take a look?
