### ISSUE TITLE
--auto and --forecast should work together

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#953]
Transaction modifier rules (--auto) should add postings to forecasted transactions generated by --forecast, but they don't.

**Comment by adept** [comment]
They used to, something has changed ...

Now applyTransactionModifiers happens in hledger-lib, Read.Common.parseAndFinalizeJournal, and --forecast happens in hledger, Cli.Utils.journalTransform (so, after --auto acts).

Seems like moving --forecast transform into hledger-lib should fix this. Any contraindications?

**Comment by simonmichael** [comment]
Nah, what could possibly go wrong!

I've forgotten how these bits fit together and what changed recently. If the order in which these steps are applied changes, that might cause trouble. But if tests pass..

**Comment by adept** [comment]
here is the issue:  the piece of code that figures out default start/end dates for the forecast depends on reportopts, and journal reader only has inputouts at its disposal... I'll think about it.

**Comment by adept** [comment]
Actually, I have an idea. I will give it a try.
