### ISSUE TITLE
hledger register-match - CLI defect?

### ISSUE THREAD

**Issue by schoettl** [simonmichael/hledger#956]
```
$ hledger --version
hledger 1.12.1
$ hledger register-match
please provide one description argument.
$ hledger register-match 'search-term'
hledger: Unhandled argument, none expected: search-term (use -h to see usage)
```

What is wrong? The manual just says, I should specify `DESC`.

Sorry, I cannot test on the very latest version.

**Comment by schoettl** [comment]
I just noticed, the bug is already mentioned by @simonmichael in #621 .

**Comment by simonmichael** [comment]
Thanks for the report.
[code](https://github.com/simonmichael/hledger/blob/master/hledger/Hledger/Cli/Commands/Registermatch.hs)

**Comment by schoettl** [comment]
Oh, I think we can close this issue. The register-match command works in the latest (git) version and also in version 1.13.2 (current version on Arch).

**Comment by simonmichael** [comment]
It looks like the help and/or command line parsing needs tweaking. [QUERY] vs DESC here:
```
register-match [OPTIONS] [QUERY]
  Print the one posting whose transaction description is closest to DESC,
  in the style of the register command. If there are multiple equally good
  matches, it shows the most recent. Query options (options, not
  arguments) can be used to restrict the search space. Helps
  ledger-autosync detect already-seen transactions when importing.
```
And it doesn't seem to accept a query:
```
$ hledger register-match aaa date:jan
please provide one description argument.
```

**Comment by simonmichael** [comment]
I think that's good enough, this is only used for integrating some tool or other (ledger-autosync ? ledger-mode ?)
