### ISSUE TITLE
Balance assertions with prices broken after 1.12

### ISSUE THREAD

**Issue by wad209** [simonmichael/hledger#958]
Balance assertions, such as the ones generated by hledger close, now seem to be broken.

Example ledger file:
```
2019/01/01 opening balances
    assets:brokerage:coinbase:btc                            0.07679373 BTC @ $3,415.37 = 0.07679373 BTC @ $3,415.37
    equity:opening balances
```

This should give the following error:
```
   |
2 |     assets:brokerage:coinbase:btc                            0.07679373 BTC @ $3,415.37 = 0.07679373 BTC @ $3,415.37
   |                                                                                                          ^
unexpected '@'
expecting ';', end of input, or newline
```

Removing the = and everything after fixes the issue.

**Comment by simonmichael** [comment]
This turns out to be breakage from https://github.com/simonmichael/hledger/commit/86a91c514dc337c122aac408f9593f4b1055acda for https://github.com/simonmichael/hledger/issues/824. Good catch! I'll close this and reply on that issue.

**Comment by simonmichael** [comment]
Should be resolved now, by restoring the old behaviour.
