### ISSUE TITLE
wiki Home page ?

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#962]
Hi @schoettl , I recently renamed https://github.com/simonmichael/hledger/wiki/Home to https://github.com/simonmichael/hledger/wiki/Cookbook , and as far as I know that was working fine. Was there a reason you recreated the Home page ?

**Comment by schoettl** [comment]
Hi Simon, that's strange. All I did is:

- Going to the Cookbook (by the link at hledger.org)
- Press the edit button on the side bar to add link to non-existing page on shell completion
- Clicked on the new link and created the page on shell completion.

I did not create another page and I also did not undo any commit in the wiki.

**Comment by simonmichael** [comment]
Ok cool. I'll delete and try to fix whatever caused it.

**Comment by simonmichael** [comment]
PS nice shell completions page.

**Comment by simonmichael** [comment]
github recreates Home.md if missing; I've reverted to that name.
