### ISSUE TITLE
hledger 1.13 does not recognize --output-format csv for register command

### ISSUE THREAD

**Issue by omidmnz** [simonmichael/hledger#967]
I used this feature extensively, with `hledger reg Expenses -V -2 --output-format csv -p "this week"` to parse my expenses of this week, as an example.

After upgrading hledger, I get an error message stating `Unknown flag: --output-format (use -h to see usage)` for the same command. I can still use the flag with `balance`, but `register` seems to be broken.

**Comment by simonmichael** [comment]
Doh! Thanks for the bug report. Fixed in master, bugfix release coming in the next day or so.

**Comment by omidmnz** [comment]
Thank you. I'm gonna go ahead and close this issue since it's fixed in master.

**Comment by simonmichael** [comment]
hledger 1.13.2 released.
