### ISSUE TITLE
Command-line completion asciinema link broken

### ISSUE THREAD

**Issue by simonmichael** [simonmichael/hledger#973]
Hi @schoettl, I did a little cleanup of http://hledger.org/Command-line-completion.html  (aka https://github.com/simonmichael/hledger/wiki/Command-line-completion) and noticed the asciinema link is broken. Maybe you can revive it.

**Comment by schoettl** [comment]
Thanks for the notice. I will upload a new video and check out, if ascinnema stores the video forever when linked to an account.

**Comment by schoettl** [comment]
Fixed in PR #972
