### ISSUE TITLE
CSV parser favors all things "1" and neglects all things "2"

### ISSUE THREAD

**Issue by adept** [simonmichael/hledger#992]
There are several pieces of code in CSV parser that heavily favor things with "1" in them:

1. The amount with cost (2 EUR @@ 1 USD) can only appear as `amount1`. `Amount2` is computed via `costOfMixedAmount` and will therefore never have cost

2. `balance` generates balance assertion for `account1`. There is no way to generate balance assertion for `account2`

If you want balance assertion on one account and amount with cost on the other one, you are out of luck. If you want to give it a try, here is a gist with sample files: https://gist.github.com/adept/f97058809feb7b23b9a6ee8f2c85b356

I propose to improve the situation, at least a bit. I envision doing one of the following:

1. Renaming `balance` to `balance1` and introducing `balance2`, with obvious semantics
2. Introducing `balance1` and `balance2` in addition to existing `balance`
3. Introducing `balance1` and `balance2` (leaving or renaming `balance`) and also introducing `amount2`, `amount2-in`, `amount2-out`

I am currently in favor of "1", mostly because it does not complicate things.

I do not like "2" that much because having `balance` and `balance1` looks weird.

And "3" introduces too many new moving parts. 

Can all in favor say "aye" ?:)

**Comment by simonmichael** [comment]
I would probably favour

4. keep `balance`, introduce `balance2`

We know that CSV rules of this kind don't handle every need, and probably never will; while we chase ever more specific use cases there's a risk of making them overcomplicated. Is this something folks will find useful, or just a nice to have ?

**Comment by adept** [comment]
I wouldn't say that this is a "more specific use case" - this just restores symmetry that is currently broken :)

`balance` and `balance2` look a bit lopsided to me, but we already have `account1` - `account2` vs `amount` (not `amount1`), so it is easy to argue that `balance`-`balance2` would look better if in the future there would be `amount`-`amount2`  ...
